python/py-pytorch/Portfile
=> py-pytorch: Update to version 1.13.1

lang/marst/Portfile
New port: https://www.gnu.org/software/marst
macOS 10.6
Xcode 3.2
Have you
=> marst: new port in lang

math/SISL/Portfile
New port in math: https://github.com/SINTEF-Geometry/SISL
macOS 10.6
Xcode 3.2
Have you
=> SISL: new port in math

textproc/pandoc/Portfile
* Fixes: https://trac.macports.org/ticket/66764
Have you
=> pandoc: Use cabal to build on older systems

audio/audiowmark/Portfile
=> audiowmark: submission

sysutils/coreutils-uutils/Portfile
=> coreutils-uutils: update to 0.0.17

sysutils/mc/Portfile
Closes: https://trac.macports.org/ticket/59868 (outdated ticket)
Have you
=> mc: update to 4.8.29

_resources/port1.0/group/meson-1.0.tcl
Adding via configure.pre_args to avoid https://trac.macports.org/ticket/66761
macOS x.y
=> meson-1.0: Add setup using configure.pre_args

sysutils/vtm/Portfile
=> vtm: update to 0.9.8q

math/igraph/Portfile
=> igraph: update to 0.10.4

devel/cpp-argparse-dev/Portfile
macOS 10.10.5 14F2511 x86_64
Xcode 7.2.1 7C1002
Have you
=> cpp-argparse-dev: update to 1.7.3

net/wireshark4/Portfile
=> wireshark4: update to 4.0.3

lang/crystal/Portfile
=> crystal: update to 1.7.2

devel/datree/Portfile
macOS 12.6 21G115 x86_64
Xcode 13.4.1 13F100
Have you
=> datree: updated to version 1.8.20

fortran/LSQR/Portfile, fortran/conmax/Portfile, fortran/daglib/Portfile, fortran/ddeabm/Portfile, fortran/feq-parse/Portfile, fortran/fmin/Portfile, fortran/fortran-bspline/Portfile, fortran/fortran-nlesolver/Portfile, fortran/fortran-numdiff/Portfile, fortran/pikaia/Portfile, fortran/quadpack/Portfile, fortran/regridpack/Portfile, fortran/slsqp/Portfile, fortran/splpak/Portfile
Some new packages in Fortran.
Xcode 3.2.6
Have you
=> Few new ports in Fortran

math/eiscor/Portfile, math/eiscor/files/patch-jacobwilliams.diff, math/eiscor/files/patch-make.inc.diff, math/eiscor/files/patch-tests.diff
New port: https://github.com/eiscor/eiscor
Xcode 3.2.6
Have you
P. S. I have tested it on 10.6.8 and got the same results as reported here: https://github.com/eiscor/eiscor/issues/94 (few tests fail presently, mostly everything passes).
=> eiscor: new port in math

devel/range-v3/Portfile, devel/range-v3/files/fix_include_dir.diff
Xcode 3.2.6
Have you
```
--->  Testing range-v3
10:ericniebler-range-v3-8c88f71 svacchanda$ cd /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_range-v3/range-v3/work/build/
10:build svacchanda$ /usr/bin/sudo ctest test
Password:
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_range-v3/range-v3/work/build
Start   1: range.v3.test.config
1/255 Test   #1: range.v3.test.config ..............................   Passed    0.02 sec
Start   2: range.v3.test.constexpr_core
2/255 Test   #2: range.v3.test.constexpr_core ......................   Passed    0.02 sec
Start   3: range.v3.test.multiple
3/255 Test   #3: range.v3.test.multiple ............................   Passed    0.02 sec
Start   4: range.v3.test.bug474
4/255 Test   #4: …
```
=> range-v3: update to 0.12.0, add tests

sysutils/vtm/Portfile
=> vtm: update to 0.9.8r

www/neon/Portfile
=> neon: update to 0.32.5

archivers/unrar/Portfile
macOS 10.6.8 10K549 i386
Have you
=> unrar: fix build on OS X <10.7

net/gallery-dl/Portfile
=> gallery-dl: update to 1.24.5

lang/hamlet/Portfile
New port in lang: https://github.com/rossberg/hamlet
macOS 10.6
Xcode 3.2
Have you
=> hamlet: new port in lang, implementation of SML

devel/FACE/Portfile
New port: https://github.com/szaghi/FACE
Xcode 3.2.6
Have you
All tests pass in Rosetta:
```
--->  Testing FACE
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_FACE/FACE/work/build" && ctest test 
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_FACE/FACE/work/build
Start 1: face_test_basic
1/4 Test #1: face_test_basic ..................   Passed    0.05 sec
Start 2: face_test_colors
2/4 Test #2: face_test_colors .................   Passed    0.05 sec
Start 3: face_test_styles
3/4 Test #3: face_test_styles .................   Passed    0.04 sec
Start 4: face_test_ucs4
4/4 Test #4: face_test_ucs4 ...................   Passed    0.04 sec
100% tests passed, 0 tests failed out of 4
Total Test time (real) =   0.24 sec
```
=> FACE: new port in devel

lang/swi-prolog/Portfile
macOS 13.1 22C65 arm64
Have you
=> swi-prolog: Updated to version 9.0.4

lang/swi-prolog-devel/Portfile
macOS 13.1 22C65 arm64
Have you
=> swi-prolog-devel: Updated to version 9.1.4

editors/MacVim/Portfile, editors/vim/Portfile
macOS 13.0.1 22A400 arm64
Have you
=> vim: add python311 variant

devel/64tass/Portfile
macOS 13.1 22C65 arm64
Have you
=> 64tass: Update to 1.58.2974

aqua/LanguageTool/Portfile, aqua/LanguageTool/files/LanguageTool_server_bin
=> LanguageTool: Add server wrappeer script & startupitem

fortran/fortran-nlesolver/Portfile
=> fortran-nlesolver: update to 1.2.0

devel/got/Portfile
=> got: update to version 0.83.

lang/logtalk/Portfile
=> logtalk: update to 3.62.0

devel/pika/Portfile, devel/pika/files/0001-compiler_fence-fix-for-Darwin-PPC.patch
New port: https://github.com/pika-org/pika
Xcode 3.2.6
Have you
I have ran headers tests, 100% pass.
=> pika: new port in devel

devel/mold/Portfile
* add revision line
* update description
* disable livecheck
Have you
=> mold: fix build on macOS <11

x11/homebank/Portfile
* fix master_sites link
Have you
=> homebank: update to 5.6.1

devel/datree/Portfile
=> datree: update to version 1.8.21

net/toxcore/Portfile
New port: https://github.com/TokTok/c-toxcore
Xcode 3.2.6
Have you
=> toxcore: new port in net

net/gpsd/Portfile
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H2, x86_64, Xcode 12.4 12D4e
macOS 11.7.3 20G1116, arm64, Xcode 13.2.1 13C100
macOS 12.6.3 21G419, arm64, Xcode 14.2 14C18
macOS 13.2 22D49, arm64, Xcode …
=> gpsd: update to 3.25, with earlier versions included

math/OpenBLAS/Portfile
=> OpenBLAS: move header files, reduce code with muniversal PG 1.1, add missing build dependency, and set NUM_THREADS

sysutils/gptfdisk/Portfile, sysutils/gptfdisk/files/patch-Makefile.mac.diff
=> gptfdisk: update to 1.0.9

math/matrix-calculator/Portfile
Fixes: https://trac.macports.org/ticket/66799
@ryandesign Thank you for noticing that.
Xcode 3.2.6
Have you
=> matrix-calculator: declare linking to libreadline

security/hydra/Portfile
Fixes: https://trac.macports.org/ticket/66827
Xcode 3.2.6
Have you
=> hydra: fix build on <10.7

aqua/Freecell/Portfile, aqua/Freecell/files/patch-Freecell-undeclared-selectors.diff
Fix failing build e.g. https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/137164
macOS 10.6.8
Have you
=> Freecell: fix build on 10.6

math/eigenmath/Portfile, math/eigenmath/files/patch-Makefile.diff
=> eigenmath: respect MacPorts compiler & linker flags

net/gallery-dl/Portfile
=> gallery-dl: use python 3.11

fortran/carlson-elliptic-integrals/Portfile, fortran/fortran-mach/Portfile, fortran/powellopt/Portfile
New fortran packages.
Xcode 3.2.6
Have you
=> fortran: three new packages

graphics/dcmtk/Portfile
=> dcmtk: Update for website reorg; Remove no-longer-needed patch.

math/blaspp/Portfile
New port: https://github.com/icl-utk-edu/blaspp
Xcode 3.2.6
Have you
P. S. Tests mostly pass on 10.6.8 Rosetta. There are three that fail: https://github.com/icl-utk-edu/blaspp/issues/35
=> blaspp: new port in math

math/eigen3/Portfile
=> eigen3: Rev-bump to capture patch, even if non-event.

lang/lua/Portfile, lang/lua/files/patch-Makefile-53.diff, lang/lua/files/patch-Makefile-54.diff, lang/lua/files/patch-src-Makefile-53.diff, lang/lua/files/patch-src-Makefile-54.diff, lang/lua/files/patch-src-luaconf.h-53.diff, lang/lua/files/patch-src-luaconf.h-54.diff
This PR doesn’t update the main port, since it will break many dependents.
It simply adds a lua54 subport, which some ports need to be updated (e.g. lite-xl). A lua53 subport is provided to help migrate ports that don’t support lua54.
Updating lua to 5.4 has already been tried twice now over two years (https://github.com/macports/macports-ports/pull/8125, https://github.com/macports/macports-ports/pull/16347). Hopefully third time's the charm ;)
See: https://trac.macports.org/ticket/66089
macOS 12.4 21F79 arm64
Command Line Tools 13.4.0.0.1.1651278267
Have you
=> lua: add lua53 and lua54 subports

databases/redis/Portfile
=> redis: update to 7.0.8

math/psblas3/Portfile, math/psblas3/files/patch-install-dirs.diff
New port: https://github.com/sfilippone/psblas3
Xcode 3.2.6
Have you
=> psblas3: new port in math

devel/onetbb/Portfile
=> onetbb: update to 2021.8.0

games/fortune-mod/Portfile
=> fortune-mod: update to 3.14.1

devel/kazmath/Portfile
New port: https://github.com/Kazade/kazmath
Xcode 3.2.6
Have you
=> kazmath: new port in devel

net/openssh/Portfile
=> openssh: update to version 9.2p1.

devel/abseil/Portfile, devel/abseil/files/patch-remove-Xarch-from-pkg-config.diff, devel/apache-arrow/Portfile, devel/grpc/Portfile
See https://github.com/macports/macports-ports/commit/37d57c306d21bef2074356d24f89103e290ad1de and https://github.com/abseil/abseil-cpp/issues/1168
Commits:
- abseil: Fix pkg-config by removing -Xarch_* cflags
- grpc: apach-arrow: Revbump after fix in abseil
Have you
=> abseil: Fix pkg-config by removing -Xarch_* cflags

sysutils/vtm/Portfile
=> vtm: update to 0.9.8t

lang/odin/Portfile
=> odin: update to 0.2023.02

games/fheroes2/Portfile
=> fheroes2: update to 1.0.1

databases/barman/Portfile
=> barman: update to 3.4.0

math/add/Portfile
=> add: update to 20230205

graphics/opencv3-devel/Portfile
closes: https://trac.macports.org/ticket/66861
=> opencv3-devel: fix worksrcdir

lang/elixir/Portfile
Mere update.
Xcode 3.2.6
Have you
=> elixir: update to 1.14.3

devel/dprint/Portfile
=> dprint: upgrade to 0.34.4

science/dspl/Portfile, science/dspl/files/0001-Fixes-for-Macports.patch
New port in science: http://en.dsplib.org
Xcode 3.2.6
Have you
=> dspl: new port in science

devel/leiningen/Portfile
=> leiningen: update to 2.10.0

x11/homebank/Portfile
=> homebank: update to 5.6.2

cross/dtc/Portfile
macOS 13.2 22D49 x86_64
Have you
=> dtc: update to 1.7.0

R/R-Hmisc/Portfile, R/R-RcppArmadillo/Portfile, R/R-blavaan/Portfile, R/R-ggplot2/Portfile, R/R-gmp/Portfile, R/R-lavaan/Portfile, R/R-mclogit/Portfile, R/R-memisc/Portfile, R/R-projpred/Portfile, R/R-readr/Portfile, R/R-readxl/Portfile, R/R-report/Portfile, R/R-testthat/Portfile
Besides versions and checksums, new dependencies are added for a couple of ports.
macOS 10.6.8
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
P. S. Tests were run for those packages where tests are added. (We cannot support testing for each and every R package due to dependencies requirements.)
=> R packages: update recently updated ones

lang/swi-prolog-devel/Portfile
macOS 13.1 22C65 arm64
Have you
=> swi-prolog-devel: Updated to version 9.1.5

math/OpenBLAS/Portfile
=> OpenBLAS: fix broken links to header files

audio/FAudio/Portfile
=> FAudio: update to 23.02

science/madness/Portfile, science/madness/files/0001-CMakeLists-support-ppc.patch, science/madness/files/0002-Do-not-build-chem-it-is-broken.patch, science/madness/files/0003-Do-not-build-apps-they-depend-on-chem.patch
New port: https://github.com/m-a-d-n-e-s-s/madness
Xcode 3.2.6
Have you
=> madness: new port in science

lang/smlnj/Portfile, lang/smlnj/files/patch-_arch.diff
Fixes: https://trac.macports.org/ticket/66745
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> smlnj: fix the build on PPC

office/taskopen/Portfile, office/taskopen/files/patch-fix-Makefile.diff
taskopen — Tool for taking notes and open urls with taskwarrior
macOS 13.2 22D49 x86_64
Have you
=> taskopen: New port

net/coeurl/Portfile, net/mtxclient/Portfile, net/nheko/Portfile
=> nheko: Update to 0.11.1 (mtxclient: Update to 0.9.1, coeurl: Update to 0.3.0)

lang/zig/Portfile
=> Remove maintainer

math/sundials6/Portfile
Closes: https://trac.macports.org/ticket/66633
Simple update.
Xcode 3.2.6
Have you
=> sundials6: update to 6.5.0

math/AlphaSparse/Portfile, math/AlphaSparse/files/0001-Support-PPC-in-Makefile.patch, math/AlphaSparse/files/0002-Makefile-cleanup.patch, math/AlphaSparse/files/0003-Fix-for-missing-COMPAR_FN_T.patch, math/AlphaSparse/files/0004-Use-stdlib.h-instead-of-malloc.h.patch, math/AlphaSparse/files/0005-Remove-some-unneeded-spaces.patch, math/AlphaSparse/files/0006-Makefile-for-x86-test-fix-lib-name-to-libalpha_spbla.patch, math/AlphaSparse/files/0007-src-Makefile-there-is-no-tuning-dir.patch, math/AlphaSparse/files/0008-Makefile-fix-dylib-target-for-macOS.patch, math/AlphaSparse/files/0009-Fixes-for-Macports.patch, math/AlphaSparse/files/0010-Makefile.tail-split-lib-target-to-fix-ar-error.patch, math/AlphaSparse/files/0011-Hack-for-Rosetta.patch
Let us see if this builds :)
https://github.com/AlphaSparse/AlphaSparse
Xcode 3.2.6
Have you
=> AlphaSparse: new port in math

devel/datree/Portfile
macOS 12.6 21G115 x86_64
Xcode 13.4.1 13F100
Have you
=> datree: updated to version 1.8.24

R/R-AsioHeaders/Portfile, R/R-BayesGOF/Portfile, R/R-Bolstad/Portfile, R/R-Bolstad2/Portfile, R/R-Deriv/Portfile, R/R-R.methodsS3/Portfile, R/R-R.oo/Portfile, R/R-R.utils/Portfile, R/R-VGAM/Portfile, R/R-VGAMdata/Portfile, R/R-VGAMextra/Portfile, R/R-cmdstanr/Portfile, R/R-cowplot/Portfile, R/R-crsmeta/Portfile, R/R-dfidx/Portfile, R/R-dqrng/Portfile, R/R-dynamite/Portfile, R/R-effsize/Portfile, R/R-fitteR/Portfile, R/R-gganimate/Portfile, R/R-gmvarkit/Portfile, R/R-hunspell/Portfile, R/R-kde1d/Portfile, R/R-locfdr/Portfile, R/R-pkgmaker/Portfile, R/R-sitmo/Portfile, R/R-skellam/Portfile, R/R-spelling/Portfile, R/R-tablexlsx/Portfile
New ports + a couple of updates.
A second batch will be later today, all do not fit into ~30.
Xcode 3.2.6
Have you
=> R: some new packages

sysutils/vtm/Portfile
=> vtm: update to 0.9.8u

R/R-RcppArmadillo/Portfile, R/R-RcppEigen/Portfile, R/R-RcppNumerical/Portfile, R/R-Rfast/Portfile, R/R-Rfast2/Portfile, R/R-ape/Portfile, R/R-httpuv/Portfile, R/R-prettydoc/Portfile, R/R-reticulate/Portfile, R/R-slam/Portfile
Updates for `ape`, `httpuv`, `Rfast`, `Rfast2`.
Add support for tests to `RcppArmadillo`, `RcppEigen` and `RcppNumerical`. Three new ports – dependencies for those.
Xcode 3.2.6
Have you
=> R: update recently updated packages; several Rcpp* ports: support tests

math/cotila/Portfile
New port, header-only library: https://github.com/calebzulawski/cotila
Xcode 3.2.6
Have you
```
--->  Testing cotila
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_math_cotila/cotila/work/build" && /usr/bin/make test 
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_math_cotila/cotila/work/build
Start 1: cotila_test
1/1 Test #1: cotila_test ......................   Passed    0.04 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) =   0.07 sec
```
=> cotila: new port in math

devel/ghidra/Portfile
=> ghidra: update to 10.2.3

math/z3/Portfile
=> z3: update to 4.12.1; add py311

gis/osm2pgsql/Portfile
[Changelog](https://github.com/openstreetmap/osm2pgsql/releases)
macOS 12.4
Xcode 13.4.1
Have you
=> osm2pgsql: update to 1.8.1

x11/luit/Portfile
=> luit: update to 2.0.20230201

devel/reflex/Portfile
=> reflex: update to 2.5.4-20230206

sysutils/vtm/Portfile
=> vtm: update to 0.9.8v

emulators/uxn/Portfile
=> uxn: update to 20230217

devel/libdsk/Portfile, devel/libdsk/files/dynamic_lookup-11.diff
=> libdsk: submission

devel/strip7/Portfile, devel/strip7/files/PR-12400897.patch, devel/strip7/files/PR-37520.patch, devel/strip7/files/cctools-829-lto.patch, devel/strip7/files/cctools-839-static-dis_info.patch, devel/strip7/files/cctools-862-prunetrie.patch, devel/strip7/files/cctools-895-OFILE_LLVM_BITCODE.patch, devel/strip7/files/cctools-895-big_endian.patch, devel/strip7/files/not-clang.patch, devel/strip7/files/patch-strip-ignore-zero-nsects.diff, devel/strip7/files/snowleopard-strnlen.patch, www/tenfourfox/Portfile, www/tenfourfox/files/patch-ots-stdlog-fix.diff, www/tenfourfox/files/patch-tenfourfox-use-old-which.diff
Perhaps a well-known browser: https://github.com/classilla/tenfourfox
This port is only for PPC.
P. S. If anyone interested to support Intel version, you are welcome. I asked earlier on Trac, but no one expressed interest: https://trac.macports.org/ticket/66185
macOS 10.6
Xcode 3.2
Have you
=> tenfourfox: new port, web-browser for PPC

net/openvpn2/Portfile
Max OS X 10.5.8 9L31a ppc64
Xcode 3.1.4 9M2809
Have you
=> openvpn2: update to 2.6.0

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.10.1

python/py-tensorflow-metal/Portfile
=> py-tensorflow-metal: Update to version 0.7.1

security/bitwarden-cli/Portfile
=> bitwarden-cli: Update to version 2023.2.0

science/OpenCoarrays/Portfile
=> opencoarrays: handle stealth update and fetch from releases

lang/fortran-stdlib/Portfile, lang/fortran-stdlib/files/0001-Check-for-equality-between-Fortran-and-C-logicals.patch
New port: https://github.com/fortran-lang/stdlib
macOS 10.6
Xcode 3.2
Have you
=> fortran-stdlib: new port

devel/got/Portfile
=> got: update to version 0.84.

editors/moe/Portfile
=> moe: update to 1.13

R/R-igraph/Portfile
=> R-igraph: update to 1.4.1

net/snac/Portfile
* closes https://trac.macports.org/ticket/66989
Have you
=> snac: update to 2.23.

devel/got/Portfile
=> got: update to 0.84.1.

devel/legacy-support/Portfile
=> legacy-support: use makefile & muniversal 1.1 PGs

R/R-DiceDesign/Portfile, R/R-MCMCglmm/Portfile, R/R-adaptMCMC/Portfile, R/R-brms/Portfile, R/R-brms/files/patch-no-spdep.diff, R/R-dials/Portfile, R/R-flexsurv/Portfile, R/R-infer/Portfile, R/R-intervals/Portfile, R/R-kknn/Portfile, R/R-msm/Portfile, R/R-mstate/Portfile, R/R-pammtools/Portfile, R/R-pec/Portfile, R/R-polspline/Portfile, R/R-polspline/files/patch-cflags.diff, R/R-ramcmc/Portfile, R/R-relsurv/Portfile, R/R-rgl/Portfile, R/R-rms/Portfile, R/R-rmsb/Portfile, R/R-rstpm2/Portfile, R/R-rtdists/Portfile, R/R-selectiveInference/Portfile, R/R-sparsevb/Portfile, R/R-tidymodels/Portfile, R/R-tsutils/Portfile, R/R-tune/Portfile, R/R-workflows/Portfile, R/R-workflowsets/Portfile
Here `tidymodels` meta-package is completed; `brms` gets support for tests (that pulled in a lot of ports).
UPD2. Error with Rosetta2 build fixed, good to merge.
Xcode 3.2.6
Have you
=> R: new packages (VII)

devel/libvterm/Portfile
=> libvterm: update to 0.3.1

devel/jreleaser/Portfile
macOS 11.6.5 20G527 x86_64
Have you
=> jreleaser: update to v1.5.0

devel/meson/Portfile
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> meson: update to 1.0.0

gnome/gnome-internet-radio-locator/Portfile
gnome-internet-radio-locator: update to 12.7.0
Have you
=> gnome-internet-radio-locator: update to 12.7.0

lang/logtalk/Portfile
=> logtalk: update to 3.63.0

www/buku/Portfile
buku: update to 4.8
macOS 12.6.2 21G320 arm64
Have you
=> buku: update to 4.8

R/R-RSQLite/Portfile, R/R-bit/Portfile, R/R-bit64/Portfile, R/R-collapse/Portfile, R/R-crayon/Portfile, R/R-devtools/Portfile, R/R-fansi/Portfile, R/R-farver/Portfile, R/R-fastverse/Portfile, R/R-foghorn/Portfile, R/R-forecast/Portfile, R/R-globals/Portfile, R/R-gmailr/Portfile, R/R-kit/Portfile, R/R-lava/Portfile, R/R-listenv/Portfile, R/R-mondate/Portfile, R/R-mvQuad/Portfile, R/R-renv/Portfile, R/R-roxygen2/Portfile, R/R-rsconnect/Portfile, R/R-unitizer/Portfile, R/R-vctrs/Portfile, R/R-withr/Portfile, R/R-xfun/Portfile, R/R-xfun/files/patch-no-magick.diff, R/R-zeallot/Portfile, R/R-zoo/Portfile
Several new ports are dependencies for testing.
Xcode 3.2.6
Have you
=> R: update recently updated packages, add support for tests

devel/cppcheck/Portfile
=> cppcheck: Switch to Python 3.11

sysutils/opendoas/Portfile
=> opendoas: update to 6.8.2

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.1.7

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff
=> py-awscli2: update to 2.11.0

R/R-admisc/Portfile, R/R-blavaan/Portfile, R/R-pomp/Portfile, R/R-renv/Portfile, R/R-sfheaders/Portfile, R/R-spData/Portfile
Into this PR I have put trivial updates with no extra changes.
Xcode 3.2.6
Have you
=> R: update recently update packages

devel/fossil/Portfile
https://fossil-scm.org/home/doc/trunk/www/changes.wiki#v2_21
macOS 12.6.3
Command Line Tools 14.1
Have you
=> fossil: update to 2.21

lang/ruby-devel/Portfile
=> ruby-devel: update to current upstream

R/R-fBasics/Portfile, R/R-sets/Portfile, R/R-styler/Portfile, R/R-triebeard/Portfile
Trivial updates.
Xcode 3.2.6
Have you
=> R: update a few recently updated packages

net/snac/Portfile
=> snac: update to 2.24.

sysutils/kubectl/Portfile
Closes: https://trac.macports.org/ticket/66987
Have you
=> kubectl_select: keep completions directory

dotnet/dotnet-sdk-3.1/Portfile, dotnet/dotnet-sdk-6/Portfile, dotnet/dotnet-sdk-7/Portfile, dotnet/dotnet-sdk-devel/Portfile
Closes: https://trac.macports.org/ticket/67048
Have you
=> dotnet-sdk: include default project templates

lang/MoarVM/Portfile, lang/nqp/Portfile, lang/rakudo/Portfile
Simple update, no changes.
Xcode 3.2.6
Have you
=> rakudo and friends: update to 2023.02

science/mpi-doc/Portfile, science/mpich/Portfile
=> mpich/mpi-doc: 4.1.1

lang/a60/Portfile, lang/algol-68rs/Portfile, lang/algol-68rs/files/Fixes-for-PPC-and-Macports.patch, lang/algol68g/Portfile, lang/marst/Portfile
New port: https://github.com/coolbikerdad/Algol-68RS-Source
Plus non-functional minor changes to other algol ports: use explicit subcategory, like for haskell (it is nowhere obvious from name that `marst` is an Algol interpreter, for example), claim maintainership over nomaintainer Algol ports.
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> algol-68rs: new port in lang

python/py-pyproject_hooks/Portfile, python/py-testpath/Portfile
Future dependency of poetry
Have you
=> py-pyproject_hooks: new port

R/R-RcppAlgos/Portfile, R/R-RcppArray/Portfile, R/R-RcppBDT/Portfile, R/R-RcppBigIntAlgos/Portfile, R/R-RcppDist/Portfile, R/R-RcppDist/files/patch-openmp.diff, R/R-RcppDynProg/Portfile, R/R-RcppEigenAD/Portfile, R/R-RcppGSL/Portfile, R/R-RcppXts/Portfile, R/R-functional/Portfile, R/R-officer/Portfile
A few new packages; added support for tests for some other. `R-functional` is a dependency for `R-RcppEigenAD`.
P. S. `R-officer` is an unrelated update: it was updated today but after the big PR merged :)
Xcode 3.2.6
Have you
=> R: small update with Rcpp* ports

devel/got/Portfile
=> got: update to 0.85.

net/zenmap/Portfile
=> zenmap: update to 7.93

_resources/port1.0/group/golang-1.0.tcl, devel/go-licenses/Portfile, textproc/vale/Portfile
=> vale: Update to 2.24.0, go-licenses: Update to 1.6.0

_resources/port1.0/group/luarocks-1.1.tcl, _resources/port1.0/group/luarocks_org-1.0.tcl, lua/lua-fennel/Portfile, lua/lua-fennel/files/lua54-fennel, lua/lua-luarocks/Portfile, lua/lua-luarocks/files/lua51-luarocks, lua/lua-luarocks/files/lua52-luarocks, lua/lua-luarocks/files/lua53-luarocks, lua/lua-luarocks/files/patch-src_luarocks_core_cfg.diff, lua/lua-mpack/Portfile, lua/lua-mpack/files/patch-c_std.diff
=> Revamp Luarocks

devel/jreleaser/Portfile
macOS 11.6.5 20G527 x86_64
Have you
=> jreleaser: update to version 1.5.1

devel/raja/Portfile, devel/raja/files/patch-throw-away-desul.diff
New port: https://github.com/LLNL/RAJA
Xcode 3.2.6
Have you
=> raja: new port in devel

sysutils/cpmtools/Portfile
=> cpmtools: update to 2.24

math/gnuplot/Portfile
=> gnuplot: use lua PG

games/fheroes2/Portfile
=> fheroes2: update to 1.0.2

ocaml/ocaml-dune/Portfile
Long due update. Now everything installs correctly without earlier trickery.
macOS 10.6 PPC
Xcode 3.2
Have you
=> ocaml-dune: update to 3.7.0

net/snac/Portfile
=> snac: update to 2.25.

science/plumed/Portfile
=> plumed: update to v2.8.2

textproc/highlight/Portfile
=> highlight: use lua PG and makefile PG features

R/R-Hmisc/Portfile, R/R-Rchoice/Portfile, R/R-VGAM/Portfile, R/R-ape/Portfile, R/R-broom/Portfile, R/R-deSolve/Portfile, R/R-emmeans/Portfile, R/R-gdtools/Portfile, R/R-ipred/Portfile, R/R-jose/Portfile, R/R-multcomp/Portfile, R/R-openssl/Portfile, R/R-pkgKitten/Portfile, R/R-qreport/Portfile, R/R-rstantools/Portfile, R/R-stochvol/Portfile, R/R-testthat/Portfile
Updates, support for tests.
Xcode 3.2.6
Have you
=> R: update recently updated packages

net/libtorrent-rasterbar/Portfile
=> libtorrent-rasterbar: add python311 variant

editors/MacVim/Portfile, editors/MacVim/files/patch-python.diff, editors/MacVim/files/patch-python3.diff, editors/MacVim/files/patch-remove-updater.diff, editors/MacVim/files/patch-tcl.diff, editors/vim/Portfile, editors/vim/files/patch-python.diff, editors/vim/files/patch-python3.diff, editors/vim/files/patch-tcl.diff
=> MacVim, vim: update & use lua PG

devel/datree/Portfile
=> datree: update to version 1.8.41

devel/datree/Portfile
=> datree: update to version 1.8.42

lang/solidity/Portfile, lang/solidity/files/fmtlib.cmake, lang/solidity/files/jsoncpp.cmake, lang/solidity/files/patch-cmake_range-v3.cmake.diff, lang/solidity/files/patch-libsolutil_JSON.cpp.diff
The smart contract programming language.
Xcode 14.2  14C18
Have you
=> solidity: new port in lang

graphics/edje/Portfile
=> edje: use lua PG (and other tweaks)

lua/lua-luacheck/Portfile, lua/lua-luacheck/files/lua54-luacheck
=> lua-luacheck: update to 1.1.0 & use luarocks_org PG

lua/lua-readline/Portfile
=> lua-readline: update to 3.2 & use luarocks_org PG

net/prosody/Portfile, net/prosody/files/patch-config.diff
use openssl and lua PGs
macOS x.y
Have you
=> prosody: update 0.11.2->0.12.3

print/a2ps/Portfile
Update a2ps to the latest stable release
Have you
=> a2ps: update to 4.15

R/R-Amelia/Portfile, R/R-BGVAR/Portfile, R/R-HDInterval/Portfile, R/R-attempt/Portfile, R/R-brio/Portfile, R/R-brnn/Portfile, R/R-calculus/Portfile, R/R-cranlogs/Portfile, R/R-descr/Portfile, R/R-diffobj/Portfile, R/R-dm/Portfile, R/R-eyelinker/Portfile, R/R-forge/Portfile, R/R-getPass/Portfile, R/R-git2r/Portfile, R/R-lgarch/Portfile, R/R-pema/Portfile, R/R-progress/Portfile, R/R-rematch2/Portfile, R/R-renv/Portfile, R/R-rstanemax/Portfile, R/R-sn/Portfile, R/R-tzdb/Portfile, R/R-vdiffr/Portfile, R/R-viridisLite/Portfile, R/R-waldo/Portfile
New ports, few updates, more support for tests.
Xcode 3.2.6
Have you
=> R: some new packages, more support for tests

net/openssh/Portfile, net/openssh/files/launchd.patch
=> openssh: update to 9.3p1

_resources/port1.0/group/rust-1.0.tcl
In particular, --remap-path-prefix prevents
build information from bing included installed binaries.
macOS x.y
Have you
=> rust PG: add ability to add flags to rust compiler

devel/cargo/Portfile
=> cargo: update version 0.68.0->0.69.0

python/py-graph-tool/Portfile
=> py-graph-tool: Update to version 2.46

www/wordpress/Portfile
https://wordpress.org/documentation/wordpress-version/version-5-5-11/
**Untested**
Have you
=> wordpress: update to 5.5.11

www/drupal7/Portfile
https://www.drupal.org/project/drupal/releases/7.95
https://www.drupal.org/project/drupal/releases/7.94
https://www.drupal.org/project/drupal/releases/7.93
https://www.drupal.org/project/drupal/releases/7.92
**Untested**
Have you
=> drupal7: update to 7.95

devel/luamake/Portfile, devel/luamake/files/Makefile, devel/luamake/files/patch-macos.ninja.diff, lua/lua-language-server/Portfile
=> lua-language-server: build with system luamake

science/ismrmrd/Portfile
=> ismrmrd: 1.13.4

devel/clojure-lsp/Portfile
=> clojure-lsp: update to 2023.02.27-13.12.12

R/R-BayesRGMM/Portfile, R/R-BiocParallel/Portfile, R/R-ComplexHeatmap/Portfile, R/R-IRanges/Portfile, R/R-RcppML/Portfile, R/R-aods3/Portfile, R/R-batchmeans/Portfile, R/R-circlize/Portfile, R/R-classGraph/Portfile, R/R-dcanr/Portfile, R/R-docore/Portfile, R/R-elhmc/Portfile, R/R-emplik/Portfile, R/R-frbs/Portfile, R/R-gbutils/Portfile, R/R-goftest/Portfile, R/R-olsrr/Portfile, R/R-vistributions/Portfile
New ports.
Xcode 3.2.6
Have you
=> R: some more new packages

science/jags/Portfile
=> jags: update to 4.3.2

net/gallery-dl/Portfile
=> gallery-dl: update to 1.25.0

science/gildas/Portfile
macOS 13.0.1 22A400 arm64
Have you
=> Gildas: update to 202303b

devel/fatal/Portfile
New port, header-only library: https://github.com/facebook/fatal
Xcode 3.2.6
Have you
=> fatal: new port in devel

sysutils/cpmtools/Portfile
=> cpmtools: fix checksums

R/R-glmnet/Portfile, R/R-htmltools/Portfile, R/R-parallelly/Portfile, R/R-vars/Portfile
Simple updates.
Xcode 3.2.6
Have you
=> R: update packages updated today

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.1.8

R/R-fido/Portfile, R/R-inline/Portfile, R/R-intervals/Portfile, R/R-shinytest/Portfile, R/R-xfun/Portfile, R/R-xfun/files/patch-no-magick.diff
=> R: few updates to existing packages

aqua/alacritty/Portfile
=> alacritty: update to version 0.12.0

x11/homebank/Portfile
=> homebank: update to 5.6.3

net/gallery-dl/Portfile
=> gallery-dl: update to 1.25.1

finance/ledger/Portfile
* Update version to 3.3.1
* Add gpgme variant to support encrypted journals
- [ x ] enhancement
Have you
- [ x ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x ] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x ] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ x ] checked your Portfile with `port lint --nitpick`?
- [ x ] tried existing tests with `sudo port test`?
- [ x ] tried a full install with `sudo port -vst install`?
- [ x ] tested basic functionality of all binary files?
- [ x ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) …
=> ledger: update to version 3.3.1

lang/logtalk/Portfile
=> logtalk: update to 3.64.0

python/py-u-msgpack-python/Portfile
=> py-u-msgpack-python: add python311 subport

devel/libatomic_ops/Portfile
=> libatomic_ops: update to 7.8.0

security/bitwarden-cli/Portfile
=> bitwarden-cli: Update to version 2023.3.0

devel/wolfssl/Portfile
macOS 10.15.7 19H1323 x86_64
Have you
=> wolfssl: update to version 5.6.0

databases/msodbcsql17/Portfile, databases/mssql-tools/Portfile
Add checksums per architecture as noted in #18107
macOS 12.6.1 21G217 x86_64
Have you
=> msodbcsql17: checksums per arch

devel/datree/Portfile
=> datree: update to version 1.8.47

python/py-userpath/Portfile
=> py-userpath: update to 1.8.0, add py311 subport

python/pipx/Portfile
macOS 12.6.4 21G526 x86_64
Have you
=> pipx: Add python311 variant

R/R-CMLS/Portfile, R/R-GameTheory/Portfile, R/R-GameTheoryAllocation/Portfile, R/R-SetMethods/Portfile, R/R-ao/Portfile, R/R-askgpt/Portfile, R/R-coopProductGame/Portfile, R/R-cpfa/Portfile, R/R-fmsb/Portfile, R/R-fso/Portfile, R/R-ggiraph/Portfile, R/R-ggiraph/files/patch-no-sf.diff, R/R-glpkAPI/Portfile, R/R-ineq/Portfile, R/R-kappalab/Portfile, R/R-listviewer/Portfile, R/R-lpSolveAPI/Portfile, R/R-matrixdist/Portfile, R/R-mockthat/Portfile, R/R-multiview/Portfile, R/R-multiway/Portfile, R/R-packcircles/Portfile, R/R-rvcheck/Portfile, R/R-tglkmeans/Portfile, R/R-tgstat/Portfile, R/R-tgstat/files/patch-fix-includes.diff, R/R-widgetframe/Portfile, R/R-yulab.utils/Portfile
New ports.
Xcode 3.2.6
Have you
=> R: new packages

lang/fortran-stdlib/Portfile
Simple update.
Xcode 3.2.6
Have you
=> fortran-stdlib: update to 2023.03.08

devel/CLI11/Portfile
Update, set cxx_standard to 2011 (required by CMakeLists).
Xcode 3.2.6
Have you
=> CLI11: update to 2.3.2

science/liblsl/Portfile
macOS 12.6.1 21G217 arm64
Have you
=> liblsl: New port

R/R-BiocCheck/Portfile, R/R-BiocIO/Portfile, R/R-Biostrings/Portfile, R/R-CDM/Portfile, R/R-CodeDepends/Portfile, R/R-GDINA/Portfile, R/R-GenomeInfoDb/Portfile, R/R-GenomeInfoDbData/Portfile, R/R-KEGGREST/Portfile, R/R-Kendall/Portfile, R/R-SnowballC/Portfile, R/R-TAM/Portfile, R/R-antiword/Portfile, R/R-cdmTools/Portfile, R/R-datetimeutils/Portfile, R/R-dcm2/Portfile, R/R-dfms/Portfile, R/R-flashClust/Portfile, R/R-highlight/Portfile, R/R-lavaan.survey/Portfile, R/R-measr/Portfile, R/R-miceadds/Portfile, R/R-modules/Portfile, R/R-odr/Portfile, R/R-pbv/Portfile, R/R-sirt/Portfile, R/R-vosonSML/Portfile
New ports.
Xcode 3.2.6
Have you
=> R: new packages (II)

devel/datree/Portfile
=> datree: update to version 1.8.51

graphics/mupdf/Portfile, python/py-mupdf/Portfile, python/py-mupdf/files/setup.py.diff
=> py-mupdf: new port (PyMuPDF)

devel/datree/Portfile
=> datree: update to version 1.8.63

gnome/grilo-plugins/Portfile
=> grilo-plugins: use lua PG

net/snac/Portfile
=> snac: update to 2.26.

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff
Tested basic API functionality locally
Have you
=> py-awscli2: update to 2.11.9

python/poetry/Portfile
=> poetry: update to 1.4.2

databases/pgbadger/Portfile
=> pgbadger: update to 12.1

math/hiop/Portfile
Simple update.
macOS 10.6
Xcode 3.2
Have you
=> hiop: update to 0.7.2

science/gnss-sdr/Portfile, science/volk-gnss-sdr/Portfile
macOS 11.7.4 20G1120 x86_64
Xcode 12.2 12B45b
Have you
=> [volk-]gnss-sdr: update release to 0.0.18 and devel to 20230407-306c566d

math/adept2/Portfile
=> adept2: update to 2023.03.30

editors/neovim/Portfile
Add @judaew to list of maintainers
=> neovim: add @judaew to list of maintainers

math/fxt/Portfile, math/fxt/files/patch-makefile.diff
=> fxt: update to 2023.03.23

R/R-igraphdata/Portfile
- set R.author so it's GitHub-compatible
- disable testing, since there are no tests
- correct license
macOS x.y
Have you
=> R-igraphdata: various improvements

net/libretroshare/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> libretroshare: update to upstream master

science/madness/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> madness: update to upstream master

lang/llvm-10/Portfile, lang/llvm-11/Portfile, lang/llvm-12/Portfile, lang/llvm-13/Portfile, lang/llvm-14/Portfile, lang/llvm-15/Portfile, lang/llvm-16/Portfile, lang/llvm-5.0/Portfile, lang/llvm-6.0/Portfile, lang/llvm-7.0/Portfile, lang/llvm-8.0/Portfile, lang/llvm-9.0/Portfile, lang/llvm-devel/Portfile
=> clang-*: default to +libstdcxx only when needed

graphics/libopenraw/Portfile
=> libopenraw: update to 0.3.4 & use cargo_fetch PG

science/proxmark3-iceman/Portfile
macOS 13.3 22E252 x86_64
Have you
fyi; trace mode is borked on ventura still so `-vs` is used instead of `-vst`
=> proxmark3-iceman: update to v4.16191

devel/mimalloc/Portfile
macOS 12.6.4 21G526 x86_64
Have you
=> mimalloc: update to 2.1.1

games/fheroes2/Portfile
=> fheroes2: update to 1.0.3

devel/datree/Portfile
=> datree: update to version 1.8.64

gnome/mm-common/Portfile
- Correct the license from GPL-2 to GPL-2+. 
All copyright notices I could find at https://gitlab.gnome.org/GNOME/mm-common/ state something like:
>mm-common is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published
> by the Free Software Foundation, either version 2 of the License,
> **or (at your option) any later version.**
For example, see https://gitlab.gnome.org/GNOME/mm-common/-/blob/master/macros/mm-common.m4.in
Debian states that the licenses relevant for this software are GPL-2+ and LGPL-2.1+, see https://metadata.ftp-master.debian.org/changelogs//main/m/mm-common/mm-common_1.0.5-1_copyright Presumably Debian did a thorough survey of all files in this software and their licenses.
macOS x.y
Xcode x.y / Command Line …
=> mm-common: correct license

R/R-labelled/Portfile, R/R-lavaSearch2/Portfile, R/R-parsnip/Portfile, R/R-tune/Portfile, R/R-volesti/Portfile
Few updates.
Xcode 3.2.6
Have you
=> R: update newly updated packages

shells/tcsh/Portfile
=> tcsh: update to 6.24.9

science/memesuite/Portfile
Upgrade to MEME Suite Release 5.5.2
- [ x] enhancement
Xcode 12.3 12C33
Have you
- [x ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x ] checked your Portfile with `port lint --nitpick`?
- [ x] tried existing tests with `sudo port test`?
- [ x] tried a full install with `sudo port -vst install`?
- [ x] tested basic functionality of all binary files?
- [x ] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?
=> Updated to MEME Suite 5.5.2

devel/thrift/Portfile, perl/p5-thrift/Portfile, python/py-thrift/Portfile
As suggested by @reneeotten – I change the PR to update rather than fixing an old version.
Xcode 3.2.6
Have you
=> thrift, py-thrift, p5-thrift: update to 0.18.1

net/snac/Portfile, net/snac/files/Makefile.patch
=> snac: update to 2.27.

editors/frescobaldi/Portfile
=> frescobaldi: update to 3.3.0

R/R-Rmpi/Portfile, R/R-doMPI/Portfile, R/R-pbdMPI/Portfile
_Let’s see if this nightmare builds._
Keeping this separate from everything else.
Xcode 3.2.6
Have you
=> R: MPI packages

devel/n/Portfile
=> n: update to 9.2

sysutils/nnn/Portfile
[Changelog](https://github.com/jarun/nnn/releases/tag/v4.8)
macOS 12.4
Xcode 13.4.1
Have you
=> nnn: update to 4.8

games/fortune-mod/Portfile
macOS 12.6.4 21G526 x86_64
Have you
=> fortune-mod: update to 3.18.0

devel/datree/Portfile
=> datree: update to 1.8.65

R/R-MSCMT/Portfile, R/R-baizer/Portfile, R/R-lmeInfo/Portfile, R/R-polspline/Portfile, R/R-polspline/files/patch-cflags.diff, R/R-pomp/Portfile, R/R-samplingR/Portfile, R/R-zip/Portfile
macOS 10.6.8
Xcode 3.2.6
Have you
=> R: updates and a fix for R-polspline

devel/cpp-argparse-dev/Portfile
macOS 10.10.5 14F2511 x86_64
Xcode 7.2.1 7C1002
Have you
=> cpp-argparse-dev: update to 1.7.5

net/wireshark4/Portfile
=> wireshark4: update to 4.0.5

R/R-BayesQVGEL/Portfile, R/R-GB2/Portfile, R/R-MRFcov/Portfile, R/R-MaximinInfer/Portfile, R/R-Pareto/Portfile, R/R-RSC/Portfile, R/R-SIHR/Portfile, R/R-TH.data/Portfile, R/R-TMB/Portfile, R/R-bellreg/Portfile, R/R-conformalbayes/Portfile, R/R-fastmatrix/Portfile, R/R-laeken/Portfile, R/R-netUtils/Portfile, R/R-pbdSLAP/Portfile, R/R-pkgcache/Portfile, R/R-processx/Portfile, R/R-rSPDE/Portfile, R/R-repsd/Portfile, R/R-rgeos/Portfile
New ports plus updates.
Xcode 3.2.6
Have you
=> R: new packages and several updates

www/privoxy/Portfile
=> privoxy: Update to version 3.0.34

R/R-BART/Portfile, R/R-MLmetrics/Portfile, R/R-PVR/Portfile, R/R-Renvlp/Portfile, R/R-Rgof/Portfile, R/R-bark/Portfile, R/R-bvarsv/Portfile, R/R-dual.spls/Portfile, R/R-dynamite/Portfile, R/R-enrichR/Portfile, R/R-fontawesome/Portfile, R/R-gMWT/Portfile, R/R-oz/Portfile, R/R-parameters/Portfile, R/R-pkgdepends/Portfile, R/R-ps/Portfile, R/R-ptf/Portfile, R/R-qtl/Portfile, R/R-rARPACK/Portfile, R/R-splancs/Portfile, R/R-tinytex/Portfile, R/R-tvReg/Portfile, R/R-vctrs/Portfile, R/R-xaringan/Portfile
New ports and updates.
Xcode 3.2.6
Have you
=> R: new packages (V) and several updates

fortran/toml-f/Portfile, fortran/toml-f/files/patch-no-tests.diff
New port: https://github.com/toml-f/toml-f
macOS 10.6
Xcode 3.2
Have you
=> toml-f: new port in fortran

devel/cargo/Portfile, devel/libgit2/Portfile, lang/rust/Portfile, python/py-pygit2/Portfile, sysutils/starship/Portfile, textproc/bat/Portfile, textproc/git-delta/Portfile
Previous version bump: https://github.com/macports/macports-ports/pull/17800
macOS x.y
Have you
=> libgit2: update to 1.6.4

fortran/fortran-rpn-calc/Portfile
New port: https://github.com/scivision/rpn-calc-fortran
macOS 10.6
Xcode 3.2
Have you
=> fortran-rpn-calc: new port

devel/fnc/Portfile
CHANGES: https://fnc.bsdbox.org/doc/trunk/CHANGES.md
log: https://fnc.bsdbox.org/timeline?p=0.15&bt=0.13
Have you
=> fnc: update to 0.15

R/R-KODAMA/Portfile, R/R-R2OpenBUGS/Portfile, R/R-VeryLargeIntegers/Portfile, R/R-apsimx/Portfile, R/R-bundle/Portfile, R/R-cyclotomic/Portfile, R/R-emdbook/Portfile, R/R-grpreg/Portfile, R/R-hedgehog/Portfile, R/R-intmap/Portfile, R/R-maybe/Portfile, R/R-metrica/Portfile, R/R-mev/Portfile, R/R-minerva/Portfile, R/R-primes/Portfile, R/R-procmaps/Portfile, R/R-qrng/Portfile, R/R-quickcheck/Portfile, R/R-rapidoc/Portfile, R/R-redoc/Portfile, R/R-sfaR/Portfile, R/R-sparseGAM/Portfile, R/R-trustOptim/Portfile, R/R-vetiver/Portfile, R/R-winch/Portfile, R/R-winch/files/0001-macho.c-update-to-a-more-complete-source.patch
New ports.
Xcode 3.2.6
Have you
=> R: new packages (VI)

fortran/fortran-csv-module/Portfile, fortran/fortran-popen/Portfile, fortran/runge-kutta-fortran/Portfile
Some new ports.
macOS 10.6
Xcode 3.2
Have you
=> fpm: new packages (fortran)

python/py-awscli2/Portfile, python/py-awscrt/Portfile
=> py-awscli2: update to 2.11.14

sysutils/vtm/Portfile
=> vtm: update to 0.9.9c

math/ipopt/Portfile
=> ipopt: update to 3.14.12

devel/sbt/Portfile
=> sbt: update to 1.8.2

python/py-imagehash/Portfile
=> py-imagehash: Submission

graphics/makeicns/Portfile
* upgrade hashes format
* disable livecheck
* homepage is dead since 2020
Have you
=> makeicns: fetch using macports_distfiles

devel/got/Portfile
=> got: update to 0.87.

graphics/mupdf/Portfile, python/py-mupdf/Portfile, python/py-mupdf/files/setup.py.diff
=> mupdf, py-mupdf: update to 1.22

python/pipenv/Portfile
=> pipenv: update to 2023.3.20

sysutils/grep/Portfile
Fix a build error on Tiger and remove an obsolete link flag.
macOS 10.4.11
Have you
=> grep: fix build on Tiger

graphics/asymptote/Portfile, graphics/asymptote/files/patch-Makefile.diff, graphics/asymptote/files/patch-time.diff, python/py-pycson/Portfile, python/py-speg/Portfile
Update to 2.85.
PPC is fixed now. Once CI pass, ready to merge.
Xcode 3.2.6
Have you
@mojca Portfile had the following:
```
```
However I could not find how to disable docs. This could be a solution for systems where docs fail to build.
=> asymptote: update to 2.85, fix the build

python/py-ctypeslib2/Portfile, python/py-ctypeslib2/files/init_py.patch
=> py-ctypeslib2: Update to 2.3.3

devel/osc/Portfile, devel/osc/files/patch-build-disable.diff, devel/osc/files/patch-config.diff
=> osc: update to 1.1.1

devel/universal-ctags/Portfile
Closes: https://trac.macports.org/ticket/65238
Have you
=> universal-ctags: update to 6.0.20230423.0

R/R-FitAR/Portfile, R/R-FitARMA/Portfile, R/R-KFAS/Portfile, R/R-bestglm/Portfile, R/R-cherry/Portfile, R/R-cml/Portfile, R/R-estmeansd/Portfile, R/R-fUnitRoots/Portfile, R/R-flip/Portfile, R/R-gcookbook/Portfile, R/R-gemtc/Portfile, R/R-hommel/Portfile, R/R-hrbrthemes/Portfile, R/R-hset/Portfile, R/R-icr/Portfile, R/R-markovmix/Portfile, R/R-mcompanion/Portfile, R/R-meta/Portfile, R/R-metaBLUE/Portfile, R/R-metarep/Portfile, R/R-parabar/Portfile, R/R-partsm/Portfile, R/R-pcts/Portfile, R/R-pimeta/Portfile, R/R-rcccd/Portfile, R/R-rex2arma/Portfile, R/R-sarima/Portfile, R/R-sjlabelled/Portfile, R/R-someMTP/Portfile, R/R-vtable/Portfile
First new batch of ports.
Xcode 3.2.6
Have you
=> R: new packages (I)

net/snac/Portfile
=> snac: update to 2.28.

math/4ti2/Portfile
=> 4ti2: update to 1.6.10

sysutils/pv/Portfile
Include COPYING/NEWS/README with distributed package.
=> pv: Add COPYING/NEWS/README

math/polymake/Portfile, math/scip/Portfile, math/soplex/Portfile
=> Update: polymake to 4.9; scip to 8.0.3; soplex to 6.0.3

R/R-BMTAR/Portfile, R/R-Quandl/Portfile, R/R-RTransferEntropy/Portfile, R/R-RcppMeCab/Portfile, R/R-Rpoppler/Portfile, R/R-VLTimeCausality/Portfile, R/R-alphavantager/Portfile, R/R-bettermc/Portfile, R/R-eBsc/Portfile, R/R-extras/Portfile, R/R-ggrcs/Portfile, R/R-hts/Portfile, R/R-ks/Portfile, R/R-lddmm/Portfile, R/R-lsa/Portfile, R/R-mcmcr/Portfile, R/R-micEcon/Portfile, R/R-micEconCES/Portfile, R/R-nlist/Portfile, R/R-rgen/Portfile, R/R-riingo/Portfile, R/R-shinyr/Portfile, R/R-term/Portfile, R/R-tidyquant/Portfile, R/R-tidyquant/files/patch-no-Rblpapi.diff, R/R-tm/Portfile, R/R-tm/files/patch-missing-deps.diff, R/R-units/Portfile, R/R-universals/Portfile
New ports, few updates.
Xcode 3.2.6
Have you
=> R: new packages (V)

net/snac/Portfile
* add nomastodon variant.
Have you
=> snac: update to version 2.29.

gis/grass/Portfile, gis/grass7/Portfile
Adds +proj9 and +postgresql15 variants to keep the default in sync with other GIS ports without need to install various versions of the same port.
This also adds the +sqlite variant as default. Sqlite3 is nowadays actually a core part of GRASS and should be added as hardcoded dependency by next version bump at the earliest. I'm not sure what the policy is on this, the best would be (if appropriate) to make that move already now.
Have you
=> grass, grass7: add +proj9 and +postgresql15, make +sqlite default

devel/jreleaser/Portfile
macOS 11.6.5 20G527 x86_64
Have you
=> jreleaser: update to version

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.1.9

math/BRiAl/Portfile, math/BRiAl/files/patch-disable-boost-unit-tests.diff, math/m4ri/Portfile, math/palp/Portfile, math/palp/files/makefile.diff
All of this small library is dependency for Sage on port of which I'm working.
Have you
=> A few more math libraries

R/R-DBI/Portfile, R/R-FSelectorRcpp/Portfile, R/R-RSQLite/Portfile, R/R-bnlearn/Portfile, R/R-doctest/Portfile, R/R-ggbeeswarm/Portfile, R/R-hset/Portfile, R/R-ichimoku/Portfile, R/R-measurements/Portfile, R/R-microbenchmark/Portfile, R/R-norm/Portfile, R/R-rlang/Portfile, R/R-vroom/Portfile, R/R-vtable/Portfile
Bioconductor ones done, these are the remaining.
Xcode 3.2.6
Have you
=> R: updates to recently updated packages

python/py-branca/Portfile, python/py-folium/Portfile
=> py-folium: Submission

gis/qgis3/Portfile, gis/qgis3/files/patch-app_info_plist_in.diff
Bump to latest version 3.28.6 ~3.28.5~.
In addition adds the variant "+grass" for plugin with latest GRASS version (presently GRASS 8) and enables setting `proj` version (which was previously hardcoded to proj v8).
Have you
=> qgis3: Update to 3.28.6 with new PROJ and GRASS variants

devel/got/Portfile
=> got: update to 0.88.

audio/lame/Portfile, audio/lame/files/lame-3.100-altivec-20171014.diff, audio/lame/files/lame-3.100-altivec-20171217.diff, audio/lame/files/lame-3.100-neon-20230418.diff, audio/lame/files/lame-3.100-sse-20171014.diff
Add simd variant, make it default when build is not universal.
Xcode 3.2.6
Have you
=> lame: add simd variant

_resources/port1.0/group/compilers-1.0.tcl, devel/cctools/Portfile, math/OpenBLAS/Portfile, math/OpenBLAS/files/patch-MacOSX-mktemp.diff, math/mumps/Portfile, math/polymake/Portfile, math/scalapack/Portfile, math/scip/Portfile
Here I've fixed building on 10.10 `scip` and on 10.7 `mumps` and `OpenBLAS`.
I've also revbumped `scalapack`.
And make explicit requirements of compiler for `polymake`.
All of it allows to build `polymake` on both target platforms.
Closes: https://trac.macports.org/ticket/67322
Closes: https://trac.macports.org/ticket/67175
Closes: https://trac.macports.org/ticket/67350
macOS 10.10.5 14F2511 x86_64
Xcode 7.2.1 7C1002
Have you
=> Fix building polymake on 10.10 and 10.7

python/py-mupdf/Portfile
=> py-mupdf: update to 1.22.2

mail/offlineimap/Portfile, mail/offlineimap/files/patch-keyring.diff, mail/offlineimap/files/patch-utf8.diff
I also fixed usage when it installed to non standard prefix, and included a few useful patches.
Have you
=> offlineimap: update to 8.0.0-20230330

security/KeePassXC/Portfile, security/KeePassXC/files/devel/0001-use-setWindowFlags-instead-of-setWindowFlag-on-Qt-5..patch, security/KeePassXC/files/devel/0002-Fix-build-failure-with-Qt5.6.patch
=> KeepassXC-devel: fix build on macos 10.7-10.9

graphics/field3d/Portfile, graphics/field3d/files/patch-old-OS-new-compiler.diff, graphics/opencolorio/Portfile, graphics/openimageio/Portfile, graphics/openimageio/files/patch-enforce-clang14.diff, graphics/openvdb/Portfile, graphics/osl/Portfile, python/py-pyside-tools/Portfile, python/py-pyside/Portfile, python/py-pyside/files/patch-py311-compatibility.diff, python/py-shiboken/Portfile, python/py-shiboken/files/patch-py311-compatibility.diff
Here I'm fixing things which was missed at https://github.com/macports/macports-ports/pull/16893
Xcode 7.3.1 7D1014
macOS 13.0.1 22A400 x86_64
Have you
=> Follow up update blender-related ports

R/R-S4Arrays/Portfile, R/R-SparseArray/Portfile, R/R-fauxpas/Portfile, R/R-logistf/Portfile, R/R-miscTools/Portfile, R/R-pkgmaker/Portfile, R/R-showtext/Portfile, R/R-survey/Portfile
=> R: few updates to newly updated packages

R/R-Biobase/Portfile, R/R-BiocGenerics/Portfile, R/R-IRanges/Portfile, R/R-S4Vectors/Portfile, R/R-XVector/Portfile, R/R-bench/Portfile, R/R-bignum/Portfile, R/R-ggeffects/Portfile, R/R-sparseSEM/Portfile, R/R-testthat/Portfile
=> R: today’s updates

science/shtools/Portfile
This should be a trivial update.
* Minor changes were made to the Makefile to use `ar` and `ranlib` instead of `libtool`.
* The man pages have been changed to to use section 3 instead of 1.
Have you
=> shtools: update to 4.10.2

sysutils/vtm/Portfile
=> vtm: update to 0.9.9g

java/openjdk8-bootstrap/Portfile, java/openjdk8/Portfile, java/openjdk8/files/Support-arm64-and-fix-zero-assembler.diff
Add arm64 support
macOS x.y
Have you
=> openjdk8: add arm64 support

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.11.18

devel/osc/Portfile
=> osc: update to 1.1.2

devel/giter8/Portfile
=> giter8: update to 0.16.2

lang/ruby-devel/Portfile
Simple update.
macOS 10.6
Xcode 3.2
Have you
=> ruby-devel: update to current upstream (2023.05.06)

devel/rapidjson-devel/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> rapidjson-devel: update to current upstream (20230407)

math/stan/Portfile, math/stanmath/Portfile
Simple updates.
Xcode 3.2.6
Have you
=> stanmath, stan: update to new versions

net/snac/Portfile, net/snac/files/Makefile.patch
=> snac: update to 2.30.

net/nali/Portfile
macOS 12.6.5
Go 1.20.4
Have you
=> nali: new port

devel/luamake/Portfile, lua/lua-language-server/Portfile
=> lua-language-server: update to 3.6.19

lang/fortran-stdlib/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> fortran-stdlib: update to current upstream (2023.05.08)

sysutils/lporg/Portfile
macOS 12.6.5
Go 1.20.4
Have you
=> lporg: update to version 20.4.9

sysutils/vtm/Portfile
=> vtm: update to 0.9.9h

sysutils/payload-dumper-go/Portfile
macOS 13.3.1
Go 1.20.4
Have you
=> payload-dumper-go: new port

archivers/cpio/Portfile
=> cpio: update to 2.14

graphics/libopenraw-legacy/Portfile, graphics/libopenraw-legacy/files/patch-Make-CR3-support-optional.diff, graphics/libopenraw-legacy/files/patch-Makefile.am.diff, graphics/libopenraw-legacy/files/patch-ifdentry.hpp.diff, graphics/libopenraw/Portfile
New port.
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> libopenraw-legacy: pre-Rust version for old systems

textproc/icdiff/Portfile
=> icdiff: update to 2.0.6

devel/quickjs/Portfile, devel/quickjs/files/quickjs.pc
=> quickjs: new port in devel

www/mod_security2/Portfile
=> mod_security2: use lua PG

fortran/fortran-git/Portfile, fortran/maptran3d/Portfile, fortran/maptran3d/files/patch-fix-paths.diff
New ports.
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> fortran: a couple of new ports

R/R-APML0/Portfile, R/R-BayesPPD/Portfile, R/R-BivGeo/Portfile, R/R-CoImp/Portfile, R/R-LongMemoryTS/Portfile, R/R-RPtests/Portfile, R/R-RestRserve/Portfile, R/R-Rserve/Portfile, R/R-bookdown/Portfile, R/R-docopt/Portfile, R/R-hbbr/Portfile, R/R-httr2/Portfile, R/R-jetpack/Portfile, R/R-memochange/Portfile, R/R-mirai/Portfile, R/R-nanoarrow/Portfile, R/R-pdfetch/Portfile, R/R-quantreg.nonpar/Portfile, R/R-rzmq/Portfile, R/R-seg/Portfile, R/R-vapour/Portfile, R/R-vscc/Portfile, R/R-waldo/Portfile
=> R: updates and new packages

archivers/advancecomp/Portfile
=> advancecomp: update to 2.5

databases/dbvis/Portfile
=> dbvis: update to 23.2.1

java/VisualVM/Portfile
=> VisualVM: update to 2.1.6

math/fxt/Portfile
Simple update.
Xcode 3.2.6
Have you
=> fxt: update to 2023.05.07

textproc/less/Portfile
=> less: update to 633

devel/CImg/Portfile, multimedia/pHash/Portfile
Another forgotten port. Long due update.
Xcode 3.2.6
Have you
=> CImg: update to 3.2.4

python/repo/Portfile
=> repo: update to 2.32

cad/gtkwave/Portfile
* Updated gtkwave to 3.3.115
* Added a maintainer to the portfile
Have you
=> gtkwave: update to 3.3.115

databases/rocksdb/Portfile, databases/rocksdb/files/0003-remove-redundant-move-11418.patch
Closes: https://trac.macports.org/ticket/67389
Have you
=> rocksdb: update to 8.1.1; use the right TBB

graphics/imath/Portfile, graphics/openexr/Portfile, graphics/openexr/files/patch-have_defines.diff
=> OpenEXR, Imath: split Portfiles, removed unnecessary code, fix on old systems

sysutils/chntpw/Portfile, sysutils/chntpw/files/chntpw.8, sysutils/chntpw/files/patch-Makefile.diff, sysutils/chntpw/files/patch-debian-04_get_abs_path.diff, sysutils/chntpw/files/patch-debian-06_correct_test_open_syscall.diff, sysutils/chntpw/files/patch-debian-07_detect_failure_to_write_key.diff, sysutils/chntpw/files/patch-debian-08_no_deref_null.diff, sysutils/chntpw/files/patch-debian-09_improve_robustness.diff, sysutils/chntpw/files/patch-debian-10_remove_static.diff, sysutils/chntpw/files/patch-debian-11_improve_documentation.diff, sysutils/chntpw/files/patch-debian-12_readonly_filesystem.diff, sysutils/chntpw/files/patch-debian-13_write_to_hive.diff, sysutils/chntpw/files/patch-debian-14_improve_description.diff, sysutils/chntpw/files/patch-debian-15_added_samunlock_binary.diff, sysutils/chntpw/files/patch-warnings_64bit.diff, sysutils/chntpw/files/reged.8, sysutils/chntpw/files/sampasswd.8, sysutils/chntpw/files/samunlock.8, sysutils/chntpw/files/samusrgrp.8
=> chntpw: new port

devel/howdoi/Portfile
P. S. Not switching to python311, because multiple dependencies are missing for it.
Xcode 3.2.6
Have you
=> howdoi: update to 2.0.20

R/R-VeryLargeIntegers/Portfile, R/R-esreg/Portfile, R/R-logcondens/Portfile, R/R-marginaleffects/Portfile, R/R-pROC/Portfile, R/R-softbib/Portfile, R/R-tzdb/Portfile
=> R: today’s updates to existing packages

devel/oniguruma6/Portfile
=> oniguruma6: fix spelling in long_description

devel/libical/Portfile, devel/libical/files/patch-gcc42.diff
Also fixes sequence in the portfile: compiler blacklist should go before a patch conditional on compiler choice.
Xcode 3.2.6
Have you
=> libical: update to 3.0.16

science/flann/Portfile
P. S. Wanted to add support for tests, but for that several Ruby packages need update: https://trac.macports.org/ticket/67419
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> flann: update to 1.9.2

devel/fpm/Portfile, devel/fpm/files/patch-install.diff
=> fpm: update to 0.8.2

lang/sbcl/Portfile, math/maxima/Portfile
Addresses <https://trac.macports.org/ticket/67422>.
=> lang/sbcl: update to sbcl-2.3.4

games/fheroes2/Portfile
=> fheroes2: update to 1.0.4

devel/libuninameslist/Portfile
=> libuninameslist: update to 20221022

games/supertuxkart/Portfile, games/supertuxkart/files/patch-supertuxkart-iosurfaceref.diff, games/supertuxkart/files/patch-supertuxkart-no-metal.diff
Closes: https://trac.macports.org/ticket/67263
macOS 10.6.8
Have you
=> supertuxkart: Fix build on 10.12 and earlier

aqua/McBopomofo/Portfile
Turned out old systems’ native python cannot preprocess sources. Simplify the code: just use Macports python across the board.
Update description.
Claim the port.
macOS 10.5.8
Xcode 3.1.4
macOS 10A190
Xcode 3.2
Have you
=> McBopomofo: depend on Macports python; portfile update

archivers/snappy/Portfile, archivers/snappy/files/patch-disable-sign-compare-warning.diff
=> snappy: update to 1.1.10

devel/starpu/Portfile, devel/starpu/files/patch-starpu_mpi_world_rank.diff
See commits.
Xcode 3.2.6
Have you
=> starpu: fix from upstream, improvements to the port

math/stan/Portfile, math/stanmath/Portfile
Updates.
macOS 10.6
Xcode 3.2
Have you
=> stan, stanmath: update to new releases

devel/mimalloc/Portfile
=> mimalloc: update to 2.1.2

net/snac/Portfile
=> snac: update to version 2.32

devel/libimobiledevice-glue/Portfile, devel/libimobiledevice/Portfile, devel/libirecovery/Portfile, devel/usbmuxd/Portfile, textproc/libplist/Portfile
=> multiple libimobiledevice ports: update

devel/sbt/Portfile
=> sbt: update to 1.8.3

python/py-alive-progress/Portfile, python/py-grapheme/Portfile, python/py-httpcore/Portfile, python/py-httpx/Portfile, python/py-hypothesis/Portfile, python/py-pycryptodome/Portfile, python/py-pycryptodomex/Portfile, python/py-werkzeug/Portfile
=> Update few python ports which I'm care of

sysutils/vtm/Portfile
=> vtm: update to 0.9.9i

devel/osc/Portfile
=> osc: update to 1.1.3

python/py-cryptg/Portfile, python/py-telethon/Portfile
=> py-telethon: Update to version 1.27.0, add py-cryptg run dependency; py-cryptg: Submission

devel/datree/Portfile
=> datree: update to 1.9.2

python/py-sentencepiece/Portfile
=> py-sentencepiece: add py311 subport

databases/postgresql15-doc/Portfile, databases/postgresql15/Portfile
=> postgresql15: update to 15.3

devel/dejagnu/Portfile
Trivial update.
Xcode 3.2.6
Have you
=> dejagnu: update to 1.6.3

_resources/port1.0/group/debug-1.0.tcl
This port group allows builders to create ports where debugging symbols are created but the code is still optimized. This is primarily useful to packagers of applications such as GIMP ([issue](https://gitlab.gnome.org/Infrastructure/gimp-macos-build/-/issues/4)) where the code needs to be optimized, but having debug symbols greatly improves the debuggability of crashes in the application.
This port group conflicts with the debug port group but is based on it.
Another approach was considered, which was to override the `debug.flags.delete` and `debug.flags.add` variables, but it was not possible to determine how this could be done in a new variant built into a port.
Xcode 14.0.1 14A400
Have you
=> pg debug: add variant debugoptimized

devel/icu/Portfile, devel/icu/files/patch-config-mh-darwin.diff
Non-devel version of #18696 
Closes: https://trac.macports.org/ticket/67428
Closes: https://trac.macports.org/ticket/67433
See: https://github.com/unicode-org/icu/pull/2467
macOS x.y
Have you
=> icu: fix rpath mess

python/py-XlsxWriter/Portfile
=> py-xlsxwriter: 3.1.1

sysutils/vtm/Portfile
=> vtm: update to 0.9.9j

R/R-FeedbackTS/Portfile, R/R-FuzzyM/Portfile, R/R-PROJ/Portfile, R/R-TDAkit/Portfile, R/R-TDAstats/Portfile, R/R-abn/Portfile, R/R-abn/files/patch-no-inla.diff, R/R-automap/Portfile, R/R-free/Portfile, R/R-gofar/Portfile, R/R-gstat/Portfile, R/R-lookout/Portfile, R/R-lwgeom/Portfile, R/R-mapdata/Portfile, R/R-matahari/Portfile, R/R-ncmeta/Portfile, R/R-proj4/Portfile, R/R-realtest/Portfile, R/R-reproj/Portfile, R/R-rjsoncons/Portfile, R/R-rrpack/Portfile, R/R-scribe/Portfile, R/R-sftime/Portfile, R/R-spacetime/Portfile, R/R-stars/Portfile, R/R-stringx/Portfile, R/R-trajectories/Portfile, R/R-xtensor/Portfile
New ports.
macOS 10.6
Xcode 3.2
Have you
=> R: new packages (III)

lang/clang-11-bootstrap/Portfile
=> clang-11-bootstrap: escape path name

graphics/diff-pdf/Portfile
=> diff-pdf: update to version 0.5.1

math/fricas/Portfile
=> fricas: revbump because of sbcl update

sysutils/diffutils/Portfile
* Bump revision number
* Add pre-configure{} code block to add the "--disable-year2038" configure flag for +universal builds
* Change "configure.args" to "configure.args-append"
* Add "--disable-silent-rules" flag to "configure.args-append"
* Reformat Portfile
CLOSES:  https://trac.macports.org/ticket/67475
Have you
=> diffutils:  fix bug with +universal variant

sysutils/vtm/Portfile
=> vtm: update to 0.9.9k

www/wordpress/Portfile
https://wordpress.org/documentation/wordpress-version/version-5-5-12/
**Untested**
Have you
=> wordpress: update to 5.5.12

science/elmerfem/Portfile, science/elmerfem/files/patch-ElmerGUI.diff, science/elmerfem/files/patch-use-right-compiler.diff
New port: http://www.elmerfem.org/blog
Xcode 3.2.6
Have you
=> elmerfem: new port in science

lang/ruby-devel/Portfile
Simple update.
macOS 10.6
Xcode 3.2
Have you
=> ruby-devel: update to current upstream (2023.05.24)

graphics/glslang/Portfile
The modifications in this PR don't affect the build in any way, so revbump not needed.
Have you
=> glslang: Portfile cleanup

devel/nodejs14/Portfile
NodeJS 14 reached EOL a couple of weeks ago; deprecate it.
macOS x.y
Have you
=> nodejs14: deprecate

python/poetry/Portfile, python/py-poetry-core/Portfile, python/py-poetry-plugin-export/Portfile
=> poetry: update to 1.5.0

databases/redis/Portfile
=> redis: update to 7.0.11

python/py-awscli2/Portfile, python/py-awscrt/Portfile
=> py-awscli2: update to 2.11.22

devel/osc/Portfile, python/py-httpcore/Portfile, python/py-pathvalidate/Portfile
I'm a maintainer or co-maintainer of all this ports.
It is simple and clean update.
Have you
=> Update a few python ports

archivers/unrar/Portfile
=> unrar: update to 6.2.7

net/eiskaltdcpp/Portfile, net/eiskaltdcpp/files/patch-CMakeLists.diff, net/eiskaltdcpp/files/patch-mac-qt.diff
New port: https://github.com/eiskaltdcpp/eiskaltdcpp
macOS 10.6
Xcode 3.2
Have you
=> eiskaltdcpp: new port, DC++ client in Qt4

net/toxcore/Portfile, net/toxic/Portfile, net/toxic/files/0001-Makefile-add-PPC.patch, net/toxic/files/0002-Config-make-paths-sane.patch, net/toxic/files/0003-Darwin.mk-do-not-hardcode-flags-to-unbreak-older-mac.patch, net/toxic/files/0004-Fix-macOS-linking.patch, net/toxic/files/0005-Remove-hardcoded-osx_video.patch
New port: https://github.com/TokTok/toxic
macOS 10.6
Xcode 3.2
Have you
=> toxcore: update to upstream; toxic: new port, p2p messenger

lang/ocaml/Portfile, lang/ocaml/files/patch-configure-darwin-ppc.diff, lang/ocaml/files/patch-configure-darwin32.diff
@pmetzger Portfile only updates the version and checksums, nothing else touched. Patches for PPC are updated to fit into the changed configure script, but otherwise are the same.
macOS 10.6.8
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> ocaml: update to 4.14

net/mhxd/Portfile, net/mhxd/files/patch-broken-comments.diff, net/mhxd/files/patch-fix-for-newer-macos.diff
Let’s see if this quite an archaic software builds.
macOS 10.6
Xcode 3.2
Have you
=> mhxd: new port, Hotline client and server

python/py-clang/Portfile, python/py-ctypeslib2/Portfile, python/py-ctypeslib2/files/init_py.patch, python/py-ctypeslib2/files/pyproject.toml.patch
=> py-clang/py-ctypeslib2: Update to latest

python/py-blosc2/Portfile, python/py-blosc2/files/pyproject.toml.patch, python/py-ndindex/Portfile
=> New: py-blosc2 and py-ndindex

python/py-numexpr/Portfile
=> py-numexpr: add py311 subport

R/R-async/Portfile, R/R-bspline/Portfile, R/R-iterors/Portfile, R/R-openxlsx2/Portfile, R/R-parallelly/Portfile, R/R-parameters/Portfile, R/R-qlcal/Portfile, R/R-qvcalc/Portfile, R/R-r2rtf/Portfile
=> R: update a few packages

net/snac/Portfile
=> snac: update to version 2.33

devel/apache-arrow/Portfile, python/py-apache-beam/Portfile, python/py-datasets/Portfile, python/py-kraken/Portfile, python/py-magenta/Portfile, python/py-sentence-transformers/Portfile, python/py-tensorflow-data-validation/Portfile, python/py-tensorflow-transform/Portfile, python/py-tfx-bsl/Portfile, python/py-transformers/Portfile
Note: I am submitting this PR from a machine on which building neither 11.0.0 nor 12.0.0 works. However, I see on other machines (configured exactly like this one) that these builds do work. So I am submitting this and will cross fingers for the CI.
Have you
=> apache-arrow: Update to version 12.0.0

fortran/fortran-cairo/Portfile, fortran/fortran-lua53/Portfile, fortran/fortran-xlib/Portfile
New ports.
Xcode 3.2.6
Have you
=> fortran: some new packages

x11/homebank/Portfile
=> homebank: update to 5.6.4

finance/bitcoin/Portfile
=> bitcoin: update to 25.0

editors/mle/Portfile
Have you
Haven't tested this as I don't have a port setup or a mac handy. cc @sikmir
=> mle: update to 1.7.2

math/strumpack/Portfile
New port: https://github.com/pghysels/STRUMPACK
macOS 10.6
Xcode 3.2
Have you
=> strumpack: new port in math

science/mfem/Portfile, science/mfem/files/0001-CMakeLists-fix-flags-for-PowerPC.patch, science/mfem/files/0002-Define-MAP_ANONYMOUS-to-MAP_ANON-whenever-it-is-unde.patch
New port: https://github.com/mfem/mfem
macOS 10.6
Xcode 3.2
Have you
=> mfem: new port in science

python/py-xyzservices/Portfile
Building currently fails (unless py-setuptools_scm is already installed and trace mode is not used):
```
--->  Building py311-xyzservices
Executing:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_macports_macports-ports_python_py-xyzservices/py311-xyzservices/work/xyzservices-2023.5.0" && /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_macports_macports-ports_python_py-xyzservices/py311-xyzservices/work 
* Getting build dependencies for wheel...
ERROR Missing dependencies:
setuptools_scm
Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_github.com_macports_macports-ports_python_py-xyzser …
```
=> py-xyzservices: fix build

lang/logtalk/Portfile
=> logtalk: update to 3.66.0

net/tcpflow/Portfile
tcpflow links against python2.17 if it installed.
See: https://github.com/simsong/tcpflow/blob/master/configure.ac#L497-L499
Have you
=> tcpflow: add missed dependency; add myself as maintainer

devel/nixpacks/Portfile
=> nixpacks: update to 1.9.0

science/madness/Portfile
=> madness: update to current upstream (2023.05.30)

devel/datree/Portfile
=> datree: update to 1.9.3

devel/fastmod/Portfile
👋🏻 this is my first contribution to this project and the getting started experience was pretty nice! The documentation was definitely more straight forward than what I'm used to from Nix.
I hope I followed all the contribution guidelines, if not, of course, let me know.
Add `fastmod` a tool to assist in large-scale refactors.
Have you
=> fastmod: new Portfile at 0.4.3

devel/volta-node/Portfile
There's already another port called "volta", so I called this "volta-node" to avoid a naming conflict. The port I'm adding is for a NodeJS toolchain manager, hence the "-node" suffix.
The CLI tool generates completions for various shells. I'm unsure if those should be separate variants each or if it's okay to just install all completions for all installations?
Have you
=> volta-node: new port in devel at 1.1.1

lisp/cl-cffi/Portfile, lisp/cl-cffi/files/0001-Support-variadic-functions-on-SBCL-Darwin-arm64.patch, lisp/cl-cffi/files/0002-fix-tests-on-SBCL-Darwin-arm64.patch
=> cl-cffi: add missed dependency, fix arm64

lisp/cl-cffi/Portfile
=> cl-cffi: remove unrequired backslash

math/libtommath/Portfile
macOS 12.6.5
Xcode 14.2
Have you
=> libtommath: install pkgconfig file

lang/julia/Portfile, lang/julia/files/patch-Makefile.diff
- Closes: https://trac.macports.org/ticket/65550
- Specify minimal platform version
- Remove p7zip dependency
- 7z is installed to private libexec/julia directory
This should allow building Julia v1.9.0 on 'OS X'/macOS 10.10 - 10.14 (Yosemite - Mojave).
ℹ️ A similar patch was tested by @quentinmit on macOS 10.14.x (Mojave).
Have you
=> julia: Patch Makefile if darwin version < 19

math/symengine/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> symengine: update to 0.10.1

archivers/zstd/Portfile
=> zstdConfig.cmake: subport to install zstd CMake file

archivers/unrar/Portfile
=> unrar: update to 6.2.8

net/openconnect/Portfile
=> openconnect: update to version 9.12

R/R-nanonext/Portfile, devel/nng/Portfile
Update, improvement.
Xcode 3.2.6
Have you
=> nng: enable TLS; R-nanonext: update to 0.9.0, build against Macports nng

python/py-alive-progress/Portfile
=> py-alive-progress: update to 3.1.4

www/minio-mc/Portfile, www/minio/Portfile
Last version available without major breaking change.
=> minio[-mc]: Update to 2022-10-2[24].

java/openjdk8/Portfile, java/openjdk8/files/Support-arm64-and-fix-zero-assembler.diff
Fixes:
https://trac.macports.org/ticket/67376
https://trac.macports.org/ticket/67377
macOS x.y
Have you
=> openjdk8: fix configure on arm64

science/h4h5tools/Portfile, science/h4h5tools/files/patch-h4h5tools.diff
closes: https://trac.macports.org/ticket/62917
Have you
=> h4h5tools: fix build on newer systems

gis/gdal-grass/Portfile, gis/grass/Portfile, gis/grass/files/01_patch-dyld-link.diff, gis/grass/files/02_grass-python.diff, gis/qgis3/Portfile
Update QGIS 3 to version 3.28.7.
macOS 12.6.5 21G531 arm64
Have you
cc/ @i0ntempest
=> qgis3: update to 3.28.7

finance/bitcoin/Portfile
=> bitcoin: use legacysupport.use_mp_libcxx on Mojave and older

R/R-CIplot/Portfile, R/R-DirectedClustering/Portfile, R/R-EBEN/Portfile, R/R-HDMFA/Portfile, R/R-bst/Portfile, R/R-easyNCDF/Portfile, R/R-ezplot/Portfile, R/R-fdatest/Portfile, R/R-fscaret/Portfile, R/R-gptstudio/Portfile, R/R-gptstudio/files/patch-no-shinytest2.diff, R/R-hmeasure/Portfile, R/R-hmeasure/files/testthat.R, R/R-isotree/Portfile, R/R-matrixset/Portfile, R/R-netseg/Portfile, R/R-rFerns/Portfile, R/R-rmdpartials/Portfile, R/R-robin/Portfile, R/R-rocc/Portfile, R/R-rucrdtw/Portfile, R/R-shiny.i18n/Portfile, R/R-shiny.i18n/files/patch-no-googleLanguageR.diff, R/R-shinyvalidate/Portfile, R/R-sparsepp/Portfile, R/R-ufs/Portfile, R/R-wrappr/Portfile, R/R-zic/Portfile, R/R-zoib/Portfile
New ports.
Xcode 3.2.6
Have you
=> R: new packages (1)

security/bitwarden-cli/Portfile
=> bitwarden-cli: Update to 2023.05.0

java/detekt-cli/Portfile
=> detekt-cli: Update to version 1.23.0

net/snac/Portfile
=> snac: update to version 2.34

gis/tinyows/Portfile, gis/tinyows/files/patch-Makefile_in.diff, gis/tinyows/files/patch-ows_define_h.diff
Update TinyOWS to version 1.2.0.
macOS 12.6.5 21G531 arm64
Have you
=> tinyows: update to version 1.2.0

devel/fpm/Portfile, devel/fpm/files/patch-install.diff
Update.
macOS 10.6
Xcode 3.2
Have you
=> fpm: update to 0.9.0

lang/ghc/Portfile
=> ghc: Update to version 9.6.2

devel/starpu/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> starpu: update to 1.4.1

devel/retdec/Portfile
=> retdec-devel: update to 20230525

graphics/gpick/Portfile, graphics/gpick/files/patch-bool_vector_fix.diff, graphics/gpick/files/patch-getExecutablePath.diff, lang/lua/Portfile, lang/lua/files/lua.pc, lang/lua/files/lua_branch.pc
=> Add support for lua-c++ & update gpick

math/vinci/Portfile
New port: https://www.multiprecision.org/vinci/home.html
Xcode 3.2.6
Have you
=> vinci: new port in math

aqua/qt513/files/patch-qtwebengine_sdk.diff
See: https://trac.macports.org/ticket/61924#comment:7
[skip ci]
macOS 10.15
Xcode 11.7
SDK 10.15.6
Have you
Build progresses past error in ticket; full build not completed
=> qt513-qtwebengine: fix build on macOS 10.15

math/cln/Portfile
=> cln: use muniversal PG version 1.1

science/bart/Portfile, science/bart/files/Makefile.patch
New port: bart, an MRI reconstruction toolbox.
=> bart: Initial portfile

science/bart/Portfile
=> bart: Tweaks to Portfile (no bump).

devel/got/Portfile
=> got: update to version 0.89

net/nghttp3/Portfile, net/ngtcp2/Portfile
Update.
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> nghttp3, ngtcp2: update to latest releases

math/newran/Portfile, math/newran/files/CMakeLists.txt
Update, clean-up portfile.
Xcode 3.2.6
Have you
=> newran: update to v. 03

security/blake3/Portfile
Update Blake3 to v.1.4.0
Have you
=> blake3: update to 1.4.0

devel/boehmgc/Portfile
macOS 10.13
Xcode 9.4
Have you
=> boehmgc: update to 8.2.4

lang/ruby-devel/Portfile
=> ruby-devel: update to upstream master (2023.06.05)

R/R-BayesTree/Portfile, R/R-CARM/Portfile, R/R-DEoptimR/Portfile, R/R-IDF/Portfile, R/R-OBRE/Portfile, R/R-Rsomoclu/Portfile, R/R-bayesRecon/Portfile, R/R-beepr/Portfile, R/R-boinet/Portfile, R/R-broom/Portfile, R/R-bslib/Portfile, R/R-cereal/Portfile, R/R-conTree/Portfile, R/R-fake/Portfile, R/R-gmvarkit/Portfile, R/R-hbamr/Portfile, R/R-kohonen/Portfile, R/R-mnonr/Portfile, R/R-polyreg/Portfile, R/R-psica/Portfile, R/R-psychotools/Portfile, R/R-regtools/Portfile, R/R-sharp/Portfile, R/R-survstan/Portfile, R/R-ufs/Portfile
=> R: updates and some new packages

www/cadaver/Portfile
Update the cadaver port to version 0.24 and fix build with neon 0.32.x.
macOS 12.6.6 21G646 x86_64
Have you
=> cadaver: update to 0.24

R/R-DelayedArray/Portfile, R/R-RSQLite/Portfile, R/R-SparseArray/Portfile, R/R-clusterSim/Portfile, R/R-cvms/Portfile, R/R-gargle/Portfile, R/R-ggeffects/Portfile, R/R-googlesheets4/Portfile, R/R-jointDiag/Portfile, R/R-morpheus/Portfile, R/R-rTensor/Portfile, R/R-usedist/Portfile
Updates and some new ports.
Xcode 3.2.6
Have you
=> R: few updates and few new packages

math/hiop/Portfile, math/strumpack/Portfile
Update.
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> strumpack: update to 7.1.3; hiop: support strumpack backend

lang/sbcl/Portfile, lang/sbcl/files/0004-arm-Darwin-disable-futex-on-BigSur.patch
=> sbcl: fix build on macOS 11 / arm

math/hypre/Portfile
Update, use a correct upstream repo.
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> hypre: update to 2.28.0

python/py-pdal/Portfile
Add new Python port `py-pdal`, which provides Python interface to the `PDAL` port.
macOS 12.6.5 21G531 arm64
Have you
=> py-pdal: add new port, version 3.2.3

python/py-wxpython-4.0/Portfile, python/py-wxpython-4.0/files/buildtools_config_py.patch
=> py-wxpython-4.0: add python 3.11

lang/loli/Portfile, lang/loli/files/loli-fix.diff
New port.
Xcode 3.2.6
Have you
=> loli: new port in lang

devel/rapidjson-devel/Portfile, devel/rapidjson-devel/files/patch-fix-cxx-standard.diff
=> rapidjson-devel: update to 20230517, fix tests

math/radian/Portfile
=> radian: update to 0.6.6

devel/alex/Portfile
=> alex: Update to version 3.3.0.0

devel/git-cinnabar/Portfile, devel/git-remote-hg/Portfile, devel/hg-credentials/Portfile, devel/hg-evolve/Portfile, devel/hg-git/Portfile, devel/hg-keyring/Portfile, devel/mercurial/Portfile, devel/mercurial/files/hg.diff, devel/mercurial/files/makefile.diff, devel/mercurial/files/setup_py.diff, devel/tortoisehg/Portfile, python/py-dulwich/Portfile, python/py-iniparse/Portfile, python/py-mercurial_extension_utils/Portfile
This switches Mercurial and its dependents to Python 3.11, and upgrades Mercurial to 6.4.2.
macOS x.y
Have you
=> mercurial: update to 6.4.3; use python311 

games/fheroes2/Portfile
=> fheroes2: update to 1.0.5, style nits

lisp/cl-plus-ssl/Portfile, lisp/cl-trivial-features/Portfile
=> Update a few lisp ports

graphics/librtprocess/Portfile, graphics/librtprocess/files/0001-ProcessorTargets-fix-native-flags.patch
New port: https://github.com/CarVac/librtprocess
macOS 10.6
Xcode 3.2
Have you
=> librtprocess: new port in graphics

devel/HaXml/Portfile
=> HaXml: Update to version 1.25.12

R/R-ConfZIC/Portfile, R/R-CptNonPar/Portfile, R/R-MBA/Portfile, R/R-MatchIt/Portfile, R/R-RcppCWB/Portfile, R/R-RcppCWB/files/0001-Fix-building-for-PowerPC.patch, R/R-RcppCWB/files/0002-Fix-static-libs.patch, R/R-RcppCWB/files/0003-Fixes-for-Macports.patch, R/R-Rdistance/Portfile, R/R-bamlss/Portfile, R/R-cbcTools/Portfile, R/R-cmna/Portfile, R/R-devEMF/Portfile, R/R-dynmix/Portfile, R/R-ergmito/Portfile, R/R-fmcmc/Portfile, R/R-fude/Portfile, R/R-gimme/Portfile, R/R-idefix/Portfile, R/R-mcompanion/Portfile, R/R-multcomp/Portfile, R/R-pkgbuild/Portfile, R/R-pkgcache/Portfile, R/R-sdPrior/Portfile, R/R-sommer/Portfile
=> R: updates and a few new packages

math/latte-int/Portfile, math/lrslib/Portfile, math/normaliz/Portfile, math/permlib/Portfile, math/permlib/files/patch-boost-1.67.diff, math/polymake/Portfile, math/sympol/Portfile, math/sympol/files/0001-patch-for-bliss-0.77-compatibility.patch, math/sympol/files/0002-Enforce-GMP-based-bliss.patch, math/sympol/files/0003-patch-for-cddlib-0.94-compatibility.patch, math/sympol/files/0004-patch-for-lrslib-7.2-compatibility.patch, math/sympol/files/0005-patch-for-permlib-0.2.9-compatibility.patch, math/sympol/files/0006-fix-headers.patch
=> polymake: update to 4.10

R/R-CompDist/Portfile, R/R-NNS/Portfile, R/R-PearsonDS/Portfile, R/R-RMixtCompUtilities/Portfile, R/R-RStata/Portfile, R/R-Rook/Portfile, R/R-StanHeaders/Portfile, R/R-berryFunctions/Portfile, R/R-cbl/Portfile, R/R-cobalt/Portfile, R/R-distillery/Portfile, R/R-ebTobit/Portfile, R/R-extRemes/Portfile, R/R-fExtremes/Portfile, R/R-gpboost/Portfile, R/R-gpboost/files/patch-unbreak-openmp.diff, R/R-gpboost/files/patch-unbreak-ppc.diff, R/R-lightgbm/Portfile, R/R-lightgbm/files/patch-unbreak-openmp.diff, R/R-lightgbm/files/patch-unbreak-ppc.diff, R/R-npde/Portfile, R/R-quantmod/Portfile, R/R-usedthese/Portfile, R/R-vctrs/Portfile
Updates and some new ports.
Xcode 3.2.6
macOS 10A190
Xcode 3.2
Have you
=> R: updates and a few new packages (II)

python/py-hypothesis/Portfile, python/py-last/Portfile, python/py-pytest/Portfile, python/py-pyzstd/Portfile
=> Updagte a few python ports

science/ismrmrd/Portfile
=> ismrmrd: 1.13.7

python/py-pytorch/Portfile
Closes: https://trac.macports.org/ticket/67627
I've skip CI because it fails by timeout anyway.
My local machine requires a bit more than 3 hours to build one subport, and here 3 of them that makes it impossible to build all of them in 6 hours.
Have you
=> py-pytorch: switch to system TBB

devel/developer_cmds/Portfile, devel/mk-configure/Portfile
New port.
macOS 10.6
Xcode 3.2
Have you
=> mk-configure: new port in devel; developer_cmds: fix the port

lang/fortran-stdlib/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> fortran-stdlib: update to upstream (2023.06.16)

R/R-PlackettLuce/Portfile, R/R-chisquare/Portfile, R/R-crew.cluster/Portfile, R/R-datawizard/Portfile, R/R-duckdb/Portfile, R/R-igraph/Portfile, R/R-nimble/Portfile, R/R-psfmi/Portfile, R/R-robustX/Portfile, R/R-robustbase/Portfile, R/R-testthat/Portfile
=> R: updates to packages

net/amule/Portfile
Let’s see if this builds.
macOS 10.6
Xcode 3.2
Have you
=> amule: new port

fortran/toml-f/Portfile
Minor update.
macOS 10.6
Xcode 3.2
Have you
=> toml-f: pick latest fixes from upstream

tex/texlive-bin/Portfile
=> texlive-bin: fix universal build

devel/cpp-argparse-dev/Portfile
=> cpp-argparse-dev: update to v1.8.0

net/snac/Portfile
=> snac: update to version 2.35

math/4ti2/Portfile
=> 4ti2: fix build on 10.8

R/R-PlaneGeometry/Portfile, R/R-RcppCGAL/Portfile, R/R-RcppSpdlog/Portfile, R/R-cvms/Portfile, R/R-ezplot/Portfile, R/R-groupdata2/Portfile, R/R-psfmi/Portfile, R/R-psychTools/Portfile, R/R-spdl/Portfile, R/R-uniformly/Portfile
=> R: updates for existing packages

science/madness/Portfile
Trivial update.
macOS 10.6
Xcode 3.2
Have you
=> madness: update to current upstream (2023.06.07)

R/R-BayesDA/Portfile, R/R-BoundEdgeworth/Portfile, R/R-DDPM/Portfile, R/R-GPoM/Portfile, R/R-RcppArmadillo/Portfile, R/R-STAREG/Portfile, R/R-clinfun/Portfile, R/R-mirai.promises/Portfile, R/R-samplingR/Portfile
Due to pathetically slow CI which fail on time-out today, breaking PRs into tiny chunks.
Xcode 3.2.6
Have you
=> R: updates and new packages (III)

lang/py-htmldocs/Portfile
=> py3*-htmldocs: Update to latest

lang/MoarVM/Portfile, lang/nqp/Portfile, lang/rakudo/Portfile
Update. Fix legacysupport wrappers in `rakudo` port.
macOS 10.6
Xcode 3.2
Have you
=> rakudo and friends: update to 2023.04

devel/datree/Portfile
=> datree: update to 1.9.6

R/R-etwfe/Portfile, R/R-gargle/Portfile, R/R-gdistance/Portfile, R/R-ggfun/Portfile, R/R-robeth/Portfile
Updates.
macOS 10.6.8
Xcode 3.2.6
Have you
=> R: a few updates to existing packages

devel/Bear/Portfile, devel/edencommon/Portfile, devel/fb303/Portfile, devel/fbthrift/Portfile, devel/fizz/Portfile, devel/folly/Portfile, devel/libfmt9/Portfile, devel/libmamba/Portfile, devel/log4cxx/Portfile, devel/pika/Portfile, devel/proxygen/Portfile, devel/wangle/Portfile, editors/cherrytree/Portfile, games/warzone2100/Portfile, graphics/openimageio/Portfile, lang/lfortran/Portfile, math/Sophus/Portfile, sysutils/poac/Portfile, sysutils/watchman/Portfile, www/restinio/Portfile
Let’s see if everything builds.
`openimageio` may fail, since it fails on several systems at the moment: https://ports.macports.org/port/openimageio/details
macOS 10.6
Xcode 3.2
Have you
=> libfmt9: update to 9.1.0

www/taizen/Portfile
New port for taizen - a terminal based wikipedia browser
Have you
=> taizen: new port (version 2023-06-05)

graphics/qoi/Portfile
=> qoi: update to 20230616

security/libfido2/Portfile, security/libfido2/files/patch-hid_osx.diff, security/libfido2/files/patch-werror.diff, security/pam-u2f/Portfile
Updates, fixes, tests.
macOS 10.6
Xcode 3.2
Have you
=> libfido2: update to 1.13.0, fix PPC; pam-u2f: update to 1.3.0; both: support tests

graphics/mupdf/Portfile
=> mupdf: update to 1.22.2

python/py-mupdf/Portfile
=> py-mupdf: update to 1.22.3

sysutils/pulumi/Portfile
=> pulumi: Update to version 3.72.2

R/R-ANOM/Portfile, R/R-BayesX/Portfile, R/R-ISwR/Portfile, R/R-MCPAN/Portfile, R/R-ParamHelpers/Portfile, R/R-SMM/Portfile, R/R-SimComp/Portfile, R/R-biomartr/Portfile, R/R-cotram/Portfile, R/R-gamboostLSS/Portfile, R/R-gamlss.data/Portfile, R/R-mboost/Portfile, R/R-mlr/Portfile, R/R-mlrMBO/Portfile, R/R-mratios/Portfile, R/R-multcomp/Portfile, R/R-nparcomp/Portfile, R/R-presmTP/Portfile, R/R-seqinr/Portfile, R/R-smoof/Portfile, R/R-stabs/Portfile, R/R-survPresmooth/Portfile, R/R-tbm/Portfile, R/R-tram/Portfile, R/R-tramnet/Portfile, R/R-trtf/Portfile, R/R-varycoef/Portfile
Updates, support for tests, new ports.
Xcode 3.2.6
Have you
=> R: few updates and new packages (I)

www/wiki-tui/Portfile
=> wiki-tui: new port (version 0.7.0)

R/R-Bhat/Portfile, R/R-CEoptim/Portfile, R/R-DPBBM/Portfile, R/R-MixSim/Portfile, R/R-NLRoot/Portfile, R/R-NPRED/Portfile, R/R-RGraphics/Portfile, R/R-SAGMM/Portfile, R/R-SemiMarkov/Portfile, R/R-TSEtools/Portfile, R/R-WgtEff/Portfile, R/R-ezglm/Portfile, R/R-fxl/Portfile, R/R-grImport/Portfile, R/R-grImport2/Portfile, R/R-gridDebug/Portfile, R/R-gridGraphviz/Portfile, R/R-gridSVG/Portfile, R/R-json64/Portfile, R/R-lowmemtkmeans/Portfile, R/R-mFilter/Portfile, R/R-momentchi2/Portfile, R/R-rai/Portfile, R/R-rexpokit/Portfile, R/R-sBIC/Portfile, R/R-valorate/Portfile
Okay, with this I am done with new packages. Next PR will be just updates.
Xcode 3.2.6
Have you
=> R: new packages (IV)

net/transmission-x11/Portfile, net/transmission-x11/files/patch-build-right-sources.diff, net/transmission-x11/files/patch-fix-flags.diff, net/transmission-x11/files/patch-fix-utils.diff
PowerPC status: CLI on PowerPC is actually working (not just building). GUI needs more work: https://trac.macports.org/ticket/67654
@i0ntempest Adding myself as a co-maintainer, since this port does not get much attention recently, but if there are any objections, I drop myself, this is not important for the PR.
macOS 10.6
Xcode 3.2
Have you
=> transmission-x11: update to 4.0.3, fix powerpc

math/ginkgo/Portfile
Update from pre-released to released version. Use `tarball_from`.
macOS 10.6
Xcode 3.2
Have you
=> ginkgo: update to 1.6.0 released, add tarball_from

devel/mogenerator/Portfile, devel/mogenerator/files/0001-Unbreak-10.7.patch
The port is currently broken almost across the board: https://ports.macports.org/port/mogenerator/details
Attempt to fix it. Sort of a blind shot in a hope the code is sane. I have only tested the build on 10.6.
macOS 10.6
Xcode 3.2
Have you
=> mogenerator: fix the port: update to 1.32 for new systems; offer versions for older

gis/grass/Portfile, gis/grass7/Portfile, gis/pdal/Portfile, gis/qgis3/Portfile, gis/saga/Portfile, python/py-pdal/Portfile
Update PDAL to version 2.5.5 and rev-bump dependents.
Have you
=> PDAL: update to version 2.5.5

math/latte-int/Portfile, math/latte-int/files/lowercased-options.diff
=> latte-int: backport configure patch, fix path to lrslib

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.12.1

python/pipenv/Portfile
=> pipenv: update to 2023.6.18

print/a2ps/Portfile
=> a2ps: update to 4.15.5

sysutils/vtm/Portfile
=> vtm: update to 0.9.9n

graphics/gimp2-devel/Portfile, graphics/gimp2-devel/files/patch-fix-pthread.diff, graphics/gimp2/Portfile, graphics/gimp2/files/patch-fix-pthread.diff
Subject :)
macOS 10.6
Xcode 3.2
Have you
=> gimp2: fix build for powerpc

R/R-BayesBP/Portfile, R/R-GenOrd/Portfile, R/R-ImpShrinkage/Portfile, R/R-KbMvtSkew/Portfile, R/R-airr/Portfile, R/R-alakazam/Portfile, R/R-bde/Portfile, R/R-dcTensor/Portfile, R/R-fastAFT/Portfile, R/R-forward/Portfile, R/R-geomtextpath/Portfile, R/R-hellno/Portfile, R/R-hopit/Portfile, R/R-jfa/Portfile, R/R-nestedLogit/Portfile, R/R-nlpred/Portfile, R/R-nnTensor/Portfile, R/R-psdr/Portfile, R/R-r6extended/Portfile, R/R-randomLCA/Portfile, R/R-robmixglm/Portfile, R/R-rsq/Portfile, R/R-simIReff/Portfile, R/R-stepjglm/Portfile, R/R-tagcloud/Portfile, R/R-voteSim/Portfile
New ports.
Xcode 3.2.6
Have you
=> R: new packages (2)

devel/wolfssl/Portfile
=> wolfssl: update to version 5.6.3

java/pdfbox/Portfile
=> pdfbox: update url to legitimate homepage

devel/global/Portfile
=> global: update to 6.6.10 and python3.11

R/R-BayesianTools/Portfile, R/R-DHARMa/Portfile, R/R-GLMMadaptive/Portfile, R/R-IDPmisc/Portfile, R/R-JMbayes2/Portfile, R/R-TrendTM/Portfile, R/R-adjclust/Portfile, R/R-btergm/Portfile, R/R-capushe/Portfile, R/R-denstrip/Portfile, R/R-dtwclust/Portfile, R/R-ergMargins/Portfile, R/R-ergm.userterms/Portfile, R/R-gap.datasets/Portfile, R/R-gap/Portfile, R/R-ggfittext/Portfile, R/R-latentnet/Portfile, R/R-mcmcplots/Portfile, R/R-netmediate/Portfile, R/R-pcnetmeta/Portfile, R/R-qgam/Portfile, R/R-relevent/Portfile, R/R-rnmamod/Portfile, R/R-sensitivity/Portfile, R/R-shades/Portfile, R/R-slm/Portfile, R/R-softImpute/Portfile
New ports.
Xcode 3.2.6
Have you
=> R: new packages (3)

R/R-DPQ/Portfile, R/R-FastGaSP/Portfile, R/R-FastJM/Portfile, R/R-RobStatTM/Portfile, R/R-RobustGaSP/Portfile, R/R-brms/Portfile, R/R-cequre/Portfile, R/R-cvCovEst/Portfile, R/R-emmeans/Portfile, R/R-facmodCS/Portfile, R/R-flexmsm/Portfile, R/R-fuzzr/Portfile, R/R-glmmrBase/Portfile, R/R-medflex/Portfile, R/R-multigraph/Portfile, R/R-parallelpam/Portfile, R/R-paropt/Portfile, R/R-pyinit/Portfile, R/R-rODE/Portfile, R/R-robust/Portfile, R/R-rrcovNA/Portfile, R/R-spaMM/Portfile, R/R-terra/Portfile, R/R-usethis/Portfile
=> R: updates and few new packages (4)

python/py-mupdf/Portfile
=> py-mupdf: update to 1.22.5

x11/homebank/Portfile
=> homebank: update to 5.6.5

R/R-AnnotationForge/Portfile, R/R-DBI/Portfile, R/R-PlaneGeometry/Portfile, R/R-cgalMeshes/Portfile, R/R-cgalMeshes/files/patch-no-randomcoloR.diff, R/R-ggfun/Portfile, R/R-mirai/Portfile, R/R-rrcov/Portfile
=> R: weekend’s updates to existing packages

sysutils/vtm/Portfile
=> vtm: update to 0.9.9o

www/tenfourfox/Portfile
Update.
It took many hours, but yes, I confirmed it builds and works normally.
macOS 10.6
Xcode 3.2
Have you
=> tenfourfox-devel: update to latest upstream (2023.04.20)

sysutils/xorriso/Portfile
=> xorriso: update to 1.5.6.pl02

devel/libsdl2/Portfile, devel/libsdl2/files/patch-revert-issue-6948.diff
- Fixes builds for 10.7/10.8
- Closes: https://trac.macports.org/ticket/67666
=> libsdl2: patch to revert upstream fix for sdl issue 6948

devel/icu/Portfile
Closes: https://trac.macports.org/ticket/67557
Have you
=> icu: update to 73.2

python/py-pydicom/Portfile
=> py-pydicom: 2.4.1

python/py-h5py/Portfile, python/py-h5py/files/patch-oldest-supported-numpy.diff
=> py-h5py: 3.9.0; py38+

devel/got/Portfile
=> got: update to version 0.90

devel/sbt/Portfile
=> sbt: update to 1.9.1

devel/cppzmq/Portfile
=> cppzmq: update to 4.10.0

devel/libwired/Portfile, net/wire/Portfile, net/wire/files/config.m4, net/wire/files/patch-configure.ac.diff, net/wire/files/patch-makefile.in.diff, net/wired-server/Portfile, net/wired-server/files/config.m4, net/wired-server/files/patch-configure.ac.diff, net/wired-server/files/patch-makefile.in.diff, www/Deriv/Portfile, www/Deriv/files/patch-fix-linking.diff
Let’s see if these build on newer systems.
UPD. Yay, all good.
macOS 10.6
Xcode 3.2
Have you
=> libwired, wire, wired-server, Deriv: new ports

devel/jreleaser/Portfile
macOS 11.6.5 20G527 x86_64
Have you
=> jreleaser: update to version v1.7.0

devel/nettle/Portfile
=> nettle: update to 3.9.1

gis/gdal-grass/Portfile, gis/grass/Portfile, gis/grass/files/01_patch-dyld-link.diff, gis/qgis3/Portfile
`grass`:
- Update to version 8.3.0
- Make the port `sqlite3` a "hardwired" dependant, remove the variant.
- Add Python 3.11 variant.
Rev-bump dependants `gdal-grass` and `qgis3` and  add new default Python 3.11 variant to QGIS, to keep in sync  with GDAL and GRASS.
Have you
=> grass: update to 8.3.0

science/socnetv/Portfile
=> socnetv: new port

python/py-ansible-core/Portfile, python/py-ansible/Portfile
=> py-ansible: update to 8.1.0, py-ansible-core: update to 2.15.1 

lang/julia/Portfile, lang/julia/files/patch-Makefile.diff
- Update maintainers
No new `revision` as this does not change any of the files installed. Added myself as as co-maintainer for this port.
Cross reference: https://github.com/JuliaLang/julia/pull/50017
clang-1000.11.45.5
Have you
=> julia: Simplify Makefile patch

R/R-GiRaF/Portfile, R/R-Rcpp11/Portfile, R/R-comat/Portfile, R/R-desla/Portfile, R/R-dlib/Portfile, R/R-gamreg/Portfile, R/R-gdalraster/Portfile, R/R-geoR/Portfile, R/R-motif/Portfile, R/R-neojags/Portfile, R/R-neojags/files/patch-fix-Makevars.diff, R/R-ordinalCont/Portfile, R/R-perry/Portfile, R/R-perryExamples/Portfile, R/R-pompp/Portfile, R/R-rDEA/Portfile, R/R-robustHD/Portfile, R/R-rrcovHD/Portfile, R/R-sparseLTSEigen/Portfile, R/R-spls/Portfile, R/R-srlars/Portfile, R/R-stokes/Portfile, R/R-tramME/Portfile, R/R-truncreg/Portfile
New ports.
Xcode 3.2.6
Have you
=> R: new packages (4)

science/memesuite/Portfile
Updated to version 5.5.3 of the MEME Suite
- [ x] bugfix
- [x ] enhancement
Xcode 14.3.1 14E300c / Command Line Tools 14.3.1.0.1.1683849156
Have you
- [ x] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [x ] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [ x] checked your Portfile with `port lint --nitpick`?
- [ x] tried existing tests with `sudo port test`?
- [x ] tried a full install with `sudo port -vst install`?
- [ x] tested basic functionality of all …
=> memesuite: Update to 5.5.3

sysutils/vtm/Portfile
=> vtm: update to 0.9.9q

R/R-DendSer/Portfile, R/R-FLAME/Portfile, R/R-Gini/Portfile, R/R-IndGenErrors/Portfile, R/R-LNPar/Portfile, R/R-ParallelLogger/Portfile, R/R-RDieHarder/Portfile, R/R-SSGL/Portfile, R/R-TruncatedNormal/Portfile, R/R-VARshrink/Portfile, R/R-ars/Portfile, R/R-bizdays/Portfile, R/R-cdgd/Portfile, R/R-corrViz/Portfile, R/R-countSTAR/Portfile, R/R-dbacf/Portfile, R/R-dprop/Portfile, R/R-heteromixgm/Portfile, R/R-mlt.docreg/Portfile, R/R-rbmn/Portfile, R/R-rcheology/Portfile, R/R-rrat/Portfile, R/R-runMCMCbtadjust/Portfile, R/R-skewlmm/Portfile, R/R-spikeSlabGAM/Portfile, R/R-ssh/Portfile
With this one, I think to retire for a while from adding new R ports. (Updates will be done with feasible regularity – I just want to switch to working on other ports more.)
Xcode 3.2.6
Have you
=> R: new packages (5)

R/R-RcmdrPlugin.DCCV/Portfile, R/R-RcmdrPlugin.EZR/Portfile, R/R-RcmdrPlugin.FactoMineR/Portfile, R/R-RcmdrPlugin.MA/Portfile, R/R-RcmdrPlugin.MPAStats/Portfile, R/R-RcmdrPlugin.PcaRobust/Portfile, R/R-RcmdrPlugin.ROC/Portfile, R/R-RcmdrPlugin.coin/Portfile, R/R-RcmdrPlugin.cpd/Portfile, R/R-RcmdrPlugin.survival/Portfile, R/R-RcmdrPlugin.temis/Portfile
Another attempt, see if CI again freeze for no reason.
macOS 10.6
Xcode 3.2
Have you
=> R: support more plug-ins for Rcmdr

security/Vidalia/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> Vidalia: update to 0.2.21

R/R-BiocIO/Portfile, R/R-GDINA/Portfile, R/R-ReMFPCA/Portfile, R/R-Rhtslib/Portfile, R/R-Rsamtools/Portfile, R/R-TSrepr/Portfile, R/R-bioDist/Portfile, R/R-deSolve/Portfile, R/R-decor/Portfile, R/R-dtt/Portfile, R/R-ecp/Portfile, R/R-esc/Portfile, R/R-future/Portfile, R/R-glmmrBase/Portfile, R/R-gmp/Portfile, R/R-mkde/Portfile, R/R-mombf/Portfile, R/R-netseg/Portfile, R/R-rgeoda/Portfile, R/R-vstdct/Portfile, R/R-wavelets/Portfile
Updates, mostly. _A few new ports smuggled in the process._
macOS 10.6
Xcode 3.2
Have you
=> R: weekend updates

math/hypre/Portfile
Also just an update.
macOS 10.6
Xcode 3.2
Have you
=> hypre: update to 2.29.0

science/scifor/Portfile
Update. (Sorry for mistaken clicks on options. This is a simple update.)
macOS 10.6
Xcode 3.2
Have you
=> scifor: update to 4.10.8

math/nickle/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> nickle: update to 2.92

math/nanoflann/Portfile
Simple update.
macOS 10.6
Xcode 3.2
Have you
=> nanoflann: update to 1.5.0

math/fxt/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> fxt: update to 2023.06.27

math/NTPoly/Portfile
_All of a sudden, so many ports turned out to be out of date._
macOS 10.6
Xcode 3.2
Have you
=> NTPoly: update to 3.0.0

math/blaspp/Portfile
=> blaspp: update to 2023.06.00

fortran/runge-kutta-fortran/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> runge-kutta-fortran: update to 2023.07.02

net/amule/Portfile, net/toxic/Portfile, net/toxic/files/0002-Config-make-paths-sane.patch
Since they install desktop files, utilize those.
macOS 10.6
Xcode 3.2
Have you
=> amule, toxic: depend on desktop-file-utils

mail/opensmtpd/Portfile
* closes: https://trac.macports.org/ticket/67614
Have you
=> opensmtpd: update to version 7.3.0p1

mail/fdm/Portfile
=> fdm: update to 2.2

net/avahi/Portfile
* Eliminate python-related copy-pasta, to simplify maintenance
=> avahi: cleanup python-related copy-pasta

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.1.11

lang/logtalk/Portfile
=> logtalk: update to 3.67.0

fortran/cafut/Portfile, fortran/fitpack/Portfile, fortran/slsqp/Portfile
Updates.
macOS 10.6
Xcode 3.2
Have you
=> Fortran: update a few FPM packages

R/R-BASS/Portfile, R/R-MendelianRandomization/Portfile, R/R-MetricGraph/Portfile, R/R-WienR/Portfile, R/R-bamlss/Portfile, R/R-biomaRt/Portfile, R/R-countrycode/Portfile, R/R-dcmle/Portfile, R/R-emdbook/Portfile, R/R-exactextractr/Portfile, R/R-fdacluster/Portfile, R/R-fsr/Portfile, R/R-glmmrOptim/Portfile, R/R-gms/Portfile, R/R-jaccard/Portfile, R/R-jack/Portfile, R/R-ldt/Portfile, R/R-lpjmlkit/Portfile, R/R-magclass/Portfile, R/R-overdisp/Portfile, R/R-quitte/Portfile, R/R-raster/Portfile, R/R-rasterVis/Portfile, R/R-rhdf5filters/Portfile, R/R-sfaR/Portfile, R/R-sfnetworks/Portfile
Updates and some new ports.
macOS 10.6
Xcode 3.2
Have you
=> R: updates to existing packages and a few new ones

sysutils/vtm/Portfile
=> vtm: update to 0.9.9r

math/polysolve/Portfile, math/polysolve/files/patch-CMakeLists.diff
New port.
macOS 10.6
Xcode 3.2
Have you
=> polysolve: new port in math

net/snac/Portfile
=> snac: update to version 2.36

games/fortune-mod/Portfile
=> fortune-mod: update to 3.20.0

multimedia/gpac/Portfile
=> gpac: update to 2.2.1

databases/barman/Portfile
=> barman: update to 3.6.0

lang/odin/Portfile
=> odin: update to 0.2023.05

math/libKriging/Portfile, math/libKriging/files/patch-CMakeLists.diff
New port in math.
macOS 10.6
Xcode 3.2
Have you
=> libKriging: new port in math

devel/raja/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> raja: update to 2023.06.0

gnome/gnome-voice/Portfile
gnome-voice 1.5.0 from upstream development site (https://www.gnomevoice.org/src/gnome-voice-1.5.0.tar.xz).
Have you
=> gnome-voice: update to 1.5.0

science/basix/Portfile
New port.
Xcode 3.2.6
Have you
=> basix: new port in science

science/proxmark3-iceman/Portfile
=> proxmark3-iceman: update to 4.16717

mail/imapdedup/Portfile, mail/offlineimap/Portfile
=> imapdedup: update to 20230707; offlineimap: update to 8.0.0-20230519

science/luma/Portfile, science/luma/files/patch-fix-includes.diff, science/luma/files/patch-makefile.diff, science/luma/files/patch-tests.diff
Let’s see if this one builds.
Xcode 3.2
Have you
=> luma: new port in science

textproc/pandoc/Portfile
Closed: https://trac.macports.org/ticket/67710
Xcode 15.0 15A5160n
Have you
=> pandoc: Switch to binary release, update to 3.1.5

R/R-GaussianHMM1d/Portfile, R/R-OpenImageR/Portfile, R/R-Pijavski/Portfile, R/R-RSiena/Portfile, R/R-StableEstim/Portfile, R/R-TempStable/Portfile, R/R-TempStable/files/patch-no-v8.diff, R/R-aldvmm/Portfile, R/R-baygel/Portfile, R/R-bsplinePsd/Portfile, R/R-cbass/Portfile, R/R-cocosoR/Portfile, R/R-cryptography/Portfile, R/R-deTestSet/Portfile, R/R-duckplyr/Portfile, R/R-einsum/Portfile, R/R-elrm/Portfile, R/R-fanovaGraph/Portfile, R/R-fergm/Portfile, R/R-gcTensor/Portfile, R/R-gsl/Portfile, R/R-lcra/Portfile, R/R-matrixset/Portfile, R/R-misty/Portfile, R/R-snfa/Portfile, R/R-unmarked/Portfile, R/R-vistla/Portfile
Updates and some new packages.
macOS 10.6
Xcode 3.2
Have you
=> R: updates to packages and some new ones

sysutils/monit/Portfile
=> monit: update to 5.33.0

science/hdf5/Portfile
Closes https://trac.macports.org/ticket/67273
=> hdf5: Default to +fortran

science/exonerate/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> exonerate: update to 2.4.0

math/basiclu/Portfile, math/basiclu/files/patch-use-right-cc.diff
New port.
macOS 10.6
Xcode 3.2
Have you
=> basiclu: new port in math

devel/tatami/Portfile, devel/tatami/files/patch-fix-includes.diff
New ports.
macOS 10.6
Xcode 3.2
Have you
=> tatami, tatami-devel: new ports

lang/ruby-devel/Portfile
=> ruby-devel: update to current upstream (2023.07.12)

net/mhxd/Portfile, www/Obsession/Portfile
Update `Obsession`. Also add hotline sub-category to another Hotline client, `mhxd`.
(UPD. I will wait until CI complete for `Obsession` first, and then add a category to `mhxd`, skipping CI for that.)
macOS 10.6
Xcode 3.2
Have you
=> Obsession: update to latest upstream

R/R-DEoptimR/Portfile, R/R-DelayedArray/Portfile, R/R-HDF5Array/Portfile, R/R-beachmat/Portfile, R/R-clubSandwich/Portfile, R/R-fMultivar/Portfile, R/R-jtools/Portfile, R/R-multiplex/Portfile, R/R-r2mlm/Portfile, R/R-sf/Portfile, R/R-stars/Portfile
Updates.
macOS 10.6
Xcode 3.2
Have you
=> R: update existing packages

R/R-AlgDesign/Portfile, R/R-BayesSurvival/Portfile, R/R-DoE.wrapper/Portfile, R/R-FrF2/Portfile, R/R-FuzzySimRes/Portfile, R/R-QCA/Portfile, R/R-ROI.plugin.quadprog/Portfile, R/R-Rborist/Portfile, R/R-SparseMDC/Portfile, R/R-cbcTools/Portfile, R/R-deductive/Portfile, R/R-doRNG/Portfile, R/R-doRedis/Portfile, R/R-ingredients/Portfile, R/R-ipc/Portfile, R/R-mcunit/Portfile, R/R-mob/Portfile, R/R-nanonext/Portfile, R/R-pammtools/Portfile, R/R-redux/Portfile, R/R-rsm/Portfile, R/R-rsurface/Portfile, R/R-simctest/Portfile, R/R-stringstatic/Portfile, R/R-timsac/Portfile, R/R-tipitaka/Portfile
=> R: new packages and a few updates

math/finufft/Portfile, math/finufft/files/patch-makefile.diff
New port: https://github.com/flatironinstitute/finufft
macOS 10.6
Xcode 3.2
Have you
=> finufft: new port in math

aqua/wezterm/Portfile
=> wezterm: update to 20230712-072601-f4abf8fd

math/igraph/Portfile, python/py-igraph/Portfile
=> igraph and py-igraph 0.10.6

devel/ghidra/Portfile
=> ghidra: update to 10.3.2

net/snac/Portfile
=> snac: update to version 2.37

devel/chai/Portfile, devel/chai/files/patch-avoid-dupe-camp.diff
New port.
macOS 10.6
Xcode 3.2
Have you
=> chai: new port in devel

net/nghttp3/Portfile, net/ngtcp2/Portfile
Simple updates to both.
macOS 10.6
Xcode 3.2
Have you
=> nghttp3, ngtcp2: update to latest versions

science/elmerfem/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> elmerfem: update to 2023.07.12

sysutils/vtm/Portfile
=> vtm: update to 0.9.9s

devel/poco/Portfile
(_Why on earth did it even have arch restriction?_)
macOS 10.6
Xcode 3.2
Have you
=> poco: fix tests, fix powerpc, add mongodb variant

devel/mimalloc/Portfile, devel/mimalloc/files/0001-prim.h-support-tls_slot-for-PPC.patch, devel/mimalloc/files/0002-Easy-on-stress-testing-for-older-systems.patch
Fixes: https://trac.macports.org/ticket/67220
macOS 10.6
Xcode 3.2
Have you
=> mimalloc: enable testing; fix build for older systems and PPC

security/s2n-tls/Portfile, security/s2n-tls/files/patch-fix-target-flags.diff
Fix the port for older OS, support testing.
macOS 10.6
Xcode 3.2
Have you
=> s2n-tls: fix build for darwin < 16, add support for tests

sysutils/osinfo-db/Portfile
=> osinfo-db: update to 20230518

lang/crystal/Portfile
=> crystal: update to 1.9.0

net/gensync/Portfile
macOS 13.0.1 22A400 arm64
Have you
=> gensync: new port

games/fheroes2/Portfile
=> fheroes2: update to 1.0.6

lang/MoarVM/Portfile, lang/nqp/Portfile, lang/rakudo/Portfile
Simple updates, no other changes.
macOS 10.6
Xcode 3.2
Have you
=> rakudo and friends: update to 2023.06

fortran/runge-kutta-fortran/Portfile
Update. Since releases now are done by upstream without ages of delay, switch to releases.
macOS 10.6
Xcode 3.2
Have you
=> runge-kutta-fortran: switch to releases, update to 0.4

devel/rapidjson-devel/Portfile
Simple update.
macOS 10.6
Xcode 3.2
Have you
=> rapidjson-devel: update to 20230717

devel/oxen-logging/Portfile
New port.
Xcode 3.2.6
Have you
=> oxen-logging: new port in devel

math/pari/Portfile
Closes: https://trac.macports.org/ticket/54022
Have you
=> pari: update to 2.15.4

net/snac/Portfile
=> snac: update to version 2.38

audio/libopenmpt/Portfile
Update, fix alignments in portfile.
macOS 10.6
Xcode 3.2
Have you
=> libopenmpt: update to 0.7.2

net/openssh/Portfile
=> openssh: update to 9.3p2

devel/got/Portfile
=> got: update to 0.91

R/R-Directional/Portfile, R/R-EXPARMA/Portfile, R/R-GDPuc/Portfile, R/R-L2hdchange/Portfile, R/R-RBesT/Portfile, R/R-RMariaDB/Portfile, R/R-Rpcop/Portfile, R/R-SEMID/Portfile, R/R-clubSandwich/Portfile, R/R-cpp11/Portfile, R/R-ctmva/Portfile, R/R-dsfa/Portfile, R/R-frab/Portfile, R/R-fs/Portfile, R/R-fs/files/0003-libuv-link-to-legacysupport.patch, R/R-gnlm/Portfile, R/R-gratia/Portfile, R/R-lavaan/Portfile, R/R-lintr/Portfile, R/R-minimaxApprox/Portfile, R/R-numGen/Portfile, R/R-princurve/Portfile, R/R-qlcal/Portfile, R/R-quickcode/Portfile, R/R-rnaturalearth/Portfile, R/R-runMCMCbtadjust/Portfile, R/R-seriation/Portfile
=> R: today’s updates and some new packages

security/easy-rsa/Portfile, security/easy-rsa/files/patch-set-macports-paths.diff
Long due update.
macOS 10.6
Xcode 3.2
Have you
=> easy-rsa: update to 3.1.5

devel/re2c/Portfile
=> re2c: update to 3.1

R/R-PMA/Portfile, R/R-SVDNF/Portfile, R/R-SpatialBSS/Portfile, R/R-cpd/Portfile, R/R-ellipse/Portfile, R/R-gargle/Portfile, R/R-migraph/Portfile, R/R-r2mlm/Portfile, R/R-reclin2/Portfile, R/R-rempsyc/Portfile, R/R-rsconnect/Portfile
Updates.
macOS 10.6
Xcode 3.2
Have you
=> R: some updates for existing packages

graphics/rawtherapee/Portfile, graphics/rawtherapee/files/no-modified-project_source_dir.diff, graphics/rawtherapee/files/patch-config_h_in.diff
* Closes: https://trac.macports.org/ticket/65851
* Closes: https://trac.macports.org/ticket/66760
Have you
=> rawtherapee: update to 5.9

lang/crystal/Portfile
=> crystal: update to 1.9.2

sysutils/coreutils-uutils/Portfile
=> coreutils-uutils: update to 0.0.20

devel/symfony-cli/Portfile
=> symfony-cli: update to 5.5.7

graphics/glslang/Portfile
=> glslang: update to 12.3.0

sysutils/vtm/Portfile
=> vtm: update to 0.9.9t

graphics/rawtherapee/Portfile
So happy to see this port working again!
Based on the output from the configure phase, a number of ports need to be added as lib deps. This PR takes care of that.
=> rawtherapee: add missing lib deps

sysutils/apcupsd/Portfile, sysutils/apcupsd/files/apcagent-makefile.diff, sysutils/apcupsd/files/apcupsd-plist.diff, sysutils/apcupsd/files/darwin-makefile.diff
New port for [apcupsd](http://www.apcupsd.org)
macOS 13.4.1 22F2083 arm64
Have you
=> apcupsd: new port in sysutils

science/madness/Portfile
Update.
macOS 10.6
Xcode 3.2
Have you
=> madness: update to current upstream (2023.07.17)

graphics/glslang/Portfile
=> glslang: update to 12.3.1

python/py-awscli2/Portfile, python/py-awscrt/Portfile
=> py-awscli2: update to 2.13.3

devel/osc/Portfile
=> osc: update to 1.2.0

devel/sbt/Portfile
=> sbt: update to 1.9.2

graphics/openvdb/Portfile
* This commit enables the building of one of the subcomponents of OpenVDB, called NanoVDB. It has been added to the default variants because at least one port that depends on OpenVDB, Blender, is already able to use NanoVDB for GPU-accelerated real-time rendering of volumetric effects.
* Made dependencies on port:imath and port:openexr into an (optional) variant. Previously, these were set as hard dependencies in the Portfile, but they weren't actually being used because the `-DUSE_EXR` CMake option wasn't set to `ON`.
* Removed building the Python module from the default variants. None of the ports that use OpenVDB as a dependency are using the Python module.
Have you
=> openvdb: add new variants +nanovdb, +utils, etc.

devel/sbt/Portfile
=> sbt: update to 1.9.3

databases/postgis3/Portfile, python/py-gdal/Portfile
Add `compiler.thread_local_storage yes` to use compiler supporting thread-local storage.
Closes: https://trac.macports.org/ticket/67781 and https://trac.macports.org/ticket/67782
Have you
=> postgis3, py-gdal: use compiler supporting thread-local storage

lang/mlton-bootstrap/Portfile, lang/mlton-bootstrap/files/patch-20070826.diff, lang/mlton-bootstrap/files/patch-20100608.diff, lang/mlton-bootstrap/files/patch-20180207.diff, lang/mlton-bootstrap/files/patch-aarch64.diff, lang/mlton-bootstrap/files/patch-x86_64.diff, lang/mlton/Portfile, lang/mlton/files/patch-settings-for-Macports.diff
Let’s see if this builds :)
macOS 10.6
Xcode 3.2
macOS 10.8.5
Xcode 5.1.1
Have you
=> mlton: new port in lang, implementation of Standard ML

gis/grass7/Portfile, gis/grass7/files/patch_implicit_int.diff
Implicit int (-Wimplicit-int) is considered an error with Clang 16+.
Backport of https://github.com/OSGeo/grass/commit/594c947ce8984f07faf28d7d71e4c902f4532069.
Closes https://trac.macports.org/ticket/67791
Have you
=> grass7: fix invalid implicit int

lang/twelf/Portfile
New port.
macOS 10.6
Xcode 3.2
Have you
=> twelf: new port in lang/math

math/pari-extra/Portfile
This is a meta port which contains all pari packages as subports.
Closes: https://trac.macports.org/ticket/45472
Have you
=> pari-extra: new submission

lang/logtalk/Portfile
=> logtalk: update to 3.68.0

python/py-hypothesis/Portfile, python/py-pathvalidate/Portfile
=> py-pathvalidate: update to 3.1.0; py-hypothesis: update to 6.82.0; pin py38 subport

math/tapkee/Portfile
New port.
macOS 10.6
Xcode 3.2
Have you
=> tapkee: new port in math

graphics/ogre/Portfile
=> ogre: update to 14.0.1

devel/datree/Portfile
=> datree: update to 1.9.19
