devel/onetbb/Portfile
devel/onetbb/files/patch-cmake-compilers.diff
devel/onetbb/files/patch-onetbb-older-platforms.diff

onetbb: update to 2021.10.0

---

multimedia/libcaption/Portfile

libcaption: build as a shared lib

---

net/rpki-client/Portfile

rpki-client: update to 8.5

---

lang/sbcl/Portfile
lang/sbcl/files/0001-fix-building-when-root-directory-contain-non-ASCII-c.patch
lang/sbcl/files/0002-add-MacPorts-XDG_DATA_DIRS.patch
lang/sbcl/files/0003-Use-CLOCK_MONOTONIC-when-CLOCK_PROCESS_CPUTIME_ID-un.patch
lang/sbcl/files/1001-x86-Darwin-Revert-x86-darwin-files.patch
lang/sbcl/files/1002-x86-Darwin-Revert-Perform-darwin-related-housekeepin.patch
lang/sbcl/files/1003-x86-Darwin-Remove-mach-exception-handler.patch
lang/sbcl/files/1004-Darwin-use-libc-nanosleep-before-10.6-and-on-PPC.patch
lang/sbcl/files/1005-Darwin-recovery-support-non-dispatch-semaphores.patch
lang/sbcl/files/1006-x86-Darwin-mask-out-O_LARGEFILE-in-fcntl.1-test.patch
lang/sbcl/files/1007-x86-Darwin-revert-OS_THREAD_STACK.patch
lang/sbcl/files/1008-x86-Darwin-fix-build-by-old-preprocessor.patch
lang/sbcl/files/1009-x86-Darwin-disable-failing-stat-mode-tests.patch
lang/sbcl/files/1010-x86-Darwin-add-missed-OS_CONTEXT_PC.patch
lang/sbcl/files/1011-x86-Darwin-fix-syntax-typos.patch
lang/sbcl/files/1012-ppc-Darwin-Revert-Delete-support-for-and-darwin-ppc.patch
lang/sbcl/files/1013-ppc-Darwin-Config.ppc-follow-up-changes.patch
lang/sbcl/files/1014-ppc-Darwin-ppc-assem.S-fix-wrong-assembler-code-chun.patch
lang/sbcl/files/1015-ppc-Darwin-Misc-fixes-for-PPC.patch
lang/sbcl/files/1016-ppc-Darwin-ppc-assem-a-minor-fix-to-assembler-syntax.patch
lang/sbcl/files/1017-Fix-building-by-lisp-without-endian-features.patch
lang/sbcl/files/1018-ppc-Darwin-fix-threads-support.patch
math/fricas/Portfile
math/maxima/Portfile

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809
Have you

sbcl: update to 2.3.7

---

databases/iowow/Portfile
databases/iowow/files/0001-Do-not-use-clangism-with-GCC.patch
databases/iowow/files/0002-unix.c-fix-for-Control-reaches-the-end-of-a-non-void.patch
databases/iowow/files/0003-Fix-MurMurHash3-for-Big-endian.patch

New port.
macOS 10.6
Xcode 3.2
Have you
P. S. On PowerPC several test cases fail:
https://github.com/Softmotions/iowow/issues/54

iowow: new port in databases/devel

---

databases/postgis3/Portfile

Update to PostGIS version 3.3.4.
Have you

postgis3: update to version 3.3.4

---

databases/tiledb/Portfile
databases/tiledb/files/0001-Add-a-fix-for-32-bit.patch
databases/tiledb/files/patch-linking.diff

New port.
macOS 10.6
Xcode 3.2
Have you

tiledb: new port in databases

---

python/py-emoji/Portfile

py-emoji: Update to version 2.7.0; Add Python 311; Delete Python 37

---

python/py-cryptg/Portfile
python/py-telethon/Portfile

py-telethon: Update to version 1.29.2; Add Python 311

---

graphics/openexr/Portfile

Use the modern one-line description from the OpenEXR project repo/website https://github.com/AcademySoftwareFoundation/openexr.
macOS 12.6.7 21G651 arm64
Have you

openexr: Update Portfile description

---

net/miniupnpc/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

miniupnpc: update to 2.2.5

---

devel/marksman/Portfile

Marksman is a program that integrates with your editor to assist you in writing and maintaining your Markdown documents. Using LSP protocol it provides completion, goto definition, find references, rename refactoring, diagnostics, and more. In addition to regular Markdown, it also supports wiki-link-style references that enable Zettelkasten-like note taking.
See https://github.com/artempyanykh/marksman
Have you

marksman: New port (v2023-07-25)

---

python/py-hdbscan/Portfile
python/py-hdbscan/files/patch-pyproject_toml.diff

py-hdbscan: Update to version 0.8.33; Add Python 311; Delete Python 37

---

fortran/runge-kutta-fortran/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

runge-kutta-fortran: update to 0.6

---

python/py-keras_preprocessing/Portfile

py-keras_preprocessing: Add Python 311; Delete Python 37

---

python/py-keras_applications/Portfile

py-keras_applications: Add Python 311; Delete Python 37

---

python/py-astunparse/Portfile

py-astunparse: Add Python 311; Delete Python 37

---

python/py-pulp/Portfile
python/py-quantecon/Portfile
python/py-rasterstats/Portfile

New python ports

---

net/nghttp3/Portfile
net/ngtcp2/Portfile

Updates.
macOS 10.6
Xcode 3.2
Have you

nghttp3: update to 0.14.0; ngtcp2: update to 0.18.0

---

python/py-pytest-flake8/Portfile

py-pytest-flake8: Add Python 311

---

sysutils/pv/Portfile
sysutils/pv/files/src_pv_display.c.patch

pv: update to 1.7.24

---

net/grafana/Portfile
net/grafana/files/grafana.ini.diff
net/grafana/files/org.macports.grafana.plist

macOS 13.5
Xcode 14.3.1 
Have you

grafana: update to 10.0.3

---

emulators/tnylpo/Portfile

tnylpo: update to 1.1.5

---

python/py-pytest-mypy/Portfile

py-pytest-mypy: Update to version 0.10.3; Add Python 311

---

python/py-curio/Portfile

py-curio: Update to version 1.6; Add Python 311

---

python/py-python-socks/Portfile

py-python-socks: Update to version 2.3.0; Add Python 311

---

python/py-portalocker/Portfile

py-portalocker: Update to version 2.7.0; Add Python 311

---

python/py-rtree/Portfile

Add Python 3.11 variant to `py-rtree`
macOS x.y
Have you

py-rtree: add Python 3.11

---

python/py-absl/Portfile

* Update to version 1.4.0
* Add Python 311
Have you

py-absl: Update to version 1.4.0

---

python/py-custom_inherit/Portfile

py-custom_inherit: Submission

---

python/py-elastic-transport/Portfile
python/py-elasticsearch/Portfile

py-elasticsearch: Update to version 8.9.0; Add Python 311

---

net/snac/Portfile

snac: update to 2.39

---

net/spegla/Portfile
net/spegla/files/0001-Fix-build-with-Apple-clang.patch
net/spegla/files/0002-Add-MacOS-makefile.patch
net/spegla/files/0003-Handle-strlcpy.h-coherently.patch

New port.
macOS 10.6
Xcode 3.2
Have you

spegla: new port in net

---

gnome/garagejam/Portfile

GarageJam 0.4.0 - new port from upstream release https://www.garagejam.org/src/garagejam-0.4.0.tar.xz
Have you

garagejam: new port (0.4.0)

---

devel/libucl/Portfile

changelog: https://github.com/vstakhov/libucl/commit/f7dbb7d987e15ceb9ed4f07ce2513bbcd901de7d

libucl: update to 0.8.2

---

lang/julia/Portfile

julia: Add notes for Apple Silicon acceleration

---

python/py-fortranformat/Portfile

Long due update.
macOS 10.6
Xcode 3.2
Have you

py-fortranformat: update to 2.0.0

---

lang/fortran-stdlib/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib: update to 2023.08.08

---

python/py-nltk/Portfile

py-nltk: Update to version 3.8.1; Add Python 311

---

net/openssh/Portfile

* closes: https://trac.macports.org/ticket/67877
Have you

openssh: update to 9.4

---

x11/homebank/Portfile

homebank: update to 5.6.6

---

science/madness/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

madness: update to 2023.08.09

---

R/R-Biostrings/Portfile
R/R-Delaporte/Portfile
R/R-FuzzySimRes/Portfile
R/R-PlaneGeometry/Portfile
R/R-RcppArmadillo/Portfile
R/R-UPG/Portfile
R/R-aplot/Portfile
R/R-apollo/Portfile
R/R-baizer/Portfile
R/R-bookdown/Portfile
R/R-brms/Portfile
R/R-cpp11/Portfile
R/R-effectsize/Portfile
R/R-future.callr/Portfile
R/R-ggfun/Portfile
R/R-ggplotify/Portfile
R/R-igraph/Portfile
R/R-piar/Portfile
R/R-purrr/Portfile
R/R-survstan/Portfile
R/R-tidytree/Portfile
R/R-tinytex/Portfile
R/R-tpn/Portfile
R/R-xfun/Portfile
R/R-yulab.utils/Portfile

Updates.
macOS 10.6
Xcode 3.2
Have you

R: update recently updated packages (III)

---

python/py-plotly/Portfile

py-plotly: update to 5.15.0, add Py 3.11

---

math/eigenmath/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

eigenmath: update to 2023.08.03

---

devel/chai/Portfile

(Git fetch is used, so no checksums to update.)
macOS 10.6
Xcode 3.2
Have you

chai: update to 2023.06.0

---

lua/stylua/Portfile

stylua: update to 0.18.1

---

python/py-awscli2/Portfile

macOS 13.5 22G74 x86_64
Have you

py-awscli2: update to 2.13.9

---

_resources/port1.0/checks/implicit_function_declaration/macosx12.1.sdk.list
_resources/port1.0/checks/implicit_function_declaration/macosx12.3.sdk.list
_resources/port1.0/checks/implicit_function_declaration/macosx13.0.sdk.list
_resources/port1.0/checks/implicit_function_declaration/macosx13.1.sdk.list
_resources/port1.0/checks/implicit_function_declaration/macosx13.3.sdk.list

Add the missing SDK symlinks/files
- macosx12.1.sdk.list
- macosx12.3.sdk.list
- macosx13.sdk.list
- macosx13.0.sdk.list
- macosx13.1.sdk.list
macOS x.y

Add implicit func decl whitelist files - missing SDKs

---

science/DMFTtools/Portfile
science/DMFTtools/files/patch-dmft_tools.pc.diff
science/DMFTtools/files/patch-prefix.diff

New port.
Xcode 3.2.6
Have you

DMFTtools: new port in science

---

math/superlu_dist/Portfile

Closes: https://trac.macports.org/ticket/67526
_Finally, someone has to update it._
macOS 10.6
Xcode 3.2
Have you

superlu_dist: update to 8.1.2

---

lisp/cl-webengine/Portfile

cl-webengine: define minimum supported Qt5 version

---

devel/pnpm/Portfile

Have you
```
> sudo port install pnpm                                                                                                   ✘ 127  10:57:38
Password:
--->  Computing dependencies for pnpm
--->  Fetching archive for pnpm
--->  Attempting to fetch pnpm-8.6.12_0.darwin_22.arm64.tbz2 from https://packages.macports.org/pnpm
--->  Attempting to fetch pnpm-8.6.12_0.darwin_22.arm64.tbz2 from http://mirror.fcix.net/macports/packages/pnpm
--->  Attempting to fetch pnpm-8.6.12_0.darwin_22.arm64.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/pnpm
--->  Staging pnpm into destroot
--->  Installing pnpm @8.6.12_0
--->  Activating pnpm @8.6.12_0
--->  Cleaning pnpm
--->  Updating database of binaries
--->  Scanning …
```

pnpm: update to 8.6.12

---

sysutils/rtx/Portfile

New port [rtx](https://github.com/jdxcode/rtx)
Have you

rtx: new port

---

databases/librasterlite2/Portfile
databases/librasterlite2/files/patch-r2gif_c.diff
databases/librasterlite2/files/patch-rasterlite2_private_h.diff
databases/spatialite-tools/Portfile
databases/spatialite/Portfile
gis/gdal/Portfile
gis/qgis3/Portfile
textproc/freexl/Portfile

Update `spatialite` and `spatialite-tools` to version 5.1.0.
Add spatialite related new ports: `freexl` and `librasterlite2`.
Have you

spatialite[-tools]: update to 5.1.0 and new freexl and librasterlite2 ports

---

devel/jenkins/Portfile

new port
macOS 13.5 (22G74)
Xcode 14.3.1 (14E300c)
Have you

jenkins: new port

---

sysutils/mc/Portfile

mc: update to 4.8.30

---

emulators/uxn/Portfile
emulators/uxn/files/patch-uxn-build.diff

uxn: update to 20230814

---

net/tinc/Portfile

Long due update to `tinc-devel`; switch to using PG.
macOS 10.6
Xcode 3.2
Have you

tinc-devel: update to 1.1pre18, use openssl PG

---

math/HiGHS/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

HiGHS: update to 1.5.4

---

net/libretroshare/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libretroshare: update to 2023.08.11

---

net/softether5/Portfile
net/softether5/files/0001-Network.h-include-forgotten-pthread.h-for-MacOS-too.patch
net/softether5/files/0002-TunTap.h-fix-for-undefined-u_char-u_short-on-MacOS.patch
net/softether5/files/0003-enable-enterprise.patch

New port
macOS 10.6
Xcode 3.2
Have you

softether5: new port in net/security

---

devel/thrust/Portfile

New port: https://github.com/NVIDIA/thrust
macOS 10.6
Xcode 3.2
Have you

thrust: new port in devel

---

_resources/port1.0/group/notabug-1.0.tcl
lisp/cl-clunit2/Portfile
lisp/cl-colors2/Portfile

notabug PG: new port group

---

net/snac/Portfile

snac: update to 2.40

---

_resources/port1.0/group/notabug-1.0.tcl

notabug: fix livecheck URL

---

games/fheroes2/Portfile

fheroes2: update to 1.0.7

---

python/py-access/Portfile
python/py-esda/Portfile
python/py-giddy/Portfile
python/py-inequality/Portfile
python/py-libpysal/Portfile
python/py-mapclassify/Portfile
python/py-mgwr/Portfile
python/py-momepy/Portfile
python/py-pointpats/Portfile
python/py-pysal/Portfile
python/py-segregation/Portfile
python/py-spaghetti/Portfile
python/py-spglm/Portfile
python/py-spint/Portfile
python/py-splot/Portfile
python/py-spopt/Portfile
python/py-spreg/Portfile
python/py-spvcm/Portfile
python/py-tobler/Portfile

The PySAL (`py-pysal`) package has been refactored, it is now a wrapper package for a number of separate modules.
This PR updates py-pysal and adds the separate modules as new ports.
Have you

py-pysal: update with new "family"-ports

---

mail/gnupg2/Portfile
mail/gnupg2/files/patch-fix-build-without-openldap.diff

Closes: https://trac.macports.org/ticket/67981
Have you

gnupg2: fix build without OpenLDAP

---

python/py-soundfile/Portfile

py-soundfile: Add Python 311

---

python/py-seqeval/Portfile

py-seqeval: Add Python 311

---

python/py-sacremoses/Portfile

py-sacremoses: Add Python 311

---

python/py-sacrebleu/Portfile

py-sacrebleu: Update to version 2.3.1; Add Python 311

---

python/py-promise/Portfile

py-promise: Add Python 311

---

python/py-fugashi/Portfile

py-fugashi: Update to version 1.3.0dev0; Add Python 311

---

python/py-fire/Portfile

py-fire: Update to version 0.5.0; Add Python 311

---

python/py-tensorflow-metadata/Portfile

py-tensorflow-metadata: Update to version 1.14.0; Add Python 311

---

python/py-omegaconf/Portfile

py-omegaconf: Update to version 2.3.0; Add Python 311

---

python/py-conllu/Portfile

py-conllu: Update to version 4.5.3; Add Python 311

---

python/py-huggingface_hub/Portfile

py-huggingface_hub: Update to version 0.16.4; Add Python 311

---

python/py-tokenizers/Portfile

py-tokenizers: Update to version 0.13.3; Add Python 311

---

python/py-unidic/Portfile

py-unidic: Add Python 311

---

python/py-timeout-decorator/Portfile

py-timeout-decorator: Add Python 311

---

databases/metabase/Portfile

new port
macOS 13.5 (22G74)
Xcode 14.3.1 (14E300c)
Have you

metabase: new port

---

devel/jenkins/Portfile

jenkins: fix java version select

---

devel/glib2-devel/Portfile
devel/glib2/Portfile

Add debug variant to glib2.
Have you

glib2, glib2-devel: add debug variant

---

lisp/cl-iterate/Portfile
lisp/cl-nclasses/Portfile
lisp/cl-nkeymaps/Portfile
lisp/cl-split-sequence/Portfile
lisp/cl-trivial-garbage/Portfile

cl-split-sequence, cl-nclasses, cl-nkeymaps, cl-iterate: add missed dependency

---

archivers/gzip/Portfile

gzip: update to 1.13

---

emulators/uxn/Portfile

uxn: update to 20230819

---

python/py-tensorflow-datasets/Portfile

py-tensorflow-datasets: Update to version 4.9.2; Add Python 311

---

net/iodine/Portfile

iodine: update to 0.8.0

---

math/liblinear/Portfile
math/liblinear/files/patch-Makefile.diff

Update, switch to `python311`.
Xcode 3.2.6
Have you

liblinear: update to 2.46

---

games/nethack/Portfile

nethack: update master_sites and livecheck

---

textproc/eb/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

eb: update to 4.5-20220808

---

net/vnstat/Portfile

vnstat: update to 2.11

---

python/py-commonmark/Portfile

py-commonmark: Add Python 311

---

devel/aspcud/Portfile

Update + support testing.
macOS 10.6
Xcode 3.2
Have you

aspcud: update to 1.9.6, support testing

---

devel/cpp-argparse-dev/Portfile

cpp-argparse-dev: update to v1.8.2

---

lisp/cl-closer-mop/Portfile
lisp/cl-containers/Portfile
lisp/cl-local-time/Portfile
lisp/cl-nasdf/Portfile
lisp/cl-nodgui/Portfile
lisp/cl-rove/Portfile
lisp/cl-spinneret/Portfile
lisp/cl-trivial-clipboard/Portfile
lisp/cl-trivial-custom-debugger/Portfile
lisp/cl-try/Portfile

Blocked by https://github.com/macports/macports-ports/pull/20051 since https://github.com/macports/macports-ports/pull/20016
Have you

Update some lisp ports

---

lang/logtalk/Portfile

logtalk: update to 3.69.0

---

audio/ncmpc/Portfile
audio/ncmpc/files/0001-Fix-for-missing-u_int32_t-for-macOS.patch
audio/ncmpc/files/0002-Fix-environ-for-Apple.patch
audio/ncmpc/files/0003-Revert-util-Concepts-remove-obsolete-fallbacks.patch

Update and a fix.
macOS 10.6
Xcode 3.2
Have you

ncmpc: update to 0.49, fix build

---

R/R-ARDL/Portfile
R/R-FuzzyLP/Portfile
R/R-IsingSampler/Portfile
R/R-MatrixExtra/Portfile
R/R-Rdpack/Portfile
R/R-colourpicker/Portfile
R/R-ghyp/Portfile
R/R-glassoFast/Portfile
R/R-groundhog/Portfile
R/R-gtable/Portfile
R/R-intergraph/Portfile
R/R-madness/Portfile
R/R-mlt/Portfile
R/R-pan/Portfile
R/R-rbibutils/Portfile
R/R-rqdatatable/Portfile
R/R-runjags/Portfile
R/R-shinydisconnect/Portfile
R/R-splancs/Portfile
R/R-tglkmeans/Portfile
R/R-vip/Portfile

Updates.
macOS 10.6
Xcode 3.2
Have you

R: update some packages

---

devel/osc/Portfile

osc: update to 1.3.0

---

math/ceres-solver/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

ceres-solver: update to 2.1.0

---

archivers/gnutar/Portfile
archivers/gnutar/files/patch-Makefile.patch
archivers/gnutar/files/patch-revert-63567.patch

gnutar: update to 1.35

---

python/py-recommonmark/Portfile

py-recommonmark: Add Python 311

---

textproc/datamash/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

datamash: update to 1.8

---

math/hiop/Portfile
math/strumpack/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

strumpack: update to 7.1.4

---

devel/demangle/Portfile

demangle: fix maintainers definition

---

audio/xmp/Portfile

Updates.
macOS 10.6
Xcode 3.2
Have you

libxmp: update to 4.6.0; xmp: update to 4.2.0

---

R/R-BaseSet/Portfile
R/R-ConvergenceConcepts/Portfile
R/R-ParallelLogger/Portfile
R/R-RcmdrPlugin.survival/Portfile
R/R-WeightedROC/Portfile
R/R-anMC/Portfile
R/R-blaster/Portfile
R/R-kantorovich/Portfile
R/R-logcondens/Portfile
R/R-markdown/Portfile
R/R-meboot/Portfile
R/R-misty/Portfile
R/R-mlflow/Portfile
R/R-msBP/Portfile
R/R-nestedcv/Portfile
R/R-ompr.roi/Portfile
R/R-tmle/Portfile
_resources/port1.0/group/R-1.0.tcl

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (2)

---

python/py-safetensors/Portfile

py-safetensors: Submission

---

security/blake3/Portfile

Update blake3 to version 1.4.1
macOS 12.6.8 21G725 arm64
Have you

blake3: update to 1.4.1

---

devel/natscli/Portfile

natscli: New port

---

devel/jenkins/Portfile

jenkins: update to 2.414.1

---

devel/qoauth/Portfile

Update to the latest version.
macOS 10.6
Xcode 3.2
Have you

qoauth: update to 2.0.1

---

textproc/discount/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

discount: update to 2.2.7c

---

tex/texlive-bin/Portfile

Closes: https://trac.macports.org/ticket/67998
Have you

texlive-bin: revbump after zlib update

---

archivers/makeself/Portfile

makeself: update to 2.5.0

---

devel/luv/Portfile

luv{,-luajit}: update to 1.45.0-0

---

textproc/less/Portfile

less: update to 643

---

sysutils/rtx/Portfile

rtx: update to 2023.8.8

---

math/asl/Portfile

asl: new port (version 20230818)

---

R/R-CARBayesdata/Portfile
R/R-CVglasso/Portfile
R/R-DiSSMod/Portfile
R/R-GLDEX/Portfile
R/R-GenBinomApps/Portfile
R/R-HMMcopula/Portfile
R/R-LMMstar/Portfile
R/R-NNS/Portfile
R/R-PReMiuM/Portfile
R/R-bartBMA/Portfile
R/R-betaMC/Portfile
R/R-bootstrapFP/Portfile
R/R-comparison/Portfile
R/R-easyanova/Portfile
R/R-expectreg/Portfile
R/R-forestplot/Portfile
R/R-gamCopula/Portfile
R/R-gap/Portfile
R/R-gasmodel/Portfile
R/R-gb/Portfile
R/R-jipApprox/Portfile
R/R-rrMixture/Portfile
R/R-sampling/Portfile
R/R-tmbstan/Portfile
R/R-trapezoid/Portfile
R/R-triangle/Portfile
R/R-vMF/Portfile

Remaining weekend updates plus some new ports.
macOS 10.6
Xcode 3.2
Have you

R: few updates and new packages

---

math/ipopt/Portfile

Closes: https://trac.macports.org/ticket/68031
Have you

ipopt: use system Mumps and ASL

---

science/elmerfem/Portfile

Update, enhancement.
macOS 10.6
Xcode 3.2
Have you

elmerfem: update to 2023.08.25, add a variant

---

devel/asio/Portfile

The port has not been updated for a year.
macOS 10.6
Xcode 3.2
Have you

asio: update to 1-28-1

---

devel/sbt/Portfile

sbt: update to 1.9.4

---

devel/lazydocker/Portfile

macOS 14.0 23A5328b arm64
Have you

lazydocker: update to 0.21.1

---

python/py-esda/Portfile
python/py-segregation/Portfile
python/py-tobler/Portfile

Update `py-esda` to version 2.5.0, `py-segregation` to 2.5 and `py-tobler` to 0.11.1.
Have you

py-pysal family ports: updates

---

python/py-awscli2/Portfile

py-awscli2: update to 2.13.13

---

databases/pgbadger/Portfile

pgbadger: update to 12.2

---

devel/libqtxdg-legacy/Portfile
devel/libqtxdg-legacy/files/patch-qiconloader_qt4.diff
devel/qt4-mimetypes/Portfile

New ports to provide support for Qt4.
macOS 10.6
Xcode 3.2
Have you

libqtxdg-legacy, qt4-mimetypes: new ports for Qt4

---

sysutils/tree/Portfile

tree: update to 2.1.1

---

gis/geographiclib/Portfile
python/py-geographiclib/Portfile

* geographiclib: [Changelog](https://github.com/geographiclib/geographiclib/blob/main/NEWS)
* py-geographiclib: [Changelog](https://github.com/geographiclib/geographiclib-python/blob/main/doc/package.rst#change-log)
Xcode 14.2
Have you

geographiclib: update to 2.3, py-geographiclib: update to 2.0

---

office/zenwriter/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

zenwriter: new port

---

R/R-BayesSUR/Portfile
R/R-BlakerCI/Portfile
R/R-DEoptimR/Portfile
R/R-Davies/Portfile
R/R-DistributionUtils/Portfile
R/R-Mcomp/Portfile
R/R-adace/Portfile
R/R-asht/Portfile
R/R-beast/Portfile
R/R-bpcp/Portfile
R/R-bravo/Portfile
R/R-bridgedist/Portfile
R/R-dyn/Portfile
R/R-einsum/Portfile
R/R-exact2x2/Portfile
R/R-exactci/Portfile
R/R-fitConic/Portfile
R/R-ginormal/Portfile
R/R-gnm/Portfile
R/R-gratis/Portfile
R/R-hdd/Portfile
R/R-mbbefd/Portfile
R/R-prodlim/Portfile
R/R-rootWishart/Portfile
R/R-sharp/Portfile
R/R-snakecase/Portfile
R/R-ssanv/Portfile
R/R-tsfeatures/Portfile

Updates, new ports.
macOS 10.6
Xcode 3.2
Have you

R: updates and some new packages (I)

---

math/blaspp/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

blaspp: update to 2023.08.25

---

archivers/libarchive-qt/Portfile
archivers/libarchive-qt/files/0001-Revert-Remove-Qt4-support-and-other-changes.patch

Cannot check Qt5 variant, hope it works, otherwise I will enable only Qt4 initially.
UPD. Everything looks good.
macOS 10.6
Xcode 3.2
Have you

libarchive-qt: new port

---

R/R-FENmlm/Portfile
R/R-NonProbEst/Portfile
R/R-RaschSampler/Portfile
R/R-cgam/Portfile
R/R-csci/Portfile
R/R-csurvey/Portfile
R/R-cxxfunplus/Portfile
R/R-diffcor/Portfile
R/R-dimensio/Portfile
R/R-emg/Portfile
R/R-extremefit/Portfile
R/R-fda.usc/Portfile
R/R-fxregime/Portfile
R/R-gamclass/Portfile
R/R-glogis/Portfile
R/R-isni/Portfile
R/R-lestat/Portfile
R/R-lmom/Portfile
R/R-locpolExpectile/Portfile
R/R-nlpsem/Portfile
R/R-pamm/Portfile
R/R-panelr/Portfile
R/R-rsdmx/Portfile
R/R-slasso/Portfile
R/R-svDialogs/Portfile
R/R-svDialogstcltk/Portfile
R/R-table1/Portfile
R/R-utility/Portfile

Second part.
macOS 10.6
Xcode 3.2
Have you

R: updates and new packages (II)

---

devel/Bear/Portfile

Bear: update to 3.1.2

---

devel/util-linux/Portfile

util-linux: update to 2.39.2

---

math/nickle/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nickle: update to 2.93

---

devel/oxenmq/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

oxenmq: update to 1.2.15

---

R/R-BiocCheck/Portfile
R/R-NMA/Portfile
R/R-dplR/Portfile
R/R-fmcmc/Portfile
R/R-labeling/Portfile
R/R-pak/Portfile

Updates. Done for today.
macOS 10.6
Xcode 3.2
Have you

R: a few remaining updates for R packages

---

net/snac/Portfile

macOS 14.0 23A5328b arm64
Have you

snac: update to 2.41

---

lisp/cl-closer-mop/Portfile
lisp/cl-com.inuoe.jzon/Portfile
lisp/cl-marshal/Portfile
lisp/cl-serapeum/Portfile

Update a few more lisp ports

---

R/R-arrow/Portfile
R/R-bmlm/Portfile
R/R-bvartools/Portfile
R/R-config/Portfile
R/R-cyclocomp/Portfile
R/R-dqrng/Portfile
R/R-emayili/Portfile
R/R-ggh4x/Portfile
R/R-hmer/Portfile
R/R-lmomco/Portfile
R/R-rematch/Portfile
R/R-shinyWidgets/Portfile
R/R-tvm/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates for packages

---

security/libressl-devel/Portfile

macOS 14.0 23A5337a arm64
Have you

libressl-devel: update to 3.8.1

---

devel/got/Portfile

macOS 14.0 23A5337a arm64
Have you

got: update to 0.92

---

net/nmap/Portfile

* closes https://trac.macports.org/ticket/68035
macOS 14.0 23A5337a arm64
Have you

nmap: update to 7.94

---

devel/simdjson/Portfile
devel/simdjson/files/patch-build-flags-on-x86.diff

simdjson: new port in devel

---

sysutils/nnn/Portfile

[Changelog](https://github.com/jarun/nnn/releases/tag/v4.9)
macOS 12.4
Xcode 13.4.1
Have you

nnn: update to 4.9

---

emulators/uxn/Portfile

uxn: update to 20230901

---

lisp/cl-async/Portfile
lisp/cl-async/files/macports-integration.diff
lisp/cl-cffi/Portfile
lisp/cl-cffi/files/0003-enforce-MacPorts-libffi.patch
lisp/cl-fastcgi/Portfile
lisp/cl-gobject-introspection/Portfile
lisp/cl-libuv/Portfile
lisp/cl-libuv/files/macports-integration.diff
lisp/cl-marshal/Portfile
lisp/cl-plus-ssl/Portfile
lisp/cl-plus-ssl/files/macports-integration.diff
lisp/cl-quri/Portfile
lisp/cl-webkit2/Portfile

Update some lisp ports, enforce use of MacPorts libraries

---

databases/litecli/Portfile
databases/mycli/Portfile
databases/pgcli/Portfile
irc/ngircd/Portfile
net/ipcalc/Portfile
python/py-cli-helpers/Portfile
python/py-humanize/Portfile
python/py-pendulum/Portfile
python/py-pgspecial/Portfile
python/py-prompt_toolkit/Portfile
python/py-pycryptodome/Portfile
python/py-pymysql/Portfile
python/py-pytzdata/Portfile
python/py-setproctitle/Portfile
python/py-sqlparse/Portfile
python/py-terminaltables/Portfile
python/py-wcwidth/Portfile
sysutils/dpkg/Portfile

Removing myself from maintainers as I'm not using macports anymore.
N/A
N/A

Remove myself (@xeron) from maintainers.

---

sysutils/lsd/Portfile

Update `lsd` to its latest verison, 1.0.0. Completions for bash, zsh, and fish have been added.
Have you

lsd: Update to 1.0.0

---

devel/apache-ant/Portfile

apache-ant: update to 1.10.14

---

net/ipcalc/Portfile

ipcalc: update to 0.51; claim maintainership

---

textproc/vale/Portfile

vale: Update to 2.28.2

---

science/pnetcdf/Portfile

See: https://github.com/macports/macports-ports/commit/5dea5f257989fdb40ebe16940c3cc7ead2f49918#commitcomment-126024766
macOS 10.6
Xcode 3.2
Have you

pnetcdf: fix mpi.setup; use https

---

net/grafana/Portfile

macOS 13.5.1 22G90 arm64
Have you

grafana: update to 10.1.1

---

math/libtommath/Portfile

macOS 12.6.8 Intel
Xcode 14.2
Have you

libtommath: update to 1.2.1

---

python/py-acoustid/Portfile
python/py-asn1crypto/Portfile
python/py-aubio/Portfile
python/py-audioread/Portfile
python/py-bottlenose/Portfile
python/py-bsddb3/Portfile
python/py-cbor2/Portfile
python/py-country/Portfile
python/py-gpsoauth/Portfile
python/py-ibroadcast/Portfile
python/py-jsonpath-rw/Portfile
python/py-munkres/Portfile
python/py-musicbrainzngs/Portfile
python/py-ordered-set/Portfile
python/py-pytest-fixture-config/Portfile
python/py-pytest-profiling/Portfile
python/py-pytest-shutil/Portfile
python/py-pytest-virtualenv/Portfile
python/py-python-coveralls/Portfile
python/py-rarfile/Portfile
python/py-setuptools-git/Portfile
python/py-smi/Portfile
python/py-termplotlib/Portfile
python/py-termtables/Portfile
python/py-validictory/Portfile
python/py-validictory/files/patch-python310.diff
python/py-zbar/Portfile

py-*: add py311

---

science/pooler/Portfile

pooler: update to 1.88

---

math/papilo/Portfile
math/scip/Portfile

papilo: update to 2.1.3

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.1.15

---

gnome/gnome-voice/Portfile

gnome-voice 2.0.0 upstream release from http://www.gnomevoice.org/src/gnome-voice-2.0.0.tar.xz
macOS 13.5.1 22G90 arm64
Have you

gnome-voice: new 2.0.0 version

---

devel/sccache/Portfile

sccache: update to 0.5.4

---

math/stan/Portfile
math/stanmath/Portfile

stan, stanmath: update to latest releases

---

multimedia/libmpeg2/Portfile

Fixes: https://trac.macports.org/ticket/68143
Fix Rosetta build.
Xcode 3.2.6
Have you

libmpeg2: fix build on rosetta

---

math/opal-ml/Portfile

opal-ml: update to 2022-03-18

---

aqua/phantomjs-qt/Portfile
aqua/qt5/Portfile
aqua/qt511/Portfile
aqua/qt513/Portfile
aqua/qt53/Portfile
aqua/qt55/Portfile
aqua/qt56/Portfile
aqua/qt57/Portfile
aqua/qt58/Portfile
aqua/qt59/Portfile
aqua/squirrel-ime/Portfile
databases/leveldb/Portfile
devel/librime-devel/Portfile
games/minetest/Portfile
math/caffe/Portfile
python/py-plyvel/Portfile
python/py-pytorch/Portfile

See: https://trac.macports.org/ticket/68132
Have you

leveldb: expose memenv

---

python/py-bitmath/Portfile
python/py-bpylist2/Portfile
python/py-bpylist2/files/cleanup-depdendencies.diff
python/py-objexplore/Portfile
python/py-progressbar/Portfile
python/py-pytest-pycodestyle/Portfile
python/py-pytest-pylint/Portfile

All these ports are dependencies for `osxphotos`
Have you

Add a dew new python ports

---

textproc/texml/Portfile

texml: update to 2.0.4

---

python/py-awscli2/Portfile

py-awscli2: update to 2.13.17

---

aqua/qt6/Portfile

This file is required for Sigil to run
macOS x.y
Have you

qt6-qtwebengine: manually install icudtl.dat

---

editors/sigil/Portfile

macOS 13.5.1 22G90 arm64
Have you

sigil: update to 2.0.1

---

editors/MacVim/Portfile

MacVim: disable sparkle auto update

---

R/R-BsMD/Portfile
R/R-GenomicFeatures/Portfile
R/R-HDMT/Portfile
R/R-HIMA/Portfile
R/R-PublicationBias/Portfile
R/R-QRegVCM/Portfile
R/R-QuadRoot/Portfile
R/R-RationalExp/Portfile
R/R-RcppArmadillo/Portfile
R/R-RegCombin/Portfile
R/R-Rhdf5lib/Portfile
R/R-biocViews/Portfile
R/R-brms/Portfile
R/R-factorstochvol/Portfile
R/R-fmtr/Portfile
R/R-glmnetUtils/Portfile
R/R-isotonic.pen/Portfile
R/R-maq/Portfile
R/R-memery/Portfile
R/R-memery/files/patch-no-gifski.diff
R/R-multibiasmeta/Portfile
R/R-pbdMPI/Portfile
R/R-revdbayes/Portfile
R/R-rtracklayer/Portfile
R/R-sqliter/Portfile
R/R-tdaunif/Portfile
R/R-tdsa/Portfile
R/R-truncSP/Portfile

Weekend updates.
Xcode 3.2.6
Have you

R: updates for existing packages and some new packages

---

games/fheroes2/Portfile

fheroes2: update to 1.0.8

---

sysutils/coreutils-uutils/Portfile

coreutils-uutils: update to 0.0.21

---

science/cdo/Portfile

macOS Ventura 13.5
Xcode 14.3.1 / Command Line Tools 14.3.1
Have you

cdo: update dependencies to use proj9

---

databases/metabase/Portfile

metabase: update to 0.47.1

---

R/R-Hmisc/Portfile
R/R-MultiAssayExperiment/Portfile
R/R-QuickJSR/Portfile
R/R-QuickJSR/files/patch-legacy.diff
R/R-QuickJSR/files/patch-libatomic.diff
R/R-RaggedExperiment/Portfile
R/R-RcppInt64/Portfile
R/R-bayesZIB/Portfile
R/R-bmgarch/Portfile
R/R-ggblanket/Portfile
R/R-marginaleffects/Portfile
R/R-mvnfast/Portfile
R/R-nimbleHMC/Portfile
R/R-performance/Portfile
R/R-rms/Portfile
R/R-rstanemax/Portfile
R/R-safer/Portfile
R/R-vetiver/Portfile
R/R-zoid/Portfile

Updates, added support for testing and a fix for https://trac.macports.org/ticket/68152
Xcode 3.2.6
Have you

R: updates for packages, added test support and a fix for R-QuickJSR

---

python/py-igraph/Portfile

py-igraph: update to 0.10.8

---

audio/lilv/Portfile
audio/lv2/Portfile
audio/serd/Portfile
audio/sord/Portfile
audio/sratom/Portfile

lilv, lv2, serd, sord, sratom: update to current versions

---

R/R-tiledb/Portfile
databases/tiledb/Portfile

tiledb: update to 2.17.0; R-tiledb: update to 0.21.0

---

devel/rapidjson-devel/Portfile

rapidjson-devel: update to 20230821

---

devel/sbt/Portfile

sbt: update to 1.9.6

---

sysutils/rtx/Portfile

rtx: update to 2023.9.1

---

www/varnish/Portfile
www/varnish/files/varnish-python.diff

varnish: update to 7.4.0

---

sysutils/vtm/Portfile

vtm: update to 0.9.9u

---

devel/tatami/Portfile

tatami: update to 2.1.2; tatami-devel: update to 2023.09.08

---

lang/logtalk/Portfile

logtalk: update to 3.70.0

---

net/wireshark4/Portfile

wireshark4: update 4.0.8, replace sha1 with rmd160

---

gis/saga/Portfile

Update `saga` to version 9.1.2.
Have you

saga: update to version 9.1.2

---

science/imager/Portfile
science/imager/files/greg.in
science/imager/files/imager.in
science/imager/files/patch-admin-Makefile.build.diff
science/imager/files/patch-admin-Makefile.def.diff
science/imager/files/patch-admin-Makefile.python.diff
science/imager/files/patch-admin-define-system.sh.diff
science/imager/files/patch-admin-imager-env.sh.diff
science/imager/files/sic.in
science/imager/files/viewer.in

imager: new port, version 202309

---

devel/got/Portfile

got: update to 0.93

---

emulators/uxn/Portfile

uxn: update to 20230906

---

devel/openssl/Portfile
devel/openssl3/Portfile
net/openssh/Portfile
sysutils/freeradius/Portfile

openssl3: Update to 3.1.3

---

math/hiop/Portfile

hiop: update to 1.0.0

---

graphics/osxphotos/Portfile

osxphotos: new port (version 0.63.0)

---

net/curl/Portfile
net/curl/files/patch-sonoma.patch

macOS 14.0 23A339 arm64
Have you

curl: patch LDFLAGS for Sonoma

---

devel/Bear/Portfile
devel/abseil/Portfile
devel/apache-arrow/Portfile
devel/grpc/Portfile
devel/protobuf3-cpp-upstream/Portfile
devel/re2/Portfile
math/s2geometry/Portfile
net/mtxclient/Portfile

- abseil: update to 20230802.1
- abseil dependents: rev-bump
Have you

abseil: update to 20230802.1

---

sysutils/glances/Portfile

glances: update to 3.4.0.3

---

sysutils/gearmand/Portfile

gearmand: update to 1.1.20

---

sysutils/calcurse/Portfile

Closes: https://trac.macports.org/ticket/65451
Have you

calcurse: update to 4.8.1

---

net/makuosan/Portfile

makuosan: update to 1.3.6

---

x11/homebank/Portfile

homebank: update to 5.7

---

R/R-ICS/Portfile
R/R-bvpSolve/Portfile
R/R-fastcpd/Portfile
R/R-jqr/Portfile
R/R-jqr/files/patch-fix-configure.diff
R/R-rootSolve/Portfile
R/R-snowFT/Portfile
R/R-sodium/Portfile

Updates.
Fix for `R-sodium`, see: https://github.com/macports/macports-ports/commit/86381201edd2b233a20f15a542eae461de5eabb6
Xcode 3.2.6
Have you

R: updates for packages; fix `R-sodium` after `libsodium` update

---

science/imager/Portfile

imager: update port version 202310

---

editors/emacs/Portfile

emacs-app-devel: update to 20230920

---

security/bitwarden-cli/Portfile

bitwarden-cli: update to 2023.9.0

---

science/proxmark3-iceman/Portfile

proxmark3-iceman: update to v4.17140

---

python/py-slack-sdk/Portfile

Updated version and added python 3.11
Have you

py-slack-sdk: update to version 3.22.0 and added python 3.11

---

fuse/s3fs/Portfile

s3fs: update to 1.93

---

python/py-pysap/Portfile
sysutils/john/Portfile
sysutils/john/files/patch-apple-m1.diff

Closes: https://trac.macports.org/ticket/42379
Closes: https://trac.macports.org/ticket/62859
Closes: https://trac.macports.org/ticket/67973
Closes: https://trac.macports.org/ticket/67974
Closes: https://trac.macports.org/ticket/67975
It depends on:
- https://github.com/macports/macports-ports/pull/20300
- https://github.com/macports/macports-ports/pull/20312
- https://github.com/macports/macports-ports/pull/20327
- https://github.com/macports/macports-ports/pull/20330
- https://github.com/macports/macports-ports/pull/20383
Anyway, it had missed dependencies for `py27-scapy` / `py311-scapy` and `py311-pysap` which depends on `py311-scapy`. MacPorts has `scapy` as dedicated program which need to be converted into python script with some work. So, I've created a ticket: …

john-jumbo: fix build on arm64; add devel subport; claim maintainership

---

textproc/libxmlxx5/Portfile
textproc/libxmlxx5/files/patch-meson-build.diff

libxmlxx5: update to 5.0.3

---

graphics/InsightToolkit4/Portfile
graphics/InsightToolkit4/files/patch-findpython.diff
graphics/InsightToolkit4/files/patch-python3.10.diff
graphics/InsightToolkit4/files/patch-python3.8.diff
graphics/InsightToolkit4/files/patch-swigpy-sliceobject.diff

New `InsightToolkit4` port pinned on version 4.x with Python subports.
The latest version of [Orfeo ToolBox](https://ports.macports.org/port/orfeotoolbox/details/) is not compatible with v5, in order to update that Portfile this pinned port is needed.
Have you

InsightToolkit4: new port based on InsightToolkit-devel, pinned on v4

---

devel/rapidjson-devel/Portfile

rapidjson-devel: update to 20230922

---

science/madness/Portfile

madness: update to 2023.09.20, switch to boost181

---

lang/mrustc/Portfile

mrustc: update to 1.54-20230925

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.1.16

---

math/hpddm/Portfile

hpddm: update to 2.2.4

---

python/py-awscli2/Portfile

py-awscli2: update to 2.13.22

---

devel/carthage/Portfile

Update to one of my ports.
macOS 14.0 23A344
Xcode 15.0 15A5229m 
Have you

carthage: Update to 0.39.1

---

lang/gcc13/Portfile
lang/gcc13/files/mp-gcc13
lang/gcc13/files/patch-darwin-gcc-13.2.0.diff
lang/gcc13/files/patch-disable-sys-header-missing-abort.diff

Not yet default runtime provider whilst testing and currently intentionally conflicts with the {lib}gcc12 port.

gcc13: New experimental version.

---

python/py-rchitect/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

py-rchitect: update to 0.4.2

---

sysutils/john/Portfile
sysutils/john/files/patch-fix-ld-multiple-definition-errors.diff

Closes: https://trac.macports.org/ticket/68232
`john-jumbo-devel` on
`john-jumbo` on
Have you

john-jumbo{,-devel}: use the right build target; john-jumbo-devel: update to 20230922

---

science/socnetv/Portfile

- fix livecheck
- add myself as maintainer
Have you

socnetv: fix livecheck and add maintainer

---

editors/zim/Portfile

zim: correct license to GPL-2+

---

audio/xmp/Portfile

Allow @douglas-carmichael to be notified of proposed changes on GitHub (if still interested in maintaining this port)
Have you

xmp: add maintainer’s GitHub handle

---

devel/CImg/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

CImg: update to 3.3.0

---

R/R-alakazam/Portfile
R/R-biocViews/Portfile
R/R-logitr/Portfile
R/R-markdown/Portfile
R/R-nanoarrow/Portfile
R/R-reporter/Portfile
R/R-tinytex/Portfile

I did not add anything to the previous updates PR, since it took multiple hours to build. These are the remaining ones for today (likely for the weekend).
macOS 10.6.8
Xcode 3.2.6
Have you

R: remaining few updates for existing packages

---

aqua/qt5/Portfile
aqua/qt5/files/patch-qtmultimedia_no_std_unary_function.diff

In Xcode 15 clang in C++17 mode, std::unary_function, deprecated since C++11, has been removed.
Have you
@MarcusCalhoun-Lopez

qt5-qtmultimedia: fix build in Xcode 15

---

mail/opensmtpd/Portfile

opensmtpd: update to 7.3.0p2

---

aqua/qt6/Portfile

https://build.macports.org/builders/ports-11_arm64-builder/builds/103369/steps/install-port/logs/stdio
```
DEBUG: Executing proc-post-org.macports.destroot-destroot-0
Error: Failed to destroot qt6-qtwebengine-docs: xinstall: Unable to create new file for: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_aqua_qt6/qt6-qtwebengine-docs/work/destroot/opt/local/libexec/qt6/lib/QtWebEngineCore.framework/Resources/, No such file or directory
DEBUG: Error code: NONE
DEBUG: Backtrace: xinstall: Unable to create new file for: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_aqua_qt6/qt6-qtwebengine-docs/work/destroot/opt/local/libexec/qt6/lib/QtWebEngineCore.framework/Resources/, No such file or directory
while executing
"$post $targetname" …
```

qt6-qtwebengine-docs: fix destroot

---

graphics/tthresh/Portfile

tthresh: update to 2023.07.12

---

security/blake3/Portfile

Update blake3 to v.1.5.0
Have you

blake3: update to 1.5.0

---

multimedia/fluidsynth/Portfile

fluidsynth: update to 2.3.4

---

python/py-libpysal/Portfile
python/py-pointpats/Portfile
python/py-spreg/Portfile
python/py-tobler/Portfile

Update:
- `py-libpysal` to version 4.8.0
- `py-pointpats` to version 2.4.0
- `py-spreg` to version 1.4
- `py-tobler` to version 0.11.2
Have you

pysal port family: updates

---

science/elmerfem/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

elmerfem: update to 2023.10.02

---

devel/re-flex/Portfile

re-flex: update to 3.4.1

---

mail/himalaya/Portfile

himalaya: update to 0.9.0

---

net/wireshark4/Portfile

net/wireshark4: revbump to 4.0.9

---

net/rpki-client/Portfile

* closes https://trac.macports.org/ticket/67883
macOS 14.1 23B5056e arm64
Have you

rpki-client: update to 8.6

---

net/wireshark4/Portfile

wireshark4: update to 4.0.10

---

audio/hydrogen/Portfile

Closes https://trac.macports.org/ticket/67793
Have you

hydrogen: update to 1.2.2

---

gis/saga/Portfile
gis/saga/files/python_cmake.diff

Update `saga` to version 9.2.0.
Have you

saga: update to version 9.2.0

---

lang/py-htmldocs/Portfile
python/py-XlsxWriter/Portfile
python/py-json-tricks/Portfile
python/py-pdfminer/Portfile
python/py-pptx/Portfile
python/py-pydicom/Portfile
python/py-pynetdicom/Portfile
python/py-qimage2ndarray/Portfile

Maintainer update; version bumps to a number of ports I maintain.

Python ports updates

---

devel/geoclue2/Portfile

This is not the newest version, 2.5 or newer requires changing to meson which I don't know how to do. But this should at least get the livechecks and urls correct again.
Have you

geoclue2: update to 2.4.13

---

devel/cmake-devel/Portfile
devel/cmake-devel/files/patch-remove-homebrew-references.diff

there are some hardcoded references to homebrew paths that have crept into cmake over time. Remove these.
prevents homebrew-installed software like python from being detected over the settings in PATH and PREFIX, if the user happens to have homebrew installed in /opt/homebrew
with both macports and homebrew installed, homebrew in /opt/homebrew
Have you

cmake-devel: remove homebrewisms

---

python/py-xxhash/Portfile

py-xxhash: Update to version 3.4.1; Add Python 311

---

ocaml/ocaml-seq/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

ocaml-seq: new port

---

www/ocaml-cgi/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-cgi: update to 0.12

---

erlang/atomvm/Portfile

atomvm: new port

---

ocaml/ocaml-easy-format/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-easy-format: update to 1.3.4

---

python/py-h5py/Portfile

py-h5py:3.10.0

---

python/py-uvicorn/Portfile

py-uvicorn: Update to version 0.23.2; Add Python 311

---

emulators/qemu/Portfile

Update qemu to v. 8.0.5
Have you

qemu: update to version 8.0.5

---

erlang/atomvm/Portfile

atomvm: update to 0.6.0-alpha.1

---

games/godot/Portfile
games/godot/files/add-external_libs-support.diff
games/godot/files/configure-macports-compiler.diff
games/godot/files/legacy-osx-defines.diff
games/godot/files/macosx-version-log_h-workaround.diff
games/godot/files/patch-available2macro-camera_osx.diff
games/godot/files/patch-available2macro-os_osx.diff

godot: update to 3.5.3

---

ocaml/ocaml-camlp-streams/Portfile

New port.
macOS 10.6
Xcode 3.2
Have you

ocaml-camlp-streams: new port

---

archivers/unrar/Portfile

unrar: update to 6.2.12

---

R/R-DT/Portfile
R/R-ExGaussEstim/Portfile
R/R-GLMsData/Portfile
R/R-SMR/Portfile
R/R-aplot/Portfile
R/R-biomartr/Portfile
R/R-chk/Portfile
R/R-cpfa/Portfile
R/R-distill/Portfile
R/R-fBasics/Portfile
R/R-fansi/Portfile
R/R-fdaSP/Portfile
R/R-fdasrvf/Portfile
R/R-glmtoolbox/Portfile
R/R-gpboost/Portfile
R/R-grImport2/Portfile
R/R-gt/Portfile
R/R-htmltools/Portfile
R/R-ijtiff/Portfile
R/R-jmatrix/Portfile
R/R-kSamples/Portfile
R/R-markdown/Portfile
R/R-paletteer/Portfile
R/R-primes/Portfile
R/R-ra4bayesmeta/Portfile
R/R-rda/Portfile
R/R-rempsyc/Portfile
R/R-systemfonts/Portfile
R/R-testthat/Portfile
R/R-textshaping/Portfile

@herbygillot @reneeotten Once CI pass, can be merged. _Nothing will be added here._
macOS 10.6
Xcode 3.2
Have you

R: updates for packages (II)

---

erlang/atomvm/Portfile

Platforms was wrongly set to any, which has the consequence of creating only one binary for all platforms.
Have you

atomvm: fix platforms

---

R/R-AnnotationForge/Portfile
R/R-CEoptim/Portfile
R/R-DEoptimR/Portfile
R/R-HDRFA/Portfile
R/R-MTest/Portfile
R/R-PNAR/Portfile
R/R-RcppEnsmallen/Portfile
R/R-abseil/Portfile
R/R-dualtrees/Portfile
R/R-gamlss.cens/Portfile
R/R-gamlss/Portfile
R/R-lamW/Portfile
R/R-miscFuncs/Portfile
R/R-multibias/Portfile
R/R-priceR/Portfile
R/R-rsconnect/Portfile
R/R-shinyvalidate/Portfile
R/R-unitizer/Portfile
R/R-vistla/Portfile

(I will make another PR with more updates.)
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (I)

---

ocaml/ocaml-topkg/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-topkg: update to 1.0.7

---

textproc/code-minimap/Portfile

Closes https://trac.macports.org/ticket/67561
Used cargo2port.
Have you

code-minimap: update to 0.6.4

---

archivers/draco/Portfile
archivers/draco/files/patch-gltf-decoder-cc.diff
graphics/tinygltf/Portfile
graphics/tinygltf/files/01_patch-cmake.diff
graphics/tinygltf/files/02_patch-third-party-includes.diff
graphics/tinygltf/files/03_patch-enable-ctest.diff

Add new ports:
- `draco` version 1.5.6
3D data compression library: https://google.github.io/draco/
- `tinygltf` version 2.8.17
Header only C++11 tiny glTF 2.0 library: https://github.com/syoyo/tinygltf
Have you

draco, tinygltf: new ports

---

R/R-CRAN-recommended/Portfile
R/R-KernSmooth/Portfile
R/R-MASS/Portfile
R/R-Matrix/Portfile
R/R-SASmixed/Portfile
R/R-boot/Portfile
R/R-class/Portfile
R/R-cluster/Portfile
R/R-codetools/Portfile
R/R-foreign/Portfile
R/R-lattice/Portfile
R/R-mgcv/Portfile
R/R-nlme/Portfile
R/R-nnet/Portfile
R/R-rpart/Portfile
R/R-spatial/Portfile
R/R-survival/Portfile
_resources/port1.0/group/R-1.0.tcl
math/R/Portfile

Rationale for the change:
1. Recommended packages are not part of `R` and are developed and maintained by third parties.
2. Since they are not a part of `R`, they get updates in between `R` versions updates, and some `R` packages require a newer version of recommended packages than which was available at the time of `R` release; in result, our current set-up prevents those from updating.
I was aware of the issue for quite a while, but initially it was a single port not being able to get an update, and also I did not see a nice way to handle the matter. Now there are several with broken updates, and I think I came up with an elegant solution, which does not require manually adding dependencies to hundreds of ports and in effect maintains existing set-up: while `R` itself does not …

R: move recommended packages to ports, update PG

---

games/fheroes2/Portfile

fheroes2: update to 1.0.9

---

ocaml/ocaml-biniou/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

ocaml-biniou: update to 1.2.2

---

sysutils/terragrunt/Portfile
sysutils/terragrunt/files/patch-options.go.52.diff

Updating terragrunt to the latest version. It will select terraform 1.5 when installing.
A couple of notes here:
* Current version is broken for me, I cannot end up installing the selected terraform port. That's why I'm upding the port
* Since patch changes, I've done my best to accomodate the fixes. But maybe this is not the standard way to do this in macports. If someone has a better way to do this, please, let me know and I'll update the PR accordingly!
* I've tried running the tests but seems like there are none `Error: Failed to test terragrunt-0.52: terragrunt-0.52 has no tests turned on. see 'test.run' in portfile(7)`
* Although I've configured the version as others, when running `terragrunt -v` says `terragrunt version latest` I suspect that this is due to the release they did …

terragrunt: update to 0.52.1

---

R/R-BACprior/Portfile
R/R-BWStest/Portfile
R/R-BayesMallows/Portfile
R/R-DBI/Portfile
R/R-IsingFit/Portfile
R/R-NNS/Portfile
R/R-RMixtCompIO/Portfile
R/R-RSQLite/Portfile
R/R-TeXCheckR/Portfile
R/R-abn/Portfile
R/R-bayesdfa/Portfile
R/R-btergm/Portfile
R/R-covr/Portfile
R/R-dm/Portfile
R/R-fude/Portfile
R/R-geostan/Portfile
R/R-glmmTMB/Portfile
R/R-hunspell/Portfile
R/R-hutilscpp/Portfile
R/R-ic.infer/Portfile
R/R-janeaustenr/Portfile
R/R-jfa/Portfile
R/R-migraph/Portfile
R/R-migraph/files/patch-no-concaveman.diff
R/R-mirai/Portfile
R/R-ragg/Portfile
R/R-robustlmm/Portfile
R/R-tidytable/Portfile
R/R-wordcloud/Portfile
R/R-wordcloud2/Portfile

R: updates for packages (III)

---

net/openfortivpn/Portfile

Closes: https://trac.macports.org/ticket/67827
Have you

openfortivpn: update to 1.20.5

---

archivers/draco/Portfile
graphics/tinygltf/Portfile

Update `tinygltf` to version 2.8.18.
Have you

tinygltf: update to version 2.8.18

---

lang/logtalk/Portfile

logtalk: update to 3.71.0

---

devel/fpm/Portfile
fortran/slsqp/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

slsqp: update to 1.4.1

---

lang/lfortran/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

lfortran: update to 0.21.5

---

lang/ruby-devel/Portfile
lang/ruby-devel/files/0001-Use-numerical-macOS-versions.patch

Update
macOS 10.6
Xcode 3.2
Have you

ruby-devel: update to 2023.10.13

---

lang/elixir/Portfile

elixir: update to 1.15.6

---

R/R-GenomicRanges/Portfile
R/R-IRanges/Portfile
R/R-PMCMRplus/Portfile
R/R-S4Vectors/Portfile
R/R-bgms/Portfile
R/R-hdpGLM/Portfile
R/R-lefko3/Portfile
R/R-minimaxApprox/Portfile
R/R-pillar/Portfile
R/R-tidySEM/Portfile
R/R-tinytex/Portfile
R/R-utf8/Portfile
R/R-vctrs/Portfile
R/R-vtable/Portfile

Remaining few updates.
macOS 10.6
Xcode 3.2
Have you

R: updates for packages (2)

---

math/arpack/Portfile

arpack: update to 3.9.1

---

devel/jenkins/Portfile

jenkins: update to 2.414.2

---

lang/lfortran/Portfile
lang/lfortran/files/patch-use-sane-install-dirs.diff

Update
macOS 14
Xcode 15
Have you

lfortran: update to 0.22.0, enable llvm

---

security/i2pd/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

i2pd: update to 2.49.0

---

www/tenfourfox/Portfile

This is a PowerPC-only port. I have tested the build locally.
macOS 10.6
Xcode 3.2
Have you

tenfourfox-devel: update to 20230921

---

math/psblas3/Portfile
math/psblas3/files/patch-install-dirs.diff

Update
macOS 10.6
Xcode 3.2
Have you

psblas3: update to 3.8.1

---

devel/cmocka/Portfile

cmocka: update to 1.1.7

---

audio/fluid-soundfont/Portfile

fluid-soundfont: update to 3.1-5.3

---

shells/ksh93-devel/Portfile

Closes https://trac.macports.org/ticket/66509
Have you

ksh93-devel: update to 93u+m/1.0.7

---

devel/re-flex/Portfile

re-flex: update to 3.5.0

---

net/libretroshare/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libretroshare: update to 2023.10.13

---

databases/metabase/Portfile

macOS 13.5.1 22G90 arm64
Have you
- [] tried existing tests with `sudo port test`?

metabase: update to 0.47.4

---

science/veryfasttree/Portfile

veryfasttree: new port

---

R/R-QuickJSR/Portfile
R/R-cpfa/Portfile
R/R-fGarch/Portfile
R/R-gamlss.spatial/Portfile
R/R-gdtools/Portfile
R/R-lavaanExtra/Portfile
R/R-modelsummary/Portfile
R/R-semptools/Portfile

R: remaining weekend updates

---

sysutils/initool/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

initool: update to 0.14.0

---

lang/mlton-bootstrap/Portfile
lang/mlton-bootstrap/files/patch-20130715.diff
lang/mlton/Portfile
lang/mlton/files/patch-rosetta.diff

Update `mlton`, add minor fixes for it and bootstrap compiler.
macOS 10.6
Xcode 3.2
Have you

mlton: update to 20230901, add minor fixes; mlton-bootstrap: add version for 10.6–10.7 x86_64

---

lang/libomp/Portfile

libomp: 17.0.2

---

lang/elixir/Portfile

elixir: update to 1.15.7

---

ocaml/ocaml-rresult/Portfile

ocaml-rresult: new port

---

devel/eask-cli/Portfile

CLI for building, runing, testing, and managing your Emacs Lisp dependencies
macOS 12
Tested with GitHub Actions, see https://github.com/emacs-eask/packaging/actions/runs/6489361688/job/17623483774.
Have you

eask-cli: new port

---

ocaml/ocaml-compiler-libs/Portfile
ocaml/ocaml-cppo/Portfile
ocaml/ocaml-ocamlbuild/Portfile
ocaml/ocaml-ppx_derivers/Portfile
ocaml/ocaml-ppx_deriving/Portfile
ocaml/ocaml-ppx_deriving_yojson/Portfile
ocaml/ocaml-ppxlib/Portfile
ocaml/ocaml-result/Portfile
ocaml/ocaml-sexplib0/Portfile
ocaml/ocaml-yojson/Portfile

A few updates to existing packages.
macOS 10.6
Xcode 3.2
Have you

ocaml-* packages: some updates

---

sysutils/font-manager/Portfile
sysutils/font-manager/files/patch-use-right-python.diff

Let’s see if this one builds.
macOS 10.6
Xcode 3.2
Have you

font-manager: new port

---

devel/dbus/Portfile

(This is not my port, but it misses updating.)
macOS 10.6
Xcode 3.2
Have you

dbus: update to 1.14.10

---

net/get_iplayer/Portfile

get_iplayer: update to 3.33

---

python/py-pefile/Portfile

py-pefile: new port (2023.2.7)

---

devel/n/Portfile

n: update to 9.2.0

---

aqua/squirrel-ime/Portfile
devel/librime-devel/Portfile
editors/textmate2/Portfile

@neverpanic 
macOS x.y
Have you

capnproto: revbump dependents

---

databases/pgpointcloud/Portfile
databases/pgpointcloud/files/patch-config-mk-in.diff
gis/grass/Portfile
gis/grass7/Portfile
gis/pdal/Portfile
gis/qgis3/Portfile
gis/qgis3/files/patch-findpdal-cmake.diff
gis/saga/Portfile
python/py-pdal/Portfile

Notable changes for `pdal`:
- port name is now lower case (and passes lint)
- addition of two new variants: `+draco` and `+tiledb`
- added support for I3S, E57 and PostgreSQL PointCloud
- PostgreSQL support for pre-12 versions is dropped
Note, also the port `pgpointcloud` is updated, the PostgreSQL variants is now replaced by subports (eg. `pg15-pgpointcloud`, where 15 is the PostgreSQL version).
Have you

pdal: enhancements and general tidying up

---

fortran/h5fortran/Portfile
fortran/h5fortran/files/patch-fix-install-dirs.diff

New port: https://github.com/geospace-code/h5fortran
macOS 10.6
Xcode 3.2
Have you

h5fortran: new port in fortran

---

devel/meson/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

meson: update to 1.2.2

---

net/grafana/Portfile

grafana: update to 10.1.5

---

fortran/stock-prices/Portfile
fortran/stock-prices/files/patch-stock-datadir.diff

New port.
macOS 10.6
Xcode 3.2
Have you

stock-prices: new port in fortran

---

security/bitwarden-cli/Portfile

bitwarden-cli: update to 2023.9.1

---

editors/mpvim/Portfile

Closes https://trac.macports.org/ticket/58612
Have you

mpvim: update to 20191228, move to github

---

R/R-clinfun/Portfile
R/R-dimensio/Portfile
R/R-eventPred/Portfile
R/R-marginaleffects/Portfile
R/R-quickcode/Portfile

R: few updates for packages

---

www/nicotine-plus/Portfile

New port: https://github.com/nicotine-plus/nicotine-plus
macOS 14
Xcode 15
Have you

nicotine-plus: new port

---

gis/grass/Portfile

General overhaul of port `grass` and new `grass-gui` subport.
Notable changes:
- remove PG wxWidgets, not needed, it is installed with wxPython
- remove PG github, official release site osgeo.org
- rename `+openmpi` variant to the more correct `+openmp`, remove compilers settings (goes with removing PG compilers)
- remove PostgreSQL pre-12 variants
- update description
- organise variants alphabetically and minor formatting changes
- replace `+gui` variant with new subport `grass-gui`
Have you

grass: general overhaul and new 'grass-gui' subport

---

perl/exiftool/Portfile
perl/p5-image-exiftool/Portfile

exiftool: update to 12.68

---

devel/md4c/Portfile

https://github.com/mity/md4c/blob/release-0.4.8/CHANGELOG.md
macOS 13.6
Command Line Tools 15
Have you

md4c: update to 0.4.8

---

python/py-crcmod/Portfile

py-crcmod: add py312 subport

---

python/py-mupdf/Portfile

py-mupdf: add py312 subport

---

R/R-DynDoc/Portfile
R/R-Qindex/Portfile
R/R-Rgof/Portfile
R/R-Rlibkdv/Portfile
R/R-bWGR/Portfile
R/R-cauchypca/Portfile
R/R-cgwtools/Portfile
R/R-deming/Portfile
R/R-esemifar/Portfile
R/R-fuj/Portfile
R/R-hstats/Portfile
R/R-lattice/Portfile
R/R-ldt/Portfile
R/R-magick/Portfile
R/R-multibias/Portfile
R/R-plotly/Portfile
R/R-priceR/Portfile
R/R-qcauchyreg/Portfile
R/R-qlcal/Portfile
R/R-rclipboard/Portfile
R/R-rmpw/Portfile
R/R-rsq/Portfile
R/R-scribe/Portfile
R/R-sharp/Portfile
R/R-telefit/Portfile
R/R-tkWidgets/Portfile
R/R-ufRisk/Portfile
R/R-widgetTools/Portfile
R/R-wk/Portfile

R: weekend updates and a few new packages

---

net/wireshark3/Portfile
net/wireshark4/Portfile

Closes: https://trac.macports.org/ticket/68362
macOS x.y
Have you

wireshark{3,4}: fix python selection

---

sysutils/coreutils-uutils/Portfile

coreutils-uutils: update to 0.0.22

---

python/py-awscli2/Portfile

py-awscli2: update to 2.13.28

---

x11/freeglut/Portfile

Move to github from sourceforge mirror
Have you

freeglut: update to 3.4.0

---

python/py-mkl/Portfile
python/py-numpy/Portfile
python/py-numpy/files/patch-build_cython_path.diff
python/py-pyproject_metadata/Portfile

py-numpy: update to 1.26.1, add py312 subport; likewise for dependencies

---

databases/sqlite3-pcre2/Portfile
databases/sqlite3-pcre2/files/prec2_c.diff
databases/sqlite3-pcre2/files/test.sh

Adds a new port for a SQLite 3 extension, enabling regular expression support (based on pcre2). The extension is installed at `${prefix}/lib/sqlite3` and may be used by e.g. `sqlite3` or `spatialite`:
```
/opt/local/bin/sqlite3
sqlite> .load /opt/local/lib/sqlite3/pcre2.dylib
sqlite> SELECT "asdf" REGEXP "(?i)^A";
...
```
Have you

sqlite3-pcre2: new port with SQLite regex extension

---

mail/notmuch/Portfile

notmuch: Bump to version 0.38

---

games/paclear/Portfile

paclear: new port

---

ocaml/ocaml-bin_prot/Portfile
ocaml/ocaml-fieldslib/Portfile
ocaml/ocaml-jane-street-headers/Portfile
ocaml/ocaml-jst-config/Portfile
ocaml/ocaml-num/Portfile
ocaml/ocaml-ppx_base/Portfile
ocaml/ocaml-ppx_bench/Portfile
ocaml/ocaml-ppx_bin_prot/Portfile
ocaml/ocaml-ppx_disable_unused_warnings/Portfile
ocaml/ocaml-ppx_enumerate/Portfile
ocaml/ocaml-ppx_fields_conv/Portfile
ocaml/ocaml-ppx_globalize/Portfile
ocaml/ocaml-ppx_inline_test/Portfile
ocaml/ocaml-ppx_log/Portfile
ocaml/ocaml-ppx_module_timer/Portfile
ocaml/ocaml-ppx_optcomp/Portfile
ocaml/ocaml-ppx_string/Portfile
ocaml/ocaml-ppx_typerep_conv/Portfile
ocaml/ocaml-ppx_variants_conv/Portfile
ocaml/ocaml-re/Portfile
ocaml/ocaml-sexp_pretty/Portfile
ocaml/ocaml-sexplib/Portfile
ocaml/ocaml-splittable_random/Portfile
ocaml/ocaml-time_now/Portfile
ocaml/ocaml-typerep/Portfile
ocaml/ocaml-uutf/Portfile
ocaml/ocaml-variantslib/Portfile

@pmetzger After this is merged, next PR will have `core` and the rest.
macOS 10.6
Xcode 3.2
Have you

ocaml: new packages, a couple of updates

---

gis/gdal-grass/Portfile
gis/grass/Portfile

Update `grass` to version 8.3.1.
Have you

grass: update to version 8.3.1

---

devel/docker/Portfile

Also remove unnecessary platforms line
Have you

docker: update to 24.0.6

---

mail/rspamd/Portfile

rspamd: Update to version 3.6

---

games/barrage/Portfile

barrage: update to 1.0.7

---

R/R-AnnotationDbi/Portfile
R/R-AnnotationForge/Portfile
R/R-BioNet/Portfile
R/R-Biostrings/Portfile
R/R-DelayedArray/Portfile
R/R-DelayedMatrixStats/Portfile
R/R-DelayedRandomArray/Portfile
R/R-GenomeInfoDb/Portfile
R/R-GenomicAlignments/Portfile
R/R-GenomicFeatures/Portfile
R/R-GenomicRanges/Portfile
R/R-IRanges/Portfile
R/R-IRanges/files/patch-remove-unavailable-suggests.diff
R/R-KEGGREST/Portfile
R/R-KEGGgraph/Portfile
R/R-MatrixGenerics/Portfile
R/R-ResidualMatrix/Portfile
R/R-Rhdf5lib/Portfile
R/R-Rhtslib/Portfile
R/R-Rsamtools/Portfile
R/R-S4Arrays/Portfile
R/R-ScaledMatrix/Portfile
R/R-ShortRead/Portfile
R/R-SparseArray/Portfile
R/R-SummarizedExperiment/Portfile
R/R-XVector/Portfile
R/R-XVector/files/patch-no-drosophila2probe.diff
R/R-biomaRt/Portfile
R/R-rtracklayer/Portfile
R/R-sparseMatrixStats/Portfile

 R: updates to packages – 2 (new release of BioConductor)

---

gnome/gtk-internet-radio-locator/Portfile

gtk-internet-radio-locator 5.0.0
Have you

gtk-internet-radio-locator: new version (5.0.0)

---

fortran/h5fortran/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

h5fortran: update to 4.10.4

---

www/roundcubemail/Portfile

* Move to github
* 1.6 and newer drop support for under PHP 7.3
* Update license (https://roundcube.net/license/)
* Use https
Closes https://trac.macports.org/ticket/54353
Have you

roundcubemail: update to 1.6.4

---

net/oxenc/Portfile

Update
macOS 14
Xcode 15
Have you

oxenc: update to 1.0.9

---

lang/lfortran/Portfile
lang/lfortran/files/patch-version.diff

Update
macOS 14
Xcode 15
macOS 10A190
Xcode 3.2
Have you

lfortran: update to 0.28.0

---

.github/workflows/bootstrap.sh

See: https://trac.macports.org/ticket/68563
Have you

CI: temporarily prefer mirror

---

math/radian/Portfile

Simple update.
macOS 10.6
Xcode 3.2
Have you

radian: update to 0.6.8

---

sysutils/yabai/Portfile
sysutils/yabai/files/patch-makefile-macos11.diff

yabai: update to version 6.0.0

---

dotnet/aspnetcore-runtime-2.1/Portfile
dotnet/aspnetcore-runtime-3.1/Portfile
dotnet/aspnetcore-runtime-6/Portfile
dotnet/aspnetcore-runtime-7/Portfile
dotnet/dotnet-cli/Portfile
dotnet/dotnet-runtime-2.1/Portfile
dotnet/dotnet-runtime-3.1/Portfile
dotnet/dotnet-runtime-6/Portfile
dotnet/dotnet-runtime-7/Portfile
dotnet/dotnet-sdk-2.1/Portfile
dotnet/dotnet-sdk-3.1/Portfile
dotnet/dotnet-sdk-6/Portfile
dotnet/dotnet-sdk-7/Portfile

As promised, some file changes:
- `dotnet-cli`: not providing `host` folder any longer as `hostfxr`s should be shipped with matching runtimes
- `aspnetcore-runtime-2.1`: add missing `Microsoft.AspNetCore.All` folder that contains extra runtimes and plugins
- `aspnetcore-runtime-*`: add `dotnet-runtime-*` as dependency
- `dotnet-runtime-*`: provide `hostfxr`s for now on
- `dotnet-sdk-{3.1, 6, 7}`: now provide target packs and apphost packs that are useful for Visual Studio/third-party analyzers & debuggers
Version changes:
- `dotnet-runtime-7` & `aspnetcore-runtime-7`: update to 7.0.13
- `dotnet-sdk-7`: update to 7.0.403
- `dotnet-runtime-6` & `aspnetcore-runtime-6`: update to 6.0.24
- `dotnet-sdk-6`: update to 6.0.416
- `*-2.1` & `*-3.1`: mark as EOL
Command Line …

dotnet-*: update to 6.0.416;7.0.403 & add missing files

---

R/R-BayesKnockdown/Portfile
R/R-ComplexHeatmap/Portfile
R/R-DECIPHER/Portfile
R/R-DESeq2/Portfile
R/R-EBImage/Portfile
R/R-EnrichedHeatmap/Portfile
R/R-HilbertCurve/Portfile
R/R-HilbertVis/Portfile
R/R-MassSpecWavelet/Portfile
R/R-MsCoreUtils/Portfile
R/R-aldvmm/Portfile
R/R-annotate/Portfile
R/R-apeglm/Portfile
R/R-bssm/Portfile
R/R-csaw/Portfile
R/R-dcanr/Portfile
R/R-dm/Portfile
R/R-edgeR/Portfile
R/R-edgeR/files/patch-no-org.Hs.eg.db.diff
R/R-gdalraster/Portfile
R/R-genefilter/Portfile
R/R-ggtree/Portfile
R/R-ggtreeExtra/Portfile
R/R-graphite/Portfile
R/R-here/Portfile
R/R-here/files/patch-no-broken-palmerpenguins.diff
R/R-ichimoku/Portfile
R/R-interactiveDisplayBase/Portfile
R/R-kebabs/Portfile
R/R-treeio/Portfile

Turned out, I missed out many Bioconductor packages in the recent updates. Updating now.
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (1)

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff
python/py-awscrt/Portfile

py-awscli2: update to 2.13.30

---

science/madness/Portfile
science/madness/files/0002-Do-not-build-chem-it-is-broken.patch
science/madness/files/0003-Do-not-build-apps-they-depend-on-chem.patch

Update with a minor fix.
macOS 10.6
Xcode 3.2
Have you

madness: update to 2023.09.29

---

graphics/tkimg/Portfile
lang/tcl/Portfile
x11/tk/Portfile

I do not consider myself more than a beginner in Tcl/Tk, but I feel I have interacted with these ports and their upstream development (particularly C internals) enough to be okay with comaintaining them.
Have you

tcl, tk, tkimg: comaintain

---

devel/gk/Portfile

macOS 13.2 22D49 x86_64
Have you

gk: Upgrade to 1.1.3

---

math/spral/Portfile
math/spral/files/patch-fix-cxx11.diff

New port: https://github.com/ralna/spral
macOS 10.6
Xcode 3.2
Have you

spral: new port in math

---

net/ngtcp2/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ngtcp2: update to 1.0.1

---

finance/bitcoin/Portfile

bitcoin: update to 25.1

---

security/aide/Portfile

aide: update to 0.18.6

---

fortran/feq-parse/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

feq-parse: update to 2023.09.27

---

fortran/runge-kutta-fortran/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

runge-kutta-fortran: update to 1.0.1

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.1.18

---

python/py-rpds-py/Portfile
python/py-rpds_py/Portfile

py-rpds_py: added new port, version 0.10.6

---

cross/android-ndk/Portfile

android-ndk: change homepage, remove platforms darwin

---

lang/antlr3/Portfile

antlr3: update to 3.5.3, use https

---

gis/qgis3/Portfile

- Update `qgis3` to version 3.34.0 with new (default) `+draco` variant and update `qgis3-ltr` to version 3.28.12.
- PostgreSQL support for pre-12 version is dropped.
- General tidying up of the Portfile
Have you

qgis3{-ltr}: update to 3.34.0 and 3.28.12 (LTR)

---

devel/wolfssl/Portfile

wolfssl: update to version 5.6.4

---

R/R-bayesmlogit/Portfile
R/R-doBy/Portfile
R/R-evaluate/Portfile
R/R-glmtrans/Portfile
R/R-jinjar/Portfile
R/R-pROC/Portfile
R/R-rasterVis/Portfile
R/R-transreg/Portfile
R/R-xfun/Portfile
R/R-xrnet/Portfile

R: remaining updates for packages

---

python/py-esda/Portfile
python/py-inequality/Portfile
python/py-spglm/Portfile
python/py-spreg/Portfile

Updates:
- `py-esda` to version 2.5.1
- `py-inequality` to version 1.0.1
- `py-spglm` to version 1.1.0
- `py-spreg` to version 1.4.1
Have you

PYSAL family ports updates

---

python/py-palettable/Portfile

Remove py37
macOS 12.7 21G816 x86_64
Have you

py-palettable: upgrade to 3.3.3, add py311

---

python/py-monty/Portfile

macOS 12.7 21G816 x86_64
Have you

py-monty: update to 2023.9.25, add py311 and py312

---

devel/gn/Portfile
devel/gn/files/0001-gen.py-do-not-force-random-macOS-version.patch
devel/gn/files/0002-mac-scoped-do-not-use-objc-types-when-unsupported.patch
devel/gn/files/0003-Fix-undefined-version-due-to-configure-not-honoring-.patch
devel/gn/files/0004-build_config.h-sys_info.cc-args.cc-fix-PowerPC-defin.patch
devel/gn/files/0005-semaphore-use-libdispatch-only-where-it-actually-exi.patch

Let’s see if this builds.
UPD. Yes, it does :)
macOS 10.6
Xcode 3.2
Have you

gn: new port in devel

---

security/libressl/Portfile

macOS 14.2 23C5030f arm64
Have you

libressl: update to 3.8.2

---

devel/gk/Portfile

gk: update to 1.1.4

---

python/py-fypp/Portfile

@reneeotten We don’t need that `python.pep517 yes` anymore, or do we?
macOS 10.6
Xcode 3.2
Have you

py-fypp: update to 3.2

---

net/get_iplayer/Portfile

get_iplayer: update to 3.34

---

gis/gdal/Portfile
python/py-gdal/Portfile

Update `gdal` and `py-gdal` to version 3.7.3.
Have you

gdal, py-gdal: update to version 3.7.3

---

sysutils/asciinema/Portfile

asciinema: update to 2.4.0

---

devel/sbt-0.7/Portfile
devel/sbt/Portfile

Update sbt to the last version and obsolete legacy sbt-0.7 which can't be used because depednency doesn't exists any more.
Have you

sbt: update to 1.9.7

---

lang/castxml/Portfile

Update `castxml` to version 0.6.2.
Have you

castxml: update to version 0.6.2

---

devel/pnpm/Portfile

Update pnpm to 8.10.2
Have you

pnpm: update to 8.10.2

---

gis/cgal5/Portfile
gis/sfcgal/Portfile

- Update `cgal5` to version 5.6.
- Update `sfcgal` to version 1.5.0 and switch to `cmake 1.1` port group
Have you

cgal5, sfcgal: updates

---

python/py-scikit-build-core/Portfile

macOS 12.7 21G816 x86_64
Have you

py-scikit-build-core: new port

---

python/py-dbus_next/Portfile

New port.
macOS 10.6
Xcode 3.2
Have you

py-dbus_next: new port

---

python/py-survey/Portfile

New port.
P. S. I do not randomly pick Python packages all of a sudden now; I wanna have `maestral` port, and that requires quite a number of dependencies.
macOS 10.6
Xcode 3.2
Have you

py-survey: new port

---

python/py-pyfatfs/Portfile

py-pyfatfs: add missing dependency on py-setuptools_scm

---

devel/cpp-argparse-dev/Portfile

cpp-argparse-dev: update to v1.8.3

---

R/R-MatrixModels/Portfile
R/R-RgoogleMaps/Portfile
R/R-RgoogleMaps/files/patch-no-PBSmapping.diff
R/R-forsearch/Portfile
R/R-hdf5r.Extra/Portfile
R/R-mlflow/Portfile
R/R-rSPDE/Portfile
R/R-rSPDE/files/patch-no-INLA.diff
R/R-stacks/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: few updates to packages

---

math/asl/Portfile

asl: update to 20230908

---

games/kmasterpiece/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

kmasterpiece: new port in games

---

python/py-spreg/Portfile

Update `py-spreg`  to version 1.4.2.
Have you

py-spreg: update to version 1.4.2

---

x11/auto-multiple-choice/Portfile

auto-multiple-choice-devel : update to version 1.6.0-git20231107111512
A topic feature has been added, allowing you to group together sets of questions to calculate a score and obtain a level of success. The aim is to enable skills to be assessed.
macOS 14.1 23B74 arm64
Xcode 15.0.1 15A507 
MacPorts 2.8.1
Have you

auto-multiple-choice-devel : update to version 1.6.0-git20231107111512

---

math/singular/Portfile

singular: update to 4.3.2p10

---

devel/rapidjson-devel/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

rapidjson-devel: update to 2023.09.28

---

lang/logtalk/Portfile

logtalk: update to 3.72.0

---

devel/libraqm/Portfile

Update `libraqm` to version 0.10.1.
Closes https://trac.macports.org/ticket/65907
Replaces partly #19560
macOS x.y
Have you

libraqm: update to version 0.10.1

---

math/hypre/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

hypre: update to 2.30.0

---

math/polymake/Portfile

Closes: https://trac.macports.org/ticket/67813
Closes: https://trac.macports.org/ticket/67350
Have you

polymake: update to 4.11

---

R/R-Carlson/Portfile
R/R-NNS/Portfile
R/R-adbcdrivermanager/Portfile
R/R-brnn/Portfile
R/R-cppdoubles/Portfile
R/R-fmtr/Portfile
R/R-plotrix/Portfile
R/R-rEDM/Portfile
R/R-runMCMCbtadjust/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: remaining few updates to packages

---

databases/metabase/Portfile

metabase: update to 0.47.7

---

devel/jenkins/Portfile

macOS 14.1 23B74 arm64
Have you

jenkins: update to 2.414.3

---

science/elmerfem/Portfile

Update.
macOS 10.6
Xcode 3.2
Have you

elmerfem: update to 2023.11.09

---

python/py-owslib/Portfile

Update `py-owslib` to version 0.29.3 and update homepage url.
Have you

py-owslib: update to version 0.29.3 and new homepage

---

gis/kealib/Portfile

Update `kealib`to version 1.5.2.
Have you

kealib: update to version 1.5.2

---

python/py-serpent/Portfile

Update, drop archaic pythons 3.x, support new ones.
macOS 10.6
Xcode 3.2
Have you

py-serpent: update to 1.41, support new pythons

---

science/geos/Portfile

Update `geos` homepage URL.
macOS x.y
Have you

geos: update homepage url

---

net/grafana/Portfile

grafana: update to 10.2.0

---

net/zmap/Portfile

macOS 14.2 23C5030f arm64
Have you

zmap: update to 4.0-RC1

---

science/scifor/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

scifor: update to 4.10.9

---

python/py-ply/Portfile

Add Python 3.12 support to `py-ply`.
Patch unittest.assert_() which was removed with Python 3.12 (https://docs.python.org/3/whatsnew/3.12.html#id3).
macOS x.y
Have you

py-ply: add Python 3.12 support

---

security/totp-cli/Portfile

totp-cli: update to version 1.8.2
* Update go.setup in Portfile to version 1.8.2
* Update the go packages in go.vendors in the Portfile to the latest versions
* Remove unneeded go packages from go.vendors in the Portfile
* Add the "gitHub.com/urfave/cli" go package to go.vendors in the Portfile
* Add the "github.com/cpuguy83/go-md2man" go package to go.vendors in the Portfile
* Add the "github.com/xrash/smetrics" go package to go.vendors in the Portfile
* Add the "github.com/russross/blackfriday" go package to go.vendors in the Portfile
* Add the "github.com/FiloSottile/age" go package to go.vendors in the Portfile
* Add post-extract code block to the Portfile with a symlink for the "filippo.io/age" go package pointing to the "github.com/FiloSottile/age" go package (since go-vendors …

totp-cli: update to version 1.8.2

---

python/py-dulwich/Portfile

py-dulwich: update to 0.21.6

---

python/py-toml/Portfile
python/py-tomli/Portfile

Add Python 3.12 support to `py-toml` and `py-tomli`.
Have you

py-toml, py-tomli: add Python 3.12 support

---

python/py-keyrings.alt/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

py-keyrings.alt: new port

---

x11/homebank/Portfile

homebank: update to 5.7.1

---

python/py-Pyro5/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

py-Pyro5: new port

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff
python/py-awscrt/Portfile

py-awscli2: update to 2.13.34

---

devel/cpp-argparse-dev/Portfile

cpp-argparse-dev: update to v1.8.4

---

graphics/jhead/Portfile

jhead: update to 3.08

---

devel/dialog/Portfile

dialog: update to 1.3-20231002

---

security/totp-cli/Portfile

top-cli:  update to version 1.8.3
* Update version number in go.setup to version 1.8.3
* Add "legacy support 1.1" PortGroup
* Add pre-build code block needed to build the port on legacy Macs running Sierra and earlier
Have you

top-cli:  update to version 1.8.3

---

palm/m68k-palm-elf-binutils/Portfile
palm/m68k-palm-elf-gcc/Portfile
palm/m68k-palm-elf-gcc/files/aarch64.diff
palm/m68k-palm-elf-gcc/files/palm.diff
palm/m68k-palm-elf-gcc/files/retro68.diff

(Bringing back #15893 now that I've finally fixed it up)
This is [the other half of][2] a toolchain for building Palm OS apps. It consists of the Retro68 fork of gcc 9.1.0, with a few patches from [dmitrygr][3].
I got the source from [here][1] (not a good master site cause it's a google drive link), and diffed it against gcc 9.1.0 and [Retro68][4] to get a set of patches. I also applied a small fix so it builds on arm.
[1]: https://old.reddit.com/r/Palm/comments/p81m58/announce_new_gcc_or_palmos_again/
[2]: https://github.com/macports/macports-ports/pull/15788
[3]: http://palmpowerups.com/index.php
[4]: https://github.com/autc04/Retro68
Have you

m68k-palm-elf-gcc: new port

---

math/fxt/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fxt: update to 2023.10.29

---

sysutils/rtx/Portfile

rtx: update to 2023.11.2

---

devel/sccache/Portfile

sccache: update to 0.7.1

---

R/R-V8/Portfile
R/R-V8/files/patch-fix-configure.diff
R/R-V8/files/patch-gcc-permissive.diff
lang/v8-8.3/Portfile
lang/v8-8.3/files/0001-Restore-ppc32-patches-from-upstream.patch
lang/v8-8.3/files/0002-inspector-unbreak-build-with-gcc.patch
lang/v8-8.3/files/0003-cpu.cc-support-powerpc-darwin.patch
lang/v8-8.3/files/0004-semaphore-use-libdispatch-only-where-it-is-available.patch
lang/v8-8.3/files/0005-runtime-utils.h-fix-static_cast.patch
lang/v8-8.3/files/0006-Register-specs-for-powerpc-darwin.patch
lang/v8-8.3/files/0007-platform-posix.cc-for-powerpc-darwin.patch
lang/v8-8.3/files/0008-isolate-data.h-disable-asserts-for-now.patch
lang/v8-8.3/files/0009-embedded-file-writer-mac-support-powerpc.patch
lang/v8-8.3/files/0010-Add-some-missing-headers-and-use-cinttypes-consisten.patch
lang/v8-8.3/files/0011-libsampler-support-powerpc-and-aarch64.patch
lang/v8-8.3/files/0012-macro-assembler-ppc.h-fix-asserts-for-ppc.patch
lang/v8-8.3/files/0013-CMakeLists-support-ppc-and-aarch64.patch
lang/v8-8.3/files/0014-tnode.h-backport-fix-for-is_convertible.patch

A brief on the status of V8 itself:
– Confirmed to build reliably for x86_64; confirmed to be functional on x86_64.
– Confirmed to build on aarch64.
– Builds for `ppc`, but needs further work on it.
While my aim with this is to support PPC, I guess, merging it first (given that Intel is good) will make it easier to debug and fix powerpc installation. Then, provided this works, we can get NodeJS built against external V8; this version should support NodeJS 14.
`R-V8`: _tests pass on x86_64;_ on ppc and aarch64 it fails to build at the moment.
macOS 10.6
Xcode 3.2
Xcode 4.2
macOS 14
Xcode 15
Have you

R-V8: new R package; v8-8.3: new port in lang

---

R/R-DoE.base/Portfile
R/R-Matrix/Portfile
R/R-OBsMD/Portfile
R/R-TruncExpFam/Portfile
R/R-cdmTools/Portfile
R/R-fungible/Portfile
R/R-gmvarkit/Portfile
R/R-hal9001/Portfile
R/R-httr2/Portfile
R/R-nor1mix/Portfile
R/R-refund/Portfile
R/R-robustlmm/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: remaining updates to packages

---

python/py-h5py/Portfile

py-h5py has its own checks; revbump for hdf5 update.

---

python/py-desktop-notifier/Portfile
python/py-pytest-rerunfailures/Portfile
sysutils/maestral/Portfile

And a couple of Python-related dependencies.
macOS 14.1.1
Xcode 15
macOS 10.6
Xcode 3.2
Have you

maestral: new port in sysutils

---

math/blaspp/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

blaspp: update to 2023.11.05

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.1.19

---

R/R-AICcmodavg/Portfile
R/R-GPArotation/Portfile
R/R-MAPA/Portfile
R/R-PStrata/Portfile
R/R-RMSDp/Portfile
R/R-SPEI/Portfile
R/R-SparseArray/Portfile
R/R-TLMoments/Portfile
R/R-arima2/Portfile
R/R-dst/Portfile
R/R-duckdb/Portfile
R/R-finalfit/Portfile
R/R-ggpmisc/Portfile
R/R-gpindex/Portfile
R/R-igcop/Portfile
R/R-leiden/Portfile
R/R-mclust/Portfile
R/R-mcmc/Portfile
R/R-mirai/Portfile
R/R-misty/Portfile
R/R-multiplex/Portfile
R/R-paran/Portfile
R/R-rclipboard/Portfile
R/R-textrecipes/Portfile
R/R-tidyindex/Portfile
R/R-tsutils/Portfile
R/R-umx/Portfile
R/R-vetiver/Portfile

Mostly updates, some new ports.
macOS 10.6
Xcode 3.2
Have you

R: updates to packages and a few new ones

---

databases/iowow/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

iowow: update to 1.4.17

---

x11/homebank/Portfile

homebank: update to 5.7.2

---

devel/re-flex/Portfile

re-flex: update to 3.5.1

---

python/poetry/Portfile
python/py-cleo/Portfile
python/py-poetry-core/Portfile
python/py-poetry-plugin-export/Portfile

poetry: update to 1.7.1

---

games/fheroes2/Portfile

fheroes2: update to 1.0.10

---

java/VisualVM/Portfile

macOS 14.1.1 23B81 x86_64
Have you
- x ] tested basic functionality of all binary files?

VisualVM: update to 2.1.7

---

R/R-Icens/Portfile
R/R-R6causal/Portfile
R/R-cfid/Portfile
R/R-cfid/files/patch-no-dagitty.diff
R/R-dosearch/Portfile
R/R-extendedFamily/Portfile
R/R-factor256/Portfile
R/R-fdasrvf/Portfile
R/R-fdth/Portfile
R/R-fritools/Portfile
R/R-jacobi/Portfile
R/R-nlopt/Portfile
R/R-yeastNagalakshmi/Portfile
_resources/port1.0/group/R-1.0.tcl

Some new ports and a few updates
macOS 10.6
Xcode 3.2
Have you

R: few new packages and weekend updates

---

science/madness/Portfile

Fixes: https://trac.macports.org/ticket/68721
Also ensures a specific python is found and not whatever happens to be picked.
Updates, fixes.
macOS 10.6
Xcode 3.2
Have you

madness: update to 2023.11.02, fix build

---

net/toxcore/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

toxcore: update to 2023.11.18

---

ocaml/ocaml-mmap/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-mmap: update to 1.2.0

---

shells/oksh/Portfile

oksh: update to 7.4

---

python/py-igraph/Portfile

py-igraph: update to 0.11.3

---

python/py-argcomplete/Portfile

py-argcomplete: update to 3.1.6, add py312 subport
Have you

py-argcomplete: update to 3.1.6, add py312 subport

---

python/py-m2crypto/Portfile

Closes: https://trac.macports.org/ticket/66337
Have you

py-m2crypto: update to 0.39.0

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff
python/py-awscrt/Portfile

py-awscli2: update to 2.13.37

---

sysutils/watch/Portfile

macOS 14.1.1 23B81 x86_64
Have you

watch: add missing gettext build dependency

---

net/openiked/Portfile

macOS 14.2 23C5047e arm64
Have you

openiked: update to 7.3

---

net/snac/Portfile

macOS 14.2 23C5047e arm64
Have you

snac: update to 2.43

---

science/libminc/Portfile

libminc: update to 2.4.06; remove obsolete dependencies

---

net/cgmnlm/Portfile
net/cgmnlm/files/patch-client.c.diff
net/cgmnlm/files/patch-no-werror.diff

New port: https://git.sr.ht/~rwa/cgmnlm
macOS 10.6
Xcode 3.2
macOS 14.1.1
Xcode 15.0.1
Have you

cgmnlm: new port in net

---

R/R-FuzzyResampling/Portfile
R/R-GGally/Portfile
R/R-assertr/Portfile
R/R-bslib/Portfile
R/R-crosstalk/Portfile
R/R-ggstats/Portfile
R/R-ggthemes/Portfile
R/R-ggthemes/files/patch-drop-v8.diff
R/R-htmlwidgets/Portfile
R/R-jagshelper/Portfile
R/R-mlflow/Portfile
R/R-polyhedralCubature/Portfile
R/R-tidydann/Portfile
R/R-tidyfit/Portfile
R/R-tidyterra/Portfile
R/R-tinytex/Portfile

Since I am temporarily away from PPC hardware, only safe updates (nothing-to-compile pure R code) are included.
macOS 14.1.1
Xcode 15.0.1
Have you

R: some updates to packages

---

devel/geoipupdate/Portfile

macOS 14.1.1 23B81 x86_64
Have you

geoipupdate: update to 6.0.0 and corrects license

---

x11/tix/Portfile
x11/tktable/Portfile

I have not personally used tix or tktable that much but would still like to be notified of changes or issues with these ports.
Have you

tktable, tix: maintain

---

x11/tkdnd/Portfile

I am not a proficient TkDND user but would still like to be notified of changes and issues for this port.
Have you

tkdnd: comaintain

---

python/pipx/Portfile

pipx: add python312 variant
Have you

pipx: add python312 variant

---

databases/postgis3/Portfile

Update `postgis3` to version 3.4.1, add `address_standardizer` variant, together with a general Portfile clean-up and re-organisation.
Have you

postgis3: update to version 3.4.1; general Portfile overhaul

---

graphics/gimp2-devel/Portfile

gimp2-devel: update to 2.10.36

---

graphics/photoqt/Portfile
graphics/photoqt/files/patch-exiv2.diff
graphics/photoqt/files/patch-include-magick.diff

@reneeotten @pmetzger I think this is fixed now. Sorry for a delay.
macOS 14.1.1
Xcode 15
macOS 10.6
Xcode 3.2
Have you

photoqt: new port in graphics

---

lang/libcxx-powerpc/Portfile
lang/libcxx-powerpc/files/0001-more-ppc-hacks-on-libcxxabi.patch
lang/libcxx-powerpc/files/0002-libcxx-test-UNSUPPORT-10.6-and-10.5-for-aligned-allo.patch
lang/libcxx-powerpc/files/0003-libcxx-Actually-push-macosx-version-so-that-UNSUPPOR.patch
lang/libcxx-powerpc/files/0004-libcxx-If-we-have-a-sysroot-don-t-try-to-use-xcrun-s.patch
lang/libcxx-powerpc/files/0005-more-ppc-hacks-on-libcxx.patch
lang/libcxx-powerpc/files/0006-libcxx-Updated-version-of-David-Fang-s-wrapper-for-m.patch
lang/libcxx-powerpc/files/0007-Fix-up-thread-constexpr-for-GCC-where-the-PPC-port-c.patch
lang/libcxx-powerpc/files/0008-libcxx-cmake-Make-sure-to-find-the-abi-lib-that-we-j.patch
lang/libcxx-powerpc/files/0009-libcxx-cmake-if-a-LIBCXX_SYSROOT-is-given-this-pre-e.patch
lang/libcxx-powerpc/files/0010-Add-coroutine-header.patch
lang/libcxx-powerpc/files/0011-libcxx-libcxxabi-minor-fix-to-linking.patch
lang/libcxx-powerpc/files/0012-disable-Apple-libc-Availability-tests.patch
lang/libcxx-powerpc/files/0013-Fix-missing-long-long-math-prototypes-when-using-the.patch
lang/libcxx-powerpc/files/0014-implement-atomic-using-mutex-lock_guard-for-64b-ops-.patch
lang/libcxx-powerpc/files/CMakeLists.txt

(Don’t really know why we did not make this earlier.)
macOS 10.6
Xcode 3.2
Have you

libcxx-powerpc: libc++ and libc++abi for PowerPC

---

emulators/uxn/Portfile
emulators/uxn/files/patch-uxn-build.diff

uxn: update to 20231125

---

net/yggdrasil-go/Portfile

yggdrasil-go: update to 0.5.4

---

python/py-XlsxWriter/Portfile
python/py-pptx/Portfile

py-{pptx,xlsxwriter}: Update to latest

---

graphics/tkimg/Portfile

As requested by https://github.com/macports/macports-ports/pull/21578#issuecomment-1829211890
Have you

tkimg: HTTPS homepage

---

math/OpenBLAS/Portfile
math/OpenBLAS/files/patch-enable-overstep-of-too-long-args-without-DYNAMIC_ARCH.diff
math/OpenBLAS/files/patch-openblas.pc-fixed-version-and-url.diff
math/OpenBLAS/files/patch-weak-linking-old-macos.diff

macOS 10.5.8 9L34 i386
Xcode 3.1.4 9M2809
Have you

OpenBLAS: follow up after switch to cmake

---

python/py-apsw/Portfile

Update, move to PyPi.
macOS 14.1.1
Xcode 15.0.1
Have you

py-apsw: update to 3.44.0.0

---

python/py-rchitect/Portfile

Closes: https://trac.macports.org/ticket/68796
Update, fix deps.
macOS 14.1.1
Xcode 15.0.1
Have you

py-rchitect: update to 0.4.4

---

python/py-clang/Portfile

py-clang: drop 15, add 17

---

lang/swi-prolog-devel/Portfile

macOS 14.1.1 23B81 arm64
Have you

swi-prolog-devel: Updated to version 9.1.20

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff
python/py-awscrt/Portfile

py-awscli2: update to 2.14.4

---

sysutils/lima/Portfile

lima: update to v0.19.0

---

math/mcmcf90/Portfile
math/mcmcf90/files/patch-dynlib.diff

New port in math: https://github.com/mjlaine/mcmcf90
Xcode 3.2.6
Have you

mcmcf90: new port in math

---

math/bpack/Portfile
math/bpack/files/patch-examples.diff

Update.
macOS 10.6
Xcode 3.2
Have you

bpack: update to 2.4.0

---

python/py-autoflake/Portfile

Update
macOS 14.1.2
Xcode 15.0.1
Have you

py-autoflake: update to 2.2.1

---

python/py-cliff/Portfile

Update
macOS 14.1.2
Xcode 15.0.1
Have you

py-cliff: update to 4.4.0

---

python/py-cjson/Portfile

Update
macOS 14.1.2
Xcode 15.0.1
Have you

py-cjson: update to 1.2.2

---

math/libKriging/Portfile
math/libKriging/files/patch-CMakeLists.diff

Upstream did something strange, deleting a version tag, which has broken the build.
Use commit for now, fix the build.
macOS 14.1.1
Xcode 15.0.1
Have you

libKriging: unbreak build

---

science/oof2/Portfile

Update to version 2.3.2
Have you

oof2: update to version 2.3.2

---

python/py-jsonschema-specifications/Portfile

Port required for future py-jsonschema upgrade
Have you

py-jsonschema-specifications: added new port, version 2023.11.1

---

R/R-RCLabels/Portfile
R/R-TaylorRussell/Portfile
R/R-bookdown/Portfile
R/R-dformula/Portfile
R/R-kcmeans/Portfile
R/R-ldbounds/Portfile
R/R-matsbyname/Portfile
R/R-matsindf/Portfile
R/R-vars/Portfile
R/R-vizdraws/Portfile

Some new ports and updates.
macOS 14.1.2
Xcode 15.0.1
Have you

R: a few updates and some new packages

---

python/py-fastapi/Portfile

Update
macOS 14.1.2
Xcode 15.0.1
Have you

py-fastapi: update to 0.104.1

---

python/py-cmd2/Portfile

Update
macOS 14.1.2
Xcode 15.0.1
Have you

py-cmd2: update to 2.4.3

---

multimedia/scrcpy/Portfile

macOS 14.0 23A339 arm64
Have you

scrcpy: Update to version 2.3.1

---

R/R-AmesHousing/Portfile
R/R-FHtest/Portfile
R/R-IPEC/Portfile
R/R-PStrata/Portfile
R/R-RODBC/Portfile
R/R-RcppClassicExamples/Portfile
R/R-SQRL/Portfile
R/R-SurvMetrics/Portfile
R/R-aorsf/Portfile
R/R-baguette/Portfile
R/R-bang/Portfile
R/R-censored/Portfile
R/R-cpfa/Portfile
R/R-cpp11/Portfile
R/R-fplyr/Portfile
R/R-iotools/Portfile
R/R-multilevelmod/Portfile
R/R-poissonreg/Portfile
R/R-rgl/Portfile
R/R-rules/Portfile
R/R-tidyAML/Portfile
R/R-tidyAML/files/patch-no-brulee.diff
R/R-tidyCpp/Portfile

New ports, some updates, a fix to `R-rgl` on Sonoma.
macOS 14.1.2
Xcode 15.0.1
Have you

R: some new packages, few updates

---

lang/ecl/Portfile

ecl-devel: update to 20231122; ecl*: keep used compiler

---

sysutils/tldr-cpp-client/Portfile
sysutils/tldr-cpp-client/files/patch-Makefile.diff

tldr-cpp-client: re-add worksrcdir to fix builds

---

lang/clang-11-bootstrap/Portfile

Closes: https://trac.macports.org/ticket/68789
Have you

clang-11-bootstrap: prefer configure.build_arch over build_arch, use universal_possible

---

python/py-mgwr/Portfile
python/py-momepy/Portfile

- Update `py*-momepy` to version 0.7.0 (but pin 0.6.0 to Python 3.9)
- Update `py*-mgwr` to version 2.2.0
macOS x.y
Have you

py-mgwr, py-momepy: updates

---

sysutils/coreutils-uutils/Portfile

coreutils-uutils: update to 0.0.23

---

science/memesuite/Portfile

memesuite: update to 5.5.5
macOS 12.7.1
Xcode 14.2 / Command Line Tools 14.2.0.0.1.1668646533
Have you
- [x ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
- [ x] squashed and [minimized your commits](https://guide.macports.org/#project.github)?
- [ x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?
- [ x] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL? 
- [x ] checked your Portfile with `port lint --nitpick`?

meme: Update to 5.5.5

---

lang/cabal/Portfile

cabal: Update to version 3.10.2.0

---

gis/proj9/Portfile

Update `proj9` to version 9.3.1.
Have you

proj9: update to version 9.3.1

---

R/R-DT/Portfile
R/R-RcppCGAL/Portfile
R/R-RcppSimdJson/Portfile
R/R-Rmpfr/Portfile
R/R-Rnanoflann/Portfile
R/R-bbmle/Portfile
R/R-factorstochvol/Portfile
R/R-fourierin/Portfile
R/R-git2r/Portfile
R/R-hpa/Portfile
R/R-ichimoku/Portfile
R/R-ldt/Portfile
R/R-lpridge/Portfile
R/R-mirai/Portfile
R/R-mnorm/Portfile
R/R-mvtnorm/Portfile
R/R-party/Portfile
R/R-png/Portfile
R/R-r2sundials/Portfile
R/R-rmumps/Portfile
R/R-rzmq/Portfile
R/R-sass/Portfile
R/R-sna/Portfile
R/R-sodium/Portfile
R/R-stochvol/Portfile
R/R-tiff/Portfile
R/R-tmvtnorm/Portfile
R/R-unix/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (II)

---

net/wireshark4/Portfile

wireshark4: update to 4.2.0

---

devel/rapidjson-devel/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

rapidjson-devel: update to 20231206

---

devel/got/Portfile

got: update to 0.95

---

security/bitwarden-cli/Portfile

bitwarden-cli: update to 2023.12.0

---

R/R-MSCMT/Portfile
R/R-RJSONIO/Portfile
R/R-RcppArmadillo/Portfile
R/R-RcppInt64/Portfile
R/R-cccp/Portfile
R/R-checkmate/Portfile
R/R-expm/Portfile
R/R-fastICA/Portfile
R/R-fastmatrix/Portfile
R/R-gRain/Portfile
R/R-gRbase/Portfile
R/R-gam/Portfile
R/R-glmmrBase/Portfile
R/R-haven/Portfile
R/R-isotree/Portfile
R/R-jqr/Portfile
R/R-jqr/files/patch-fix-configure.diff
R/R-lcopula/Portfile
R/R-lokern/Portfile
R/R-nleqslv/Portfile
R/R-outliertree/Portfile
R/R-qs/Portfile
R/R-redux/Portfile
R/R-round/Portfile
R/R-stringi/Portfile
R/R-stringr/Portfile
R/R-tseries/Portfile
R/R-vctrs/Portfile
R/R-vroom/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (III)

---

R/R-LambertW/Portfile
R/R-RcppCWB/Portfile
R/R-RcppEnsmallen/Portfile
R/R-RcppQuantuccia/Portfile
R/R-WienR/Portfile
R/R-XML/Portfile
R/R-declared/Portfile
R/R-dotCall64/Portfile
R/R-eha/Portfile
R/R-extraDistr/Portfile
R/R-gRc/Portfile
R/R-gpboost/Portfile
R/R-lolog/Portfile
R/R-msm/Portfile
R/R-multicool/Portfile
R/R-pcaPP/Portfile
R/R-qlcal/Portfile
R/R-re2/Portfile
R/R-refund/Portfile
R/R-rlecuyer/Portfile
R/R-rstpm2/Portfile
R/R-scales/Portfile
R/R-segmented/Portfile
R/R-seriation/Portfile
R/R-splus2R/Portfile
R/R-svglite/Portfile
R/R-testthat/Portfile
R/R-xml2/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (IV)

---

sysutils/colima/Portfile

colima: Update to 0.6.7

---

R/R-BTdecayLasso/Portfile
R/R-CovRegRF/Portfile
R/R-QuickJSR/Portfile
R/R-QuickJSR/files/patch-legacy.diff
R/R-QuickJSR/files/patch-libatomic.diff
R/R-RMySQL/Portfile
R/R-RQuantLib/Portfile
R/R-RTMB/Portfile
R/R-RcppSpdlog/Portfile
R/R-TMB/Portfile
R/R-WeightSVM/Portfile
R/R-dbarts/Portfile
R/R-dplR/Portfile
R/R-echoice2/Portfile
R/R-foreign/Portfile
R/R-fstcore/Portfile
R/R-huxtable/Portfile
R/R-markovmix/Portfile
R/R-mev/Portfile
R/R-mongolite/Portfile
R/R-ore/Portfile
R/R-pomp/Portfile
R/R-rBDAT/Portfile
R/R-randomForestSRC/Portfile
R/R-robust/Portfile
R/R-robustbase/Portfile
R/R-rtables/Portfile
R/R-seqinr/Portfile
R/R-stan4bart/Portfile

Almost done :) 
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (VII)

---

R/R-BAS/Portfile
R/R-BGVAR/Portfile
R/R-BayesFactor/Portfile
R/R-BayesMallows/Portfile
R/R-ClusterR/Portfile
R/R-FD/Portfile
R/R-PMCMRplus/Portfile
R/R-RcppAlgos/Portfile
R/R-Rtsne/Portfile
R/R-Rvcg/Portfile
R/R-ast2ast/Portfile
R/R-av/Portfile
R/R-bnlearn/Portfile
R/R-bvhar/Portfile
R/R-distances/Portfile
R/R-dqrng/Portfile
R/R-fixest/Portfile
R/R-influential/Portfile
R/R-ipaddress/Portfile
R/R-lefko3/Portfile
R/R-qtl/Portfile
R/R-rjags/Portfile
R/R-rotasym/Portfile
R/R-rrum/Portfile
R/R-signal/Portfile
R/R-simcdm/Portfile
R/R-sphunif/Portfile
R/R-symengine/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (VI)

---

archivers/advancecomp/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

advancecomp: update to 2.6

---

R/R-igraph/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

R-igraph: update to 1.6.0

---

ruby/ruby-build/Portfile

ruby-build: Update to 20231211

---

math/stanc3/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

stanc3: update to 2023.12.08

---

devel/mk-configure/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

mk-configure: update to 0.38.3

---

R/R-BayesPPD/Portfile
R/R-BayesSUR/Portfile
R/R-BiocFileCache/Portfile
R/R-Cairo/Portfile
R/R-DescTools/Portfile
R/R-DescTools/files/patch-no-RDCOMClient.diff
R/R-JointFPM/Portfile
R/R-OpenMx/Portfile
R/R-PMCMRplus/Portfile
R/R-PeakSegDisk/Portfile
R/R-RGMM/Portfile
R/R-RMVL/Portfile
R/R-bsvars/Portfile
R/R-crqa/Portfile
R/R-descr/Portfile
R/R-diptest/Portfile
R/R-fastcpd/Portfile
R/R-ggdist/Portfile
R/R-gtools/Portfile
R/R-hibayes/Portfile
R/R-matrixStats/Portfile
R/R-monomvn/Portfile
R/R-nftbart/Portfile
R/R-revdbayes/Portfile
R/R-rexpokit/Portfile
R/R-rust/Portfile
R/R-stringi/Portfile
R/R-tikzDevice/Portfile
R/R-yaml/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (3)

---

lang/py-htmldocs/Portfile

py311-htmldocs: 3.11.7

---

lang/logtalk/Portfile

logtalk: update to 3.73.0

---

python/py-python-json-logger/Portfile

Required for a later Jupyter upgrade
Have you

py-python-json-logger: added new port

---

ocaml/ocaml-xmlm/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-xmlm: update to 1.4.0

---

R/R-RBE3/Portfile
R/R-RSSL/Portfile
R/R-Rmpi/Portfile
R/R-RobStatTM/Portfile
R/R-bindrcpp/Portfile
R/R-comat/Portfile
R/R-datefixR/Portfile
R/R-dbx/Portfile
R/R-float/Portfile
R/R-interp/Portfile
R/R-lightgbm/Portfile
R/R-lightgbm/files/patch-unbreak-ppc.diff
R/R-memisc/Portfile
R/R-mets/Portfile
R/R-ncdf4/Portfile
R/R-nseval/Portfile
R/R-oeli/Portfile
R/R-pbdMPI/Portfile
R/R-rbmi/Portfile
R/R-s2/Portfile
R/R-simex/Portfile
R/R-svd/Portfile
R/R-tesseract/Portfile
R/R-tesseract/files/patch-cxx11.diff
R/R-tpn/Portfile
R/R-xgboost/Portfile
R/R-yulab.utils/Portfile

With this, I have only left a handful of R ports which should be switched to newer Proj and their dependents to be updated :)
macOS 10.6
Xcode 3.2
Have you

R: updates to packages (4)

---

R/R-tiledb/Portfile
databases/tiledb/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

tiledb: update to 2.18.2; R-tiledb: update to 0.22.0

---

devel/gFTL/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

gFTL: update to 1.11.0

---

devel/starpu/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

starpu: update to 1.4.2

---

python/py-bitarray/Portfile

macOS 14.1.2 23B92 arm64
Have you

py-bitarray: update to 2.8.5, add py312 subport

---

ocaml/ocaml-shell/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

ocaml-shell: new port

---

archivers/draco/Portfile
graphics/tinygltf/Portfile

Update `tinygltf` to version 2.8.19.
Have you

tinygltf: update to version 2.8.19

---

R/R-BGVAR/Portfile
R/R-NetMix/Portfile
R/R-extraoperators/Portfile
R/R-klaR/Portfile
R/R-recipes/Portfile

Remaining few updates.
macOS 10.6
Xcode 3.2
Have you

R: a few updates to packages

---

math/superlu_dist/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

superlu_dist: update to 8.2.1

---

python/py-tornado/Portfile

py-tornado: upgrade to version 6.4, add py312

---

R/R-symengine/Portfile
math/symengine/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

symengine: update to 0.11.2

---

python/py-terminado/Portfile

py-terminado: upgrade to version 1.18.0, add py312

---

math/strumpack/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

strumpack: update to 7.2.0

---

math/psblas3/Portfile

Update; ensure desired BLAS is picked and not a random one.
macOS 10.6
Xcode 3.2
Have you

psblas3: update to 3.8.1-2

---

math/NTPoly/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

NTPoly: update to 3.1.0

---

math/radian/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

radian: update to 0.6.9

---

net/oci-cli/Portfile

This Port is the Oracle Cloud Infrastructure CLI, utilizing the SDK Port py-oci.
The Port is Python version-limited to 3.9 as this is the latest (as of commit date) Python version officially supported by Oracle for the OCI Python SDK.
Have you

oci-cli: submission

---

python/py-oci/Portfile

This PR updates the `py-oci` package to version `2.118.0`
Have you

py-oci: update to 2.118.0

---

python/py-applescript/Portfile
python/py-asn1-modules/Portfile
python/py-asn1/Portfile
python/py-astroid/Portfile
python/py-blinker/Portfile
python/py-flask/Portfile
python/py-flask/files/disable-failing-tests.diff
python/py-gpsoauth/Portfile
python/py-httpcore/Portfile
python/py-httpx/Portfile
python/py-httpx/files/py312-httpx
python/py-hypothesis/Portfile
python/py-inflate64/Portfile
python/py-lazy_object_proxy/Portfile
python/py-openssl/Portfile
python/py-osxmetadata/Portfile
python/py-pathvalidate/Portfile
python/py-photoscript/Portfile
python/py-pyannotate/Portfile
python/py-pybcj/Portfile
python/py-pycryptodome/Portfile
python/py-pycryptodomex/Portfile
python/py-pylint/Portfile
python/py-pylint/files/pylint312
python/py-pytest-trio/Portfile
python/py-service_identity/Portfile
python/py-trio/Portfile
python/py-trustme/Portfile
python/py-wrapt/Portfile

Here the next bulk from my local branch where I've updated all python ports which I'm care of and added to whem and dependencies py312 subports.
Have you

Update some python ports and add py312 subport

---

science/elmerfem/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

elmerfem: update to 2023.12.13

---

ocaml/ocaml-yojson/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-yojson: update to 2.1.2

---

science/DMFTtools/Portfile
science/scifor/Portfile

Also support MPI for both.
macOS 10.6
Xcode 3.2
Have you

scifor: ensure correct BLAS is used; DMFTtools: update to 2.6.5

---

science/lal/Portfile
science/lalapps/Portfile
science/lalburst/Portfile
science/lalframe/Portfile
science/lalinference/Portfile
science/lalinspiral/Portfile
science/lalmetaio/Portfile
science/lalpulsar/Portfile
science/lalsimulation/Portfile

I don't have time to maintain these ports, unfortunately. Most macOS users of the lal* packages are installing them using conda or pip these days. MacPorts packages might still be useful if they were kept up to date.
macOS x.y
Have you

lal*: abandon ports

---

net/rs-aggregate/Portfile

macOS 14.1.2 23B92 x86_64
Have you

net/rs-aggregate: submission (new Portfile)

---

math/blis/Portfile
math/flexiblas/Portfile

Fix installation of `blis`, support it in `flexiblas`.
macOS 10.6
Xcode 3.2
Have you

blis: fix installation; flexiblas: support blis

---

python/py-nest_asyncio/Portfile

py-nest_asyncio: upgrade to version 1.5.8, add py312

---

sysutils/fontmatrix/Portfile
sysutils/fontmatrix/files/0001-CMakeLists-do-not-force-i386.patch

New port
macOS 14.1.1
Xcode 15.0.1
macOS 10.6.8
Xcode 3.2.6
Have you

fontmatrix: new port in sysutils

---

gis/proj6/Portfile
gis/proj6/files/patch-add-missing-includes.diff
gis/proj7/Portfile
gis/proj7/files/patch-add-missing-includes.diff
gis/proj8/Portfile
gis/proj8/files/patch-add-missing-includes.diff

Fixes: https://trac.macports.org/ticket/68889
Also fixes native variants for powerpc.
macOS 10.6
Xcode 3.2
Have you

proj6–8: fix build with gcc13

---

multimedia/mpv/Portfile
multimedia/mpv/files/config-maintainer

mpv: update to 0.37.0, use meson build system

---

math/hpddm/Portfile

hpddm: update to 2.2.5

---

math/asl/Portfile

asl: update to 20231117

---

devel/libatomic_ops/Portfile

libatomic_ops: update to 7.8.2

---

sysutils/lima/Portfile

lima: upgrade to 0.19.1

---

net/openssh/Portfile

macOS 14.3 23D5033f arm64
Have you

openssh: update to 9.6p1

---

devel/qtermwidget/Portfile
devel/qtermwidget/files/patch-qt4-plugins-path.diff
sysutils/qterminal/Portfile
sysutils/qterminal/files/patch-0.6.0-config.h.diff
sysutils/qterminal/files/patch-0.6.0-fix-icns-path.diff

Update, support old systems.
macOS 14.2
Xcode 15.1
macOS 10.6
Xcode 3.2
Have you

qtermwidget, qterminal: update to 1.4.0; provide Qt4-based fallback version for old systems

---

net/scdl/Portfile
python/py-asn1crypto/Portfile
python/py-backports.zoneinfo/Portfile
python/py-clint/Portfile
python/py-dacite/Portfile
python/py-hypothesis/Portfile
python/py-ifaddr/Portfile
python/py-jellyfish/Portfile
python/py-mutagen/Portfile
python/py-ptpython/Portfile
python/py-ptpython/files/py312-ptpython
python/py-pytest-dotenv/Portfile
python/py-python-dotenv/Portfile
python/py-pytzdata/Portfile
python/py-pytzdata/files/use-poetry-core.patch
python/py-qrcode/Portfile
python/py-requests-mock/Portfile
python/py-sh/Portfile
python/py-soco/Portfile
python/py-soundcloud-v2/Portfile
python/py-termcolor/Portfile
python/py-tzlocal/Portfile
python/py-xdg-base-dirs/Portfile
python/py-xdg/Portfile
python/py-xmltodict/Portfile
python/py-zopfli/Portfile

Here I update some of python ports which I'm care of; non mine ports gets `py312` sunports and I've added a few new ports whcich requries by dependencies or by future update of `john-jumbo-devel`.
Have you

Update some of python ports

---

python/py-certomancer-csc-dummy/Portfile
python/py-certomancer/Portfile
python/py-hanko-certvalidator/Portfile
python/py-hanko/Portfile
python/py-oscrypto/Portfile
python/py-python-pae/Portfile
python/py-uritools/Portfile

Final PR at updating some python ports

---

math/papilo/Portfile
math/polymake/Portfile
math/scip/Portfile

scip: update to 8.1.0

---

lang/mlton/Portfile

Update
macOS 14.2
Xcode 15.1
macOS 10A190
Xcode 3.2
Have you

mlton: update to 20231123

---

www/adblock2privoxy/Portfile
www/adblock2privoxy/files/openssl.cnf

macOS 14.1.1 23B81 arm64
Have you

adblock2privoxy: Update to version 2.1.1; Add proxy_settings variant

---

sysutils/john/Portfile

john-jumbo-devel: update to 20231220; john-jumbo*: works with py-scapy-devel

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff
python/py-awscrt/Portfile

py-awscli2: update to 2.15.3

---

gis/gdal/Portfile
python/py-gdal/Portfile

Update `gdal` and `py-gdal` to version 3.8.2.
Have you

gdal, py-gdal: update to version 3.8.2

---

devel/retdec/Portfile

retdec-devel: update to 20230920

---

python/py-bitarray/Portfile

py-bitarray: update to 2.9.0

---

devel/qbs/Portfile

macOS 14.2 23C64 x86_64
Have you

qbs: Update to 2.2.1

---

net/rpki-client/Portfile

macOS 14.3 23D5033f arm64
Have you

rpki-client update to 8.7

---

mail/rspamd/Portfile
mail/rspamd/files/patch-BackwardConfig_cmake.diff

rspamd: Update to version 3.7.5

---

gis/saga/Portfile

Update `saga` to version 9.2.1 and remove unnecessary mpi PG as well as obsolete postgresql10-11 variants.
Have you

saga: update to version 9.2.1

---

math/fxt/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fxt: update to 2023.12.18

---

devel/wolfssl/Portfile

wolfssl: update to version 5.6.6

---

devel/flamegraph/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

flamegraph: update to 2023.11.07

---

devel/aeson-pretty/Portfile

aeson-pretty: Update to version 0.8.10

---

devel/mz-cmaketools/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

mz-cmaketools: new port in devel

---

games/fheroes2/Portfile

fheroes2: update to 1.0.11

---

audio/opensmile/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

opensmile: update to 3.0.2

---

net/jreen/Portfile

New port
macOS 14.2
Xcode 15.1
macOS 10A190
Xcode 3.2
Have you

jreen: new port in net

---

net/macos-fortress/Portfile

macOS 14.1.1 23B81 arm64
Have you

macos-fortress: Update to version 2023.12.11; add proxy_settings variant

---

science/proxmark3-iceman/Portfile

This PR updates `proxmark3-iceman` to v4.17511.
The CI builds will fail due to timeouts and https://trac.macports.org/ticket/67737.
Have you

proxmark3-iceman: update to 4.17511

---

math/libKriging/Portfile
math/libKriging/files/patch-CMakeLists.diff

Update
macOS 10.6
Xcode 3.2
Have you

libKriging: update to 0.8.3

---

python/py-m2crypto/Portfile

Closes: https://trac.macports.org/ticket/66337
Have you

py-m2crypto: update to 0.40.1

---

python/py-asn1/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

py-asn1: update to 0.5.1

---

science/giza/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

giza: update to 1.4.1

---

gnome/gnome-voice/Portfile

Update gnome-voice 6.0.0 from https://www.gnomevoice.org/src/gnome-voice-6.0.0.tar.xz
macOS 14.1.2 23B92 arm64
Have you

gnome-voice: update to 6.0.0

---

gnome/gnome-voice/Portfile

macOS 14.1.2 23B92 arm64
Have you

gnome-voice: update app.name to Voice

---

math/ensmallen/Portfile

Update, add supports for testing. Add myself as a co-maintainer.
macOS 10A190
Xcode 3.2
macOS 14.2.1
Xcode 15.1
Have you

ensmallen: update to 2.21.0, support tests, add myself as co-maintainer

---

mail/notmuch/Portfile

notmuch: update to 0.38.2

---

multimedia/QMPlay2/Portfile
multimedia/QMPlay2/files/0001-macOS-unbreak-build-with-Qt4.patch
multimedia/QMPlay2/files/0002-MainWidget-fix-for-missing-qt_mac_set_dock_menu.patch
multimedia/QMPlay2/files/0003-ScreenSaver-fix-IOKit-defines.patch
multimedia/QMPlay2/files/0004-PlayClass-do-not-use-QRawFont.patch
multimedia/QMPlay2/files/0005-Revert-some-broken-code.patch
multimedia/QMPlay2/files/0006-FFMpeg-fix-compatibility-with-modern-FFMpeg.patch
multimedia/QMPlay2/files/0007-Fix-Qt-paths.patch
multimedia/QMPlay2/files/2001-Fix-Qt-paths.patch

Let’s see if this builds :) 
UPD. _Yay, it does._
I actually got it to work on PowerPC – not just building, but with video playback working.
macOS 14.2.1
Xcode 15.1
macOS 10A190
Xcode 3.2
Have you

QMPlay2: new port in multimedia, Qt-based player

---

aqua/qt5/Portfile
aqua/qt5/files/CVE-2023-51714-qtbase-5.15.diff
aqua/qt5/files/mysql-plugin-qtbug-109832.patch
python/py-pyside2/Portfile

Apply recent security patches
https://github.com/qt/qtreleasenotes/blob/dev/qt/5.15.12/release-note.md
macOS 12.7.1
Xcode 14.2
Have you

qt5, py-pyside2: update to 5.15.12

---

security/bitwarden-cli/Portfile

macOS 14.0 23A339 arm64
Have you

bitwarden-cli: Update to version 2023.12.1

---

lang/fortran-stdlib/Portfile

Just an update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib: update to 2023.12.26

---

R/R-BTtest/Portfile
R/R-BiocNeighbors/Portfile
R/R-DeBoinR/Portfile
R/R-FBMS/Portfile
R/R-HEtools/Portfile
R/R-MeSHDbi/Portfile
R/R-Mhorseshoe/Portfile
R/R-NPP/Portfile
R/R-PUlasso/Portfile
R/R-PoissonMultinomial/Portfile
R/R-RSQLite/Portfile
R/R-RSclient/Portfile
R/R-Unicode/Portfile
R/R-agop/Portfile
R/R-bayescount/Portfile
R/R-constrainedKriging/Portfile
R/R-finity/Portfile
R/R-gslnls/Portfile
R/R-npsf/Portfile
R/R-pexm/Portfile
R/R-pexm/files/patch-cxx11.diff
R/R-plugdensity/Portfile
R/R-rmgarch/Portfile
R/R-semidist/Portfile
R/R-sglasso/Portfile
R/R-spBayes/Portfile
R/R-spatialCovariance/Portfile
R/R-tibble/Portfile
R/R-tinythemes/Portfile
R/R-tsfknn/Portfile

New ports and a few updates.
macOS 10.6
Xcode 3.2
Have you

R: some new packages and a few updates

---

net/rpki-client/Portfile

macOS 14.3 23D5033f arm64
Have you

rpki-client: update to 8.8

---

aqua/gimp2-launcher/Portfile
aqua/gimp2-launcher/files/patch-Info.plist.diff
graphics/gimp/Portfile
graphics/gimp2/Portfile

gimp2: update to 2.10.36

---

editors/neovim/Portfile

Updated neovim from 0.9.4 to 0.9.5
Have you

neovim: update to 0.9.5

---

devel/jreleaser/Portfile

jreleaser: update to version v1.10.0

---

sysutils/podman/Portfile
sysutils/podman/files/patch-defaultHelperBinariesDir-for-MacPorts.diff
sysutils/podman/files/patch-getEdk2CodeFd-for-MacPorts.diff

podman: update to 4.8.2; add myself as co-maintainer

---

sysutils/initool/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

initool: update to 0.14.1

---

java/mvnd/Portfile

Fix the download location for mvnd.

mvnd: fix download location

---

graphics/gscan2pdf/Portfile

gscan2pdf: add missing dependency to p5-data-uuid

---

python/py-pygraphviz/Portfile

* update to version 1.11
* set supported python versions to 3.10, 3.11, and 3.12 (as specified upstream)
Have you

py-pygraphviz: update to version 1.11

---

devel/astyle/Portfile

astyle: update to 3.4.10

---

science/verilator/Portfile

Updated verilator from 5.018 to 5.020
Have you

Updated verilator from 5.018 to 5.020

---

databases/barman/Portfile

barman: use python312

---

python/py-postgresql/Portfile

Drop python 3.7, use newer ones.
macOS 10.6
Xcode 3.2
Have you

py-postgresql: update to 1.3.0

---

tex/EqualX/Portfile
tex/EqualX/files/patch-DialogPreferences.cpp.diff
tex/EqualX/files/patch-MainWindow.cpp.diff
tex/EqualX/files/patch-defines.h.diff
tex/EqualX/files/patch-equalx.pro.diff

New port: https://equalx.sourceforge.io
macOS 14.2.1
Xcode 15.1
macOS 10.6
Xcode 3.2
Have you

EqualX: new port in tex

---

sysutils/chrony/Portfile

macOS 14.3 23D5043d arm64
Have you

chrony: update to 4.5

---

lua/lua-psl/Portfile
net/knot-resolver/Portfile
net/knot-resolver/files/respect-rundir.diff

knot-resolver: add missed dependency; lau-psl: new port (version 0.3)
