macports/macports-ports

gis/pdal/Portfile
python/py-pdal/Portfile

Update `pdal` to 2.6.2 and `py-pdal` to 3.3.0. Drop py37 and add py312 support for `py-pdal`.
macOS x.y
Have you

pdal: update to 2.6.2; py-pdal: update to 3.3.0

---

sysutils/clamav-server/Portfile
sysutils/clamav-server/files/patch-etc-clamd-conf-macports.diff
sysutils/clamav-server/files/patch-etc-freshclam-conf-macports.diff

clamav-server: Update to clamd version 1.2.1; Add proxy_settings variant

---

lang/sbcl/Portfile
math/fricas/Portfile
math/maxima/Portfile

sbcl: update to 2.4.0; sbcl-devel: update to 20240106

---

textproc/trdsql/Portfile

trdsql: update to 0.20.0

---

mail/offlineimap/Portfile
net/openntpd/Portfile

Closes: https://trac.macports.org/ticket/69054
Have you

*: use a path-style dependency on curl-ca-bundle

---

devel/jenkins/Portfile

jenkins: update to 2.426.2

---

databases/metabase/Portfile

metabase: update to 0.48.2

---

python/pipenv/Portfile

pipenv: update to 2023.11.15

---

net/dnscrypt-proxy/Portfile

dnscrypt-proxy: update to 2.1.5

---

textproc/po4a/Portfile

po4a: update to 0.69

---

math/fricas/Portfile

fricas: update to version 3.10

---

multimedia/bento4/Portfile

bento4: update to 1.6.0-641

---

www/cpprestsdk/Portfile

cpprestsdk: update to 2.10.19

---

lang/odin/Portfile
lang/odin/files/patch-build.diff
lang/odin/files/patch-raylib.diff

odin: update to 0.2024.01

---

python/py-tiktoken/Portfile
python/py-tiktoken/files/test_misc.diff
python/py-tiktoken/files/test_simple_public.diff

py*-tiktoken: new port

---

graphics/Aseprite/Portfile
graphics/Aseprite/files/DEPS.patch
graphics/Aseprite/files/USE_SHARED_LIBARCHIVE.patch
graphics/Aseprite/files/USE_SHARED_LIBWEBP.patch
graphics/Aseprite/files/git-sync-deps.patch

Closes: https://trac.macports.org/ticket/66140
macOS 12.7.2 21G1974 x86_64

Aseprite: Update to 1.3.2

---

net/snac/Portfile

macOS 14.3 23D5051b arm64
Have you

snac: update to 2.44

---

net/macos-fortress/Portfile
net/macos-fortress/files/privoxy-config.macports
net/macos-fortress/files/privoxy-config.patch

macos-fortress: Bugfix, typo

---

devel/dispenso/Portfile
devel/dispenso/files/0001-platform.h-add-cpuRelax-for-PowerPC-and-ARM.patch
devel/dispenso/files/0002-no-werror.patch

New port: https://github.com/facebookincubator/dispenso
macOS 14.2.1
Xcode 15.2
macOS 10.6
Xcode 3.2
Have you

dispenso: new port in devel

---

python/py-spopt/Portfile

py-spopt: update to 0.6.0

---

graphics/wgshadertoy/Portfile

macOS 10.14.5 18F203 x86_64
Have you

wgshadertoy: update to 0.3.3

---

devel/fpm/Portfile
devel/fpm/files/patch-install.diff

Update
macOS 14.2.1
Xcode 15.2
macOS 10.6
Xcode 3.2
Have you

fpm: update to 0.10.0

---

gis/pgrouting/Portfile
gis/rsgislib/Portfile
gis/sfcgal/Portfile
python/py-mgwr/Portfile

Updates:
-  `py-mgwr` to version 2.2.1.
-  `rsgislib`, `py-rsgislib` to version 5.1.0 and adds py312 subport.
-  `sfcgal` to version 1.5.1.
-  `pgrouting` to version 3.6.1.
Have you

py-mgwr, rsgislib, sfcgal, pgrouting: updates

---

python/py-zmq/Portfile

py-zmq: upgrade to version 25.1.2, add py312

---

math/dbcsr/Portfile

The port has been broken for quite a while. Finally update it so that it builds.
macOS 14.2.1
Xcode 15.2
macOS 10.6
Xcode 3.2
Have you

dbcsr: update to 2.6.0, fix the port

---

devel/libfilezilla/Portfile
devel/libfilezilla/files/patch-gcc7.diff
www/FileZilla/Portfile
www/FileZilla/files/patch-cloexec.diff
www/FileZilla/files/patch-dnd.diff
www/FileZilla/files/patch-paths-1050.diff
www/FileZilla/files/patch-powermanagement.diff
www/FileZilla/files/patch-src-commonui-buildinfo.cpp.diff
www/FileZilla/files/patch-src-engine-version.cpp.diff
www/FileZilla/files/patch-src-interface-mainfrm.cpp.diff
www/FileZilla/files/patch-src-interface-toolbar.mm.diff

Update the FileZilla port to version 3.62.2.1 and libfilezilla to 0.41.1.
Have you

filezilla: update to 3.63.2.1

---

www/adblock2privoxy/Portfile

adblock2privoxy: Fix documentation

---

lang/fortran-stdlib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib: update to 2024.01.09

---

graphics/feh/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

feh: update to 3.10.2

---

ruby/rb-concurrent-ruby-ext/Portfile
ruby/rb-concurrent-ruby/Portfile

New port: https://github.com/ruby-concurrency/concurrent-ruby
macOS 14.2.1
Xcode 15.2
Have you

rb-concurrent-ruby, rb-concurrent-ruby-ext: new ports in Ruby

---

www/adblock2privoxy/Portfile
www/adblock2privoxy/files/openssl.cnf

adblock2privoxy: Update PKI example

---

www/privoxy/Portfile
www/privoxy/files/openssl.cnf

privoxy: Update PKI documentation, example

---

devel/arduino-cli/Portfile

arduino-cli: update to 0.35.0

---

python/py-beancount/Portfile

pyproject.toml only exists on upstream master, not in 2.3.6.
This partially reverts commit e3c833d38bade42b0c937255eccca4f0a78ae6f1.
Have you

py-beancount: revert pep517 change

---

ruby/rb-rake/Portfile

Update
macOS 14.2.1
Xcode 15.2
Have you

rb-rake: update to 13.1.0

---

ruby/rb-x/Portfile

New port in Ruby: https://github.com/sferik/x-ruby
macOS 14.2.1
Xcode 15.2
Have you

rb-x: new port in Ruby

---

fortran/runge-kutta-fortran/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

runge-kutta-fortran: update to 1.0.2

---

gis/gdal/Portfile
gis/pcraster/Portfile
gis/pcraster/files/patch-configure_python_extension.diff

- Enable built-in 'PCRaster' driver for port `gdal` (and rev-bump to make it effective).
- New port `pcraster` version 4.4.1  for [PCRaster](https://pcraster.geo.uu.nl).
Have you

gdal: enable PCRaster driver; pcraster: new port version 4.4.1

---

python/fava/Portfile
python/py-beancount/Portfile
python/py-bottle/Portfile
python/py-cheroot/Portfile
python/py-flask-babel/Portfile
python/py-google-api-core/Portfile
python/py-google-api/Portfile
python/py-google-auth-httplib2/Portfile
python/py-google-auth/Portfile
python/py-googleapis-common-protos/Portfile
python/py-httplib2/Portfile
python/py-magic/Portfile
python/py-markdown2/Portfile
python/py-protobuf3/Portfile
python/py-uritemplate/Portfile

The py311-markdown2 tests fail, but they also fail for py310-markdown2 in the same way, so this does not look like a regression in this change.
fava itself has tests, but I could not get them working after some fiddling, so I gave up. The program itself works on my test case (my personal finances.)
Have you

fava: update to 1.27, use py312

---

ruby/rb-citrus/Portfile
ruby/rb-toml-rb/Portfile

New ports in Ruby
macOS 14.2.1
Xcode 15.2
Have you

rb-citrus, rb-toml-rb: new ports in Ruby

---

ruby/rb-addressable/Portfile
ruby/rb-public_suffix/Portfile

New ports in ruby.
macOS 14.2.1
Xcode 15.2
Have you

rb-addressable, rb-public_suffix: new ports in Ruby

---

python/py-jwt/Portfile
python/py-oauthlib/Portfile
python/py-pygithub/Portfile
python/py-requests-oauthlib/Portfile
python/py-tweepy/Portfile
python/py-twilio/Portfile
python/py-twython/Portfile

py-requests.oauthlib (and dependencies): add py312 subports, remove py37 subports

---

databases/pgbadger/Portfile

pgbadger: update to 12.4

---

python/py-awscli2/Portfile

py-awscli2: update to 2.15.10

---

python/py-svgelements/Portfile

py-svgelements: update to 1.9.6, add py312 subport

---

python/py-zipfile-deflate64/Portfile

py-zipfile-deflate64: add py312 subport

---

archivers/cpio/Portfile

cpio: update to 2.15

---

ruby/rb-buftok/Portfile
ruby/rb-domain_name/Portfile
ruby/rb-equalizer/Portfile
ruby/rb-http-cookie/Portfile
ruby/rb-memoizable/Portfile
ruby/rb-multipart-post/Portfile
ruby/rb-naught/Portfile
ruby/rb-thread_safe/Portfile

This PR does not touch any existing ones, so it is safe.
macOS 14.2.1
Xcode 15.2
(These are trivial ports, so I will not specifically test them on PowerPC.)
Have you

Ruby: a few new ports

---

devel/libcryptopp/Portfile

Update
macOS 14.2.1
Xcode 15.2
macOS 10.6
Xcode 3.2
Have you

libcryptopp: update to 8.9.0

---

R/R-CGNM/Portfile
R/R-MCMCpack/Portfile
R/R-antiword/Portfile
R/R-glmmPen/Portfile
R/R-gpboost/Portfile
R/R-lightgbm/Portfile
R/R-psych/Portfile
R/R-rstanarm/Portfile
R/R-rstanarm/files/patch-no-v8.diff
R/R-rworkflows/Portfile
R/R-survstan/Portfile
R/R-svines/Portfile
R/R-tstools/Portfile

Today’s updates
macOS 10.6
Xcode 3.2
Have you

R: update a few exiting packages

---

sysutils/zsh-fpm-completions/Portfile

New port, extra completions for `zsh`: https://github.com/ShinobuAmasaki/fpm-completions
macOS 14.2.1
Xcode 15.2
Have you

zsh-fpm-completions: new port

---

net/snac/Portfile
net/snac/files/Makefile.patch

macOS 14.3 23D56 arm64
Have you

snac: update to 2.45

---

math/radian/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

radian: update to 0.6.10

---

python/py-cbor2/Portfile
python/py-luma.core/Portfile
python/py-luma.emulator/Portfile
python/py-pyftdi/Portfile
python/py-smbus2/Portfile

py-luma.emulator (and dependencies): add py312 subport

---

python/py-geographiclib/Portfile
python/py-geopy/Portfile

py-geographiclib: add py312 subport, remove py37 subport

---

devel/asio/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

asio: update to 1.29.0

---

mail/mail-server/Portfile
mail/mail-server/files/prefix/etc/certificates/ca/openssl.cnf

mail-server: Use appropriate hash for P-384 curves in ECC PKI example

---

lang/MoarVM/Portfile
lang/MoarVM/files/patch-libuv-includes-path.diff
lang/MoarVM/files/patch-libuv-legacy.diff
lang/MoarVM/files/patch-moar.pc.diff
lang/nqp/Portfile
lang/rakudo/Portfile

Updated, finally.
macOS 10.6
Xcode 3.2
Have you

Rakudo and friends: update to 2023.12

---

audio/libsoundio/Portfile
audio/libsoundio/files/0001-os.c-use-NOTE_TRIGGER-conditionally-use-EV_TRIGGER.patch

I also make minor non-functional changes to portfile in a separate commit.
macOS 10.6
Xcode 3.2
Have you

libsoundio: support testing; patch for older systems

---

python/py-annotated_types/Portfile
python/py-pydantic/Portfile
python/py-pydantic_core/Portfile
python/py-pydantic_settings/Portfile

Depends upon  #22104 or #21985.
Have you

py-pydantic: Update to version 2.5.3; Remove py37

---

net/get_iplayer/Portfile

get_iplayer: update to 3.35

---

graphics/inkscape-textext/Portfile

* update to version 1.10.1
* increment python version for dependency to py311
Have you

inkscape-textext: update to version 1.10.1

---

lang/MoarVM/Portfile

@reneeotten Please review.
macOS x.y
Have you

MoarVM: minor fixup to portfile following the update

---

devel/jujutsu/Portfile

Update jujutsu to 0.13.0
Have you

jujutsu: update to 0.13.0

---

multimedia/kvazaar/Portfile

kvazaar: update to 2.3.0

---

fortran/fortran-lapack/Portfile

New port
macOS 14.2.1
Xcode 15.2
macOS 10.6
Xcode 3.2
Have you

fortran-lapack: new port

---

sysutils/fq/Portfile

fq: mark nq port as conflict

---

archivers/draco/Portfile

Update `draco` to version 1.5.7.
Have you

draco: update to version 1.5.7

---

net/vnstat/Portfile

vnstat: update to 2.12

---

python/py-giddy/Portfile

Update `py*-giddy` to version 2.3.5.
macOS x.y
Have you

py-giddy: update to version 2.3.5

---

python/py-affine/Portfile
python/py-click-plugins/Portfile
python/py-cligj/Portfile
python/py-fiona/Portfile
python/py-munch/Portfile
python/py-rasterio/Portfile
python/py-rasterstats/Portfile
python/py-seaborn/Portfile
python/py-snuggs/Portfile

`py-rasterstats`: add Python 3.12 subport
`py-rasterio`: add Python 3.12 subport
`py-snuggs`: add Python 3.12 subport
`py-fiona`: add Python 3.12 subport
`py-munch`: update to 4.0.0; add Python 3.12 subport (pin py37 to version 2.5.0)
`py-click-plugins`: add Python 3.12 subport
`py-cligj`: add Python 3.12 subport
`py-affine`: add Python 3.12 subport
`py-seaborn`: update to 0.13.1; add py312 subport (pin py37 to version 0.12.2.)
Have you

Add py312 subport to various GIS related ports

---

science/shtools/Portfile

Fix home page only.  Skip CI.
Portfile doc only.  Not tested.
Have you

shtools: Fix home page only

---

multimedia/streamlink/Portfile

Closes: https://trac.macports.org/ticket/67645
Have you

streamlink: update to 6.5.1

---

net/oxenc/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

oxenc: update to 1.0.10

---

devel/libt3config/Portfile
devel/libt3highlight/Portfile
devel/libt3key/Portfile
devel/libt3key/files/patch-config.pkg.diff
devel/libt3widget/Portfile
devel/libt3widget/files/patch-menu.cc.diff
devel/libt3window/Portfile
devel/libt3window/files/patch-config.pkg.diff
devel/libtranscript/Portfile
devel/libtranscript/files/patch-config.pkg.diff
editors/tilde/Portfile
editors/tilde/files/patch-Makefile.in.diff

Closes: https://trac.macports.org/ticket/68594
Have you

tilde: new port (version 1.1.3)

---

python/py-annotated_types/Portfile
python/py-pydantic/Portfile
python/py-pydantic_settings/Portfile

py-pydantic, py-pydantic_settings, py-annotated_types: Add supported_archs and platforms to Portfile

---

devel/libt3highlight/Portfile
devel/libt3widget/Portfile
editors/tilde/Portfile

Everything is obvious from commits :) 
With these, it builds fine.
macOS 10.6
Xcode 3.2
Have you

tilde and friends: fix build on < 10.7

---

finance/bitcoin/Portfile

bitcoin: update to 26.0

---

devel/astyle/Portfile

astyle: update to 3.4.11

---

science/xtide/Portfile

xtide: eliminate liner warnings in Portfile

---

math/nanoflann/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nanoflann: update to 1.5.4

---

python/py-telethon/Portfile

py-telethon: Update to version 1.33.1

---

sysutils/osinfo-db/Portfile

osinfo-db: update to 20231215

---

lang/lfortran/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

lfortran: update to 0.31.0

---

math/flexiblas/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

flexiblas: update to 3.4.1

---

fortran/h5fortran/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

h5fortran: update to 4.10.5

---

devel/hscolour/Portfile

hscolour: Update to version 1.25

---

devel/alex/Portfile

alex: Update to version 3.5.0.0

---

R/R-mmrm/Portfile

Follow-up update for this port, looks like upstream had some reason to jump three versions in a couple of days.
macOS 10.6
Xcode 3.2
Have you

R-mmrm: update to 0.3.10

---

graphics/diff-pdf/Portfile

diff-pdf: update to 0.5.2

---

sysutils/zsh-fpm-completions/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

zsh-fpm-completions: update to 0.2

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.1.22

---

sysutils/tmux/Portfile

intergrate -> integrate
Have you

tmux: Typo

---

net/yggdrasil-go/Portfile

macOS 12.7.3 21H1015 x86_64
Have you

yggdrasil-go: update to 0.5.5

---

math/nickle/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nickle: update to 2.97

---

math/gemmlowp/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

gemmlowp: update to 2023.11.03

---

lang/algol68g/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

algol68g: update to 3.4.7

---

devel/sccache/Portfile

sccache: update to 0.7.6

---

R/R-GA/Portfile
R/R-HHG/Portfile
R/R-Tejapi/Portfile
R/R-ZIPLL/Portfile
R/R-bayesWatch/Portfile
R/R-bayesWatch/files/patch-fix-isnan.diff
R/R-bsitar/Portfile
R/R-dslice/Portfile
R/R-dynsurv/Portfile
R/R-eff2/Portfile
R/R-emoa/Portfile
R/R-ess/Portfile
R/R-ezplot/Portfile
R/R-gammSlice/Portfile
R/R-gsbDesign/Portfile
R/R-lorad/Portfile
R/R-mimi/Portfile
R/R-nlraa/Portfile
R/R-ollggamma/Portfile
R/R-rasterize/Portfile
R/R-robustsae/Portfile
R/R-segMGarch/Portfile
R/R-sitar/Portfile
R/R-tsdecomp/Portfile
R/R-tsdisagg2/Portfile
R/R-yulab.utils/Portfile
_resources/port1.0/group/R-1.0.tcl

Fix running tests broken after Macports update to 2.9.0.
Sort out port stages, close related tickets. Now build can be interrupted and resumed without an error.
Add some new ports, so that we have something to build now and verify it actually works :) 
macOS 10.6
Xcode 3.2
macOS 14.3
Xcode 15.2
Have you

R: fix test stage after Macports update to 2.9.0, add some new packages

---

python/py-pyobjc6/Portfile
python/py-pyobjc6/files/patch-docs-conf.py.diff
python/py-pyobjc6/files/patch-install.py.diff

The current version of py-pyobjc is unsupported on old systems. Provide an alternative. Version has been advised by upstream: https://github.com/ronaldoussoren/pyobjc/issues/587
@danchr Could you please take a look?
macOS 10.6
Xcode 3.2
Have you

py-pyobjc6: port for old systems

---

editors/neovim/Portfile

- tree-sitter: Update to 0.20.9
- neovim-devel: Update to 2024-01-26
Have you

neovim-devel: Update to 2024-01-26

---

net/snac/Portfile

macOS 14.4 23E5180j arm64
Have you

snac: update to 2.46

---

R/R-RCLabels/Portfile
R/R-RcppCGAL/Portfile
R/R-adaptMCMC/Portfile
R/R-bqtl/Portfile
R/R-csaw/Portfile
R/R-distr/Portfile
R/R-ggrcs/Portfile
R/R-kyotil/Portfile
R/R-lavaanPlot/Portfile
R/R-lavaanPlot/files/patch-no-DiagrammeRsvg.diff
R/R-mixture/Portfile
R/R-mombf/Portfile
R/R-rankinma/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: remaining few updates for packages

---

devel/symfony-cli/Portfile

symfony-cli: update to 5.8.6

---

sysutils/cdrtools/Portfile

See commits.
macOS 10.6
Xcode 3.2
Have you

cdrtools: unbreak after pulseaudio update, fix universal flags for Leopard on powerpc

---

science/ast/Portfile
science/ast/files/dynamic_lookup-11.patch

Remove merged patch
Closes https://trac.macports.org/ticket/64560
Have you

ast: update to 9.2.10

---

lang/logtalk/Portfile

logtalk: update to 3.74.0

---

gis/saga/Portfile

Update `saga` to version 9.3.1.
macOS x.y
Have you

saga: update to version 9.3.1

---

python/py-spaghetti/Portfile

Update `py-spaghetti` to version 1.7.5.post1; pin 1.7.4 for py39.
macOS x.y
Have you

py-spaghetti: update to 1.7.5.post1; pin 1.7.4 for py39

---

databases/tiledb/Portfile
databases/tiledb/files/patch-2.19.1.diff
databases/tiledb/files/patch-libatomic-32-bit.diff
databases/tiledb/files/patch-random.diff
databases/tiledb/files/patch-unit_capi_error_tree.cc-temporary-fix.diff

Update, fixes.
macOS 10.6
Xcode 3.2
Have you

tiledb: update to 2.19.1, fix building tests variant

---

R/R-igraph/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

R-igraph: update to 2.0.1.1

---

python/py-codecov/Portfile

Add py312 subport to `py-codecov`.
macOS x.y
Have you

py-codecov: add py312

---

python/py-branca/Portfile
python/py-folium/Portfile

Update `py-branca` to version 0.7.1 and add py312 subport.
Update `py-folium` to version 0.15.1 and add py312 subport. Also update port description.
macOS x.y
Have you

py-folium, py-branca: updates and add py312

---

python/py-pytest-env/Portfile

New `py{*}-pytest-env` port, version 1.1.3.
Have you

py-pytest-env: new port, version 1.1.3

---

science/mmg/Portfile
science/mmg/files/0001-libmmg3d_private.h-include-inttypes.h-for-PRId.patch

Update, a minor fix.
macOS 10.6
Xcode 3.2
Have you

mmg: update to 5.7.2

---

science/cgnslib/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

cgnslib: update to 4.4.0

---

python/py-geopandas/Portfile
python/py-llvmlite/Portfile
python/py-numba/Portfile

Update `py-geopanda` to version 0.14.3; update and pin 0.13.2 to py38; drop py37; add py312.
Update `py-numba`  to version  0.59.0; pin 0.58.1 to py38; add py312.
Update `py-llvmlite` to version 0.42.0; pin 0.41.1 to py38; add py312.
macOS x.y
Have you

py-geopanda, py-numba, py-llvmlite: update and add py312

---

python/py-psycopg/Portfile

py-psycopg: update to 3.1.17, add 312

---

python/py-quantecon/Portfile

Add Python 3.12 subport to `py-quantecon` and enable test.
macOS x.y
Have you

py-quantecon: add Python 3.12 subport; enable test

---

sysutils/tmux/Portfile

tmux-devel: update to 20240122-ea7136f
macOS x.y
Have you

tmux: overwrite config dir

---

devel/shards/Portfile

shards: update to 0.17.4

---

science/mpich/Portfile

Fixes https://trac.macports.org/ticket/68346

mpich: remove -commons flag on XC 15

---

gis/rsgislib/Portfile

Update `rsgislib` to version 5.1.1.
macOS x.y
Have you

rsgislib: update to version 5.1.1

---

python/py-invoke/Portfile

py-invoke: update to 2.2.0

---

www/adblock2privoxy/Portfile

It's preferable to merge this against #22398.
macOS x.y
Have you

adblock2privoxy: Update to version 2.2.0

---

devel/haskell-language-server/Portfile
devel/haskell-language-server/files/Paths_NAME.hs

It's preferable to merge this against #22398.
macOS x.y
Have you

haskell-language-server: Submission

---

lang/lpython/Portfile
lang/lpython/files/0001-stacktrace.cpp-include-syslimits.h-for-PATH_MAX.patch
lang/lpython/files/0002-UserOverride.cmake-fix-native-optflag-for-PowerPC.patch
lang/lpython/files/0003-Install-libs-into-a-sane-location.patch
lang/lpython/files/0004-parser_stype.h-allow-building-for-ppc.patch
lang/lpython/files/0005-patch-build0.sh.patch
lang/lpython/files/0006-patch-version.patch

New port
macOS 14.3
Xcode 15.2
macOS 10.6
Xcode 3.2
Have you

lpython: new port in lang

---

graphics/libopenraw-legacy/Portfile

[skip ci]
Skipping CI, nothing to test here.
macOS x.y
Have you

libopenraw-legacy: non-functional: fix homepage

---

R/R-AER/Portfile
R/R-Boom/Portfile
R/R-Boom/files/patch-unbreak-lib.diff
R/R-CVXR/Portfile
R/R-DescTools/Portfile
R/R-DiagrammeR/Portfile
R/R-DiagrammeR/files/patch-no-DiagrammeRsvg.diff
R/R-atime/Portfile
R/R-cobs/Portfile
R/R-cpfa/Portfile
R/R-dbarts/Portfile
R/R-devEMF/Portfile
R/R-dsem/Portfile
R/R-dynamite/Portfile
R/R-expectreg/Portfile
R/R-extRemes/Portfile
R/R-fGarch/Portfile
R/R-fracdiff/Portfile
R/R-gasmodel/Portfile
R/R-geepack/Portfile
R/R-genlogis/Portfile
R/R-gplots/Portfile
R/R-groundhog/Portfile
R/R-hardhat/Portfile
R/R-hstats/Portfile
R/R-intergraph/Portfile
R/R-matsindf/Portfile
R/R-mirai/Portfile
R/R-mlflow/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates for packages (I)

---

net/iwnet/Portfile
net/iwnet/files/0001-Revert-iwn_poller_poll_in_thread-now-waits-poller-th.patch

Update
macOS 10.6
Xcode 3.2
Have you

iwnet: update to 2024.01.27

---

python/py-awscli2/Portfile

macOS 13.6.4 22G513 x86_64
Have you

py-awscli2: update to 2.15.17

---

lang/fortran-stdlib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib: update to 2024.01.17

---

sysutils/coreutils-uutils/Portfile

macOS 13.6.4 22G513 x86_64
Have you

coreutils-uutils: update to 0.0.24

---

net/newsraft/Portfile
sysutils/sfm/Portfile

Missed revision bump:
* https://github.com/macports/macports-ports/pull/22551
* https://github.com/macports/macports-ports/pull/22552
cc @herbygillot 
macOS x.y
Have you

sfm,newsraft: bump revision

---

science/OpenCoarrays/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

OpenCoarrays: update to 2.10.2

---

textproc/msort/Portfile
textproc/msort/files/patch-fix-includes.diff

Fix the build, improve portfile.
macOS 14.3
Xcode 15.2
macOS 10.6
Xcode 3.2
Have you

msort: fix the port

---

net/cgmnlm/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

cgmnlm: update to 1.7

---

games/fheroes2/Portfile

fheroes2: update to 1.0.12

---

sysutils/sshpass/Portfile

Update `sshpass` version to `1.10`
Have you

sshpass: update to 1.10

---

devel/boehmgc/Portfile

macOS 10.13
Xcode 9.4
Have you

boehmgc: update to 8.2.6

---

lang/fpc/Portfile
lang/fpc/files/patch-powerpc.diff

Support PowerPC builds. Fix building for `ppc` on > 10.4.
`powerpc` target (32-bit) confirmed to build on 10.6, 10.5.8 and 10.4.11.
P. S. `ppc64` should work, but does not yet, since something with sources resets CPU_TARGET from `powerpc64` to `powerpc`.
I suggest merging this first. In the next PR I add support for `i386` and fix `ppc64`.
macOS 10.6
Xcode 3.2
macOS 10.5.8
Xcode 3.1.4
macOS 10.4.11
Xcode 2.5
Have you

fpc: add support for PowerPC

---

erlang/atomvm/Portfile

atomvm: update to 0.6.0b0

---

textproc/extractpdfmark/Portfile

extractpdfmark: update to 1.1.1

---

devel/qbs/Portfile

qbs: Update to 2.2.2

---

www/libmicrohttpd/Portfile

* removed unused dependencies
* enabled check
* removed unused configure parameter

libmicrohttpd: update receipt

---

lang/chez-scheme/Portfile

chez-scheme: update to 10.0.0

---

graphics/dcmtk/Portfile
graphics/dcmtk/files/install_path_fix.patch
graphics/dcmtk/files/install_path_fix_part2.patch

dcmtk: Update to 3.6.8

---

fortran/forlab/Portfile
fortran/forlab/files/0001-fpm.toml-add-install-target.patch

New port
macOS 14.3
Xcode 15.2
Have you

forlab: new port in fortran

---

fortran/simulated-annealing/Portfile
fortran/simulated-annealing/files/patch-link-with-openblas.diff

New port
macOS 14.3
Xcode 15.2
Have you

simulated-annealing: new port in fortran

---

www/dokuwiki/Portfile

dokuwiki: update to 2024-02-06a

---

databases/pgcli/Portfile

The only reason this can't use python 312 yet is because of py-sqlparse
Closes: https://trac.macports.org/ticket/69166
Have you

pgcli: update to 4.0.1, use psycopg3, add 311

---

net/snac/Portfile

macOS 14.3 23D56 arm64
Have you

snac: update to 2.47

---

www/roundcubemail/Portfile

roundcubemail: update to 1.6.6, add php83

---

_resources/port1.0/group/haskell_cabal-1.0.tcl
devel/haskell-language-server/Portfile

haskell-language-server, PG haskell_cabal

---

devel/got/Portfile

got: update to 0.96

---

sysutils/yabai/Portfile
sysutils/yabai/files/patch-makefile-macos11.diff
sysutils/yabai/files/patch-makefile.diff

Had some issues with latest (6.0.10), holding off for now -- might be that upstream is already working on it.
macOS 14.1 23B74 x86_64
Have you

yabai: update to version 6.0.10

---

multimedia/youtube-viewer/Portfile
perl/p5-lwp-useragent-cached/Portfile
sysutils/skhd/Portfile
sysutils/yabai/Portfile

As per https://github.com/macports/macports-ports/pull/22646#pullrequestreview-1879276148, fix the casing of my github handle.
macOS x.y
Have you

meta: fix my github handle in maintainer references

---

devel/haskell-stan/Portfile

This must be merged against #22598.
macOS x.y
Have you

haskell-stan: Submission

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.3.1

---

lang/swi-prolog/Portfile

swi-prolog: Updated to version 9.2.1

---

x11/tkdnd/Portfile
x11/tkdnd/files/patch-CMakeLists.txt.diff

macOS 12.7.3
Xcode 14.2
Have you

tkdnd: update to 2.9.4

---

R/R-BVAR/Portfile
R/R-CGP/Portfile
R/R-GDAdata/Portfile
R/R-LTFHPlus/Portfile
R/R-RcppCNPy/Portfile
R/R-baggr/Portfile
R/R-bayesmeta/Portfile
R/R-bayesplot/Portfile
R/R-brms.mmrm/Portfile
R/R-concordancer/Portfile
R/R-cpfa/Portfile
R/R-fasta/Portfile
R/R-heplots/Portfile
R/R-huxtable/Portfile
R/R-idx2r/Portfile
R/R-l2boost/Portfile
R/R-liureg/Portfile
R/R-mlflow/Portfile
R/R-modelbased/Portfile
R/R-nebula/Portfile
R/R-nna/Portfile
R/R-openxlsx2/Portfile
R/R-palasso/Portfile
R/R-plde/Portfile
R/R-probout/Portfile
R/R-see/Portfile
R/R-targets/Portfile
R/R-tgstat/Portfile

Updates and some new ports.
macOS 10.6.8
Xcode 3.2.6
Have you

R: remaining updates and a few new packages

---

math/hypre/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

hypre: update to 2.31.0

---

math/ensmallen/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

ensmallen: update to 2.21.1

---

math/hiop/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

hiop: update to 1.0.3

---

irc/bitchx/Portfile
irc/bitchx/files/patch-expr2.diff

https://build.macports.org/builders/ports-14_x86_64-builder/builds/26873/steps/install-port/logs/stdio
Have you

bitchx: fix build with Clang > 13

---

java/apache-solr8/Portfile

apache-solr8: Update to version 8.11.3

---

R/R-NMA/Portfile
R/R-magick/Portfile
R/R-recipes/Portfile
R/R-setRNG/Portfile
R/R-splus2R/Portfile

macOS 10.6.8
Xcode 3.2.6
Have you

R: a few remaining weekend updates for packages

---

audio/liblo/Portfile
audio/liblo/files/dynamic_lookup-11.patch

Update
macOS 10.6
Xcode 3.2
Have you

liblo: update to 0.32

---

lang/lfortran/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

lfortran: update to 0.33.1

---

math/s2geometry/Portfile
math/s2geometry/files/patch-fix-build.diff

Update
macOS 10.6
Xcode 3.2
Have you

s2geometry: update to 0.11.1

---

math/radian/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

radian: update to 0.6.12

---

devel/rapidjson-devel/Portfile

Update for -devel port.
macOS 10.6
Xcode 3.2
Have you

rapidjson-devel: update to 20240209

---

devel/ihaskell/Portfile

This should be merged against #22722.
macOS x.y
Have you

ihaskell: Update to version 20240218

---

_resources/port1.0/group/haskell_stack-1.0.tcl
lang/stack/Portfile

stack: Update to version 2.15.1

---

R/R-parallelly/Portfile

Needed to fix pre-built package.
macOS x.y
Have you

R-parallelly: not noarch anymore, fix it

---

www/nicotine-plus/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nicotine-plus: update to 3.3.0

---

devel/nng/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nng: update to 1.7.2

---

lang/mercury/Portfile
lang/mercury/files/patch-no-werror.diff

Let’s see if this one builds.
macOS 14.3.1 aarch64
Xcode 15.2
macOS 10.6 ppc
Xcode 3.2
UPD. Took me unexpectedly whole day, but yes, it installed on 10.6 without issues.
Have you

mercury: update to 22.01.8

---

_resources/port1.0/group/ruby-1.0.tcl
lang/ruby-devel/Portfile

Update, also add to ruby PG.
macOS 10.6
Xcode 3.2
Have you

ruby-devel: update to 2024.02.19

---

R/R-ACDm/Portfile
R/R-BayesMultiMode/Portfile
R/R-BayesTools/Portfile
R/R-BranchGLM/Portfile
R/R-FaultTree/Portfile
R/R-NNS/Portfile
R/R-amen/Portfile
R/R-bayesPO/Portfile
R/R-beachmat/Portfile
R/R-binGroup2/Portfile
R/R-bistablehistory/Portfile
R/R-bootUR/Portfile
R/R-callr/Portfile
R/R-circlize/Portfile
R/R-cooltools/Portfile
R/R-drake/Portfile
R/R-e1071/Portfile
R/R-ergm.multi/Portfile
R/R-estimability/Portfile
R/R-exdex/Portfile
R/R-fiery/Portfile
R/R-fitdistrplus/Portfile
R/R-fmesher/Portfile
R/R-fnets/Portfile
R/R-foghorn/Portfile
R/R-frab/Portfile
R/R-latentnet/Portfile
R/R-networktools/Portfile
R/R-winch/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

R: updates for packages (1)

---

math/stan/Portfile
math/stanmath/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

stanmath: update to 4.8.1; stan: update to 2.34.1

---

lang/algol68g/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

algol68g: update to 3.5.0

---

devel/starpu/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

starpu: update to 1.4.4

---

python/py-rchitect/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

py-rchitect: update to 0.4.6

---

aqua/qt5/Portfile
aqua/qt5/files/CVE-2023-33285-qtbase-5.15.diff
aqua/qt5/files/CVE-2024-25580-qtbase-5.15.diff

macOS 12.7.3 Intel
Xcode 14.2
Have you

qt5-qtbase: apply security patch

---

aqua/qt6/Portfile
aqua/qt6/files/CVE-2023-32762-qtbase.diff
aqua/qt6/files/CVE-2023-32763-qtbase.diff
aqua/qt6/files/CVE-2023-33285-qtbase.diff
aqua/qt6/files/CVE-2023-37369-qtbase.diff
aqua/qt6/files/CVE-2023-38197-qtbase.diff
aqua/qt6/files/CVE-2023-51714-qtbase.diff
aqua/qt6/files/CVE-2024-25580-qtbase.diff
aqua/qt6/files/patch-qtbase-macos_10.14_sdk.diff

Also avoid fuzz in existing patch
macOS 12.7.3. Intel
Xcode 14.2
Have you

qt6-qtbase: apply security patches

---

ocaml/ocaml-dune/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-dune: update to 3.14.0

---

ruby/ruby-build/Portfile

ruby-build: Update to 20240221

---

R/R-RSiena/Portfile
R/R-Rhdf5lib/Portfile
R/R-SSNbayes/Portfile
R/R-SuperLearner/Portfile
R/R-TAM/Portfile
R/R-TempStable/Portfile
R/R-TempStable/files/patch-no-v8.diff
R/R-TraMineR/Portfile
R/R-pastecs/Portfile
R/R-pbdSLAP/Portfile
R/R-pbv/Portfile
R/R-pcalg/Portfile
R/R-philentropy/Portfile
R/R-pkglite/Portfile
R/R-plotly/Portfile
R/R-powerindexR/Portfile
R/R-report/Portfile
R/R-rhdf5/Portfile
R/R-rhdf5filters/Portfile
R/R-rmumps/Portfile
R/R-secretbase/Portfile
R/R-spatialreg/Portfile
R/R-stokes/Portfile
R/R-surveil/Portfile
R/R-survstan/Portfile
R/R-tarchetypes/Portfile
R/R-thor/Portfile
R/R-timbr/Portfile
R/R-tinysnapshot/Portfile
R/R-twang/Portfile

Remaining updates.
(I won’t be able to do any for next 2–3 weeks, perhaps, so tried to update whatever is there now.)
macOS 10.6
Xcode 3.2
Have you

R: remaining updates for packages (3)

---

fortran/econ-toolchain/Portfile
fortran/econ-toolchain/files/0001-fpm.toml-fix-parsing.patch

New port in Fortran
macOS 14.3.1
Xcode 15.2
(Cannot test on PowerPC at the moment, but Fortran stuff normally builds and tests fine there.)
Have you

econ-toolchain: new port in fortran

---

lang/py-htmldocs/Portfile

py-htmldocs: add 312, remove 38/9, update 311

---

math/fxt/Portfile
math/fxt/files/patch-makefile.diff

Update
macOS 10.6
Xcode 3.2
macOS 14.3.1
Xcode 15.2
Have you

fxt: update to 2024.01.14

---

x11/homebank/Portfile

* update with new version 5.7.4
* update maintainer's github handle
* update homepage url
* add livecheck section
Have you

homebank: Update in version 5.7.4

---

ruby/rb-gpgme/Portfile
ruby/rb-mini_portile2/Portfile

New port
macOS 14.3.1
Xcode 15.2
Have you

rb-gpgme: new port in ruby

---

ruby/rb-image_science/Portfile
ruby/rb-multi_json/Portfile
ruby/rb-nitpick/Portfile
ruby/rb-parsetree/Portfile
ruby/rb-ruby_parser/Portfile
ruby/rb-rubyinline/Portfile
ruby/rb-rubytoc/Portfile
ruby/rb-sexp_processor/Portfile
ruby/rb-trollop/Portfile
ruby/rb-zentest/Portfile

Update some Ruby ports.
macOS 14.3.1
Xcode 15.2
Have you

Ruby: update some ports

---

_resources/port1.0/group/haskell_stack-1.0.tcl

PG haskell_stack: add default master_sites

---

devel/n/Portfile

n: update to 9.2.1

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff

macOS 13.6.4 22G513 x86_64
Have you

py-awscli2: update to 2.15.23

---

python/py-mdx_linkify/Portfile

py-mdx_linkify: Submission

---

ruby/rb-forwardable/Portfile
ruby/rb-htmlentities/Portfile
ruby/rb-ncursesw/Portfile
ruby/rb-optimist/Portfile
ruby/rb-retryable/Portfile
ruby/rb-rmail/Portfile
ruby/rb-singleton/Portfile
ruby/rb-unf/Portfile
ruby/rb-unf_ext/Portfile
ruby/rb-unicode-display_width/Portfile
ruby/rb-unicode/Portfile

Some new Ruby ports, to be used as dependencies later.
macOS 14.3.1
Xcode 15.2
Have you

Ruby: some new ports

---

lang/logtalk/Portfile

logtalk: update to 3.75.0

---

ruby/rb-3llo/Portfile
ruby/rb-pastel/Portfile
ruby/rb-tty-color/Portfile
ruby/rb-tty-cursor/Portfile
ruby/rb-tty-prompt/Portfile
ruby/rb-tty-reader/Portfile
ruby/rb-tty-screen/Portfile
ruby/rb-wisper/Portfile

New ports.
macOS 14.3.1
Xcode 15.2
Have you

rb-3llo and supporting ports: new packages in ruby

---

python/py-sphinx-jsonschema/Portfile

py-sphinx-jsonschema: Add Python 311, 312, Remove Python 37

---

ruby/rb-ast/Portfile
ruby/rb-parser/Portfile

New ports
macOS 14.3.1
Xcode 15.2
Have you

rb-ast, rb-parser: new ports in ruby

---

graphics/opencv4-devel/Portfile

opencv4-devel: update to 4.9.0, use python 3.12

---

textproc/pandoc/Portfile

* Fixes: https://trac.macports.org/ticket/69413
macOS x.y
Have you

pandoc: Fix checksums

---

net/snac/Portfile

macOS 14.4 23E5211a arm64
Have you

snac: update to 2.48

---

dotnet/aspnetcore-runtime-devel/Portfile
dotnet/dotnet-runtime-devel/Portfile
dotnet/dotnet-sdk-devel/Portfile

dotnet-runtime-devel: update to 9.0.0-preview.1.24080.9
aspnetcore-runtime-devel: update to 9.0.0-preview.1.24081.5
dotnet-sdk-devel: update to 9.0.100-preview.1.24101.2
Have you

dotnet-devel: update to 9.0.0-preview.1

---

lang/swi-prolog/Portfile

swi-prolog: Updated to version 9.2.2

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.3.2

---

devel/simdjson/Portfile

Update
macOS 14.3.1
Xcode 15.2
Have you

simdjson: update to 3.7.0

---

devel/operator-sdk/Portfile

operator-sdk: new port submission

---

R/R-Compositional/Portfile
R/R-Directional/Portfile
R/R-dslabs/Portfile
R/R-gmvarkit/Portfile
R/R-pillar/Portfile
R/R-shinyWidgets/Portfile

Updates
macOS 14.3.1
Xcode 15.2
Have you

R: a few updates for packages

---

textproc/lilypond/Portfile

lilypond-devel: update to 2.25.13

---

sysutils/john/Portfile

john-jumbo: use ruby 3.2 and python 3.12

---

erlang/atomvm/Portfile

atomvm: update to 0.6.0b1

---

devel/pnpm/Portfile

pnpm: update to 8.15.4
Have you

pnpm: update to 8.15.4

---

emulators/uxn/Portfile
emulators/uxn/files/patch-uxn-build.diff

Closes: https://trac.macports.org/ticket/68860
Have you

uxn: update to 20240302

---

math/R/Portfile

R: update to 4.3.3

---

sysutils/mc/Portfile

mc: update to 4.8.31

---

devel/operator-sdk/Portfile

operator-sdk: update to 1.34.0

---

math/R/Portfile
math/R/files/patch-fix-10.9.diff

Closes: https://trac.macports.org/ticket/69437
macOS x.y
Have you

R: unbreak aqua variant for < 10.10

---

gis/qgis3/Portfile

The patch fix https://github.com/macports/macports-ports/commit/63a27db81cd90a126375bd94d231755cb811f349 actually broke the `qgis3-ltr` `+grass` variant. The need of the patch was caused by file rename with QGIS 3.36 only. This fixes the `qgis3-ltr +grass`.
macOS x.y
Have you

qgis3-ltr: fix Grass7Utils.py patch

---

net/rpki-client/Portfile

macOS 14.4 23E5211a arm64
Have you

rpki-client: update to 9.0

---

python/py-g2p-en/Portfile

Distance is listed as a dependency in setup.py, 
but it doesn't seem to do anything and has been omitted
Have you
- [ =x] checked that there aren't other open [pull requests](https://github.com/macports/macports-ports/pulls) for the same change?

py-g2p-en: new port

---

lang/llvm-16/files/mp-clang-16
lang/llvm-17/files/mp-clang-17
sysutils/clang_select/Portfile
sysutils/clang_select/files/base

This adds some more entries for clang_select that were added in 6ff441c but then reverted. I've only filled in the entries for clang-15 and clang-16, since I'm not sure if every binary is available in previous verisons. 
I've left out clangd, see https://github.com/macports/macports-ports/pull/10558 cc @gpanders @kencu
Have you

clang_select: Add entries for git-clang-format + some others

---

net/snac/Portfile

macOS 14.4 23E5211a arm64
Have you

snac: update to 2.49

---

archivers/unrar/Portfile

unrar: update to 7.0.7

---

devel/global/Portfile

global: update to 6.6.12 and use python 3.12

---

devel/docker/Portfile

docker: update to 25.0.3

---

erlang/atomvm/Portfile

atomvm: update to 0.6.0

---

python/py-XlsxWriter/Portfile

py-xlsxwriter: 3.2.0

---

devel/operator-sdk/Portfile

operator-sdk: update to 1.34.1

---

python/py-cryptg/Portfile
python/py-pyaes/Portfile
python/py-telethon/Portfile

py-telethon: Update to version 1.34.0

---

python/py-imagehash/Portfile

py-imagehash: Add Python 312

---

python/py-portalocker/Portfile

py-portalocker: Add Python 312

---

devel/libretls/Portfile
irc/pounce/Portfile
net/catgirl/Portfile
net/telescope/Portfile

libretls: update to 3.8.1

---

python/py-plotly/Portfile

* allow jupyterlab version >3
Closes: https://trac.macports.org/ticket/69416
Have you
- [ x squashed and [minimized your commits](https://guide.macports.org/#project.github)?

py-plotly:  fix jupyterlab version

---

R/R-CBnetworkMA/Portfile
R/R-GDAtools/Portfile
R/R-NNS/Portfile
R/R-accessibility/Portfile
R/R-aides/Portfile
R/R-betafunctions/Portfile
R/R-colorRamps/Portfile
R/R-descriptio/Portfile
R/R-gmodels/Portfile
R/R-libr/Portfile
R/R-migraph/Portfile
R/R-pillar/Portfile
R/R-rcpptimer/Portfile
R/R-stinepack/Portfile
R/R-stringmagic/Portfile

Mostly updates, a few new ports.
macOS 14.3.1
Xcode 15.3
Have you

R: updates and a few new packages (2)

---

ruby/rb-fsevent/Portfile
ruby/rb-inotify/Portfile
ruby/rb-inotify/files/patch-gemspec-3.1.diff
ruby/rb-inotify/files/patch-gemspec-3.2.diff
ruby/rb-inotify/files/patch-gemspec-3.3.diff
ruby/rb-sass-listen/Portfile
ruby/rb-sass-listen/files/patch-gemspec-3.1.diff
ruby/rb-sass-listen/files/patch-gemspec-3.2.diff
ruby/rb-sass-listen/files/patch-gemspec-3.3.diff
ruby/rb-sass/Portfile

(New ports are dependencies.)
macOS 14.3.1
Xcode 15.3
Have you

rb-sass: update to 3.7.4, use modern Ruby

---

ruby/rb-gem-patch/Portfile
ruby/rb-nokogiri/Portfile
ruby/rb-racc/Portfile

Support Ruby 3.3.
macOS 14.3.1
Xcode 15.3
Have you

rb-nokogiri: support ruby33

---

devel/docker/Portfile

docker: update to 25.0.4

---

math/LightGBM/Portfile
math/LightGBM/files/0001-Fix-CMakeLists.txt.patch
math/LightGBM/files/0002-common.h-fix-includes.patch

New port: https://github.com/microsoft/LightGBM
P. S. Cannot test for old systems right now, but will follow-up with a fix, if anything needed. `R` version of this builds fine even for PowerPC.
macOS 14.3.1
Xcode 15.3
Have you

LightGBM: new port in math

---

audio/tenacity/Portfile
audio/tenacity/files/CMAKE_OSX_ARCHITECTURES.patch
audio/tenacity/files/Cursors.h.patch
audio/tenacity/files/FFmpeg.patch
audio/tenacity/files/GIT_DESCRIBE.patch
audio/tenacity/files/TenacityFunctions.cmake.patch

tenacity: New port, version 1.3.3

---

security/libressl/Portfile

libressl: update to 3.8.3

---

security/libressl-devel/Portfile

libressl-devel: update to 3.9.0

---

devel/kompose/Portfile

kompose: update to 1.32.0

---

gnome/gtk-radio/Portfile
gnome/gtk-radio/files/autogen.sh

gtk-radio 264.2 for macports 2.9.1
Have you

gtk-radio: new port

---

python/py-importlib-resources/Portfile

py-importlib-resources: Update to version 6.1.2; Add Python 311, 312

---

python/py-nbconvert/Portfile
textproc/pandoc/Portfile

* Update to version 3.1.12.2
* Add minimal pdf creation runtime dependencies
macOS x.y
Have you

pandoc: Update to version 3.1.12.2

---

ruby/rb-bones/Portfile
ruby/rb-bones/files/patch-gemspec-3.1.diff
ruby/rb-bones/files/patch-gemspec-3.2.diff
ruby/rb-bones/files/patch-gemspec-3.3.diff
ruby/rb-little-plugger/Portfile
ruby/rb-loquacious/Portfile
ruby/rb-psych/Portfile
ruby/rb-rdoc/Portfile
ruby/rb-stringio/Portfile

(New ports are dependencies.)
macOS 14.3.1
Xcode 15.3
Have you

rb-bones: update to 3.9.0, use modern Ruby

---

R/R-InspectChangepoint/Portfile
R/R-RcppCWB/Portfile
R/R-SUMMER/Portfile
R/R-duckdbfs/Portfile
R/R-duckplyr/Portfile
R/R-fastcpd/Portfile
R/R-fastcpd/files/patch-drop-missing-deps.diff
R/R-gfpop/Portfile
R/R-ggdist/Portfile
R/R-ggraph/Portfile
R/R-jfa/Portfile
R/R-runjags/Portfile
R/R-showtext/Portfile
R/R-stochvol/Portfile
R/R-survey/Portfile
R/R-sysfonts/Portfile
R/R-tinytable/Portfile
R/R-tm/Portfile
R/R-ufs/Portfile
R/R-vMF/Portfile
R/R-wdnet/Portfile

Remaining updates.
macOS 14.3.1
Xcode 15.3
Have you

R: updates for packages (3)

---

python/py-nbconvert/Portfile

Fixes [this problem](https://build.macports.org/builders/jobs-mirror/builds/722285/steps/mirror/logs/stdio):
```
--->  Fetching distfiles for py-nbconvert
--->  :main does not exist in /Volumes/RAID/opt/local/var/rsync/macports/distfiles/py-nbconvert
--->  Attempting to fetch :main from http://distfiles.macports.org/py-nbconvert
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0--->  Attempting to fetch :main from http://mirror.fcix.net/macports/distfiles/py-nbconvert
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- …
```

py-nbconvert: Don't set distfiles in stub port

---

R/R-RcppEigen/Portfile
R/R-RcppEigen/files/patch-fix-powerpc.diff

Sorry, this was missed.
macOS 10.6.8
Xcode 3.2.6
Have you

R-RcppEigen: fix PowerPC includes

---

mail/nmail/Portfile

Fix all-that-familiar `malloc` errors.
macOS 10.6.8
Xcode 3.2.6
Have you

nmail: fix when built against libstdc++

---

R/R-igraph/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

R-igraph: update to 2.0.3

---

gis/proj9/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

proj9: update to 9.4.0

---

devel/docker-base-plugin/Portfile
devel/docker-buildx-plugin/Portfile
devel/docker-compose-plugin/Portfile
devel/docker-index-plugin/Portfile
devel/docker/Portfile
sysutils/colima/Portfile
sysutils/lima/Portfile
sysutils/lima/files/patch-main.diff

This PR contains various tweaks to Docker and related ports, adding a few plugins, including some completions and manual pages. Furthermore, I added a runtime dependency from `colima` to `docker`, as that seems the most likely use.
Have you

Assorted Docker-related tweaks

---

lang/algol68g/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

algol68g: update to 3.5.1

---

devel/nng/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nng: update to 1.7.3

---

textproc/enchant2/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

enchant2: update to 2.6.7

---

lang/fortran-stdlib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib: update to 2024.03.05

---

lang/ruby-devel/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ruby-devel: update to 2024.03.14

---

math/flexiblas/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

flexiblas: update to 3.4.2

---

ruby/rb-rice/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

rb-rice: update to 4.3.0

---

ocaml/ocaml-alcotest/Portfile
ocaml/ocaml-syntax-shims/Portfile
ocaml/ocaml-utop/Portfile

Update, add test deps.
macOS 10.6
Xcode 3.2
macOS 14.4
Xcode 15.3
Have you

ocaml-utop: update to 2.14.0

---

net/picotls/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

picotls: update to 2024.03.05

---

ruby/rb-chronic/Portfile
ruby/rb-gpgme/Portfile
ruby/rb-lockfile/Portfile
ruby/rb-sup/Portfile
ruby/rb-sup/files/patch-fix-xapian.diff
ruby/rb-sup/files/patch-set-version.diff
ruby/rb-unicode/Portfile

New port and a few needed updates.
macOS 14.4
Xcode 15.3
Have you

rb-sup: e-mail client in Ruby

---

net/ddclient/Portfile

ddclient: update to 3.11.2

---

aqua/iTerm2/Portfile
aqua/iTerm2/files/patch-xcode12.diff

https://trac.macports.org/ticket/65354
Have you

iTerm2: fix XCode 12 build

---

graphics/libdmtx/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libdmtx: update to 0.7.7

---

devel/gFTL-shared/Portfile
devel/gFTL/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

gFTL: update to 1.12.0; gFTL-shared: update to 1.8.0

---

ruby/rb-uuidtools/Portfile

Update
macOS 14.3.1
Xcode 15.3
Have you

rb-uuidtools: update to 2.2.0

---

graphics/asymptote/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

asymptote: update to 2.88

---

graphics/dvisvgm-devel/Portfile

I update only -devel port.
macOS 10.6
Xcode 3.2
Have you

dvisvgm-devel: update to 3.2.2

---

games/fheroes2/Portfile

fheroes2: update to 1.0.13

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff

py-awscli2: update to 2.15.30

---

shells/tcsh/Portfile

tcsh: update to 6.24.11

---

audio/FAudio/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

FAudio: update to 24.03

---

python/poetry/Portfile

poetry: update to 1.8.3

---

gis/qgis3/Portfile
gis/qgis3/files/patch-PROJ94.diff
gis/qgis3/files/patch-configure_PROJ94.diff

`qgis3`, `qgis3-ltr`: use CMake's default FindSQLite3 to configure with PROJ 9.4
Closes: https://trac.macports.org/ticket/69507
Have you

qgis3, qgis3-ltr: use CMake's default FindSQLite3

---

net/softether5/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

softether5: update to 5.02.5182

---

ruby/rb-rice/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

rb-rice: update to 4.3.1

---

devel/libsdl2-powerpc/Portfile
devel/libsdl2-powerpc/files/0001-Fixes-for-PowerPC.patch
devel/libsdl2-powerpc/files/0002-fix-x11.diff
devel/libsdl2-powerpc/files/0003-hidapi-revert-a-commit-that-triggers-ICE-with-GCC.patch

Here we go.
Making a standalone port, so that a) exiting Josh’s SDL2 port is untouched (and it is already complicated, better not worsen that anyway) and b) I can fix stuff for PowerPC without worrying of breaking anything else.
Therefore, this is restricted to < 10.7 and ppc/ppc64. (Though it should work in principle on any system.)
macOS x.y
Have you

libsdl2-powerpc: SDL2 for PowerPC

---

devel/mercurial/Portfile

mercurial: update to 6.7

---

emulators/uxn/Portfile

uxn: update to 20240316

---

net/ngtcp2/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ngtcp2: update to 1.4.0

---

gis/gdal-grass/Portfile
gis/grass/Portfile
gis/grass/files/03_patch_python312.diff

Update `grass` to version 8.3.2.
macOS x.y
Have you

grass: update to version 8.3.2

---

python/py-cbor2/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

py-cbor2: update to 5.6.2

---

java/flyway/Portfile

flyway: update to 10.10.0

---

lang/logtalk/Portfile

logtalk: update to 3.76.0

---

math/qalculate-gtk/Portfile

* update to version 5.0.0
* current version 4.9.0 is broken since `libqalculate` was updated to 5.0.0
Have you

qalculate-gtk:  update to version 5.0.0

---

python/py-jupytext/Portfile
python/py-jupytext/files/patch-pyproject.toml.diff

py-jupytext: update to 1.16.1

---

devel/docker/Portfile

docker: update to 25.0.5

---

graphics/tinygltf/Portfile
python/py-libpysal/Portfile
python/py-quantecon/Portfile

Updates: 
- `tinygltf` to version 2.8.21
- `py-quantecon` to version 0.7.2
- `py-libpysal` to version 4.10
Have you

tinygltf, py-quantecon, py-libpysal: updates

---

python/py-gensim/Portfile
python/py-gensim/files/patch-do-not-hardcode-cpp-runtime.diff

Update, fix build with `libstdc++`
macOS 14.4
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

py-gensim: update to 4.3.2

---

math/libflame/Portfile
math/libflame/files/patch-Makefile.diff

This is an initial support for LAPACK-like library for `blis` (which currently has no lapack).
At the moment I just add the port, but do not use it anywhere.
@catap Kirill, I add you as a maintainer, since you are a maintainer of `blis`, and this is supposed to be its lapack.
(If you prefer not to be involved here, please let me know.)
macOS 14.4
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

libflame: new port in math

---

python/py-colored/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

py-colored: update to 2.2.4, support python312

---

devel/docker/Portfile

docker: update to 26.0.0

---

graphics/opencv4/Portfile

opencv4: update to 4.9.0, use python 3.12

---

devel/wolfssl/Portfile

wolfssl: update to version 5.7.0

---

multimedia/live555/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

live555: update to 2024.03.08

---

python/py-owslib/Portfile

Update `py-owslib` to version 0.30.0.
macOS x.y
Have you

py-owslib: update to version 0.30.0

---

gis/cgal5/Portfile
gis/rsgislib/Portfile

Update:
- `rsgislib` and `py-rsgislib` to version 5.1.2
- `cgal5` to version 5.6.1
In addition makes `[py-]rsgislib` maintenance open and adds me as co-maintainer.
Have you

rsgislib, py-rsgislib, cgal5: updates

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.3.3

---

devel/libsdl2-powerpc/Portfile
devel/libsdl2-snowleopard/Portfile
devel/libsdl2/Portfile

[skip ci]
There is no change to the code, just a switch to path-style dependency.
macOS x.y
Have you

libsdl2: use libsdl2-powerpc on powerpc systems (no change for other platforms)

---

math/fxt/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fxt: update to 2024.03.14

---

devel/chai/Portfile
devel/raja/Portfile
devel/raja/files/patch-throw-away-desul.diff

Update both
macOS 10.6
Xcode 3.2
Have you

raja, chai: update to 2024.02.0

---

devel/cmake-devel/Portfile

cmake-devel update to 20240322-3.29.1-cff8aefc

---

python/py-cinderclient/Portfile
python/py-dogpile-cache/Portfile
python/py-keystoneauth1/Portfile
python/py-novaclient/Portfile
python/py-stevedore/Portfile
python/py-virtualenvwrapper/Portfile
python/py-virtualenvwrapper/files/virtualenvwrapper37

py-stevedore: update to 5.2.0

---

gis/qgis3/Portfile

qgis3: enable and default to python 3.12

---

news/tin/Portfile

tin: update to 2.6.3

---

net/snac/Portfile

snac: update to 2.50

---

python/py-dropbox/Portfile
python/py-stone/Portfile

Add Python 3.12
macOS 10.6
Xcode 3.2
Have you

py-dropbox, py-stone: support python 3.12

---

sysutils/maestral/Portfile

Update
macOS 14.4
Xcode 15.3
Have you

maestral: update to 1.9.1

---

net/nextdns/Portfile

Closes: https://trac.macports.org/ticket/68410
Have you

nextdns: update to 1.42.0

---

databases/duckdb/Portfile

This resolves the issue where the current version information of duckdb is being built abnormally as `v..1-dev`, preventing the installation of extensions.
Additionally, it addresses the problem where the build-in extension defined in the Portfile is not being applied.
* Use `OVERRIDE_GIT_DESCRIBE` instead of `DUCKDB_VERSION`
* Use `BUILD_EXTENSIONS` instead of `BUILD_*_EXTENSION`
* https://duckdb.org/dev/building#overriding-git-hash-and-version
* https://github.com/duckdb/duckdb/tree/main/extension#building-extensions
<details>
<summary>As-is</summary>
```
$ duckdb --version
v..1-dev 
$ duckdb          
v..1-dev 
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D FROM duckdb_extensions(); …
```

duckdb: fix configure args

---

mail/dcc/Portfile

dcc: Update to version 2.3.169

---

security/blake3/Portfile

Update blake3 to version 1.5.1
macOS 13.6.5 22G621 arm64
Have you

blake3: update 1.5.1

---

math/arborx/Portfile

Update.
Use path-style dep for Kokkos.
macOS 14.4
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

arborx: update to 1.5

---

devel/CImg/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

CImg: update to 3.3.5

---

archivers/xz/Portfile

Update xz to 5.6.1
macOS 13.6.5 22G621 arm64
Have you

xz: update to 5.6.1

---

devel/alex/Portfile

alex Update to version 3.5.1.0

---

math/nanoflann/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nanoflann: update to 1.5.5

---

R/R-highs/Portfile
R/R-highs/files/patch-cxx11.diff
R/R-highs/files/patch-fix-paths.diff
R/R-highs/files/patch-gcc-builds.diff
math/HiGHS/Portfile
math/HiGHS/files/0001-CMakeLists-use-CMAKE_OSX_ARCHITECTURE-not-CMAKE_SYST.patch

Update
macOS 10.6
Xcode 3.2
Have you

HiGHS: update to 1.7.0

---

x11/Hypr/Portfile
x11/Hypr/files/0001-CMakeLists-fix-compiler.patch

New port
macOS 14.4
Xcode 15.3
macOS 10a190
Xcode 3.2
Have you

Hypr: new port in x11

---

R/R-bgw/Portfile
R/R-emBayes/Portfile
R/R-felp/Portfile
R/R-rmumps/Portfile
R/R-wrangle/Portfile

(Nothing will be added here.)
macOS 14.4.1
Xcode 15.3
Have you

R: few remaining updates

---

math/muparser/Portfile

Update, support tests
macOS 10.6
Xcode 3.2
Have you

muparser: update to 2.3.4, support testing

---

databases/postgis3/Portfile
gis/mod_tile/Portfile
gis/osm2pgrouting/Portfile
gis/osm2pgsql/Portfile
gis/pgrouting/Portfile
gis/tinyows/Portfile
gis/tinyows/files/patch_ows_config_c.patch

- `postgis3`: change `postgresql[XX]` variants to `pg[XX]-postgis3` subports
- `pgrouting`: change `postgresql[XX]` variants to `pg[XX]-pgrouting ` subports; make port open maintained, add nilason as co-maintainer.
- updates `osm2pgrouting`, `osm2pgsql`, `tinyows` and `mod_tile` to the change to the new postgis3 subports.
macOS x.y
Have you

postgis3, pgrouting: change PostgreSQL variants to subports

---

www/nicotine-plus/Portfile
www/nicotine-plus/files/patch-GTK3.diff
www/nicotine-plus/files/patch-GTK4.diff

Update
macOS 10.6
Xcode 3.2
Have you

nicotine-plus: update to 3.3.2, use gtk4 and python312 by default

---

net/pidgin/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

pidgin: update to 2.14.13

---

net/amule/Portfile

1. Use wxGTK on older systems, since wxWidgets is buggy there (it builds but remains broken). Since I cannot check it on 10.7, to be on a safe side, use wxGTK there as well. I have confirmed that on 10.8 wxWidgets does work.
2. Add `libgeoip` dependency.
P. S. Let’s go with this now, since it works fine.
macOS 10.6
Xcode 3.2
Have you

amule: use wxGTK on old systems; add GeoIP support

---

python/py-awscli2/Portfile

py-awscli2: update to 2.15.34

---

sysutils/coreutils-uutils/Portfile

coreutils-uutils: update to 0.0.25

---

graphics/rawstudio/Portfile
graphics/rawstudio/files/patch-compatibility-with-libxml2-2.12.x.diff
graphics/rawstudio/files/patch-inlines.diff
graphics/rawstudio/files/patch-plugins-dcp.diff
graphics/rawstudio/files/patch-rawstudio.h.diff

Fixes: https://trac.macports.org/ticket/69524
@ryandesign I have fixed it on PowerPC now :) 
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

rawstudio: fix build with new libxml2; fix build with gcc

---

devel/legacy-support/Portfile

legacy-support-devel: update to latest master

---

devel/libSDL2pp/Portfile

New port
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

libSDL2pp: new port in devel

---

R/R-DBI/Portfile
R/R-DBItest/Portfile
R/R-Epi/Portfile
R/R-RSQLite/Portfile
R/R-data.table/Portfile
R/R-dsem/Portfile
R/R-forsearch/Portfile
R/R-modelsummary/Portfile
R/R-modelsummary/files/patch-no-webshot2.diff
R/R-onion/Portfile
R/R-pandoc/Portfile
R/R-phylopath/Portfile
R/R-pomp/Portfile
R/R-tinytable/Portfile

Updates.
(For `R-DBI*` I am a co-maintainer, and those are trivial updates, so no need to wait 3 days ritualistically.)
macOS 10.6
Xcode 3.2
Have you

R: weekend updates to packages

---

lang/ruby-devel/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

ruby-devel: update to 2024.03.31

---

devel/mz-cmaketools/Portfile

Update
macOS 14.4.1
Xcode 15.3
Have you

mz-cmaketools: update to 2024.03.25

---

devel/gFTL-shared/Portfile
devel/gFTL-shared/files/patch-fix-install.diff
devel/gFTL/Portfile

Update and fix
macOS 10.6
Xcode 3.2
Have you

gFTL: update to 1.13.0; gFTL-shared: fix linking to gFTL on case-sensitive systems

---

python/py-dbus_next/Portfile
python/py-desktop-notifier/Portfile
python/py-keyrings.alt/Portfile
python/py-pytest-rerunfailures/Portfile
python/py-rubicon-objc/Portfile
python/py-survey/Portfile
sysutils/maestral/Portfile

Update
macOS 14.4.1
Xcode 15.3
Have you

maestral: update to 1.9.2

---

x11/xorg-xcb-util-image/Portfile

Update, fix lint.
macOS 10.6.8
Xcode 3.2.6
Have you

xorg-xcb-util-image: update to 0.4.1

---

multimedia/mpv/Portfile

Closes: https://trac.macports.org/ticket/69645
macOS x.y
Have you

mpv: link ffmpeg6

---

multimedia/mkvtoolnix-legacy/Portfile

mkvtoolnix-legacy: submission

---

python/py-line_profiler/Portfile

py-line_profiler: Submission

---

lang/logtalk/Portfile

logtalk: update to 3.77.0

---

gis/pgrouting/Portfile

Update `[pg-]pgrouting` to version 3.6.2.
macOS x.y
Have you

pgrouting: update to version 3.6.2

---

www/wiki-tui/Portfile

Update to wiki-tui version 0.8.2
macOS 13.6.5 22G621 arm64
Have you

wiki-tui: update to 0.8.2

---

devel/gitu/Portfile

Add [`gitu`](https://github.com/altsem/gitu), a TUI Git client inspired by Magit.
Closes: https://trac.macports.org/ticket/69476
Have you

gitu: new port (0.12.1)

---

devel/gl-headers/Portfile

gl-headers: These headers conflict with mesa

---

x11/mesa/Portfile

mesa: Add conflicts with gl-headers

---

ruby/rb-roauth/Portfile

Update
macOS 14.4.1
Xcode 15.3
Have you

rb-roauth: update to 0.0.8

---

science/elmerfem/Portfile

Closes: https://trac.macports.org/ticket/69308
Update
macOS 14.4.1
Xcode 15.3
Have you

elmerfem: update to 2024.04.03, use Qt5 on newer systems

---

devel/libSDL2pp/Portfile

Closes: https://trac.macports.org/ticket/69638
Fix
macOS x.y
Have you

libSDL2pp: fix build on 10.7–10.12

---

devel/astyle/Portfile

astyle: update to 3.4.13

---

palm/m68k-palm-elf-gcc/Portfile
palm/m68k-palm-elf-gcc/files/aarch64.diff
palm/m68k-palm-elf-gcc/files/palm.diff
palm/m68k-palm-elf-gcc/files/retro68.diff

I mistakenly left newlib out in #19772 , thinking it wasn't necessary. Now this port should actually match the Linux build script provided by dmitrygr.
Have you

m68k-palm-elf-gcc: add newlib

---

sysutils/bash-completion/Portfile
sysutils/bash-completion/files/patch-xine-add-more-formats.diff
sysutils/bash-completion/files/patch-xpdf-support-compressed-pdf.diff

bash-completion: update to 2.13.0

---

net/snac/Portfile

snac: update to 2.51

---

gis/gdal/Portfile
python/py-gdal/Portfile

Update `gdal` and `py-gdal` to version 3.8.5.
Have you

gdal, py-gdal: update to 3.8.5

---

gis/qgis3/Portfile

`qgis3`, `qgis3-ltr`: check Python variants sync in pre-commit phase and correcting faulty set of default +pythonXX +plugin_supportXX variants.
Closes: https://trac.macports.org/ticket/69607
macOS x.y
Have you

qgis3, qgis3-ltr: fix python/plugin_support variants' default and sync check

---

ruby/rb-ffi-compiler/Portfile

Update
macOS 14.4.1
Xcode 15.3
Have you

rb-ffi-compiler: update to 1.3.2

---

mail/claws-mail/Portfile
mail/claws-mail/files/patch-no-cpp-precomp.diff

Update
macOS 10.6
Xcode 3.2
Have you

claws-mail: update to 3.20.0

---

devel/sccache/Portfile

sccache: update to 0.7.7

---

sysutils/mise/Portfile

mise: update to 2024.4.0

---

R/R-DPTM/Portfile
R/R-DT/Portfile
R/R-Delaporte/Portfile
R/R-DiffNet/Portfile
R/R-GeneralizedWendland/Portfile
R/R-MonteCarloSEM/Portfile
R/R-NetCluster/Portfile
R/R-RNewsflow/Portfile
R/R-RoBTT/Portfile
R/R-bWGR/Portfile
R/R-bayest/Portfile
R/R-bmemLavaan/Portfile
R/R-fastTS/Portfile
R/R-fmx/Portfile
R/R-htmltools/Portfile
R/R-knnmi/Portfile
R/R-knnmi/files/patch-fix-eigen-altivec.diff
R/R-lbfgsb3c/Portfile
R/R-mcgf/Portfile
R/R-modelfactory/Portfile
R/R-pkgcache/Portfile
R/R-quanteda/Portfile
R/R-quanteda/files/patch-Makevars.diff
R/R-rTensor2/Portfile
R/R-rtmpt/Portfile
R/R-scatterpie/Portfile
R/R-secretbase/Portfile
R/R-shinyWidgets/Portfile
R/R-stars/Portfile
R/R-tester/Portfile

Mostly updates, a few new ports.
macOS 10.6
Xcode 3.2
Have you

R: updates for packages and a few new ones

---

ruby/rb-gdk4/Portfile
ruby/rb-gmp/Portfile
ruby/rb-goffice/Portfile
ruby/rb-gsf/Portfile
ruby/rb-gtk4/Portfile

New ports in Ruby.
macOS 14.4.1
Xcode 15.3
Have you

Ruby: some new packages

---

editors/lite-xl/Portfile

Update
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

lite-xl: update to 2.1.3

---

devel/mz-cmaketools/Portfile
devel/xdispatch2/Portfile
devel/xdispatch2/files/0001-Avoid-a-need-for-Conan.patch
devel/xdispatch2/files/0002-Add-missing-stdexcept-header.patch
devel/xdispatch2/files/0003-Fix-tests.patch
devel/xdispatch2/files/0004-Tests-no-qt5.patch

New port in devel
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

xdispatch2: new port in devel

---

graphics/d2/Portfile

d2: update to 0.6.3

---

devel/libsdl2-powerpc/Portfile
devel/libsdl2-powerpc/files/0002-fix-x11.diff

Update
macOS 10.6
Xcode 3.2
Have you

libsdl2-powerpc: update to 2.30.2

---

ruby/rb-base32/Portfile
ruby/rb-base_convert/Portfile
ruby/rb-bigdecimal/Portfile
ruby/rb-concurrent-ruby/Portfile
ruby/rb-curb/Portfile
ruby/rb-hessian2/Portfile
ruby/rb-i18n/Portfile
ruby/rb-posix-spawn/Portfile
ruby/rb-rbon/Portfile
ruby/rb-super_random/Portfile
ruby/rb-totp/Portfile
ruby/rb-yaml_zlib_blowfish/Portfile

Some new ports in Ruby.
macOS 14.4.1
Xcode 15.3
Have you

Ruby: a few new packages

---

shells/tcsh/Portfile

tcsh: update to 6.24.12

---

editors/bvi/Portfile

Update
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

bvi: update to 1.4.2

---

math/flint/Portfile

@MarcusCalhoun-Lopez Please review this. (For reasons of switching to autotools see the issues referred.)
macOS 14.4.1 / arm64
Xcode 15.3
macOS 10.6 / ppc
Xcode 3.2
Build conformed on both, test-suite ran on Sonoma.
Have you

flint: update to 3.1.2

---

security/i2pd/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

i2pd: update to 2.51.0

---

ruby/rb-diakonos/Portfile

New port
macOS 14.4.1
Xcode 15.3
Have you

rb-diakonos: new port, Ruby-based CLI editor

---

ocaml/ocaml-js_of_ocaml/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-js_of_ocaml: update to 5.7.2

---

databases/pgpointcloud/Portfile
gis/grass/Portfile
gis/grass/files/04_patch-pdal.diff
gis/pdal/Portfile

- Update `pdal` to 2.7.1 and  add postgresql16 variant
- `pgpointcloud`: add PostgreSQL 16 subport (pg16-pgpointcloud)
- `grass`: fix runtime bug with PDAL 2.7.0+
Have you

pdal: update to 2.7.1, add postgresql16 variant

---

gis/libosmium/Portfile
gis/osmium-tool/Portfile

- Add `libosmium` build dependencies, enable test without +tests variant.
- Remove +tests variant.
- Update build dependency of `proj4` to `proj7`.
- Add new `libosmium-doc` subport.
Have you

libosmium: general overhaul; add libosmium-doc subport

---

emulators/uxn/Portfile

uxn: update to 20240405

---

devel/libxdg-basedir/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libxdg-basedir: update to 1.2.3

---

R/R-nanonext/Portfile
devel/nng/Portfile

Revbumps to fix broken ports.
macOS 10.6
Xcode 3.2
Have you

nng, R-nanonext: revbumps forgotten after mbedtls3 update

---

python/py-awscli2/Portfile

py-awscli2: update to 2.15.37

---

R/R-CGNM/Portfile
R/R-Directional/Portfile
R/R-ape/Portfile
R/R-gpboost/Portfile
R/R-renv/Portfile

Remaning few updates
macOS 10.6
Xcode 3.2
Have you

R: a few remaining updates

---

R/R-symengine/Portfile
math/symengine/Portfile

Revbump after `flint` update
macOS 10.6
Xcode 3.2
Have you

symengine, R-symengine: revbump after flint update

---

lang/ruby-devel/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ruby-devel: update to 2024.04.12

---

science/madness/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

madness: update to 2024.04.10

---

lang/fortran-stdlib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib: update to 2024.04.12

---

math/normaliz/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

normaliz: update to 3.10.2

---

devel/haskell-language-server/Portfile

haskell-language-server: Update to version 2.7.0.0

---

audio/wavpack/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

wavpack: update to 5.7.0

---

audio/dsdcc/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

dsdcc: update to 1.9.5

---

multimedia/mkvtoolnix/Portfile

Add myself as maintainer
Closes: https://trac.macports.org/ticket/62648
Closes: https://trac.macports.org/ticket/65248
Closes: https://trac.macports.org/ticket/67391
Closes: https://trac.macports.org/ticket/68771
Closes: https://trac.macports.org/ticket/69030
macOS x.y
Have you

mkvtoolnix: overhaul & update to 83.0

---

databases/metabase/Portfile

metabase: update to 0.49.5

---

devel/jenkins/Portfile

jenkins: update to 2.440.2

---

x11/xorg-libXres/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

xorg-libXres: update to 1.2.2

---

x11/xorg-libXxf86dga/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

xorg-libXxf86dga: update to 1.1.6

---

x11/xorg-libXmu/Portfile

Update, make portfile more readable.
macOS 10.6
Xcode 3.2
Have you

xorg-libXmu: update to 1.2.0

---

ruby/rb-nokogiri/Portfile

Update
macOS 14.4.1
Xcode 15.3
Have you

rb-nokogiri: update to 1.16.4

---

devel/re-flex/Portfile

re-flex: update to 4.2.1

---

R/R-tiledb/Portfile
databases/tiledb/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

tiledb: update to 2.22.0; R-tiledb: update to 0.26.0

---

python/py-h5py/Portfile
python/py-h5py/files/patch-oldest-supported-numpy.diff

py-h5py: 3.11.0

---

lang/py-htmldocs/Portfile

py-htmldocs: Update to latest

---

gis/saga/Portfile
gis/saga/files/patch-findpostgres-cmake.diff

Update `saga`, `py-pysaga` to version 9.4.0 and add `postgresql16` variant.
macOS x.y
Have you

saga, py-pysaga: update to 9.4.0

---

devel/ninja/Portfile

ninja: update to 1.12.0

---

devel/clavus/Portfile

clavus: submission port in devel

---

net/ejabberd/Portfile

macOS 10.13
Command Line Tools 10.1.0
Have you

ejabberd: update to 24.02

---

lang/cabal/Portfile

cabal: Update to version 3.10.3.0

---

math/gretl/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

gretl: update to 2024a

---

irc/hexchat/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

hexchat: update to 2.16.2

---

devel/tatami/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

tatami-devel: update to 2024.04.10

---

devel/clavus/Portfile

clavus: version update to 1.1.0

---

R/R-BayesMallows/Portfile
R/R-BayesSUR/Portfile
R/R-JointAI/Portfile
R/R-MCCM/Portfile
R/R-NMI/Portfile
R/R-RegKink/Portfile
R/R-Rmisc/Portfile
R/R-SSRA/Portfile
R/R-adbcsqlite/Portfile
R/R-bayesROE/Portfile
R/R-bliss/Portfile
R/R-dst/Portfile
R/R-fastcpd/Portfile
R/R-felp/Portfile
R/R-fixest/Portfile
R/R-future.mirai/Portfile
R/R-future.tests/Portfile
R/R-gplm/Portfile
R/R-mBvs/Portfile
R/R-ngram/Portfile
R/R-nlive/Portfile
R/R-norMmix/Portfile
R/R-oaii/Portfile
R/R-pbANOVA/Portfile
R/R-plsmmLasso/Portfile
R/R-pooh/Portfile
R/R-segen/Portfile
R/R-statGraph/Portfile
R/R-tdcmStan/Portfile
R/R-yodel/Portfile

Few remaining updates and new ports.
macOS 10.6
Xcode 3.2
Have you

R: remaining updates and some new packages

---

devel/n/Portfile

n: update to 9.2.3

---

ocaml/ocaml-syslog/Portfile

ocaml-syslog: new port 2.0.2

---

ocaml/ocaml-bigstringaf/Portfile

ocaml-bigstringaf: new port 0.9.1

---

ocaml/ocaml-jingoo/Portfile

ocaml-jingoo: new port 1.5.0

---

ocaml/ocaml-calendars/Portfile

ocaml-calendars: new port 1.0.0

---

ocaml/ocaml-unidecode/Portfile

ocaml-unidecode: new port 0.4.0

---

graphics/cyan/Portfile
graphics/cyan/files/patch-do-not-hardcode-deployment-target.diff
graphics/cyan/files/patch-libomp.diff
graphics/cyan/files/patch-no-libomp copy.diff

New port
macOS 14.4.1
Xcode 15.3
Have you

cyan: new port in graphics

---

erlang/atomvm/Portfile

atomvm: update to 0.6.1

---

ocaml/ocaml-bos/Portfile

ocaml-bos: new port 0.2.1

---

finance/bitcoin/Portfile

bitcoin: update to 27.0

---

erlang/mochiweb/Portfile
erlang/rebar3/Portfile
erlang/tsung/Portfile
lang/elixir/Portfile
lang/erlang/Portfile

See commits.
macOS 10.6
Xcode 3.2
Have you

erlang: update to 26.2.3; update some Erlang ports

---

sysutils/cdrtools/Portfile

cdrtools: update to 3.02-2024-03-21
* Update codeberg.setup to version 2024-03-21
* Add bison as a build dependency
See: https://trac.macports.org/ticket/69395
Have you

cdrtools: update to 3.02-2024-03-21

---

lang/zig/Portfile

zig: update to 0.12.0

---

sysutils/maestral/Portfile

Update
macOS 14.4.1
Xcode 15.3
Have you

maestral: update to 1.9.3

---

devel/asio/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

asio: update to 1.30.2

---

science/imager/Portfile

imager: update to v4.0-02 (apr24)

---

databases/pxlib/Portfile
gnome/gnumeric/Portfile
gnome/goffice/Portfile
ruby/rb-gnumeric/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

gnumeric: update to 1.12.57; goffice: update to 0.10.57

---

ocaml/ocaml-angstrom/Portfile

ocaml-angstrom: new port 0.16.0

---

ocaml/ocaml-ppx_import/Portfile

ocaml-ppx_import: new port 1.10.0

---

lang/camlp5/Portfile

camlp5: update to 8.02.01

---

editors/ed/Portfile

ed: update to 1.20.2

---

audio/libechonest/Portfile

New port
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

libechonest: new port in audio

---

www/arora/Portfile
www/arora/files/0001-fix-the-problem-in-the-downloadmanager-when-the-dele.patch
www/arora/files/0002-Show-the-number-of-downloads-in-the-download-manager.patch
www/arora/files/0003-Change-the-AutoFillManager-to-not-use-hard-coded-off.patch
www/arora/files/0004-Fixed-ssl-certificate-problem-with-sites-like-https-.patch
www/arora/files/0005-Autofill-webforms-in-Preferences-was-always-checked.patch
www/arora/files/0006-Autofill-manager-was-always-storing-forms.patch
www/arora/files/0007-Support-persistent-data-storage-HTML5-localStorage.patch
www/arora/files/0008-Fix-start-page-not-being-valid-XML-but-claiming-to-b.patch
www/arora/files/0009-Fix-for-fullscreen-on-Mac-issue931.patch
www/arora/files/0010-Fix-xhtml-warning-in-the-startpage.patch
www/arora/files/0011-Work-around-Qt-bug-in-QCompleter-found-in-Qt-4.8.2.patch
www/arora/files/0012-Create-autotest-for-BookmarkNode-class.patch
www/arora/files/0013-Don-t-output-error-when-checking-files-that-have-bee.patch
www/arora/files/0014-Expose-HistoryManager-addHistoryEntry-QString.patch
www/arora/files/0015-Add-unit-tests-for-functionality-that-wasn-t-unit-te.patch
www/arora/files/0016-Move-FrecencyTimer-to-the-HistoryFilterModel.patch
www/arora/files/0017-Fix-segfaults-in-history-manual-test.patch
www/arora/files/0018-Update-README-after-project-has-officially-moved-all.patch

All patches are from the upstream master.
(I only skipped Korean locale ones, since they do not apply cleanly, and not essential anyway.)
macOS 10.6
Xcode 3.2
Have you

arora: update with upstream patches, revbump

---

ocaml/ocaml-uri/Portfile

ocaml-uri: new port 4.4.0

---

ocaml/ocaml-markup/Portfile

ocaml-markup: new port 1.0.3

---

lang/swi-prolog/Portfile

swi-prolog: Updated to version 9.2.4

---

mail/trojita/Portfile
mail/trojita/files/0001-CMakeLists-drop-breaking-flag.patch

New port in mail
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
(Qt4 support is experimental.)
Have you

trojita: new port in mail

---

xfce/exo/Portfile
xfce/garcon/Portfile
xfce/libxfce4ui/Portfile
xfce/libxfce4ui/files/remove-intltool-perl-hack.diff
xfce/libxfce4util/Portfile
xfce/xfconf/Portfile

Update the XFCE libraries.  This is needed to update XFCE applications like Thunar to the latest versions.
Have you

Update XFCE libraries

---

net/i2pchat/Portfile
net/i2pchat/files/patch-qt4.diff

Let provide a version for Qt4.
macOS 10.6
Xcode 3.2
Have you

i2pchat: initial support with Qt4

---

devel/girara/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

girara: update to 0.4.3

---

net/zmap/Portfile

zmap: update to v4.1.0-RC2

---

audio/rnnoise/Portfile
audio/rnnoise/files/patch-372f7b4b76cde4ca1ec4605353dd17898a99de38.diff

Update
macOS 10.6
Xcode 3.2
Have you

rnnoise: update to 0.2

---

math/vampire/Portfile

Long-due update
macOS 10.6
Xcode 3.2
Have you

vampire: update to 2024-04-12

---

lang/MoarVM/Portfile
lang/nqp/Portfile
lang/rakudo/Portfile

Just updates
macOS 10.6
Xcode 3.2
Have you

rakudo & friends: update to 2024.04

---

devel/libmaxminddb/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

libmaxminddb: update to 1.9.1

---

ruby/rb-rexml/Portfile

Non-functional
macOS x.y
Have you

rb-rexml: non-functional: fix license, use https

---

graphics/diff-pdf/Portfile

diff-pdf: update to use wxWidgets-3.2

---

devel/libfilezilla/Portfile
www/FileZilla/Portfile
www/FileZilla/files/patch-fix-fz_datadir.diff
www/FileZilla/files/patch-fix-mac-wxgtk.diff
www/FileZilla/files/patch-relax-wxwidgets-version.diff
www/FileZilla/files/patch-wx3.0.diff

Ok, now with wxGTK-3.0-cxx11 merged, I can fix this.
(Earlier it was building but not launching.)
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you

FileZilla: actually fix it for old systems

---

devel/git/Portfile
devel/git/files/patch-Revert-breaking-osxkeychain.diff

Revert a breakage introduced in 2.45.0 for affected systems (< 10.7).
Also fixes an obscure but annoying failure to extract man with some very old versions of Apple tar.
macOS 10.6
Xcode 3.2
Have you

git-devel: fix osx keychain broken in 2.45.0 for < 10.7

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.3.5

---

graphics/ptex/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ptex: update to 2.4.2

---

graphics/asymptote/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

asymptote: update to 2.89

---

devel/jreleaser/Portfile

jreleaser: update to version v1.12.0

---

security/pam-google-authenticator/Portfile

pam-google-authenticator: Update to 1.10

---

python/py-rubicon-objc/Portfile
python/py-rubicon-objc/files/patch-pyproject.diff

Update
macOS 14.4.1
Xcode 15.3
Have you

py-rubicon-objc: update to 0.4.8

---

ocaml/ocaml-bos/Portfile

ocaml-bos: fix livecheck

---

python/py-awscli2/Portfile

py-awscli2: update to 2.15.43

---

devel/mz-cmaketools/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

mz-cmaketools: update to 2024.04.29

---

lang/ruby-devel/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ruby-devel: update to 2024.05.03

---

devel/starpu/Portfile

macOS-13 CI will fail due to MPICH.
macOS 10.6
Xcode 3.2
Have you

starpu: update to 1.4.5

---

python/fava/Portfile

fava: update to 1.27.3

---

devel/64tass/Portfile

Xcode 15.0.1 / Command Line Tools 15.3.0.0.1.1708646388
Have you

64tass: update to 1.59.3120

---

graphics/openvdb/Portfile
graphics/openvdb/files/patch-libatomic.diff

Fix the build
macOS 10.6
Xcode 3.2
Have you

openvdb: fix build on PowerPC

---

devel/libsdl2-powerpc/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

libsdl2-powerpc: update to 2.30.3

---

emulators/uxn/Portfile

uxn: update to 20240506

---

lang/logtalk/Portfile

logtalk: update to 3.78.0

---

devel/apr-util/Portfile

See: https://trac.macports.org/ticket/43431

apr-util: Remove mysql5 variant

---

net/snac/Portfile

snac: update to 2.52

---

www/nicotine-plus/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

nicotine-plus: update to 3.3.3

---

net/baresip/Portfile
net/libre/Portfile

baresip: update to 3.11.0

---

ruby/rb-bigdecimal/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

rb-bigdecimal: update to 3.1.8

---

math/igraph/Portfile
python/py-igraph/Portfile

igraph: update to 0.10.12

---

x11/imake/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

imake: update to 1.0.10

---

x11/viewres/Portfile

Long due update
macOS 10.6
Xcode 3.2
Have you

viewres: update to 1.0.7

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to 19.27.0

---

net/mqttcli/Portfile

Add a new port for `mqttcli`, a simple commandline MQTT client.
Have you

mqttcli: new port (version 0.2.6)

---

_resources/port1.0/group/rust-1.0.tcl
lang/rust-bootstrap/Portfile

Minor Rust Fixes

---

math/clac/Portfile

clac: new port

---

devel/neocmakelsp/Portfile

neocmakelsp: new port

---

net/nghttp3/Portfile
net/ngtcp2/Portfile

Updates
macOS 10.6
Xcode 3.2
Have you

nghttp3: update to 1.3.0; ngtcp2: update to 1.5.0

---

math/blis/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

blis: update to 1.0

---

lang/ecl/Portfile

lang/ecl: update to 2024 05 10 release

---

python/py-pygmt/Portfile

Update `pygmt` to its latest released version, 0.12.0
Have you

py-pygmt: Update to 0.12.0

---

R/R-tiledb/Portfile
databases/tiledb/Portfile
databases/tiledb/files/patch-do-not-force-VCPKG.diff

Update
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you

tiledb: update to 2.23.0; R-tiledb: update to 0.27.0

---

net/gensync/Portfile

Version update
macOS 13.0.1
Xcode 14.3.1
Have you

gensync:update to 2.1.0

---

graphics/ctlang/Portfile

Also alphabetize stuff and align to multiples of 4.
macOS 10.6
Xcode 3.2
Have you

ctlang: update to 1.5.3, support tests

---

devel/astyle/Portfile

astyle: update to 3.4.15

---

python/py-bcrypt/Portfile

Unbreak the port for systems without Rust.
macOS 10.6
Xcode 3.2
Have you

py-bcrypt: fix for systems without Rust

---

devel/FTXUI/Portfile
devel/git-tui/Portfile
devel/git-tui/files/patch-CmakeLists.diff
devel/subprocess/Portfile
editors/TermME/Portfile
editors/TermME/files/patch-CMakeLists.diff
gnome/notekit/Portfile
gnome/notekit/files/clang-build.patch
gnome/notekit/files/patch-gtk_update_icon_cache.diff
gnome/notekit/files/patch-use-correct-path.diff
tex/MicroTeX/Portfile

New ports
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you

FTXUI and friends (git-tui, TermMe): new ports

---

net/zabbix3/Portfile

See: https://trac.macports.org/ticket/43431

zabbix3: Remove mysql5 variant

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 19.29.0

---

sysutils/coreutils-uutils/Portfile

coreutils-uutils: update to 0.0.26

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.3.6

---

net/softether5/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

softether5: update to 5.02.5184

---

sysutils/bash-completion/Portfile

macOS x.y
Have you
- x ] checked your Portfile with `port lint --nitpick`?

bash-completion: update to 2.14.0

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 19.29.1

---

lang/logtalk/Portfile

logtalk: update to 3.79.0

---

ocaml/ocaml-js_of_ocaml/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-js_of_ocaml: update to 5.8.1

---

net/libretroshare/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libretroshare: update to 2024.05.13

---

R/R-rsparse/Portfile

Checksums fail. Fix that, switch to archive tarball.
macOS 10.6
Xcode 3.2
Have you

R-rsparse: handle stealth update

---

lang/fortran-stdlib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib: update to 2024.05.13

---

sysutils/glances/Portfile
sysutils/glances/files/patch-make-pydantic-optional.diff

@herbygillot This fixes 4.0.4. Is the threshold okay or should be adjusted? I do not know where Rust stuff works on Intel.
macOS 10.6
Xcode 3.2
Have you

glances: unbreak for old systems

---

editors/turbo/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

turbo: update to 2024.05.15

---

lang/nasm/Portfile

nasm: update to 2.16.03

---

devel/kokkos/Portfile

Kokkos update

---

net/snac/Portfile

snac: update to 2.53

---

audio/lastfm-desktop/Portfile
audio/lastfm-desktop/files/0001-Drop-sparkle-and-growl.patch
audio/lastfm-desktop/files/0002-patch-old-systems.diff
audio/lastfm-desktop/files/0003-Compatibility-for-10.5.patch

Let’s see if this builds.
macOS 10.6
Xcode 3.2
Have you

lastfm-desktop: new port

---

math/qalculate-gtk/Portfile

The port needs a revbump after libqalculate update, but rather update it.
macOS 10.6
Xcode 3.2
Have you

qalculate-gtk: update to 5.1.0

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 19.30.0

---

lang/camlp5/Portfile

camlp5: update to 8.03.00

---

sysutils/colima/Portfile

macOS 14.5 23F79 arm64 Xcode 15.3 15E204a
Have you
same change?

colima: Upgrade to 0.6.9

---

print/fondu/Portfile

fondu: fix livecheck

---

audio/qmmp/Portfile
audio/qmmp/files/patch-CMakeLists.diff
audio/qmmp/files/patch-fix-include.diff
audio/qmmp/files/patch-powerpc.diff

New port
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you

qmmp: new port in audio, a Qt-based player

---

devel/oxker/Portfile

https://github.com/mrjackwills/oxker - A simple tui to view & control docker containers.
[![Packaging status](https://repology.org/badge/tiny-repos/oxker.svg)](https://repology.org/project/oxker/versions)
How to run: `oxker --host ~/.docker/run/docker.sock`
Xcode 14.2
Have you

oxker: new port

---

science/ncview/Portfile

macOS 13.6.7
Xcode 15.2 / Command Line Tools 15.2
Have you

ncview: update to v2.1.10

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 19.31.0

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 19.32.0

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 20.0.0

---

ocaml/ocaml-rresult/Portfile

ocaml-rresult: take ownership, fix livecheck and factorize master_sites

---

ocaml/ocaml-ocamlformat/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-ocamlformat: update to 0.26.2

---

lang/libomp/Portfile

libomp: 18.1.6

---

R/R-EMD/Portfile
R/R-LBI/Portfile
R/R-PResiduals/Portfile
R/R-RcppBlaze/Portfile
R/R-bayesMeanScale/Portfile
R/R-bayesian/Portfile
R/R-bbl/Portfile
R/R-bbnet/Portfile
R/R-bindata/Portfile
R/R-calibmsm/Portfile
R/R-cloudfs/Portfile
R/R-convdistr/Portfile
R/R-edstan/Portfile
R/R-evinf/Portfile
R/R-fastcmh/Portfile
R/R-fastkqr/Portfile
R/R-fude/Portfile
R/R-genMCMCDiag/Portfile
R/R-ggeffects/Portfile
R/R-gptr/Portfile
R/R-hht/Portfile
R/R-iGraphMatch/Portfile
R/R-lzstring/Portfile
R/R-multinma/Portfile
R/R-polyMatrix/Portfile
R/R-tinytable/Portfile
R/R-tinytable/files/patch-no-webshot2.diff
R/R-unitizer/Portfile
R/R-yyjsonr/Portfile

Weekend updates and some new ports for R.
macOS 10.6
Xcode 3.2
Have you

R: few updates and some new packages

---

sysutils/albafetch/Portfile
sysutils/albafetch/files/0001-macos_infos.c-fix-for-i386-and-ppc.patch
sysutils/albafetch/files/0002-Fix-Makefile.patch

New port
macOS 10.6
Xcode 3.2
Have you

albafetch: new port in sysutils

---

lang/algol68g/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

algol68g: update to 3.5.2

---

python/py-maxminddb/Portfile

py-maxminddb: update to 2.6.1

---

lang/stack/Portfile

stack: update to 2.15.7

---

databases/postgresql12-doc/Portfile
databases/postgresql12-server/Portfile
databases/postgresql12/Portfile
databases/postgresql13-doc/Portfile
databases/postgresql13-server/Portfile
databases/postgresql13/Portfile
databases/postgresql14-doc/Portfile
databases/postgresql14-server/Portfile
databases/postgresql14/Portfile
databases/postgresql15-doc/Portfile
databases/postgresql15-server/Portfile
databases/postgresql15/Portfile
databases/postgresql16-server/Portfile
databases/postgresql16/Portfile

postgresql16, -server: update to 16.3

---

science/ismrmrd/Portfile

ismrmrd: Revbump for HDF5 (missed).

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 20.0.1

---

devel/evas/Portfile

Fix and minor portfile clean-up.
P. S. I remove a commented-out `--enable-gl-x11`, since it is not recognized by configure with the current version anyway.
macOS 10.6
Xcode 3.2
Have you

evas: fix building on powerpc

---

games/fheroes2/Portfile

fheroes2: update to 1.1.0

---

graphics/MoltenVK/Portfile

MoltenVK: update to 1.2.9

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 20.0.2

---

lang/swi-prolog/Portfile

swi-prolog: Updated to version 9.2.5

---

databases/openldap-devel/Portfile

openldap-devel: update to 2.6.8

---

science/libdicom/Portfile

Does not build with old gcc.
macOS 10.6
Xcode 3.2
Have you

libdicom: blacklist old Xcode gcc to fix build

---

databases/lmdb/Portfile

lmdb: update to 0.9.33

---

sysutils/yabai/Portfile
sysutils/yabai/files/patch-makefile-macos11.diff
sysutils/yabai/files/patch-makefile.diff

Update `yabai` to latest release.
Have you

yabai: update to 7.1.1

---

lang/rust-bootstrap/Portfile
lang/rust/Portfile

rust*: fix setting of configure.sdkroot

---

ruby/rb-arrayfields/Portfile

Update
macOS 14.4.1
Xcode 15.3
Have you

rb-arrayfields: update to 4.9.2

---

devel/mk-configure/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

mk-configure: update to 0.39.0

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 20.2.0

---

sysutils/font-manager/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

font-manager: update to 0.8.9

---

_resources/port1.0/group/crossgcc-1.0.tcl
cross/i686-w64-mingw32-gcc/Portfile
cross/x86_64-w64-mingw32-gcc/Portfile

Also added myself as maintainer as I'm usually the one to upgrade these

*-w64-mingw32-gcc: update to 14.1.0

---

_resources/port1.0/group/crossbinutils-1.0.tcl
cross/i686-w64-mingw32-binutils/Portfile
cross/x86_64-w64-mingw32-binutils/Portfile

Also adding myself as maintainer as I'm usually the one to upgrade these.

*-w64-mingw32-binutils: Update to 2.42

---

gnome/gcr/Portfile
gnome/gcr/files/patch-ui-gcr.pc.in.diff

Update
macOS 10.6
Xcode 3.2
Have you

gcr: update to 3.41.2

---

graphics/MoltenVK/Portfile

closes https://trac.macports.org/ticket/70057

moltenvk: Set lower case for libMoltenVK.a

---

sysutils/initool/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

initool: update to 0.15.0

---

devel/args/Portfile
devel/json-tui/Portfile
devel/json-tui/files/patch-CMakeLists.diff

New ports: json-tui and its dependency args.
macOS 14.5
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

json-tui: new port

---

python/py-nbval/Portfile

py-nbval: Update to version 0.11.0; Add Python 311 312

---

python/py-onnx/Portfile
python/py-onnx/files/patch-pyproject_toml.diff

Depends upon #24096, #24107
macOS x.y
Have you

py-onnx: Update to version 1.16.1

---

devel/re-flex/Portfile

re-flex: update to 4.3.0

---

devel/astyle/Portfile

astyle: update to 3.4.16

---

devel/mk-configure/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

mk-configure: update to 0.39.2

---

emulators/mednafen/Portfile

mednafen: update to 1.32.1

---

lang/swi-prolog-devel/Portfile

swi-prolog-devel: Updated to version 9.3.7

---

fortran/fortran-json/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-json: update to 8.4.0

---

science/cdsclient/Portfile

Update the port.
Presently it does not even extract due to a checksums error.
macOS 10.6
Xcode 3.2
Have you

cdsclient: update to 3.84

---

devel/mk-configure/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

mk-configure: update to 0.39.3

---

ocaml/ocaml-js_of_ocaml/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-js_of_ocaml: update to 5.8.2

---

devel/dagger/Portfile

dagger: update to 0.11.5

---

ruby/rb-diakonos/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

rb-diakonos: update to 0.9.11

---

graphics/mupdf/Portfile
graphics/mupdf/files/patch-Makethird.diff
graphics/mupdf/files/patch-build.diff
python/py-mupdf/Portfile
python/py-mupdf/files/patch-build.diff

Update
Also needed due to `gumbo-parser` update in https://github.com/macports/macports-ports/pull/24110
macOS 10.6
Xcode 3.2
Have you

mupdf: update to 1.24.2

---

graphics/asymptote/Portfile

asymptote: revbump for gsl update

---

sysutils/initool/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

initool: update to 0.17.0

---

devel/starpu/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

starpu: update to 1.4.7

---

R/R-BNSP/Portfile
R/R-BayesVarSel/Portfile
R/R-BayesXsrc/Portfile
R/R-DirichletMultinomial/Portfile
R/R-GeneralizedWendland/Portfile
R/R-QF/Portfile
R/R-RDieHarder/Portfile
R/R-RcppGSL/Portfile
R/R-Rlibeemd/Portfile
R/R-abn/Portfile
R/R-bbl/Portfile
R/R-bnpmr/Portfile
R/R-coga/Portfile
R/R-fRLR/Portfile
R/R-geoCount/Portfile
R/R-gsl/Portfile
R/R-gslnls/Portfile
R/R-libstable4u/Portfile
R/R-libstableR/Portfile
R/R-mBvs/Portfile
R/R-mixture/Portfile
R/R-mlr/Portfile
R/R-monoreg/Portfile
R/R-mvabund/Portfile
R/R-mvst/Portfile
R/R-rtmpt/Portfile
R/R-spaMM/Portfile
R/R-topicmodels/Portfile

Fix packages broken by gsl update
macOS x.y
Have you

R-*: revbump dependents of gsl after its update

---

databases/lmdb/Portfile

lmdb: add livecheck

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 21.0.0

---

databases/tiledb/Portfile
devel/ixion-0.17/Portfile
devel/ixion-0.18/Portfile
devel/libmamba/Portfile
devel/oxen-logging/Portfile
editors/cherrytree/Portfile
net/abaddon/Portfile
sysutils/poac/Portfile

Depends on https://github.com/macports/macports-ports/pull/24205
macOS x.y
Have you

spdlog dependents: revbump

---

erlang/atomvm/Portfile

atomvm: update to 0.6.2

---

net/dnsmasq/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

dnsmasq: update to 2.90

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 21.0.1

---

_resources/port1.0/group/muniversal-1.1.tcl

muniversal PG tweaks

---

net/transmission/Portfile

transmission: add myself as maintainer

---

ruby/rb-numo-gsl/Portfile

This my port also needs a revbump.
macOS x.y
Have you

rb-numo-gsl: revbump for gsl update

---

science/plplot/Portfile

Fix, improve layout
macOS 10.6
Xcode 3.2
Have you

plplot: fix build on old systems, improve portfile readability

---

devel/dagger/Portfile

dagger: update to 0.11.6

---

math/cminpack/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

cminpack: update to 1.3.9

---

lang/lfortran/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

lfortran: update to 0.36.0

---

math/wxMaxima/Portfile
math/wxMaxima/files/patch-no-bundle.diff

Draft, since I am rerunning the build with a minor change. Looks like for GTK version building a bundle is suboptimal.
Verified also on Sonoma aarch64 against wxGTK (which the profile does not do, but yes, that also works).
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.3
Have you

wxMaxima: fix for old systems and powerpc

---

ocaml/ocaml-dune/Portfile

Update Dune and add new subports of it.
macOS 10.6
Xcode 3.2
Have you

ocaml-dune: update to 3.15.3

---

ocaml/ocaml-cmdliner/Portfile
ocaml/ocaml-ppx_deriving/Portfile
ocaml/ocaml-ppxlib/Portfile
ocaml/ocaml-sexplib0/Portfile

Some updates for ocaml ports
macOS 10.6
Xcode 3.2
Have you

ocaml: update a few ports

---

devel/cxxopts/Portfile
sysutils/just-fast/Portfile
sysutils/just-fast/files/patch-CMakeLists.diff

Another port using FTXUI library.
macOS 10.6
Xcode 3.2
Have you

just-fast: new tui port

---

graphics/rgb-tui/Portfile
graphics/rgb-tui/files/patch-CMakeLists.diff

New port
macOS 14.5
Xcode 15.4
Have you

rgb-tui: new port

---

net/yggdrasil-go/Portfile

yggdrasil-go: update to 0.5.6

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 21.1.0

---

fortran/gtk-fortran/Portfile

New port in Fortran
macOS 10.6
Xcode 3.2
Have you

gtk-fortran: new port

---

sysutils/e2fsprogs/Portfile
sysutils/e2fsprogs/files/patch_xlocale_h.diff

e2fsprogs: update to 1.47.1

---

databases/mariadb/Portfile
databases/mariadb/files/patch-powerpc.diff

Did anyone build it for ppc, like ever? )
It is trivially fixable, but without this the code cannot possibly compile, I believe.
macOS 10.6
Xcode 3.2
Have you

mariadb: fix build on powerpc and Sonoma

---

kde/kate/Portfile

kate: fix compiler choice

---

lang/ruby-devel/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ruby-devel: update to 2024.06.03

---

sysutils/just-fast/Portfile

Cannot test, but hopefully works.
macOS x.y
Have you

just-fast: use legacysupport for filesystem with libc++

---

devel/inipp/Portfile

New port 
macOS 14.5
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you

inipp: new port in devel

---

games/bluemoon/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

bluemoon: update to 2.13
