- net/libretroshare/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libretroshare: update to 2024.03.05

- python/py-cattrs/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> py-cattrs: update to 23.2.3, support python312

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.23. [Changelog](https://github.com/astral-sh/uv/releases/tag/0.1.23).
Have you
> uv: Update to 0.1.23

- textproc/yq/Portfile
- textproc/yq/files/mandoc.diff
Partly inspired by the Debian rules, which also include a manual page and the license file. While at it, I also added shell completion and the bundled examples.
I included a patch to suppress an issue where showing the manual which trigger a warning:
$ man yq
This manpage is not compatible with mandoc(1) and might display incorrectly.
macOS x.y
Have you
> yq: documentation & completion

- devel/reproc/Portfile
- devel/reproc/files/patch-gcc13.diff
Backport upstream fix
macOS 10.6
Xcode 3.2
Have you
> reproc: backport upstream patch for gcc13

- games/lpairs2/Portfile
- games/lpairs2/files/patch-uint.diff
Fix building with gcc
macOS 10.6
Xcode 3.2
Have you
> lpairs2: fix build with gcc

- devel/jemalloc/Portfile
Update
macOS 14.4
Xcode 15.3
macOS 10a190
Xcode 3.2
Have you
> jemalloc-devel: update to 2024.03.15

- java/openjdk22-temurin/Portfile
New port for Eclipse Temurin, based on OpenJDK 22.
Have you
> openjdk22-temurin: new submission

- devel/libsdl2-powerpc/Portfile
- devel/libsdl2-powerpc/files/0001-Fixes-for-PowerPC.patch
No need to revbump, this only adds configure args for 10.4.
macOS 10.4.11
Xcode 2.5
Have you
> libsdl2-powerpc: allow building on Tiger

- devel/gl-headers/Portfile
A GStreamer dependency as of 
[1.19.3](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/13ff7f43ec18128ec1dc8abeeae57d236e70a3a0), without this the meson will use the included wrap. Falling back to the wrap could cause issues for older systems.
Version taken from [gl-headers/meson.build](https://gitlab.freedesktop.org/gstreamer/meson-ports/gl-headers/-/blob/master/meson.build?ref_type=heads), commit used was taken from [gl-headers.wrap](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gl-headers.wrap?ref_type=heads)
Have you
> gl-headers: New Portfile

- graphics/gifsicle/Portfile
This one has less stringent TLS requirements so it works on the machine we use to mirror the distfiles.
Closes: https://trac.macports.org/ticket/69565
> gifsicle: Add another master_sites entry

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.461.
Have you
> ipsw: Update to 3.1.461

- gis/JOSM/Portfile
macOS 12.6.7 x86_64
Xcode 14.2
Have you
> josm: update to 19017

- x11/auto-multiple-choice/Portfile
auto-multiple-choice-devel : update to version 1.6.0-git20240317102301
Multiple improvements.
MacPorts 2.9.1
Have you
> auto-multiple-choice-devel : update to version 1.6.0-git20240317102301

- textproc/ebook-tools/Portfile
Fix build on old systems.
macOS 10.6
Xcode 3.2
Have you
> ebook-tools: blacklist old Xcode gcc to fix build on < 10.7

- _resources/port1.0/group/meson-1.0.tcl
https://mesonbuild.com/Installing.html
Using `meson` instead of `ninja` allows the use of `--tags` functionality allowing more granular control of the install target.
macOS 14.4
> meson PG: Use meson for destroot.cmd

- math/coinor-cbc/Portfile
- math/coinor-cbc/files/wimplicit-function-declaration.diff
- math/coinor-cgl/Portfile
- math/coinor-cgl/files/wimplicit-function-declaration.diff
- math/coinor-clp/Portfile
- math/coinor-clp/files/wimplicit-function-declaration.diff
- math/coinor-coinutils/Portfile
- math/coinor-coinutils/files/wimplicit-function-declaration.diff
- math/coinor-osi/Portfile
- math/coinor-osi/files/wimplicit-function-declaration.diff
This adds the ports coinor-cbc, coinor-cgl, coinor-clp, coinor-coinutils, and coinor-osi, which are all packages for one or another optimisation problem.
I have two open questions:
- Is `math` the correct category or should it be science? I noticed there is a `science/coinor-liblemon` package, but all in all I see these `coinor` packages more in the direction of `eigen`, `lapack`, and `scip` who live in the `math` category. If you'd prefer them in `science`, however, I will of course move them there.
- There are some "optional" and "recommended" dependencies to those packages. What is the guideline here? Should these all be variants? If so, should the default variant be to include all capabilities, so that other ports can easily depend on them?
macOS 13.6.4 22G513 arm64 …
> coinor-(cbc,cgl,clp,coinutils,osi): new ports

- lang/libomp/Portfile
Fixes https://trac.macports.org/ticket/69557
> libomp: grab ompx.h from temporary install loc.

- net/sslh/Portfile
Archaic gcc does not build this now. Blacklist it, fix the build.
macOS 10.6
Xcode 3.2
Have you
> sslh: fix build on < 10.7

- lang/ruby/Portfile
- lang/ruby/files/conversion.patch
These warnings have become errors as of Xcode 15.3.
> ruby: fix type conversion errors

- python/py-ezdxf/Portfile
This adds the python package `ezdxf` which offers functionality to read, create, manipulate, and export dxf files.
macOS 13.6.4 22G513 arm64
Have you
> py-ezdxf: new port

- java/micronaut/Portfile
Update to Micronaut Starter 4.3.7, and limit lines in Portfile to 80 columns where possible.
Have you
> micronaut: update to 4.3.7

- aqua/kitty/Portfile
- aqua/kitty/files/patch-kitty-incorrect-prefix-in-arm-neon-vshrn-intrinsic.diff
Building Kitty on MacOS 14.4 with Xcode 15 fails in error due to implicit function declaration. The error caused by the [vshrn_n_u16](https://developer.arm.com/architectures/instruction-sets/intrinsics/vshrn_n_u16) ARM NEON intrinsic having an incorrect `simde_ `prefix in [kitty/simd-string-impl.h](https://github.com/kovidgoyal/kitty/blob/a0aba4da4a338585c4e6f3d1abba9d53a1efafd4/kitty/simd-string-impl.h#L244) causing simde_vshrn_n_u16() to be seen as an undeclared function in Clang 15, where the `-Wimplicit-function-declaration` warning diagnostic defaults to an error in C99 and later:
```
In file included from kitty/simd-string-128.c:9:
kitty/simd-string-impl.h:244:27: error: call to undeclared function 'simde_vshrn_n_u16'; ISO C99 and later do not support implicit function declarations …
```
> kitty: Fix build error with Clang 15

- devel/cpp-argparse-dev/Portfile
* Fix: memory leak & update smart ptrs for C++98
macOS 13.6.5 22G621 x86_64
Have you
> cpp-argparse-dev: update to v1.9.2

- textproc/pandoc/Portfile
* Fixes: https://trac.macports.org/ticket/69529
macOS x.y
Have you
> pandoc: Add texlive variant for LaTeX dependencies

- net/lftp/Portfile
Fix build on old systems
macOS 10.6
Xcode 3.2
Have you
> lftp: avoid old Xcode gcc4

- _resources/port1.0/group/octave-1.0.tcl
- math/octave/Portfile
- math/octave/files/patch-run-octave-libstdcpp.diff
This PR fixes Octave 9.1.0 for PowerPC.
macOS 10.6
Xcode 3.2
Have you
> Octave: fix build on PowerPC systems

- devel/libdiscid/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libdiscid: update to 0.6.4

- graphics/graphviz-devel/Portfile
- graphics/graphviz/Portfile
Graphviz commit b517af6738b5900b10dd5397a918760d6c14f76f removed the offending file quoted in the comment here. This commit made it into Graphviz 4.0.0, so this suppression should no longer be required.
I do not have a macOS environment in which to test this. I am just one of the upstream Graphviz maintainers who noticed this in driving by.
Have you
> graphviz-devel: remove Clang '_Nullable' work around

- sysutils/simplotask/Portfile
macOS 12.7.1 x86_64
Xcode 14.2
Have you
> simplotask: update to 1.14.1

- gis/GPXSee/Portfile
> GPXSee: update to 13.18

- devel/libimobiledevice-glue/Portfile
Update the devel subport of `libimobiledevice-glue` to its latest pushed commit. The devel subport correctly conflicts with the normal port.
Sidenote: MacPorts might want to reconsider re-caching the release tarball for `libimobiledevice-glue`, as there was [a bug that made the port fail to build on OS X 10.8 and below to 10.6](https://github.com/libimobiledevice/libimobiledevice-glue/issues/42). This can also be done if rightful to update the `revision` field.
Have you
> libimobiledevice-glue-devel: Update to latest commit

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.8.14

- net/gtk-gnutella/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> gtk-gnutella: update to 2024.03.05

- archivers/libdeflate/Portfile
Archaic compilers are not supported anymore, see: https://github.com/ebiggers/libdeflate/commit/a83fb24e1cb0ec6b6fd53446c941013edf055192
macOS x.y
Have you
> libdeflate: fix build on older systems

- net/ipfs/Portfile
> ipfs: update to 0.27.0

- net/gallery-dl/Portfile
gallery-dl: update to 1.26.9
Have you
> gallery-dl: update to 1.26.9

- gnome/gjs-devel/Portfile
* Update to 1.80.1.
* Avoids typedef problem in 1.79.3 through 1.80.0, was fixed upstream.
Closes https://trac.macports.org/ticket/69549
CI only.  Mac OS 11, 12, 13, 14.
Have you
> gjs-devel: Update to 1.80.1

- sysutils/borgmatic/Portfile
> borgmatic: Update to 1.8.8, use Python 3.12

- net/tcp_wrappers/Portfile
- net/tcp_wrappers/files/patch-no-return-type.diff
No revbump because it either builds correctly, or not at all.
Have you
> tcp_wrappers: Fix -Wimplicit-int errors

- net/tlrc/Portfile
Update `tlrc` to its latest released update, 1.9.0. [Changelog](https://github.com/tldr-pages/tlrc/releases/tag/v1.9.0).
Have you
> tlrc: Update to 1.9.0

- python/py-svgpath/Portfile
This adds the python package `svg.path` which offers functionality to parse, manipulate, and work with SVG path objects.
macOS 13.6.4 22G513 arm64
Have you
> py-svgpath: new port

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 470.0.0.
Have you
> google-cloud-sdk: update to 470.0.0

- archivers/libdeflate/Portfile
* Fix Apple clang version numbering in blacklisting.
* Applies for recent update to libdeflate 1.20.
* Per suggestion in the following ticket, comment no. 1.
* Closes https://trac.macports.org/ticket/69600
CI only.  OS 11, 12, 13, 14 only.
Testing for the targets OS 10.7 through 10.10 is deferred to builders.
Have you
> libdeflate: Fix builds for 10.7-10.10

- editors/lite-xl/Portfile
Fix building on < 10.7
macOS 10.6
Xcode 3.2
Have you
> lite-xl: allow building on < 10.7

- python/py-virtualenv-clone/Portfile
- python/py-virtualenv-clone/files/virtualenv-clone312
- python/py-virtualenv-clone/virtualenv-clone312
- python/py-virtualenvwrapper/Portfile
- python/py-virtualenvwrapper/files/virtualenvwrapper312
Notable improvements: compatibility with python 3.12, and thus it is now possible to have py312-virtualenvwrapper.
Reference: [​https://github.com/python-virtualenvwrapper/virtualenvwrapper/releases/tag/6.0.0](https://github.com/python-virtualenvwrapper/virtualenvwrapper/releases/tag/6.0.0)
See here for more details: https://trac.macports.org/ticket/69090
> py-virtualenvwrapper: Update to 6.0.0

- gnome/libsecret/Portfile
- gnome/libsecret/files/patch-meson-dylib-versions.diff
This will require revbumping dependents.
@mascguy How should we do this? CI for revbumping will fail, since there are several WebKit versions etc.
UPD. Well, we could just do a follow-up revbump for all dependents then.
macOS 10.6
Xcode 3.2
Have you
> libsecret: update to 0.20.5

- python/py-mac-alias/Portfile
New port required as a dependency to update `osxphotos` to the latest version. I'll create a follow-up PR for that.
Have you
> py-mac-alias: new submission

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.462. Newly specified dependencies enable extra features that should be enabled by default (such as the [`pongo`](https://blacktop.github.io/ipsw/docs/guides/pongo) command).
Have you
> ipsw: Update to 3.1.462

- gnome/gtk3-devel/Portfile
- gnome/gtk3-devel/files/patch-tests-gdkgears.diff
Update -devel port to the current version
macOS 14.4
Xcode 15.3
macOS 10.8.5
Xcode 5.1.1
macOS 10.6.8
Xcode 3.2.6
macOS 10a190
Xcode 3.2
Have you
> gtk3-devel: update to 3.24.41

- math/SuiteSparse/Portfile
> SuiteSparse: update to 7.6.1

- net/wget/Portfile
Standard fix for a common problem.
macOS 10.6
Xcode 3.2
Have you
> wget: use legacysupport.redirect_bins to fix malloc errors with libstdc++

- python/py-vobject/Portfile
- textproc/translate-toolkit/Portfile
- update translate-toolkit to its latest upstream version and use Python 3.12
Please note, there are many [optional dependencies](https://github.com/translate/translate/blob/master/requirements/optional.txt) that could be included but only the ones that were originally there are kept.
- also update `py-vobject` and its subports
Have you
> translate-toolkit: update to 3.12.2, use Python 3.12

- gnome/gjs-devel/Portfile
* Update 1.80.1 --> 1.80.2
* Also test very recent dependency fixes, in particular rust and libdeflate.
CI only.  macOS 11, 12, 13, 14 only.
Waiting to test earlier OS on builders.
Have you
> gjs-devel: Update to 1.80.2

- x11/Hypr/Portfile
Based on logs from buildbots, it needs support for filesystem in libc++: https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/226008/steps/install-port/logs/stdio
Cannot test this now, but hopefully it fixes the issue.
(With `libstdc++` it builds fine on 10.6.)
No revbump needed, on affected systems it failed to build.
macOS x.y
Have you
> Hypr: use legacysupport for filesystem

- security/libressl/Portfile
> libressl: update to 3.9.1

- graphics/osxphotos/Portfile
Update to osxphotos 0.67.9.
Have you
> osxphotos: update to 0.67.9

- net/mbusd/Portfile
https://github.com/3cky/mbusd/releases/tag/v0.5.2
Xcode 14.2
Have you
> mbusd: update to 0.5.2

- science/gnuastro/Portfile
- science/gnuastro/files/patch-buildjobs.diff
[Changelog](https://git.savannah.gnu.org/cgit/gnuastro.git/plain/NEWS?id=gnuastro_v0.22)
Xcode 14.2
Have you
> gnuastro: update to 0.22

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.52.0

- devel/ghidra/Portfile
update ghidra to 11.0.2
Have you
> ghidra: update to 11.0.2

- net/tlrc/Portfile
Update `tlrc` to its latest released version, 1.9.1.
Have you
> tlrc: Update to 1.9.1

- multimedia/VLC2/Portfile
A quick fix for 10.10, where Xcode clang fails.
10.9 is okay since uses Clang-16.
https://ports.macports.org/port/VLC2/details
Cannot test it, but presumably it should work.
macOS x.y
Have you
> VLC2: fix build on 10.10

- net/miniupnpc/Portfile
This package is a dependency of bitcoin (both the port and for people compiling bitcoin core by themselves). This is not a critical update, but it's important to keep the ports up to date. In this regard, I added myself as a maintainer (together with the openmaintainer flag).
Have you
> miniupnpc: Update to 2.2.7

- multimedia/VLC2/Portfile
Fixes: https://trac.macports.org/ticket/69625
Follow-up fix, see the ticket.
macOS x.y
Have you
> VLC2: add dependency on xz, revbump

- science/gildas/Portfile
- science/gildas/files/astro.in
- science/gildas/files/class.in
- science/gildas/files/clic.in
- science/gildas/files/cube.in
- science/gildas/files/greg.in
- science/gildas/files/imager.in
- science/gildas/files/mapping.in
- science/gildas/files/mira.in
- science/gildas/files/mrtcal.in
- science/gildas/files/sched-30m.in
- science/gildas/files/sic.in
This fixes [installation issues](https://trac.macports.org/ticket/69564) under macOS 10.15 and earlier.
Note: the patch is generic to work under under pre- and post- 10.15 macOS versions.
Have you
> Gildas: fixed installation under macOS 10.15 and earlier

- lang/lua/Portfile
Closes: https://trac.macports.org/ticket/67799
Fix building on 32-bit archs.
macOS 10.6.8
Xcode 3.2.6
Have you
> lua54: fix 32-bit build

- devel/libusbmuxd/Portfile
Update `libusbmuxd` to its latest released version, 2.1.0. [Changelog](https://github.com/libimobiledevice/libusbmuxd/releases/tag/2.1.0).
Have you
> libusbmuxd: Update to 2.1.0

- devel/libimobiledevice/Portfile
A new update to `libusbmuxd` was introduced in #23285. Without this revision bump, this port remains broken with `libusbmuxd` [due to a new soversion](https://github.com/libimobiledevice/libusbmuxd/commit/499fb0c4e25ba1eb82607ca3f6c6f5a2510b9b53); the port correctly uses the `openssl` PortGroup to link with said library.
Have you
> libimobiledevice: Revision bump (libusbmuxd 2.1.0)

- lang/gcc12/Portfile
- lang/gcc12/files/patch-avoid-over-poisoning.diff
- lang/gcc13/Portfile
- lang/gcc13/files/patch-avoid-over-poisoning.diff
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111632
No revbump since ports build correctly or not at all.
macOS x.y
Have you
> gcc12, gcc13: fix build with recent libc++

- archivers/libarchive/Portfile
- archivers/libarchive/files/patch-use-correct-errno.patch
An echo of the xz backdoor drama: https://github.com/libarchive/libarchive/pull/1609
Have you
> libarchive: backport upstream fix

- net/toxic/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
> toxic: update to 0.15.1

- java/spring-boot-cli/Portfile
Update to Spring Boot 3.2.4.
Have you
> spring-boot-cli: update to 3.2.4

- graphics/osxphotos/Portfile
Update to osxphotos 0.67.10.
Have you
> osxphotos: update to 0.67.10

- devel/editorconfig-core-c/Portfile
Update `editorconfig-core-c` to its latest released version, 0.12.7. [Changelog](https://github.com/editorconfig/editorconfig-core-c/blob/v0.12.7/CHANGELOG).
Have you
> editorconfig-core-c: Update to 0.12.7

- python/py-lxml/Portfile
[skip ci]
Skipping CI, the fix is inconsequential for systems using Clangs, since only old Xcode gccs are blacklisted.
macOS 10.6
Xcode 3.2
Have you
> py-lxml: avoid old Xcode gcc, which cannot build this anymore

- devel/pkgconf/Portfile
Update `pkgconf` to its latest released version, 2.2.0.
Have you
> pkgconf: Update to 2.2.0

- gnome/gspell/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
> gspell: update to 1.12.2

- x11/xorg-xcb-util-cursor/Portfile
Update.
Make lint happy.
Also fix build on 10.6, where old Xcode clang cannot build this just like gcc-4.2 (same error).
macOS 10.6.8
Xcode 3.2.6
Have you
> xorg-xcb-util-cursor: update to 0.1.4

- net/libnatpmp/Portfile
- net/libnatpmp/files/makefile.diff
libnatpmp is a dependency for bitcoin core for folks that are building from source. The current bitcoin port does not support libnatpmp. This port opens the possibility of adding a new feature to the bitcoin port.
Have you
Bitcoin Core v26 was successfully compiled from source and tested with the library provided by this port.
> libnatpmp: new port in net

- news/pan2/Portfile
build now uses cmake
autotools is deprecated
macOS 12.7 21G816 x86_64
Have you
both quartz and x11 work OK.
Run this past CI for assessment.
> pan2: update to 0.157

- lang/lfortran/Portfile
- lang/lfortran/files/patch-stacktrace.cpp-add-limits.h-for-PATH_MAX.diff
- lang/lfortran/files/patch-use-sane-install-dirs.diff
Update
macOS 10.6
Xcode 3.2
Have you
> lfortran: update to 0.34.0

- math/SuiteSparse/Portfile
- Update to 7.7.0
- Reorder subports alphabetically so that it's easier to check versions during update
Have you
> SuiteSparse: update to 7.7.0

- .github/workflows/main.yml
While this will use more resources for changes with build problems, it is often useful to be able to see if something is only failing on a subset of platforms.
> CI: disable fail-fast

- net/syncthing/Portfile
update syncthing  to v1.27.5
Have you
> syncthing: update to v1.27.5

- math/igraph/Portfile
> igraph: update to 0.10.11

- devel/virtuoso-7/Portfile
macOS 14.4.1
Xcode 15.3 / Command Line Tools 15.3
Have you
> virtuoso-7: Fix compilation problems on macOS 14.4

- devel/cpp-peglib/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> cpp-peglib: update to 1.8.8

- graphics/img2pdf/Portfile
img2pdf: added Python 3.12 variant
Have you
> img2pdf: added Python 3.12 variant

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 471.0.0.
Have you
> google-cloud-sdk: update to 471.0.0

- python/py-deprecated/Portfile
py-deprecated: added python 3.12 subport
Have you
> py-deprecated: added python 3.12 subport

- multimedia/QMPlay2/Portfile
Update
macOS 14.4.1
Xcode 15.3
Have you
> QMPlay2: update to 24.04.02

- fuse/macfuse/Portfile
> macfuse: update to 4.6.2

- sysutils/htop/Portfile
When libunwind is installed, htop automatically detects and links against it, without declaring a dependency. Avoid this by explicitly disabling unwind support.
Closes: #23292
with libunwind installed
Have you
> htop: Do not opportunistically link libunwind

- security/ipsw/Portfile
Update `ipsw` to its latest released verison, 3.1.464.
Have you
> ipsw: Update to 3.1.464

- math/R/Portfile
`xz` has been recently downgraded to an earlier version, and not all dependents were revbumped. On 10.8 I get this now:
```
Incompatible library version: /opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/lib/libR.dylib requires version 12.0.0 or later, but /opt/local/lib/liblzma.5.dylib provides version 10.0.0
```
It may be that `R` links to `liblzma` only for newer MacOS, since I did not have a breakage on PowerPC, however to be on a safe side just revbump for all.
macOS x.y
Have you
> R: revbump after xz downgrade

- textproc/most/Portfile
Upgrades `most` to the most recent version from https://www.jedsoft.org/releases/most/
update
Have you
> most: update to 5.2.0

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.13.1.
Have you
> gitu: Update to 0.13.1

- devel/tree-sitter-bash/Portfile
- devel/tree-sitter-cpp/Portfile
- devel/tree-sitter-elixir/Portfile
- devel/tree-sitter-html/Portfile
- devel/tree-sitter-javascript/Portfile
- devel/tree-sitter-markdown/Portfile
- devel/tree-sitter-php/Portfile
- devel/tree-sitter-ruby/Portfile
- devel/tree-sitter-scala/Portfile
- devel/tree-sitter-tsx/Portfile
- devel/tree-sitter-typescript/Portfile
Fix the port on systems using Xcode gcc.
macOS 10.6.8
Xcode 3.2.6
Have you
> tree-sitter-*: fix build on systems using gcc-4.2

- python/py-pikepdf/Portfile
- per the upstream pyproject.toml, py-deprecated is a required (and missing from the portfile) dependency. (cf. https://github.com/pikepdf/pikepdf/blob/7f3c540f4904a19cec4363bbd13e93085ee5b72d/pyproject.toml#L29)
- the missing py-deprecated module is causing errors when using OCRmyPDF (#23347)
Have you
> py-pikepdf: added missing dependency

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.29. [Changelog](https://github.com/astral-sh/uv/releases/tag/0.1.29)
This update was halted as it required Rust 1.76.0 since 0.1.24, which was proposed and merged in #23232.
Have you
> uv: Update to 0.1.29

- sysutils/ipatool/Portfile
Add `ipsw`, [a CLI that allows searching and downloading app packages from the iOS App Store](https://github.com/majd/ipatool)
Have you
> ipatool: new port (2.1.4)

- textproc/ocrmypdf/Portfile
Adding OCRmyPDF, a tool that extends tesseract to create PDFs with searchable text.
depends on py-deprecated getting python 3.12 support as in #23346  
Have you
> OCRmyPDF: new port

- devel/tree-sitter-cpp/Portfile
@amake Please take a look.
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-cpp: require C11 to fix build on old systems

- devel/skaffold/Portfile
Update to Skaffold 2.11.0.
Have you
> skaffold: update to 2.11.0

- devel/safeclib/Portfile
Fix the build on older systems.
macOS 10.6
Xcode 3.2
Have you
> safeclib: fix compiler choice: thread_local_storage required

- mail/imapsync/Portfile
Update imapsync to 2.264.
Have you
> imapsync: update to 2.264

- devel/xdispatch2/Portfile
> xdispatch2: non-functional: fix a typo

- databases/tiledb/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> tiledb: update to 2.21.2

- gnome/gstreamer1-gst-libav/Portfile
Removed unnecessary dependencies.
Also fix build for other platforms.
macOS 14.4.1
Xcode 15.3
> gstreamer1-gst-libav: Remove unnecessary deps

- audio/xmp/Portfile
```
10:~ svacchanda$ file /opt/local/lib/libxmp.4.dylib
/opt/local/lib/libxmp.4.dylib: Mach-O universal binary with 2 architectures
/opt/local/lib/libxmp.4.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/opt/local/lib/libxmp.4.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
10:~ svacchanda$ port -v installed libxmp 
The following ports are currently installed:
libxmp @4.6.0_0+universal (active) requested_variants='+universal' platform='darwin 12' archs='i386 x86_64' date='2024-04-05T04:41:31+0800'
```
```
10:~ svacchanda$ file /opt/local/bin/xmp
/opt/local/bin/xmp: Mach-O universal binary with 2 architectures
/opt/local/bin/xmp (for architecture x86_64):	Mach-O 64-bit executable x86_64
/opt/local/bin/xmp (for …
```
> xmp: allow universal

- net/i2pchat/Portfile
- net/i2pchat/files/0001-Patch-gitversion.pri.patch
New port, messenger over i2p.
At the moment, only Qt5 version, but Qt4 support is considered.
macOS 14.4.1
Xcode 15.3
Have you
> i2pchat: new port in net

- lang/luajit/Portfile
- Update to commit [d06beb048](https://github.com/LuaJIT/LuaJIT/commit/d06beb0480c5d1eb53b3343e78063950275aa281) of 2024-03-10 (still branch 2.1)
- Add PortGroup muniversal to support variant `+universal`
- Closes: https://trac.macports.org/ticket/41304
Have you
> luajit: Update to commit d06beb048 and support universal variant

- audio/nrsc5/Portfile
Fixes https://trac.macports.org/ticket/67860 by adding missing port dependencies. This also stops the build from downloading and building additional libraries.
Have you
> Maintainer fixed https://trac.macports.org/ticket/67860

- security/ipsw/Portfile
Update `ipsw` to its latest released verison, 3.1.468. [Changelog](https://github.com/blacktop/ipsw/compare/v3.1.464...v3.1.468)
Have you
> ipsw: Update to 3.1.468

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.14.0
Have you
> gitu: Update to 0.14.0

- devel/tree-sitter-rust/Portfile
And now this one needs C99 too.
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-rust: fix build for older systems, needs C99

- graphics/opencolorio/Portfile
- remove circular dependency on openimageio
- use python 3.12
- fix symlinks
Have you
> opencolorio: update to 2.3.2

- graphics/ImageMagick7/files/Color.cpp.patch
Fixes the installation of the port by aligning a type in the port's patch with the upstream.
fixes: https://trac.macports.org/ticket/69692
Not tested, just copied the line with a proper type from the upstream to the patch.
Have you
> ImageMagick7: fix port installation&build

- multimedia/libass/Portfile
Update
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you
> libass-devel: update to 2024.04.08

- science/gildas/Portfile
> Gildas: update to 202404a

- devel/openssl3/Portfile
- devel/openssl3/files/7e4d731b1c07201ad9374c1cd9ac5263bdf35bce.patch
- devel/openssl3/files/e9d7083e241670332e0443da0f0d4ffb52829f08.patch
See https://www.openssl.org/news/secadv/20240408.txt for the upstream advisory.
No revbump because there's no ABI change.
CVE: CVE-2024-2511
Have you
> openssl3: Fix CVE-2024-2511

- devel/libgit2-devel/Portfile
- devel/libgit2-devel/files/0001-process.c-fix-environ-for-macOS.patch
Fix environ for macOS
macOS 10.6
Xcode 3.2
Have you
> libgit2-devel: fix environ, unbreak the build on < 10.8

- sysutils/stow/Portfile
Update `stow` to its latest released version, 2.4.0, while claiming maintainer role.
Have you
> stow: Update to 2.4.0

- irc/weechat/Portfile
weechat: update to 4.2.2
macOS 12.7.4 21H1123 arm64
Have you
> weechat: update to 4.2.2

- python/buku/Portfile
buku: update to 4.9, clean up Portfile
* Remove github PortGroup and fetch packages from PyPI instead
* Add supported Python versions (3.8 to 3.12)
* Remove explicitly set Python default version (was: 3.9) and use MacPorts's default instead (currently: 3.12)
* Move port from folder `www` to `python`, and append the `www` category
macOS 12.7.4 21H1123 arm64
Have you
> buku: update to 4.9, clean up Portfile

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.469. [Changelog](https://github.com/blacktop/ipsw/releases/tag/v3.1.469)
Have you
> ipsw: Update to 3.1.469

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.31. [Changelog](https://github.com/astral-sh/uv/compare/0.1.29...0.1.31)
Have you
> uv: Update to 0.1.31

- emulators/advancemame/Portfile
Fix build on old systems.
macOS 10.6
Xcode 3.2
Have you
> advancemame: do not use old Xcode gcc

- science/nco/Portfile
Simple update to upstream version 5.2.3
Have you
> nco: update to 5.2.3

- graphics/openvdb/Portfile
- use onetbb
- add python312
Have you
> openvdb: update to 11.0.0

- irc/epic4/Portfile
Use MacPorts tcl and perl
macOS 12.7.2 21G1974 x86_64
Have you
> epic4: Use MacPorts tcl and perl

- multimedia/QMPlay2/Portfile
Update
macOS 14.4.1
Xcode 15.3
Have you
> QMPlay2: update to 24.04.07

- graphics/oofcanvas/Portfile
- science/oof2/Portfile
Upgrade oof2 to version 2.3.3 and oofcanvas to version 1.1.2.
Have you
> Upgrade oof2 to 2.3.3 and oofcanvas to 1.1.2

- devel/mbedtls3/Portfile
- devel/mbedtls3/files/patch-Fix-compilation-of-ssl_tls13_generic.c-when-memcpy-i.diff
Closes: https://trac.macports.org/ticket/69624
Fix this
macOS 10.6
Xcode 3.2
Have you
> mbedtls3: backport upstream fix for builds on < 10.13

- lang/groovy/Portfile
Update to Groovy 4.0.21.
Have you
> groovy: update to 4.0.21

- python/buku/Portfile
buku: set Python default version to 3.12
macOS 12.7.4 21H1123 arm64
Have you
> buku: set Python default version to 3.12

- devel/libnfs/Portfile
- devel/libnfs/files/0001-Fix-for-older-macOS-include-sys-socket.h-before-net-.patch
Fixes: https://trac.macports.org/ticket/69724
Fix headers for < 10.9
macOS 10.6
Xcode 3.2
Have you
> libnfs: fix for < 10.9

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.15.0
Have you
> gitu: Update to 0.15.0

- science/ecCodes/Portfile
Simple update to upstream version 2.35.0
Have you
> ecCodes: update to 2.35.0

- science/cdo/Portfile
This is an update to upstream version 2.4.0 of cdo.
The new version of cdo switched to C++20 standards, which are supposedly supported by MacOS12 but fails to compile when including make_heap.h. Therefore I introduced a `compiler.blacklist` to allow only C++20 compatible compilers.
En passant, I changed the build dependency from Python 3.11 to 3.12 (used for test only, but checked at build stage irrespectively). In addition, after sending in so many PRs for this package, I finally added myself as maintainer. 
This makes PR #22907 obsolete.
Have you
> cdo: update to 2.4.0

- sysutils/podman/Portfile
See
- https://trac.macports.org/ticket/69683
- https://github.com/crc-org/vfkit/issues/125
macOS x.y
Have you
> podman: workaround for macOS 11 and below

- multimedia/libmtp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libmtp: update to 1.1.21

- net/libretroshare/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libretroshare: update to 2024.04.01

- www/lighttpd/Portfile
> lighttpd: Update to 1.4.76

- math/antic/Portfile
See: https://github.com/flintlib/antic/issues/83
Retire the port
macOS x.y
Have you
> antic: retire the port (it got merged into flint)

- audio/mpg123/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> mpg123: update to 1.32.6

- audio/libopenmpt/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libopenmpt: update to 0.7.6

- audio/libdca/Portfile
Update
macOS 14.4.1
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you
> libdca: update to 0.0.7

- devel/reuse/Portfile
* Using Python is updated to 3.12.
* Dependency on requests is removed on 1.1.0.
* urllib.request is used and CA certs are required.
Have you
> reuse: update to 3.0.2

- erlang/atomvm/Portfile
Due to a recent mbedtls3 update, revbump is required. However, going from 0.6.0-beta.1 to 0.6.0 is seen as a version downgrade by Macports, and revbumping does not solve that. Instead, bump epoch, solves both issues.
Bump epoch.
macOS 10.6
Xcode 3.2
Have you
> atomvm: bump epoch due to unrecognized update and mbedtls3 API change

- gis/pgrouting/Portfile
Adds `perl5` to build dependency for `pg[NN]-pgrouting`. On older systems the system Perl version is too old to build and causes build failure.
Closes https://trac.macports.org/ticket/69659
macOS x.y
Have you
> pg[NN]-pgrouting: add perl5 build dependency

- devel/hyprlang/Portfile
- devel/hyprlang/files/0001-config.cpp-fix-environ-for-Apple.patch
New port
macOS 14.4
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you
> hyprlang: new port in devel

- devel/openssl3/Portfile
The previous change added patchfiles for both 3.2.1 and 3.1.5, but neglected to revbump 3.1.5.
TESTED:
Built and ran simple checks on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.  All variants tested except 10.4 ppc +universal, which doesn't build due to dependency issues. Did not include 'port test', since it has issues on some platforms.
```
OS X 10.8.5 12F2560, x86_64, Xcode …
```
> openssl3: Add missing revbump for 3.1.5

- textproc/ocrmypdf/Portfile
per an email i received on 2024-04-07, adding in variants for python 3.10 and 3.11. 3.12 remains the default.
Have you
> OCRmyPDF: add in variants for python 3.10 and 3.11 per request.

- python/pipx/Portfile
pipx: update to 1.5.0
Have you
> pipx: update to 1.5.0

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.8.15

- graphics/MoltenVK/Portfile
Making `MoltenVK` stub `noarch` resolves issues when `MoltenVK +universal` is called on Apple Silicon.
> MoltenVK: Make the stub noarch

- graphics/libpixman-devel/Portfile
- graphics/libpixman/Portfile
I've applied @kencu's patch for https://trac.macports.org/ticket/68473 found at https://trac.macports.org/ticket/69385 such that libpixman can build and be used by other ports on Leopard PPC.
macOS 10.5 9A581 Power Macintosh
Xcode 3.1.4 9M2809
Have you
> libpixman/libpixman-devel: fix ppc build failure

- devel/libdispatch-legacy/Portfile
- devel/libdispatch-legacy/files/patch-no-crashreporter_info.diff
- devel/libdispatch-legacy/files/patch-pthread-overcommit.diff
Minor fixes allowing other ports to use `libdispatch`.
This port is only relevant for archaic macOS versions, primarily powerpc. It is restricted to old systems.
macOS 10.6
Xcode 3.2
Have you
> libdispatch-legacy: minor fix-ups

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.16.0.
Have you
> gitu: Update to 0.16.0

- x11/xorg-libXvMC/Portfile
- x11/xorg-libXvMC/files/patch-fix-install-ext-headers.diff
Update
macOS 10.6
Xcode 3.2
Have you
> xorg-libXvMC: update to 1.0.14

- x11/xorg-libxshmfence/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> xorg-libxshmfence: update to 1.3.2

- devel/gitui/Portfile
https://github.com/extrawurst/gitui/releases
Xcode 14.2
Have you
> gitui: update to 0.26.1

- audio/portaudio/Portfile
- science/gqrx/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> portaudio: update to 20240308

- archivers/draco/Portfile
Draco transcoder support requires C++ 2017 standard from version 1.5.7.
Closes https://trac.macports.org/ticket/69719
Have you
> draco: specify C++17 is needed

- archivers/draco/Portfile
- archivers/draco/files/patch-draco-targets-cmake.diff
Apply patch to not use the linker flags -start-group and --end-group on macOS systems, as [noted by Ryan](https://trac.macports.org/ticket/69719#comment:8).
Hopefully this finally closes https://trac.macports.org/ticket/69719.
macOS x.y
Have you
> draco: patch cmake to not use --start-group ,--end-group on mac

- graphics/opencolorio/Portfile
- graphics/openimageio/Portfile
- graphics/osl/Portfile
I don't know why the versions of opencolorio, openimageio, and osl are pinned ([this comment](https://trac.macports.org/ticket/67005#comment:2) suggests there is no reason), but if there is a reason, then this unifies all three ports to use the same condition, and in particular it fixes opencolorio and openimageio to allow non-macOS operating systems to see the latest version. I hope this will allow the ports.macports.org web site to see the current versions of these ports.
Also fix some typos in comments.
> opencolorio, openimageio, osl: Fix version pinning

- multimedia/mkvtoolnix-legacy/Portfile
Fixes: https://trac.macports.org/ticket/69735
Switch to Boost version which works for all systems (1.76 has a bug in multiprecision library which breaks build on powerpc).
macOS 10.6
Xcode 3.2
Have you
> mkvtoolnix-legacy: use Boost 1.81

- audio/libmysofa/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libmysofa: update to 1.3.2

- java/micronaut/Portfile
Update to Micronaut Starter 4.3.8.
Have you
> micronaut: update to 4.3.8

- devel/skaffold/Portfile
Update to Skaffold 2.11.1.
Have you
> skaffold: update to 2.11.1

- archivers/draco/Portfile
Make `draco`s  dependency `ghc-filesystem` a build dependency.
Closes: https://trac.macports.org/ticket/69738
macOS x.y
Have you
> draco: make 'ghc-filesystem' a build dependency

- gnome/gstreamer1-gst-plugins-base/Portfile
When the GL headers are not found meson will download them using  the gl-headers wrap, this causes gstreamer1-gst-plugins-base to conflict with gl-headers port & mesa.
Use the gl-headers Port to avoid embedding the headers, this also avoids the download from failing as it requires a modern version of git to download the subproject.
<br>
This is only seen when not using the default variants, trying to fixup the `gstreamer1` Portfiles to possibly remove the custom ones from my overlay.
> gstreamer1-gst-plugins-base: Don't conflict with gl-headers & mesa

- science/nco/Portfile
Simple update to upstream version 5.2.4
Have you
> nco: update to 5.2.4

- devel/ghidra/Portfile
ghidra: update to 11.0.3
Have you
> ghidra: update to 11.0.3

- java/openjdk22-oracle/Portfile
Update to Oracle OpenJDK 22.0.1.
Have you
> openjdk22-oracle: update to 22.0.1

- java/openjdk22-graalvm/Portfile
Update to GraalVM Community Edition 22.0.1.
Have you
> openjdk22-graalvm: update to 22.0.1

- java/jdk22/Portfile
Update to Oracle JDK 22.0.1.
Have you
> jdk22: update to 22.0.1

- sysutils/simplotask/Portfile
https://github.com/umputun/spot/releases/tag/v1.15.0
Xcode 14.2
Have you
> simplotask: update to 1.15.0

- java/jdk22-graalvm/Portfile
Update to Oracle GraalVM for JDK 22.0.1.
Have you
> jdk22-graalvm: update to 22.0.1

- security/libsam3/Portfile
New port: a tiny library to be used in RetroShare app.
macOS 14.4.1
Xcode 15.3
Have you
> libsam3: new port in security

- java/jdk21-graalvm/Portfile
Update to Oracle GraalVM for JDK 21.0.3.
Have you
> jdk21-graalvm: update to 21.0.3

- java/jdk21/Portfile
Update to Oracle Java SE Development Kit 21.0.3. 
Have you
> jdk21: update to 21.0.3

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.470
Have you
> ipsw: Update to 3.1.470

- devel/uv/Portfile
Update `uv` to its latest released version.
Have you
> uv: Update to 0.1.32

- ruby/ruby-build/Portfile
Upgrade ruby-build to 20240416
Have you
> ruby-build: Update to 20240416

- audio/vorbis-tools/Portfile
> vorbis-tools: fix missing dependency to build ogg123

- java/openjdk22-corretto/Portfile
Update to Amazon Corretto 22.0.1.8.1.
Have you
> openjdk22-corretto: update to 22.0.1.8.1

- java/openjdk22-sap/Portfile
Update to SAP Machine 22.0.1.
Have you
> openjdk22-sap: update to 22.0.1

- java/openjdk22-zulu/Portfile
Update to Azul Zulu 22.30.13.
Have you
> openjdk22-zulu: update to 22.30.13

- java/openjdk21-zulu/Portfile
Update to Azul Zulu 21.34.19.
Have you
> openjdk21-zulu: update to 21.34.19

- java/openjdk17-zulu/Portfile
Update to Azul Zulu 17.50.19.
Have you
> openjdk17-zulu: update to 17.50.19

- java/openjdk17-corretto/Portfile
Update to Amazon Corretto 17.0.11.9.1.
Have you
> openjdk17-corretto: update to 17.0.11.9.1

- java/openjdk21-corretto/Portfile
Update to Amazon Corretto 21.0.3.9.1.
Have you
> openjdk21-corretto: update to 21.0.3.9.1

- java/openjdk11-corretto/Portfile
Update to Amazon Corretto 11.0.23.9.1.
Have you
> openjdk11-corretto: update to 11.0.23.9.1

- java/openjdk17-sap/Portfile
Update to SAP Machine 17.0.11.
Have you
> openjdk17-sap: update to 17.0.11

- java/openjdk8-corretto/Portfile
Update to Amazon Corretto 8.412.08.1.
Have you
> openjdk8-corretto: update to 8.412.08.1

- java/openjdk21/Portfile
Update to OpenJDK 21.0.3.
Have you
> openjdk21: update to 21.0.3

- java/jdk17-graalvm/Portfile
Update to GraalVM for JDK 17.0.11.
Have you
> jdk17-graalvm: update to 17.0.11

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 472.0.0.
Have you
> google-cloud-sdk: update to 472.0.0

- java/jdk17/Portfile
Update to Oracle JDK 17.0.11.
Have you
> jdk17: update to 17.0.11

- devel/ninja/Portfile
C++11 is needed here.
macOS 10.6
Xcode 3.2
Have you
> ninja: use required cxx_standard, fix the port

- java/openjdk11-sap/Portfile
Update to SAP Machine 11.0.23.
Have you
> openjdk11-sap: update to 11.0.23

- java/openjdk17/Portfile
Update to OpenJDK 17.0.11.
Have you
> openjdk17: update to 17.0.11

- java/openjdk11/Portfile
Update to OpenJDK 11.0.23.
Have you
> openjdk11: update to 11.0.23

- net/wget2/Portfile
Port 'gettext' will be used opportunistically, if installed. But even if it isn't installed/available - such as when `wget2` is built via trace mode - `gettext-runtime` will still be linked to. (Albeit without an explicit dependency on it.)
Add formal deps for both, to ensure all is well.
> wget2: add deps gettext, gettext-runtime

- java/openjdk22/Portfile
Update to OpenJDK 22.0.1.
Have you
> openjdk22: update to 22.0.1

- graphics/ImageMagick/Portfile
- graphics/ImageMagick7/Portfile
By default, `ImageMagick` will opportunistically use `libraqm` if it's installed. Explicitly disable that behavior.
> ImageMagick, ImageMagick7: prevent opportunistic use of libraqm

- textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.2.0
Have you
> ocrmypdf: update to 16.2.0

- ruby/rb-fsevent-legacy/Portfile
A version for old systems.
(In this case -legacy is a part of the original gem name.)
macOS 10.6
Xcode 3.2
Have you
> rb-fsevent-legacy: new port

- gnome/libhandy/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libhandy: update to 1.8.3

- java/openjdk17-temurin/Portfile
Update to Eclipse Temurin 17.0.11.
Have you
> openjdk17-temurin: update to 17.0.11

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.2.5.
Have you
> spring-boot-cli: update to 3.2.5

- java/micronaut/Portfile
Update to Micronaut Starter 4.4.0.
Have you
> micronaut: update to 4.4.0

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.4.1
Have you
> ruff: Update 0.4.1

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.472
Have you
> ipsw: Update to 3.1.472

- ocaml/ocaml-rresult/Portfile
Fix port extract
macOS 10.6
Xcode 3.2
Have you
> ocaml-rresult: fix port extract

- finance/hledger/Portfile
Upgraded `hledger` to the latest version release yesterday, `1.33`. See https://hledger.org/relnotes.html.
I have just Command Line Tools installed but no `pkgutil` is command available.
Have you
> hledger: update to 1.33

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.34
Have you
> uv: Update to 0.1.34

- java/openjdk8-temurin/Portfile
Update to Eclipse Temurin 8u412.
Have you
> openjdk8-temurin: update to 8u412

- java/openjdk21-microsoft/Portfile
Update to Microsoft OpenJDK 21.0.3.
Have you
> openjdk21-microsoft: update to 21.0.3

- java/openjdk17-microsoft/Portfile
Update to Microsoft OpenJDK 17.0.11.
Have you
> openjdk17-microsoft: update to 17.0.11

- java/openjdk11-microsoft/Portfile
Update to Microsoft OpenJDK 11.0.23.
Have you
> openjdk11-microsoft: update to 11.0.23

- java/openjdk21-temurin/Portfile
Update to Eclipse Temurin 21.0.3.
Have you
> openjdk21-temurin: update to 21.0.3

- java/openjdk21/Portfile
Switch to source tarball from location in the [release announcement](https://mail.openjdk.org/pipermail/jdk-updates-dev/2024-April/032196.html) instead of the GitHub mirror.
Have you
> openjdk21: switch from GitHub mirror to official source

- java/openjdk11-temurin/Portfile
Update to Eclipse Temurin 11.0.23.
Have you
> openjdk11-temurin: update to 11.0.23

- gnome/gtk-vnc/Portfile
- gnome/gtk-vnc/files/patch-meson-python3.diff
- Add patch to ensure python3 is found.
- Explicitly disable `sasl2`, otherwise it will be opportunistically used when installed. (Unless the desire is to have this enabled. In which case, we'll need to add a formal lib dep.)
- Add missing build and lib deps.
Fixes: https://trac.macports.org/ticket/69757
> gtk-vnc: patch for python3; explicitly disable sasl2; add missing deps

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.18.4
Have you
> gitu: Update to 0.18.4

- math/libtommath/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libtommath: update to 1.3.0

- security/keychain-cpp/Portfile
- security/keychain-cpp/files/0001-keychain_mac-fix-build-on-10.9.patch
New port
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you
> keychain-cpp: new port

- audio/soundtouch/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
> soundtouch: update to 2.3.3

- java/openjdk7-bootstrap/Portfile
1. Existing version was linked to Apple X11, however there is no guarantee it is installed, and even if it is, uninstalling it will leave openjdk broken. (This is what I experienced myself.) Move usage of Apple X11 into a variant, relink to Macports X11 by default.
2. Add homepage to make lint happy.
3. Since this is a powerpc-only port, add myself as a co-maintainer.
macOS 10.6
Xcode 3.2.
Have you
> openjdk7-bootstrap: use Macports X11 by default to avoid a breakage

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.475
Have you
> ipsw: Update to 3.1.475

- net/ixwebsocket/Portfile
- net/ixwebsocket/files/0001-IXSocket.h-add-missing-sys-types.h-for-macOS.patch
New port: https://github.com/machinezone/IXWebSocket
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you
> ixwebsocket: new port in net

- ocaml/ocaml-stringext/Portfile
> ocaml-stringext: new port 1.6.0

- ocaml/ocaml-ppx_blob/Portfile
> ocaml-ppx_blob: new port 0.8.0

- devel/skalibs/Portfile
- lang/execline/Portfile
- sysutils/s6/Portfile
There was a small [bug](https://skarnet.org/lists/skaware/2003.html) in execline 2.9.5.0.  Laurent [released a fix](https://skarnet.org/lists/skaware/2008.html) in .1.
Thank you, @herbygillot, for keeping this port up to date.
This works on my machine™, though GitHub Actions is complaining about some inscrutable failure on macOS 14.  I am unable to test on macOS 14.  Let me know if this is a true positive failure, and I will rework somehow.
Have you
> execline: update to 2.9.5.1

- ruby/rb-fsevent-legacy/Portfile
Fix a build failure with clang.
See: https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/197130/steps/install-port/logs/stdio
macOS x.y
Have you
> rb-fsevent-legacy: fix build with clang

- graphics/ImageMagick/Portfile
* Update only long_description in Portfile.
* Add reference to new ImageMagick7 port.
CI only.
Have you
> ImageMagick: Update description only

- devel/typescript-language-server/Portfile
This should allow upgrading the npm portgroup to use nodejs20
Have you
> typescript-language-server: update to 4.3.3

- audio/libsoundio/Portfile
- audio/libsoundio/files/0002-coreaudio-add-fallback-aliases-for-10.8.patch
Update
macOS 10.6
Xcode 3.2
Have you
> libsoundio: update to 2.0.1-7

- devel/libxmlb/Portfile
New port
macOS 10.6
Xcode 3.2
Have you
> libxmlb: new port in devel

- lang/luajit/Portfile
- lang/luajit/files/TARGET_OS.patch
Fix two build issues observed by @rmottola on Mac OS X 10.5:
* Indicate that thread-local storage is required so that old compilers are not used. Manual blacklisting for gcc-4.2 removed since MacPorts knows it doesn't support thread-local storage. Leave the other blacklisting explicit since there was a runtime crash associated with building with those compilers.
* Check if `TARGET_OS_IPHONE` is defined before checking its value, since old SDKs don't define it and new clangs consider it an error to check an undefined `TARGET_OS_` macro.
Have you
> luajit: needs thread-local storage and TARGET_OS_IPHONE macro fix

- devel/smake/Portfile
smake: update to 1.7-2024-03-21
* Update codeberg.setup to version 2024-03-21
See:  https://trac.macports.org/ticket/69395
Have you
> smake: update to 1.7-2024-03-21

- net/abaddon/Portfile
- net/abaddon/files/0001-Do-not-use-precomp-headers-target-with-GCC-on-Apple.patch
- net/abaddon/files/0002-platform.cpp-add-missing-unistd.h.patch
- net/abaddon/files/0003-CMakeLists-also-link-to-AudioUnit-on-Apple.patch
- net/abaddon/files/0004-platform.cpp-add-a-missing-spdlog-include.patch
- net/abaddon/files/0005-miniaudio.h-fix-for-macOS.patch
New port, a Discord client on GTK3.
Works on PowerPC :) 
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you
> abaddon: new port, GTK-based Discord client

- archivers/star/Portfile
star: update to 1.7.0-2024-03-21
* Update codeberg.setup to version 2024-03-21
* Add bison as a build dependency
See: https://trac.macports.org/ticket/69395
Have you
> star: update to 1.7.0-2024-03-21

- graphics/d2/Portfile
Update d2 to 0.6.5. Add myself as co-maintainer.
Have you
> d2: update to 0.6.5; add myself as co-maintainer

- net/coeurl/Portfile
- net/coeurl/files/patch-pthread.diff
Backport a fix for spdlog (port uses an older bundled version, not our spdlog).
macOS 10.6
Xcode 3.2
Have you
> coeurl: fix build on old systems

- java/openjdk22-temurin/Portfile
Update to Eclipse Temurin 22.0.1.
Have you
> openjdk22-temurin: update to 22.0.1

- security/pkcs11-provider/Portfile
- security/pkcs11-provider/files/0001-build-Install-provider-in-correct-path.patch
> new port: pkcs11-provider, an OpenSSL 3 PKCS#11 provider

- devel/mediainfolib/Portfile
- multimedia/mediainfo/Portfile
Update to version 24.04
Have you
> medainfo,mediainfolib: update to version 24.04

- devel/libxmlb/Portfile
Update, fix for older systems using clangs.
They also cannot take a problematic flag: https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/271597/steps/install-port/logs/stdio
macOS 10.6
Xcode 3.2
Have you
> libxmlb: update to 0.3.19

- math/eigen3/Portfile
Update for -devel subport
macOS 14.4.1
Xcode 15.3
Have you
> eigen3-devel: update to 20240423

- lang/castxml/Portfile
- Add missing deps, per the configure output
Fixes: https://trac.macports.org/ticket/69802
> castxml: add missing deps

- sysutils/skopeo/Portfile
Updated to the latest version: https://github.com/containers/skopeo/releases
Have you
> skopeo: update to 1.15

- ruby/ruby-build/Portfile
ruby-build: Upgrade to 20240423
Have you
> ruby-build: Upgrade to 20240423

- security/putty/Portfile
- security/putty/files/patch-STDC_FORMAT_MACROS.diff
Update
macOS 10.6
Xcode 3.2
Have you
> putty: update to 0.81

- java/micronaut/Portfile
Update to Micronaut Starter 4.4.1.
Have you
> micronaut: update to 4.4.1

- sysutils/checkssl/Portfile
Update to checkssl 0.5.1.
Have you
> checkssl: update to 0.5.1

- java/openjdk11/Portfile
Switch to source tarball from location in the [release announcement](https://mail.openjdk.org/pipermail/jdk-updates-dev/2024-April/032198.html) instead of the GitHub mirror.
Have you
> openjdk11: switch from GitHub mirror to official source

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 473.0.0.
Have you
> google-cloud-sdk: update to 473.0.0

- devel/legacy-support/Portfile
Adds support for stpncpy().
Fixes reexport issue building libMacportsLegacySystem.B.dylib on 11.x+, without relying on optool.
Fixes a warning building one of the tests.
TESTED:
Tested both normal and -devel versions (currently identical) on 10.4-10.5 ppc, 10.5-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-14.x arm64.
Builds on all tested platforms except 10.5 ppc +universal. Passes all tests in all buildable cases.
```
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809 …
```
> legacy-support: update to v1.2.3

- _resources/port1.0/group/wxWidgets-1.0.tcl
- graphics/wxWidgets-3.0/Portfile
- sysutils/wxHexEditor/Portfile
- sysutils/wxHexEditor/files/0001-Fix-build-for-wxWidgets-v3.1.2.patch
New port
macOS 14.4.1 arm64
Xcode 15.3
macOS 10.6.8 x86_64
Xcode 3.2.6
macOS 10a190 ppc
Xcode 3.2
Have you
> wxHexEditor: new port in sysutils; wxgtk-3.0-cxx11: new subport of wxWidgets

- sysutils/pv/Portfile
Fix `pv` on OSX < 10.12 with `legacysupport`, since it requires `clock_gettime`, which isn't available on OSX < 10.12
Have you
> pv: Fix support for OSX < 10.12

- office/icalbuddy64/Portfile
Disable `-Werror` on powerpc to unbreak the port.
macOS 10.6
Xcode 3.2
Have you
> icalbuddy64: fix build on powerpc

- devel/gpgme/Portfile
See: https://trac.macports.org/ticket/69279
This is not a proper fix, so the ticket should not be closed.
This merely reverts enabling of C++ part for Tiger, since otherwise `gpgme` is just broken there.
macOS 10.4.11
Xcode 2.5
Have you
> gpgme: temporarily disable c++ part on Tiger to unbreak the port

- gis/qgis3/Portfile
- Update `qgis3` to 3.36.2 and  `qgis-ltr` to 3.34.6.
- Add `postgresql16` variant.
Have you
> qgis3, qgis-ltr: update to 3.36.2 and 3.34.6

- java/openjdk17/Portfile
Switch to source tarball from location in the [release announcement](https://mail.openjdk.org/pipermail/jdk-updates-dev/2024-April/032197.html) instead of the GitHub mirror.
Have you
> openjdk17: switch from GitHub mirror to official source

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.19.1
Have you
> gitu: Update to 0.19.1

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.37
Have you
> uv: Update to 0.1.37

- sysutils/edid-decode/Portfile
* update to version 20240402
Have you
> edid-decode: update to version 20240402

- gnome/tracker/Portfile
> tracker: Add `-Wno-int-conversion` to fix FTBFS on recent compilers

- devel/libtool/Portfile
- devel/libtool/files/hardcode-m4.patch
libtool: Remove stray $ after variable assignment
Closes: https://trac.macports.org/ticket/69599
Have you
> libtool: Remove stray $ after variable assignment

- science/hdf5/Portfile
- science/hdf5/files/patch-tools-src-misc-h5cc.in.diff
* Update hdf5 1.14.3 --> 1.14.4.2
* Use github portgroup.
* Switch distfile to one of the official GH release assets.
* Remove broken part of the `h5cc` wrapper script patch file.
* Looks like upstream worked on that wrapper script, maybe fixed something.
macOS 13.6.4 22G513 x86_64
Xcode 15.2 / Command Line Tools 15.1.0
Have you
> hdf5: Update to 1.14.4.2

- devel/gcli/Portfile
A new port submission.
Have you
> gcli: new port, CLI utility to interact with various Git forges

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.8.16

- _resources/port1.0/group/meson-1.0.tcl
- audio/pulseaudio/Portfile
This tries to improve the meson portgroup in a couple ways:
* `meson::add_depends` added meson and ninja dependencies which could have resulted in duplicate dependencies if the port or another portgroup it included already added them. Fixed this by deleting the dependencies first. It is not an error to delete nonexistent items from a list so this should not be a problem.
* `meson::get_post_args` added the same arguments in different conditions. Streamlined the code by adding each argument only once, or at least fewer times than before. The procedure now returns a list instead of a string which also better matches its destination (`configure.post_args`).
* meson.build files use `find_program` to locate programs but MacPorts might install them by a different name or with a version suffix. …
> meson portgroup improvements

- python/py-cython/Portfile
Closes: https://trac.macports.org/ticket/67380
Old Xcode clang gets pulled in only on Rosetta, and it fails to build `py-cython` now. Disable it together with old Xcode gccs.
(The problem is not specific to ppc, it is just not popping up on x86, because Macports overrides compiler choice.)
macOS 10.6.8
Xcode 3.2.6
Have you
> py-cython: avoid archaic Xcode clang of 10.6

- python/py-lxml/Portfile
Closes: https://trac.macports.org/ticket/65043
Same issue, old Xcode clang does not build this.
macOS 10.6.8
Xcode 3.2.6
Have you
> py-lxml: avoid old Xcode clang

- lang/swi-prolog-devel/Portfile
> swi-prolog-devel: Updated to version 9.3.4

- math/qalculate-gtk/Portfile
Blacklisting old compilers is not enough, linking fails then. It actually needs C++11.
macOS 10.6
Xcode 3.2
Have you
> qalculate-gtk: set cxx_standard 2011

- office/charm/Portfile
- office/charm/files/patch-fix-Qt5.diff
1. Fix build on older systems by setting C++11 standard.
2. Fix build with Qt5 on newer systems.
macOS 10.6
Xcode 3.2
Have you
> charm: fix the build

- python/py-bugsnag/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> py-bugsnag: update to 4.7.0

- print/libpaper/Portfile
Update
macOS 14.4.1
Xcode 15.3
macOS 10.4.11
Xcode 2.5
Have you
> libpaper: update to 2.2.5, fix build on Tiger

- audio/pavucontrol/Portfile
C++11 is required.
macOS 10.6
Xcode 3.2
Have you
> pavucontrol: set the correct cxx_standard, fix the port

- devel/pika/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> pika: update to 0.24.0

- textproc/asciidoctor/Portfile
TESTED:
Tested on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.
Builds and passes tests on all versions.
Functionally tested with gpsd and ntpsec on 10.9.  Generated docs match except for expected metadata differences specifically related to asciidoctor version.
```
OS X 10.10.5 14F2511, …
```
> asciidoctor: update to v2.0.21

- sysutils/port-whatsnew/Portfile
Closes: https://trac.macports.org/ticket/38110
As with PR #20951, this is basically just the same Portfile that I submitted in the original Trac ticket (38110 in this case), albeit with the `# $Id$` line removed, and revision reset to `0`. The actual script that the port installs probably needs to be updated to reflect the migration from `svn` to `git`, but that's an issue for `macports-contrib`, not `macports-ports`, and it can be reflected with an update to the port once the script is updated.
submission
Have you
> port-whatsnew: new port

- math/libqalculate/Portfile
Closes: https://trac.macports.org/ticket/63645
See also: https://github.com/Qalculate/libqalculate/issues/543
Turned out the issue was rather trivial.
macOS 10.6
Xcode 3.2
Have you
> libqalculate: fix segfault during the build

- lang/clojure/Portfile
> clojure: update to  1.11.3.1456

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.478. Complete diff @[`3.1.475...3.1.478`](https://github.com/blacktop/ipsw/compare/v3.1.475...v3.1.478)
Have you
> ipsw: Update to 3.1.478

- lang/camlp5/Portfile
Fix the target here as well.
macOS 10.6
Xcode 3.2
Have you
> camlp5: fix build target

- sysutils/simplotask/Portfile
https://github.com/umputun/spot/releases/tag/v1.16.0
Xcode 14.2
Have you
> simplotask: update to 1.16.0

- devel/the_Foundation/Portfile
https://git.skyjake.fi/skyjake/the_Foundation/releases/tag/v1.8.1
Xcode 14.2
Have you
> the_Foundation: update to 1.8.1

- python/py-jsonpatch/Portfile
> py-jsonpatch: update to 1.33, add 3.12

- math/R/Portfile
- math/R/files/patch-fix-memsize.diff
Fixes: https://trac.macports.org/ticket/69849
@ryandesign This should fix the problem. We will not need to patch every affected package then.
macOS 10.6
Xcode 3.2
Have you
> R: fix a bug breaking installation of some packages on 32-bit platforms

- archivers/unrar/Portfile
Difference: https://github.com/pmachapman/unrar/commit/05567f51502f156685e346fa072755ea07738edf
Have you
> unrar: update to 7.0.8

- sysutils/pv/Portfile
Update `pv` to its latest released version, 1.8.9
Have you
> pv: Update to 1.8.9

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.39
Have you
> uv: Update to 0.1.39

- net/tlrc/Portfile
Update `tlrc` to its latest released version, 1.9.2
Have you
> tlrc: Update to 1.9.2

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.480
Have you
> ipsw: Update to 3.1.480

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.19.2
Have you
> gitu: Update to 0.19.2

- math/mpdecimal/Portfile
- math/mpdecimal/files/no-rpath.patch
Closes: https://trac.macports.org/ticket/69870
Have you
> mpdecimal: Use absolute path in install names

- audio/libgig/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libgig: update to 4.4.1

- R/R-clock/Portfile
- R/R-clock/files/Makevars
Fixes: https://trac.macports.org/ticket/68533
Fix
macOS 10.8.5
Xcode 5.1.1
Have you
> R-clock: fix for < 10.13 with clang

- devel/dagger/Portfile
upgrade to latest version from https://github.com/dagger/dagger/releases
Have you
I updated the x64_64 variant's checksum's and file size but did not test its binary.
> dagger: update to 0.11.2

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 474.0.0.
Have you
> google-cloud-sdk: update to 474.0.0

- ruby/ruby-build/Portfile
ruby-build: Upgrade to 20240501
Have you
> ruby-build: Upgrade to 20240501

- editors/nvi/Portfile
Closes: https://trac.macports.org/ticket/69888
Fix this version too
macOS 10.6
Xcode 3.2
Have you
> nvi: blacklist old Xcode gcc, which does not build this

- editors/nvi2/Portfile
- editors/nvi2/files/patch-SLIST_REMOVE_AFTER.diff
- editors/nvi2/files/patch-fix-include-path.diff
Re-make on `nvi`
macOS 10.6
Xcode 3.2
Have you
> nvi2: new port in editors

- devel/google-cloud-sdk/Portfile
Add `istioctl` variant.
Have you
> google-cloud-sdk: add istioctl variant

- devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases/tag/v0.175.0
Xcode 14.2
Have you
> jsoncons: update to 0.175.0

- net/httpie-go/Portfile
Add `httpie-go`, an httpie-like client written in Go.
Have you
> httpie-go: new port (version 0.7.0)

- sysutils/ntpsec/Portfile
The previous regex change to allow the patch letter broke the case where the letter is absent.  The regex is now derived from the GitHub default regex, but adjusted to exclude patterns with dashes to avoid versions such as X.Y.Z-rcN.  The unnecessary quote exclusion is dropped.
TESTED:
Tested with current and older port versions, including with modified regex to make 1.2.2a the apparent latest.
Have you
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [NO] tried existing tests with `sudo port test`?
- [NO] tried a full install with `sudo port -vst install`?
- [NO] tested basic functionality of all binary files?
- [NO] checked that the Portfile's most important …
> ntpsec: Fix livecheck

- lang/ruby33/Portfile
- lang/ruby33/files/patch-sources.diff
See:
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-3-1-released/
This incorporates the applicable patches from ruby32, including converting the reinplace patch for the gem program name to a normal source patch.
All source patches are in a single patchfile derived from the ruby fork at github.com/fhgwright/ruby.  The changes are much more readable in the git repo.
It also narrows the compiler blacklisting and fixes the 10.5 cstdbool issue, corresponding to what was done in ruby30/ruby32.
Also fixes livecheck.
Also adds self as co-maintainer.
TESTED:
Built successfully with no variants on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.
Built with all variants except jemalloc and yjit on 10.4-10.5, all variants except yjit on 10.6-10.13, and all variants on …
> ruby33: update to v3.3.1; fix build on 10.4, 10.5

- lang/ruby32/Portfile
- lang/ruby32/files/patch-sources.diff
See:
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-2-4-released/
This incorporates the applicable patches from ruby30, including converting the reinplace patch for the gem program name to a normal source patch.
It adds two new patches related to the CommonCrypto headers on 10.4 and 10.5.
All source patches are in a single patchfile derived from the ruby fork at github.com/fhgwright/ruby.  The changes are much more readable in the git repo.
It also narrows the compiler blacklisting, corresponding to what was done in ruby30.
It also incorporates the cstdbool fix for 10.5, from ruby30.
Also adds self as co-maintainer.
TESTED:
Built successfully with no variants on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.
Built with all variants except jemalloc and yjit on …
> ruby32: update to v3.2.4; fix build on 10.4, 10.5

- science/hdf5/Portfile
[User report](https://trac.macports.org/ticket/69861) of fortran tools failing with errors matching [upstream report](https://github.com/HDFGroup/hdf5/issues/4310).
Disabling new float16 support for now.
> hdf5: Disable new float16 support for now.

- lang/clojure/Portfile
> clojure: update to  1.11.3.1463

- textproc/asciidoctor/Portfile
Also updates the underlying ruby version to 3.3, just to avoid EOL concerns (since it doesn't affect the behavior of asciidoctor itself). 3.3 is outside the compatible version range stated on the asciidoctor homepage, but that appears to be outdated.
TESTED:
Tested on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.
Builds and passes tests on all versions.
Functionally tested with gpsd and ntpsec on 10.9.  Generated docs match except for expected metadata differences specifically related to asciidoctor version.
```
Mac OS X 10.6.8 …
```
> asciidoctor: update to v2.0.22

- gis/JOSM/Portfile
macOS 12.6.7 x86_64
Xcode 14.2
Have you
> josm: update to 19067

- science/gildas/Portfile
> Gildas: update to 202405b

- audio/pulseaudio/Portfile
- audio/pulseaudio/files/patch-avoid-segfault-on-powerpc.diff
Other stuff fixed in https://github.com/macports/macports-ports/commit/baa9797fc30ad642bec24014769c0d7c8da49f68 so I rebased to that, and just one patch needed.
macOS 10.6
Xcode 3.2
macOS 14.4.1
Xcode 15.3
Have you
> pulseaudio: fix segfault on powerpc

- ruby/rb-net-ftp/Portfile
Ruby 3.3.1 has this gem included.
macOS 10.6
Xcode 3.2
Have you
> rb-net-ftp: remove rb33 subport, as it is now included in ruby33

- audio/libfdk-aac/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> libfdk-aac: update to 2.0.3

- graphics/glfw/Portfile
- graphics/glfw/files/patch-use-x11.diff
Fix the port on older systems
macOS 10.6
Xcode 3.2
Have you
> glfw: build on < 10.6 and ppc against x11, unbreak the port

- databases/valkey/Portfile
- databases/valkey/files/patch-fix-older-macOS.diff
- databases/valkey/files/patch-remove-brewism.diff
Closes: https://trac.macports.org/ticket/69887
Fix build on 10.6, drop unneeded brewism
macOS 10.6
Xcode 3.2
Have you
> valkey: fix on 10.6, remove brewism

- java/micronaut/Portfile
Update to Micronaut Starter 4.4.2.
Have you
> micronaut: update to 4.4.2

- sysutils/stern/Portfile
Update to Stern 1.29.0.
Have you
> stern: update to 1.29.0

- devel/tree-sitter-c-sharp/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-c-sharp: now needs -std=c99

- R/R-QuickJSR/Portfile
- R/R-QuickJSR/files/patch-no-libatomic.diff
Closes: https://trac.macports.org/ticket/69872
@ryandesign Cannot check, but I hope this solves the issue raised in the ticket.
macOS x.y
Have you
> R-QuickJSR: do not try libatomic linking with clang builds

- audio/rnnoise/Portfile
Removes the need to autoreconf. Removes need for autoconf, automake, libtool, wget dependencies. No longer downloads a file at build time. The version number is now correct in rnnoise.pc.
Closes: https://trac.macports.org/ticket/69882
Have you
> rnnoise: Use release tarball

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.8.17

- sysutils/borgmatic/Portfile
> borgmatic: Update to 1.8.11

- devel/tree-sitter-css/Portfile
Fix on old systems
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-css: also needs C99 after update

- lang/eiffelstudio/Portfile
* updated maintainer's list
Have you
- [] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message?
> eiffelstudio: Add another maintainer

- sysutils/ddrescue/Portfile
Can ddrescue be made openmaintainer for minor version updates?
Have you
> ddrescue: update to 1.28

- gis/imposm/Portfile
[Imposm](https://github.com/omniscale/imposm3) imports OpenStreetMap data into PostGIS.
Xcode 14.2
Have you
> imposm: new port

- net/samba4/Portfile
https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/272986/steps/install-port/logs/stdio
This does not happen where legacysupport is enabled (Mavericks and older).
Have you
> samba4: fix build on macOS <10.13

- graphics/unpaper/Portfile
This updates unpaper to 7.0.0 which involves changing the build system to meson. I have also adopted the port since it was unmaintained.
Have you
> unpaper: update to 7.0, change build system, adopt

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 475.0.0.
Have you
> google-cloud-sdk: update to 475.0.0

- lang/kotlin/Portfile
Update to Kotlin 1.9.24.
Have you
> kotlin: update to 1.9.24

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.40
Have you
> uv: Update to 0.1.40

- aqua/emacs-mac-app/Portfile
Emacs Mac port is by default installed as `EmacsMac.app` instead of `Emacs.app` to avoid conflicting with `emacs-app`. I added the variant `renameapp` to control whether the application bundle is renamed. This way, users who install only the Mac port can choose to have it named `Emacs.app` by negating the variant. It is enabled by default, so the existing behavior of `sudo port install emacs-mac-app` is preserved.
Have you
> emacs-mac-app: Add renameapp variant

- comms/c3270/Portfile
Updates the port to 4.3ga8.
Have you
For some reason `port -vst install` fails on my machine.
> c3270: update to 4.3ga8

- python/py-pypng/Portfile
Update `pypng` to version 0.20220715.0, while adding the Python 3.12 subport
Have you
> py-pypng: Update to 0.20220715.0

- textproc/openjade/Portfile
Current blacklist is wrong and leaves the port broken on old systems. Fix it.
Xcode Xcode 3.2.6
macOS 10.6
Xcode 3.2
Have you
> openjade: fix compiler choice

- games/2048.c/Portfile
Add [`2048.c`](https://github.com/mevdschee/2048.c), a terminal version of the game 2048 written in C
Have you
> 2048.c: new port (1.0.0)

- multimedia/audacious-plugins/Portfile
Fixes: https://trac.macports.org/ticket/60227
Have you
> audacious-plugins: enable more plugins

- audio/rnnoise/Portfile
Needed for Yosemite and older versions: https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/269995/steps/install-port/logs/stdio
Have you
> rnnoise: blacklist clang < 800

- devel/astyle/Portfile
- devel/astyle/files/dont-force-stdlib.diff
> astyle: update to 3.4.14

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.4.4
Have you
> ruff: Update to 0.4.4

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.20.2
Have you
> gitu: Update to 0.20.1

- www/nicotine-plus/Portfile
Well, again, yeah.
macOS 10.6
Xcode 3.2
Have you
> nicotine-plus: update to 3.3.4

- python/py-pyqrcode/Portfile
Add the Python 3.12 subport to `pyqrcode`
Closes: https://trac.macports.org/ticket/69778
Have you
> py-pyqrcode: Add Python 3.12 subport

- devel/tree-sitter-c/Portfile
- devel/tree-sitter-dockerfile/Portfile
Fix the build on older systems.
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-c, tree-sitter-dockerfile: need C99 after the last update

- python/py-slack-sdk/Portfile
Adding support for python 3.12. I am not updating the package to its latest version because there are some issues, but this version should work as well.
Have you
> py-slack-sdk: add python 3.12

- gnome/gtk3-devel/Portfile
- gnome/gtk3/Portfile
Resolves "Symbol not found: _g_desktop_app_info_get_filename"
macOS x.y
Have you
> gtk3: require active variant for glib2

- devel/uv/Portfile
Update `uv` to its latest released version, 0.1.42
Have you
> uv: Update to 0.1.42

- sysutils/g-ls/Portfile
Update `g-ls` to its latest released version, 0.27.0
Have you
> g-ls: Update to 0.27.0

- devel/got/Portfile
* closes https://trac.macports.org/ticket/69827
Have you
> got: update to 0.99

- devel/jujutsu/Portfile
Update jujutsu to 0.17.1
Have you
> jujutsu: update to 0.17.1

- devel/qbs/Portfile
> qbs: Update to 2.3.1

- multimedia/QMPlay2/files/0003-ScreenSaver-fix-IOKit-defines.patch
Fix the build on 10.5
macOS x.y
Have you
> QMPlay2: fix for 10.5

- gis/mod_tile/Portfile
- gis/mod_tile/files/README_MacPorts.md
- gis/mod_tile/files/osm_setup_db.sh
- gis/mod_tile/files/renderd.conf.dist
Fixed launch daemon failing to start on macOS 14.4.1 (Sonoma)
Also now creates `mapnik.xml.dist` during the build/install so it longer needs to be distributed with the `openstreetmap-carto` port.
Have you
@nilason - available for your review and comments.
> mod_tile: Update to proj7, variants to use Postgresql15-16

- sysutils/oh-my-posh/Portfile
* update to version 19.28.0
* fix leak of information when use `oh-my-posh version -v`
See: https://github.com/JanDeDobbeleer/oh-my-posh/issues/4014
Have you
> oh-my-posh: update to version 19.28.0

- devel/Bear/Portfile
- devel/apache-arrow/Portfile
- devel/grpc/Portfile
- devel/protobuf3-cpp-upstream/Portfile
- devel/re2/Portfile
- math/s2geometry/Portfile
- net/mtxclient/Portfile
After the change of the c++ standard used for building abseil in f013da941ee8e69ff11d57f4a5c213ac005bf5c3, its dependants need a rev-bump.
Should fix the following track tickets:
- [69909](https://trac.macports.org/ticket/69909)
- [69932](https://trac.macports.org/ticket/69932)
Have you
> abseil-dependants: revbump after c++ std change

- textproc/pdfjam/Portfile
Update to pdfjam 3.11.
Have you
> pdfjam: update to pdfjam 3.11

- _resources/port1.0/group/rust-1.0.tcl
> rust PG: sort crate names in alphabetical order

- textproc/jj/Portfile
The `jujutsu` port installs `jj` as does `textproc/jj`, but only `jujutsu` declares conflicts.
Have you
This is a special case where I installed `jujutsu` and then ran:
```console
$ sudo port install
--->  Computing dependencies for jj
Error: Can't install jj because conflicting ports are active: jujutsu
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port jj failed
```
> textproc/jj: Add conflicts with jujutsu

- audio/olaf-devel/Portfile
- audio/olaf-devel/files/patch-altivec.diff
Needs C11 (obviously).
Disable AltiVec for now, code is broken.
macOS 10.6
Xcode 3.2
Have you
> olaf-devel: fix for older systems and powerpc

- audio/codec2/Portfile
Fix for old systems, minor portfile clean-up.
macOS 10.6
Xcode 3.2
Have you
> codec2: avoid old Xcode gcc, it fails to build this

- x11/rxvt-unicode/Portfile
- x11/rxvt-unicode/files/patch-fix-osc-response.diff
Closes: https://trac.macports.org/ticket/69951
> rxvt-unicode: backport fix for OSC responses with 7-bit ST

- security/libressl/Portfile
> libressl: update to 3.9.2

- devel/dagger/Portfile
Have you
I updated the x64 variant too but did not test it.
> dagger: update to 0.11.4

- devel/d3dmetal/Portfile
A Port for installing Apples D3DMetal, this will be used by `game-porting-toolkit` & also `wine-crossover`\
The license for this is a little weird so not entirely sure on the best way to handle it. I've set the license to restrictive but that might now be exactly accurate still accord to Nat Brown we can redistribute D3DMetal we just can't use it in commercial wine wrapped game ports.
This port only supports x86_64 on Apple Silicon, the `try` section is something to ensure it's only installed onto an Apple Silicon system running macOS Sonoma and later systems, if theres a better way to handle that I'm open to ideas.
@kencu & @ryandesign 
macOS 14.5 23F5074a x86_64
> d3dmetal: New Port

- devel/d3dmetal/Portfile
Simply force arm64 when the system isn’t running under Rosetta2
Some users might be running macports under a rosetta2 terminal session instead of arm64.
> d3dmetal: Don’t break everything

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.8.19

- devel/tig/Portfile
> tig: Update to 2.5.10

- science/hdf5/Portfile
- science/hdf5/files/fix-leak-of-internal-ids.patch
See: https://trac.macports.org/ticket/69938
Also clean up fetch and extract code.
Have you
> hdf5: Fix leak of internal IDs

- python/py-h5py/Portfile
- python/py-h5py/files/float16.patch
Closes: https://trac.macports.org/ticket/69938
Also remove reinplace that hasn't been needed since 3.6.0.
Have you
> py-h5py: Use float16 datatype only if available

- kde/kdepim4-runtime/Portfile
- kde/kdepim4/Portfile
Remove link-grammar dependency
Support for link-grammar was removed in kdepim4 4.13.1.
See KDE/kdepim@9fed451
@bjoernricks Are you the Björn Ricks listed as the maintainer of this port? If so we would like to add your GitHub handle to this port and the others you maintain, unless you no longer wish to maintain them, in which case we can remove your email address from them.
Have you
> kdepim4: Remove link-grammar dependency

- finance/numchk/Portfile
Fix for old systems
macOS 10.6
Xcode 3.2
Have you
> numchk: blacklist old Xcode gcc to fix build on old OS

- devel/gk/Portfile
> gk: update to v2.0.0

- comms/minicom/Portfile
(I tried to patch out the flag and use gcc-4.2 initially, but then linking failed due to missing Static assert.)
macOS 10.6
Xcode 3.2
Have you
> minicom: fix for old systems

- x11/xscreensaver/Portfile
- x11/xscreensaver/files/patch-ignore-qos.diff
> xscreensaver: fix build on macOS <10.13

- devel/git-tui/Portfile
- devel/subprocess/Portfile
- tex/MicroTeX/Portfile
A failure on < 10.15: https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/209177/steps/install-port/logs/stdio
macOS 10.8.5
Xcode 5.x
Have you
> subprocess, git-tui, MicroTeX: fix for pre-Catalina systems with libc++

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 476.0.0.
Have you
> google-cloud-sdk: update to 476.0.0

- devel/skaffold/Portfile
Update to Skaffold 2.12.0.
Have you
> skaffold: update to 2.12.0

- math/singular/Portfile
Closes: https://trac.macports.org/ticket/69714
@catap Kirill, please take a look. Trivial update, but required one.
macOS 10.6
Xcode 3.2
Have you
> singular: update to 4-4-0 to fix building with new flint

- devel/util-linux/Portfile
Fix the build for 32-bit.
macOS 10.6
Xcode 3.2
Have you
> util-linux: unbreak for 32-bit platforms

- security/tor-devel/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> tor-devel: update to 0.4.8.11

- x11/openmotif/Portfile
Last update unconditionally added a flag which broken the build with gcc.
Fix that.
macOS 10.6
Xcode 3.2
Have you
> openmotif: unbreak after recent update

- devel/kokkos/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> kokkos-devel: update to 2024.05.13

- gnome/vte/Portfile
- gnome/vte/files/patch-F_DUPFD_CLOEXEC.diff
Fixes: https://trac.macports.org/ticket/69963
Fix
macOS 10.6
Xcode 3.2
Have you
> vte: fix build on < 10.7

- python/py-pkginfo/Portfile
> py-pkginfo: update to 1.10.0

- ruby/ruby-build/Portfile
ruby-build: Upgrade to 20240517
Have you
> ruby-build: Upgrade to 20240517

- devel/string_theory/Portfile
Add the [string_theory](https://github.com/zrax/string_theory) C++ string library as a port.
Have you
> string_theory: New port, version 3.8

- audio/audiowmark/Portfile
- audio/audiowmark/files/patch-cinttypes.diff
Fix build
macOS 10.6
Xcode 3.2
Have you
> audiowmark: fix build with compiler which need __STDC_FORMAT_MACROS

- sysutils/readpe/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> readpe: fix build on < 10.7

- devel/libck/Portfile
- devel/libck/files/patch-fix-powerpc.diff
Fix build on powerpc
macOS 10.6
Xcode 3.2
Have you
> libck: fix build for PowerPC

- net/dnsperf/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> dnsperf: use legacysupport for clock_gettime

- net/heimdal/Portfile
Libdispatch headers may be present, but we do not want to use `libdispatch` on PowerPC, until it is fixed properly and known to work. Thankfully, Heimdal has a fallback implementation, we just need to turn off dispatch from configure.
I am not adding a variant to use `libdispatch-legacy` port on ppc, since while that may work, for now rather use the upstream code.
macOS 10.6
Xcode 3.2
Have you
> heimdal: use heimdal fallback instead of dispatch on powerpc

- net/ettercap/Portfile
See: https://trac.macports.org/ticket/70015
Avoid a weird failure on ppc
macOS 10.6
Xcode 3.2
Have you
> ettercap: declare build conflict with libtapi on powerpc

- devel/gitui/Portfile
https://github.com/extrawurst/gitui/releases
Xcode 14.2
Have you
> gitui: update to 0.26.2

- net/fping/Portfile
> fping: update to 5.2

- devel/d3dmetal/Portfile
Closes https://trac.macports.org/ticket/69983
> d3dmetal: Only run sysctl on Sonoma and later

- net/mqttui/Portfile
[Changelog](https://github.com/EdJoPaTo/mqttui/releases)
https://github.com/EdJoPaTo/mqttui/compare/v0.19.0...v0.21.0
Xcode 14.2
Have you
> mqttui: update to 0.21.0

- print/ghostscript/Portfile
Simple update to upstream version 10.03.1
This update does not remove the necessity of the last introduced patch (pdf_sec.c.diff); the developers did not yet introduce it into their version.
This update does not require revbumping any of the dependencies since the library name does not change. 
Have you
> ghostscript: update to 10.03.1

- python/py-maturin/Portfile
Fixes https://trac.macports.org/ticket/70003
macOS x.y
Have you
> py-maturin: use rust PG instead of cargo PG

- textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.3.0
Have you
> ocrmypdf: update to 16.3.0

- ocaml/ocaml-astring/Portfile
> ocaml-astring: take ownership and fix livecheck

- lang/mlton/Portfile
- lang/mlton/files/patch-settings-for-Macports.diff
Update
macOS 10.6
Xcode 3.2
Have you
> mlton: update to 20240519

- dotnet/dotnet-sdk-6/Portfile
Closes: https://trac.macports.org/ticket/70034
macOS x.y
Have you
> dotnet-sdk-6: correct arm64 checksum

- games/2048.c/Portfile
Fix conflicts with `2048.cpp` by renaming `2048` -> `c2048` when installing the `2048.c` port
Have you
> 2048.c: Fix conflicts with 2048.cpp

- irc/weechat/Portfile
- irc/weechat/files/no-extra-gcc-warnings.patch
Remove extra warning flags to fix builds with gcc < 7
Closes: https://trac.macports.org/ticket/70002
> weechat: Remove extra warning flags to fix old GCC

- sysutils/tmate/Portfile
Fix building with gcc
macOS 10.6.8
Xcode 3.2.6
Have you
> tmate: fix build with gcc

- editors/mle/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> mle: fix build on < 10.7

- net/wireshark4/Portfile
> wireshark4: update to 4.2.5, new qt6 variant, http/3 support

- multimedia/zvbi/Portfile
Do not apply the patch when building with old gcc, it breaks the build unnecessarily.
Also use legacysupport for `sincos`, revbump for that.
macOS 10.6.8
Xcode 3.2.6
Have you
> zvbi: unbreak build for gcc-4.x

- multimedia/libass/Portfile
MacPorts base does not work correctly now if built for `ppc` on an Intel system. I.e., on Rosetta it has to be built for x86.
That breaks `libass`, which uses `uname`, I think, to detect the arch, and used `platform powerpc` to blacklist Xcode clang.
Fix that.
macOS 10.6.8 Rosetta
Xcode 3.2.6
Have you
> libass: update powerpc fix

- archivers/snappy/Portfile
- archivers/snappy/files/patch-version-number.diff
Apply as a patch a PR content that was merged after upstream 1.2.0 release. Fixes https://trac.macports.org/ticket/70046
Have you
> snappy: set version of dylib to 1.2.0

- textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.3.1
Have you
> ocrmypdf: update to 16.3.1

- x11/gccmakedep/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> gccmakedep: update to 1.0.4

- graphics/rawtherapee/Portfile
- graphics/rawtherapee/files/0001-Fix-linking-with-jpeg-turbo.patch
- graphics/rawtherapee/files/0002-removes-redundant-jpeg-error-message.patch
Closes: https://trac.macports.org/ticket/69982
This seems to work.
macOS 10.8.5
Xcode 5.x
Have you
> rawtherapee: fix build with libjpeg-turbo 3.0.3

- devel/zix/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
> zix: fix for darwin < 16

- gnome/tepl/Portfile
The patch uses a flag which gcc-4.2 cannot handle. Avoid old Xcode gcc.
macOS 10.6
Xcode 3.2
Have you
> tepl: fix build on < 10.7

- www/retroshare-qt4/Portfile
- www/retroshare-qt4/files/0001-Fix-broken-linking-and-settings.patch
- www/retroshare-qt4/files/0002-bdthreads.cc-fix-pointer-comparison.patch
- www/retroshare-qt4/files/0003-Add-missing-headers.patch
UPD. There is really no need to torture the code to build for the latest OS, where instead Qt5-based version should be used.
I will restrict this to older OS.
retroshare-qt5 upcoming, but I need time to sort out the build. There is one module broken in the master, I need to find a neat way to fix it.
macOS 10.6
Xcode 3.2
Have you
> retroshare-qt4: new port

- devel/xdispatch2/Portfile
https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/270375/steps/install-port/logs/stdio
https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/191277/steps/install-port/logs/stdio
Have you
> xdispatch2: fix build on macOS <10.11

- audio/nrsc5/Portfile
Fix the build.
macOS 10.6
Xcode 3.2
Have you
> nrsc5: fix build for < 10.7

- lang/perl5/Portfile
- lang/perl5/files/5.38/avoid-no-cpp-precomp-PR38913.patch
- lang/perl5/files/5.38/clean-up-paths.patch
- lang/perl5/files/5.38/config.h.ed
- lang/perl5/files/5.38/enable-syscall-on-sierra.patch
- lang/perl5/files/5.38/fix-db_file-paths.patch
- lang/perl5/files/5.38/fix-miniperl-linking-PR36438.patch
- lang/perl5/files/5.38/install-under-short-version-PR43480.patch
- lang/perl5/files/5.38/patch-Configure-remove-libs.diff
- lang/perl5/files/5.38/patch-want-implicit-errors.diff
> perl5: add perl5.38

- audio/libsidplayfp/Portfile
- audio/libsidplayfp/files/configure.patch
libsidplayfp: Fix detection of C++11 compilers
Should fix build on OS X 10.8 and 10.9 buildbot workers.
Have you
> libsidplayfp: Fix detection of C++11 compilers

- science/bowtie/Portfile
- science/bowtie/files/patch-powerpc.diff
Fix the broken code :) 
macOS 10.6
Xcode 3.2
Have you
> bowtie: fix build for powerpc

- graphics/openslide/Portfile
Here also need to blacklist archaic gcc.
macOS 10.6
Xcode 3.2
Have you
> openslide: blacklist Xcode gcc

- devel/libdevil/Portfile
@ryandesign Is there some special reason not to set the standard? As of now, it does not work, expectedly, since gcc-4.2 gets picked, and errs out at configure.
macOS 10.6
Xcode 3.2
Have you
> libdevil: require C++11 compiler, since portfile uses -std=gnu++11

- devel/liblightgrep/Portfile
- devel/liblightgrep/files/patch-ssize_t.diff
- devel/liblightgrep/files/patch-unbreak-gcc-build.diff
Fix the build
macOS 10.6
Xcode 3.2
Have you
> liblightgrep: unbreak build with gcc

- lang/erlang/Portfile
* keep doc_version in case future patches do not come with doc updates
* remove use_parallel_build no as comment mentioned R13B which was a long time ago
* change openssl branch to 3
Closes: https://trac.macports.org/ticket/69611
Have you
> Erlang: update to 27.0

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.2.6.
Have you
> spring-boot-cli: update to 3.2.6

- java/spring-boot-cli/Portfile
Update to Spring Boot 3.3.0.
Have you
> spring-boot-cli: update to 3.3.0

- kde/baloo/Portfile
Use the right C++ standard.
macOS 10.6
Xcode 3.2
Have you
> baloo: require C++11

- kde/kde4-runtime/Portfile
Port requires C++11. Drop redundant and wrong blacklist, use `cxx_standard`.
Also improve text layout.
macOS 10.6
Xcode 3.2
Have you
> kde4-runtime: use the right C++ standard

- gnome/gstreamer1-gst-plugins-base/Portfile
Starting with orc 0.4.34 gstreamer1-gst-plugins-base needs to be compiled with a c11 compiler to avoid sluggish behavior. See https://gitlab.freedesktop.org/gstreamer/orc/-/issues/47
I attach two videos showing the behaviour with and without the change in this PR using the same command mentioned in the issue linked above:
```
gst-launch-1.0 -v videotestsrc pattern=ball ! autovideosink
```
This requires installing `gstreamer1-gst-plugins-good`.
Testing this requires either the use of `+x11` variants or to use the changes made in #23760 to test it with the `+quartz` variants.
**Before:**
https://github.com/macports/macports-ports/assets/59110786/d45eb94a-8677-4e90-916a-6010f108d44c
**After:**
https://github.com/macports/macports-ports/assets/59110786/f854a477-075e-4790-accb-d87f15efe5ff
I'm …
> gstreamer1-gst-plugins-base: Fix sluggishness

- sysutils/pciutils/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> pciutils: update to 3.12.0

- devel/hyprlang/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> hyprlang: update to 0.5.2

- multimedia/QMPlay2/Portfile
Update for newer systems.
macOS 14.5
Xcode 15.3
Have you
> QMPlay2: update to 24.05.23

- devel/gumbo-parser/Portfile
Closes: https://trac.macports.org/ticket/69545
Have you
> gumbo-parser: update to 0.12.1

- devel/qxmpp/Portfile
Fix for powerpc
macOS 10.6
Xcode 3.2
Have you
> qxmpp: provide Qt4-based version for PowerPC systems

- lang/mlton/Portfile
The source was changed recently in a way which left out MLTon broken.
Fix that.
macOS 14.5
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you
> mlton: fix path pointing to C compiler

- devel/rcs/Portfile
Use gnulib PG
macOS 10.6*
Xcode 3.2
* gnulib PG itself needs a fix for 10.6 ppc, but once that it does, it works nicely and `rcs` installs normally.
Have you
> rcs: use gnulib PG to fix confdir bug and fix build on Sonoma

- devel/util-linux/Portfile
The previous fix for 32-bit builds only took build_arch into account, which didn't fix, e.g., universal builds on x86_64.  This version looks at all target architectures.
Since this only affects previously broken builds, no revbump is necessary.
TESTED:
Tested on 10.4-10.5 ppc, 10.5-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-14.x arm64.
Builds on all tested platforms except 10.4 ppc +universal (due to broken dependency).
Passes token "port test" in all buildable cases.
```
Mac OS …
```
> util-linux: Fix 32-bit universal builds

- gnome/libgtksourceviewmm/Portfile
Fix building on older systems
macOS 10.6
Xcode 3.2
Have you
> libgtksourceviewmm: fix build on older systems, restrict to Catalina and earlier

- cross/mingw-w64-wine-mono/Portfile
Stub that contains multiple subports, will be used for the new `wine` portfiles.
macOS 14.5 23F5074a x86_64
> mingw-w64-wine-mono: New Port

- python/internetarchive/Portfile
- python/py-schema/Portfile
- python/tubeup/Portfile
> tubeup: new port

- python/py-pyobjc6/Portfile
- python/py-pyobjc6/files/0001-Fix-obsolete-Python-API.patch
- python/py-pyobjc6/files/0002-module.m-no-AssociatedObject-on-ppc.patch
- python/py-pyobjc6/files/0003-properties.m-disable-test-that-fails-to-compile-with.patch
- python/py-pyobjc6/files/0004-struct-wrapper-fix-for-python-3.10.patch
Closes: https://trac.macports.org/ticket/69728
This fixes the build of core library. (Currently the port is totally broken and installs only docs.)
macOS 10.6
Xcode 3.2
Have you
> py-pyobjc6: fix the build of core library

- devel/tbb/Portfile
- devel/tbb/files/patch-tbb-older-malloc.diff
Finally fix this as well. It is not maintained, but still used by some ports.
macOS 10.6
Xcode 3.2
Have you
> tbb (legacy TBB): minor fixes for powerpc

- science/netcdf-cxx4/Portfile
* Remove accidental dependency on HDF5.
* Disable filter tests which caused accidental dependency.
* Fix whitespace nitpicks.
There was a choice to either formally add the `hdf5` dependency, or eliminate it.  The `hdf5` dependency was in some optional filter tests, not in the core library.  Disabling the optional tests seems to have no impact on the core library build.
Furthermore, enabling filter tests installed some extra bundled plugins, which may have conflicted with plugins installed by the main `hdf5` port.
I chose to eliminate the `hdf5` dependency as the safer strategy.
macOS 13.6.4
Xcode 15.2 / Command Line Tools 15.1.0
Have you
> netcdf-cxx4: Remove overlinking to HDF5

- gnome/grisbi/Portfile
Just a small simplification.
Have you
> grisbi: Use files directly instead of copying them

- graphics/tinygltf/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> tinygltf: update to 2.8.22

- science/cdo/Portfile
Simple update to upstream version 2.4.1
Have you
> cdo: update to 2.4.1

- graphics/xvega/Portfile
- graphics/xvega/files/0001-CMakeLists-fix-optflags-for-PowerPC-case.patch
Unbreak build on powerpc
macOS 10.6
Xcode 3.2
Have you
> xvega: fix build on powerpc

- devel/legacy-support/Portfile
- stpncpy: Fix potential header collision with "later" SDK
- provide workaround for pthread_get_stacksize_np
macOS x.y
Have you
> legacy-support: update to v1.2.4

- _resources/port1.0/group/rust-1.0.tcl
> rust PG: fix for early CLT that did not install SDKs

- devel/zix/Portfile
- devel/zix/files/fdatasync.patch
Closes: https://trac.macports.org/ticket/70070
Have you
> zix: Avoid fdatasync on macOS

- sysutils/stern/Portfile
Update to Stern 1.30.0.
Have you
> stern: update to 1.30.0

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.3. [Changelog](https://github.com/astral-sh/uv/releases/tag/0.2.3) and [diff@`0.1.42...0.2.3`](https://github.com/astral-sh/uv/compare/0.1.42...0.2.3)
Have you
> uv: Update to 0.2.3

- games/2048.c/Portfile
Update `2048.c` to its latest released version, 1.0.1
Have you
> 2048.c: Update to 1.0.1

- java/maven3/Portfile
Update to Maven 3.9.7.
Have you
> maven3: update to 3.9.7

- archivers/unrar/Portfile
* blacklist GCC 3/4
* remove redundant legacysupport portgroup
Have you
> unrar: update to 7.0.9

- java/openjdk22-openj9/Portfile
New port for IBM Semeru 22.
Have you
> openjdk22-openj9: new submission

- security/KeePassXC/Portfile
fix extract on older versions of os
In theory this is something that upstream could fix but since they don't seem terribly interested in issues on older versions I'm not sure they'd go for it. In the meantime this allowed me to install and confirm the app works.
Have you
> keepassxc: update to 2.7.8

- gis/GPXSee/Portfile
> GPXSee: update to 13.20

- java/tomcat-native/Portfile
tomcat-native: update to version 1.3.0
Have you
> tomcat-native: update to version 1.3.0

- math/primesieve/Portfile
no longer needs manually-added libatomic on
some gcc builds
Have you
> primesieve: update to 12.3

- graphics/pqiv/Portfile
- graphics/pqiv/files/patch-gcc-4.diff
Fix building with old gcc
macOS 10.6
Xcode 3.2
Have you
> pqiv: fix build with gcc-4.x

- emulators/mednafen/Portfile
https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/271897/steps/install-port/logs/stdio
Have you
> mednafen: blacklist clang < 800

- audio/rnnoise/Portfile
https://github.com/macports/macports-ports/pull/23833#issuecomment-2102874545
Needed for PowerPC machines, but there's no particular reason to use legacy compilers with this port anyway.
Have you
> rnnoise: blacklist GCC 3/4

- multimedia/dmapd/Portfile
[skip ci]
This port is broken old all new systems: https://ports.macports.org/port/dmapd/details
Therefore skipping CI.
P. S. It should be perhaps updated, but that will likely require updating its dependencies, and that is rather to be done in a separate PR. Let’s fix this first.
macOS 10.6
Xcode 3.2
Have you
> dmapd: fix build on old systems

- devel/libdmapsharing/Portfile
Fix, also minor non-functional layout improvement.
macOS 10.6
Xcode 3.2
Have you
> libdmapsharing: fix build on older systems

- gnome/gtk3-devel/Portfile
- gnome/gtk3/Portfile
- graphics/libepoxy/Portfile
Currently `gtk3` depends on `mesa` and other `x11` related packages even when building with `+quartz -x11`. This dependency was required through `gtk3`'s dependency on `libepoxy`, which pulls those build-dependencies in to support GLX and proposes to make them required by dependees at link time.
From what I could find out, GLX is also specific to X11 and thus not required when building with `+quartz -x11`.
This PR removes the build dependency on `mesa` and cohorts from `libepoxy` and the lib-dependency from `gtk3`, if variant is `+quartz`.
This was sufficient to make `gstreamer1-gst-plugins-good +quartz -x11` installable again (related track ticket: [https://trac.macports.org/ticket/69787](https://trac.macports.org/ticket/69787). I therefor did not check further dependees of `libepoxy` …
> gtk3, libepoxy: Remove dependency to mesa for +quartz

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.4
Have you
> uv: Update to 0.2.4

- java/openjdk20-openj9/Portfile
Obsolete IBM Semeru 20, replaced by IBM Semeru 21.
Have you
> openjdk20-openj9: obsolete, replaced by openjdk21-openj9

- java/micronaut/Portfile
Update to Micronaut Starter 4.4.3.
Have you
> micronaut: update to 4.4.3

- graphics/libbpg/Portfile
Fix the port for old systems
macOS 10.6
Xcode 3.2
Have you
> libbpg: avoid old Xcode gcc

- graphics/converseen/Portfile
- graphics/converseen/files/patch-fix-formats.diff
Provide a version for older systems 
macOS 10.6
Xcode 3.2
Have you
> converseen: provide version for < 10.10

- math/fgsl/Portfile
* Update FGSL 1.5.0 --> 1.6.0.
* Version 1.6.0 is for use with GSL 2.7 and later GSL versions.
* Maybe fix 10.7 Lion build, using compiler blacklist.
Xcode 15.2 / Command Line Tools 15.1.0
Have you
> fgsl: Update to 1.6.0

- databases/dblab/Portfile
> dblab: update to 0.23

- databases/mycli/Portfile
Bring port up to date.
Have you
> mycli: update to 1.27.2

- lang/kotlin/Portfile
Update to Kotlin 2.0.0.
Have you
> kotlin: update to 2.0.0

- audio/rtaudio/Portfile
The is still unfixed. Fix it finally.
macOS 10.6
Xcode 3.2
Have you
> rtaudio: use required C++11 standard

- gnome/gtk3-devel/Portfile
- gnome/gtk3/Portfile
This is a followup to PR #23760, which ensures that the `x11` and `quartz` variant of `gtk3` matches the respective variant of `libepoxy`. See the discussion on [the corresponding commit](https://github.com/macports/macports-ports/commit/4fb8088b2838539db152705c8ec612d71aa4d237#commitcomment-142465364).
Have you
> gtk3: Require matching x11/quartz variant of libepoxy

- lang/clang-11-bootstrap/Portfile
- lang/clang-11-bootstrap/files/0009-x86-pad-for-align.diff
- lang/llvm-11/Portfile
- lang/llvm-11/files/0009-x86-pad-for-align.diff
See https://github.com/llvm/llvm-project/commit/a048ce13e32daa255d26533c00da8abd0b67e819
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100340
See https://trac.macports.org/ticket/62775
macOS x.y
Have you
> llvm-11, clang-11-bootstrap: apply upstream patch

- graphics/xfig/Portfile
Fix for old systems
macOS 10.6
Xcode 3.2
Have you
> xfig: avoid old Xcode gcc to fix build on old OS

- net/lexbor/Portfile
- net/lexbor/files/0001-perf.c-fix-for-powerpc.patch
Fix build on old systems, support testing.
See: https://github.com/lexbor/lexbor/issues/226
macOS 10.6
Xcode 3.2
Have you
> lexbor: fix build on old systems and support tests

- gnome/planner/Portfile
Fix build on old OS
macOS 10.6
Xcode 3.2
Have you
> planner: avoid old Xcode gcc to fix build on old macOS

- science/bali-phy/Portfile
- science/bali-phy/files/patch-bitset.diff
Fixes: https://trac.macports.org/ticket/70096
Fix
macOS 10.6
Xcode 3.2
Have you
> bali-phy: add missing include to fix build

- devel/libgnt/Portfile
- devel/libgnt/files/patch-PANEL.diff
Backport a fix.
macOS 10.6
Xcode 3.2
Have you
> libgnt: backport upstream patch to fix the build

- graphics/openimageio/Portfile
Fix the port:
1. Disable `openvdb` for Darwin < 20, due to https://trac.macports.org/ticket/69842
2. Since GUI requires Qt5 5.6+, build with GUI on 10.7+.
3. Unbreak build with GCC.
macOS 10.6
Xcode 3.2
Have you
> openimageio: fix the build for Darwin < 20 and powerpc

- kde/ktorrent4/Portfile
Fix C++ standard
_CI failure unrelated._
macOS 10.6
Xcode 3.2
Have you
> ktorrent4: set cxx_standard 2011

- lang/algol68g/Portfile
Fix after a breaking update of `gsl`
macOS 10.6
Xcode 3.2
Have you
> algol68g: revbump for gsl update

- math/gsl/Portfile
- math/gsl/files/patch-fix-linking.diff
Fix linking
macOS 10.6
Xcode 3.2
Have you
> gsl: drop a breaking ldflag added in 2.8 configure

- devel/spdlog/Portfile
Update
macOS 14.5
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you
> spdlog: update to 1.14.1

- audio/unixcw/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> unixcw: fix build for older systems

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.483
Have you
> ipsw: Update to 3.1.483

- net/nextdns/Portfile
netlink dependency removed in 1.43.0
Have you
> nextdns: update to 1.43.5

- ruby/ruby-build/Portfile
ruby-build: Upgrade to 20240530.1
macOS 14.5 23F79 arm64 Xcode 15.4 15F31d
Have you
same change?
> ruby-build: Upgrade to 20240530.1

- science/oof2/Portfile
- science/oof2/files/patch-disable-broken-altivec-in-eigen.diff
Fix powerpc build
macOS 10.6
Xcode 3.2
Have you
> oof2: fix build on PowerPC

- math/pspp-devel/Portfile
- math/pspp/Portfile
For `pspp` also blacklist archaic Xcode gcc.
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.3
Have you
> pspp*: revbump for gsl update

- ocaml/opam/Portfile
Updating the opam package repository can silently fail when using macos patch whenever files are removed upstream. As of opam 2.1.6 there is a warning on install to
manually install gpatch to avoid any possible issue and the corruption of the local switches. See also https://github.com/ocaml/opam-repository/issues/25961
This commit adds a dependency to gpatch to prevent any issue and avoid unnecessary manual intervention.
Have you
> update opam Portfile: add dependency on gpatch

- science/nco/Portfile
Revbump needed for `nco` because `libgsl.27.dylib` became `libgsl.28.dylib` with the latest `gsl` update.
Have you
> nco: revbump because of gsl version update

- multimedia/frei0r-plugins/Portfile
Xcode gcc cannot build this.
macOS 10.6
Xcode 3.2
Have you
> frei0r-plugins: fix build on old systems

- science/bladeRF/Portfile
Port is forcing docs variant which pulls in Pandoc dependency. While this is generally problematic, on PowerPC Pandoc is just broken.
So add a variant conditionally.
macOS 10.6
Xcode 3.2
Have you
> bladeRF: unbreak port on PowerPC via fixing default variants

- ocaml/ocaml-ppx_import/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> ocaml-ppx_import: update to 1.11.0

- sysutils/g-ls/Portfile
Update `g-ls` to its latest released version, 0.28.0, while adding new completions for other terminals
Have you
> g-ls: Update to 0.28.0

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.4.7
Have you
> ruff: Update 0.4.7

- sysutils/mactop/Portfile
The log file is currently hardcoded to /var/log [1] so change this to
$prefix/var/log.
[1] https://github.com/context-labs/mactop/commit/52b618c1cc383a81b5fa50c80853b9569b92e15b
Have you
> mactop: write log file in $prefix/var/log

- multimedia/mlt-legacy/Portfile
- multimedia/mlt-legacy/files/patch-RtAudio.cpp.diff
- multimedia/mlt-legacy/files/patch-enforce-cxx14.diff
- multimedia/mlt-legacy/files/patch-filter_rbpitch.cpp.diff
- multimedia/mlt-legacy/files/patch-numeric_limits.diff
- multimedia/mlt-legacy/files/patch-sdl2-x11.diff
- multimedia/mlt/Portfile
I make it in a separate port, since adding a third Qt into `mlt` which uses a different build system is completely unnecessary and will be painful to maintain for `mlt` maintainers and myself alike.
Instead of restoring an outdated 6.x we had, I update it to the last release of 6.x branch.
macOS 10.6
Xcode 3.2
Have you
> mlt-legacy: new port

- audio/cava/Portfile
Allow building on old systems.
macOS 10.6
Xcode 3.2
Have you
> cava: avoid opengl on old macOS

- sysutils/mc/Portfile
This is the port of Homebrew/homebrew-core#173306 to MacPorts. I now know thanks to Homebrew CI that it at least works on all still supported macOS versions. Original description follows.
---
We introduced support for nanosecond timestamps with `utimensat` years ago and only enabled it if OS supported it.
This "worked" fine util macOS 10.13 High Sierra, when Apple introduced `utimensat` in a half-assed POSIX-incompatible way (apparently the name of the the `st` structure members were like `st_atimespec` instead of `st_atim` etc.). So the function was there, but our code couldn't use it and builds failed.
We neither had macOS, nor the kernel was published, so we couldn't fix it and the workaround here was to disable `utimensat` by force even if it was available.
I have now checked the …
> mc: remove build workaround for macOS 10.13 (High Sierra)

- sysutils/g-ls/Portfile
Update `g-ls` to its latest released version, 0.28.2
Have you
> g-ls: Update to 0.28.2

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.485
Have you
> ipsw: Update to 3.1.485

- math/vdt/Portfile
_Why was it even done this way?_
macOS 10.6
Xcode 3.2
Have you
> vdt: unbreak build on powerpc

- audio/ncmpcpp/Portfile
Switch to a properly working Boost.
macOS 10.6
Xcode 3.2
Have you
> ncmpcpp: switch to boost181 to fix gcc build, revbump

- net/youtube-dl/Portfile
yt-dlp: update to 2024.05.27
Have you
> yt-dlp: update to 2024.05.27

- _resources/port1.0/group/npm-1.0.tcl
- devel/bash-language-server/Portfile
- devel/eask-cli/Portfile
- devel/pnpm/Portfile
- devel/pyright/Portfile
- devel/typescript-language-server/Portfile
- security/bitwarden-cli/Portfile
Trying again with a clean slate from https://github.com/macports/macports-ports/pull/23658
Have you
> npm portgroup: use latest LTS release for default

- devel/codeblocks-devel/Portfile
Earlier version was building but not launching. Now it works.
P. S. Revbumping needed, because build was not broken, but wrong library version was used.
macOS 10.6
Xcode 3.2
Have you
> codeblocks-devel: fix for systems building with gcc using `libstdc++`

- java/openjdk17-openj9/Portfile
Update to IBM Semeru 17.0.11.
Have you
> openjdk17-openj9: update to 17.0.11

- java/openjdk21-openj9/Portfile
Update to IBM Semeru 21.0.3.
Have you
> openjdk21-openj9: update to 21.0.3

- java/openjdk11-openj9/Portfile
Update to IBM Semeru 11.0.23.
Have you
> openjdk11-openj9: update to 11.0.23

- java/openjdk8-openj9/Portfile
Update to IBM Semeru 8u412.
Have you
> openjdk8-openj9: update to 8u412

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 478.0.0.
Have you
> google-cloud-sdk: update to 478.0.0

- graphics/vips/Portfile
As suggested in https://trac.macports.org/ticket/69691 added `libarchive` to the dependencies.
Also updated vips to v8.15.2 and added `configure.cflags-append -Wno-incompatible-function-pointer-types` to allow for compilation on Macos-14.
Have you
`sudo port -vs install vips` works as expected but `sudo port -vst install vips` fails.
> vips: updated to 8.15.2, added libarchive to support vips dzsave and fixed macos-14 compilation

- archivers/zstd/Portfile
- archivers/zstd/files/flags.patch
- archivers/zstd/files/patch-prper_linker_flags.diff
- archivers/zstd/files/patch-zstd-tiger-no-backtrace.diff
> zstd: properly handle link flag with space

- gis/rsgislib/Portfile
Has to be revbumped for gsl updated, also fix gcc build in the same go.
macOS 10.6
Xcode 3.2
Have you
> rsgislib: revbump for gsl update and use boost181 to fix gcc build

- databases/sqlcipher/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> sqlcipher: update to 4.6.0

- devel/bun/Portfile
- devel/bun/bun/Portfile
[Bun](https://bun.sh) is a nodeJS-compatible JavaScript runtime focused on speed. This port uses the `npm` port group.
I wasn't able to build with `-t`, but this seems to be an Apple Silicon issue rather than an issue with the Portfile.
Have you
> Submission: Bun

- net/newsraft/Portfile
- net/newsraft/files/patch-makefile.diff
Update. Also needed due to `gumbo-parser` update in https://github.com/macports/macports-ports/pull/24110
macOS 10.6
Xcode 3.2
Have you
> newsraft: update to 0.24

- aqua/LimeChat/Portfile
Avoid building again in destroot
macOS x.y
Have you
> LimeChat: sign app bundle on 13.0 and later

- python/pipx/Portfile
pipx: update to 1.6.0
Have you
> pipx: update to 1.6.0

- devel/ccache/Portfile
> ccache: update to 4.10

- www/nghttp2/Portfile
C++20 is not required to build nghttp2. It's only required to build the nghttp2-tools subport. Removing this requirement for nghttp2 allows the port to build on Snow Leopard and earlier again and will allow the curl port to enable http2 support for all macOS versions.
Closes: https://trac.macports.org/ticket/65066
Closes: https://trac.macports.org/ticket/70027
Closes: https://trac.macports.org/ticket/70048
Running autoreconf is not needed anymore since the configure.ac patch was removed years ago.
Closes: https://trac.macports.org/ticket/70141
Have you
> nghttp2: Remove C++20 requirement and don't autoreconf anymore

- graphics/wxWidgets-3.0/Portfile
- graphics/wxWidgets-3.0/files/patch-no-osx-evtloopsrc.h.diff
Addresses a missing header issue which prevents building `wxMaxima` with GTK backend.
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.3
Have you
> wxGTK-3.0: fix for a missing header bug

- audio/FAudio/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> FAudio: update to 24.06

- devel/pika/Portfile
Simple update
_CI on macOS-13 gonna fail, I guess, due to a broken MPICH._
macOS 10.6
Xcode 3.2
Have you
> pika: update to 0.25.0

- lang/sdcc/Portfile
This is unneeded for gcc build and does not work correctly with those. Restrict it to clangs (which are used by default anyway).
macOS 10.6
Xcode 3.2
Have you
> sdcc: use -stdlib= only for clang

- audio/libclastfm/Portfile
- audio/libclastfm/files/patch-fix-linking.diff
New port
macOS 14.5
Xcode 15.3
macOS 10.6
Xcode 3.2
Have you
> libclastfm: new port

- devel/talloc/Portfile
> talloc: required thread_local_storage

- security/ipsw/Portfile
Update `ipsw` to its latest released verison, 3.1.488
Have you
> ipsw: Update to 3.1.488

- databases/tdb/Portfile
And here also.
macOS 10.6
Xcode 3.2
Have you
> tdb: requires thread_local_storage

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.6.
`libgit2` (and thus `openssl3`) are no longer needed after this release: https://github.com/astral-sh/uv/commit/261aa2c70a93e1705f6bcea142c7cf71d7666dfa
Have you
> uv: Update to 0.2.6

- multimedia/ffms2/Portfile
Fix build for older systems
macOS 10.6
Xcode 3.2
Have you
> ffms2: set required C++11 standard, fix build deps

- editors/emacs/Portfile
- editors/emacs/files/site-start-app.el
- editors/emacs/files/site-start.el
~~The reason for this change is that the canonical way to use the new tree-sitter functionality in Emacs 29 is to either configure Emacs yourself to have it compile the libraries for you automatically or use a package like [treesit-auto](https://melpa.org/#/treesit-auto). Emacs upstream frequently assumes whatever the HEAD was in the tree-sitter grammar repo when the Elisp code was written and pays little attention to the differences between HEAD and the last released version, which frequently falls far behind HEAD by years and thus miss out on lots of the latest changes in the languages. There's also an ever increasing number of these language libraries but no reasonable Emacs users will ever require all of them. Let's make these a do-it-yourself part of Emacs as the users are so …
> emacs: Prevent Macports tree-sitter grammar libs from shadowing

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.9.1

- science/gildas/Portfile
- science/gildas/files/patch-admin-Makefile.build.diff
> Gildas: update to 202406a

- multimedia/zvbi/Portfile
Fixes: https://trac.macports.org/ticket/70160
Fix this finally
macOS 10.6
Xcode 3.2
Have you
> zvbi: disable rpath

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.490
Have you
> ipsw: Update to 3.1.490

- net/gallery-dl/Portfile
gallery-dl: update to 1.27.0
Have you
> gallery-dl: update to 1.27.0

- multimedia/ffmpeg-devel/Portfile
For now, in -devel port.
macOS 10.6
Xcode 3.2
Have you
> ffmpeg-devel: enable sdl2 on powerpc

- devel/glib2-devel/Portfile
- devel/glib2-devel/files/patch-meson_build-meson_options-appinfo.diff
For applications such as nautilus who require x11 the
gio-launch-desktop bin is a requirement for some functions.
By adding the patch for build quartz(native) or x11(generic)
This add was forgotten for build of x11.
With this modified patch it is back in.
the last part of patch :
devel/glib2/files/patch-meson_build-meson_options-appinfo.diff
has been modified and in section generic build this part below is added
```
launch_desktop_sources = files('gio-launch-desktop.c')
gio_launch_desktop = executable('gio-launch-desktop', launch_desktop_sources,
include_directories : glibinc,
install : true,
install_dir : multiarch_libexecdir,
install_tag : 'bin',
c_args : gio_c_args,
link_args : noseh_link_args)
```
I also included a port bump revision from 0 to 1 . Tested by me by building without -s …
> glib2-devel Adapted patch to include gio-launch-desktop bin in x11 (generic)

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.4.8
Have you
> ruff: Update to 0.4.8

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.8
Have you
> uv: Update to 0.2.8

- x11/fireworkx/Portfile
Upbreak ppc and avoid cpu-specific optimizations generally.
macOS 10.6
Xcode 3.2
Have you
> fireworkx: do not use -march=native

- graphics/rgb-tui/Portfile
Update notes
macOS 10.6
Xcode 3.2
Have you
> rgb-tui: non-functional: add port notes re true color support

- mail/notmuch/Portfile
Building with gcc-4.2 fails earlier for other reasons, but blacklisting does not work, since it actually also requires C++11, so just set that.
macOS 10.6
Xcode 3.2
Have you
> notmuch: needs C++11

- graphics/pympress/Portfile
This adds the new port [`pympress`](https://github.com/Cimbali/pympress), a python viewer for presentations in pdf format (e.g., create with LaTeX beamer) that also supports showing embedded videos and audio.
Have you
> pympress: new port

- multimedia/bento4/Portfile
- multimedia/bento4/files/patch-CMakeLists.diff
- multimedia/mp4v2/Portfile
Also add conflict with mp4v2
macOS 10.6
Xcode 3.2
Have you
> bento4: fix build with gcc

- octave/octave-fits/Portfile
- octave/octave-fits/files/patch-fits-3-octave-9-compat.diff
Closes: https://trac.macports.org/ticket/70041
Fix build with gcc
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.3
Have you
> octave-fits: fix build with gcc

- science/zfp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> zfp: update to 2024.05.18

- devel/ace/Portfile
- devel/ace/files/patch-ace-config.h.diff
- devel/ace/files/patch-include-makeinclude-platform_macros.GNU.diff
* update to version 8.0.0
* remove includes of version-specific configuration files since the distro solves that internally
* remove unused code from the portfile
- `[x]` enhancement
Xcode 15.4 15F31d / Command Line Tools 15.3.0.0.1.1708646388
Have you
> ace: update to version 8.0.0

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.491
Have you
> ipsw: Update to 3.1.491

- python/py-pdal-plugins/Portfile
- python/py-pdal-plugins/files/patch_pyproject_pybind11.diff
- python/py-pdal/Portfile
- python/py-pdal/files/patch_pyproject_pybind11.diff
- Update `py-pdal` to 3.4.3 and drop py38.
- New port `py-pdal-plugins` version 1.5.0.
Have you
> py-pdal: update to 3.4.3; py-pdal-plugin: new port 1.5.0

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.9
Have you
> uv: Update to 0.2.9

- x11/sakura/Portfile
New port: https://launchpad.net/sakura
macOS 10.6
Xcode 3.2
Have you
> sakura: new port, a terminal emulator

- sysutils/caps-log/Portfile
New port
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.3
Have you
> caps-log: new port

- sysutils/caps-log/Portfile
Needs `filesystem`
https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/236962/steps/install-port/logs/stdio
macOS x.y
Have you
> caps-log: use legacysupport for older systems with libc++

- ocaml/ocaml-camlp5-buildscripts/Portfile
> camlp5-buildscripts: new port 0.03

- editors/neovim/Portfile
- editors/neovim/files/embed-parsers-build.diff
**I consider this patch as some kind of WIP proposal. Perhaps things like the path to the cmake executable or its args should be filled dynamically from macports defaults. But I do not know the best practices for this specific case so I feel free to just push on top of this if it needs refinement.**
neovim needs a number of prebuilt parsers in <prefix>/lib/nvim/parser/ or else it will throw errors when opening e.g. ":help". USE_BUNDLED is also not a valid option for the root cmake build system anymore, but applies to the one in cmake.deps/.
Closes: https://trac.macports.org/ticket/70072
macOS 15.5
Xcode 15.3 / Command Line Tools 15.3.0
Have you
> neovim: Build and install tree-sitter parsers

- devel/xcode-build-server/Portfile
Update the `xcode-build-server` port to version 1.1.0
Have you
> xcode-build-server: update to 1.1.0

- gis/JOSM/Portfile
macOS 12.6.7 x86_64
Xcode 14.2
Have you
> josm: update to 19096

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.55.0

- gis/GPXSee/Portfile
> GPXSee: update to 13.21

- devel/bun/Portfile
Update Bun port to 1.1.12
Have you
> Update: Bun 1.1.12

- devel/libabw/Portfile
C++11 is required
macOS 10.6
Xcode 3.2
Have you
> libabw: set required C++11 standard

- lisp/cl-cffi-gtk/Portfile
Specify the cairo, glib2, gtk3, and gdk-pixbuf2 dependencies the way other ports do, by referencing the .pc file (not by the .dylib file since that would not exist on non-macOS operating systems). Reference each port only once. Alphabetize deps by port name.
> cl-cffi-gtk: Standardize dependencies

- .github/workflows/main.yml
The macos-11 runner is slated for removal by the end of the month with brownouts scheduled to occur in the weeks leading up to that.
> CI: Remove macos-11

- net/pkixssh/Portfile
Make this a bit better.
macOS 10.6
Xcode 3.2
Have you
> pkixssh: allow builds with gcc, move keychain in a variant

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.492
Have you
> ipsw: Update to 3.1.492

- gis/gdal/Portfile
Fixes: https://trac.macports.org/ticket/70193
Recent update ignored C++17 requirement.
macOS 10.6
Xcode 3.2
Have you
> gdal: unbreak after update to 3.9.0

- gnome/gcab/Portfile
- gnome/gcab/files/allow-xcode-gcc.patch
Fix for old gcc
macOS 10.6
Xcode 3.2
Have you
> gcab: fix build with old Xcode gcc

- python/py-bugsnag/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> py-bugsnag: update to 4.7.1

- lang/camlp5/Portfile
* Remove dependences that are only used in tests (ounit, pcre2)
* Add missing dependency declared in opam which is not strictly required but expected by other software (camlp5-buildscript)
* Add missing dependency that was installed by transitiveness (ocaml-findlib)
* add `bin:perl:perl5` as a dependency in case perl is not present
* sort dependencies in opam order
Have you
> camlp5: synchronize dependencies with opam

- cross/msp430-elf-binutils/Portfile
Texas Instruments use a strange version system. The website says 9.3.1.2,
release notes say 9.3.1.11 but the binutils patch is based on version 2.34.
Opted for the later to follow the gnu tools versioning.
Have you
> msp430-elf-binutils: update to version 2.34

- gnome/tracker3/Portfile
- gnome/tracker3/files/patch-meson.build-32.diff
- gnome/tracker3/files/patch-meson.build.diff
New port, a dependency for newer versions of `nautilus` and a few others.
No conflict needed, it is co-installable with `tracker`.
macOS 10.6
Xcode 3.2
Have you
> tracker3: new port in gnome

- python/py-qt4py/Portfile
Add a standalone port exclusively for powerpc systems, which do not currently support Qt5+.
macOS 10.6
Xcode 3.2
Have you
> py-qt4py: Qt4 version to support powerpc systems

- python/py-msgpack/Portfile
- python/py-msgpack/files/patch-32-bit.diff
Fixes: https://trac.macports.org/ticket/69537
@stromnov Sorry for a delay with this.
`UL` still fails, `ULL` works.
macOS 10.6
Xcode 3.2
Have you
> py-msgpack: fix for 32-bit

- science/wdsp/Portfile
Old gcc cannot build this.
macOS 10.6
Xcode 3.2
Have you
> wdsp: blacklist old Xcode gcc, fix for old systems

- devel/libmsp430/Portfile
- devel/libmsp430/files/bsl430dll_makefile.diff
- devel/libmsp430/files/makefile.diff
The MSP430 opensource toolchain requires a USB driver provided by Texas Instruments under the name MSP Debug Stack. It installs a dynamic library called `libmsp430.dylib` which can be used by mspdebug and other tools.
Have you
> libmsp430: new port

- net/net-snmp/Portfile
- net/net-snmp/files/patch-legacy-compat.diff
Fixes: https://trac.macports.org/ticket/70165
Fix
macOS 10.6
Xcode 3.2
Have you
> net-snmp: fix for older systems

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.10
Have you
> uv: Update to 0.2.10

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.493
Have you
> ipsw: Update to 3.1.493

- python/py-cgmetadata/Portfile
New port for CGMetadata.
Have you
> py-cgmetadata: new submission
