sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.2.0

editors/sigil-qt4/Portfile, editors/sigil-qt4/files/patch-newboost.diff, editors/sigil/Portfile
Plus minor improvements.
macOS 10.6
Xcode 3.2
Have you
=> sigil: minor improvements; sigil-qt4: new port

devel/cyclonedds/Portfile, devel/cyclonedds/files/0001-threads.c-fix-for-pthread_threadid_np-on-macOS.patch, devel/cyclonedds/files/0002-threads.c-provide-def-of-MAXTHREADNAMESIZE-when-unde.patch, devel/cyclonedds/files/0003-ddsi_udp.c-use-ip_mreqn-where-it-is-actually-availab.patch, devel/cyclonedds/files/0004-crypto_transform.c-fix-memcpy.patch, devel/cyclonedds/files/0005-Fix-unresolved-symbol-on-big-endian-architectures.patch
Fix the build
macOS 10.6
Xcode 3.2
Have you
=> cyclonedds: fix build on earlier macOS

lang/logtalk/Portfile
=> logtalk: update to 3.80.0

kde/kdepim4-runtime/Portfile, kde/kdepim4/Portfile
Fix ports.
_CI on some versions will fail for unrelated reasons._
macOS 10.6
Xcode 3.2
Have you
=> kdepim4*: fix compiler choice

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.2.1

net/mosh/Portfile, net/mosh/files/patch-fix-AltiVec.diff
Fix the build, for now disabling a broken Altivec.
macOS 10.6
Xcode 3.2
Have you
=> mosh: unbreak build on powerpc

science/proxmark3-iceman/Portfile
Updating `proxmark3-iceman` to v4.18589, Python 3.12 is still not supported; will be spearheading work on it upstream.
Have you
=> proxmark3-iceman: update to 4.18589

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.2.2

python/py-scikit-build-core/Portfile
Update `py-scikit-build-core` to version 0.9.5.
Have you
=> py-scikit-build-core: update to 0.9.5

math/blaspp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> blaspp: update to 2024.05.31

math/arborx/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> arborx: update to 1.6

math/superlu_dist/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> superlu_dist: update to 9.0.0

lang/MoarVM/Portfile, lang/nqp/Portfile, lang/rakudo/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rakudo and friends: update to 2024.05

multimedia/libass/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libass: update to 0.17.2; libass-devel: update to 2024.06.02

genealogy/geneweb/Portfile, genealogy/geneweb/files/patch-Makefile-PR1806.diff, ocaml/ocaml-not-ocamlfind/Portfile, ocaml/ocaml-not-ocamlfind/files/patch-Makefile.diff, ocaml/ocaml-ocamlgraph/Portfile, ocaml/ocaml-ppx_blob/Portfile
Also:
* Bump revision of ocaml-ppx_blob as it needs to be recompiled after ocaml-ppxlib update
* Add port ocaml-not-ocamlfind that geneweb fixes requires
* Add port ocaml-ocamlgraph that ocaml-not-ocamlfind requires
Have you
=> Fix geneweb incompatibility with camlp5 8.03.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.3.0

python/py-awscli2/Portfile
=> py-awscli2: update to 2.16.2

math/stan/Portfile, math/stanmath/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> stan, stanmath: update to current releases

math/bpack/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> bpack: update to 3.1.0

lang/fortran-stdlib/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> fortran-stdlib: update to 2024.06.06

ocaml/ocaml-merlin/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ocaml-merlin: update to 4.14-414

graphics/rawproc/Portfile
This port also needs `filesystem`
macOS x.y
Have you
=> rawproc: use legacysupport for filesystem

multimedia/mpv-legacy/Portfile
Closes: https://trac.macports.org/ticket/69268
Fix support for ffmpeg (several components require higher versions than ffmpeg4 provides), fix coreaudio variant.
Use sdl2.
macOS 10.6
Xcode 3.2
Have you
=> mpv-legacy: fix coreaudio, switch to ffmpeg6

devel/libsdl2-powerpc/Portfile
Some improvements
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: add variants, minor fix to deps, revbump

x11/mlterm/Portfile
Improve the port
macOS 10.6
Xcode 3.2
Have you
=> mlterm: use gtk3 by default, add variants for gtk2 and sdl2

gnome/zenity/Portfile, graphics/geeqie/Portfile
These are broken by unjustified defaults.
macOS 10.6
Xcode 3.2
Have you
=> geeqie: update to 2.4, fix for older systems; zenity: fix for old systems

multimedia/audacious-core/Portfile, multimedia/audacious-plugins/Portfile
See: https://trac.macports.org/ticket/69585
=> audacious-*: Fix gtk2 and gtk3 dependencies

aqua/qtiplot/Portfile
Revbump this finally
macOS 10.6
Xcode 3.2
Have you
=> qtiplot: revbump upon gsl update

editors/treesheets/Portfile, editors/treesheets/files/0001-lobster-tools.h-avoid-conflicting-define-for-ssize_t.patch
Long due update
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.4
Have you
=> treesheets: update new systems to 20240609, old systems to 20230408

net/snac/Portfile
=> snac: update to 2.54

net/snac/Portfile
=> snac: update to 2.55

science/elmerfem/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> elmerfem: update to 2024.06.07

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.4.0

gis/pdal/Portfile
Increase revision for `pdal` after GDAL update to 3.9.0.
Closes: https://trac.macports.org/ticket/70196
macOS x.y
Have you
=> pdal: increase revision after GDAL update to 3.9.0

gnome/appstream/Portfile, gnome/appstream/files/patch-use-correct-include-dir.diff, gnome/libadwaita/Portfile, gnome/libadwaita/files/patch-fix-adw-settings-impl-macos.diff
This port is needed as a dependency for new Gnome stuff.
macOS 10.6
Xcode 3.2
Have you
=> libadwaita: new port in gnome

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.5.0

science/gnuastro/Portfile
This has to be revbumped too
macOS x.y
Have you
=> gnuastro: revbump upon gsl update

cross/msp430-gcc-support-files/Portfile
Update to version 1.212.
Have you
=> msp430-gcc-support-files: update to version 1.212

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.6.0

ruby/ruby-build/Portfile
macOS 14.5 23F79 arm64 Xcode 15.4 15F31d
Have you
same change?
=> ruby-build: Upgrade to 20240612

math/HiGHS/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> HiGHS: update to 1.7.1

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.16.8

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.8.0

science/volk/Portfile, science/volk/files/0001-cpu_features_macros.h-fix-PowerPC-macros.patch
Fix build on ppc
macOS 10.6
Xcode 3.2
Have you
=> volk: unbreak build on ppc

_resources/port1.0/group/R-1.0.tcl, math/R/Portfile
=> R: update to 4.4.1

devel/mediainfolib/Portfile, multimedia/mediainfo/Portfile
Update, fix
macOS 10.6
Xcode 3.2
Have you
=> MediaInfo*: update to 24.05, fix GUI for old macOS

devel/getdns/Portfile, devel/getdns/files/patch-xcode-gcc.diff, net/stubby/Portfile
Fix build with gcc-4.2
macOS 10.6
Xcode 3.2
Have you
=> getdns, stubby: fix build with Xcode gcc

x11/xscreensaver/Portfile
=> xscreensaver: update to 6.09

shells/tcsh/Portfile
=> tcsh: update to 6.24.13

x11/gobby/Portfile
Also path-style dep for `gnutls`
macOS 10.6
Xcode 3.2
Have you
=> gobby: requires C++11

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.10.0

emulators/wine-devel/Portfile
=> wine-devel,wine-staging: Update to 9.11

net/c-ares/Portfile, net/c-ares/files/patch-fix-build-pre-10.12.diff
Fixes: https://trac.macports.org/ticket/70208
Fixes: https://trac.macports.org/ticket/70207
macOS 10.6
Xcode 3.2
Have you
=> c-ares: fix for older systems

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.10.2

emulators/uxn/Portfile
=> uxn: update to 20240614

net/nghttp3/Portfile, net/ngtcp2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> nghttp3: update to 1.4.0; ngtcp2: update to 1.6.0

fortran/fortran-json/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> fortran-json: update to 9.0.1

fortran/fortran-csv-module/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> fortran-csv-module: update to 2.0.1

fortran/feq-parse/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> feq-parse: update to 2024.06.15

textproc/cfonts/Portfile
=> cfonts: update to 1.2.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.11.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.12.0

sysutils/pv/Portfile
=> pv: 1.8.10

python/py-pydicom/Portfile
=> py-pydicom: 2.4.4

sysutils/initool/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> initool: update to 0.18.0

python/py-absl/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-absl: update to 2.1.0

python/py-pydicom/Portfile
=> py-pydicom: Add 312 version

science/bart/Portfile
=> bart: 0.9.00

science/bart/Portfile
=> BART: don't attempt failing (old OS) builds; tweaks to build

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.13.1

lang/eiffelstudio/Portfile
macOS x.y
Have you
Updated: make the homepage url https.
Added the tools/sepc in the PATH.
Closes:  https://github.com/macports/macports-ports/pull/24534
=> eiffelstudio: update to version 24.05

devel/bun/Portfile
=> Bun: Update to 1.1.14

lang/algol68g/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> algol68g: update to 3.5.4

net/librdkafka/Portfile, net/librdkafka/files/patch-unbreak-configure.diff
Fix compiler choice.
Fix configure: remove Linux-only flag.
macOS 10.6
Xcode 3.2
Have you
=> librdkafka: fix the build

x11/homebank/Portfile, x11/homebank/files/patch-fix-clang-build.diff
=> homebank: update to 5.8.1

_resources/port1.0/group/haskell_cabal-1.0.tcl, _resources/port1.0/group/haskell_stack-1.0.tcl
Fixes: https://trac.macports.org/ticket/69915
macOS x.y
Have you
=> PG haskell_cabal: Fix configure.universal_args

ruby/rb-ffi/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rb-ffi: update to 1.17.0

ruby/rb-i18n/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rb-i18n: update to 1.14.5

R/R-BFpack/Portfile, R/R-bsvars/Portfile, R/R-formatters/Portfile, R/R-glmmrBase/Portfile, R/R-multiplex/Portfile, R/R-nanotime/Portfile, R/R-netmediate/Portfile, R/R-nloptr/Portfile, R/R-nloptr/files/patch-legacy.diff, R/R-quanteda/Portfile, R/R-reticulate/Portfile, R/R-scam/Portfile, R/R-seededlda/Portfile
Remaining updates for today.
macOS 10.6
Xcode 3.2
Have you
=> R: remaining updates (2)

graphics/tinygltf/Portfile
Update `tinygltf`  to version 2.8.23.
macOS x.y
Have you
=> tinygltf: update to 2.8.23

python/py-libpysal/Portfile
Update `py-libpysal` to version 4.11.0.
macOS x.y
Have you
=> py-libpysal: update to 4.11.0

multimedia/AtomicParsley/Portfile
=> AtomicParsley: update to 20240608.083822.1ed9031

lang/fortran-stdlib/Portfile
Self-explanatory
macOS 10.6
Xcode 3.2
Have you
=> fortran-stdlib: switch to released version; fortran-stdlib-devel: new port to track upstream

gis/saga/Portfile
Update `saga`, `py-pysaga`: update to 9.4.1
macOS x.y
Have you
=> saga, py-saga: update to 9.4.1

python/py-pdal-plugins/Portfile, python/py-pdal/Portfile
Update:
- `py-pdal` to version 3.4.5.
- `py-pdal-plugins` to version 1.5.2.
macOS x.y
Have you
=> py-pdal, py-pdal-plugins: updates

devel/ayatana-ido/Portfile, devel/libayatana-appindicator/Portfile, devel/libayatana-appindicator/files/0001-Fix-build-on-macOS.patch, devel/libayatana-indicator/Portfile, devel/libayatana-indicator/files/0001-Fix-build-on-macOS.patch, devel/libdbusmenu/Portfile, devel/libdbusmenu/files/patch-configure.diff, x11/xpad/Portfile
Some new ports
macOS 10.6
Xcode 3.2
Have you
=> xpad: new port, and its dependencies

kde/kdepimlibs4/Portfile
Also improve text layout in portfile.
macOS 10.6
Xcode 3.2
Have you
=> kdepimlibs4: fix compiler choice

mail/rspamd/Portfile, mail/rspamd/files/patch-OSDep_cmake.diff, textproc/hyperscan/Portfile, textproc/vectorscan/Portfile
=> vectorscan: Submission; rspamd: Use vectorscan, add hyperscan variant

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.15.1

net/oci-cli/Portfile, python/py-oci/Portfile
Updates Oracle Cloud Infrastructure SDK and CLI to current latest (2.128.2 for SDK, 3.43.2 for CLI). This PR also updates the library and CLI to use Python 3.11 as its listed to be supported in various other OSes: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/pythonsdk.htm#pythonsdk_topic-supported_python_versions
Have you
=> py-oci,oci-cli: update to 2.128.2,3.43.2

multimedia/shairport-sync/Portfile, multimedia/shairport-sync/files/0412a84006773098c558ed3f8d4b57b8540244ce.patch, multimedia/shairport-sync/files/c064b8bae5f1d2816857646382de5ca3a1ab5e15.patch
Closes: https://trac.macports.org/ticket/70148
Fix from upstream
macOS 10.6
Xcode 3.2
Have you
=> shairport-sync: fix for older systems (patch from upstream)

multimedia/AtomicParsley-devel/Portfile
=> AtomicParsley-devel: update to 20240608

science/dspl/Portfile, science/dspl/files/0001-Fixes-for-Macports.patch
Update
macOS 10.6
Xcode 3.2
Have you
=> dspl: update to 2024.06.05

finance/bitcoin/Portfile
=> bitcoin: update to 27.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.16.0

devel/mk-configure/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> mk-configure: update to 0.39.4

lang/lfortran/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> lfortran: update to 0.36.1

gnome/gnome-desktop/Portfile, gnome/gnome-settings-daemon/Portfile, gnome/gnome-settings-daemon/files/patch-legacy-cups.diff
Fixes: https://trac.macports.org/ticket/69962
Fix build with old `cups`
macOS 10.6
Xcode 3.2
Have you
=> gnome-settings-daemon: fix for old systems

devel/libsdl2-powerpc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: update to 2.30.4

gis/laszip/Portfile
Update `laszip` to version 3.4.4.
Have you
=> laszip: update to 3.4.4

python/py-asn1/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-asn1: update to 0.6.0

python/py-asgiref/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-asgiref: update to 3.8.1, add py312 subport

python/py-kaitaistruct/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-kaitaistruct: update to 0.10

aqua/qt6/Portfile, gis/gdal/Portfile
Roll back change to mysql8 library path updates now that mysql8 is
updated to use the derfault macports paths.
Have you
=> qt6, GDAL: roll back mysql8 library path update

gis/qgis3/Portfile
Update `qgis3` to version 3.38.0 and `qgis3-ltr` to 3.34.8.
Have you
=> qgis3, qgis3-ltr: update to 3.38.0 and 3.34.8 (LTR)

net/offpunk/Portfile
Fix deps, revbump.
macOS 10.6
Xcode 3.2
Have you
=> offpunk: now requires py-lxml_html_clean

python/py-setproctitle/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-setproctitle: update to 1.3.3

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.16.1

devel/bun/Portfile
=> Bun: Update to 1.1.16

mail/nmail/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> nmail: update to 4.67

net/rpki-client/Portfile
=> rpki-client: update to 9.1

net/dino/Portfile, net/dino/files/patch-disable-openpgp.diff, net/dino/files/patch-gcc-flags.diff
New port: https://dino.im
macOS 14.5
Xcode 15.4
Have you
=> dino: new port in net

LICENSE
=> LICENSE: update Copyright year

editors/texstudio/Portfile, editors/texstudio/files/patch-pdfviewer.pri-qt4.diff, editors/texstudio/files/patch-texstudio.pro-qt4.diff, editors/texstudio/files/patch-texstudio.pro.diff
Fix the broken port
macOS 14.5
Xcode 15.4
macOS 10.6
Xcode 3.2
Have you
=> texstudio: update to 4.8.1 for new systems, 2.12.22 with Qt4 for older ones

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.16.2

gnome/gnome-vfsmm/Portfile, gnome/libgnomecanvasmm/Portfile, gnome/libgnomeuimm/Portfile
Fix build, fix alignments.
macOS 10.6
Xcode 3.2
Have you
=> gnome-vfsmm, libgnomecanvasmm, libgnomeuimm: need C++11

python/py-awscli2/Portfile, python/py-awscrt/Portfile
=> Py awscli2

devel/bun/Portfile
=> Bun: Update to 1.1.17

python/py-hypothesis/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-hypothesis: update to 6.103.2

tex/luametatex/Portfile, tex/luametatex/files/patch-fix-gcc-build.diff
Fix
macOS 10.6
Xcode 3.2
Have you
=> luametatex: fix build on older systems with gcc

devel/haskell-language-server/Portfile
=> haskell-language-server: Update to version 2.9.0.0

devel/dialog/Portfile
=> dialog: update to 1.3-20240619

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.17.0

math/igraph/Portfile
=> igraph: update to 0.10.13

java/detekt-cli/Portfile
=> detekt-cli: Update to version 1.23.6

math/mlpack/Portfile
Update this finally. Hopefully gonna fix the build also (the port is semi-broken, judging from buildbots and a local attempt to install the old version).
macOS 10.6
Xcode 3.2
Have you
=> mlpack: update to 4.4.0

graphics/sxiv/Portfile, graphics/sxiv/files/patch-Makefile.diff
Currently checksums are broken. However, rather update it.
macOS 10.6
Xcode 3.2
Have you
=> sxiv: update to v. 26

net/mscp/Portfile
=> mscp: submission new Portfile

gnome/libadwaita/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libadwaita: update to 1.5.2

net/offpunk/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> offpunk: update to 2.3

devel/sccache/Portfile
=> sccche: update to 0.8.1

sysutils/mise/Portfile
=> mise: update to 2024.6.6

devel/jreleaser/Portfile
=> jreleaser: update to version v1.13.0

python/py-fipy/Portfile
* update to version 3.4.5
* remove post-destroot step (pending approval and cleanup)
closes https://trac.macports.org/ticket/70303
Have you
=> py-fipy:  update to version 3.4.5

devel/jreleaser/Portfile
=> jreleaser: update to version v1.13.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.17.2

science/elmerfem/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> elmerfem: update to 2024.07.01

ruby/rb-concurrent-ruby-ext/Portfile, ruby/rb-concurrent-ruby/Portfile, ruby/rb-net-ftp/Portfile, ruby/rb-parallel/Portfile, ruby/rb-rdoc/Portfile, ruby/rb-stringio/Portfile
Some updates
macOS 10.6
Xcode 3.2
Have you
=> ruby: update a few packages

devel/gk/Portfile
=> gk update to v2.1.0

lang/MoarVM/Portfile, lang/nqp/Portfile, lang/rakudo/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> Rakudo and friends: update to 2024.06

math/ginkgo/Portfile
Update.
This port uses MPICH, so at least macOS 13 CI will fail, heh.
macOS 10.6
Xcode 3.2
Have you
=> ginkgo: update to 1.8.0

lang/typescript/Portfile
Update TypeScript to 5.5.2
Have you
=> TypeScript: Update to 5.5.2

sysutils/coreutils-uutils/Portfile
=> coreutils-uutils: update to 0.0.27

comms/tio/Portfile
=> tio: fix build on macOS <11

math/HiGHS/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> HiGHS: update to 1.7.2

python/py-momepy/Portfile, python/py-spaghetti/Portfile, python/py-spopt/Portfile
Updates:
- `py-momepy` to version 0.7.2
- `py-spaghetti` to version 0.7.6
- `py-spopt` to version 0.6.1
macOS x.y
Have you
=> py-momepy, py-spaghetti, py-spopt: updates

archivers/draco/Portfile, graphics/tinygltf/Portfile
Update `tinygltf` to version 2.9.0.
Have you
=> tinygltf: update to 2.9.0

sysutils/font-manager/Portfile, sysutils/font-manager/files/patch-use-right-python.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> font-manager: update to 0.9.0

devel/global/Portfile
=> global: update to 6.6.13

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.18.2

python/py-pytorch/Portfile, python/py-pytorch/files/Werror.patch, python/py-pytorch/files/patch-macOS12-xcode14.diff, python/py-pytorch/files/patch-macOS13-xcode14.diff, python/py-pytorch/files/patch-pyproject_toml.diff
Depends upon #24097
macOS x.y
Have you
=> py-pytorch: Update to version 2.3.0; Add Python 311 312

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.20.2

python/py-asn1-modules/Portfile, python/py-asn1/Portfile
Should have been updated together, sorry -_-
Support for old pythons were dropped in new versions, so add fallbacks.
macOS 10.6
Xcode 3.2
Have you
=> py-asn1-modules: update to 0.4.0

devel/libsdl2-powerpc/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: update to 2.30.5

lang/lfortran/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> lfortran: update to 0.37.0

devel/thrust/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> thrust: update to 2.4.0

math/fricas/Portfile
macOS 13.6.7 22G720 x86_64
Have you
=> fricas: update to 1.3.11

python/py-gdal/Portfile
Update `py-gdal` to version 3.9.1.
macOS x.y
Have you
=> py-gdal: update to 3.9.1

science/geos/Portfile
Update `geos` to version 3.12.2.
Have you
=> geos: update to 3.12.2

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.21.1

sysutils/fq/Portfile, sysutils/nq/Portfile, sysutils/nq/files/patch-fq-note-funlock.diff
=> nq: update to 1.0

ruby/rb-nokogiri/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> rb-nokogiri: update to 1.16.6

_resources/port1.0/group/fortran-1.0.tcl, devel/fpm/Portfile, fortran/fortran-csv-module/Portfile
No revbump needed for any fortran packages, nothing changed for them.
macOS 10.6
Xcode 3.2
Have you
=> fortran-csv-module: update to 2.1.0; fpm/fortran PG: use gcc13 until next release

lang/fortran-stdlib/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> fortran-stdlib: update to 0.7.0; -devel: update to 2024.07.01

mail/fetchmail/Portfile
Update 
macOS 10.6
Xcode 3.2
Have you
=> fetchmail: update to 6.4.38

databases/pazpar2/Portfile, databases/pazpar2/files/patch-includes.diff, databases/zebra/Portfile, databases/zebra/files/patch-includes.diff, net/metaproxy/Portfile, net/yaz/Portfile, net/yazpp/Portfile, net/yazproxy/Portfile, net/yazproxy/files/dynamic_lookup-11.patch
@ryandesign Looks like I cannot re-open the old PR, so I just make a new one.
macOS 10.6
Xcode 3.2
Have you
=> yaz and friends: update

math/stanc3/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> stanc3: update to 2.35.0

science/elmerfem/Portfile, science/elmerfem/files/patch-umf4_f77wrapper.c.diff
Fix build with gcc14, update in one go.
macOS 10.6
Xcode 3.2
Have you
=> elmerfem: update to 2024.07.04, fix build with gcc14

multimedia/ffmpeg-devel/Portfile, multimedia/ffmpeg/Portfile, multimedia/ffmpeg6/Portfile
=> ffmpeg, -devel, ffmpeg6: fix build with gcc14

ocaml/ocaml-yojson/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ocaml-yojson: update to 2.2.2

xfce/orage/Portfile
=> orage: Update to 4.18.0

databases/sqlean/Portfile, databases/sqlean/files/patch-Makefile.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> sqlean: update to 0.24.1

net/snac/Portfile
=> snac: update to 2.56

xfce/xfce4-terminal/Portfile, xfce/xfce4-terminal/files/remove-intltool-perl-hack.diff
=> xfce4-terminal: Update to 1.1.3

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.23.0

gis/pdal/Portfile
Update `pdal` to version 2.7.2.
Have you
=> pdal: update to 2.7.2

science/shtools/Portfile
shtools: update to 4.13.1
macOS x.y
Have you
=> shtools: update to 4.13.1

net/zmap/Portfile
=> zmap: update to 4.2.0

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.8

devel/astyle/Portfile
=> astyle: update to 3.5.2

python/py-igraph/Portfile
=> py-igraph: update to 0.11.6

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.23.4

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.24.0

sysutils/maestral/Portfile
Simple update
macOS x.y
Have you
=> maestral: update to 1.9.4 for new systems

lang/ghc/Portfile
=> ghc: update to 9.6.6

devel/vttest/Portfile
=> vttest: update to 20240708

python/py-awscli2/Portfile
=> py-awscli2: update to 2.17.13

textproc/enchant2/Portfile
=> enchant2: update to 2.8.1

tex/texmaker/Portfile
=> texmaker: Update to 5.1.4

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.25.0

mail/mlmmj/Portfile
Introduces a new port 'mlmmj' to the tree.
Mlmmj is a simple and slim mailing list manager.
This software is licensed under MIT license.
Homepage: https://mlmmj.org/
Upstream: https://codeberg.org/mlmmj/mlmmj
Have you
=> mail/mlmmj: Added a new port

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.26.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.26.2

security/blake3/Portfile
Update BLAKE3 to version 1.5.2
macOS 13.6.7 22G720 arm64
Have you
=> blake3: update to 1.5.2

devel/libmcfp/Portfile, science/dssp/Portfile
See commits
macOS 10.6
Xcode 3.2
Have you
=> libmcfp, dssp: fix for older systems

lang/logtalk/Portfile
=> logtalk: update to 3.81.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.26.3

devel/wolfssl/Portfile
=> wolfssl: update to version 5.7.2

games/fheroes2/Portfile
=> fheroes2: update to 1.1.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.27.0

archivers/7zip/Portfile
* simplify compiler blacklist
Have you
=> 7zip: update to 24.07

security/nsrllookup/Portfile
Update. Also fixes the build with gcc.
macOS 10.6
Xcode 3.2
Have you
=> nsrllookup: update to 1.4.2

security/KeePassKit/Portfile
=> KeePassKit: update to 3.3.2

R/R-Rcpp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> R-Rcpp: update to 1.0.13

emulators/wine-devel/Portfile, emulators/wine-devel/files/1001-msync.diff, emulators/wine-devel/files/macos_hacks.diff
=> wine-devel,wine-staging: Update to 9.13

devel/git/Portfile, devel/git/files/patch-Revert-breaking-osxkeychain-devel.diff
@herbygillot Updated the patch for 2.46.0.
macOS x.y
Have you
=> git-devel: fix the patch for 2.46 so that it applies

graphics/MoltenVK/Portfile
=> MoltenVK: update to 1.2.10

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 21.28.0

erlang/atomvm/Portfile
=> atomvm: update to 0.6.3

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 22.0.1

databases/csvdb/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
=> csvdb: use legacysupport for clock_gettime

multimedia/musikcube/Portfile, multimedia/musikcube/files/patch-CMakeLists.diff, multimedia/musikcube/files/patch-fix-curses.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> musikcube: update to 3.0.4

devel/gFTL/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> gFTL: update to 1.14.0

gis/sfcgal/Portfile, gis/sfcgal/files/patch-atomic.diff
Also link to libatomic with gcc for 8-byte atomics support.
macOS 10.6
Xcode 3.2
Have you
=> sfcgal: set required C++ 17 standard

devel/gcli/Portfile
=> gcli: update to 2.4.0

devel/kchmviewer/Portfile
Fix port where it fails to build.
macOS 10.6
Xcode 3.2
Have you
=> kchmviewer: fix port for legacy systems

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 22.0.3

lang/swi-prolog/Portfile
=> swi-prolog: Updated to version 9.2.6

science/mpich/Portfile, science/mpich/files/patch-scandir-lion.diff
=> mpich: Fix https://trac.macports.org/ticket/70418 (pre 10.8 scandir)

textproc/lilypond/Portfile
=> lilypond: update to 2.24.4

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.0.2

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.2.0

lang/lfortran/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> lfortran: update to 0.38.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.3.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.3.1

devel/bun/Portfile
=> Bun: Update to 1.1.21

devel/ayatana-ido/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> ayatana-ido: update to 0.10.3

emulators/wine-stable/Portfile, emulators/wine-stable/files/macos_hacks.diff
=> wine-stable: Force older deployment target & rev-bump

math/LightGBM/Portfile, math/LightGBM/files/0001-Fix-CMakeLists.txt.patch
Update
macOS 10.6
Xcode 3.2
Have you
=> LightGBM: update to 4.5.0

science/spglib/Portfile
=> spglib: update to version 2.5.0

science/scifor/Portfile
Update.
Also do not use Ninja for now, since the build may fail (see the issue referred).
macOS 10.6
Xcode 3.2
Have you
=> scifor: update to 4.10.12

www/links/Portfile, www/links/files/implicit.patch
=> links: update to 2.30

gis/saga/Portfile
Update `saga`, `py-pysaga` to version 9.5.1.
Have you
=> saga, py-pysaga: update to 9.5.1

math/asl/Portfile
Update and fix
macOS 10.6
Xcode 3.2
Have you
=> asl: update to 20240106, fix threads variant for gcc

security/botan/Portfile, security/botan/files/patch-compiler_flags.diff
=> botan: update to 2.19.5

python/py-spglib/Portfile
=> py-spglib: version 2.4.0, variants for 3.11+3.12

python/py-palettable/Portfile
=> py-palettable: add py312 variant

python/py-monty/Portfile
=> py-monty: version 2024.7.30

python/py-plotly/Portfile
=> py-plotly: version 5.23.0

python/py-hdf5plugin/Portfile
Also add python 3.12 variant.
Have you
=> py-hdf5plugin: version 4.4.0

python/py-wxmplot/Portfile, python/py-wxpython-4.0/Portfile, python/py-wxutils/Portfile
=> py-wxpython-4.0, py-wxutils, py-wxmplot for Py 3.11 and 3.12

fortran/h5fortran/Portfile, fortran/h5fortran/files/patch-fix-install-dirs.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> h5fortran: update to 4.10.6

science/viking/Portfile, science/viking/files/autogen.sh
This solves https://trac.macports.org/ticket/60085
macOS 13.6.8 22G820 x86_64
Have you
=> viking: update to 1.10

python/py-pymatgen/Portfile
Also add subports for Python 3.11 and 3.12.
Have you
=> py-pymatgen: update to v2024.7.18

python/py-fabio/Portfile, python/py-fabio/files/pyproject.toml.patch, python/py-fabio/files/requirements.txt.patch
Also add py311 and py312
Depend on py-meson. Requires patching the package to remove the extraneous pip requirement for python `ninja`
Have you
=> py-fabio: update to version 2024.4.0

python/py-silx/Portfile
=> py-silx: update to 2.1.0

archivers/draco/Portfile, graphics/tinygltf/Portfile
Update `tinygltf` to version 2.9.2.
Have you
=> tinygltf: update to 2.9.2

lang/MoarVM/Portfile, lang/nqp/Portfile, lang/rakudo/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rakudo & friends: update to 2024.07

R/R-arrow/Portfile, devel/apache-arrow/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> apache-arrow: update to 17.0.0

science/libsc/Portfile, science/p4est/Portfile, science/p4est/files/patch-libsc-lib.diff
Update both port, put versions in sync.
macOS 10.6
Xcode 3.2
Have you
=> libsc, p4est: update to 2.8.6

devel/qbs/Portfile
=> qbs: Update to 2.4.0

gnome/gnome-calculator/Portfile
=> gnome-calculator: Update to 46.1

gis/grass/Portfile, gis/orfeotoolbox/Portfile, math/libsvm/Portfile
Update `libsvm` to version 3.33.
macOS x.y
Have you
=> libsvm: update to 3.33

lang/castxml/Portfile
Update `castxml` to version 0.6.8.
macOS x.y
Have you
=> castxml: update to 0.6.8

multimedia/scrcpy/Portfile
=> scrcpy: Update to version 2.6

devel/difftastic/Portfile
=> difftastic: Update to version 0.60.0

gnome/libadwaita/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> libadwaita: update to 1.5.3

security/bitwarden-cli/Portfile
=> bitwarden-cli: Update to version 2024.7.2

devel/libsdl2-powerpc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: update to 2.30.6

science/libdap/Portfile, science/libdap/files/patch-fix-32-bit.diff
See commits.
Fixes: https://trac.macports.org/ticket/70469
macOS 10.6
Xcode 3.2
Have you
=> libdap: fix 32-bit build, add license

multimedia/scrcpy/Portfile
=> scrcpy: Update to version 2.6.1

gis/sfcgal/Portfile
Update `sfcgal` to version 1.5.2.
macOS x.y
Have you
=> sfcgal: update to 1.5.2

sysutils/fastfetch/Portfile, sysutils/fastfetch/files/0001-gpu_apple.m-unbreak-for-10.11.patch, sysutils/fastfetch/files/0002-memory_apple-fix-for-32-bit.patch, sysutils/fastfetch/files/0003-opengl_apple.c-fix-for-10.7.patch, sysutils/fastfetch/files/0004-sound_apple.c-fix-for-10.8.patch, sysutils/fastfetch/files/0005-monitor_apple.m-no-HDR-before-10.11.patch, sysutils/fastfetch/files/0006-gpu_apple.c-fix-for-old-systems.patch, sysutils/fastfetch/files/0007-camera_apple.m-unbreak-for-10.7.patch, sysutils/fastfetch/files/0008-brightness_apple.c-add-a-missing-include.patch, sysutils/fastfetch/files/0009-Revert-refresh-rate-detection-commit-for-macOS.patch, sysutils/fastfetch/files/0010-disk_bsd-minor-fix-for-a-type-fixes-calculation-of-d.patch, sysutils/fastfetch/files/0011-CMakeLists-adjust-for-legacy-macOS.patch, sysutils/fastfetch/files/0012-os_apple.m-etc.-fix-syntax-for-plists.patch, sysutils/fastfetch/files/0013-osascript.m-fix-syntax.patch, sysutils/fastfetch/files/0014-Revert-some-display-related-breakages.patch, sysutils/fastfetch/files/0015-Fix-PowerPC-macros.patch, sysutils/fastfetch/files/0016-Fix-autorelease-pools.patch, sysutils/fastfetch/files/0017-disk_bsd-no-support-for-creation-time.patch, sysutils/fastfetch/files/0018-Support-PowerPC-CPU-detection.patch
@herbygillot Last time I gave up on this, but now it worked through.
Some modules are disabled; maybe I fix something extra, but for now this. AFAICT, the app is functional now.
macOS 10.6
Xcode 3.2
Have you
=> fastfetch: fix the port for old systems and powerpc

lang/ruby-devel/Portfile
Update, minor improvements, drop a breaking and unneeded C99.
macOS 10.6
Xcode 3.2
Have you
=> ruby-devel: update to 2024.08.03

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.4.1

devel/serpl/Portfile
macOS 14.6
Xcode 15.3.0
Have you
=> serpl: new port

science/exodriver/Portfile, science/exodriver/files/patch-Makefile.diff
Broken across the board, fix it.
macOS 10.6
Xcode 3.2
Have you
=> exodriver: fix broken build

devel/git-interactive-rebase-tool/Portfile
=> git-interactive-rebase-tool: Update to version 2.4.1

net/yggdrasil-go/Portfile
=> yggdrasil-go: update to 0.5.7

editors/bluefish/Portfile
This is needed now
macOS 10.6
Xcode 3.2
Have you
=> bluefish: use legacysupport to fix < 10.7

science/openEMS/Portfile, science/openEMS/files/0001-operator_ext_lumpedRLC.h-fix-includes.patch, science/openEMS/files/0002-CMakeLists-define-version-once.patch, science/openEMS/files/0003-CMakeLists-fix-powerpc.patch
Update, fix
macOS 10.6
Xcode 3.2
Have you
=> openEMS: update to 20240312, fix powerpc build

net/catgirl/Portfile
Totally forgot to add it in #25181.
Have you
=> catgirl: bump legacysupport to 13 for mkdirat and openat

ruby/rb-unicode/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rb-unicode: update to 0.4.4.5

gnome/hicolor-icon-theme/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> hicolor-icon-theme: update to 0.18

ocaml/ocaml-zarith/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ocaml-zarith: update to 1.14

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.6.1

devel/jujutsu/Portfile
Update jujutsu to 0.20.0
Have you
=> jujutsu: update to 0.20.0

math/gretl/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> gretl: update to 2024b

devel/CImg/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> CImg: update to 3.4.0

net/shadowsocks-rust/Portfile
Added `shadowsocks-rust` to Macports
Have you
=> shadowsocks-rust: new port starting from v1.20.3

net/snac/Portfile
=> snac: update to 2.57

ruby/rb-highline/Portfile, ruby/rb-http-cookie/Portfile, ruby/rb-http-cookie/files/patch-gemspec-3.1.diff, ruby/rb-http-cookie/files/patch-gemspec-3.2.diff, ruby/rb-http-cookie/files/patch-gemspec-3.3.diff, ruby/rb-method_source/Portfile, ruby/rb-minitar-cli/Portfile, ruby/rb-minitar-cli/files/patch-gemspec-3.1.diff, ruby/rb-minitar-cli/files/patch-gemspec-3.2.diff, ruby/rb-minitar-cli/files/patch-gemspec-3.3.diff, ruby/rb-minitar/Portfile, ruby/rb-path_expander/Portfile, ruby/rb-public_suffix/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> ruby: update some packages

python/py-gmpy2/Portfile
py-gmpy2: update to 2.2.1
Have you
=> py-gmpy2: update to 2.2.1

python/py-pyFAI/Portfile, python/py-pyFAI/files/pyproject.toml.patch, python/py-pyFAI/files/requirements.txt.patch
Have to patch the pyproject and requirements.txt files to remove `ninja` as a requirement.
Have you
=> py-pyFAI: update to 2024.5.0

graphics/asymptote/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> asymptote: update to 2.90

devel/libnumbertext/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libnumbertext: update to 1.0.11

math/nanoflann/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> nanoflann: update to 1.6.0

x11/xorg-libX11/Portfile, x11/xorg-libXfont2/Portfile, x11/xorg-libXtst/Portfile
Update a few xorg ports
macOS 10.6
Xcode 3.2
Have you
=> xorg-libX11: update to 1.8.10; xorg-libXfont2, xorg-libXtst: update

textproc/itstool/Portfile, textproc/itstool/files/invalid-sequence-pygte-312.patch
closes ticket : 
https://trac.macports.org/ticket/70527#ticket
macOS 10.15.7 x86_64
Xcode 12.4 / Command Line Tools 12.4.0.0.1.1610135815
Have you
=> Itstool invalid sequence patch py312

math/pari/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> pari: update to 2.15.5

net/torsocks/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
=> torsocks: fix build on < 10.7

math/normaliz/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> normaliz: update to 3.10.3

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.17.27

databases/pgpool-II/Portfile
=> pgpool-II: update to 4.5.2

archivers/xdelta/Portfile
Removed website, since it redirects to something completely unrelated. (GitHub repo is alive.)
macOS 10.6
Xcode 3.2
Have you
=> xdelta: fix the build

x11/sakura/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> sakura: update to 3.8.8

ocaml/ocaml-parmap/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ocaml-parmap: update to 1.2.5

www/catgirl-downloader/Portfile, www/catgirl-downloader/files/patch-use-right-python.diff
New port
macOS 10.6
Xcode 3.2
Have you
=> catgirl-downloader: new port

net/yggdrasil-go/Portfile
=> yggdrasil-go: update to 0.5.8

lang/py-htmldocs/Portfile
=> py-htmldocs: 3.12.5

devel/bun/Portfile
=> Bun: Update to 1.1.22

www/catgirl-downloader/Portfile
Closes: https://trac.macports.org/ticket/70538
Add run deps
CC @ryandesign 
macOS 10.6
Xcode 3.2
Have you
=> catgirl-downloader: add missing deps

devel/xmlwrapp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> xmlwrapp: update to 0.9.1

databases/postgresql12-doc/Portfile, databases/postgresql12-server/Portfile, databases/postgresql12/Portfile
=> postgresql12: update to 12.20

devel/readline/Portfile
=> readline: update to 8.2.13

math/eigenmath/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> eigenmath: update to 2024.06.20

science/basix/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> basix: update to 0.8.0

databases/postgresql15-doc/Portfile, databases/postgresql15-server/Portfile, databases/postgresql15/Portfile
=> postgresql15: update to 15.8

databases/postgresql13-doc/Portfile, databases/postgresql13-server/Portfile, databases/postgresql13/Portfile
=> postgresql13: update to 13.16

aqua/pgAdmin3/Portfile
See commits.
macOS 10.6
Xcode 3.2
Have you
=> pgAdmin3: fix the port

devel/any/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> any: update to 2024.05.01

security/xmltooling/Portfile
Plus minor improvement to portfile
macOS 10.6
Xcode 3.2
Have you
=> xmltooling: needs C++11

sysutils/fluent-bit/Portfile, sysutils/fluent-bit/files/0001-macos-setup-do-not-use-clang-flag-with-gcc.patch, sysutils/fluent-bit/files/0002-posix_file.c-add-a-missing-header.patch, sysutils/fluent-bit/files/0003-libatomic-gcc.patch, sysutils/fluent-bit/files/0004-snappy-compat.h-fix-Big-endian-on-Apple.patch, sysutils/fluent-bit/files/0005-mk_scheduler-fix-for-missing-pthread_threadid_np.patch, sysutils/fluent-bit/files/0006-flb_utils.c-fix-for-macOS-12.patch, sysutils/fluent-bit/files/0007-Fix-for-meminfo-on-32-bit-darwin.patch
@herbygillot I will submit most of the patches to upstream, so hopefully we do not need to rebase much.
macOS 10.6
Xcode 3.2
Have you
=> fluent-bit: fix the port for earlier systems

emulators/wine-devel/Portfile, emulators/wine-devel/files/1001-devel-msync.diff, emulators/wine-devel/files/1001-staging-msync.diff
=> wine-devel,wine-staging: update to 9.15

databases/mysql8/Portfile
Update mysql 8 to 8.4.2
Have you
=> mysql8: rev bump to 8.4.2

archivers/ucl/Portfile, devel/libucl/Portfile
Needs a conflict with `ucl`, but also let’s update it in the same go.
macOS 10.6
Xcode 3.2
Have you
=> libucl: update to 0.9.2, add conflict with ucl

math/petsc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> petsc: update to 3.21.4

devel/bun/Portfile
=> Bun: Update to 1.1.24

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.9

python/py-rchitect/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> py-rchitect: update to 0.4.7

net/shadowsocks-rust/Portfile
Update shadowsocks-rust to v1.20.4. [Release](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.20.4)
Have you
=> shadowsocks-rust: update to v1.20.4

devel/got/Portfile
=> got: update to 0.102

mail/getmail/Portfile, mail/getmail6/Portfile, mail/getmail6/files/0001-pop3-Support-use_xoauth2.patch
Since getmail6 is a fork of getmail, not just a new version, introduce it as a new port.  It conflicts with getmail, there is little reason to have both installed at the same time and this way I do not have to deal with selections.
macOS 14.6
Have you
=> getmail6: New port.

devel/docker-compose-plugin/Portfile
* update to version 2.29.1
Xcode 15.4 Build version 15F31d / Command Line Tools 15.3.0.0.1.1708646388
Have you
=> docker-compose-plugin: update to version 2.29.1

emulators/uxn/Portfile
=> uxn: update to 20240812

science/shtools/Portfile
Fix dependency
macOS x.y
Have you
=> shtools: non-functional: path-style dep on OpenBLAS

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.6.3

devel/astyle/Portfile
=> astyle: update to 3.6

java/openjdk8-powerpc/Portfile, java/openjdk8-powerpc/files/0001-Fix-timebomb-bug-in-GenerateCurrencyData.patch, java/openjdk8-powerpc/files/0002-Ignore-__NSAutoreleaseNoPool-errors.patch, java/openjdk8-powerpc/files/0003-os_perf_bsd-allow-to-compile-with-ZERO-CPU.patch, java/openjdk8-powerpc/files/0004-Added-macosx-bin-zero-jvm.cfg.patch, java/openjdk8-powerpc/files/0005-ExtendedOptionsImpl.c-define-TCP_KEEPINTVL-and-TCP_K.patch, java/openjdk8-powerpc/files/0006-Revert-8211301-macos-support-full-window-content-opt.patch, java/openjdk8-powerpc/files/0007-Provide-definition-of-__private_extern__-where-undef.patch, java/openjdk8-powerpc/files/0008-8181503-Can-t-compile-hotspot-with-c-11.patch, java/openjdk8-powerpc/files/0009-Disable-C-11-warnings.patch, java/openjdk8-powerpc/files/1001-os_bsd_zero.cpp-implement-sync_val_compare_and_swap_.patch, java/openjdk8-powerpc/files/1002-CoreLibraries.gmk-do-not-hardcode-arch.patch, java/openjdk8-powerpc/files/1003-java_md_macosx-fix-broken-ObjC-code.patch, java/openjdk8-powerpc/files/1004-os_bsd-add-ppc64-case.patch, java/openjdk8-powerpc/files/1005-jniTypes_ppc-downgrade-error-to-warning.patch, java/openjdk8-powerpc/files/1006-os_bsd.cpp-fix-vm_statistics.patch, java/openjdk8-powerpc/files/1007-Awt2dLibraries-add-fnested-functions.patch, java/openjdk8-powerpc/files/1008-java_md_macosx.c-define-preferredJVM.patch, java/openjdk8-powerpc/files/1009-os_bsd.cpp-allow-headless-on-Apple.patch, java/openjdk8-powerpc/files/1010-Makefile-fix-LP64-define.patch, java/openjdk8-powerpc/files/1011-No-dtrace-for-now.patch, java/openjdk8-powerpc/files/1012-toolchain.m4-hack-around-a-broken-Xcode-version-dete.patch, java/openjdk8-powerpc/files/1013-os_bsd.cpp-fix-running-VM.patch, java/openjdk8-powerpc/files/1014-portconfig-try-fix-broken-pipe.patch, java/openjdk8-powerpc/files/1015-Some-hacks-to-fix-the-build-for-powerpc.patch
@breun @pmetzger Following the suggestion, a standalone powerpc port.
I have just built 8u422 now.
macOS 10.6
Xcode 3.2
Have you
=> openjdk8-powerpc: new port to support modern Java on PowerPC

erlang/atomvm/Portfile
=> atomvm: update to 0.6.4

editors/JuffEd/Portfile
New port
macOS 10.6
Xcode 3.2
macOS 14.6.1
Xcode 15.4
Have you
=> JuffEd: new port in editors

sysutils/pv/Portfile
=> pv: 1.8.13

sysutils/ud/Portfile
ud - new port 
macOS 13.6.9 22G830 arm64
Have you
=> ud: new port, version 1.1.0

math/radian/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> radian: update to 0.6.13

security/blake3/Portfile
Update blake3 to v. 1.5.4
macOS 13.6.9 22G830 arm64
Have you
=> blake3: update to 1.5.4

devel/eask-cli/Portfile
=> eask-cli: update to 0.10.0

devel/ayatana-ido/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ayatana-ido: update to 0.10.4

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.7.2

devel/wt/Portfile, devel/wt/files/0001-src-CMakeLists-fix-OpenGL-linking.patch, devel/wt/files/0002-WServerGLWidget.C-do-not-hardcode-OpenGL-implementat.patch
New port: https://github.com/emweb/wt
macOS 10.6
Xcode 3.2
Have you
=> wt: new port in devel

R/R-BDgraph/Portfile, R/R-Compositional/Portfile, R/R-KernelKnn/Portfile, R/R-NNS/Portfile, R/R-PAGFL/Portfile, R/R-ParallelLogger/Portfile, R/R-Rfast2/Portfile, R/R-Rnanoflann/Portfile, R/R-VLMC/Portfile, R/R-dockerfiler/Portfile, R/R-elmNNRcpp/Portfile, R/R-gmp/Portfile, R/R-intervals/Portfile, R/R-jfa/Portfile, R/R-logging/Portfile, R/R-mixture/Portfile, R/R-mvgam/Portfile, R/R-rkriging/Portfile, R/R-rstpm2/Portfile, R/R-shapviz/Portfile, R/R-spatstat.explore/Portfile, R/R-tspredit/Portfile, R/R-wrswoR/Portfile
Remaining stuff for this time.
macOS 10.6
Xcode 3.2
Have you
=> R: remaining updates (3)

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.10

net/rpki-client/Portfile
=> rpki-client: update to 9.2

lang/lfortran/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> lfortran: update to 0.39.0

x11/xorg-server-legacy/Portfile
Avoid a breakage due to undeclared dependency.
macOS 10.6
Xcode 3.2
Have you
=> xorg-server-legacy: declare dependency on xorg-libxshmfence

sysutils/glances/Portfile
glances:  Update to version 4.1.2.1
* Update to version 4.1.2.1
* Add myself as a maintainer
Have you
=> glances:  Update to version 4.1.2.1

sysutils/colima/Portfile
=> colima: Upgrade to 0.7.5

net/nghttp3/Portfile, net/ngtcp2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ngtcp2: update to 1.7.0; nghttp3: update to 1.5.0

lang/cppman/Portfile
=> cppman: 0.5.6

sysutils/glances/Portfile, sysutils/glances/files/0001-Unrustify-glances.patch
See: https://trac.macports.org/ticket/70625
Fix the port
macOS 10.6
Xcode 3.2
Have you
=> glances: fix for systems without rust

gnome/gstreamer1-gst-libav/Portfile, gnome/gstreamer1-gst-plugins-bad/Portfile, gnome/gstreamer1-gst-plugins-base/Portfile, gnome/gstreamer1-gst-plugins-good/Portfile, gnome/gstreamer1-gst-plugins-good/files/patch-gstosxaudiodeviceprovider.c.diff, gnome/gstreamer1-gst-plugins-ugly/Portfile, gnome/gstreamer1/Portfile, gnome/gstreamer1/files/0001-Revert-macos-Fix-gst_macos_main-terminating-whole-pr.patch
Update
macOS 10.6
Xcode 3.2
Have you
=> gstreamer1*: update to 1.24.7

math/nauty/Portfile
=> nauty: update to 2.8.9

lang/lfortran/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> lfortran: update to 0.40.0

python/py-pptx/Portfile
=> py-pptx: 1.0.2

python/hyfetch/Portfile, python/hyfetch/files/0001-neofetch-add-info-for-PowerMac-iMac-models.patch, python/hyfetch/files/0002-neofetch-add-info-for-PowerBook-iBook-models.patch, python/hyfetch/files/0003-neofetch-support-MacPorts-on-Linux-BSD.patch
See commits
macOS 10.6
Xcode 3.2
Have you
=> hyfetch: support host info for PowerPC Macs and MacPorts on Linux/BSD

python/py-awscli2/Portfile
=> py-awscli2: update to 2.17.42

devel/CLI11/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> CLI11: update to 2.4.2

lang/algol68g/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> algol68g: update to 3.5.5

devel/jreleaser/Portfile
=> jreleaser: update to version v1.14.0

devel/orc/Portfile
Closes: https://trac.macports.org/ticket/70664
Have you
=> orc: blacklist clang < 1100

textproc/tesseract/Portfile
macOS 15.0 24A5331b
Xcode 16.0 16A5230g
Have you
=> tesseract: update to 5.4.1

devel/edencommon/Portfile, devel/fatal/Portfile, devel/fb303/Portfile, devel/fbthrift/Portfile, devel/fizz/Portfile, devel/folly/Portfile, devel/mvfst/Portfile, devel/proxygen/Portfile, devel/wangle/Portfile, sysutils/watchman/Portfile, sysutils/watchman/files/0001-backport-58a8b4e39385d5e8ef8dfd12c1f5237177340e10.diff
Update folly & friends
macOS 10.6
Xcode 3.2
Have you
=> folly and friends: update to 2024.08.26.00

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.9.1

x11/TkPasMan/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> TkPasMan: update to 2.2b

devel/libsdl2-powerpc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: update to 2.30.7

aqua/LyX/Portfile, aqua/LyX/files/patch-GuiFontMetrics.cpp.diff
This is broken completely, as of now: configuring fails already due to a missing arg. Fix it.
macOS 10.6
Xcode 3.2
Have you
=> LyX: fix building Qt4 variant

devel/CImg/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> CImg: update to 3.4.1

lang/swi-prolog/Portfile
=> swi-prolog: Updated to version 9.2.7

cross/binwalk/Portfile
=> binwalk: switch fork, update to 2.4.1

math/boolector/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> boolector: update to 3.2.4

devel/tatami/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> tatami: update to 3.1.0; tatami-devel: update to 2024.09.02

graphics/exempi/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> exempi: update to 2.6.5

sysutils/glances/Portfile
glances: restore Lion compatibility
* bump revision number
* fix maintainer block
macOS 10.7.5 11G63 i386
Have you
=> glances: restore Lion compatibility

lang/ruby-devel/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ruby-devel: update to 2024.09.04

science/gildas/Portfile, science/gildas/files/patch-admin-Makefile.python.diff
=> Gildas: update to 202409a

net/snac/Portfile
=> snac: update to 2.58

devel/jujutsu/Portfile
Update jujutsu to 0.21.0
Have you
=> jujutsu: update to 0.21.0

devel/n/Portfile
=> n: update to 10.0.0

devel/libpipeline/Portfile
Update `libpipeline` to 1.5.8.
Have you
=> libpipeline: update to 1.5.8

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.11

math/primesieve/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> primesieve: update to 12.4

math/spral/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> spral: update to 2024.05.08

devel/boehmgc/Portfile
macOS 10.13
Xcode 9.4
Have you
=> boehmgc: update to 8.2.8

python/py-pynetdicom/Portfile
=> py-pynetdicom: 2.1.1

sysutils/pv/Portfile
=> pv: 1.8.14

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.12.0

databases/redis/Portfile
=> redis: update to 7.4.0

devel/got/Portfile
=> got: update to 0.103

graphics/asymptote/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> asymptote: update to 2.91

databases/rocksdb/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rocksdb: update to 9.6.1

audio/rsgain/Portfile
=> rsgain: add port

sysutils/syslog-ng/Portfile, sysutils/syslog-ng/files/80e97634cb75878ee94b23ebf35cebc92481fbfc.patch, sysutils/syslog-ng/files/patch-sonoma.diff
Fix the build.
macOS 10.6
Xcode 3.2
Have you
=> syslog-ng: fix build on Sonoma and old macOS

devel/qtsingleapplication-qt4/Portfile, devel/qtsingleapplication-qt4/files/0001-qtsingleapplication-unbreak-build-with-Qt4.patch
New port, a dependency for some Qt software.
macOS 10.6
Xcode 3.2
Have you
=> qtsingleapplication-qt4: new port in devel

math/petsc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> petsc: update to 3.21.5

math/nanoflann/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> nanoflann: update to 1.6.1

math/TOPCOM/Portfile, math/ipopt/Portfile, math/papilo/Portfile, math/scip/Portfile, math/soplex/Portfile
Update some math ports
macOS 10.6
Xcode 3.2
Have you
=> papilo & friends: update to current versions

net/tcpkali/Portfile, net/tcpkali/files/0001-tcpkali_iface.c-define-AI_NUMERICSERV-when-undefined.patch
Update, fix
macOS 10.6
Xcode 3.2
Have you
=> tcpkali: update to 1.1.1, fix build on < 10.7

math/cminpack/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> cminpack: update to 1.3.10

math/cminpack/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> cminpack: update to 1.3.11

sysutils/fastfetch/Portfile, sysutils/fastfetch/files/0001-Support-hostinfo-for-PowerPC-Macs.patch, sysutils/fastfetch/files/0002-version.c-add-a-missing-macro-for-powerpc.patch, sysutils/fastfetch/files/0003-Support-PowerPC-CPU-detection.patch, sysutils/fastfetch/files/0004-gpu_apple.m-unbreak-for-10.11.patch, sysutils/fastfetch/files/0005-memory_apple-fix-for-32-bit.patch, sysutils/fastfetch/files/0006-opengl_apple.c-fix-for-10.7.patch, sysutils/fastfetch/files/0007-sound_apple.c-fix-for-10.8.patch, sysutils/fastfetch/files/0008-gpu_apple.c-fix-for-old-systems.patch, sysutils/fastfetch/files/0009-camera_apple.m-unbreak-for-10.7.patch, sysutils/fastfetch/files/0010-brightness_apple.c-add-a-missing-include.patch, sysutils/fastfetch/files/0011-os_apple.m-etc.-fix-syntax-for-plists.patch, sysutils/fastfetch/files/0012-osascript.m-fix-syntax.patch, sysutils/fastfetch/files/0013-disk_bsd-no-support-for-creation-time.patch, sysutils/fastfetch/files/0014-yyjson-PowerPC-macros.patch, sysutils/fastfetch/files/0015-monitor_apple.m-no-HDR-before-10.11.patch, sysutils/fastfetch/files/0016-Fix-autorelease-pools.patch, sysutils/fastfetch/files/0017-Fix-compatibility-with-10.4.patch, sysutils/fastfetch/files/0018-Revert-some-breakages.patch, sysutils/fastfetch/files/0019-CMakeLists-adjust-for-legacy-macOS.patch, sysutils/fastfetch/files/0020-swap_fat_arch_64-does-not-exist-in-10.6.patch, sysutils/fastfetch/files/0021-CMakeLists-do-not-use-Linux-ldflag-on-macOS.patch
Update
macOS 10.6
Xcode 3.2
Have you
=> fastfetch: update to 2.24.0 for old systems

emulators/tnylpo/Portfile
=> tnylpo: update to 1.1.6

devel/git/Portfile, devel/git/files/patch-git-devel-Revert-breaking-osxkeychain.diff
@herbygillot Confirmed to work.
macOS 10.6
Xcode 3.2
Have you
=> git-devel: update patch for < 10.7

net/snmptt/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> snmptt: update to 1.5

python/py-graphviz/Portfile, python/py-objgraph/Portfile
Need this for testing another port.
macOS 10.6
Xcode 3.2
Have you
=> py-graphviz: update to 0.20.3; py-objgraph: new port

net/zenmap/Portfile
=> zenmap: update to 7.95, use python 3.12

lang/racket/Portfile, lang/racket/files/patch-fix-Big-endian.diff, lang/racket/files/paths-to-openssl.diff
New port: https://racket-lang.org
macOS 10.6
Xcode 3.2
Have you
=> racket: new port in lang

devel/JSE/Portfile, devel/JSE/files/patch-find-json.diff
New port
macOS 10.6
Xcode 3.2
Have you
=> JSE: new port in devel

math/fricas/Portfile
macOS 13.6.9 22G830 x86_64
Have you
=> fricas: revbump because of sbcl upgrade

games/fheroes2/Portfile
=> fheroes2: update to 1.1.2

net/snac/Portfile
=> snac: update to 2.59

devel/reflex/Portfile
=> reflex: update to 2.5.4-20240906

games/ferium/Portfile
Update Ferium to 4.7.1
Have you
=> Ferium: Update to 4.7.1

devel/fnc/Portfile, devel/fnc/files/libf-Werror-include-ncursesw.diff
update fnc: 0.16 -> 0.18
macOS 13.6.9 22G830 x86_64
Have you
=> fnc: update to 0.18

x11/homebank/Portfile
=> homebank: update to 5.8.3

science/veryfasttree/Portfile
=> veryfasttree: Update to version 4.0.4

devel/bun/Portfile
=> Bun: Update to 1.1.27

multimedia/scrcpy/Portfile
=> scrcpy: Update to version 2.7

net/paho.mqtt.c/Portfile, net/paho.mqtt.c/files/0001-Thread-fix-dispatch-usage-on-macOS.patch, net/paho.mqtt.c/files/0002-Thread.c-fix-Availability-macros.patch
1. Fix build on old macOS
2. Enable tests
3. Install static libs as well (dynamic are installed)
macOS 10.6
Xcode 3.2
Have you
=> paho.mqtt.c: fix build on old macOS, enable tests

python/py-clang/Portfile
=> py-clang: add 3.12; clang18

python/py-ctypeslib2/Portfile
=> py-ctypeslib2: Add 3.12

gis/grass/Portfile, gis/grass7/Portfile, gis/pdal/Portfile, gis/qgis3/Portfile, gis/saga/Portfile, python/py-pdal-plugins/Portfile, python/py-pdal/Portfile
Updates 
- `qgis3` to 3.38.3
- `qgis3-ltr` to 3.34.11
- `pdal` to 2.8.0
- `py-pdal-plugins` to 1.6.0
New subports of `pdal`:
- `pdal-draco` replacing "draco" variant
- `pdal-pgpointcloud` replacing "postgresql[NN]" variants
- `pdal-tiledb` replacing "tiledb" variant
In addition the following changes are made:
- qgis3{-ltr}: remove variant `draco`, add port draco as dependant
Have you
=> qgis3, pdal, py-pdal-plugins: updates

devel/ivykis/Portfile, sysutils/syslog-ng-devel/Portfile, sysutils/syslog-ng-devel/files/0001-compat-add-inttypes.h-and-define-__STDC_FORMAT_MACRO.patch, sysutils/syslog-ng-devel/files/syslog-ng.conf-dist
@Schamschula Finally this builds with clangs. GCC on 10.6 does better :) 
Could you handle then non-devel port, whenever you feel like? I am done with this.
`ivykis` now can be used without relying on a bundled one.
macOS 10.6
Xcode 3.2
Have you
=> syslog-ng-devel: new port

textproc/meld/Portfile
* update to version 3.22.2
* use Python 3.12
Have you
=> meld: update to 3.22.2

devel/lazarus/Portfile, devel/lazarus/files/noGUI-Printer.patch
Closes: https://trac.macports.org/ticket/70740
macOS x.y
Have you
=> lazarus: update to 3.4

databases/postgis3/Portfile
Update `porstgis3` to version 3.4.3.
macOS x.y
Have you
=> postgis3: update to 3.4.3

net/bettercap/Portfile
=> bettercap: update to 2.40.0

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.17.54

ruby/rb-diakonos/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rb-diakonos: update to 0.9.12

lang/ruby-devel/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ruby-devel: update to 2024.09.19

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.13.4

ruby/rb-atk/Portfile, ruby/rb-cairo-gobject/Portfile, ruby/rb-clutter-gdk/Portfile, ruby/rb-clutter/Portfile, ruby/rb-gdk3/Portfile, ruby/rb-gdk4/Portfile, ruby/rb-gdk_pixbuf2/Portfile, ruby/rb-gio2/Portfile, ruby/rb-glib2/Portfile, ruby/rb-gnumeric/Portfile, ruby/rb-gobject-introspection/Portfile, ruby/rb-goffice/Portfile, ruby/rb-gsf/Portfile, ruby/rb-gtk3/Portfile, ruby/rb-gtk4/Portfile, ruby/rb-gtksourceview4/Portfile, ruby/rb-pango/Portfile, ruby/rb-vte3/Portfile
Update all gnome bindings from 4.2.2 to 4.2.3.
macOS 10.6
Xcode 3.2
Have you
=> rb-*: update gnome bindings to 4.2.3

net/openssh/Portfile
=> openssh: update to 9.9p1

devel/wolfssl/Portfile, devel/wolfssl/files/0001-types.h-add-powerpc-macros.patch, devel/wolfssl/files/0002-asm.c-fix-ppc-asm-for-macOS.patch, devel/wolfssl/files/0003-sp_int.c-fix-ppc-asm-for-macOS.patch, devel/wolfssl/files/0004-wc_port.h-fix-macros-for-powerpc.patch, devel/wolfssl/files/0005-Fix-libdispatch-usage-condition.patch, devel/wolfssl/files/0006-crl.c-use-EV_TRIGGER-when-NOTE_TRIGGER-unavailable.patch
Some fixups
macOS 10.6
Xcode 3.2
Have you
=> wolfssl: fix build on older systems and powerpc

net/librdkafka/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> librdkafka: update to 2.5.3

python/py-scikit-learn/Portfile
temporary workaround for numpy v2 requirement
macOS x.y
Have you
=> py-scikit-learn: update to 1.5.2

www/nicotine-plus/Portfile, www/nicotine-plus/files/patch-GTK3.diff, www/nicotine-plus/files/patch-GTK4.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> nicotine-plus: update to 3.3.5

net/shadowsocks-rust/Portfile
Update shadowsocks-rust to v1.21.0. [Release](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.21.0)
Have you
=> shadowsocks-rust: update to v1.21.0

science/elmerfem/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> elmerfem: update to 2024.09.21

python/py-pydicom/Portfile
=> py-pydicom: 3.0.1

www/varnish/Portfile, www/varnish/files/patch-no-werror.diff
Update, minor fix
macOS 10.6
Xcode 3.2
Have you
=> varnish: update to 7.6.0

net/rpki-client/Portfile
=> rpki-client: update to 9.3

lisp/cl-fset/Portfile, lisp/cl-misc-extensions/Portfile
Update these to working versions.
macOS 10.6
Xcode 3.2
Have you
=> cl-misc-extensions: update to 4.0.4, fixes port fetch; cl-fset: update to 1.4.1

lang/logtalk/Portfile
=> logtalk: update to 3.83.0

ruby/rb-atk/Portfile, ruby/rb-cairo-gobject/Portfile, ruby/rb-clutter-gdk/Portfile, ruby/rb-clutter/Portfile, ruby/rb-gdk3/Portfile, ruby/rb-gdk4/Portfile, ruby/rb-gio2/Portfile, ruby/rb-glib2/Portfile, ruby/rb-gnumeric/Portfile, ruby/rb-gobject-introspection/Portfile, ruby/rb-goffice/Portfile, ruby/rb-gsf/Portfile, ruby/rb-gtk3/Portfile, ruby/rb-gtk4/Portfile, ruby/rb-gtksourceview4/Portfile, ruby/rb-pango/Portfile, ruby/rb-vte3/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rb-*: update gnome bindings to 4.2.4

python/py-ruamel-yaml-clib/Portfile, python/py-ruamel-yaml-clib/files/clang16.patch
Fix py312-ruamel-yaml-clib @0.2.8: incompatible function pointer types errors during build on macOS Sequoia (with clang16).
The patch has been shamelessly [stolen from FreeBSD](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271531).
Trac ticket: https://trac.macports.org/ticket/70796
Have you
=> py312-ruamel-yaml-clib: fix incompatible function pointer types

sysutils/FatDriveSorter/Portfile, sysutils/FatDriveSorter/files/patch-use_MP_fatsort.diff
=> FatDriveSorter: submission

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.14.2

databases/postgis3/Portfile
Update `pg{N}-postgis3` to version 3.5.0.
macOS x.y
Have you
=> postgis3: update to 3.5.0

archivers/draco/Portfile, graphics/tinygltf/Portfile
Update `tinygltf` to version 2.9.3.
Have you
=> tinygltf: update to 2.9.3

gis/saga/Portfile
Update `saga` to version 9.6.0 and use latest version of PROJ (`proj`).
Have you
=> saga: update to version 9.6.0

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.12

devel/edencommon/Portfile, devel/fatal/Portfile, devel/fb303/Portfile, devel/fbthrift/Portfile, devel/fizz/Portfile, devel/folly/Portfile, devel/folly/files/patch-legacy-systems.diff, devel/mvfst/Portfile, devel/proxygen/Portfile, devel/wangle/Portfile, sysutils/watchman/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> folly & friends: update to 2024.09.23.00

sysutils/tmux/Portfile
=> tmux: update to 3.5_1

net/dnsviz/Portfile
=> dnsviz: update to 0.11.0

net/irrtoolset/Portfile
Closes: https://trac.macports.org/ticket/70638
Update and fix
macOS 10.6
Xcode 3.2
Have you
=> irrtoolset: update to 5.1.3, fixes build

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to v23.15.0

devel/fizz/Portfile, devel/liboqs/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> liboqs: update to 0.11.0

R/R-AER/Portfile, R/R-MRCE/Portfile, R/R-MTPS/Portfile, R/R-MultivariateRandomForest/Portfile, R/R-SiER/Portfile, R/R-hms/Portfile, R/R-joinet/Portfile, R/R-tarchetypes/Portfile, R/R-timeDate/Portfile, R/R-timeSeries/Portfile, R/R-transreg/Portfile, R/R-tseries/Portfile, R/R-tsmethods/Portfile, R/R-vistla/Portfile
Remaining updates
macOS 10.6
Xcode 3.2
Have you
=> R: updates to packages (final)

gnome/gstreamer1-gst-libav/Portfile, gnome/gstreamer1-gst-plugins-bad/Portfile, gnome/gstreamer1-gst-plugins-base/Portfile, gnome/gstreamer1-gst-plugins-good/Portfile, gnome/gstreamer1-gst-plugins-ugly/Portfile, gnome/gstreamer1/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> gstreamer1*: update to 1.24.8

gis/tilemaker/Portfile, graphics/shapelib/Portfile, science/grads/Portfile, science/plplot/Portfile, science/xastir/Portfile, textproc/gpsbabel/Portfile
Update `shapelib` to version 1.6.1.
Have you
=> shapelib: update to 1.6.1

math/dbcsr/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> dbcsr: update to 2.7.0

mail/nmail/Portfile, mail/nmail/files/patch-remove-brewisms.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> nmail: update to 5.1.16

gnome/libadwaita/Portfile
P. S. 1.6.0 requires a newer gtk4 than we have. For now, update to 1.5.4.
macOS 10.6
Xcode 3.2
Have you
=> libadwaita: update to 1.5.4

editors/turbo/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> turbo: update to 2024.09.03

audio/ncmpc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ncmpc: update to 0.51

devel/sccache/Portfile
macOS 15.0 24A335 x86_64
Have you
=> sccache: update to 0.8.2

textproc/remind/Portfile
=> remind: update to 05.00.06

textproc/vale/Portfile
macOS 15.0 24A335 x86_64
Have you
=> vale: update to 3.7.1

www/linkchecker/Portfile
=> linkchecker: update to 10.5.0

python/py-awscli2/Portfile
=> py-awscli2: update to 2.18.0

python/py-gpxpy/Portfile
=> py-gpxpy: new port, version 1.6.2

databases/postgis3/Portfile
`pg{NN}-postgis3-doc`: mark supported_archs noarch, platforms any
macOS x.y
Have you
=> pg-postgis3-doc: mark noarch, platforms any

lang/julia/Portfile
=> julia: update to 1.11.0

gnome/gpodder/Portfile, gnome/gpodder/files/510de4b3a0b0444231f87bc6cb60527817847865.patch, gnome/gpodder/files/dd9b594d24a541c0f1d3b096e47b6d7f1c11ca7e.patch
Fix the port
macOS 14.7
Xcode 15.4
Have you
=> gpodder: fix py312 variant, add missing dep

net/snac/Portfile, net/snac/files/Makefile.patch
=> snac: update to 2.60

graphics/MoltenVK/Portfile
=> MoltenVK: update to 1.2.11

sysutils/oh-my-posh/Portfile
update oh-my-posh to v23.17.0
Have you
=> oh-my-posh: update to v23.17.0

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.13

sysutils/oh-my-posh/Portfile
update oh-my-posh to v23.19.0
Have you
=> oh-my-posh: update to v23.19.0

devel/eask-cli/Portfile
=> eask-cli: update to 0.10.1

sysutils/oh-my-posh/Portfile
[
](oh-my-posh: update to v23.20.0)
Have you
=> oh-my-posh: update to v23.20.0

lang/py-htmldocs/Portfile
=> py-htmldocs: 3.12.7, 3.13.0

python/py-tz/Portfile
=> py-tz: update to 2024.2, add py313 subport

erlang/atomvm/Portfile
=> atomvm: update to 0.6.5

python/py-pefile/Portfile
=> py-pefile: update to 2024.8.26, add py313, remove py38

java/jdk17-graalvm/Portfile
=> jdk17-graalvm: update platform comment

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to v23.20.1

emulators/wine-devel/Portfile, emulators/wine-devel/files/1001-devel-msync.diff, emulators/wine-devel/files/1001-staging-msync.diff
=> wine-devel,wine-staging: Update to 9.19

python/py-itemloaders/Portfile
=> py-itemloaders: update to 1.3.2

graphics/glslang/Portfile, graphics/glslang/files/create-pkgconfig-file.diff, graphics/shaderc/Portfile, graphics/shaderc/files/use-installed-spirv-tools.patch, graphics/spirv-headers/Portfile, graphics/spirv-tools/Portfile, graphics/vulkan-headers/Portfile, graphics/vulkan-loader/Portfile, graphics/vulkan-loader/files/vulkan-headers-find.patch, graphics/vulkan-tools/Portfile, graphics/vulkan-utility-libraries/Portfile, graphics/vulkan-validationlayers/Portfile, graphics/vulkan-volk/Portfile
See: https://trac.macports.org/ticket/71081
shaderc: Added Newport
vulkan-\<all>: update to 1.3.296.0
glslang: update to 1.3.296.0
spirv-tools: update to 1.3.296.0
spirv-headers: update to 1.3.296.0
Set where it was not done yet the python used version to 3.12
Fixes: https://trac.macports.org/ticket/71081
macOS 10.15
Xcode 11.5 / Command Line Tools 11.5
Have you
=> Shaderc new port,update vulkan-<all>, glslang, spirv-tools, spirv-headers

python/py-tempora/Portfile, python/py-tempora/files/patch-fix-compat.diff
=> py-tempora: update to 5.7.0; add patch to fix test

python/py-attrs/Portfile
=> py-attrs: update to 24.2.0

python/py-sybil/Portfile
=> py-sybil: update to 8.0.0; pin 6.1.1 for py38

python/py-xlsx2csv/Portfile
=> py-xlsx2csv: update to 0.8.3

net/c-ares/Portfile
=> c-ares: update to 1.34.2

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.20.2

net/yggdrasil-go/Portfile
=> yggdrasil-go: update to 0.5.9

lang/libomp/Portfile
=> libomp:19.1.2

lang/logtalk/Portfile
=> logtalk: update to 3.84.0

emulators/uxn/Portfile
=> uxn: update to 20241019

devel/oxker/Portfile
=> oxker: update to 0.7.2

science/qucs/Portfile
* add myself as maintainer, removing rowue at his request.
macOS x.y
Have you
=> qucs: add myself as maintainer

net/wireshark4/Portfile
=> wireshark4: update to 4.4.1

games/fheroes2/Portfile
=> fheroes2: update to 1.1.3

x11/homebank/Portfile
=> homebank: update to 5.8.5

net/snac/Portfile
=> snac: update to 2.61

devel/got/Portfile
=> got: update to 0.104

python/py-certifi/Portfile, python/py-charset-normalizer/Portfile, python/py-idna/Portfile, python/py-requests/Portfile, python/py-urllib3/Portfile
=> py-requests: add py313 subport (including dependencies)

net/mldonkey/Portfile, net/mldonkey/files/patch-lablgtk.diff, x11/lablgtk2/Portfile
Update, ensure it actually builds.
macOS 14.7
Xcode 15.4
macOS 10.6
Xcode 3.2
Have you
=> mldonkey: update to 3.2.1, fix build

net/shadowsocks-rust/Portfile
=> shadowsocks-rust: update to v1.21.2

devel/cproto/Portfile
=> cproto: update to 4.7w

sysutils/bfs/Portfile
=> bfs: update to 4.0.3

devel/bun/Portfile
=> Bun: Update to 1.1.33

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 23.20.3

devel/libsdl2-powerpc/Portfile
Update
macOS 10.6.8
Xcode 3.2.6
Have you
=> libsdl2-powerpc: update to 2.30.8

devel/minify/Portfile
=> minify: update to 2.21.1

lang/algol68g/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> algol68g: update to 3.5.9

devel/libxmlb/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libxmlb: update to 0.3.21

devel/mk-configure/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> mk-configure: update to 0.40.0

mail/opensmtpd/Portfile
=> opensmtpd: update to 7.6.0p1

devel/hyprlang/Portfile, devel/hyprutils/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> hyprlang: update to 0.5.3

net/nghttp3/Portfile, net/ngtcp2/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> ngtcp2: update to 1.8.1; nghttp3: update to 1.6.0

devel/wt/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> wt: update to 4.11.0

math/linalg/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> linalg: update to 1.8.2

gis/qgis3/Portfile
Update `qgis3` to version 3.40 and `qgis3-ltr` to 3.34.12.
In addition, drop py38 support, and use latest PROJ (dropping the proj variants).
Have you
=> qgis3: update to 3.40.0; qgis3-ltr: updated to 3.34.12

devel/vttest/Portfile
=> vttest: update to 20241024

R/R-litedown/Portfile, R/R-mirai/Portfile, R/R-nanonext/Portfile, R/R-xfun/Portfile, devel/nng/Portfile, devel/nng/files/patch-u_int32_t.diff
Updates
macOS 10.6
Xcode 3.2
Have you
=> nng: update to 1.9.0; update R-related ports which use nng 

textproc/ugrep/Portfile
=> ugrep: update to 7.0.2

math/hiop/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> hiop: update to 1.1.0

math/HiGHS/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> HiGHS: update to 1.8.0

math/hypre/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> hypre: update to 2.32.0

sysutils/topgrade/Portfile
=> topgrade: update to 16.0.1

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.14

devel/jreleaser/Portfile
=> JReleaser v1.15.0

audio/lms/Portfile, audio/lms/files/0001-Fix-lms.conf-path.patch
Port requires revbump after `wt` update, but rather update it as well.
macOS 10.6
Xcode 3.2
Have you
=> lms: update to 3.60.0

python/py-random2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-random2: update to 1.0.2, drop unsupported pythons

gis/pdal/Portfile, gis/pgrouting/Portfile, gis/saga/Portfile, python/py-gdal/Portfile
Update `pdal` to version 2.8.1. (and use latest version of PROJ, dropping proj variants)
Update `saga` to version 9.6.1.
Update `py-gdal` to version 3.9.3.
Update `pgrouting` to 3.6.3. (and drop unnecessary dependency of cgal5)
Have you
=> pdal, saga, py-gdal, pgrouting: updates

R/R-tiledb/Portfile, R/R-tiledb/files/patch-unbreak-build.diff, databases/tiledb/Portfile
Also fixes a bug left from the last update.
macOS 10.6
Xcode 3.2
Have you
=> tiledb: update to 2.26.2

python/py-stagger/Portfile, python/py-stagger/files/patch-py310_collections.diff, python/py-stagger/files/patch-py312_rstring.diff, python/py-stagger/files/patch-py313_imghdr.diff, python/py-stagger/files/patch-pytest_collect.diff
=> py-stagger: new port, version 1.0.1

python/py-blinker/Portfile, python/py-cryptography/Portfile, python/py-cryptography/files/patch-setuptools_no_version.diff, python/py-jwt/Portfile, python/py-mock/Portfile, python/py-oauthlib/Portfile, python/py-oauthlib/files/0001-Make-UtilsTests.test_filter_params-Python-3.13-compa.patch, python/py-oauthlib/files/0002-Fix-CI-Errors-878.patch, python/py-pbr/Portfile, python/py-requests-mock/Portfile, python/py-requests-oauthlib/Portfile, python/py-requests-oauthlib/files/patch-no_selenium_tests.diff, python/py-setuptools-rust/Portfile
=> py-requests-oauthlib: update to 2.0.0, add py313 subport (including dependencies)

graphics/timg/Portfile
=> timg: Add new port of timg version 1.6.0

python/py-awscli2/Portfile
=> py-awscli2: update to 2.19.1

math/blaspp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> blaspp: update to 2024.10.26

audio/schismtracker/Portfile
New port
macOS 10.6
Xcode 3.2
Have you
=> schismtracker: new port in audio

devel/libsdl2-powerpc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: update to 2.30.9

www/nicotine-plus/Portfile, www/nicotine-plus/files/0757668709f00190c357549f3eb5101566da0bde.patch, www/nicotine-plus/files/937eacfb63e026030e4f010097c3c2e8f8a0cbf6.patch, www/nicotine-plus/files/patch-GTK3.diff, www/nicotine-plus/files/patch-GTK4.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> nicotine-plus: update to 3.3.6

databases/librasterlite2/Portfile, gis/gdal/Portfile
`gdal`:
- Use latest `proj` port, and drop its variants
- Remove deprecated variants +poppler and +libkml
- Add +rasterlite2 variant (closes https://trac.macports.org/ticket/68655)
`librasterlite2`:
- Use latest `proj` port, and drop its variants
Have you
=> gdal, librasterlite2: various updates

devel/vttest/Portfile
=> vttest: update to 20241031

sysutils/mas/Portfile, sysutils/mas/files/patch-fix-version.diff
=> mas: 1.8.7

mail/rspamd/Portfile
=> rspamd: Update to version 3.10.2

lang/racket/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> racket: update to 8.15

editors/abiword-x11/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> abiword-x11: update to 3.0.6

security/passage/Portfile
passage: Update to 1.7.4a2
Have you
=> passage: Update to 1.7.4a2

sysutils/neohtop/Portfile
=> neohtop: submission

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.0.11

www/dufs/Portfile
=> dufs: new port, version 0.43.0

python/py-Pillow/Portfile, python/py-Pillow/files/patch-setup.py.diff, python/py-cbor2/Portfile, python/py-game/Portfile, python/py-luma.core/Portfile, python/py-luma.emulator/Portfile, python/py-olefile/Portfile, python/py-pyftdi/Portfile, python/py-pyftdi/files/0001-tests-Fix-for-Python-3.13-unittest.makeSuite-was-rem.patch, python/py-pyusb/Portfile, python/py-ruamel-yaml/Portfile, python/py-smbus2/Portfile
=> py-luma.emulator: add py313 subport (including dependencies)

java/jdk22/Portfile
=> jdk22: updates until September 2024

java/jdk22-graalvm/Portfile
=> jdk22-graalvm: updates until September 2024

java/openjdk17-temurin/Portfile
=> openjdk17-temurin: Long Term Support

java/openjdk22-corretto/Portfile
=> openjdk22-corretto: EOL

java/openjdk22-sap/Portfile
=> openjdk22-sap: EOL

java/openjdk8-temurin/Portfile
=> openjdk8-temurin: LTS

math/bpack/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> bpack: update to 3.2.0

python/py-geographiclib/Portfile
=> py-geographiclib: add py313 subport

python/py-tomli/Portfile, python/py-yapf/Portfile, python/py-yapf/files/py313-yapf
=> py-yapf: add py313 subport (including dependencies)

python/pipx/Portfile
pipx: add python313 variant
Have you
=> pipx: add python313 variant, drop python38

math/igraph/Portfile
=> igraph: update to 0.10.15

math/nanoflann/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> nanoflann: update to 1.6.2

devel/CImg/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> CImg: update to 3.4.3

graphics/asymptote/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> asymptote: update to 2.92

math/mlpack/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> mlpack: update to 4.5.0

science/scotch/Portfile
Update
_This can be merged now._
macOS 10.6
Xcode 3.2
Have you
=> scotch: update to 7.0.5

math/normaliz/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> normaliz: update to 3.10.4

R/R-symengine/Portfile, math/symengine/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> symengine: update to 0.13.0

emulators/wine-devel/Portfile, emulators/wine-devel/files/0001-winemac.drv-no-flicker-patch.diff, emulators/wine-devel/files/1001-devel-msync.diff, emulators/wine-devel/files/1001-staging-msync.diff, emulators/wine-devel/files/macos_hacks.diff
Update `wine-devel`, `wine-staging`, updated and regenerated patches
=> wine-devel,wine-staging: Update to 9.21

gnome/desktop-file-utils/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> desktop-file-utils: update to 0.28

devel/oxker/Portfile
=> oxker: update to 0.8.0

graphics/vtk/Portfile
* add python312 variant
* remove python38 variant
* revert/fix python variant looping syntax
- Resolves the [syntax regression](https://github.com/macports/macports-ports/pull/26442#discussion_r1835155017) noted by @jmroot 
- Replaces #26515
Have you
=> vtk: add python312 variant

graphics/vtk/Portfile, python/py-apptools/Portfile, python/py-envisage/Portfile, python/py-mayavi/Portfile, python/py-pyface/Portfile, python/py-traits/Portfile, python/py-traitsui/Portfile
* update py-mayavi to 4.8.2
* update py-apptools to 5.3.0
* update py-envisage to 7.0.3
* update py-traitsui to 8.0.0
* update py-pyface to 8.0.0
* update python versions
- Python versions included to py312 (requires #26526 for mayavi).
Have you
=> py-mayavi: update to version 4.8.2

math/pari/Portfile, math/sympow/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> pari: update to 2.17.0; sympow: update to 2.023.7

math/gretl/Portfile, math/gretl/files/patch-fix-gretl_matrix.c.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> gretl: update to 2024c

java/detekt-cli/Portfile
=> detekt-cli: Update to version 1.23.7

python/py-igraph/Portfile, python/py-igraph/files/relax-setuptools-version.patch
=> py-igraph: update to 0.11.8

python/py-shapely/Portfile
=> py-shapely: add py313 subport

lisp/cl-3bmd/Portfile, lisp/cl-access/Portfile, lisp/cl-bordeaux-threads/Portfile, lisp/cl-cffi/Portfile, lisp/cl-chunga/Portfile, lisp/cl-closer-mop/Portfile, lisp/cl-colorize/Portfile, lisp/cl-colors2/Portfile, lisp/cl-containers/Portfile, lisp/cl-djula/Portfile, lisp/cl-easy-routes/Portfile, lisp/cl-esrap/Portfile, lisp/cl-fiveam/Portfile, lisp/cl-flexi-streams/Portfile, lisp/cl-float-features/Portfile, lisp/cl-hunchentoot/Portfile, lisp/cl-iterate/Portfile, lisp/cl-lass/Portfile, lisp/cl-local-time/Portfile, lisp/cl-parachute/Portfile, lisp/cl-parse-number/Portfile, lisp/cl-rove/Portfile, lisp/cl-static-vectors/Portfile, lisp/cl-str/Portfile, lisp/cl-trivial-gray-streams/Portfile, lisp/cl-usocket/Portfile, lisp/cl-who/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> lisp: update some packages

audio/lms/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
=> lms: update to 3.60.1

devel/oxen-logging/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> oxen-logging: update to 1.0.3

lang/logtalk/Portfile
=> logtalk: update to 3.85.0

devel/n/Portfile
=> n: update to 10.1

math/openlibm/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> openlibm: update to 0.8.4

python/py-pandas/Portfile, python/py-pandas/files/patch-pyproject.toml.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> py-pandas: update to 2.2.3

security/bitwarden-cli/Portfile
=> bitwarden-cli: Update to version 2024.10.0

python/py-httpx/Portfile
Update 
macOS 10.6
Xcode 3.2
Have you
=> py-httpx: update to 0.27.2

gnome/libadwaita/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libadwaita: update to 1.5.5

graphics/img2pdf/Portfile, python/py-deprecated/Portfile, python/py-pikepdf/Portfile
=> img2pdf: add python313 variant, remove python38 variant (including dependencies)

devel/got/Portfile
=> got: update to 0.105

net/snac/Portfile
=> snac: update to 2.63

python/py-flatbuffers/Portfile, python/py-protobuf3/Portfile
=> py-protobuf3: add py313 subport (including dependencies)

math/petsc/Portfile, math/slepc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> petsc, slepc: update to 3.22.1
