- python/py-makelive/Portfile
New port for MakeLive.
Have you
> py-makelive: new submission

- graphics/osxphotos/Portfile
Update to osxphotos 0.68.0.
Have you
> osxphotos: update to 0.68.0

- www/nghttp2/Portfile
> nghttp2: allow build on older systems

- cross/msp430-elf-gcc/Portfile
- cross/msp430-elf-gcc/files/gcc_config_host.diff
- cross/msp430-elf-gcc/files/gcc_system.diff
TI's versioning is a mess. The website reports 9.3.1.2, the release notes say 9.3.1.11 and everything is based on gcc 9.3.0. I kept the former as it is what I would expect after visiting TI's website. But that required a hack to make newlib compile.
The patches are backports of official gcc patches (see port comments with links to the issue trackers).
Have you
> msp430-elf-gcc: update to version 9.3.1.2

- devel/mspdebug/Portfile
- devel/mspdebug/files/fix-dynlib-load.diff
- devel/mspdebug/files/patch-Makefile-define_flag.diff
mspdebug requires the tilib driver to work properly with recent Texas Instrument's MSP430 Launchpad family ov development boards. This driver is missing in the current port. The tilib driver is provided by TI under the package MSP430 Debug Stack. #24397 introduces a port that provides the tilib driver. This enhancement:
1. add libmsp430 as a dependency (#24397)
2. provide patches so that mspdebug can find the shared library in the right place when installed through macports.
Have you
> mspdebug: add driver dependency

- devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases/tag/v0.176.0
Xcode 14.2
Have you
> jsoncons: update to 0.176.0

- devel/stm32flash/Portfile
* Fix worksrcdir
* Simplify port
* Take maintainership
* Align to current linting rules
Have you
> Fix port stm32flash

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.495. [Changelog](https://github.com/blacktop/ipsw/releases/tag/v3.1.495)
Have you
> ipsw: Update to 3.1.495

- lang/erlang/Portfile
(Upstream wants it to fail by default and a user to need to pass the arg to fix it. So we should fix it locally.)
macOS 10.6
Xcode 3.2
Have you
> erlang: unbreak for 32-bit

- java/micronaut/Portfile
Update to Micronaut Starter 4.5.0.
Have you
> micronaut: update to 4.5.0

- graphics/osxphotos/Portfile
Update to osxphotos 0.68.1.
Have you
> osxphotos: update to 0.68.1

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 480.0.0.
Have you
> google-cloud-sdk: update to 480.0.0

- devel/bun/Portfile
Update Bun to 1.1.13
For some reason, macOS 12 and 13 took forever to build in GitHub Actions on my fork, but they got there in the end.
14.5 23F79 arm64
Have you
> Bun: Update to 1.1.13

- _resources/port1.0/group/muniversal-1.1.tcl
> muniversal PG: add finer control `-arch` flag

- lang/algol68g/Portfile
- lang/algol68g/files/0001-configure.ac-fix-triples.patch
Update
macOS 10.6
Xcode 3.2
Have you
> algol68g: update to 3.5.3

- math/pyxplot/Portfile
The last port on my system which requires revbump after a recent GSL update.
macOS 10.6
Xcode 3.2
Have you
> pyxplot: revbump upon gsl update

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.11
Have you
> uv: Update to 0.2.11

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.497
Have you
> ipsw: Update to 3.1.497

- textproc/dwdiff/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
> dwdiff: fix build on < 10.7

- textproc/CSXCAD/Portfile
- textproc/CSXCAD/files/patch-CMakeLists.diff
- textproc/CSXCAD/files/patch-no-mpich.diff
Update
macOS 10.6
Xcode 3.2
Have you
> CSXCAD: update to 20231216 and fix the build

- sysutils/snapraid/Portfile
My first contribution, so hopefully I've done this correctly. This is a Portfile for snapraid (https://github.com/amadvance/snapraid). I've used this for v12.2 without submitting, and with v12.3, it still works well, so submitting. I'll maintain this as updates are released, and I install updates for my own usage. 
Have you
> snapraid: new port

- devel/editorconfig-core-c/Portfile
Update `editorconfig-core-c` to its latest released version, 0.12.8
Have you
> editorconfig-core-c: Update to 0.12.8

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.498
Have you
> ipsw: Update to 3.1.498

- databases/pgpointcloud/Portfile
- databases/pgpointcloud/files/04-patch-pgsql.diff
This is still broken: the port uses C++11, so it cannot possibly build with pre-C++11 compilers. Fix this finally.
macOS 10.6
Xcode 3.2
Have you
> pgpointcloud: fix for older systems

- sysutils/libosinfo/Portfile
- sysutils/libosinfo/files/patch-unbreak-linking.diff
Update
macOS 10.6
Xcode 3.2
Have you
> libosinfo: update to 1.11.0

- devel/gk/Portfile
> gk update to v2.0.1

- math/itpp/Portfile
> itpp: needs compiler thread_local_storage

- net/openfortivpn/Portfile
- net/openfortivpn/files/patch-fix-configure.diff
- net/openfortivpn/files/patch-vdprintf.diff
Update and fix
macOS 10.6
Xcode 3.2
Have you
> openfortivpn: update to 1.22.0, fix build on older systems

- kde/kget/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
> kget: requires C++11

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.4.9
Have you
> ruff: Update to 0.4.9

- x11/xournalpp/Portfile
- x11/xournalpp/files/patch-CMakeLists.diff
The port is currently broken across the board: https://ports.macports.org/port/xournalpp/details
Fix it, update.
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.4
Have you
> xournalpp: update to 1.2.3, fix build

- science/gmic/Portfile
Self-explanatory
macOS 10.6
Xcode 3.2
Have you
> gmic*: use legacysupport for strnlen

- sysutils/osxbom/Portfile
Closes: https://trac.macports.org/ticket/38306
`osxbom` is a free reimplementation of the NextSTEP/OSX `lsbom` utility. It is used by the PureDarwin project to deal with MacPorts binary packages.
submission
Have you
> osxbom: new port

- python/py-matplotlib/Portfile
Fix the condition. The issue is not SDK but compiler: amazing Apple ObjC does not compile with GCC.
macOS 10.6
Xcode 3.2
Have you
> py-matplotlib: fix condition to disable native backend on old systems

- sysutils/k9s/Portfile
Update to k9s 0.32.5.
Have you
> k9s: update to 0.32.5

- devel/onetbb/Portfile
Closes: https://trac.macports.org/ticket/69657
I cannot test this, but looks like this should work.
macOS x.y
Have you
> onetbb: fix for 10.10–10.11

- editors/emacs/Portfile
Update to latest master
Have you
> emacs{,-app}-devel: update to 20240615

- gis/GPXSee/Portfile
> GPXSee: update to 13.22

- multimedia/kdenlive/Portfile
Fix dependencies.
_CI will fail due to `kdelibs4` broken by `raptor2`. This is expected and unrelated._
macOS 10.6
Xcode 3.2
Have you
> kdenlive: fix dependencies

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.21.0
Have you
> gitu: Update to 0.21.0

- devel/editorconfig-core-c/Portfile
Update `editorconfig-core-c` to its latest released version, 0.12.9
Have you
> editorconfig-core-c: Update to 0.12.9

- mail/neomutt/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
> neomutt: fix build on old systems

- net/paho.mqtt.cpp/Portfile
[Changelog](https://github.com/eclipse/paho.mqtt.cpp/releases)
Xcode 14.2
Have you
> paho.mqtt.cpp: update to 1.4.0

- devel/libimobiledevice-glue/Portfile
Update `libimobiledevice-glue` to its latest released version, 1.3.0
Have you
> libimobiledevice-glue: Update to 1.3.0

- java/mvnd/Portfile
Update to mvnd 1.0.0.
Have you
> mvnd: update to 1.0.0

- graphics/osxphotos/Portfile
Update to osxphotos 0.68.2.
Have you
> osxphotos: update to 0.68.2

- java/maven3/Portfile
Update to Maven 3.9.8.
Have you
> maven3: update to 3.9.8

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.12
Have you
> uv: Update to 0.2.12

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.499
Have you
> ipsw: Update to 3.1.499

- graphics/chafa/Portfile
> chafa: fix build on macOS < 10.14

- gis/liblas/Portfile
Increase revision of `liblas` after update to GDAL 3.9.0.
macOS x.y
Have you
> liblas: increase revision after update to GDAL 3.9.0

- devel/binutils/Portfile
Closes: https://trac.macports.org/ticket/37921
The current `port notes` for binutils are rather vague. This new wording should make the notes clearer and less scary-sounding.
Have you
> binutils: update notes

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.13
Have you
> uv: Update to 0.2.13

- mail/libvmime/Portfile
- mail/libvmime/files/patch-unbreak-arm64-powerpc.diff
Do not break ppc unnecessarily.
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.4
Have you
> libvmime: allow builds on powerpc and arm64

- sysutils/tzdiff/Portfile
tzdiff 1.2.1 released
macOS 14.5
FreeBSD 13.3 / 14.1
Debian 12.5
> tzdiff: update to 1.2.1

- gis/rsgislib/Portfile
Update `rsgislib`, `py-rsgislib` to version 5.1.6.
`rsgislib` previously installed a version of the utility `flip`, which conflicted with the port of the same name.
The rsgislib's version of flip has now been renamed to `rsgisflip` and the conflict is now solved.
Closes: https://trac.macports.org/ticket/70213
Have you
> rsgislib, py-rsgislib: update to 5.1.6

- multimedia/QMPlay2/Portfile
Update
macOS 14.5
Xcode 15.4
Have you
> QMPlay2: update to 24.06.16

- python/py-makelive/Portfile
Use `python.pep517_backend`, as recommended via https://github.com/macports/macports-ports/pull/24446#pullrequestreview-2126807646.
Have you
> py-makelive: use python.pep517_backend

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.500
Have you
> ipsw: Update to 3.1.500

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 481.0.0.
Have you
> google-cloud-sdk: update to 481.0.0

- net/offpunk/Portfile
The `chafa` port seems fixed (except [i386 platform](https://github.com/hpjansson/chafa/issues/203)), so I want to see how it builds on buildbots now.
Have you
> offpunk: revbump after chafa fix

- python/py-mako/Portfile
Update to Mako 1.3.5.
Have you
> py-mako: update to 1.3.5

- python/py-wurlitzer/Portfile
Update to Wurlitzer 3.1.1.
Have you
> py-wurlitzer: update to 3.1.1

- python/py-more-itertools/Portfile
Update to More Itertools 10.3.0.
Have you
> py-more-itertools: update to 10.3.0

- fortran/fortran-pcre2/Portfile
- fortran/fortran-pcre2/files/patch-Makefile.diff
Something went wrong with this port earlier, required patch got lost.
Anyway, update it also and ensure it builds and tests run.
macOS 10.6
Xcode 3.2
Have you
> fortran-pcre2: update to 0.1.1, fix build

- python/py-makelive/Portfile
Update to MakeLive 0.6.1.
Have you
> py-makelive: update to 0.6.1

- devel/xa/Portfile
> xa: update to 2.4.1

- devel/minizinc/Portfile
- devel/minizinc/files/0001-file_utils.cpp-add-a-missing-cstdint-include.patch
Fix for gcc13, minor improvements
macOS 10.6
Xcode 3.2
Have you
> minizinc: fix build with gcc13, switch to legacysupport 1.1

- gis/pcraster/Portfile
The binary file 'legend' is renamed to 'pcrlegend', due to conflict with mapserver.
Bump default Python variant to version 3.12 (which now is the case for most other GIS ports).
Have you
> pcraster: fix conflict with mapserver; default to +py312

- graphics/xfractint/Portfile
- graphics/xfractint/files/patch-prefix-x11-dirs.diff
Closes: https://trac.macports.org/ticket/70092
Closes: https://trac.macports.org/ticket/63280
Have you
> xfractint: update to 20.04p16

- devel/jemalloc/Portfile
Update -devel subport
macOS 10.6
Xcode 3.2
Have you
> jemalloc-devel: update to 2024.06.13

- net/kcat/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
> kcat: fix build on older OS

- multimedia/libcec/Portfile
Fix build with gcc via legacysupport.
Switch to cmake 1.1 PG.
macOS 10.6
Xcode 3.2
Have you
> libcec: fix build with gcc

- R/R-distrMod/Portfile
Checksums mismatch now.
macOS 10.6
Xcode 3.2
Have you
> R-distrMod: handle stealth update, add test deps

- python/py-tenacity/Portfile
Update to Tenacity 8.4.1.
Have you
> py-tenacity: update to 8.4.1

- sysutils/clifm/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> clifm: update to 1.18

- sysutils/lirc/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> lirc: fix build on older systems

- emulators/wine-devel/Portfile
- emulators/wine-devel/files/5871.patch
- emulators/wine-stable/Portfile
- emulators/wine-stable/files/5871.patch
Apply the upstream MR so `wine-stable`, `wine-devel` & `wine-staging` build with Xcode16
macOS x.y
> wine-stable,wine-devel: Upstream MR 5871 - Fix macOS build errors with Xcode 16.

- devel/openssl/Portfile
- devel/openssl3/Portfile
- devel/openssl3/files/patch-use-timegm.diff
- net/openssh/Portfile
- perl/p5-net-ssleay/Portfile
- sysutils/freeradius/Portfile
```
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 …
```
> openssl3: Remove version holdback for OS <10.14.

- gis/imposm/Portfile
https://github.com/omniscale/imposm3/releases/tag/v0.13.2
Xcode 14.2
Have you
> imposm: update to 0.13.2

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.4.10
Have you
> ruff: Update to 0.4.10

- science/opendx/Portfile
- science/opendx/files/patch-compiler_compat_2024.diff
Make opendx compile with current clang, which has made some things that were previously warnings into errors. This involves making some function arguments explicitly type `int`, casting some inconsistent function return types, and replacing various `static char []` in bitmaps (`*.bm` files) with `static unsigned char []`, and then casting them back to `char *` when passing to X functions that expect this data type.
Have you
> Update to opendx -  fix warning/error compatibility issues with modern clang

- emulators/wine-devel/Portfile
GitHub PG livecheck works just fine for this
> wine-devel: Remove livecheck override

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.21.1
Have you
> gitu: Update to 0.21.1

- devel/peg/Portfile
Closes: https://trac.macports.org/ticket/70239
Have you
> peg: Downgrade to latest stable version 0.1.19

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.3.1.
Have you
> spring-boot-cli: update to 3.3.1

- devel/openssl3/Portfile
This was negelected in the update, and ensures better handling of existing -devel installs (only applicable to OS <10.14).
TESTED:
On 10.9, the openssl3-devel port correctly reports as obsolete, doesn't refuse "port clean", and installs openssl-3.3.1_1 on "port upgrade".
```
```
Have you
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [NO] tried existing tests with `sudo port test`?
- [NO] tried a full install with `sudo port -vst install`?
- [NO] tested basic functionality of all binary files?
- [NO] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?
NOTE: Abbreviated testing since the only change is …
> openssl3: Make obsoleteness of -devel subport explicit.

- databases/mysql8/Portfile
- databases/mysql8/files/patch-cmake-install_layout.cmake.diff
- databases/mysql8/files/patch-copy_openssl_binary.cmake.diff
- databases/mysql8/files/patch-ssl.cmake.diff
- perl/p5-dbd-mysql/Portfile
mysql8:
In more recent mysql8 releases, some of the cmake files have are
hard coded to the homebrew install locations.  This commit resolves
the issues when using the macports openssl / libcrypto packages.
This commit also resolved issues where mysql_config produced the
incorrect path for the installed mysql support libraries.
p5-dbd-mysql:
This commit additionally updates p5-dbd-mysql to 5.006
Closes: https://trac.macports.org/ticket/70001
Have you
Renders [PR 24232](https://github.com/macports/macports-ports/pull/24232) obsolete
QT6 will require an update that reverses [dd5b391](https://github.com/macports/macports-ports/commit/dd5b391e5a3c4263f3457732b5f7c09ceec089b9)
GDAL will require an update that reverses …
> mysql8, p5-dbd-mysql: Fix my_openssl / mysqlclient.dylib link errors

- science/nco/Portfile
Simple update to upstream version 5.2.6
Have you
> nco: update to 5.2.6

- databases/tiledb/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
> tiledb: update to 2.24.1

- textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.4.0
Have you
> ocrmypdf: update to 16.4.0

- gnome/libshumate/Portfile
New port
macOS 14.5
Xcode 15.4
macOS 10.6
Xcode 3.2
Have you
> libshumate: new port in gnome

- lang/ruby33/Portfile
- lang/ruby33/files/patch-sources.diff
This regenerates the patchfile from updated git commits, and updates the related comment in the Portfile.  There are no substantive changes in the Patchfile, but the mtimes are updated to correspond to the new release.  The result of the patch phase is unchanged.
Also, the update URL was omitted from the original update commit message.  See:
https://www.ruby-lang.org/en/news/2024/06/12/ruby-3-3-3-released/
TESTED:
Verified that the build trees from "port patch" are identical before and after this change.
```
```
Have you
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [NO] tried existing tests with `sudo port test`?
- [NO] tried a full install with `sudo port -vst …
> ruby33: Cosmetic patchfile cleanup

- devel/openscop/Portfile
- devel/openscop/files/patch-fix-tests-linking.diff
Minor fix
macOS 10.6
Xcode 3.2
Have you
> openscop: fix linking of tests

- science/hdf4/Portfile
- science/hdf4/files/implicit-int.patch
- science/hdfeos/Portfile
- science/hdfeos/files/implicit.patch
hdf4: Fix implicit int error
hdfeos: Fix implicit function declaration
Closes: https://trac.macports.org/ticket/70234
with MacPorts clang 18
Have you
> hdf4: Fix implicit int error; hdfeos: Fix implicit function declaration

- devel/gcli/Portfile
- devel/gcli/files/patch-Xcode-gcc.diff
Fix
macOS 10.6
Xcode 3.2
Have you
> gcli: fix build with Xcode gcc

- emulators/wine-devel/Portfile
- emulators/wine-stable/Portfile
Instead of using the stub just directly call `MoltenVK-latest`
> wine-stable.wine-devel: Swap from MoltenVK stub to MoltenVK-latest

- textproc/wc2/Portfile
- textproc/wc2/files/patch-pedantic.diff
Minor fix.
(If does not work unconditionally, I make it only for Xcode gcc.)
macOS 10.6
Xcode 3.2
Have you
> wc2: use -pedantic instead of -Wpedantic

- security/KeePassXC/Portfile
xattr error does not occur in this update
Have you
> KeePassXC: update to 2.7.9

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.502
Have you
> ipsw: Update to 3.1.502

- python/py-ptpython/Portfile
Update to ptpython 3.0.27.
Have you
> py-ptpython: update to 3.0.27

- octave/octave-piqp/Portfile
- octave/octave-piqp/files/patch-fix-build.diff
- octave/octave-piqp/files/patch-unbreak-eigen3.diff
1. Drop `-march=native`, revbump.
2. Also disable broken Altivec in Eigen3.
macOS 10.6
Xcode 3.2
Have you
> octave-piqp: fix the build

- net/libsrtp/Portfile
Fix build after the recent update
macOS 10.6
Xcode 3.2
Have you
> libsrtp: fix the build

- python/py-asynctest/Portfile
Support new pythons
macOS 14.5
Xcode 15.4
Have you
> py-asynctest: add py311–312 subports

- net/openvpn2/Portfile
Needs legacysupport
macOS 10.6
Xcode 3.2
Have you
> openvpn2: fix build on < 10.7

- sysutils/kube-ps1/Portfile
Update to kube-ps1 0.9.0.
Have you
> kube-ps1: update to 0.9.0

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.503
Have you
> ipsw: Update to 3.1.503

- python/py-cryptography/Portfile
- python/py-cryptography/files/patch-build-no-rust.diff
- python/py-cryptography/files/patch-openssl3.diff
Current `py3*-cryptography` are broken since they link to OpenSSL 3 but use symbols from OpenSSL 1.1. While I found a way to build 3.3.2 against OpenSSL 1.1, wasting a lot of time, and solution is simple but ugly, rather update them to 3.4.8.
`py27` subport uses OpenSSL 1.1 by default and is not supported in 3.4 branch. (So nothing to fix for it, and it cannot be updated along.)
macOS 10.6
Xcode 3.2
Have you
> py-cryptography: update to 3.4.8 for legacy systems

- editors/emacs/Portfile
- Emacs 29.4: security update
- emacs{,-app}-devel: security update and move to 31.0.50
Have you
> Emacs updates

- python/py-rencode/Portfile
Support Python 3.12
macOS 10.6
Xcode 3.2
Have you
> py-rencode: add py312 subport

- science/ecCodes/Portfile
Simple update to upstream version 2.36.0
Have you
> ecCodes: update to 2.36.0

- lang/idris2/Portfile
- lang/idris2/files/0007-chez-support.ss-support-macOS-PowerPC.patch
One case was missed initially and pointed by upstream now. Fix it.
macOS 10.6
Xcode 3.2
Have you
> idris2: a fix and revbump

- net/gallery-dl/Portfile
gallery-dl: update to 1.27.1
Have you
> gallery-dl: update to 1.27.1

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.15
Have you
> uv: Update to 0.2.15

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.505
Have you
> ipsw: Update to 3.1.505

- java/mvnd/Portfile
Update to mvnd 1.0.1.
Have you
> mvnd: update to 1.0.1

- graphics/ImageMagick7/Portfile
* Update ImageMagick7.1.1-30 --> 7.1.1-34
* Clean up long_description
Xcode 15.4 / Command Line Tools 15.1.0
Have you
> imagemagick7: Update to 7.1.1-34

- textproc/pandoc/Portfile
pandoc: update to 3.2.1
Have you
> pandoc: update to 3.2.1

- python/py-pytest-asyncio/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> py-pytest-asyncio: update to 0.23.7

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 482.0.0.
Have you
> google-cloud-sdk: update to 482.0.0

- math/libKriging/Portfile
Revbumps were not done.
macOS 10.6
Xcode 3.2
Have you
> libKriging: revbump to unbreak after armadillo upgrade

- math/hpddm/Portfile
> hpddm: Update to 2.3.0

- lang/chez-scheme/Portfile
- lang/chez-scheme/files/intrinsics.patch
Closes: https://trac.macports.org/ticket/70278
Have you
> chez-scheme: Only use intrinsics if available

- devel/hwloc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> hwloc: update to 2.11.0

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.507
Have you
> ipsw: Update to 3.1.507

- devel/game-porting-toolkit/Portfile
This make the SDK check work correctly so build will error out when required SDK isn't precent, `MacOSX13.sdk` is required to build on macOS Sequoia.
No rev-bump is required as installed files don't change, the build currently simply fails on macOS Sequoia (fixed by #24703) and this check being incorrect.
macOS 15 (beta 2)
Xcode Command Line Tools 16 (beta 2)
> game-porting-toolkit: Correct SDK check

- devel/cereal/Portfile
The port explicitly claims C++11, but fails to actually set it.
macOS 10.6
Xcode 3.2
Have you
> cereal: set cxx_standard 2011

- emulators/wine-stable/Portfile
~~Need to rebase some upstream changes to resolve this properly but this will do for the interim.~~
macOS 15 (beta 2)
Xcode Command Line Tools 16 (beta 2)
> wine-stable: Force MacOSX14.sdk for macOS Sequoia

- lang/llvm-cx/Portfile
macOS 15 (beta 2)
Xcode Command Line Tools 16 (beta 2)
> llvm-cx: Fix for Xcode16

- cross/i686-w64-mingw32-gcc/Portfile
- cross/mingw-w64/Portfile
- cross/x86_64-w64-mingw32-gcc/Portfile
UCRT is now the default CRT runtime instead of MSVCRT, so need to rev-bump *-w64-mingw32-gcc Ports at the same time.
See https://www.mingw-w64.org/changelog/#v1200-2024-05-29
> mingw-w64: Update to 12.0.0

- devel/hut/Portfile
Update the hut tool to its latest version, 0.6.0. Per [the README](https://git.sr.ht/~emersion/hut/tree/master/item/README.md), the repo's home has also changed to another user on sourcehut.
Have you
> hut: update to 0.6.0

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.17
Have you
> uv: Update to 0.2.17

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.5.0. This port now includes shell completions.
Have you
> ruff: Update to 0.5.0

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.22.0
Have you
> gitu: Update to 0.22.0

- devel/chai/Portfile
- devel/raja/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> raja, chai: update to 2024.02.2

- gis/gdal/Portfile
* Update GDAL 3.9.0 --> 3.9.1
* Includes numerous upstream bug fixes, including compile fixes.
* Includes fixes for the new plugin capability introduced in 3.9.0.
* See release announcement and release notes:
* https://lists.osgeo.org/pipermail/gdal-announce/2024-June/000119.html
* Also do not opportunistically link to armadillo. See PR #24687.
* Also switch to path-style dependency for pkgconfig.
CI only. OS 12, 13, 14 only.
Maintainer also tested the RC2.
Have you
> gdal: Update to 3.9.1

- net/deluge/Portfile
- python/py-automat/Portfile
- python/py-constantly/Portfile
- python/py-incremental/Portfile
- python/py-m2r/Portfile
- python/py-pyhamcrest/Portfile
- python/py-twisted/Portfile
`libtorrent-rasterbar` has been switched to python312 earlier without considering `deluge`, which uses python311 by default. In addition, it uses a different Boost.
Also, on of its Python dependencies does not build at all, which leaves it broken.
Fix this.
P. S. Running `deluge` also requires these:
https://github.com/macports/macports-ports/pull/24679
https://github.com/macports/macports-ports/pull/24658
macOS 10.6
Xcode 3.2
Have you
> deluge: switch to python312 and boost181 to match libtorrent-rasterbar, fix dependencies

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.508
Have you
> ipsw: Update to 3.1.508

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.18
Have you
> uv: Update to 0.2.18

- lang/groovy/Portfile
Update to Groovy 4.0.22.
Have you
> groovy: update to 4.0.22

- devel/cppcheck/Portfile
> cppcheck: update to 3.14.2

- textproc/pdfjam/Portfile
Update to pdfjam 3.12.
Have you
> pdfjam: update to 3.12

- net/mscp/Portfile
Fix the port
macOS 10.6
Xcode 3.2
Have you
> mscp: fix build on systems where it fails

- gis/gdal/Portfile
This fix is independent of anything else and does not need a revbump.
@kencu Ken, I followed your suggestion, dropping a conditioning on build arch.
macOS 10.6
Xcode 3.2
Have you
> gdal: fix arrow variant on 32-bit platforms (no revbump needed)

- devel/icmake/Portfile
Simple fix
macOS 10.6
Xcode 3.2
Have you
> icmake: fix build on older systems

- cross/x86_64-binutils/Portfile
Builds cross binutils for linux dragonfly embedded freebsd netbsd and openbsd.#### Description
macOS 13.6.4 22G513 arm64
Have you
> x86_64-binutils: new package

- audio/FAudio/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> FAudio: update to 24.07

- devel/cppcheck/Portfile
https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/270063/steps/install-port/logs/stdio
Doesn't happen on other buildbots that use the newer Clang.
Have you
> cppcheck: fix build on macOS <10.12

- net/openssh/Portfile
- net/openssh/files/launchd.patch
- net/openssh/files/pam.patch
- net/openssh/files/patch-sshd-session.c-apple-sandbox-named-external.diff
Update OpenSSH to 9.8p1, update patches so they apply
Have you
> openssh: update to 9.8p1, update patchfiles

- ruby/ruby-build/Portfile
ruby-build: Upgrade to 20240702
Have you
> ruby-build: Upgrade to 20240702

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.20
Have you
> uv: Update to 0.2.20

- textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.4.1
Have you
> ocrmypdf: update to 16.4.1

- science/dcw-gmt/Portfile
Simple update to upstream version 2.2.0
Have you
> dcw-gmt: update to 2.2.0

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 483.0.0.
Have you
> google-cloud-sdk: update to 483.0.0

- databases/mysql8/Portfile
On older versions of macOS, cmake does not automatically set the
OPENSSL_ROOT_DIR flag.  This flag needs to be set to avoid tripping
hard-coded Homebrew logic in the ssl.cmake cmake file.
Closes: https://trac.macports.org/ticket/70314
This fixes a regression introduced in https://github.com/macports/macports-ports/pull/24696 (sorry about that)
Have you
> mysql8: Add missing cmake PortGroup Flag OPENSSL_ROOT_DIR

- graphics/chafa/Portfile
- graphics/chafa/files/patch-extract-128-epi64.diff
Can't really check, but the issue mentioned in the comments solved the build on Void Linux i686. It's unclear when the update will be released, but it's worth a try.
Have you
> chafa: fix build on i386 systems

- lang/wren-cli/Portfile
* Update to 0.4.0
* Fix build failure when libuv port is active (https://trac.macports.org/ticket/68057)
* Fix universal variant and enable non-Intel archs (I tried an x86_64/arm64 universal build on macOS 12 and it succeeded but I don't know whether the arm64 part works; the port gave no explanation for why it had been limited to Intel archs so I've speculatively removed the limit)
* Fix whitespace to conform to modeline (4 spaces per indent)
Have you
> wren-cli: Update to 0.4.0; fix conflict with libuv; fix universal variant and enable non-Intel archs; fix whitespace

- lang/ruby-devel/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> ruby-devel: update to 2024.07.04

- science/madness/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> madness: update to 2024.06.27

- science/cdo/Portfile
Simple update to upstream version 2.4.2
Have you
> cdo: update to 2.4.2

- _resources/port1.0/compilers/gcc_dependencies.tcl
[skip ci]
@cjones051073 We forgot this one again )
macOS x.y
Have you
> gcc_dependencies: sync compiler choice to use gcc14

- lang/MoarVM/Portfile
https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/197004/steps/install-port/logs/stdio
https://developer.apple.com/documentation/kernel/mach_task_basic_info_t
Have you
> MoarVM: enable mimalloc support in a separate variant

- devel/bun/Portfile
> Bun: Update to 1.1.18

- _resources/port1.0/group/R-1.0.tcl
- math/R/Portfile
Setting a variant works for systems with clang, where gcc is only providing gfortran.
It is not sufficient when gcc is used as the primary compiler.
(No need to revbump, since there are no systems in MacPorts which use modern gcc instead of clang by default.)
macOS 10.6
Xcode 3.2
Have you
> R, R PG: ensure correct gcc picked when gcc is the primary compiler (no revbump)

- databases/sqlean/Portfile
@herbygillot I do not update directly to 0.24.0 due to: https://github.com/nalgeon/sqlean/issues/124
macOS 10.6
Xcode 3.2
Have you
> sqlean: update to 0.23.0, fix build on old systems

- irc/znc/Portfile
> znc: fix build on macOS <10.14

- sysutils/flashrom/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
> flashrom: fix build for < 10.7

- math/petsc/Portfile
- math/slepc/Portfile
`slepc` does not build since it is too old. Update both ports.
macOS 10.6
Xcode 3.2
Have you
> petsc: update to 3.21.2; slepc: update to 3.21.1, fix the port

- python/py-pudb/Portfile
- python/py-urwid/Portfile
Tested the same way as in #18183 and #18184. For pudb I also ran a simple script through it.
There are updates to both packages, but py-urwid no longer supports Python 2.7 and there are other ports (`PIDA`, `alot`) that depend on the py27 subport. Updating pudb to a five year newer version without updating urwid might well break things, so I am leaving both packages on their current versions for now.
Have you
> py-urwid,py-pudb: add py312 subport

- python/py-mistune/Portfile
Subports was deleted without checking if something depends on it. And there are several ports that do.
macOS x.y
Have you
> py-mistune: restore py27 subport to unbreak dependents

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.21
Have you
> uv: Update to 0.2.21

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.22.1
Have you
> gitu: Update to 0.22.1

- audio/rtmidi/Portfile
Fix the build on old systems.
macOS 10.6
Xcode 3.2
Have you
> rtmidi: set correct C++ standard

- devel/xeus-zmq/Portfile
https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/270323/steps/install-port/logs/stdio
https://github.com/jupyter-xeus/xeus-zmq/commit/2081a57728b19c312dc26ffb312fbc0f25a6ce44
Have you
> xeus-zmq: set cxx_standard 2017

- xfce/mousepad/Portfile
Updates Mousepad to 0.6.2, enabling GTK3 in the process.  (Since https://github.com/macports/macports-ports/pull/23731 is currently stalled, the necessary tweaks have been made to not depend on that PR.)
Have you
> mousepad: Update to 0.6.2

- graphics/feh/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> feh: update to 3.10.3

- office/timewarrior/Portfile
- office/timewarrior/files/patch-fix-cxx.diff
Set the required standard to fix compiler choice.
Drop hardcoded flag which breaks the build with libstdc++.
macOS 10.6
Xcode 3.2
Have you
> timewarrior: unbreak for systems with libstdc++

- emulators/qemu/Portfile
This is useful for server operating systems as it's easier to copy/paste from the terminal and not require a separate window. It also doesn't conflict with `+cocoa`.
Have you
> qemu: enable +curses always

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.5.1
Have you
> ruff: Update to 0.5.1

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.512. [ipsw@`v3.1.508...v3.1.512`](https://github.com/blacktop/ipsw/compare/v3.1.508...v3.1.512)
Have you
> ipsw: Update to 3.1.512

- net/unison/Portfile
- x11/lablgtk2/Portfile
Later versions of `unison` switch to `lablgtk3`, which is not a trivial upgrade and also in experimental status.
macOS 10.6
Xcode 3.2
Have you
> unison: update to 2.52.0, fix build for powerpc; lablgtk2: update to 2.18.13

- devel/xeus/Portfile
https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/239315/steps/install-port/logs/stdio
As in #24831, it now [also targets C++ 17](https://github.com/jupyter-xeus/xeus/commit/089f18026ff4ae5939c8de95f258061ae2926a80).
Have you
> xeus: set cxx_standard 2017

- gis/gdal/Portfile
`gdal` is currently broken on macOS 10.12 and earlier, because of too old libc++. This PR upgrades to PortGroup `legacysupport 1.1` and enable the use of MacPort's libc++ for macOS earlier than 10.13.
See: https://trac.macports.org/ticket/70228#comment:7
Replaces #24726
macOS x.y
Have you
> gdal: enable MacPort's libc++ on macOS 10.12 and earlier

- xfce/ristretto/Portfile
(Since https://github.com/macports/macports-ports/pull/23731 is currently stalled, the necessary tweaks have been made to not depend on that PR.)
Have you
> ristretto: Update to 0.13.2

- sysutils/albafetch/Portfile
- sysutils/albafetch/files/0001-fix-macos_infos.patch
Tweaked the patch a bit, I'll do a PR in the upstream later.
Have you
> albafetch: fix build on macOS <10.9, refactor patch

- devel/kokkos/Portfile
Update devel subport
macOS 10.6
Xcode 3.2
Have you
> kokkos-devel: update to 2024.07.05

- sysutils/edid-decode/Portfile
* update to version 20240703
macOS 15.0 24A5279h arm64
Have you
> edid-decode: update to version 20240703

- lang/MoarVM/Portfile
Looks like what we have with clangs is now also an issue with gcc.
macOS 10.6
Xcode 3.2
Have you
> MoarVM: fix build with gcc14

- math/mathmod/Portfile
- math/mathmod/files/patch-ParisoMathObject.cpp.diff
- math/mathmod/files/patch-ParisoMathObject.h.diff
- math/mathmod/files/patch-commun.cpp.diff
- math/mathmod/files/patch-drawingoptions.cpp.diff
- math/mathmod/files/patch-drawingoptions.ui.diff
- math/mathmod/files/patch-jiso.h.diff
- math/mathmod/files/patch-jpar.h.diff
- math/mathmod/files/patch-mathmodconfig.js.diff
- math/mathmod/files/patch-parametersoptions.cpp.diff
- math/mathmod/files/patch-parametersoptions.h.diff
New port in math
macOS 10.6
Xcode 3.2
macOS 14.5
Xcode 15.4
Have you
> mathmod: new port in math

- gnome/gjs/Portfile
- gnome/gjs/files/patch-atomic_load.diff
- gnome/gjs/files/patch-gjs-gint64.diff
- gnome/gjs/files/patch-gjs-gsize.diff
- gnome/gjs/files/patch-gjs-meson_options-legacy.diff
- gnome/gjs/files/patch-gjs-test-legacy.diff
Fix this finally.
I can confirm that it actually works: at least I can build apps requiring it:
macOS 10.6
Xcode 3.2
Have you
> gjs: fix for systems where latest mozjs fails

- gnome/gnucash-docs/Portfile
- gnome/gnucash/Portfile
* move dependent gnucash-docs to variant docs
Upstream seperates gnucash and gnucash-doc so that gnucash can work well without gnucash-doc. Since gnucash-doc aren't currently working anyway (https://github.com/macports/macports-ports/pull/23661#issuecomment-2101247020), and https://trac.macports.org/ticket/69942 seems won't be fixed in a short time, it will be better if we have a no-docs variant gnucash.
cc @drkp 
Have you
> gnucash: add variant docs

- ruby/ruby-build/Portfile
ruby-build: Upgrade to 20240709.1
- Add JRuby 9.4.8.0
- Add Ruby 3.3.4
- Use OpenSSL 3 LTS
Have you
- Add JRuby 9.4.8.0
- Add Ruby 3.3.4
- Use OpenSSL 3 LTS
> ruby-build: Upgrade to 20240709.1

- net/telescope/Portfile
[Changelog](https://github.com/omar-polo/telescope/releases)
Xcode 14.2
Have you
> telescope: update to 0.10.1

- science/gildas/Portfile
- science/gildas/files/patch-admin-Makefile.build.diff
> Gildas: update to 202407b

- gis/JOSM/Portfile
macOS 12.6.7 x86_64
Xcode 14.2
Have you
> josm: update to 19128

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.514
Have you
> ipsw: Update to 3.1.514

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.23
Have you
> uv: Update to 0.2.23

- devel/skaffold/Portfile
Update to Skaffold 2.13.0.
Have you
> skaffold: update to 2.13.0

- emulators/dosbox-x/Portfile
Update dosbox-x to version 2024.07.01
macOS 13.6.7 22G720 arm64
Have you
> dosbox-x: update to version 2024.07.01

- net/paho.mqtt.cpp/Portfile
[Changelog](https://github.com/eclipse/paho.mqtt.cpp/releases)
Xcode 14.2
Have you
> paho.mqtt.cpp: update to 1.4.1

- lang/gcc12/Portfile
- lang/gcc13/Portfile
- lang/gcc14/Portfile
@cjones051073 I am only adding this where you have added a fix for `arm64`.
No revbump needed.
macOS x.y
Have you
> gcc12–14: fix triple for powerpc (no revbump)

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.518
Have you
> ipsw: Update to 3.1.518

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.24
Have you
> uv: Update to 0.2.24

- devel/got/Portfile
> got: update to 0.101

- devel/pika/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> pika: update to 0.26.0

- devel/libfilezilla/Portfile
- www/FileZilla/Portfile
Update both
macOS 10.6
Xcode 3.2
Have you
> libfilezilla: update to 0.48.1; FileZilla: update to 3.67.1

- xfce/xfce4-appfinder/Portfile
Sadly the application is currently broken due to https://gitlab.xfce.org/xfce/xfce4-appfinder/-/issues/90, but the old version is broken in the same way, so might as well at least update to a current version.
macOS x.y
Have you
> xfce4-appfinder: Update to 4.18.1

- sysutils/screenfetch/Portfile
New port
macOS 14.5
Xcode 15.4
Have you
> screenfetch: new port in sysutils

- net/youtube-dl/Portfile
yt-dlp: update to 2024.07.09
Have you
> yt-dlp: update to 2024.07.09

- textproc/less/Portfile
> less: update to 661

- net/miniflux/Portfile
> miniflux: update to 2.1.4

- lang/crystal/Portfile
https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/239776/steps/install-port/logs/stdio
https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/210836/steps/install-port/logs/stdio
Have you
> crystal: set platforms to darwin >= 19

- lang/ruby33/Portfile
- lang/ruby33/files/patch-vm_insnhelper.c.diff
Closes: https://trac.macports.org/ticket/70348 (reported upstream)
Closes: https://trac.macports.org/ticket/70369
Have you
> ruby33: refactor failing patch

- devel/dagger/Portfile
Update to the latest version
Have you
> dagger: update to 0.12.0

- databases/pgtcl/Portfile
> pgtcl: update to 3.1.0

- devel/bun/Portfile
> Bun: Update to 1.1.20

- graphics/wxWidgets-3.0/Portfile
Ports built with gcc14 will not run with wx*-3.0* ports built earlier, since ABI changed.
macOS 10.6
Xcode 3.2
Have you
> wx*-3.0*: revbump for C++ ABI change

- math/mumps/Portfile
- math/mumps/files/patch-Makefile.inc.diff
- math/mumps/files/patch-shared.diff
(This also uses MPICH, so macOS-13 CI will fail.)
macOS 10.6
Xcode 3.2
Have you
> mumps: update to 5.7.2

- R/R-BayesianNetwork/Portfile
- R/R-ClusBoot/Portfile
- R/R-Epi/Portfile
- R/R-RCurl/Portfile
- R/R-crew.cluster/Portfile
- R/R-datawizard/Portfile
- R/R-disaggR/Portfile
- R/R-dosearch/Portfile
- R/R-exams/Portfile
- R/R-ipumsr/Portfile
- R/R-leidenbase/Portfile
- R/R-ltable/Portfile
- R/R-mstate/Portfile
- R/R-multilevelcoda/Portfile
- R/R-rebmix/Portfile
- R/R-report/Portfile
- R/R-rmsb/Portfile
- R/R-samc/Portfile
- R/R-surveil/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
> R: updates for packages

- aqua/smooth/Portfile
- audio/BoCA/Portfile
- audio/freac/Portfile
- audio/proxy-audio-device/Portfile
- devel/HNHUi/Portfile
- devel/KissXML/Portfile
- devel/TransformerKit/Portfile
- finance/portfolio-performance/Portfile
- security/KeePassKit/Portfile
- security/MacPass/Portfile
Remove myself as a maintainer from all my ports. 
Not tested. Port metadata change only.
Have you
> freac, MacPass, portfolio-performance +deps: Remove myself as maintainer

- sysutils/tmux/Portfile
Trac ticket: https://trac.macports.org/ticket/70377
macOS 14.5 23F79
Have you
> tmux: update tmux-devel to latest commit (5039be6)

- python/py-gmpy2/Portfile
py-gmpy2: update to 2.2.0, add py312 subport
Have you
> py-gmpy2: update to 2.2.0, add py312 subport

- devel/libvterm/Portfile
- devel/libvterm/files/patch-fix-pedantic.diff
Fix the build with Xcode gcc
macOS 10.6
Xcode 3.2
Have you
> libvterm: fix pedantic flag, fixes build with Xcode gcc

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.5.2
Have you
> ruff: Update to 0.5.2

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.25
Have you
> uv: Update to 0.2.25

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.523
Have you
> ipsw: Update to 3.1.523

- java/openjdk22-zulu/Portfile
Update to Azul Zulu OpenJDK 22.32.15.
Have you
> openjdk22-zulu: update to 22.32.15

- java/openjdk21-zulu/Portfile
Update to Azul Zulu OpenJDK 21.36.17.
Have you
> openjdk21-zulu: update to 21.36.17

- java/openjdk17-zulu/Portfile
Update to Azul Zulu OpenJDK 17.52.17.
Have you
> openjdk17-zulu: update to 17.52.17

- java/openjdk11-zulu/Portfile
Update to Azul Zulu OpenJDK 11.74.15.
Have you
> openjdk11-zulu: update to 11.74.15

- java/openjdk8-zulu/Portfile
Update to Azul Zulu OpenJDK 8.80.0.17.
Have you
> openjdk8-zulu: update to 8.80.0.17

- java/openjdk22/Portfile
Update to OpenJDK 22.0.2.
Have you
> openjdk22: update to 22.0.2

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 484.0.0.
Have you
> google-cloud-sdk: update to 484.0.0

- java/openjdk21-corretto/Portfile
Update to Amazon Corretto 21.0.4.7.1.
Have you
> openjdk21-corretto: update to 21.0.4.7.1

- java/openjdk17-corretto/Portfile
Update to Amazon Corretto 17.0.12.7.1.
Have you
> openjdk17-corretto: update to 17.0.12.7.1

- java/openjdk22-corretto/Portfile
Update to Amazon Corretto 22.0.2.9.1.
Have you
> openjdk22-corretto: update to 22.0.2.9.1

- java/openjdk8-corretto/Portfile
Update to Amazon Corretto 8.422.05.1
Have you
> openjdk8-corretto: update to 8.422.05.1

- java/openjdk11-corretto/Portfile
Update to Amazon Corretto 11.0.24.8.1.
Have you
> openjdk11-corretto: update to 11.0.24.8.1

- java/openjdk22-oracle/Portfile
Update to Oracle OpenJDK 22.0.2.
Have you
> openjdk22-oracle: update to 22.0.2

- java/jdk22/Portfile
Update Oracle JDK 22.0.2.
Have you
> jdk22: update to 22.0.2

- java/openjdk22-graalvm/Portfile
Update to GraalVM Community Edition 22.0.2.
Have you
> openjdk22-graalvm: update to 22.0.2

- java/jdk22-graalvm/Portfile
Update to Oracle GraalVM 22.0.2.
Have you
> jdk22-graalvm: update to 22.0.2

- java/jdk21-graalvm/Portfile
Update to Oracle GraalVM 21.0.4.
Have you
> jdk21-graalvm: update to 21.0.4

- java/jdk21/Portfile
Update to Oracle JDK 21.0.4.
Have you
> jdk21: update to 21.0.4

- java/openjdk21-sap/Portfile
Update to SapMachine 21.0.4.
Have you
> openjdk21-sap: update to 21.0.4

- java/openjdk22-sap/Portfile
Update to SapMachine 22.0.2.
Have you
> openjdk22-sap: update to 22.0.2

- java/openjdk17-sap/Portfile
Update to SapMachine 17.0.12.
Have you
> openjdk17-sap: update to 17.0.12

- java/openjdk11-sap/Portfile
Update to SapMachine 11.0.24.
Have you
> openjdk11-sap: update to 11.0.24

- java/jdk17-graalvm/Portfile
Update to Oracle GraalVM 17.0.12.
Have you
> jdk17-graalvm: update to 17.0.12

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.26
Have you
> uv: Update to 0.2.26

- python/py-gmpy2/Portfile
- python/py-gmpy2/files/patch-c99.diff
Upbreak the build for old Xcode compilers.
macOS 10.6
Xcode 3.2
Have you
> py-gmpy2: use c99

- devel/kokkos/Portfile
Closes: https://trac.macports.org/ticket/68371
Actually "available on macOS 10.14" is not true, perhaps the reason is a typo in the Clang 11 source code.
Have you
> kokkos-devel: do not use aligned allocation on macOS <10.13 with Clang

- devel/apr-util/Portfile
The patching is not needed anymore, the build scripts correctly get what they need out of pg_config. I can confirm that the build was able to produce a `/lib/apr-util-1/apr_dbd_pgsql-1.so` that correctly linked against postgresql16.
Have you
> apr-util: add postgresql16 variant

- security/medusa/Portfile
autoconf does not support pg_config discovery of postgresql and its paths, a requirement for installation with modern versions of postgresql.
Have you
> medusa: remove postgresql variant

- gnome/gnucash/Portfile
Those dependencies were formerly satisfied implicitly via gnucash-docs. Since we are now able to build the `-docs` variant (#24764), they need to be explicitly specified so that `port reclaim` won't clean them away.
Have you
> gnucash: update depends

- java/openjdk11-temurin/Portfile
Update to Eclipse Temurin 11.0.24.
Have you
> openjdk11-temurin: update to 11.0.24

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.3.2.
Have you
> spring-boot-cli: update to 3.3.2

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.5.3
Have you
> ruff: Update to 0.5.3

- sysutils/clifm/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> clifm: update to 1.19

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.10.2

- cross/x86_64-binutils/Portfile
Also fixes clash of doc files https://trac.macports.org/ticket/70335
x86_64-binutils:
update to 2.42
fix clash of doc files https://trac.macports.org/ticket/70335
- [] security fix
Have you
- [] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?
> x86_64-binutils: update to 2.42 and fix

- kde/kig/Portfile
- kde/kig/files/patch-isfinite.diff
CI will fail, for unrelated reasons.
macOS 10.6
Xcode 3.2
Have you
> kig: fix the build

- gis/geographiclib/Portfile
https://github.com/geographiclib/geographiclib/blob/main/NEWS
Xcode 14.2
Have you
> geographiclib: update to 2.4

- java/openjdk8-temurin/Portfile
Update to Eclipse Temurin 8u422.
Have you
> openjdk8-temurin: update to 8u422

- java/openjdk21-temurin/Portfile
Update to Eclipse Temurin 21.0.4.
Have you
> openjdk21-temurin: update to 21.0.4

- science/gmt5/Portfile
- science/gmt5/files/patch-gmt5-arm64.diff
macOS 13.6.7 22G720 arm64
Have you
> gmt5: fix build on arm64

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.23.0
Have you
> gitu: Update to 0.23.0

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.524
Have you
> ipsw: Update to 3.1.524

- devel/dagger/Portfile
Update to the latest version
Have you
> dagger: update to 0.12.1

- science/mpi-doc/Portfile
- science/mpich/Portfile
- science/mpich/files/patch-mpi-h.diff
- science/mpich/files/portselect/mpich-clang18
- science/mpich/files/portselect/mpich-clang18-fortran
- science/mpich/files/portselect/mpich-gcc14-fortran
Still working on #24812, but just to get this update in. Mayo also address issues with extra rpaths from gcc flavors.
> mpich: 4.2.2

- _resources/port1.0/group/tree_sitter-1.0.tcl
Before this change, If both `scanner.c` and `scanner.cc` exists, `scanner.c` will be compiled with `${configure.cc}` and linked with `${configure.cxx}`.
This change makes it consistently prefer C++ source files for compilation and linking.
Was there a particular reason to be inconsistent in the first place?
macOS x.y
Have you
> tree_sitter PG: prefer C++ source consistently

- java/openjdk22-temurin/Portfile
Update to Eclipse Temurin 22.0.2.
Have you
> openjdk22-temurin: update to 22.0.2

- devel/libstaroffice/Portfile
> libstaroffice: needs C++11

- science/gdcm/Portfile
Fix for old systems
macOS 10.6
Xcode 3.2
Have you
> gdcm: fix for < 10.7

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.5.4
Have you
> ruff: Update to 0.5.4

- sysutils/colima/Portfile
colima: Upgrade to 0.6.10
Have you
> colima: Upgrade to 0.6.10

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.27
Have you
> uv: Update to 0.2.27

- sysutils/clex/Portfile
Fix build on old systems.
macOS 10.6
Xcode 3.2
Have you
> clex: avoid old Xcode gcc, fixes build on old systems

- net/dnsviz/Portfile
dnsviz: update to 0.10.0
Have you
> dnsviz: update to 0.10.0

- cross/msp430-elf-gcc/Portfile
Fix bug #70411 reported on https://trac.macports.org/ticket/70411.
Have you
> msp430-elf-gcc: fix version bug

- multimedia/ffmpeg7/Portfile
- multimedia/ffmpeg7/files/patch-avutil-builtin-available.diff
- multimedia/ffmpeg7/files/patch-configure-no-error-on-missing-prototypes.diff
- multimedia/ffmpeg7/files/patch-libavcodec-audiotoolboxenc.c.diff
- multimedia/ffmpeg7/files/patch-libavcodec-librsvgdec.diff
- multimedia/ffmpeg7/files/patch-libavcodec-profvidworkflow.diff
New port.
Patches are copied from `ffmpeg6` port with no changes, but dropping unneeded ones.
@mascguy Christopher, I hope you do not mind being a primary maintainer? (If you would like not to, please let me know.)
macOS 10.6
Xcode 3.2
Have you
> ffmpeg7: new port

- multimedia/ffmpeg6/Portfile
This is also needed now.
macOS 10.6
Xcode 3.2
Have you
> ffmpeg6: a minor follow-up fix for gcc (no revbump)

- science/iverilog/Portfile
* Update to v12.0
* Move to github and autoconf as suggested for by https://steveicarus.github.io/iverilog/usage/installation.html and ftp://ftp.icarus.com times out
macOS 15.0 24A5289h arm64
Xcode 16.0 16A5202i
Have you
> iverilog: Update to v12.0

- devel/quickfix/Portfile
- devel/quickfix/files/patch-UnitTest++-Makefile.diff
The unreleased master branch drops python 2.x and java support so I've also dropped it here. The java support was only for building examples that were not shipped with the port.
I can confirm this produces a libquickfix.17.dylib that links against python 3.12 and postgresql 16. I was also able to import the quickfix Python packages that it installed but didn't exercise them beyond that.
Have you
> quickfix: update to 1.15.1

- archivers/afio/Portfile
- archivers/afio/files/patch-cflags.diff
Small fix
macOS 10.6
Xcode 3.2
Have you
> afio: fix build with Xcode gcc

- devel/tmt/Portfile
- python/py-fmf/Portfile
Add a new port for the `tmt` test management tool.
Have you
> tmt: new port (1.34.0)

- gis/imposm/Portfile
https://github.com/omniscale/imposm3/releases/tag/v0.14.0
Xcode 14.2
Have you
> imposm: update to 0.14.0

- ruby/ruby-build/Portfile
ruby-build: Upgrade to 20240722
Have you
> ruby-build: Upgrade to 20240722

- comms/tio/Portfile
- comms/tio/files/patch-socket.diff
> tio: replace post-patch with upstream fix, revbump to pick changes

- java/openjdk17/Portfile
Update to OpenJDK 17.0.12.
Have you
> openjdk17: update to 17.0.12

- java/openjdk11/Portfile
Update to OpenJDK 11.0.24.
Have you
> openjdk11: update to 11.0.24

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.525
Have you
> ipsw: Update to 3.1.525

- java/openjdk21/Portfile
Update to OpenJDK 21.0.4.
Have you
> openjdk21: update to 21.0.4

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 485.0.0.
Have you
> google-cloud-sdk: update to 485.0.0

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.28
Have you
> uv: Update to 0.2.28

- textproc/ocrmypdf/Portfile
ocrmypdf: upgrade to 16.4.2
Have you
> ocrmypdf: upgrade to 16.4.2

- devel/meson/Portfile
- python/py-meson/Portfile
- python/py-meson/files/duplicate-rpath-delete-darwin-fix.diff
Since meson release 1.5.0 we do have a lot of packages using mesonbuild who do not build anymore
Failure is during destroot install phase while excuting install_name_tool command.
Tickets :
https://trac.macports.org/ticket/70394
https://trac.macports.org/ticket/69760#comment:3
This patch is made by :
holymonson (Monson Shao)
Proposed to macports master by:
christophecvr (christophecvr)
Closes :  https://trac.macports.org/ticket/70394
On branch master
modified:   devel/meson/Portfile
modified:   python/py-meson/Portfile
new file:   python/py-meson/files/duplicate-rpath-delete-darwin-fix.diff
macOS 10.13.6
Xcode 10.1 / Command Line Tools 10.1.0
Have you
> Meson 1.5.0 patch to solve destroot build error.

- devel/skaffold/Portfile
Update to Skaffold 2.13.1.
Have you
> skaffold: update to 2.13.1

- devel/legacy-support/Portfile
Since the previous legacy-support-devel:
- Adds SLIST_REMOVE_AFTER, SLIST_HEAD_INITIALIZER Re: https://trac.macports.org/ticket/69890
- Adds fgetattrlist()
In the previous legacy-support-devel, since v1.2.4:
- Adds optional security wrapper for stpncpy(). Re: https://trac.macports.org/ticket/69878
- Moves renameat() prototype to the proper header location.
- Fixes incorrect CLOCK_UPTIME_RAW_APPROX definition
- Eliminates spurious fmemopen() in OSes that don't need it
- Adds appropriate __DARWIN_C_LEVEL conditionals, as in SDK headers. Re: https://trac.macports.org/ticket/69688
- Reworks headers for "mismatched" SDK compatibility. Re: https://trac.macports.org/ticket/69867
- Makes clockid_t an enum, matching SDK behavior.
TESTED:
Tested both normal and -devel versions on 10.4-10.5 ppc, …
> legacy-support-devel: Update to latest master.

- science/nco/Portfile
Simple update to upstream version 5.2.7
Have you
> nco: update to 5.2.7

- sysutils/felix/Portfile
- sysutils/fx/Portfile
- **felix: conflicts with sysutils/fx**
- **fx: conflicts with sysutils/felix**
Have you
Mutual installs now properly fail early when the conflicting port is active.
```console
Error: Can't install felix because conflicting ports are active: fx
```
Should we consider having a `felix+felix` variant that installs felix as `felix` instead of `fx`?
> felix & fx have mutual conflicts

- lang/idris2/Portfile
macOS 10.8.5
Xcode 5.1.1
Have you
> idris2: blacklist clang < 700 due to stdatomic

- net/netcalc/Portfile
- net/netcalc/files/0001-netcalc.h-add-missing-include-for-macOS.patch
Fix build
macOS 10.6
Xcode 3.2
Have you
> netcalc: fix build where it fails

- java/micronaut/Portfile
Update to Micronaut Starter 4.5.1.
Have you
> micronaut: update to 4.5.1

- devel/libfilezilla/Portfile
- devel/libfilezilla/files/patch-errno.diff
Fix build error. Revbump, since the port does build for a number of systems, but now a header is added.
macOS 10.15
Xcode 12.4
macOS 10.6.8 (to make sure adding header does not break gcc build)
Xcode 3.2.6
Have you
> libfilezilla: fix for 10.15 and some other systems

- python/vitables/Portfile
Note that vitables depends on tables. The subport of `py312-tables` is in #25000 
I've only tested `py312-vitables`. So I set the python version start from 3.8
Have you
> vitables: new port

- net/mtxclient/Portfile
- net/nheko/Portfile
44d5472e3a5ab532ac23ecb98d6345f8799eb5bf changed the ABI of spdlog, but did not revbump its dependents.
Have you
> mtxclient, nheko: revbump for spdlog ABI change

- python/vitables/Portfile
https://github.com/macports/macports-ports/pull/25001#issuecomment-2252917174
Have you
> fix: add setuptools as dep of vitables

- sysutils/just-fast/Portfile
https://lists.macports.org/pipermail/macports-users/2024-July/052820.html
Have you
> just-fast: fetch using macports_distfiles

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.30
Have you
> uv: Update to 0.2.30

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.57.0

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.527
Have you
> ipsw: Update to 3.1.527

- devel/cpp-argparse-dev/Portfile
* Fix: (C++11) build with gcc 4.8.1-5.4, 6.1-6.3
* Add: Argument::choice\<T>(...) functions
* Update: self_test checks
* Remove: function keyword from bash_completion output
macOS 13.6.5 22G621 x86_64
Have you
> cpp-argparse-dev: update to v1.9.3

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.23.1
Have you
> gitu: Update to 0.23.1

- sysutils/g-ls/Portfile
Update `g-ls` to its latest released version, 0.29.0
Have you
> g-ls: Update to 0.29.0

- multimedia/QMPlay2/Portfile
Some of the recent updates from upstream has broken the port due to `@rpath` being baked into libraries and app, which was not the case earlier, so our destroot fixup code did not work anymore. Perhaps this commit https://github.com/zaps166/QMPlay2/commit/7f9c183cf54d0a71893f46c986dfe3e0c13d9282 has broken it.
Fix the fix, revbump. Only newer systems affected, nothing changes for the earlier.
macOS 14.5
Xcode 15.4
macOS 10.15
Xcode 12.4
Have you
> QMPlay2: fix installation on new systems after switch to Ninja

- devel/cpr/Portfile
New port: https://docs.libcpr.org
macOS 10.6
Xcode 3.2
Have you
> cpr: new port

- devel/glib2/Portfile
- devel/glib2/files/patch-meson_build-meson_options-appinfo.diff
For applications such as nautilus who require x11 the
gio-launch-desktop bin is a requirement for some functions.
By adding the patch for build quartz(native) or x11(generic)
This add was forgotten for build of x11.
With this modified patch it is back in.
the last part of patch :
devel/glib2/files/patch-meson_build-meson_options-appinfo.diff
has been modified and in section generic build this part below is added
```
launch_desktop_sources = files('gio-launch-desktop.c')
gio_launch_desktop = executable('gio-launch-desktop', launch_desktop_sources,
include_directories : glibinc,
install : true,
install_dir : multiarch_libexecdir,
install_tag : 'bin',
c_args : gio_c_args,
link_args : noseh_link_args)
```
I also included a port bump revision from 0 to 1 . Tested by me by building without -s …
> Adapted glib2 to have the gio-launch-desktop back build on the generic (x11) version.

- multimedia/audacious-core/Portfile
- multimedia/audacious-plugins/Portfile
- multimedia/audacious-plugins/files/0001-xsf-desmume-types.h-ensure-LOCAL_BE-gets-defined-on-.patch
- multimedia/audacious-plugins/files/0002-mac-media-keys-use-correct-objc-flags.patch
Ports are broken on older systems due to a wrong C++ standard in the portfile. Fix that.
```
```
Source: https://github.com/audacious-media-player/audacious/blob/005eae06671dab4331bd0d8316072e98601bf254/meson.build#L5-L6
Switch < 10.7 to GTK3 by default, since Qt5 is broken there on all archs.
Fix build with gcc.
macOS 10.8.5
Xcode 5.1.1
Have you
> audacious: set correct compiler standards, fix build with gcc and for powerpc

- devel/love-11/Portfile
* blacklist clang < 900
Have you
> love-11: fix build on macOS <10.12

- archivers/lz4/Portfile
Fix the build with Xcode gcc
macOS 10.6
Xcode 3.2
Have you
> lz4: needs -std=c99

- ruby/ruby-build/Portfile
ruby-build: Update to 20240727
Have you
> ruby-build: Update to 20240727

- kde/kdesvn/Portfile
- kde/kdesvn/files/patch-fix-build.diff
Fixes: https://trac.macports.org/ticket/70158
CI gonna fail, but unrelated.
macOS 10.6
Xcode 3.2
Have you
> kdesvn: fix the build

- graphics/xpdf/Portfile
- graphics/xpdf/files/patch-fix-qt4.diff
1. Support on systems where Qt5 fails to install (see logs in port details) via Qt4 variant.
2. Hopefully fix for other legacy OS by amending compiler choice for atomics support (cannot test, but should work).
macOS 10.6
Xcode 3.2
Have you
P. S. As far as I can tell, Qt4-based app is functional, though has minor glitches. Specifically, pulling sliders does not work and wheel scrolling works only if the cursor is placed above sliders, but not randomly over a page; single-page view mode literally displays a single page instead of displaying document per-page; changing pages via clicking on arrows in the tab bar does not work correctly.
Notice, neither of these makes the app unusable, since other methods of scrolling and changing pages work normally.
Also zoom works, text search works, …
> xpdf: enable building with qt4 for old systems, fix compiler choice to support atomics

- devel/LucenePlusPlus/Portfile
Fix builds
macOS 10.8.5
Xcode 5.1.1
Have you
> LucenePlusPlus: fix on 10.7–10.11

- devel/libmwaw/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
> libmwaw: requires C++11

- python/py-meson/Portfile
- python/py-meson/files/patch-meson64-32bit-apple.diff
"sudo port install glib2" was failing on OS X 10.4 Tiger (32-bit) with meson build reporting "subprocess" being an undefined symbol.
The above used to happen because patch-meson64-32bit-apple.diff introduces some code which depends on "subprocess" python module but the module itself was not imported.
This change updates patch-meson64-32bit-apple.diff file to include an import statement for the "subprocess" module to resolve the described failure.
macOS 10.4.11 8S2169 i386
Have you
> py-meson: Update patch-meson64-32bit-apple.diff

- sysutils/starship/Portfile
Update to Starship 1.20.1.
Have you
> starship: update to 1.20.1

- python/py-openssl/Portfile
Use a fallback for systems without Rust. Match `py-cryptography` for the threshold.
macOS 10.6
Xcode 3.2
Have you
> py-pyopenssl: use a fallback on legacy systems without Rust

- databases/iplike/Portfile
> iplike: update to 2.3.0

- sysutils/qrcp/Portfile
qrcp: Update to 0.11.2
Have you
> qrcp: Update to 0.11.2

- lang/ruby32/Portfile
- lang/ruby32/files/patch-sources.diff
See:
https://www.ruby-lang.org/en/news/2024/07/26/ruby-3-2-5-released/
The upstream code includes both the change that broke 3.2.4 and the fix for it as patched in 3.2.4_2.
TESTED:
Built successfully on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.  Included all variants compatible with available dependencies on the respective platforms.
```
OS X 10.8.5 12F2560, x86_64, Xcode …
```
> ruby32: update to 3.2.5

- archivers/libmspack/Portfile
- archivers/libmspack/files/patch-xcode-gcc.diff
New port.
macOS 10.6
Xcode 3.2
Have you
> libmspack: new port in archivers

- emulators/wine-devel/Portfile
- emulators/wine-devel/files/1001-msync.diff
> wine-devel,wine-staging: Update to 9.14

- python/py-pyshortcuts/Portfile
Have you
Add support for Python 3.12. This is not explicitly support OR excluded by the upstream project, but it works for me.
> py-pyshortcuts: add python 3.12 support

- security/s2n-tls/Portfile
- security/s2n-tls/files/0001-Fix-build-on-macOS-10.15-and-earlier.patch
Fix the port
macOS 10.6
Xcode 3.2
Have you
> s2n-tls: fix build on Catalina and earlier

- emulators/oberon-risc/Portfile
- emulators/oberon-risc/files/patch-rename-program.diff
Emulator for Wirth & Gutknecht's Project Oberon 2013 desktop system.
Have you
> oberon-risc: New port, version 20200818

- sysutils/colima/Portfile
colima: Upgrade to 0.7.0
Have you
> colima: Upgrade to 0.7.0

- science/opencascade/Portfile
This PR revbumps `opencascade` which is a dependent of `onetbb`, which was updated in commit 1a20b58 without a revbump.
Have you
> opencascade: revbump after previous onetbb update

- gis/rsgislib/Portfile
Update `rsgislib`, `py-rsgislib` to version 5.1.7.
macOS x.y
Have you
> rsgislib, py-rsgislib: Update to 5.1.7

- devel/libnumbertext/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
> libnumbertext: fix build on older OS

- math/papilo/Portfile
Fix build with gcc, use boost 1.81
macOS 10.6
Xcode 3.2
Have you
> papilo: switch to boost 1.81, fix build with gcc

- mail/aerc/Portfile
[Changelog](https://git.sr.ht/~rjarry/aerc/refs/0.18.2)
macOS 12.6.5 x86_64
Xcode 14.2
Have you
> aerc: update to 0.18.2

- _resources/port1.0/group/legacysupport-1.1.tcl
Commit 9180c459eda overlooked the fact that there are two versions of the legacysupport PG, and only updated v1.0.  This makes the equivalent change to v1.1.
Untested
Have you
- [N/A] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message?
> legacysupport-1.1 PG: Update default newest OS to Darwin 18

- security/ipsw/Portfile
Update `ipsw` to its latest released, 3.1.531
Have you
> ipsw: Update to 3.1.531

- net/tlrc/Portfile
Update `tlrc` to its latest released version, 1.9.3
Have you
> tlrc: Update to 1.9.3

- science/libmed/Portfile
Revbump needed, because it was building before, despite undefined `strndup`.
macOS 10.6
Xcode 3.2
Have you
> libmed: use legacysupport for strndup

- science/spglib/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
> spglib: requires now C11 and C++11

- sysutils/resticprofile/Portfile
add resticprofile, a configuration profiles manager and scheduler for restic 
Have you
> resticprofile: new port

- math/eigen3/Portfile
Update -devel subport.
macOS 14.5
Xcode 15.4
Have you
> eigen3-devel: update to 20240730

- java/openjdk21-microsoft/Portfile
Update to Microsoft OpenJDK 21.0.4.
Have you
> openjdk21-microsoft: update to 21.0.4

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 486.0.0.
Have you
> google-cloud-sdk: update to 486.0.0

- java/openjdk17-microsoft/Portfile
Update to Microsoft OpenJDK 17.0.12.
Have you
> openjdk17-microsoft: update to 17.0.12

- java/openjdk11-microsoft/Portfile
Update to Microsoft OpenJDK 11.0.24.
Have you
> openjdk11-microsoft: update to 11.0.24

- python/py-pulp/Portfile
Update`py-pulp` to 2.9.0; migrate to PyPi.
macOS x.y
Have you
> py-pulp: update to 2.9.0; migrate to PyPi

- science/OpenCSG/Portfile
Use Qt4 for old systems
macOS 10.6
Xcode 3.2
Have you
> OpenCSG: unbreak for older systems

- python/py-ansible-core/Portfile
- python/py-ansible/Portfile
Update **py-ansible** _and_ **py-ansible-core** to latest version.
```
>ansible
ansible [core 2.17.2]
config file = None
configured module search path = ['/Users/emre/.ansible/plugins/modules', '/opt/local/share/ansible/plugins/modules']
ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ansible
ansible collection location = /Users/emre/.ansible/collections:/opt/local/share/ansible/collections
executable location = /opt/local/bin/ansible
python version = 3.12.4 (main, Jun  8 2024, 04:51:36) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/opt/local/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12)
jinja version = 3.1.4
libyaml = True
```
> ansible: update to 2.17.2

- net/youtube-dl/Portfile
yt-dlp: update to 2024.08.01
Have you
> yt-dlp: update to 2024.08.01

- audio/FAudio/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> FAudio: update to 24.08

- devel/shellcheck/Portfile
Add man.1 for shellcheck
macOS 12.7.2 21G1974 x86_64
Have you
> shellcheck: add manpage

- lang/fortran-stdlib/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> fortran-stdlib-devel: update to 2024.07.09

- gnome/libsoup-devel/Portfile
- gnome/libsoup/Portfile
Closes: https://trac.macports.org/ticket/70479
There is no problem with `vapigen` anymore, drop a special case. Fixes build of `gnome-calculator`.
macOS 10.6
Xcode 3.2
Have you
> libsoup, -devel: drop now unneeded special case for ppc

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.5.6
Have you
> ruff: Update to 0.5.6

- gnome/gtk-internet-radio-locator/Portfile
GTK Internet Radio Locator 5.4.8 (macOS 14.5 / MacPorts 2.9.3) from https://gtk.audio/src/gtk-internet-radio-locator-5.4.8.tar.xz
Have you
> GTK Internet Radio Locator 5.4.8 (macOS 14.5 / MacPorts 2.9.3)

- textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.4.3
Have you
> ocrmypdf: update to 16.4.3

- science/hdfeos5/Portfile
Closes: https://trac.macports.org/ticket/70029
Fix this finally
macOS 10.6
Xcode 3.2
Have you
> hdfeos5: fix build when hdf5 is installed with +mpich

- databases/libzdb-mysql55/Portfile
I can confirm this builds and links against PostgreSQL 16 but can't test its functionality.
Have you
> libzdb-mysql55: add postgresql16 variant

- x11/fvwm2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> fvwm2: update to 2.7.0

- devel/pika/Portfile
Update, drop now unneeded MPICH-related blacklist.
macOS 10.6
Xcode 3.2
Have you
> pika: update to 0.26.1

- gis/JOSM/Portfile
[Changelog](https://josm.openstreetmap.de/wiki/Changelog#a2024-08-01:Stablerelease1916024.07)
Xcode 14.2
Have you
> josm: update to 19160

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.532
Have you
> ipsw: Update to 3.1.532

- graphics/osxphotos/Portfile
Update to osxphotos 0.68.3.
Have you
> osxphotos: update to 0.68.3

- net/zmap/Portfile
Fix build on older systems.
macOS 10.6
Xcode 3.2
Have you
> zmap: set required C11 standard

- databases/pgbouncer/Portfile
Fixes: https://trac.macports.org/ticket/70487
Fix
macOS 10.6
Xcode 3.2
Have you
> pgbouncer: fix for < 10.7

- net/torsocks/Portfile
- net/torsocks/files/gethostbyaddr_r.patch
- net/torsocks/files/implicit.patch
- net/torsocks/files/version.patch
Closes: https://trac.macports.org/ticket/61631
Have you
> torsocks: Update to 2.4.0

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.24.0
Have you
> gitu: Update to 0.24.0

- devel/legacy-support/Portfile
- Adds optional security wrapper for stpncpy(). Re: https://trac.macports.org/ticket/69878
- Moves renameat() prototype to the proper header location.
- Fixes incorrect CLOCK_UPTIME_RAW_APPROX definition.
- Eliminates spurious fmemopen() in OSes that don't need it.
- Adds appropriate __DARWIN_C_LEVEL conditionals, as in SDK headers. Re: https://trac.macports.org/ticket/69688
- Reworks headers for "mismatched" SDK compatibility. Re: https://trac.macports.org/ticket/69867
- Makes clockid_t an enum, matching SDK behavior.
- Adds SLIST_REMOVE_AFTER, SLIST_HEAD_INITIALIZER. Re: https://trac.macports.org/ticket/69890
- Adds fgetattrlist(). Closes: https://trac.macports.org/ticket/70350
Portfile changes:
- Removes obsolete portion of Tiger-specific additions.
- Moves atexit removal from …
> legacy-support: Update to v1.3.0.

- lang/clojure/Portfile
> clojure: update to  1.11.4.1474

- net/gallery-dl/Portfile
gallery-dl: update to 1.27.2
Have you
> gallery-dl: update to 1.27.2

- editors/neovim/Portfile
- editors/neovim/files/embed-parsers-build.diff
- neovim: update to 0.10.1
- neovim-devel: update to 20240803
Have you
> neovim, -devel: update to 0.10.1 and 20240805

- sysutils/edid-decode/Portfile
Update to version 20240731
macOS 15.0 24A5298h arm64
Have you
> edid-decode: update to version 20240731

- textproc/json2tsv/Portfile
[Changelog](https://git.codemadness.org/json2tsv/log.html)
macOS 12.6.6 x86_64
Xcode 14.2
Have you
> json2tsv: update to 1.2

- net/catgirl/Portfile
- net/catgirl/files/patch-explicit-bzero.diff
* fix build on macOS <10.9
Closes: https://trac.macports.org/ticket/67214
Have you
> catgirl: update to 2.2a

- lang/kotlin/Portfile
Update to Kotlin 2.0.10.
Have you
> kotlin: update to 2.0.10

- graphics/osxphotos/Portfile
Update to osxphotos 0.68.4.
Have you
> osxphotos: update to 0.68.4

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 487.0.0.
Have you
> google-cloud-sdk: update to 487.0.0

- lang/vala-devel/Portfile
- lang/vala/Portfile
```
:) cllang@gallumbits:~$ sudo port -vy rev-upgrade
--->  Scanning binaries for linking errors
Could not open /opt/local/lib/libcdt.5.dylib: Error opening or reading file (referenced from /opt/local/bin/valadoc-0.56)
Could not open /opt/local/lib/libcgraph.6.dylib: Error opening or reading file (referenced from /opt/local/bin/valadoc-0.56)
Could not open /opt/local/lib/libgvc.6.dylib: Error opening or reading file (referenced from /opt/local/bin/valadoc-0.56)
--->  Found 6 broken files, matching files to ports
--->  Found 1 broken port, determining rebuild order
You can always run 'port rev-upgrade' again to fix errors.
The following ports will be rebuilt: vala @0.56.17+valadoc
```
This has probably been broken for a while, but
7352fd2fee713ea5d9b89024a9df92af326d3640 made valadoc a …
> vala{,-devel}: add missing lib dep for graphviz

- sysutils/checkssl/Portfile
Update to checkssl 0.6.0.
Have you
> checkssl: update to 0.6.0

- security/ipsw/Portfile
Update `ipsw` to its latest released version, [3.1.533](https://github.com/blacktop/ipsw/releases/tag/v3.1.533)
Have you
> ipsw: Update to 3.1.533

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.534
Have you
> ipsw: Update to 3.1.534

- devel/minify/Portfile
Added port "minify"
macOS 12.7.5 21H1222 arm64
Have you
> minify: new port

- sysutils/timoni/Portfile
Updated to the latest version.
Have you
> timoni: update to 0.22

- devel/got/Portfile
- devel/got/files/patch-use-volatile-memset.diff
* set legacysupport version
Closes: https://trac.macports.org/ticket/66087
Have you
> got: fix build on macOS <10.9

- sysutils/pv/Portfile
Update `pv` to its latest released version, 1.8.12
Have you
> pv: Update to 1.8.12

- devel/gFTL-shared/Portfile
- devel/gFTL-shared/files/patch-fix-install.diff
Update
macOS 10.6
Xcode 3.2
Have you
> gFTL-shared: update to 1.9.0

- devel/md4c/Portfile
It uses gcc builtins which Xcode gcc does not understand. Blacklist it.
macOS 10.6
Xcode 3.2
Have you
> md4c: fix build on old systems

- science/gmtsar/Portfile
Revbump needed here, since the build did not fail despite missing `getline` and a linking error, unfortunately.
macOS 10.6
Xcode 3.2
Have you
> gmtsar: use legacysupport for getline

- graphics/vtk/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> vtk: update to 9.3.1

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.34. This update only works with Rust 1.80+
Have you
> uv: Update to 0.2.34

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.58.0

- net/magic-wormhole/Portfile
magic-wormhole: update to 0.15.0
fixes: https://trac.macports.org/ticket/69937
Have you
> magic-wormhole: update to 0.15.0

- sysutils/colima/Portfile
colima: Upgrade to 0.7.1
Have you
same change?
> colima: Upgrade to 0.7.1

- devel/fbzmq/Portfile
New port, `folly` group
macOS 10.6
Xcode 3.2
Have you
> fbzmq: new port in devel

- gis/GPXSee/Portfile
> GPXSee: update to 13.23

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.35
Have you
> uv: Update to 0.2.35

- java/openjdk21-openj9/Portfile
Update to IBM Semeru 21.0.4.
Have you
> openjdk21-openj9: update to 21.0.4

- lang/ruby30/Portfile
- lang/ruby32/Portfile
- lang/ruby33/Portfile
The Portfile has been carrying the -std=c99 setting (for OS <10.7) forward through many versions, but that has been inappropriate since ruby30, when the compiler selection was switched by the thread-local storage requirement.  Since the compiler now defaults to C11, specifying C99 is a step backward.  This removes that inappropriate setting.
Since this is not known not to impact the installed content, it includes a revbump.
Also, since the latest legacy-support includes fgetattrlist(), builds of ruby32-33 for <10.6 no longer include the private fallback, making the installed content different on those platforms.  The revbump covers that as well.
Also removes unnecessary "platforms darwin", making lint happy.
TESTED:
Minimally tested on unaffected 10.7+.
Built successfully with no variants …
> ruby30,32,33: Remove inappropriate -std=c99.

- lang/ruby31/Portfile
The Portfile has been carrying the -std=c99 setting (for OS <10.7) forward through many versions, but that has been inappropriate since ruby30, when the compiler selection was switched by the thread-local storage requirement.  Since the compiler now defaults to C11, specifying C99 is a step backward.  This removes that inappropriate setting.
Since this is not known not to impact the installed content, it includes a revbump.
Also, since the latest legacy-support includes fgetattrlist(), builds for <10.6 no longer include the private fallback, making the installed content different on those platforms.  The revbump covers that as well.
Also removes unnecessary "platforms darwin", making lint happy.
TESTED:
Minimally tested on unaffected 10.7+.
Built with all variants except jemalloc on 10.5 …
> ruby31: Remove inappropriate -std=c99.

- net/catgirl/Portfile
Allow building with gcc
macOS 10.6
Xcode 3.2
Have you
> catgirl: fix build with gcc

- java/openjdk22-openj9/Portfile
Update to IBM Semeru 22.0.2.
Have you
> openjdk22-openj9-: update to 22.0.2

- java/openjdk11-openj9/Portfile
Update to IBM Semeru 11.0.24.
Have you
> openjdk11-openj9: update to 11.0.24

- java/openjdk17-openj9/Portfile
Update to IBM Semeru 17.0.12.
Have you
> openjdk17-openj9: update to 17.0.12

- java/openjdk8-openj9/Portfile
Update to IBM Semeru 8u422.
Have you
> openjdk8-openj9: update to 8u422

- math/mumps/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> mumps: update to 5.7.3

- gis/gdal/Portfile
0659a06 left gdal's variants in a broken state. Thus, this PR:
- corrects the subport installation messages
- moves variant error messages to pre-fetch blocks
- refers to the new sub-ports correctly
Have you
> gdal: cleanup after 0659a06

- shells/bash/Portfile
Just very minor bugfixes.
Have you
> bash: update to 5.2.32

- devel/cegui/Portfile
@ryandesign Still need this, it fails to build with gcc-4.2.
macOS 10.6
Xcode 3.2
Have you
> cegui: use C++11 to fix build on legacy systems

- net/darkstat/Portfile
Update and fix
macOS 10.6
Xcode 3.2
Have you
> darkstat: update to 3.0.721, fix build on older OS

- devel/bcunit/Portfile
- devel/bcunit/files/patch-drop-unsupported-flags.diff
Fix
macOS 10.6
Xcode 3.2
Have you
> bcunit: fix build with Xcode gcc

- sysutils/mise/Portfile
mise: Upgrade to 2024.8.6
Have you
same change?
> mise: Upgrade to 2024.8.6

- lang/ocaml-camlp4/Portfile
(Why we forgot this?)
macOS 10.6
Xcode 3.2
Have you
> ocaml-camlp4: update to 4.14+1

- editors/neovim/Portfile
- editors/neovim/files/patch-lua51-includes.diff
Fixes neovim builds. _See_ [#70420](https://trac.macports.org/ticket/70420#comment:9) for full description.
Have you
> neovim: include lua51 headers to build properly

- net/gallery-dl/Portfile
gallery-dl: update to 1.27.3
Have you
> gallery-dl: update to 1.27.3

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.535
Have you
> ipsw: Update to 3.1.535

- sysutils/colima/Portfile
colima: Upgrade to 0.7.3
Have you
> colima: Upgrade to 0.7.3

- lang/ruby32/Portfile
- lang/ruby32/files/patch-sources.diff
This backports the upstream commit 055613fd86, which fixes a pointer-type mismatch in 32-bit builds, which gcc14 treats as an error.
Although the intent is only to fix a build failure, the fix replaces one function call with another, and hence requires a revbump.
TESTED:
Built successfully on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.  Included all variants compatible with available dependencies on the respective platforms (except ppc builds, which were limited to default variants to save time).
```
Mac OS X 10.6.8 10K549, …
```
> ruby32: Fix build with gcc14.

- devel/libqb/Portfile
Closes: https://trac.macports.org/ticket/70535
> libqb: Use release tarball

- games/packwiz/Portfile
Packwiz is a command line tool for creating Minecraft modpacks. `go.offline_build no` is used because it depends on a package that is in a sub-folder of a GitHub repository, which the portgroup has trouble downloading by itself.
Have you
> Packwiz: New Port

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 488.0.0.
Have you
> google-cloud-sdk: update to 488.0.0

- gnome/spice-gtk/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> spice-gtk: fix build for old systems

- python/py-meson/Portfile
- python/py-meson/files/patch-unbreak-linking.diff
See:
https://trac.macports.org/ticket/70386
https://trac.macports.org/ticket/70496
This should be fixed ASAP
macOS 10.6
Xcode 3.2
Have you
> py-meson: unbreak linking on < 10.7

- devel/qbs/Portfile
>  qbs: Update to 2.4.1

- devel/libfmt11/Portfile
New version of libfmt
macOS 10.6
Xcode 3.2
Have you
> libfmt11: new port

- net/iperf3/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
> iperf3: fix for < 10.7

- sysutils/findutils/Portfile
I see a series of tickets about gnulib-related failures on old versions of MacOS X. I imagine this release has the latest gnulib and any fixes, however, I don't have any of these old machines to see if findutils is building better on them. So I will not close any of those tickets in this PR.
Have you
> findutils: update to 4.10.0

- math/conauto/Portfile
Original site is gone, as so the tarball.
macOS 10.6
Xcode 3.2
Have you
> conauto: non-functional: use macports_distfiles

- devel/oski/Portfile
Fixes: https://trac.macports.org/ticket/70543
Avoid Xcode gcc which fails to link this.
macOS 10.6
Xcode 3.2
Have you
> oski: avoid archaic Xcode gcc

- databases/postgresql16-server/Portfile
- databases/postgresql16/Portfile
> postgresql16: update to 16.4

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.36
Have you
> uv: Update to 0.2.36

- sysutils/edid-decode/Portfile
Update to version 20240811
* translate cp437 and ISO 8859-1 to UTF-8
* document new --utf8 option
* enable UTF-8 for the emscripten version
* document the two supported InfoFrame variants
macOS 15.0 24A5309e arm64
Have you
> edid-decode: update to version 20240811

- www/drupal7/Portfile
I did not attempt to build this although I suspect there are no users for the port. If there is a user they'll have to migrate their data between postgresql databases via pg_dump/pg_restore. In general the Portfile variants are not a great way to handle database dependencies for this package, I would suggest users instead just install their database of choice explicitly and separately.
Have you
> drupal7: use postgresql16 dependency

- net/jitsi-meet-electron/Portfile
Update jitsi-meet-electron. 
This port is marked as openmaintainer and has been outdated for quite some time.
I've checked the changelog, there haven't been any mayor changes and it still builds and works.
Have you
> jitsi-meet-electron: update to 2024.6.0

- gnome/gtk3-devel/Portfile
- gnome/gtk3/Portfile
Partially reverts 4fb8088b2838539db152705c8ec612d71aa4d237.
According to [1], this only is a problem when epoxy was configured with mesa present, but until somebody fixes epoxy to never add `Requires.private: gl` to its pkg-config file when built with +quartz, we must assume user systems out there have it and value build stability over minimal dependencies.
[1]: https://github.com/macports/macports-ports/commit/4fb8088b2838539db152705c8ec612d71aa4d237#commitcomment-142476278
See: https://lists.macports.org/pipermail/macports-users/2024-August/052836.html
Closes: https://trac.macports.org/ticket/70184
Have you
> gtk3: Add missing build dependency on mesa

- graphics/qrscan/Portfile
- graphics/qrscan/files/patch-Makefile.diff
Simple fix
macOS 10.6
Xcode 3.2
Have you
> qrscan: fix build with Xcode gcc

- graphics/osxphotos/Portfile
Update to osxphotos 0.68.5.
Have you
> osxphotos: update to 0.68.5

- irc/pounce/Portfile
- irc/pounce/files/patch-explicit-bzero.diff
* respect MacPorts flags via enabling use_configure
Have you
> pounce: fix build on macOS <10.9

- multimedia/libheif/Portfile
x265 has a GPL license which makes redistribution difficult.
Have you
> libheif: build with kvazaar instead of x265

- aqua/qt6/Portfile
- aqua/qt6/files/patch-qtbase-fix-cmake-3.28.diff
Closes: https://trac.macports.org/ticket/68713
This fix landed upstream only in Qt 6.7, so I believe it's worth having it until Qt in MacPorts is updated to 6.7.
Have you
> qt6-qtbase: Fix build with CMake 3.28

- devel/uv/Portfile
Update `uv` to its latest released version, 0.2.37
Have you
> uv: Update to 0.2.37

- devel/ruff/Portfile
Update `ruff` to its latest release, 0.6.1. [The release notes mark this as a hotfix.](https://github.com/astral-sh/ruff/releases/tag/0.6.1)
Have you
> ruff: Update to 0.6.1

- devel/zmqpp/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> zmqpp: needs C++11

- devel/tree-sitter-go/Portfile
Same fix as with a few other subports.
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-go: fix build on older systems after update

- devel/pika/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> pika: update to 0.27.0

- databases/libpqxx/Portfile
The test suite passes but the lints fail. I assume that upstream gets the lints to pass before making a release anyway. I opened https://github.com/jtv/libpqxx/issues/885 to track the lint issue upstream.
Have you
> libpqxx: update to 7.9.2

- sysutils/xdg-utils/Portfile
- sysutils/xdg-utils/files/patch-xdg-realpath.diff
Draft, because
1. `xdg-realpath` does not seem to be installed/working for some reason (`xdg-realpath: command not found`)
2. `port livecheck xdg-utils` fails (is this expected?)
- `Error: cannot check if xdg-utils was updated (regex didn't match)`
Have you
> xdg-utils: Update to 1.2.1

- java/maven3/Portfile
Update to Apache Maven 3.9.9.
Have you
> maven3: update to 3.9.9

- java/gng/Portfile
> gng: update to 1.0.5

- sysutils/clifm/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> clifm: update to 1.20

- sysutils/mise/Portfile
mise: Upgrade to 2024.8.8
Have you
same change?
> mise: Upgrade to 2024.8.8

- aqua/mkconsole/Portfile
- aqua/mkconsole/files/2ed541237808b584962cb0ae7485ee3d31a1ca45.patch
Fix for older systems
macOS 10.6
Xcode 3.2
Have you
> mkconsole: backport fix from upstream for older systems

- sysutils/nnn/Portfile
- sysutils/nnn/files/0001-Drop-a-defunct-fallback.patch
Closes: https://trac.macports.org/ticket/70577
Fix this finally
macOS 10.6
Xcode 3.2
Have you
> nnn: fix for older systems

- devel/got/Portfile
https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/283723/steps/install-port/logs/stdio
Have you
> got: bump legacysupport to 16 for open_memstream

- sysutils/lima/Portfile
- sysutils/lima/files/patch-Makefile.diff
lima: Upgrade to 0.23.1
Have you
same change?
> lima: Upgrade to 0.23.1

- sysutils/mise/Portfile
mise: Upgrade to 2024.8.9
Have you
> mise: Upgrade to 2024.8.9

- sysutils/mise/Portfile
mise: Upgrade to 2024.8.11
Have you
> mise: Upgrade to 2024.8.11

- emulators/qemu/Portfile
The libfdt included in qemu conflicts with the one in dtc. Configure qemu to depend on dtc and use that version of libfdt.
Have you
> qemu: Use libfdt from dtc

- security/infisical/Portfile
Support the [Infisical](https://github.com/Infisical/infisical/) secret manager.
Have you
> infisical: new submission

- archivers/7zip/Portfile
* simplify replacement of linker flags
Have you
> 7zip: update to 24.08

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 489.0.0.
Have you
> google-cloud-sdk: update to 489.0.0

- emulators/sheepshaver/Portfile
- emulators/sheepshaver/files/xcode-sdl2.diff
I changed the repo from cebix's repo to the more frequently updated fork he recommends. I also changed the build system over to using Xcode, since in my testing the linux-based autogen build's Preferences window did not work correctly.
SheepShaver should now build correctly on newer OSes including ARM platforms.
macOS 12.7.5 21H1222 arm64
Have you
> sheepshaver: switched repo, support newer OSes and arm

- aqua/qt4-mac-postgresql16-plugin/Portfile
This also adds qt4-mac-postgresql15-plugin and removes ports for PostgreSQL 8.2 through 9.2.
I confirmed the new package is building a libqsqlpsql.dylib that links against the right PostgreSQL and libqt but am unable to test its functionality. This also blows away the old ports without notice but presumably they have no users given how old and unsupported the versions are.
Have you
> qt4-mac-postgresql16-plugin: new port

- sysutils/quotatool/Portfile
- sysutils/quotatool/files/install.patch
quotatool: Update to 1.6.5
Fixes implicit function declaration build failure with Xcode 12 and later.
Also adds maintainer GitHub handle.
Also switches to GitHub hosting.
Have you
> quotatool: Update to 1.6.5

- sysutils/mise/Portfile
mise: Upgrade to 2024.8.12
Have you
> mise: Upgrade to 2024.8.12

- devel/uv/Portfile
Update `uv` to its latest released version, 0.3.0
Have you
> uv: Update to 0.3.0

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.536
Have you
> ipsw: Update to 3.1.536

- editors/tea/Portfile
- editors/tea/files/7126a9aef1f8313a2e97b7e3b1b8280f8f088935.patch
Update
macOS 10.6
Xcode 3.2
Have you
> tea: update to 63.1.0

- audio/libsdl2_mixer/Portfile
- audio/libsdl2_mixer/files/a2c6c892aae6b28bbb03adc1bb5ffe32f1eea17e.patch
- devel/libsdl2_image/Portfile
- devel/libsdl2_image/files/30b30dfa804602423db7450483b973d62d144bb3.patch
- devel/libsdl2_net/Portfile
- devel/libsdl2_ttf/Portfile
@jmroot @reneeotten These are the minimal patches to fix the build. Upstream got every instance of this error fixed, but we skip some components, so I only include what is required.
Refs:
https://github.com/libsdl-org/SDL_image/commit/30b30dfa804602423db7450483b973d62d144bb3
https://github.com/libsdl-org/SDL_image/commit/5c5051cb3e594cf301e76f6e6b55df1c6b54c04b
https://github.com/libsdl-org/SDL_mixer/commit/a2c6c892aae6b28bbb03adc1bb5ffe32f1eea17e
https://github.com/libsdl-org/SDL_mixer/commit/518311a7e473c9fc3f1314b486db1c899823020f
macOS 10.6
Xcode 3.2
Have you
> libsdl2_*: backport fixes from upstream, allow build with gcc

- textproc/po4a/Portfile
> po4a: update to 0.73

- devel/skaffold/Portfile
Update to Skaffold 2.13.2.
Have you
> skaffold: update to 2.13.2

- devel/leiningen/Portfile
* update to version 2.11.2
Xcode 15.4 Build version 15F31d / Command Line Tools 15.3.0.0.1.1708646388
Have you
> leiningen: update to version 2.11.2

- devel/libepubgen/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> libepubgen: requires C++11

- lang/kotlin/Portfile
Update to Kotlin 2.0.20.
Have you
> kotlin: update to 2.0.20

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.3.3.
Have you
> spring-boot-cli: update to 3.3.3

- devel/toml11/Portfile
CMakeLists ask for that.
macOS 10.6
Xcode 3.2
Have you
> toml11: set C++11 standard

- archivers/zlib-ng/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
> zlib-ng: needs C11 and C++11

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.6.2
Have you
> ruff: Update to 0.6.2

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.537
Have you
> ipsw: Update to 3.1.537

- devel/uv/Portfile
Update `uv` to its latest released version, 0.3.1
Have you
> uv: Update to 0.3.1

- net/openssh/Portfile
Also adds message regarding test requirements.
Closes: https://trac.macports.org/ticket/70319
TESTED:
With +legacy_dsa, accepts "+ssh-rsa,ssh-dss" config options. Built successfully on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.  Included all variants compatible with available dependencies on the respective platforms, except that testing of +universal was limited to avoid the need to install +universal versions of many dependencies.
```
Mac OS X 10.6.8 10K549, x86_64, Xcode …
```
> openssh: Add legacy_dsa variant.

- lang/execline/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
> execline: use legacysupport for clock_gettime

- python/py-dmgbuild/Portfile
- python/py-dmgbuild/files/patch-pyproject.patch
- python/py-ds-store/Portfile
- python/py-mac-alias/Portfile
macOS 13.6.9
Xcode 15.2.0
Have you
I have not included the dmgbuild tests as they do not work, but this is because the source archive appears to be missing files necessary for the tests to work properly.
> Submission: py-dmgbuild (and py-ds-store, which the former depends on)

- science/cdo/Portfile
Simple update to upstream version 2.4.3.
This is a second attempt after an earlier PR (#25431) went awry.
Have you
> cdo: update to 2.4.3

- audio/whisper/Portfile
- audio/whisper/files/add-metal-path.diff
- audio/whisper/files/ggml-hard-coded.diff
- audio/whisper/files/whisper-add-models.diff
Adds the whisper.cpp project to MacPorts (a port of OpenAI's whisper in C/C++). Note: this is my first contribution to MacPorts, so forgive any mistakes or bad practices. I named the project "whisper," but maybe it needs to be whisper-cpp or something like that, though whisper is easier as a name and executable. Its variants also allow users to download the models that are necessary for using the program and store them in /opt/local/share/whisper.
Replaces #25270 
Have you
> whisper: submission of port (whisper.cpp)

- devel/uv/Portfile
Update `uv` to its latest released version, 0.3.2
Have you
> uv: Update to 0.3.2

- devel/bun/Portfile
Upgrade Bun to 1.1.25
Have you
> Bun: Upgrade to 1.1.25

- java/micronaut/Portfile
Update to Micronaut Starter 4.6.0.
Have you
> micronaut: update to 4.6.0

- java/mvnd/Portfile
Update to Maven Daemon 1.0.2.
Have you
> mvnd: update to 1.0.2

- devel/bun/Portfile
> Bun: Update to 1.1.26

- graphics/unpaper/Portfile
Xcode gcc does not build this.
macOS 10.6
Xcode 3.2
Have you
> unpaper: fix build on old systems

- textproc/texinfo/Portfile
The port is supposed not to install libs, however it does, which brings in undeclared dependency on `libunistring`.
Avoid opportunistic building of libs and opportunistic linking.
macOS 10.6
Xcode 3.2
Have you
> texinfo: do not build extra libs opportunistically

- lisp/cl-ppcre/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> cl-ppcre*: update to 2.1.2

- graphics/darktable-devel/Portfile
Update `darktable-devel` port to latest version released by upstream (4.8.1).
Also adapted livecheck regex to new convention used in upstream releases page.
Have you
> darktable-devel: update to 4.8.1

- mail/urlscan/Portfile
Update urlscan to 1.0.3
– Add new build dependencies: hatchling and hatch-vcs
– Use Python 3.12 by default
– Add compatible Python versions
– Remove unnecessary 
**This should not be merged without review from project's maintainer (@ryanakca), since the package is being updated from a prerelease version to a stable version.**
The urlscan package is quite outdated. Here, I've updated it to the newest version, which includes the addition of two new build dependencies. I've also set the compatible Python versions and defaulted to 3.12 (previously 3.9). This also removes the unnecessary `darwin` setting.
Have you
> urlscan: update to 1.0.3

- gnome/zenity/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
> zenity: fix build for old systems and powerpc

- java/mvnd/Portfile
Restore master_sites URL.
Have you
> mvnd: restore master_sites URL

- sysutils/mc/Portfile
Update `mc` port to latest upstream version.
Have you
> mc: update to 4.8.32

- emulators/wine-devel/Portfile
- emulators/wine-devel/files/0001-winemac.drv-no-flicker-patch.diff
> wine-devel,wine-staging: update to 9.16

- devel/spdlog0/Portfile
- devel/spdlog0/files/patch-pthread.diff
Backport a patch
macOS 10.6
Xcode 3.2
Have you
> spdlog0: backport upstream fix for old systems

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.60.0

- lua/stylua/Portfile
By default, stylua is built with support for Lua 5.1 only, but can be built to support Lua 5.1 through Lua 5.4 and Luau. This only requires adding `luau` and `lua54` to the default features, `editorconfig` and `wasm-bindgen`. `lua54` implies `lua52` and `lua53`.
I was able to format a Lua 5.4 file that was not previously formattable with the existing feature set.
Have you
> stylua: Enable more Lua version formatting

- x11/xarchiver/Portfile
- x11/xarchiver/files/0001-window.c-define-st_mtim-on-macOS.patch
- x11/xarchiver/files/0002-exe.c-define-le16toh-on-macOS.patch
Update
macOS 10.6
Xcode 3.2
Have you
> xarchiver: update to 0.5.4.23

- devel/uv/Portfile
Update `uv` to its latest released version, 0.3.3
Have you
> uv: Update to 0.3.3

- devel/kokkos/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> kokkos-devel: update to 2024.08.23

- devel/libhv/Portfile
[Changelog](https://github.com/ithewei/libhv/releases/tag/v1.3.3)
Xcode 14.2
Have you
> libhv: update to 1.3.3

- security/totp-cli/Portfile
totp-cli:  Update dependencies
* Bump revision number
* Update go dependencies to latest versions
Have you
> totp-cli:  Update dependencies

- python/pipx/Portfile
pipx: update to 1.7.1
Have you
> pipx: update to 1.7.1

- gnome/gtk-radio/Portfile
GTK Radio 549.0 -- upstream release from http://www.gtkradio.org/src/gtk-radio-549.0.tar.xz
Have you
> gtk-radio: update to 549.0

- gis/gdal/Portfile
- python/py-gdal/Portfile
Update `gdal` and `py-gdal` to version 3.9.2.
macOS x.y
Have you
> gdal, py-gdal: Update to version 3.9.2

- perl/p5-ifeffit/Portfile
Avoid Xcode gcc, it cannot link this.
macOS 10.6
Xcode 3.2
Have you
> p5-ifeffit: fix build on old systems

- sysutils/mise/Portfile
mise: Upgrade to 2024.8.13
Have you
> mise: Upgrade to 2024.8.13

- devel/uv/Portfile
Update `uv` to its latest released version, 0.3.5
Have you
> uv: Update to 0.3.5

- sysutils/fastfetch/Portfile
- sysutils/fastfetch/files/0001-Support-hostinfo-for-PowerPC-Macs.patch
- sysutils/fastfetch/files/0002-version.c-add-a-missing-macro-for-powerpc.patch
- sysutils/fastfetch/files/0003-Support-PowerPC-CPU-detection.patch
- sysutils/fastfetch/files/0004-gpu_apple.m-unbreak-for-10.11.patch
- sysutils/fastfetch/files/0005-memory_apple-fix-for-32-bit.patch
- sysutils/fastfetch/files/0006-opengl_apple.c-fix-for-10.7.patch
- sysutils/fastfetch/files/0007-sound_apple.c-fix-for-10.8.patch
- sysutils/fastfetch/files/0008-gpu_apple.c-fix-for-old-systems.patch
- sysutils/fastfetch/files/0009-camera_apple.m-unbreak-for-10.7.patch
- sysutils/fastfetch/files/0010-brightness_apple.c-add-a-missing-include.patch
- sysutils/fastfetch/files/0011-os_apple.m-etc.-fix-syntax-for-plists.patch
- sysutils/fastfetch/files/0012-osascript.m-fix-syntax.patch
- sysutils/fastfetch/files/0013-disk_bsd-no-support-for-creation-time.patch
- sysutils/fastfetch/files/0014-yyjson-PowerPC-macros.patch
- sysutils/fastfetch/files/0015-monitor_apple.m-no-HDR-before-10.11.patch
- sysutils/fastfetch/files/0016-Fix-autorelease-pools.patch
- sysutils/fastfetch/files/0017-Fix-compatibility-with-10.4.patch
- sysutils/fastfetch/files/0018-Revert-some-breakages.patch
- sysutils/fastfetch/files/0019-CMakeLists-adjust-for-legacy-macOS.patch
- sysutils/fastfetch/files/0020-swap_fat_arch_64-does-not-exist-in-10.6.patch
- sysutils/fastfetch/files/0021-Tiger-specific-adjustments-to-CMakeLists.patch
- sysutils/fastfetch/files/1001-CMakeLists-disable-bluetooth-modules.patch
Closes: https://trac.macports.org/ticket/70616
@herbygillot Bluetooth patch added. I am not sure if that will be sufficient, but let’s see.
macOS 10.6
Xcode 3.2
Have you
> fastfetch: update to 2.22.0 for legacy systems

- gnome/gdm/Portfile
- gnome/gdm/files/patch-daemon-gdm-session-record.c.diff
- gnome/gdm/files/patch-daemon-gdm-xdmcp-display-factory.c.diff
Fix the build
macOS 10.6
Xcode 3.2
Have you
> gdm: fix the build

- net/dibbler/Portfile
Fix build for older OS
macOS 10.6
Xcode 3.2
Have you
> dibbler: use legacysupport for clock_gettime

- devel/gdb/Portfile
* Update gdb 13.2 --> 15.1.
* Add new dependency mpfr.
* Add python 3.12.
* Remove broken makeinfo patch.
* Tried enabling ARM builds, did not work.
CI only.  OS 12, 13 only.  X86 only.
Tried OS 14/ARM build on CI, did not work.
Have you
> gdb: Update to 15.1

- devel/tree-sitter-python/Portfile
Fix after the recent update
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-python: needs C99 now

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 490.0.0.
Have you
> google-cloud-sdk: update to 490.0.0

- R/R-BiocManager/Portfile
- R/R-RSQLite/Portfile
- R/R-RcppBessel/Portfile
- R/R-SSN2/Portfile
- R/R-bigergm/Portfile
- R/R-boot/Portfile
- R/R-broom.helpers/Portfile
- R/R-cubble/Portfile
- R/R-extras/Portfile
- R/R-garchx/Portfile
- R/R-gdtools/Portfile
- R/R-glmmTMB/Portfile
- R/R-golem/Portfile
- R/R-greybox/Portfile
- R/R-harmony/Portfile
- R/R-nnlasso/Portfile
- R/R-pRF/Portfile
- R/R-pdR/Portfile
- R/R-pillar/Portfile
- R/R-quanteda.textstats/Portfile
- R/R-runMCMCbtadjust/Portfile
- R/R-rvg/Portfile
- R/R-sem/Portfile
- R/R-sensitivity/Portfile
- R/R-starma/Portfile
- R/R-tvgarch/Portfile
- R/R-vegan/Portfile
- R/R-vek/Portfile
A few updates
macOS 10.6
Xcode 3.2
Have you
> R: updates to packages

- devel/gh/Portfile
gh:  update checksums for gh binary used for macOS 10.12 and earlier
* update checksums for gh binary used for macOS 10.12 and earlier
Have you
> gh:  update checksums for gh binary used for macOS 10.12 and earlier

- devel/chai/Portfile
- devel/raja/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> raja, chai: update to 2024.07.0

- devel/proxychains-ng/Portfile
- devel/proxychains-ng/files/patch-EAI_OVERFLOW.diff
- devel/proxychains-ng/files/patch-fix-memcpy.diff
Fix build
macOS 10.6
Xcode 3.2
macOS 14.6
Xcode 15.4
Have you
> proxychains-ng: fix build on older OS and Sonoma

- textproc/mdtree-cpp/Portfile
CMakeLists want C++20
macOS 10.6
Xcode 3.2
Have you
> mdtree-cpp: set required C++ standard

- databases/sqlean/Portfile
- databases/sqlean/files/patch-no-time-ext.diff
@herbygillot Okay, this one fixed.
macOS 10.6
Xcode 3.2
Have you
> sqlean: fix for older systems again

- sysutils/mise/Portfile
mise: Upgrade to 2024.8.15
Have you
> mise: Upgrade to 2024.8.15

- sysutils/lima/Portfile
lima: Upgrade to 0.23.2
Have you
> lima: Upgrade to 0.23.2

- gnome/vte/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> vte: update to 0.76.4

- sysutils/nnn/Portfile
Avoid defunct clangs of 10.8–10.9. Tested on 10.8.5.
macOS 10.8.5
Xcode 5.1.1
Have you
> nnn: fix build on 10.8–10.9

- devel/uv/Portfile
Update `uv` to its latest released version, 0.4.0
Have you
> uv: Update to 0.4.0

- gnome/libgit2-glib/Portfile
Vala works now, no reason to disable it.
macOS 10.6
Xcode 3.2
Have you
> libgit2-glib: enable vala on powerpc

- lang/zig/Portfile
- Update to version 0.13.0
- Force static linking of llvm/clang; this was the default previously
- Since llvm/clang are linking statically these can be build-only dependencies.
Closes: https://trac.macports.org/ticket/70584
Supersedes: https://github.com/macports/macports-ports/pull/24430 (draft)
macOS 13.6.9 22G830 x86_64
Have you
There is a [draft PR](https://github.com/macports/macports-ports/pull/24430) for this that seems to have died on the vine.
>     zig: update to version 0.13.0

- sysutils/asprint/Portfile
Closes: https://trac.macports.org/ticket/70576
Have you
> asprint: Fetch from GitHub tarball instead of git rep

- net/gajim/Portfile
- net/gajim/files/0001-Avoid-non-existing-unsupported-AppKit-module.patch
- python/py-css-parser/Portfile
- python/py-emoji/Portfile
- python/py-nbxmpp/Portfile
- python/py-omemo-dr/Portfile
- python/py-precis-i18n/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
> gajim: update to 1.9.3, update its python dependencies

- devel/libayatana-appindicator/Portfile
Fix this, needed to run `gajim`
macOS 10.6
Xcode 3.2
Have you
> libayatana-appindicator: fix dylib path in gir file

- devel/orc/Portfile
Closes: https://trac.macports.org/ticket/70658
Fix
macOS 10.6
Xcode 3.2
Have you
> orc: use C11 to fix build on older OS

- devel/uv/Portfile
Update `uv` to its latest released version, 0.4.1
Have you
> uv: Update to 0.4.1

- gnome/libsoup-devel/Portfile
Update -devel port
macOS 10.6
Xcode 3.2
Have you
> libsoup-devel: update to 3.6.0

- math/dlib/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> dlib: update to 19.24.6

- _resources/port1.0/group/crossgcc-1.0.tcl
- cross/i686-w64-mingw32-gcc/Portfile
- cross/x86_64-w64-mingw32-gcc/Portfile
> *-w64-mingw32-gcc: Update to 14.2.0

- devel/Bear/Portfile
- devel/abseil/Portfile
- devel/abseil/files/patch-remove-Xarch-from-pkg-config.diff
- devel/apache-arrow/Portfile
- devel/grpc/Portfile
- devel/protobuf3-cpp-upstream/Portfile
- devel/re2/Portfile
- math/s2geometry/Portfile
- net/mtxclient/Portfile
Updated devel/abseil to 20240722.0, where MacOS 10.14 build is fixed. Revbumped abseil's dependents according to the Portfile note.
Have you
> abseil: update to 20240722.0, fixing MacOS 10.14 build

- lang/gnucobol/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> gnucobol: update to 3.2

- devel/cpp-utilities/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> cpp-utilities: update to 5.26.0

- devel/grpc/Portfile
[skip ci]
Skipping CI, this is a trivial change. Just tired every time to fix this locally (I use `libuv-devel`)
macOS 10.6
Xcode 3.2
Have you
> grpc: non-functional: use path-style deps for pkgconfig and libuv

- science/apbs/Portfile
Do not break the build by an unsupported flag.
macOS 10.6
Xcode 3.2
Have you
> apbs: unbreak build with gcc

- devel/nlohmann-json-schema-validator/Portfile
> nlohmann-json-schema-validator: new port

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.538
Have you
> ipsw: Update to 3.1.538

- devel/uv/Portfile
Update `uv` to its latest released version, 0.4.2
Have you
> uv: Update to 0.4.2

- _resources/port1.0/group/crossgcc-1.0.tcl
When originally copied from gcc11 the compiler blacklist listed blocking clang < 1000, but going off gcc14 that should be clang < 1001 so matching that instead.
> crossgcc: Correct compiler blacklist

- devel/lazydocker/Portfile
Update to the latest release of lazydocker.
Have you
> lazydocker: update to version 0.23.3

- devel/tree-sitter-java/Portfile
And this too )
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-java: needs C99 now

- gnome/gobject-introspection-devel/Portfile
- gnome/gobject-introspection-devel/files/msvccompiler.patch
Closes: https://trac.macports.org/ticket/70667
macOS 10.15.7
Xcode 12.4 / Command Line Tools 12.4.0.0.1.1610135815
Have you
> gobject-introspection-devel: Fix giscanner with setuptools 74

- audio/FAudio/Portfile
Simple update
macOS 10.6
Xcode 3.2
Have you
> FAudio: update to 24.09

- aqua/qt64/Portfile
- aqua/qt64/files/patch-qtbase-QTBUG-111443-qt64.diff
- aqua/qt64/files/patch-qtbase-macos_10.14_sdk.diff
- aqua/qt64/files/patch-qtbase-macports-clang-qt64.diff
One patch fixes an error when passing incorrect options to non-Apple CLang.
The other fixes useless locale warnings when running any QCoreApplication-based app compiled with Qt 6.4.3.
Both patches are taken from the upstream Qt repository.
P.S. Added a 10.15 SDK build fix.
Have you
> qt64-qtbase: Fix building on 10.14 and 10.15 and a minor patch

- databases/mysql57/Portfile
- databases/mysql57/files/patch-NOTE_TRIGGER.diff
- databases/mysql57/files/patch-powerpc.diff
Also, add a build conflict with `poll-emulator`
macOS 10.6
Xcode 3.2
Have you
> mysql57: fix for powerpc

- archivers/blosc2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> blosc2: update to 2.15.1

- science/ngspice/Portfile
- science/ngspice/files/patch-fix-linking.diff
- science/ngspice/files/patch-ngspice-older-MACH-defines.diff
- science/ngspice/files/patch-use-cxx-to-link-cxx-code.diff
Fixes `ngspice` after a breaking update, fixes what was broken in the earlier version.
@markemer @bpdegnan 
P. S. Likely fixups which are for < 10.7 should be used unconditionally, but let maintainers decide on that.
macOS 10.6
Xcode 3.2
Have you
> ngspice: fix the port for < 10.8

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.539
Have you
> ipsw: Update to 3.1.539

- _resources/port1.0/group/crossbinutils-1.0.tcl
- cross/i686-w64-mingw32-binutils/Portfile
- cross/x86_64-w64-mingw32-binutils/Portfile
> *-w64-mingw32-binutils: Update to 2.43.1

- devel/catch2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> catch2: update to 3.7.0

- devel/tree-sitter-json/Portfile
And this also needs C99
macOS 10.6
Xcode 3.2
Have you
> tree-sitter-json: needs C99

- lang/php/Portfile
I was able to succesfully build php82-postgresql and confirmed pdo_pgsql.so and pgsql.so both linked against the right postgresql16 libpq. However, I did not test the functionality of the libraries.
Have you
> php-postgres: update postgresql versions

- databases/sqlean/files/patch-no-time-ext.diff
@herbygillot This builds now again
macOS 10.6
Xcode 3.2
Have you
> sqlean: update the patch for legacy systems so that it works again

- ruby/ruby-build/Portfile
> ruby-build: Upgrade to 20240903

- gis/JOSM/Portfile
> josm: update to 19207

- python/py-rasterio/Portfile
- python/py-rasterio/files/patch-fix-setup.py.diff
@stromnov Should we just apply this patch unconditionally? Compiler is supposed to handle it, but I cannot test on every system.
macOS 10.6
Xcode 3.2
Have you
> py-rasterio: unbreak build with libstdc++

- textproc/ocrmypdf/Portfile
- update to 16.5.0
- add hatchling to build deps
Have you
> OCRmyPDF: update to 16.5.0

- security/rage/Portfile
This adds a portfile for [rage](https://github.com/str4d/rage), a Rust implementation of [age](https://github.com/C2SP/C2SP/blob/main/age.md).
Have you
> rage: add port

- security/tor-devel/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> tor-devel: update to 0.4.8.12

- math/tapkee/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> tapkee: update to 2024.07.17

- devel/protobuf3-cpp-upstream/Portfile
- devel/protobuf3-cpp-upstream/files/patch-unbreak-time.diff
Update
macOS 10.6
Xcode 3.2
Have you
> protobuf3-cpp-upstream: update to 3.28.0

- devel/swiftformat/Portfile
Add new port: swiftformat
Have you
- [] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken? N/A
> swiftformat: new port

- lang/elixir/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
> elixir: update to 1.17.2

- devel/dyncall/Portfile
- devel/dyncall/files/patch-callback_suite.diff
Update
macOS 10.6
Xcode 3.2
Have you
> dyncall: update to 1.4

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.540
Have you
> ipsw: Update to 3.1.540

- devel/uv/Portfile
Update `uv` to its latest released version, 0.4.4
Have you
> uv: Update to 0.4.4

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.25.0
Have you
> gitu: Update to 0.25.0

- net/syncthing/Portfile
update syncthing to 1.27.11
Have you
> syncthing: update to 1.27.11

- sysutils/qrcp/Portfile
* changelog: https://github.com/claudiodangelis/qrcp/releases/tag/0.11.3
* install completions
* add ldflags
Xcode 14.2
Have you
> qrcp: update to 0.11.3

- devel/openssl/Portfile
- devel/openssl3/Portfile
- net/openssh/Portfile
- sysutils/freeradius/Portfile
See https://openssl-library.org/news/secadv/20240903.txt and https://openssl-library.org/news/secadv/20240627.txt for the upstream advisories.
The changelog is at https://openssl-library.org/news/openssl-3.3-notes/.
The source code has moved to GitHub releases, so adjust the source accordingly.
CVE: CVE-2024-6119
CVE: CVE-2024-5535
Have you
> openssl3: Update to 3.3.2, fix two CVEs

- sysutils/mise/Portfile
mise: Upgrade to 2024.9.0
Have you
> mise: Upgrade to 2024.9.0

- security/age-plugin-yubikey/Portfile
This adds a portfile for [age-plugin-yubikey](https://github.com/str4d/age-plugin-yubikey), a plugin for [age](https://age-encryption.org/v1) clients like [age](https://age-encryption.org/) and [rage](https://str4d.xyz/rage), which enables files to be encrypted to age identities stored on YubiKeys.
Have you
> age-plugin-yubikey: add port

- net/libpcap/Portfile
Fix compiler choice after the recent update
macOS 10.6
Xcode 3.2
Have you
> libpcap: needs compiler.thread_local_storage

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 491.0.0.
Have you
> google-cloud-sdk: update to 491.0.0

- math/lean/Portfile
Update, drop arch restriction
macOS 10.6
Xcode 3.2
Have you
> lean: update to 3.51.1

- java/micronaut/Portfile
Update to Micronaut Starter 4.6.1.
Have you
> micronaut: update to 4.6.1

- lang/clojure/Portfile
> clojure: update to  1.12.0.1479

- devel/cpputest/Portfile
- devel/cpputest/files/0001-MockParameterTest.cpp-fix-ULL-constants.patch
Fix constants
macOS 10.6
Xcode 3.2
Have you
> cpputest: fix build

- devel/openssl3/Portfile
- devel/openssl3/files/patch-mkinstallvars.diff
Closes: https://trac.macports.org/ticket/70684
Have you
> openssl3: fix build with older versions of Perl

- sysutils/fastfetch/Portfile
Update for legacy systems
macOS 10.6
Xcode 3.2
Have you
> fastfetch: update to 2.23.0 for legacy systems

- devel/uv/Portfile
Update `uv` to its latest released verison, 0.4.6
Have you
> uv: Update to 0.4.6

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.6.4
Have you
> ruff: Update to 0.6.4
