devel/cpp-peglib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

cpp-peglib: update to 1.9.0

---

gis/tippecanoe/Portfile

tippecanoe: update to 2.62.0

---

sysutils/screen/Portfile

Fix building `screen` on < OSX 10.12 by setting `compiler.c_standard` to support value "c17" in "-std=c17"
Have you

screen: Fix invalid value 'c17' in '-std=c17'

---

databases/valkey/Portfile

The purpose of this variant is to ease transition from the redis package.
Have you

valkey: add redis_compat variant with redis symlinks

---

net/gallery-dl/Portfile

- update to 1.27.4
- removed the youtube-dl variant, kept the yt-dlp variant
Have you

gallery-dl: update to 1.27.4, remove youtube-dl

---

x11/Xaw3d/Portfile
x11/Xaw3d/files/patch-src-vendor.diff

Update
macOS 10.6
Xcode 3.2
Have you

Xaw3d: update to 1.6.6

---

lang/gccxml-devel/Portfile
lang/gccxml-devel/files/patch-fix-host-darwin.diff

Fix the port
macOS 10.6
Xcode 3.2
Have you

gccxml-devel: update, fix on powerpc, set supported platforms

---

math/vampire/Portfile
math/vampire/files/0001-Allocator.cpp-fix-for-macOS-where-aligned_alloc-may-.patch

Update to a released version.
macOS 10.6
Xcode 3.2
Have you

vampire: update to 4.9 release

---

sysutils/fastfetch/Portfile
sysutils/fastfetch/files/0021-CMakeLists-do-not-use-Linux-ldflag-on-macOS.patch
sysutils/fastfetch/files/0022-Tiger-specific-adjustments-to-CMakeLists.patch

Hopefully should fix build on 10.5, which reportedly fails on recently added module `binary_apple`.
A patch to remove `-rdynamic` is a matter of neatness.
macOS x.y
Have you

fastfetch: minor fix for legacy macOS (no revbump)

---

devel/pika/Portfile
devel/pika/files/patch-fix-finding-boost.diff

Update
macOS 10.6
Xcode 3.2
Have you

pika: update to 0.28.0

---

python/py-awscli2/Portfile
python/py-awscli2/files/0001-py-awscli2-Support-empty-PAGER.patch

Closes: https://trac.macports.org/ticket/70601
Have you

py-awscli2: update to 2.17.46

---

graphics/ImageMagick7/Portfile

ImageMagick7: Update to 7.1.1-38
CI only.  OS 12-x86, 13-x86, 14-arm only.
Have you

ImageMagick7: Update to 7.1.1-38

---

sysutils/bfs/Portfile

Update `bfs` to 4.0.1
Have you

bfs: update to 4.0.1

---

devel/gitui/Portfile

https://github.com/extrawurst/gitui/releases/tag/v0.26.3
Xcode 14.2
Have you

gitui: update to 0.26.3

---

textproc/man-db/Portfile

Update `man-db` to 2.13.0
Have you

man-db: update to 2.13.0

---

science/nco/Portfile

Simple update to upstream version 5.2.8. No further changes needed.
Have you

nco: update to 5.2.8

---

science/ecCodes/Portfile

Simple update to upstream version 2.37.0. No further updates needed.
Have you

ecCodes: update to 2.37.0

---

multimedia/jpeginfo/Portfile

jpeginfo: add legacysupport portgroup for macOS 10.6 (strnlen)

---

math/LBFGSpp/Portfile

New port in math
macOS 10.6
Xcode 3.2
Have you

LBFGSpp: new port in math

---

math/cppoptlib/Portfile

New port in math
macOS 10.6
Xcode 3.2
Have you

cppoptlib: new port in math

---

math/finite-diff/Portfile
math/finite-diff/files/patch-CMakeLists.diff

New port in math
macOS 10.6
Xcode 3.2
Have you

finite-diff: new port in math

---

devel/boehmgc/Portfile

Fix the build: the port now uses C11 atomics
macOS 10.6
Xcode 3.2
Have you

boehmgc: fix build after update

---

cross/mingw-w64-wine-mono/Portfile
emulators/wine-devel/Portfile
emulators/wine-devel/files/1001-devel-msync.diff
emulators/wine-devel/files/1001-staging-msync.diff

Also adds `mingw-w64-wine-mono-9.3.0` subport as it's required for wine-9.17

Wine devel,wine staging update to 9.17

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.1
Have you

mise: Upgrade to 2024.9.1

---

security/stunnel/Portfile

Currently the build checks for `mimalloc` and links to it if it is found. Fix that.
macOS 10.6
Xcode 3.2
Have you

stunnel: prevent opportunistic linking to mimalloc, add a variant

---

graphics/msdfgen/Portfile

Do not use Clang-specific flag with gcc
macOS 10.6
Xcode 3.2
Have you

msdfgen: unbreak build with gcc

---

science/sparskit/Portfile
science/sparskit/files/patch-makefile.diff

Closes: https://trac.macports.org/ticket/70636
Have you

sparskit: Update to 2-20210601

---

devel/cryptlib/Portfile
devel/cryptlib/files/patch-static_assert.diff

Fix build with gcc
macOS 10.6
Xcode 3.2
Have you

cryptlib: fix build with gcc

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 492.0.0.
Have you

google-cloud-sdk: update to 492.0.0

---

irc/weechat/Portfile

weechat: update to 4.4.2
* add new build dependency `libcjson`
* remove old, no longer used build option `ENABLE_PYTHON2`
* update AUTHORS, README, and CHANGELOG file extensions to `.md`
Have you

weechat: update to 4.4.2

---

security/ipsw/Portfile

Update `ipsw` to its latest version, 3.1.542
Have you

ipsw: Update to 3.1.542

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.9
Have you

uv: Update to 0.4.9

---

sysutils/stow/Portfile

Update `stow` to its latest released version, 2.4.1
Have you

stow: Update to 2.4.1

---

math/flint/Portfile

Update to the latest release
macOS 10.6
Xcode 3.2
Have you

flint: update to 3.1.3-p1

---

science/verilator/Portfile

Updated verilator from 5.020 to 5.028
Have you

verilator: update version 5.020->5.028

---

python/py-bottleneck/Portfile
python/py-bottleneck/files/patch-pyproject.toml.diff

Work around PyPI py-numpy >= 2.0.0 requirement
See: https://github.com/pydata/bottleneck/blob/master/pyproject.toml
See: https://trac.macports.org/ticket/70251
Have you

py-bottleneck: update to 1.4.0

---

devel/direnv/Portfile

direnv: update to 2.34.0

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.543
Have you

ipsw: Update to 3.1.543

---

devel/tree-sitter-go-mod/Portfile

A usual issue
macOS 10.6
Xcode 3.2
Have you

tree-sitter-go-mod: needs C99

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.2
Have you

mise: Upgrade to 2024.9.2

---

devel/libcoverart/Portfile
devel/libcoverart/files/patch-cmakelists-4.diff

Not sure why the source wants to break the build specifically with gcc, but anyway, this does not compiler with `-Werror` due to warnings been treated as errors then. Remove breaking flags.
There is no effect on clang builds.
macOS 10.6
Xcode 3.2
Have you

libcoverart: fix build with gcc

---

sysutils/screen/Portfile
sysutils/screen/files/patch-use-right-environ.diff

Fix `screen` on OSX 10.6 by using the `legacysupport` PG for `strndup`. Other patches were added to use appropriate functions and fix building on OSX 10.5 and lower.
Have you

screen: Use `legacysupport` to support OSX 10.6

---

gis/GPXSee/Portfile

GPXSee: update to 13.24

---

devel/libgdiplus/Portfile

Portfile code unnecessarily breaks building on old systems by forcing linking to a non-existing before 10.8 framework. (Also, obviously, that gonna break the build on any non-Apple OS.)
Use a correct condition.
Since the source redefines types, set C11 standard.
macOS 10.6
Xcode 3.2
Have you

libgdiplus: unbreak build on < 10.8

---

math/OpenBLAS/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

OpenBLAS: update to 0.3.28

---

databases/dbeaver-community/Portfile

Update dbeaver-community to 24.2.0
Have you

dbeaver-community: Update to 24.2.0

---

sysutils/mise/Portfile

cargo.crates \
anstream                    0.6.15  64e15c1ab1f89faffbf04a634d5e1962e9074f2741eef6d97f3c4e322426d526 \
anstyle                      1.0.8  1bec1de6f59aedf83baf9ff929c98f2ad654b97c9510f4e70cf6f661d49fd5b1 \
anstyle-parse                0.2.5  eb47de1e80c2b463c735db5b217a0ddc39d612e7ac9e2e96a5aed1f57616c1cb \
anstyle-query                1.1.1  6d36fc52c7f6c869915e99412912f22093507da8d9e942ceaf66fe4b7c14422a \
anstyle-wincon               3.0.4  5bf74e1b6e971609db8ca7a9ce79fd5768ab6ae46441c572e46cf596f59e57f8 \
bitflags                     2.6.0  b048fb63fd8b5923fc5aa7b340d8e156aec7ec02f0c78fa8a6ddc2613f6f71de \
cc                           1.1.7  26a5c3fd7bfa1ce3897a3a3501d362b2d87b7f2583ebcb4a949ec25911025cbc \
cfg-if                       1.0.0 …

mise: Upgrade to 2024.9.3

---

sysutils/tldr-cpp-client/Portfile

Avoid Xcode gcc
macOS 10.6
Xcode 3.2
Have you

tldr-cpp-client: fix build on old systems

---

textproc/help2man/Portfile

Using `-bundle` flag breaks build on Linux.
Linux pinetab 5.15
Have you

help2man: do not break build on Linux

---

audio/rsgain/Portfile
devel/inih/Portfile

Should be self-evident.
macOS 10.6
Xcode 3.2
Have you

rsgain, inih: set required C++ standards, fix build with gcc

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.6.5
Have you

ruff: Update to 0.6.5

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.10
Have you

uv: Update to 0.4.10

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.544
Have you

ipsw: Update to 3.1.544

---

mail/mblaze/Portfile

Fix the build, add conflicts
macOS 10.6
Xcode 3.2
Have you

mblaze: fix on < 10.7, add needed conflicts

---

java/micronaut/Portfile

Update to Micronaut Starter 4.6.2.
Have you

micronaut: update to 4.6.2

---

audio/lms/Portfile
audio/lms/files/0001-CMakeLists-do-not-use-Linux-ldflag-on-macOS.patch
audio/lms/files/0002-Fix-lms.conf-path.patch
audio/lms/files/777c36005bdcdc09e1813a84f3f2c0acc0b47fac.patch

New port
macOS 10.6
Xcode 3.2
Have you

lms: new port in audio

---

gnome/gpodder/Portfile
python/py-mygpoclient/Portfile
python/py-podcastparser/Portfile

Also support py312 in dependencies 
macOS 10.6
Xcode 3.2
Have you

gpodder: update to 3.11.4

---

aqua/input-leap/Portfile

Minor build fix, remove unnecessary dependency to 'qt5compat'.
Have you

input-leap: update port

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.4
Have you

mise: Upgrade to 2024.9.4

---

graphics/ImageMagick7/Portfile

Recent update of `libjxl` left it broken.
macOS x.y
Have you

ImageMagick7: explicitly depend on libjxl, revbump

---

lang/ruby33/Portfile
lang/ruby33/files/patch-sources.diff

See:
https://www.ruby-lang.org/en/news/2024/09/03/3-3-5-released/
As usual, all source patches are in a single patchfile derived from the ruby fork at github.com/fhgwright/ruby.  The changes are much more readable in the git repo.
The patches no longer include the atomic_signal_fence fix, which is now upstream.  Otherwise, the only patchfile changes are for the newer file mtimes.
Also updates the +yjit description to indicate that it requires rust.
TESTED:
Built successfully with no variants on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.
Built with all variants except jemalloc and yjit on 10.4-10.5, all variants except yjit on 10.6-10.12, and all variants on 10.13+. Tests not run due to test framework issues.
```
Mac …
```

ruby33: update to v3.3.5

---

audio/lms/Portfile
audio/lms/files/0001-CMakeLists-do-not-use-Linux-ldflag-on-macOS.patch

Update, somehow missed earlier
macOS 10.6
Xcode 3.2
Have you

lms: update to 3.57.0

---

multimedia/libass/Portfile
multimedia/libass/files/0760c5302d12dbb358cabd81c330c3ce20b5151c.patch
multimedia/libass/files/abc7fbdbb0313536d2f9684dd527c736814e45d8.patch

Update. Should fix compilation with gcc7 (backport of upstream patch).
macOS 10.6
Xcode 3.2
Have you

libass: update to 0.17.3; libass-devel: update to 2024.09.13

---

sysutils/tmux/Portfile
sysutils/tmux/files/patch-devel-gcc4.diff

Fix build of -devel subport.
macOS 10.6
Xcode 3.2
Have you

tmux-devel: fix build with gcc-4.2

---

sysutils/edid-decode/Portfile

* add options to read EDID and HDCP data directly from DDC
* fix emscripten build
* check if linux/i2c-dev.h is available
* report if InfoFrame size is too small
* Fix Visual Studio builds. Add utf-8 option and parse-if.cpp file.
Have you

edid-decode: update to version 20240903

---

devel/mongo-cxx-driver/Portfile

Not sure why the arch restriction at all. I could build this for ppc with no changes to the portfile besides dropping this line.
I suspect it will build for riscv64 too, I just do not have dependencies there.
Drop restriction.
macOS 10.6
Xcode 3.2
Have you

mongo-cxx-driver: drop unneeded arch restriction

---

devel/mongo-c-driver/Portfile
devel/mongo-c-driver/files/pthread_threadid_np.patch

Fix build on old macOS.
macOS 10.6
Xcode 3.2
Have you

mongo-c-driver: fix build for old systems

---

java/openjdk23-zulu/Portfile

New port for Azul Zulu OpenJDK 23.
Have you

openjdk23-zulu: new submission

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.5
Have you

mise: Upgrade to 2024.9.5

---

ruby/ruby-build/Portfile

ruby-build: Upgrade to 20240917
Have you

ruby-build: Upgrade to 20240917

---

games/packwiz/Portfile

Update Packwiz to 240808 (0bb89a4)
Have you

Packwiz: Update to 240808

---

graphics/ctpv/Portfile

ctpv: fix build on old systems

---

x11/xorg-libXi/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

xorg-libXi: update to 1.8.2

---

perl/p5-mac-fsevents/Portfile

See: https://trac.macports.org/ticket/70736
Temporary fix for a broken port.
macOS 10.6
Xcode 3.2
Have you

p5-mac-fsevents: provide version for < 10.7

---

java/openjdk23-corretto/Portfile

Update to Amazon Corretto 23.0.0.37.1.
Have you

openjdk23-corretto: update to 23.0.0.37.1

---

java/jdk23/Portfile

New port for Oracle Java SE Development Kit 23.
Have you

jdk23: new submission

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 493.0.0.
Have you

google-cloud-sdk: update to 493.0.0

---

java/openjdk23-temurin/Portfile

New port for Eclipse Temurin 23.
Have you

openjdk23-temurin: new submission

---

java/openjdk21-openj9/Portfile

Update to OpenJ9 0.46.1.
Have you

openjdk21-openj9: update to OpenJ9 0.46.1

---

java/openjdk17-openj9/Portfile

Update to OpenJ9 0.46.1.
Have you

openjdk17-openj9: update to OpenJ9 0.46.1

---

java/openjdk11-openj9/Portfile

Update to OpenJ9 0.46.1.
Have you

openjdk11-openj9: update to OpenJ9 0.46.1

---

java/openjdk8-openj9/Portfile

Update to OpenJ9 0.46.1.
Have you

openjdk9-openj9: update to OpenJ9 0.46.1

---

java/openjdk23-sap/Portfile

New port for SapMachine 23.
Have you

openjdk23-sap: new submission

---

aqua/qt5/Portfile

* qt5-qtbase error for CGDIsplayImageForRect on macOS 15
* Set macosx_deployment_target 14.0 for qt5 in general to stop the following error: `error: 'CGDisplayCreateImageForRect' is unavailable: obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.`
macOS 15.0 24A335
Xcode 16.0 16A242
Have you

qt5-qtbase: fix for macOS 15

---

lang/groovy/Portfile

Update to Groovy 4.0.23.
Have you

groovy: update to 4.0.23

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.6
Have you

mise: Upgrade to 2024.9.6

---

lang/fortran-stdlib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib-devel: update to 2024.09.18

---

graphics/babl-devel/Portfile
graphics/babl/Portfile
graphics/gegl-devel/Portfile
graphics/gegl/Portfile

1. There was a time when vala was broken on powerpc, it is not the case anymore. Drop special cases for powerpc.
2. Since libsdl2 builds on all systems, use it consistently, but retain sdl1 in a variant.
3. Use legacysupport 1.1.
4. Path-style deps on pkgconfig.
All changes are relevant only for legacy systems. Revbumps are still required though.
macOS 10.6
Xcode 3.2
Have you

babl*, gegl*: enable vala on powerpc, use libsdl2 across the board

---

textproc/asciidoc/Portfile

asciidoc: Update to 10.2.1
Closes: https://trac.macports.org/ticket/70039
macOS 10.15.7
Xcode 11.5 / Command Line Tools 11.5.0
Compiler Apple clang 11.0.1
Have you

asciidoc @10.2.0 Warning: invalid escape sequence '\S'

---

devel/nusmv/Portfile

Closes: https://trac.macports.org/ticket/70360
Fix this one
macOS 10.6
Xcode 3.2
Have you

nusmv: fix the build on older systems

---

java/spring-boot-cli/Portfile

Update to Spring Boot CLI 3.3.4.
Have you

spring-boot-cli: update to 3.3.4

---

graphics/wxWidgets-3.0/Portfile

* CGDisplayCreateImage fails on macOS 15 due to removal from macOS 15 SDK
Closes: https://trac.macports.org/ticket/70756
macOS 15.0 24A335
Have you

wxWidgets: fix error on macOS 15

---

math/gnuplot/Portfile

Simple update to upstream version 6.0.1.
Also took up the recommendation from @markemer to replace `+x11` by `+qt` in the `default_variants`.
Closes https://trac.macports.org/ticket/70357
Have you

gnuplot: update to 6.0.1

---

java/openjdk23-openj9/Portfile

New port for IBM Semeru based on OpenJDK 23 (OpenJ9 0.47.0).
Have you

openjdk23-openj9: new submission

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.13
Have you

uv: Update to 0.4.13

---

science/mafft/Portfile

mafft: needs thread_local_storage

---

cross/avr-gcc/Portfile

GCC 13.1 does not compile on my macOS Sequoia machine. This breaks avr-gcc. Fix it by bumping version to 14.2.

Update avr-gcc to use GCC 14.2

---

science/ncbi_tools/Portfile
science/ncbi_tools/files/patch-fix-build.diff

* Update patch of ncbi_tools to enable compilation on macOS Sequoia - careful not to let text editor clean up whitespace!
* Removing platform from portfile, suppresses warning
NOTE - A previous PR for this fix failed spectacularly because config linted whitespace in the patch upon committing (ie after I tested it). Apologies. I committed this version via my terminal and confirmed that it patches, builds and installs correctly afterward.
Make adjustments to patch file to fix warnings that are treated as errors in macOS 15.0 / Xcode 16.0.
macOS 15.0
Xcode 16.0
Have you

Update ncbi_tools for macOS Sequoia

---

net/paho.mqtt.cpp/Portfile

paho.mqtt.cpp: set required C++11 standard

---

multimedia/ltc-tools/Portfile

Fix build with old Apple gcc
macOS 10.6
Xcode 3.2
Have you

ltc-tools: fix build with Xcode gcc

---

devel/protobuf3-cpp-upstream/Portfile
devel/re2/Portfile
math/s2geometry/Portfile

This PR is a followup to #23907 and updates the dependents of abseil to also use c++17 standard.
The dependents `Bear` and `apache-arrow` already use c++17 and `mtxclient` even c++20, so these were not updated.
I'm not sure if `protobuf-c` as a recursive dependent must be updated, too? 
Relevant ticket on trac: [https://trac.macports.org/ticket/69975](https://trac.macports.org/ticket/69975)
Have you

abseil-dependents: Use c++17 standard

---

sysutils/libvirt/Portfile
sysutils/libvirt/files/patch-fix-linking.diff
sysutils/libvirt/files/patch-st_birthtimespec.diff

Fix
macOS 10.6
Xcode 3.2
Have you

libvirt: fix build on older systems

---

devel/c2t/Portfile
devel/c2t/files/Makefile.patch

Drop a warning flag which breaks the build with Xcode gcc.
macOS 10.6
Xcode 3.2
Have you

c2t: allow build with Xcode gcc

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.6.6
Have you

ruff: Update to 0.6.6

---

devel/bctoolbox/Portfile
devel/bctoolbox/files/0001-ios_utils.hh-add-a-missing-memory-include.patch
devel/bctoolbox/files/0002-port.c-define-AI_NUMERICSERV-if-undefined.patch
devel/bctoolbox/files/0003-BcToolboxCMakeUtils.cmake-fix-flags-for-Apple.patch
devel/bctoolbox/files/patch-fix-10.6.diff
devel/ortp/Portfile
devel/ortp/files/patch-fix-gcc-build.diff
devel/ortp/files/patch-legacy.diff

Unbreak both ports for old systems.
macOS 10.6
Xcode 3.2
Have you

bctoolbox, ortp: fix build for < 10.7

---

devel/cmake-devel/Portfile

Update -devel port
macOS 14.5
Xcode 15.4
macOS 10.6
Xcode 3.2
Have you

cmake-devel: update to 3.30.2

---

math/crfsuite/Portfile

Do not use Intel vectorization on non-Intel archs.
macOS 10.6
Xcode 3.2
Have you

crfsuite: unbreak build on non-x86 archs

---

gis/grass/Portfile
gis/orfeotoolbox/Portfile
math/libsvm/Portfile
math/libsvm/files/patch-Makefile.diff
php/php-svm/Portfile
python/py-pymvpa/Portfile

Update `libsvm` to version 3.35.
As this rev-bumps `orfeotoolbox`, I took the opportunity to include a fix for livecheck regex (which used to include rc versions as well).
Have you

libsvm: update to 3.35 and add py312-libsvm subport

---

python/py-astroML/Portfile
python/py-astroML_addons/Portfile
python/py-beancount-import/Portfile
python/py-eli5/Portfile
python/py-geoplot/Portfile
python/py-hdbscan/Portfile
python/py-librosa/Portfile
python/py-mapclassify/Portfile
python/py-note-seq/Portfile
python/py-pmdarima/Portfile
python/py-seqeval/Portfile
python/py-tpot/Portfile
python/py-umap-learn/Portfile
python/py-xraylarch/Portfile

py38-scikit-learn deps: drop python 3.8 or use 3.9

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.15
Have you

uv: Update to 0.4.15

---

gnome/gtk2/Portfile

* Another victim of the ScreenCaptureKit requirement, CGWindowListCreateImage is removed in SDK 15
* Set macosx_deployment_target to 14
Closes: https://trac.macports.org/ticket/70774
macOS 15.0 24A335
Have you

gtk2: fix for macOS 15

---

devel/the_Foundation/Portfile
net/lagrange/Portfile

* https://github.com/skyjake/lagrange/releases/tag/v1.18.0
* https://git.skyjake.fi/skyjake/the_Foundation/src/tag/v1.9.0
Xcode 14.2
Have you

lagrange: update to 1.18.0, the_Foundation: update to 1.9.0

---

graphics/wxWidgets-3.2/Portfile

* Another victim of the CoreGraphics deprecations in the macOS 15 SDK in favor of screen capture kit
* macos_deployment_target of 14.0 fixed it
Closes: https://trac.macports.org/ticket/70844
macOS 15.0 24A335
Have you

wxWidgets-3.2: fix error on macOS 15

---

java/openjdk22/Portfile
java/openjdk22/files/JDK-8340341-clang-16-workaround.patch

Apply patch from https://github.com/openjdk/jdk/pull/21119 to fix build on clang 16.
Have you

openjdk22: fix build for clang 16

---

java/openjdk21/Portfile
java/openjdk21/files/JDK-8340341-clang-16-workaround.patch

Backport fix for https://trac.macports.org/ticket/70819 to OpenJDK 21.
Have you

openjdk21: fix build for clang 16

---

java/openjdk23-openj9/Portfile

Support for OpenJDK 23 ends in March 2025 instead of September 2024.
Have you

openjdk23-openj9: correct support end date

---

java/openjdk23/Portfile
java/openjdk23/files/JDK-8340341-clang-16-workaround.patch

New port for building OpenJDK 23 from source.
Have you

openjdk23: new submission

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.6.7
Have you

ruff: Update to 0.6.7

---

devel/cpp-argparse-dev/Portfile

* Add: unicode 16 to upper case support
* Fix: TranslationPack::operator [] impl
* Fix: don't break bash completion for const actions
macOS 13.6.5 22G621 x86_64
Have you

cpp-argparse-dev: update to v1.9.4

---

lang/sbcl-bootstrap/Portfile

Update later, since 2.4.6 fails on macOS 13. Here update powerpc boot binary, which is required to support powerpc now (2.4.4 has been broken, since the old boot binary cannot build it).
macOS 10.6
Xcode 3.2
Have you

sbcl-bootstrap: update powerpc boot binary

---

gnome/at-spi2-core/Portfile

at-spi2-core v2.38.0 fails to compile on macOS 15/Xcode 16. Updating to version 2.44.1 resolves the issue. 
Closes: https://trac.macports.org/ticket/70776
Note that at-spi2-atk has no updates, but as of at-spi2-core version 2.45.1, the two libraries are merged.  So updating at-spi2-core to v2.44.1 is simply a work-around until then.
Xcode 16.0 16A242d / Command Line Tools 16.0.0.0.1.1724870825
Have you

at-spi2-core: Update to version 2.44.1.

---

mail/spellutils/Portfile
mail/spellutils/files/patch-configure.diff

The configure script for spellutils attempts to check if the compiler can create an executable with this C code:
```
main(){return(0);}
```
On my system, this is the output:
```
gcc foo.c
foo.c:1:1: error: return type defaults to 'int' [-Wimplicit-int]
1 | main(){return(0);}
| ^~~~
[Exit 1]
```
This commit adds a patch to ensure that the configure command succeeds. I also took the opportunity to fix the lint errors.
Ideally, the issue would be fixed upstream but the [upstream project webpage](http://home.worldonline.dk/byrial/spellutils/) is currently timing out for me.
Have you

spellutils: patch configure build script to allow building with modern gcc

---

graphics/ipe-tools/Portfile

ipe-tools: set required C++ standard

---

textproc/lttoolbox/Portfile

lttoolbox: set required C++14 standard

---

devel/libical/Portfile

Requires C++11 now (in fact already in 3.0.17, but that was missed), so drop a patch for gcc-4.2.
```
:info:configure   Target "ical_cxx" requires the language dialect "CXX11" (with compiler
:info:configure   extensions).  But the current compiler "GNU" does not support this, or
:info:configure   CMake does not know the flags to enable it.
```
macOS 10.6
Xcode 3.2
Have you

libical: update to 3.0.18

---

devel/asmotor/Portfile

Update `asmotor` to the latest released version, 1.3.1
Have you

asmotor: update to 1.3.1

---

devel/pnpm/Portfile

Update PNPM to 9.11.0
`port test` warns that there are Mach-O files built for x86 in the ARM build, but PNPM includes files for all platforms in all distributions. In the future, a step could be added to remove the unneeded mach-o files, but this isn't strictly necessary. Although I'm pretty sure it's a universal package, I couldn't mark it as such because it depends on Node.js, which isn't.
Have you

PNPM: Update to 9.11.0

---

cross/arm-none-eabi-gcc/Portfile

This makes it possible to build arm-none-eabi-gcc using the Xcode 16 toolchain, enabling macOS 15 support. gcc 14 is currently the only gcc version that can build under Xcode 16/macOS 15.
Closes: https://trac.macports.org/ticket/70754
Have you

arm-none-eabi-gcc: update to 14.2.0

---

lisp/cl-gobject-introspection/Portfile

CI on macOS 13 expected to fail due to SBCL. Unrelated to this PR.
macOS 10.6
Xcode 3.2
Have you

cl-gobject-introspection: update to upstream, fixes build with current SBCL

---

security/KeePassXC/Portfile

**KeePassXC** fails to compile on macOS 15/Xcode 16. Setting the macOS deployment target to 14 (or less) resolves the issue.  See also:
https://trac.macports.org/wiki/SequoiaProblems#ScreenCaptureKitRequirementwithmacOS15SDK
NB: **KeePassXC** depends on ports **qt5-qtbase** and **libsodium**, which must be patched as well on macOS 15. **qt5-qtbase** can be patched in the same manner as this PR.  **libsodium** just needs to be updated - see PR #25833.
Xcode 16.0 16A242d / Command Line Tools 16.0.0.0.1.1724870825
Have you

KeePassXC: Fix by setting deployment target for darwin 24.

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.7
Have you

mise: Upgrade to 2024.9.7

---

sysutils/bpytop/Portfile
sysutils/bpytop/files/patch-pr422.diff

In MacPorts, bpytop didn't find its themes, because it did not search relative to its executable, and only search default paths /usr and /usr/local.
Have you

bpytop: Fix theme path detection

---

devel/binutils/Portfile
devel/binutils/files/patch-fix-riscv.diff

Update
macOS 10.6 ppc
Xcode 3.2
PinIx 1.2 riscv64
Have you

binutils: update to 2.43.1

---

lang/sbcl/Portfile
lang/sbcl/files/0003-runtime.c-fix-time-header-for-LISP_FEATURE_AVOID_CLO.patch

Also fix build when LISP_FEATURE_AVOID_CLOCK_GETTIME is used.
@easye @catap 
macOS 10.6
Xcode 3.2
Have you

sbcl-devel: update to 20240924

---

databases/valkey/Portfile
databases/valkey/files/d07c29791a4cecd8bce76b05d046981f39fe5fcd.patch

Closes: https://trac.macports.org/ticket/70794
Fix this
macOS 10.6
Xcode 3.2
Have you

valkey: backport a fix from upstream

---

print/a2ps/Portfile
print/a2ps/files/patch-xcode-gcc.diff

Fix build with old gcc
macOS 10.6
Xcode 3.2
Have you

a2ps: fix build with Xcode gcc

---

devel/expect/Portfile
devel/expect/files/patch-implicitly-defined-functions.diff

This fixes the build with Xcode 16.
macOS 15.1 24B5046f
Xcode 16.1 16B5014f 
Have you

expect: Add missing return type in configure tests

---

textproc/remind/Portfile

Fix compiler choice on old systems
macOS 10.6
Xcode 3.2
Have you

remind: fix build on old systems

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.8
Have you

mise: Upgrade to 2024.9.8

---

lang/llvm-17/Portfile
lang/llvm-17/files/0043-builtins-Move-cfi-start-s-after-the-symbol-name-NFC.patch

This is a cherry-pick of
https://github.com/llvm/llvm-project/commit/7939ce39dac0078fef7183d6198598b99c652c88.
Xcode 16 runs on macOS 14 and 15, so the patch is applied on macOS ≥ 14.
Closes: https://trac.macports.org/ticket/70779
Have you

clang-17, llvm-17: restore functionality on macOS 15 (Xcode 16)

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 494.0.0.
Have you

google-cloud-sdk: update to 494.0.0

---

emulators/wine-devel/Portfile
emulators/wine-devel/files/1001-devel-msync.diff
emulators/wine-devel/files/1001-staging-msync.diff

wine-devel,wine-staging: Update to 9.18

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.9
Have you

mise: Upgrade to 2024.9.9

---

devel/uv/Portfile

uv: Upgrade to 0.4.16
Have you

uv: Upgrade to 0.4.16

---

lang/llvm-16/Portfile
lang/llvm-16/files/0032-lldb-Add-cstdio-include-to-fix-a595b931f1f91897317a4.patch
lang/llvm-16/files/0033-xray-Use-L-instead-of-.L-for-Mach-O.patch
lang/llvm-16/files/0034-builtins-Move-cfi-start-s-after-the-symbol-name-NFC.patch

This is a cherry-pick of:
https://github.com/llvm/llvm-project/commit/c57c7b7c99605021123b54c02e57943923874cbe https://github.com/llvm/llvm-project/commit/7939ce39dac0078fef7183d6198598b99c652c88
This enables clang-16 to be built by Xcode 16, making it possible to build on macOS 15, and macOS 14 with Xcode 16. It also enables clang-16 to be built by clang-18 and newer.
Have you
@cjones051073

clang-16, llvm-16: restore functionality on macOS 15 (Xcode 16)

---

multimedia/ffmpeg7/Portfile

add usage notes
macOS x.y
Have you

ffmpeg7: allow disabling bin symlinks and suffices

---

ruby/rb-gdk_pixbuf2/Portfile

This was missed somehow
macOS 10.6
Xcode 3.2
Have you

rb-gdk_pixbuf2: update to 4.2.4

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.546
Have you

ipsw: Update to 3.1.546

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.6.8
Have you

ruff: Update to 0.6.8

---

x11/xcircuit/Portfile

Forgotten revbump
macOS 10.6
Xcode 3.2
Have you

xcircuit: revbump after ghostscript update

---

devel/entityx/Portfile

entityx: set required C++11 standard

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.10
Have you

mise: Upgrade to 2024.9.10

---

print/libspectre/Portfile

Forgotten revbump
macOS 10.6
Xcode 3.2
Have you

libspectre: revbump after ghostscript update

---

graphics/xfig/Portfile

Fix
macOS 10.6
Xcode 3.2
Have you

xfig: needs legacysupport for strndup

---

perl/p5-object-pad/Portfile

Avoid archaic Xcode gcc.
macOS 10.6
Xcode 3.2
Have you

p5-object-pad: fix build on old macOS

---

perl/p5-test-simple/Portfile

* p5-module-pluggable is optional.  Remove it, fix dependency cycle.
* Add user note for optional dependency.
* Rev bump for dependency change.
* Closes: https://trac.macports.org/ticket/70547
macOS 14.6.1 23G93 Sonoma, x86_64
Xcode 15.4 / Command Line Tools 15.3.0
macOS 10.15.7 Macbookpro mid 2010 Intel i7 x86_64
Xcode 11.5 / Command Line Tools 11.5
Have you

p5-test-simple: Fix dependency cycle

---

python/py-graph-tool/Portfile

py-graph-tool: Update to version 2.77; Add Python 312

---

lang/llvm-15/Portfile
lang/llvm-15/files/0032-lldb-Add-cstdio-include-to-fix-a595b931f1f91897317a4.patch
lang/llvm-15/files/0033-xray-Use-L-instead-of-.L-for-Mach-O.patch
lang/llvm-15/files/0034-builtins-Move-cfi-start-s-after-the-symbol-name-NFC.patch

This is a cherry-pick of:
https://github.com/llvm/llvm-project/commit/c57c7b7c99605021123b54c02e57943923874cbe https://github.com/llvm/llvm-project/commit/7939ce39dac0078fef7183d6198598b99c652c88
This enables clang-15 to be built by Xcode 16, making it possible to build on macOS 15, and macOS 14 with Xcode 16. It also enables clang-15 to be built by clang-18 and newer.
Have you
@cjones051073

clang-15, llvm-15: restore functionality on macOS 15 (Xcode 16)

---

lang/guile-3.0/Portfile
lang/guile-3.0/files/0010-filesys.patch
lang/guile-3.0/files/0011-powerpc.patch

Guile 3.0.10 is still broken and Debian reverted to 3.0.9. Do the same until upstream fixes the regression.
macOS 10.6
Xcode 3.2
Have you

guile-3.0: use 3.0.9 on 32-bit archs until 3.0.10 regression is fixed

---

sysutils/bfs/Portfile

bfs: update to 4.0.2

---

lang/llvm-14/Portfile
lang/llvm-14/files/0032-lldb-Add-cstdio-include-to-fix-a595b931f1f91897317a4.patch
lang/llvm-14/files/0033-xray-Use-L-instead-of-.L-for-Mach-O.patch
lang/llvm-14/files/0034-builtins-Move-cfi-start-s-after-the-symbol-name-NFC.patch

This is a cherry-pick of:
https://github.com/llvm/llvm-project/commit/c57c7b7c99605021123b54c02e57943923874cbe https://github.com/llvm/llvm-project/commit/7939ce39dac0078fef7183d6198598b99c652c88
This enables clang-14 to be built by Xcode 16, making it possible to build on macOS 15, and macOS 14 with Xcode 16. It also enables clang-14 to be built by clang-18 and newer.
Have you
@cjones051073

clang-14, llvm-14: restore functionality on macOS 15 (Xcode 16)

---

science/ecCodes/Portfile

Simple upgrade to upstream version 2.38.0
Have you

ecCodes: update to 2.38.0

---

sysutils/fatsort/Portfile

Avoid old Xcode gcc
macOS 10.6
Xcode 3.2
Have you

fatsort: fix on old systems

---

lisp/cl-dissect/Portfile

Closes: https://trac.macports.org/ticket/70590
Fix this
macOS 10.6
Xcode 3.2
Have you

cl-dissect: update to 20240325, fixed build

---

python/py-gssapi/Portfile
python/py-gssapi/files/patch-c99.diff

Fix
macOS 10.6
Xcode 3.2
Have you

py-gssapi: fix build with Xcode gcc

---

ocaml/ocaml-dune/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ocaml-dune: update to 3.16.0

---

devel/openssl3/Portfile

Avoid building tests by default, move them to a variant.
Building tests takes forever on older hardware, and seems to cause troubles in VM builds.
macOS 10.6
Xcode 3.2
macOS 10.6.8
Xcode 3.2.6
Have you

openssl3: do not build tests by default

---

lang/llvm-16/Portfile
lang/llvm-17/Portfile
lang/llvm-18/Portfile
lang/llvm-19/Portfile
lang/llvm-devel/Portfile

The Portfiles for these llvm versions were mishandling `CMAKE_INSTALL_NAME_DIR` in `configure.pre_args-delete`, failing to delete the intended variable set by the _resources/port1.0/group/cmake-1.1.tcl port group because [the port group encloses the value in quotes](https://github.com/macports/macports-ports/blob/a69f475c8f10a886fec1c440a280fdb0cc11362a/_resources/port1.0/group/cmake-1.1.tcl#L236), but the Portfiles omitted the quotes.
`CMAKE_INSTALL_RPATH` was being mishandled in the same way, but because these Portfiles specify `cmake.install_rpath` as empty, [the port group does not set `CMAKE_INSTALL_RPATH` at all](https://github.com/macports/macports-ports/blob/a69f475c8f10a886fec1c440a280fdb0cc11362a/_resources/port1.0/group/cmake-1.1.tcl#L96), so the `configure.pre_args-delete` …

llvm-{16,17,18,19,devel}: fix cmake variable handling

---

sysutils/mise/Portfile

mise: Upgrade to 2024.9.11
Have you

mise: Upgrade to 2024.9.11

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.547
Have you

ipsw: Update to 3.1.547

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.17
Have you

uv: Update to 0.4.17

---

audio/libopenmpt/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libopenmpt: update to 0.7.10

---

irc/halloy/Portfile

This commit updates `halloy` to `2024.12`.
macOS 15.0, bleeding edge xcode
Have you

halloy: update to 2024.12

---

textproc/pandoc/Portfile

pandoc: update to v3.4
Have you

pandoc: update to v3.4

---

sysutils/mise/Portfile

mise: Update to 2024.9.12
Have you

mise: Update to 2024.9.12

---

python/py-pyproj/Portfile

Fix
macOS 10.6
Xcode 3.2
Have you

py-pyproj: fix build with Xcode gcc

---

python/py-shapely/Portfile
python/py-shapely/files/patch-setup.py.diff

Fix 
macOS 10.6
Xcode 3.2
Have you

py-shapely: update to 2.0.6, fix build on old systems

---

archivers/libzip/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libzip: update to 1.11.1

---

python/py-obspy/Portfile

Uses types redefinition, which is C11 feature.
macOS 10.6
Xcode 3.2
Have you

py-obspy: fix build on old systems

---

archivers/lunzip/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

lunzip: update to 1.14

---

graphics/shapelib/Portfile

Fix compiler choice after recent update
macOS 10.6
Xcode 3.2
Have you

shapelib: set required now C++ standard

---

devel/jam/Portfile
devel/jam/files/patch-jam.c.diff
devel/jam/files/patch-mkjambase.c.diff

building jam failes with quite recent XCode (at least 15 and 16) versions failed with message 
```
jam.c:169:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
mkjambase.c:27:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
```
so fixing these by adding the formerly used "int"  
Have you

jam: bugfix compatibility with ISO C99

---

graphics/argyll/Portfile

just replaced version and checksums for new version
(be aware: building on macos 15 requires a fixed jam (https://github.com/macports/macports-ports/pull/25988))
Have you

argyll: Update to 3.3.0

---

net/qpid-proton/Portfile
net/qpid-proton/files/patch-fix-macOS-build.diff

Update, hopefully fixes the build
macOS 10.6
Xcode 3.2
Have you

qpid-proton: update to 0.39.0

---

net/dynamips/Portfile

Fix build
macOS 10.6
Xcode 3.2
Have you

dynamips: fix build on old macOS

---

www/tenfourfox/Portfile
www/tenfourfox/files/0785667d630acf269af554f538c19da181e5253f.patch

Added Aquafox subport, a TenFourFox fork with extra optimizations, and updated tenfourfox-devel to the latest version 20240505.
macOS 10.6
Xcode 3.2
**Note:** Testing was conducted by @barracuda156.
Have you

tenfourfox: Add Aquafox subport and update tenfourfox-devel

---

cross/openocd/Portfile

Adds `remote_bitbang` variant to support building with Remote Bitbang JTAG driver.
Have you

openocd: add variant to enable Remote Bitbang jtag adapter

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.548
Have you

ipsw: Update to 3.1.548

---

devel/xeus-zmq/Portfile
devel/xeus/Portfile
devel/xproperty/Portfile
graphics/xvega/Portfile

xvega and friends: set cxx_standard 2017, remove the unnecessary dependency on xtl

---

lang/llvm-13/Portfile
lang/llvm-13/files/0028-lldb-Add-cstdio-include-to-fix-a595b931f1f91897317a4.patch
lang/llvm-13/files/0029-xray-Use-L-instead-of-.L-for-Mach-O.patch
lang/llvm-13/files/0030-builtins-Move-cfi-start-s-after-the-symbol-name-NFC.patch
lang/llvm-13/files/patch-xcode-15.diff

This rolls up backports of the following fixes for later llvm versions to llvm-13:
93df94134805 clang-14: Fix build under Xcode 15
2605e66ff779 lldb-14: fix build with macOS ≥ 14 SDK (Xcode ≥ 15)
aa0bc47391a7 clang-14: Move libc++*.* libraries to libc++ sub-dir, fix install names
49df5ce7f1f6 clang-14, llvm-14: restore functionality on macOS 15 (Xcode 16)
References: https://trac.macports.org/ticket/68257
This is mostly being done for aa0bc47391a7, which fixes a latent bug on any OS version. The easiest way for me to develop and test that fix was on macOS 15, hence the rest of the change.
@cjones051073
Have you

clang-13, llvm-13, lldb-13: fix for macOS ≥ 14

---

devel/expect/Portfile

This fixes a bug introduced in #25873 and reported here: https://lists.macports.org/pipermail/macports-users/2024-September/053033.html
macOS 15.1 24B5046f
Xcode 16.1 16B5014f 
Have you

expect: Fix install name for libexpect dylib

---

net/gallery-dl/Portfile

gallery-dl: update to 1.27.5
Have you

gallery-dl: update to 1.27.5

---

lang/llvm-13/Portfile

93df94134805 (as fixed by c04f7bf1e4b0) must be made to apply to flang-13 in addition to clang-13, because the sanitizer runtimes are built for both.
flang-mp-13 delegates to a bash wrapper script that uses modern bash-isms not supported by bash-3.2 shipped by Apple in /bin. A run-time dependency on the bash port is added, and the wrapper script is patched to use MacPorts’ bash as its interpreter rather than whatever happens to be first in the PATH.
@jmroot @ryandesign
This was requested by https://github.com/macports/macports-ports/commit/9e855c03657030f7cc3c85a41a89e09ae453be67#r147430250.
Have you

lldb-13, mlir-13, flang-13: enable on macOS ≥ 14

---

textproc/pandoc/Portfile

fixes: https://trac.macports.org/ticket/71002
Have you

pandoc: fixed x86 and arm64 checksums

---

lang/go/Portfile

During the last go [go version update](https://github.com/macports/macports-ports/commit/1978d33dc665858eb67ce79024ac671f3a9434fd), there's mismatch of rmd160 & file size checksums.
Have you

go: fix for mismatch rmd160/size

---

sysutils/oh-my-posh/Portfile

oh-my-posh: update to version 23.15.3

---

kde/marble/Portfile

[skip ci]
@reneeotten @herbygillot Skipping CI, since all KDE4 stuff broken on CI due to `raptor2` (nothing changed here).
This is needed, however, since it opportunistically links to `shapelib`, which was updated now, and that broke `marble`.
macOS 10.6
Xcode 3.2
Have you

marble: depend on shapelib, revbump

---

graphics/graphviz-devel/Portfile
graphics/graphviz/Portfile

The GNU flavor of sed is required only for guile variant, so add it into depends_build only there.
whatever CI tests on
Have you

graphviz{,-devel}: Depend on gsed only for guile variant.

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 495.0.0.
Have you

google-cloud-sdk: update to 495.0.0

---

python/py-makelive/Portfile

Update to MakeLive 0.6.2.
Have you

py-makelive: update to 0.6.2

---

editors/MacVim/Portfile
editors/vim/Portfile

See commits
macOS 10.6
Xcode 3.2
Have you

vim: fix build on old macOS; support ruby31

---

textproc/typst/Portfile
textproc/typst/files/patch-cargo.lock.diff

Rust 1.80+ contains some [breaking changes](https://github.com/rust-lang/rust/issues/127343) which break some crates, mostly `time` crate. This patch upgrades `time` crate because upstream does not fix it.
macOS 15.0 24A335 x86_64
Have you

typst: fix build on rust 1.80+

---

editors/bluefish/Portfile

bluefish: update to version 2.2.16
* Update version number
Also tested on Mountain Lion (10.8.5) x86_64
Have you

bluefish: update to version 2.2.16

---

devel/gh/Portfile

The executable patch to use legacy-support on <10.12 was using the wrong library file.  This fixes that.
Closes: https://trac.macports.org/ticket/70675
Also, 10.12 requires legacy-support for for utimensat(), so the threshold for using legacy-support is adjusted, which happens to make it apply to all cases where the precompiled binary is used.
There are, however, at least two other missing functions not currently provided by legacy-support, so this change doesn't actually make any new cases work.  See the ticket for details.
TESTED:
No longer gets the failures addressed by these fixes. Still has other issues on many older platforms.
```
Mac OS X …
```

gh: Fix legacy-support library usage

---

devel/icmake/Portfile
devel/icmake/files/exit.patch

icmake: Fix building icm-exec and exit if an error occurs
Closes: https://trac.macports.org/ticket/70874
Have you

icmake: Fix building icm-exec and exit if an error occurs

---

net/openconnect/Portfile

Use MacPorts python on old systems.
macOS 10.6
Xcode 3.2
Have you

openconnect: fix build on < 10.7

---

gis/JOSM/Portfile

josm: update to 19230

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.6.9
Have you

ruff: Update to 0.6.9

---

emulators/dosbox-x/Portfile

Update to dosbox-x v2024.10.01
macOS 13.7 22H123 arm64
Have you

dosbox-x: update to 2024.10.01

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.18
Have you

uv: Update to 0.4.18

---

devel/ghidra/Portfile

update java dependency to JDK21
Have you

ghidra: update to 11.2

---

lang/guile-3.0/Portfile

Commit b68c30c52be7790bbe795e5815e440464ddec0f0 removed libatomic_ops from dependencies of boehmgc, but did not bump revision on downstream consumer (guile-3.0).  So let us do the bump here.
Closes: https://trac.macports.org/ticket/71038
macOS N/A
Xcode N/a / Command Line Tools N/A
Have you

guile-3.0: Bump revision.

---

www/webarchiver/Portfile

In 2020, I inadvertly changed the epoch to 0; set it back to 1
I had to add a large amount of code to get this to compile on a newer
system.   All of them were taken from tickets or other portfiles.

webarchiver: update to 0.12

---

sysutils/resticprofile/Portfile

update resticprofile to 0.28.1
Have you

resticprofile: update to 0.28.1

---

games/openttd/Portfile

update to version 14.1
Have you

openttd: update to 14.1

---

graphics/shapelib/Portfile

shapelib: disable building test
Closes: https://trac.macports.org/ticket/71026
macOS x.y
Have you

shapelib: disable building test

---

comms/xlog/Portfile

xlog: update to version 2.0.25
* update version number
* update checksums
Have you

xlog: update to 2.0.25

---

devel/tree-sitter-magik/Portfile

A tree-sitter parser for Smallworld Magik
Have you

tree-sitter-magik: new port

---

java/jdk17-graalvm/Portfile

jdk17-graalvm: update minimum OS version

---

java/openjdk21-corretto/Portfile

openjdk21-corretto: update minimum OS version

---

java/openjdk21-zulu/Portfile

openjdk21-zulu: update minimum OS version

---

lang/llvm-15/Portfile
lang/llvm-16/Portfile
lang/llvm-17/Portfile
lang/llvm-18/Portfile

flang-to-external-fc-mp-{15–18} delegates to a bash wrapper script that uses modern bash-isms not supported by bash-3.2 shipped by Apple in /bin. A run-time dependency on the bash port is added, and the wrapper script is patched to use MacPorts’ bash as its interpreter rather than whatever happens to be first in the PATH.
flang-14 is being handled in #26039, and flang-13 was handled in c8ea54857743.
Have you

flang-{15–18}: depend on and use bash

---

java/openjdk21-temurin/Portfile

openjdk21-temurin: update minimum OS version

---

java/openjdk21-openj9/Portfile

openjdk21-openj9: update minimum OS version

---

java/openjdk17-openj9/Portfile

Correct the minimum OS version.
Have you

openjdk17-openj9: update minimum OS version

---

java/openjdk21-microsoft/Portfile

openjdk21-microsoft: update minimum OS version

---

java/openjdk21-graalvm/Portfile

openjdk21-graalvm: update minimum OS version

---

java/jdk21-graalvm/Portfile

jdk21-graalvm: update minimum OS version

---

java/openjdk21/Portfile

openjdk21: update minimum OS version

---

java/openjdk21/Portfile

Correct minimum OS version.
Have you

openjdk21: builds on macOS 11+

---

java/openjdk17/Portfile
java/openjdk17/files/JDK-8340341-clang-16-workaround.patch

Backport fix for https://trac.macports.org/ticket/70819 to OpenJDK 17.
Have you

openjdk17: fix build for clang 16

---

java/openjdk11/Portfile
java/openjdk11/files/JDK-8340341-clang-16-workaround.patch

Backport fix for https://trac.macports.org/ticket/70819 to OpenJDK 11.
Have you

openjdk11: fix build for clang 16

---

java/openjdk21/files/JDK-8340341-clang-16-workaround.patch

Update syntax of patch.
Have you

openjdk21: update patch syntax

---

java/openjdk17/files/JDK-8340341-clang-16-workaround.patch

Update syntax of patch.
Have you

openjdk17: update patch syntax

---

java/openjdk22/files/JDK-8340341-clang-16-workaround.patch

Update syntax of patch.
Have you

openjdk22: update patch syntax

---

java/openjdk23/files/JDK-8340341-clang-16-workaround.patch

Update syntax of patch.
Have you

openjdk23: update patch syntax

---

devel/pnpm/Portfile

Update PNPM to 9.12.0
Mach-o files for x86 files are present, but all distributions of pnpm include mach-o files for all architechtures. It can't be marked as universal because it depends on node, which doesn't have a universal varient.
Have you

PNPM: Update to 9.12.0

---

lang/pike/Portfile

I put some effort into trying to get this to build.
- the current portfile does not build, with or without postgresql.
- I tried to update pike as this is a long-outdated version. It seems upstream has redone their build system, the portfile likely needs to be rewritten/redesigned.
I am OK with just disabling the postgresql variant but there's a strong argument to be made here to just remove pike entirely until someone can redo the portfile and get it building again.
Have you

pike: remove postgresql variant

---

audio/xmms2/Portfile

1. Unbreak build with gcc and on < 10.7.
2. Prevent opportunistic linking to jack and pulseaudio: current variants do not do that.
macOS 10.6
Xcode 3.2
Have you

xmms2: fix the port

---

lang/llvm-14/Portfile

93df94134805 (as fixed by c04f7bf1e4b0) must be made to apply to flang-14 in addition to clang-14, because the sanitizer runtimes are built for both.
flang-mp-14 delegates to a bash wrapper script that uses modern bash-isms not supported by bash-3.2 shipped by Apple in /bin. A run-time dependency on the bash port is added, and the wrapper script is patched to use MacPorts’ bash as its interpreter rather than whatever happens to be first in the PATH.
Have you

flang-14: fix for macOS ≥ 14

---

lang/llvm-12/Portfile
lang/llvm-12/files/0028-lldb-Add-cstdio-include-to-fix-a595b931f1f91897317a4.patch
lang/llvm-12/files/0029-xray-allow-xray_trampoline_x86_64.S-to-build-with-Xc.patch
lang/llvm-12/files/0030-compiler-rt-Move-.cfi_start-after-the-symbol-label-d.patch
lang/llvm-12/files/patch-xcode-15.diff

This rolls up backports of the following fixes for later llvm versions to llvm-12:
93df94134805 clang-14: Fix build under Xcode 15
2605e66ff779 lldb-14: fix build with macOS ≥ 14 SDK (Xcode ≥ 15)
aa0bc47391a7 clang-14: Move libc++*.* libraries to libc++ sub-dir, fix install names
49df5ce7f1f6 clang-14, llvm-14: restore functionality on macOS 15 (Xcode 16)
References: https://trac.macports.org/ticket/68257
This is mostly being done for aa0bc47391a7, which fixes a latent bug on any OS version. The easiest way for me to develop and test that fix was on macOS 15, hence the rest of the change.
@cjones051073
Have you

clang-12, llvm-12, lldb-12: fix for macOS ≥ 14

---

sysutils/mise/Portfile

mise: Upgrade to 2024.10.1
Have you

mise: Upgrade to 2024.10.1

---

textproc/aha/Portfile

Adding new port for aha (Ansi HTML Adapter), which is a utility for converting ANSI escape sequences to HTML code. See more at https://github.com/theZiz/aha
Note: this is the first time I submit a new Portfile. While I have done my best to do it correctly and the file passes `port lint --nitpick`, it is probably a good idea to take an extra look at it.
Have you

aha: new port

---

java/micronaut/Portfile

Update to Micronaut Starter 4.6.3.
Have you

micronaut: update to 4.6.3

---

ruby/ruby-build/Portfile

ruby-build: Update to 20241007
Have you

ruby-build: Update to 20241007

---

devel/carthage/Portfile

Updates carthage to [0.40.0](https://github.com/Carthage/Carthage/releases/tag/0.40.0).
Have you

carthage: Update to 0.40.0

---

multimedia/VLC2/Portfile
multimedia/VLC2/files/backport-fixes.patch
multimedia/VLC2/files/patch-ffmpeg4-compat.diff
multimedia/avidemux/Portfile
multimedia/ffmpeg/Portfile
multimedia/ffmpeg6/Portfile
multimedia/ffmpeg7/Portfile
multimedia/x265/Portfile
multimedia/x265/files/patch-ppc.diff

1. Update x265, finally.
2. Revbump dependents.
3. Address a problem with FFMpeg which is pending for 5 years.
I do not revbump one completely broken port, it is pointless, and dropped `libheif` due to https://github.com/macports/macports-ports/pull/25265
I also do not include FFMpeg7 and -devel, since we rather merge https://github.com/macports/macports-ports/pull/25173 after this PR and avoid another rebuild.
macOS 10.6
Xcode 3.2
Have you

x265: update to 3.6; revbump dependents

---

multimedia/ffmpeg-devel/Portfile
multimedia/ffmpeg/Portfile
multimedia/ffmpeg6/Portfile
multimedia/ffmpeg7/Portfile

ffmpeg-devel: Enable webp 
ffmpeg7: Enable webp 
ffmpeg6: Enable webp 
ffmpeg: Enable webp and lzo2 
Closes: https://trac.macports.org/ticket/70958
Have you

ffmpeg*: Enable webp

---

devel/symfony-cli/Portfile

symfony-cli: update to 5.10.3

---

java/openjdk21/Portfile

After https://github.com/macports/macports-ports/pull/26116 was merged `openjdk21` should now build on macOS 10.12.0 and later.

openjdk21: should build on macOS 10.12.0+

---

aqua/LyX/Portfile

This is the last version in 2.3.x.  In 2.4 there are a lot of changes that are not trival to get it to build ATM.
See: https://trac.macports.org/ticket/70162
macOS x.y
Have you

LyX: update to 2.3.8

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 496.0.0.
Have you

google-cloud-sdk: update to 496.0.0

---

sysutils/stern/Portfile

Update to Stern 1.31.0.
Have you

stern: update to 1.31.0

---

devel/pnpm/Portfile

Update PNPM to 9.12.1
Mach-o files for all architechtures are included in all distributions. The port cannot be marked as Universal because it depends on Node, which does not have a universal varient.
Have you

PNPM: Update to 9.12.1

---

aqua/LyX/Portfile

We are ignoring expermental Qt6 ATM. Add other python versions.
Closes: https://trac.macports.org/ticket/70162
macOS x.y
Have you

LyX: update to 2.4.2 for Qt5; pin Qt4 at 2.3.8

---

editors/neovim/Portfile

`neovim`: update to 0.10.2:
- removed `lua51-mpack` as a dependency since it's [no longer required][0]
- removed `libtermkey` as a dependency since it's [no longer required][1]
[0]: https://github.com/neovim/neovim/pull/15566
[1]: https://github.com/neovim/neovim/pull/25870
`neovim-devel`: update to 20240831:
- removed `msgpack` as a dependency since it's [no longer required][2]
- removed `libvterm` as a dependency since it's [no longer required][3]
[2]: https://github.com/neovim/neovim/pull/29540
[3]: https://github.com/neovim/neovim/pull/30011
Also note that `neovim-devel` is not progressing past 2024-08-31 until `utf8proc` sees its next release. Versions after this date will fail with a compile error due to a type mismatch.
Fixes: https://trac.macports.org/ticket/70028
macOS 14.6.1 …

neovim, -devel: update to 0.10.2 and 20240831

---

python/py-autopage/Portfile
python/py-cliff/Portfile
python/py-cmd2/Portfile

`py-cliff` at its present version (4.4.0) misses the Python library Autopage. This PR adds the missing dependency (via the submission of the port `py-autopage`) and updates `py-cliff`.
Xcode 9.1 9B55
Have you

py-cliff: update to 4.7.0 and add missing dependency

---

devel/symfony-cli/Portfile

symfony-cli: update to 5.10.4

---

lang/kotlin/Portfile

Update to Kotlin 2.0.21.
Have you

kotlin: update to 2.0.21

---

gnome/gpodder/Portfile

Needed after https://github.com/macports/macports-ports/pull/26133
macOS x.y
Have you

gpodder: forgotten revbump

---

devel/asmotor/Portfile

Update `asmotor` to the latest released version 1.3.2.
Command Line Tools 15.3.0.0.1.1708487402
Have you

asmotor: update to 1.3.2

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.20
Have you

uv: Update to 0.4.20

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.549
Have you

ipsw: Update to 3.1.549

---

multimedia/QMPlay2/Portfile

At least on Sonoma pre-built app is broken: it fails to launch. Rebuilding fixes that.
Earlier versions may need to be revbumped, but I have no way to check it now.
macOS 14.7
Xcode 15.4
Have you

QMPlay2: revbump after dependencies update

---

graphics/ctpv/Portfile

ctpv fails to build on Leopard and Snow Leopard as the compiler blacklist does not cause MacPorts to use an appropriate compiler on these systems. Defining the C language standard required for building the port resolves the issue. #25798 previously attempted to address this.
Closes: https://trac.macports.org/ticket/70170
macOS 10.6.8 10K549 i386
Have you

ctpv: fix build on Leopard and Snow Leopard

---

net/lagrange/Portfile

https://github.com/skyjake/lagrange/releases
Xcode 14.2
Have you

lagrange: update to 1.18.3

---

sysutils/ntpsec/Portfile

Also removes redundant platforms line.
TESTED:
Built and ran tests with all variants on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-15.x arm64.  Successful except where pythonXY was unavailable or broken on the OS/CPU combination.
```
OS X 10.11.6 …
```

ntpsec: Add python313 variant.

---

python/py-serial/Portfile

TESTED:
Except where the underlying dependenciess are unavailable, built and ran "port test" on all subports on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-15.x arm64.  Also did a quick functional test of the new subport.
```
OS X 10.11.6 15G22010, …
```

py-serial: Add py313 subport.

---

net/gallery-dl/Portfile

gallery-dl: update to 1.27.6
Have you

gallery-dl: update to 1.27.6

---

games/sdl_sopwith/Portfile
games/sdl_sopwith/files/src_sdl_Makefile.in.patch

Per [comments from jmroot on previous PR](https://github.com/macports/macports-ports/commit/fbe25355e770c5a0748a6ac88e2b01fef93b7905#r147929525), added patch for CFLAGS include order in src/sdl/Makefile.in. This is a generated file, so a PR for upstream has already been reported and a fix landed in https://github.com/fragglet/sdl-sopwith/pull/45. 
This should be able to be discarded at next upstream release.
Also adopted port (was with nomaintainer, per guide 7.3.3, including openmaintainer as well).
Have you

sdl_sopwith: patch header include order, adopt

---

python/py-sniffio/Portfile

Bugfix: [fails](https://build.macports.org/builders/ports-13_x86_64-builder/builds/80286) to build without setuptools_scm:
```
[build-system]
requires = [
"setuptools >= 64",
"setuptools_scm >= 6.4"
]
```

py-sniffio: Add missing build dep (setuptools_scm)

---

java/jdk23/Portfile

Update to JDK 23.0.1.
Have you

jdk23: update to 23.0.1

---

java/jdk21/Portfile

Update to JDK 21.0.5.
Have you

jdk21: update to 21.0.5

---

java/jdk23-graalvm/Portfile

Update to GraalVM for JDK 23.0.1.
Have you

jdk23-graalvm: update to 23.0.1

---

python/py-pip/Portfile
python/py-pip/files/pip313

py-pip: add py313 subport

---

java/jdk21-graalvm/Portfile

Update to GraalVM for JDK 21.0.5.
Have you

jdk21-graalvm: update to 21.0.5

---

java/openjdk21-zulu/Portfile

Update to Azul Zulu 21.38.21 (OpenJDK 21.0.5).
Have you

openjdk21-zulu: update to 21.38.21

---

java/openjdk23-zulu/Portfile

Update to Azul Zulu 23.30.13 (OpenJDK 23.0.1).
Have you

openjdk23-zulu: update to 23.30.13

---

java/openjdk17-zulu/Portfile

Update to Azul Zulu 17.54.21 (OpenJDK 17.0.13).
Have you

openjdk17-zulu: update to 17.54.21

---

security/gitleaks/Portfile

gitleaks: Upgrade to 8.21.0
Have you

gitleaks: Upgrade to 8.21.0

---

java/openjdk11-zulu/Portfile

Open to Azul Zulu 11.76.21 (OpenJDK 11.0.25).
Have you

openjdk11-zulu: update to 11.76.21

---

java/openjdk8-zulu/Portfile

Update to Azul Zulu 8.82.0.21 (OpenJDK 8u432).
Have you

openjdk8-zulu: update to 8.82.0.21

---

java/openjdk21-corretto/Portfile

Update to Amazon Corretto 21.0.5.11.1 (OpenJDK 21.0.5).
Have you

openjdk21-corretto: update to 21.0.5.11.1

---

java/openjdk23-corretto/Portfile

Update to Amazon Corretto 23.0.1.8.1 (OpenJDK 23.0.1).
Have you

openjdk23-corretto: update to 23.0.1.8.1

---

java/openjdk17-corretto/Portfile

Update to Amazon Corretto 17.0.13.11.1 (OpenJDK 17.0.13).
Have you

openjdk17-corretto: update to 17.0.13.11.1

---

java/openjdk11-corretto/Portfile

Update to Amazon Corretto 11.0.25.9.1 (OpenJDK 11.0.25).
Have you

openjdk11-corretto: update to 11.0.25.9.1

---

java/openjdk8-corretto/Portfile

Update to Amazon Corretto 8.432.06.1 (OpenJDK 8u432).
Have you

openjdk8-corretto: update to 8.432.06.1

---

java/openjdk11-sap/Portfile

Update to SapMachine 11.0.25 (OpenJDK 11.0.25).
Have you

openjdk11-sap: update to 11.0.25

---

java/openjdk17-sap/Portfile

Update to SapMachine 17.0.13 (OpenJDK 17.0.13).
Have you

openjdk17-sap: update to 17.0.13

---

java/openjdk21-sap/Portfile

Update to SapMachine 21.0.5 (OpenJDK 21.0.5).
Have you

openjdk21-sap: update to 21.0.5

---

devel/ruff/Portfile
devel/uv/Portfile
security/ipsw/Portfile
sysutils/g-ls/Portfile
sysutils/ipatool/Portfile

Fix the fish completion destination for devel/ruff, devel/uv, security/ipsw, sysutils/g-ls, and sysutils/ipatool. Alll of these had been installing completions to `${destroot}${prefix}/share/fish/vendor_completion.d` but the correct destination is `${destroot}${prefix}/share/fish/vendor_completions.d`.
Tests had to be performed manually. I previously had `ruff` and `uv` installed and completions were not invoked. After installation with this change, completions were invoked. I do not use `ipsw`, `g-ls`, and `ipatool`, but have verified completions on them.
Have you

Various ports: Fix fish completion destination

---

java/openjdk23-sap/Portfile

Update to SapMachine 23.0.1 (OpenJDK 23.0.1).
Have you

openjdk23-sap: update to 23.0.1

---

devel/golangci-lint/Portfile

* update [golangci-lint](https://github.com/golangci/golangci-lint) to [v1.61.0](https://github.com/golangci/golangci-lint/releases/tag/v1.61.0)
Have you
```shell
port -vst install golangci-lint
--->  Cleaning golangci-lint
--->  Removing work directory for golangci-lint
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.
```
```shell
$ command -v golangci-lint
/opt/local/bin/golangci-lint
```
```shell
$ golangci-lint --help   
Smart, fast linters runner.
Usage:
golangci-lint [flags]
golangci-lint [command]
Available Commands:
cache       Cache control and information
completion  Generate the autocompletion script for the specified shell
config      Config
help        Help
linters     List …
```

golangci-lint: update to 1.61.0

---

devel/openssl3/Portfile
devel/openssl3/files/8e008cb8b23ec7dc75c45a66eeed09c815b11cd2.patch

```
a5ec7feb78e openssl3: Fix CVE-2024-9143
7b79a9ab880 openssl3: Fix livecheck
```
Have you

openssl3: Fix CVE-2024-9143, fix livecheck

---

devel/dagger/Portfile

Update to current version
Have you

dagger: update to 0.13.5

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.23
Have you

uv: Update to 0.4.23

---

python/py-awscli2/Portfile
python/py-awscli2/files/patch-requirements.diff
python/py-awscrt/Portfile

py-awscli2: update to 2.18.9

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.7.0
Have you

ruff: Update to 0.7.0

---

net/c-ares/Portfile

Resolves dependency cycle when curl is installed with +ares variant.
Closes: https://trac.macports.org/ticket/70910
Have you

c-ares: Use cmake-bootstrap instead of cmake

---

java/openjdk21-temurin/Portfile

Update to Eclipse Temurin 21.0.5 (OpenJDK 21.0.5).
Have you

openjdk21-temurin: update to 21.0.5

---

java/openjdk23-temurin/Portfile

Update to Eclipse Temurin 23.0.1 (OpenJDK 23.0.1).
Have you

openjdk23-temurin: update to 23.0.1

---

java/openjdk17-temurin/Portfile

Update to Eclipse Temurin 17.0.13 (OpenJDK 17.0.13).
Have you

openjdk17-temurin: update to 17.0.13

---

science/ngspice/Portfile

* Delete --enable-relpath
Closes: https://trac.macports.org/ticket/71124
macOS 15.0.1 24A348
Have you

ngspice: fix inability to find spinit file

---

multimedia/mat2/Portfile

bump mat2 default python version to 3.12
Have you

mat2: bump python from 3.11 to 3.12

---

python/py-bcrypt/Portfile

We don't have Rust on Darwin 8. We've already carved out an older version of py-bcrypt for PPC machines- this adds anything Darwin 8 to this group. 
macOS 10.4.11 8S2167 i386
Component versions: DevToolsCore-798.0; DevToolsSupport-794.0
Have you

py-bcrypt: Revert to older version on Tiger where Rust unavailable

---

x11/qt3/Portfile

The postgresql variant does not build with newer postgresqls so removing it.
I attempted to get the entire thing to compile and it does build on macOS 14! However, there are still enough problems I didn't want to push it all the way through. I left a comment on trac #57350 explaining what I did. However, that ticket is calling for qt3 to be removed anyway which seems sensible.
Have you

qt3: remove postgresql variant

---

devel/afl/Portfile
devel/afl/files/patch-allow-32-bit.diff

Fix this
macOS 10.6
Xcode 3.2
Have you

afl: unbreak for < 10.7

---

java/openjdk21/Portfile

Update to OpenJDK 21.0.5.
Have you

openjdk21: update to 21.0.5

---

java/openjdk17/Portfile

Update to OpenJDK 17.0.13.
Have you

openjdk17: update to 17.0.13

---

sysutils/yabai/Portfile
sysutils/yabai/files/patch-makefile.diff

update `yabai` to latest release.
Have you

yabai: update to 7.1.4

---

databases/timescaledb/Portfile

* convert variants to subports
* update to 2.16.1
Have you

timescaledb: convert variants to subports

---

science/nco/Portfile

Simple upgrade to upstream version 5.2.9
Have you

nco: update to 5.2.9

---

graphics/osxphotos/Portfile

Update to osxphotos 0.68.6.
Have you

osxphotos: update to 0.68.6

---

java/openjdk21-microsoft/Portfile

Update to Microsoft OpenJDK 21.0.5.
Have you

openjdk21-microsoft: update to 21.0.5

---

java/openjdk17-microsoft/Portfile

Update to Microsoft OpenJDK 17.0.13.
Have you

openjdk17-microsoft: update to 17.0.13

---

java/openjdk11-microsoft/Portfile

Update to Microsoft OpenJDK 11.0.25.
Have you

openjdk11-microsoft: update to 11.0.25

---

science/ecCodes/Portfile

Simple update in response to upstream's hot fix
Have you

ecCodes: update to 2.38.3

---

emulators/wine-devel/Portfile
emulators/wine-devel/files/1001-devel-msync.diff
emulators/wine-devel/files/1001-staging-msync.diff

wine-devel,wine-staging: Update to 9.20

---

sysutils/termscp/Portfile

https://github.com/veeso/termscp/releases
Xcode 14.2
Have you

termscp: update to 0.16.0

---

net/newsraft/Portfile

https://codeberg.org/newsraft/newsraft/releases/tag/newsraft-0.27
Xcode 14.2
Have you

newsraft: update to 0.27

---

net/mqttui/Portfile

https://github.com/EdJoPaTo/mqttui/releases/tag/v0.21.1
Xcode 14.2
Have you

mqttui: update to 0.21.1

---

java/openjdk11-temurin/Portfile

Refactor portfile and fix the platform.
Have you

openjdk11-temurin: use feature variable and fix platform

---

java/jdk17/Portfile

Oracle changed the license for Oracle JDK 17.0.13 and later in October 2024 and doesn't offer direct downloads for these versions, so this port cannot be updated anymore.
Noting in the description that users may want to use a different JDK 17 port instead.
I'm also switching this port to `nomaintainer`.
Have you

jdk17: note that version 17.0.13+ is not available via MacPorts

---

java/openjdk17-graalvm/Portfile

Note that GraalVM Community Edition 17 is no longer receiving upstream updates. Switching to `nomaintainer`.
Have you

openjdk17-graalvm: no longer supported

---

java/openjdk11-graalvm/Portfile

Note that GraalVM Community Edition 11 is no longer receiving upstream updates. Switching to `nomaintainer`.
Have you

openjdk11-graalvm: no longer supported

---

java/openjdk8-temurin/Portfile

Update to Eclipse Temurin 8u432 (OpenJDK 8u432).
Have you

openjdk8-temurin: update to 8u432

---

java/jdk17-graalvm/Portfile

Oracle changed the license for Oracle GraalVM for JDK 17.0.13 and later in October 2024 and doesn't offer direct downloads for these versions, so this port cannot be updated anymore.
Noting in the description that users may want to use a later GraalVM for JDK port instead.
I'm also switching this port to `nomaintainer`.
Have you

jdk17-graalvm: note that version 17.0.13+ is not available via MacPorts

---

java/openjdk11/Portfile

Update to OpenJDK 11.0.25.
Have you

openjdk11: update to 11.0.25

---

devel/uv/Portfile

Update `uv` to its latest released version
Have you

uv: Update to 0.4.25

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 498.0.0. Also downgraded Python dependency to 3.11, because `gsutil` is not compatible with Python 3.12 yet.
Have you

google-cloud-sdk: update to 498.0.0

---

java/openjdk17/Portfile
java/openjdk17/files/JDK-8340341-clang-16-workaround.patch
java/openjdk17/files/JDK-8342071-undecl-ident-nsbun-arm64-workaround.patch

Update patch comments with assigned bug ID's.
Have you

openjdk17: update patches

---

python/py-crcmod/Portfile

py-crcmod: add py313 subport, remove py38 subport

---

science/gwyddion/Portfile

Update of gwyddion to the actual version
Xcode 10.1 10B61 / Command Line Tools x.y.z
Have you

gwyddion: update to 2.66

---

erlang/elp/Portfile
erlang/eqwalizer/Portfile

Two ports (one commit per port, CI was confirmed to pass on the first commit):
- eqwalizer, a type checker for Erlang, written mainly in Scala
- elp (which uses eqwalizer), a language server and CLI tool for Erlang, written mainly in Rust
Have you

eqwalizer & elp: new ports

---

lang/erlang/Portfile
lang/erlang/files/patch-asmjit-dualmap.diff

Also fix support for JIT which was disabled by default by upstream on macOS/amd64 because of an annoying popup starting from Sonoma. Fix was eventually provided by asmjit and this is backported here as a patch.
Also fix a bug where tools such as epmd were not properly symlinked.
Have you

erlang: update to 27.1.2

---

sysutils/starship/Portfile

Update to Starship 1.21.1.
Have you

starship: update to 1.21.1

---

java/openjdk11-temurin/Portfile

Update to Eclipse Temurin 11.0.25 (OpenJDK 11.0.25).
Have you

openjdk11-temurin: update to 11.0.25

---

java/openjdk17-temurin/Portfile

Fix checksum for arm64.
Have you

openjdk17-temurin: fix checksum for arm64

---

science/gmtk/Portfile

Like in other similar cases, use wxGTK on old systems.
macOS 10.6
Xcode 3.2
Have you

gmtk: use wxGTK on < 10.8

---

java/openjdk21-temurin/Portfile

openjdk21-temurin: fix livecheck

---

java/openjdk17-temurin/Portfile

openjdk17-temurin: fix livecheck

---

java/openjdk23-temurin/Portfile

openjdk23-temurin: fix livecheck

---

devel/autoconf/Portfile
devel/libtool/Portfile

Closes: https://trac.macports.org/ticket/70673
Non-macOS-only:
Use MacPorts perl5 on non-Darwin systems.
Also it may need `help2man`.
Linux riscv64
Have you

autoconf: fix Linux build

---

editors/MacVim/Portfile
editors/vim/Portfile

* update Vim to v9.1.0727
* update MacVim to release-180
* add python312, python313, ruby32, and ruby33 variants for Vim and MacVim
* remove variants python36, python37, and python38 corresponding to EOL Python versions from Vim and MacVim
Have you
- n/a 
- Unable to run with trace-mode due to [#66356](https://trac.macports.org/ticket/66358)
- Tested functionality of Vim with +cscope, +huge, +python312, +python313, +tcl
- Tested build of Vim with +python27, +python39, +python310, python311, +ruby32, and +ruby33
- Tested functionality with MacVim with +cscope, +huge, +python312, +python313, +tcl
- Tested build of MacVim with +python27, +python39, +python310, python311, +ruby32, and +ruby33
- Vim patch  `patch-python.diff` and `patch-tcl.diff` …

vim, MacVim: update to vim version 9.1.0727

---

java/openjdk22-temurin/Portfile

openjdk22-temurin: fix livecheck

---

lang/swi-prolog/Portfile

swi-prolog: Updated to version 9.2.8

---

python/py-pyobjc/Portfile

Fix build of Quartz module by setting deployment target to macOS 14 (see [Sequoia Problems](https://trac.macports.org/wiki/SequoiaProblems)), because `CGWindowListCreateImageFromArray` is no longer available on macOS 15.
Have you

py-pyobjc: fix Quartz module on macOS 15

---

java/openjdk8-temurin/Portfile

openjdk8-temurin: fix livecheck

---

guile/guile-gnutls/Portfile

Guile gnutls

---

java/spring-boot-cli/Portfile

Update to Spring Boot CLI 3.3.5.
Have you

spring-boot-cli: update to 3.3.5

---

sysutils/tmux/Portfile

tmux added SIXEL support since 3.4, enable this feature during build.
https://github.com/tmux/tmux/blob/2df15ad08c9e4cf286cdb38cb645fc9066c3098d/CHANGES#L102
test method, build and open shell in tmux, install ImageMagick
```
convert /path/to/pic sixel:-
```
You should get a preview of the picture within tmux, if your terminal also support SIXEL images. (terminals including iTerm2, wezterm, etc)
macOS 12.7 21G816 arm64
Have you

tmux: enable sixel support

---

python/py-attrs/Portfile
python/py-hatch-fancy-pypi-readme/Portfile
python/py-hypothesis/Portfile
python/py-iniconfig/Portfile
python/py-parsing/Portfile
python/py-py/Portfile
python/py-pytest/Portfile
python/py-pytest/files/pytest313
python/py-sortedcontainers/Portfile
python/py-zope-event/Portfile
python/py-zopeinterface/Portfile

py-pytest: update to 7.4.4, add py313 subport (including dependencies)

---

sysutils/sketchybar/Portfile

update `sketchybar` to latest release.
Have you

sketchybar: update to 2.21.0

---

comms/tio/Portfile
comms/tio/files/patch-replace-send.diff

https://build.macports.org/builders/ports-15_x86_64-builder/builds/16687/steps/install-port/logs/stdio
Have you

tio: fix build on macOS Sequoia

---

python/py-param/Portfile

Upstream does not mention/use `py-numpy` and/or `py-pyobjc` as build dependencies.
Have you

py-param: remove unneeded build dependencies

---

net/miniflux/Portfile

miniflux: update to 2.2.1

---

gis/tippecanoe/Portfile

tippecanoe: update to 2.65.0

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.26
Have you

uv: Update to 0.4.26

---

www/kiln/Portfile

[kiln 0.4.1 announce](https://lists.sr.ht/~adnano/kiln-announce/%3CD16W9W04FD21.BO2PHV15E8YN@adnano.co%3E)
macOS 12.5.1
Xcode 13.4.1
Have you

kiln: update to 0.4.1

---

sysutils/simplotask/Portfile

https://github.com/umputun/spot/releases/tag/v1.16.1
Xcode 14.2
Have you

simplotask: update to 1.16.1

---

security/sequoia-sq/Portfile

sequoia-sq: new port, an OpenPGP implementation

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.554
Have you

ipsw: Update to 3.1.554

---

gis/GPXSee/Portfile

GPXSee: update to 13.26

---

devel/gitu/Portfile

Update `gitu` to its latest released version, 0.26.0
Have you

gitu: Update to 0.26.0

---

devel/ruff/Portfile

Update `ruf` to its latest released version, 0.7.1
Have you

ruff: Update to 0.7.1

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.27
Have you

uv: Update to 0.4.27

---

audio/cubeb/Portfile

See commits.
macOS 10.6.8
Xcode 3.2.6
Have you

cubeb: a few fixes to the port

---

audio/FAudio/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

FAudio: update to 24.10

---

multimedia/QMPlay2/Portfile

Move version threshold in a hope it fixes some pre-Catalina OS. (Also current one is duplicate after https://github.com/macports/macports-ports/commit/613d55e83fe738b77320937cd443a62b6841d69e commit.)
Not tested, but the change only concerns systems which currently fail anyway.
macOS x.y
Have you

QMPlay2: fix version threshold

---

science/libbiosig/Portfile

Fix for old systems
macOS 10.6
Xcode 3.2
Have you

libbiosig: fix build on < 10.7

---

graphics/MyPaint/Portfile
graphics/MyPaint/files/compatibiliby-newer-Python-versions.diff
graphics/libmypaint/Portfile

- use Python 3.12 for both ports (want to remove the `py38-numpy` subport in preparation for an update that uses the new `meson` backend) and this is the only straggler.
- `libmypaint` is missing a build dependency on `gettext` - at least I cannot get it to configure without
- `MyPaint` needs a backport of an upstream patch to allow newer Python versions due to deprecations in the Python standard library  
- tests for `libmypaint`, enabled in this PR, pass and `MyPaint` starts up correctly and I can do some drawing
Have you
There are a few Trac tickets for older OSes which I cannot check whether or not that is resolved by this PR.

libmypaint,MyPaint: use Python 3.12

---

devel/cpr/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

cpr: update to 1.11.0

---

security/libcotp/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libcotp: update to 3.1.0

---

security/s2n-tls/files/patch-fix-target-flags.diff

Patch fails to apply, since it was not rebased.
macOS 10.6
Xcode 3.2
Have you

s2n-tls: fix applying a patch after update

---

multimedia/libass/Portfile
multimedia/libass/files/6a759836e5e76bb7b69b0ac244eea76b0d290512.patch

Backport a fix, update -devel port.
macOS 10.6
Xcode 3.2
Have you

libass: backport fix from upstream; libass-devel: update to 2024.10.14

---

devel/pnpm/Portfile

MACH-O files for all architechtures in all distributions. The port can't be marked as Universal because it depends on Node, which doesn't have a universal variant
Have you

PNPM: Update to 9.1.12

---

devel/libimobiledevice-glue/Portfile
devel/libimobiledevice-glue/files/0001-socket.c-define-AI_NUMERICSERV-if-undefined.patch

Fix build on legacy OS
macOS 10.6
Xcode 3.2
Have you

libimobiledevice-glue: fix build when AI_NUMERICSERV undefined

---

devel/pika/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

pika: update to 0.29.0

---

python/py-gmpy2/Portfile

py-gmpy2: add py313 subport
Have you

py-gmpy2: add py313 subport

---

python/py-pylsqpack/Portfile
www/ls-qpack/Portfile

(There are a lot of those pragmas, so just use a modern compiler.)
macOS 10.6
Xcode 3.2
Have you

ls-qpack, py-pylsqpack: avoid old Xcode gcc

---

sysutils/bfs/Portfile
sysutils/bfs/files/515cda3e3763484af448ad1bc599d583eeeadb18.patch

Fix build on powerpc
macOS 10.6
Xcode 3.2
Have you

bfs: upstream fix for big-endian build

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 499.0.0.
Have you

google-cloud-sdk: update to 499.0.0

---

net/gallery-dl/Portfile

update to 1.27.7, make yt-dlp default
Have you

gallery-dl: update to 1.27.7, make yt-dlp default

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.28
Have you

uv: Update to 0.4.28

---

lang/lfortran/Portfile
lang/lfortran/files/8531580bd727a5b1ce4e7da2d0fe5f78460edfa4.patch
lang/lfortran/files/patch-use-sane-install-dirs.diff

Update
macOS 10.6
Xcode 3.2
Have you

lfortran: update to 0.41.0

---

multimedia/svt-av1/Portfile

svt-av1: disable AVX512 support by default, revbump

---

graphics/inkscape-textext/Portfile

* update to version 1.10.2
* add `openmaintainer`
Incremental upstream update to inkscape-textext. I just noticed that `typst` is now a supported backend. This port should be updated to support it, either by variants or by a user note.
Have you

inkscape-textext:  update to version 1.10.2

---

python/py-fastjsonschema/Portfile
python/py-filelock/Portfile
python/py-pkginfo/Portfile
python/py-platformdirs/Portfile
python/py-requests-toolbelt/Portfile
python/py-shellingham/Portfile
python/py-xattr/Portfile

For testing, I just did an `import foo` from the interpreter. That being said, I did review changelogs etc and this is all low risk.
Have you

Add python 3.13 subports for several packages

---

gis/qgis3/Portfile

Remove post-patch fix for an issue already addressed upstream for version 3.40.0, which after commit  https://github.com/macports/macports-ports/commit/d6053d2dd885aa1f9a4ffc482197454d95175c4f causes configuration failure on the build bots. (Interestingly, it worked without this fix both locally and on the CI runners.)
macOS x.y
Have you

qgis3: remove post-patch fix

---

_resources/port1.0/group/R-1.0.tcl
math/R/Portfile

If `R` is built with ccache enabled, then it will require ccache to build all its packages which have compilable code.
Avoid introducing this unwanted dependency.
macOS x.y
Have you

R: disable ccache, since R bakes in compiler value

---

ruby/ruby-build/Portfile

ruby-build: Update to 20241030
Have you

ruby-build: Update to 20241030

---

sysutils/colima/Portfile

Update to Colima 0.7.6.
Have you

colima: update to 0.7.6

---

multimedia/ffmpeg7/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ffmpeg7: update to 7.1

---

sysutils/cargo2port/Portfile

I don't use cargo2port very frequently, but I found myself yesterday being unable to use it the way I had before:
```sh
% cargo2port <(curl -s https://raw.githubusercontent.com/l2dy/cargo2port/refs/tags/0.3.0/Cargo.lock)|pbcopy
Error: cannot find file /dev/fd/12/Cargo.lock
```
So I updated to get the ability to read stdin.
Have you

cargo2port: update to 0.3.0

---

python/py-zipfile-deflate64/Portfile

py-zipfile-deflate64: add py313 subport, remove py38 subport

---

python/py-clang/Portfile

py-clang: Update to clang19

---

sysutils/mise/Portfile

mise: Update to 2024.11.0
Have you

mise: Update to 2024.11.0

---

audio/FAudio/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

FAudio: update to 24.11

---

math/cadabra2/Portfile

Some fixes for powerpc and libstdc++ systems.
macOS 10.6
Xcode 3.2
Have you

cadabra2: fix build on libstdc++ systems

---

python/py-tomlkit/Portfile

py-tomlkit: update to 0.13.2

---

devel/astyle/Portfile
devel/astyle/files/dont-force-stdlib.diff

astyle: update to 3.6.4

---

databases/timescaledb/Portfile

* fix conflict with subport
* fix license
Closes: https://trac.macports.org/ticket/71189
cc @barracuda156 @ryandesign 
Have you

timescaledb: fix conflict with subport

---

editors/emacs/Portfile

This is a weird one I think since I have chosen to specifically only update emacs-app-devel which also has differing compilation flags (native compilation is now default for example).
As and when Emacs 30 gets released I imagine the Portfile will get simpler, I've been using this general structure since August rebuilding from Emacs' master every other week or so.
Have you

emacs-app-devel: update to 20241021

---

erlang/atomvm/Portfile
erlang/atomvm/files/0001-otp_net.c-use-EAI_OVERFLOW-when-it-is-defined.patch

Fix
macOS 10.6
Xcode 3.2
Have you

atomvm: fix build on old systems

---

python/py-crashtest/Portfile

py-crashtest: add python 3.13 subport

---

audio/libopenmpt/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libopenmpt: update to 0.7.11

---

audio/libmysofa/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libmysofa: update to 1.3.3

---

graphics/xaos/Portfile

This just cleans up the portfile a bit by using `build.dir`. I wasn't able to find `build.dir` when I submitted the last update to this port, and had to resort to an uglier solution. No need for revision bump.
Have you

xaos: use `${build.dir}` for convenience

---

security/rage/Portfile

rage: update to 0.11.0

---

devel/isl-devel/Portfile

Update -devel subport.
macOS 10.6
Xcode 3.2
Have you

isl-devel: update to 0.27

---

ruby/ruby-build/Portfile

ruby-build: Update to 20241105
Have you

ruby-build: Update to 20241105

---

sysutils/mise/Portfile

mise: Update to 2024.11.1
Have you

mise: Update to 2024.11.1

---

audio/mpg123/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

mpg123: update to 1.32.9

---

python/py-rapidfuzz/Portfile

py-rapidfuzz: update to 3.10.1

---

python/py-click/Portfile

py-click: add py313 subport
Have you

py-click: add py313 subport

---

python/py-msgpack/Portfile
python/py-msgpack/files/patch-32-bit.diff

py-msgpack: update to 1.1.0

---

lang/squeak/Portfile

1. Unbreak destroot.
2. Remove `known_fail`, replace with version threshold.
3. Default to X11: `quartz` is already used here only on 32-bit archs, and on `ppc` it does not work, no point to keep these ridiculous macros for the sake of `i386`. Just use X11 everywhere by default.
macOS 10.6
Xcode 3.2
Have you

squeak: unbreak build on old systems

---

fuse/osxfuse/Portfile
fuse/osxfuse/files/patch-fix-valid-archs.diff

To test https://github.com/macports/macports-ports/pull/25953 in Rosetta I had to fix this first.
macOS 10.6.8 Rosetta
Xcode 3.2
Have you

osxfuse: fix build for powerpc

---

devel/gitu/Portfile

Update `gitu` to its latest released version, 0.27.0
Have you

gitu: Update to 0.27.0

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.4.30
Have you

uv: Update to 0.4.30

---

graphics/libfive/Portfile
graphics/libfive/files/patch-remove-march-native.diff
graphics/libfive/files/patch-use-macports-guile.diff

- Fixes build on recent macOS at the cost of breaking it on 10.14 and earlier
- Use Guile 3.0
- Add support for recent Python versions
- Use Python 3.12 by default
Closes https://trac.macports.org/ticket/63664
Have you

libfive: update to 20241103

---

security/tor-devel/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

tor-devel: update to 0.4.8.13

---

sysutils/mise/Portfile

mise: Update to 2024.11.3
Have you

mise: Update to 2024.11.3

---

python/py-dateutil/Portfile
python/py-dateutil/files/patch-setuptools_command_test_gone.diff
python/py-dateutil/files/patch-setuptools_scm_version.diff
python/py-dateutil/files/patch-test_no_pytest-cov.diff
python/py-freezegun/Portfile

py-dateutil: update to 2.9.0.post0, add py313 subport (including dependencies)

---

sysutils/mise/Portfile

mise: Update to 2024.11.4
Have you

mise: Update to 2024.11.4

---

_resources/port1.0/group/R-1.0.tcl
math/R/Portfile

* update to 4.4.2
* adjust accelarate variant to use BLAS and LAPACK libraries under the Accelerate framework that 'are [...] inline with reference version 3.9.1’ # see https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Accelerate-1
Have you

R: update to 4.4.2, adjust Accelerate variant

---

audio/libsidplayfp/Portfile
audio/sidplayfp/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libsidplayfp, sidplayfp: update to 2.11.0

---

devel/ghidra/Portfile

ghidra: update to 11.2.1
Have you

ghidra: update to 11.2.1

---

python/poetry/Portfile
python/py-cachecontrol/Portfile
python/py-cleo/Portfile
python/py-clikit/Portfile
python/py-filelock/Portfile
python/py-pastel/Portfile
python/py-poetry-plugin-export/Portfile
python/py-pylev/Portfile

-various Python ports maintained by @dgilman: remove EOL subports, update to latest version
Have you

various Python ports maintained by @dgilman: remove EOL subports, update to latest version

---

python/py-dulwich/Portfile
python/py-dulwich/files/eb6e78f01a44d738ca3c801d777785910aab5000.patch
python/py-dulwich/files/patch-strnlen-lion.diff

@dgilman This should fix the issue.
macOS 10.6
Xcode 3.2
Have you

py-dulwich: build pure version on legacy systems with no rust

---

python/py-lxml/Portfile

Have you
The checks are failing for py35-lxml and py36-lxml on macOS 14 and 15 because those builders are arm64, but python35 and python36 only build on x86_64. The macOS 13 builder is x86_64, and shows that py35-lxml and py36-lxml can be built, installed, and tested successfully on that architecture.

py-lxml: update to 5.3.0, add py313 subport

---

audio/cubeb/Portfile
audio/cubeb/files/patch-CMakeLists.diff

Closes: https://trac.macports.org/ticket/71197
@herbygillot Speex should be fine to just depend on, right? Builds everywhere, I guess.
macOS 10.6
Xcode 3.2
Have you

cubeb: fix linking, add variants

---

math/scalapack/Portfile

Update
_This can be merged now._
macOS 10.6
Xcode 3.2
Have you

scalapack: update to 2.2.1

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 500.0.0.
Have you

google-cloud-sdk: update to 500.0.0

---

python/py-msgpack/Portfile

Closes: https://trac.macports.org/ticket/71250
Python 3.12 itself already requires a modern compiler, so no hard blacklisting Xcode gcc (rather than patching in flags).
macOS 10.6
Xcode 3.2
Have you

py-msgpack: fix build on legacy systems

---

sysutils/colima/Portfile

Update to Colima 0.8.0.
Have you

colima: update to 0.8.0

---

python/py-numexpr/Portfile

Fix the build
macOS 10.6
Xcode 3.2
Have you

py-numexpr: fix build on legacy systems

---

python/py-blosc2/Portfile
python/py-blosc2/files/patch-gnu99.diff
python/py-scikit-build/Portfile
python/py-scikit-build/files/patch-fix-macOS-archs.diff

Fix the port for legacy systems
macOS 10.6
Xcode 3.2
Have you

py-blosc2: fix build on legacy systems and 32-bit archs

---

devel/google-cloud-sdk/Portfile

Note that the Python version should also be supported by `gsutil`.

google-cloud-sdk: update comment about Python version

---

python/py-numpy/Portfile

MacOS 13.2 was failed to build py-numpy.
This is because they try to use Accelerate variants though they cannot use it.
Fixed not to use Accelerate variatns on MacOS 13.2, 13.2.1
macOS x.y
Have you

py-numpy: fixed version filtering part

---

gis/JOSM/Portfile

josm: update to 19253

---

graphics/vtk/Portfile

* create `.dist-info` folder for python variants
* create appropriate contents (`LICENSE`, `METADATA`, `top_level.txt`)
Closes: https://trac.macports.org/ticket/71163
Having a `vtk-<version>.dist-info` folder in `.../site-packages`, with the appropriate installation files, informs Python's setuptools and pip that VTK with python wrappers is installed.
Have you

vtk: create .dist-info folder for python variants

---

textproc/libunistring/Portfile

Unbreak the build after the recent update
macOS 10.6
Xcode 3.2
Have you

libunistring: use gnulib PG to fix confdir bug

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.555
Have you

ipsw: Update to 3.1.555

---

x11/auto-multiple-choice/Portfile

Update auto-multiple-choice-devel.
Solve bug #943: https://project.auto-multiple-choice.net/issues/943
MacPort 2.10.4
Have you

auto-multiple-choice-devel : update to version 1.6.0-git20240805161640

---

gnome/gsettings-desktop-schemas/Portfile

See https://trac.macports.org/wiki/Python#VersionPolicy.
Have you

gsettings-desktop-schemas: Use Python 3.12

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.7.3
Have you

ruff: Update to 0.7.3

---

sysutils/mise/Portfile

mise: Update to 2024.11.5
Have you

mise: Update to 2024.11.5

---

devel/the_Foundation/Portfile

https://git.skyjake.fi/skyjake/the_Foundation/src/branch/main/CHANGES.md#1-9-1
Xcode 14.2
Have you

the_Foundation: update to 1.9.1

---

archivers/xar/Portfile

Don't try to use e2fsprogs. Fixes build failure when e2fsprogs is installed.
Closes: https://trac.macports.org/ticket/71270
Have you

xar: Don't try to use e2fsprogs

---

lang/groovy/Portfile

Update to Groovy 4.0.24.
Have you

groovy: update to 4.0.24

---

devel/openssl3/Portfile

It is not clear to me if revbump is needed, I also ask @jmroot to review it.
Have you

openssl3: use cctools only on macOS <10.7

---

lang/sbcl/Portfile
lang/sbcl/files/0004-fix-pthread-macOS.patch

Fix building 2.4.10 
macOS 10.6
Xcode 3.2
Have you

sbcl: fix including pthread in 2.4.10

---

graphics/d2/Portfile

d2: update to 0.6.8

---

science/gnuastro/Portfile

[Changelog](https://git.savannah.gnu.org/cgit/gnuastro.git/plain/NEWS?id=gnuastro_v0.23)
Xcode 14.2
Have you

gnuastro: update to 0.23

---

gis/tippecanoe/Portfile

tippecanoe: update to 2.68.0

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.556
Have you

ipsw: Update to 3.1.556

---

devel/hyprutils/Portfile
devel/hyprutils/files/d504d45114ad96cc143bcc2107529b2bf544f248.patch

Update
macOS 10.6
Xcode 3.2
Have you

hyprutils: update to 0.2.4

---

gis/GPXSee/Portfile

GPXSee: update to 13.27

---

sysutils/mise/Portfile

mise: Update to 2024.11.6
Have you

mise: Update to 2024.11.6

---

graphics/vtk/Portfile

[skip ci]
Skipping CI, since gcc is not used by default on any (in fact on any system from 10.6 up).
No need to revbump.
macOS 10.6
Xcode 3.2
Have you

vtk: minor fix only for gcc builds

---

graphics/gegl-devel/Portfile
graphics/gegl-devel/files/patch-fix-objc-flags.diff

Fixes: https://trac.macports.org/ticket/71257
@mascguy This fixes the issue.
macOS 10.6
Xcode 3.2
Have you

gegl-devel: unbreak build with gcc

---

sysutils/oh-my-posh/Portfile

update oh-my-posh to 24.2.2
Have you

oh-my-posh: update to 24.2.2

---

security/pidgin-otr/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

pidgin-otr: update to 4.0.2

---

math/z3/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

z3: update to 4.13.3

---

devel/libssh/Portfile
devel/libssh/files/patch-fix-includes.diff

Update
macOS 10.6
Xcode 3.2
Have you

libssh: update to 0.11.1

---

finance/hledger-iadd/Portfile
finance/hledger-iadd/files/stack.yaml.diff

Add [hledger-iadd](https://github.com/hpdeifel/hledger-iadd) 1.3.21 Portfile.
It is a terminal UI as drop-in replacement for [hledger](https://hledger.org/) add. 
Have you

hledger-iadd: new Portfile

---

python/py-pacal/Portfile

See https://trac.macports.org/ticket/71182

py-pacal: update to 1.6.1, drop python2, add python3

---

textproc/xercesc3/Portfile

- add openmaintainer
Closes: https://trac.macports.org/ticket/69018
Have you

xercesc3: update to 3.3.0

---

sysutils/mise/Portfile

mise: Update to 2024.11.8
Have you

mise: Update to 2024.11.8

---

python/py-pypdf/Portfile
python/py-pypdf/files/0001-TST-Add-missing-pytest.mark.samples-decorators-2940.patch

py-pypdf: add py313 subport, enable tests

---

devel/pika/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

pika: update to 0.30.0

---

archivers/unrar/Portfile
archivers/unrar/files/patch-dylib.diff
archivers/unrar/files/patch-makefile.unix.diff

* update patches to remove hunks
Have you

unrar: update to 7.1.1

---

www/hugo/Portfile

hugo: update to 0.138.0, add deploy variant
* adds new `deploy` variant which enables support for deploying site directly to Google Cloud Storage, AWS S3, or Azure Storage.
this feature was pulled out into its own, separate build tag as of upstream v0.137.0 and building without this feature (default) significantly reduces the final binary size.
* minor Portfile reformatting
Have you

hugo: update to 0.138.0, add deploy variant

---

textproc/ocrmypdf/Portfile

ocrmypdf: update to 16.6.1
Have you

ocrmypdf: update to 16.6.1

---

security/xml-security-c/Portfile

Requires revbump, since broken by xercesc3 update. Also add a minor fix along.
macOS 10.6
Xcode 3.2
Have you

xml-security-c: fix after xercesc3 update

---

editors/sigil-qt4/Portfile
editors/sigil-qt4/files/patch-sys_icache_invalidate.diff

Unbreak the port after `xercesc3` update
macOS x.y
Have you

sigil-qt4: revbump after xercesc3 update

---

x11/xorg-libXcursor/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

xorg-libXcursor: update to 1.2.3

---

finance/hledger/Portfile

Update hledger to 1.40
Have you

hledger: update to 1.40

---

devel/cmake-devel/Portfile

cmake-devel: update to 3.31.0

---

irc/weechat/Portfile

weechat: update to 4.4.3, update Python and Ruby variants
* remove variants for EOL ruby-3.0, python-3.8
* add variants for ruby-3.3, python-3.13
* Ruby variants: no longer need to set PKG_CONFIG_PATH, which was also interfering with Python's PKG_CONFIG_PATH if both a Ruby and Python variant was specified
* update maintainer email
Have you

weechat: update to 4.4.3, update Python and Ruby variants

---

devel/qd/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

qd: update to 2.3.24

---

sysutils/mise/Portfile

mise: Update to 2024.11.9
Have you

mise: Update to 2024.11.9

---

math/fplll/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fplll: update to 5.5.0

---

multimedia/youtube-viewer/Portfile

Closes: https://trac.macports.org/ticket/70452
Update, support GUI.
macOS 10.6
Xcode 3.2
Have you

youtube-viewer: update to 3.11.3, add gtk variant

---

gnome/gobject-introspection-devel/Portfile
gnome/gobject-introspection/Portfile

Verified to fix `malloc` errors with two dependents: gexiv2 and libcmatrix.
macOS 10.6
Xcode 3.2
Have you
@kencu @mascguy Please take a look.

gobject-introspection*: use legacysupport to fix malloc errors

---

gnome/gtk3-devel/Portfile
gnome/gtk3-devel/files/patch-sincos.diff
gnome/gtk3/Portfile
gnome/gtk3/files/patch-sincos.diff

Fixes build with gcc14
macOS 10.6
Xcode 3.2
Have you

gtk3, gtk3-devel: fix broken sincos check

---

lang/clisp/Portfile

1. Update.
2. On legacy systems avoid old Xcode gccs: they require c99, and clisp bakes in CC value as `/usr/bin/gcc-4.2 -std=gnu99`, which in turn breaks some dependents. We also do not want to be restricted by an archaic compiler. This change is confirmed to fix installation of `cl-osicat`.
macOS 10.6
Xcode 3.2
Have you

clisp: update to 2.50.0-20241112, fix legacy systems installation

---

math/HiGHS/Portfile

Simple update
macOS 10.6
Xcode 3.2
Have you

HiGHS: update to 1.8.1

---

math/eigen3/Portfile

Update
macOS 14.7
Xcode 15.4
Have you

eigen3-devel: update to 20241114

---

python/py-affine/Portfile
python/py-click-plugins/Portfile
python/py-cligj/Portfile
python/py-rasterio/Portfile
python/py-rasterio/files/patch-numpy_version.diff
python/py-snuggs/Portfile

This is an update to 1.3.11 instead of 1.4.2, as 1.4.2 requires numpy 2.
Have you

py-rasterio: update to 1.3.11, add py313 subport (including dependencies)

---

textproc/xercesc3/Portfile
textproc/xercesc3/files/ICUMsgLoader.cpp.patch

For version 3.3.0 it should be `_xercesc_messages_3_3_dat`.
Closes: https://trac.macports.org/ticket/71304
Ports that link with the library do not need another revbump, but after merging this PR we should schedule new builds of all those ports on the buildbot workers in case they had failed to build because of this problem.
Have you

xercesc3: Fix _xercesc_messages_3_2_dat symbol problem

---

devel/libgcrypt/Portfile

This fixes the build of gnupg2 in trace mode.
Closes: https://trac.macports.org/ticket/71317
Have you

libgcrypt: Avoid opportunistic use of ggrep

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.5.2
Have you

uv: Update to 0.5.2

---

security/ipsw/Portfile

Update `ipsw` to its latest released version, 3.1.557
Have you

ipsw: Update to 3.1.557

---

sysutils/edid-decode/Portfile

* update to version 20241012
Have you

edid-decode: update to version 20241012

---

python/py-blockdiag/Portfile
python/py-chardet/Portfile
python/py-fonttools/Portfile
python/py-fonttools/files/fonttools-313
python/py-fonttools/files/fonttools-38
python/py-funcparserlib/Portfile
python/py-gobject3/Portfile
python/py-matplotlib/Portfile
python/py-pyobjc/Portfile
python/py-reportlab/Portfile
python/py-sphinxcontrib-blockdiag/Portfile
python/py-unicodedata2/Portfile
python/py-webcolors/Portfile

- add py313 subport for `py-matplotlib`
- update a few dependencies to their latest versions
- update Python versions in subport (i.e., drop EOL)
Have you

py-matplotlib and all its (recursive) dependencies: add py313 subport

---

python/py-svgelements/Portfile
python/py-svgelements/files/0001-Fix-tests-by-fixing-typos.patch

py-svgelements: add py313 subport, enable tests

---

archivers/unrar/Portfile

The compiler choice gets wrong when ccache is active. Fix it.
macOS 10.6
Xcode 3.2
Have you

unrar: fix build when ccache is used

---

devel/libcmatrix/Portfile

No need to revbump, a minor fix to the build where it failed.
See: https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/290987/steps/install-port/logs/stdio
macOS x.y
Have you

libcmatrix: set C standard to fix compiler choice

---

lang/perl5/Portfile
lang/perl5/files/5.36/remove-deployment-target-override.diff
lang/perl5/files/5.38/remove-deployment-target-override.diff

closes: https://trac.macports.org/ticket/71152
see: https://trac.macports.org/ticket/71142
macOS 10.5 Intel
Have you
Note, this PR replaces the previous one -- I force-pushed against the previous PR while it was closed, and so it can't be reopened. 
This is a reasonable fix to get the newer perls working on 10.5 again. 
It was suggested the other 10 perls in macports should have the deployment target override removed from them too, and all be revbumped. Although it's true that the 10 perls prior to 5.36 are built with a forced deployment target of 10.3 on systems < 10.6, they have been working OK.

perl5.36/perl5.38: don't override deployment target

---

sysutils/mise/Portfile

mise: Update to 2024.11.13
Have you

mise: Update to 2024.11.13

---

java/micronaut/Portfile

Update to Micronaut Starter 4.7.0.
Have you

micronaut: update to 4.7.0

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.7.4
Have you

ruff: Update to 0.7.4

---

gis/tippecanoe/Portfile

tippecanoe: update to 2.70.0

---

sysutils/mise/Portfile

mise: Update to 2024.11.15
Have you

mise: Update to 2024.11.15

---

net/miniflux/Portfile

miniflux: update to 2.2.3

---

lang/fortran-stdlib/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

fortran-stdlib-devel: update to 2024.11.09

---

net/yewtube/Portfile
net/youtube-search-python/Portfile
python/py-pylast/Portfile
python/py-trio/Portfile
python/py-trio/files/0001-_socket.py-fix-for-systems-where-AI_NUMERICSERV-is-n.patch

See commits
macOS 10.6
Xcode 3.2
Have you

yewtube: new port, update dependencies

---

devel/jemalloc/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

jemalloc-devel: update to 2024.11.09

---

security/xmlsec/Portfile
security/xmlsec/files/patch-gcc4.diff

Fix the build with old compilers
macOS 10.6
Xcode 3.2
Have you

xmlsec: fix build with Xcode gcc

---

sysutils/clifm/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

clifm: update to 1.21

---

editors/turbo/Portfile

Update
macOS 10.6.8
Xcode 3.2.6
Have you

turbo: update to 2024.10.23

---

lang/llvm-12/Portfile
lang/llvm-13/Portfile
lang/llvm-14/Portfile
lang/llvm-15/Portfile
lang/llvm-16/Portfile
lang/llvm-17/Portfile
lang/llvm-18/Portfile
lang/llvm-19/Portfile
lang/llvm-devel/Portfile

Python was only specified as a build dependency, but for lldb, it’s actually a lib dependency. For example, after removing python310:
```
--->  Scanning binaries for linking errors
--->  Found 3 broken files, matching files to ports
--->  Found 3 broken ports, determining rebuild order
You can always run 'port rev-upgrade' again to fix errors.
The following ports will be rebuilt:
lldb-12 @12.0.1
lldb-13 @13.0.1
lldb-14 @14.0.6
```
```
% lldb-mp-12
dyld[…]: Library not loaded: /opt/local/Library/Frameworks/Python.framework/Versions/3.10/Python
Referenced from: <…> /opt/local/libexec/llvm-12/lib/liblldb.12.0.1.dylib
Reason: tried: '/opt/local/Library/Frameworks/Python.framework/Versions/3.10/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/Library/Frameworks/Python.fra …
```

lldb-{12…19,devel}: Python is a lib dependency

---

net/snac/Portfile

https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/249394/steps/install-port/logs/stdio
This does not happen where the newer Clang is used.
Have you

snac: blacklist clang < 1001

---

audio/audiowmark/Portfile
audio/libzita-resampler/Portfile

I don't actually have access to Apple Silicon machines, but CI successfully builds the code. Also added a check that these flags are not used on `+universal`.
Have you

libzita-resampler: build with NEON intrinsics on arm64, revbump

---

python/py-urwid/Portfile

Xcode 14.0 14A309
Have you
- [n/a] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [n/a] tested basic functionality of all binary files?
- [n/a] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

py-urwid: update to 2.6.16

---

databases/postgresql17-server/Portfile
databases/postgresql17/Portfile
databases/postgresql17/files/patch-fix-ppc-asm.diff
databases/postgresql17/files/patch-icu.diff

I expect this to build!
It must be merged after https://github.com/macports/macports-ports/pull/26042
Also see: https://github.com/macports/macports-ports/pull/24825
Have you

postgresql17: new port

---

devel/lazarus/Portfile

@kamischi Could you please take a look?
macOS 10.6
Xcode 3.2
Have you

lazarus: variants for GUI backends; allow building on powerpc

---

graphics/gimp3-devel/Portfile

* Bumped package version string to 3.0.0rc1 to match UI. (There doesn't seem to be a 3.0.0rc1 release branch, unless I'm missing something.)
* Build system switched to meson. Updated dependences and build options accordingly.
* Added more recent versions of python to variant selection. Removed obsolete Python 3.8.
* Added X11 variant for parity with other X11-or-Quartz packages. (This was also needed due to the meson change changing how the backend was specified at configure time.)
* Switched from hardcoded debug variant to standard PortGroup debug-1.0 variants.
* Removed +remote variant; gimp-remote has been removed.
* Removed some outdated patches and portfile rules.
Closes: https://trac.macports.org/ticket/71141
Note that there may still be extraneous dependencies (especially in X11 …

gimp3-devel: update to a recent commit

---

sysutils/mise/Portfile

mise: Update to 2024.11.16
Have you

mise: Update to 2024.11.16

---

java/openjdk21-openj9/Portfile

Update to IBM Semeru 21.0.5.
Have you

openjdk21-openj9: update to 21.0.5

---

multimedia/libheif/Portfile
multimedia/libheif/files/c5cba3186e7382abe6247317c888490493708edd.patch

Closes: https://trac.macports.org/ticket/71352
Fix the build.
Support `openh264`.
macOS 10.6
Xcode 3.2
Have you

libheif: backport upstream fix for 1.19.3; enable openh264

---

java/openjdk17-openj9/Portfile

Update to IBM Semeru 17.0.13.
Have you

openjdk17-openj9: update to 17.0.13

---

java/openjdk11-openj9/Portfile

Update to IBM Semeru 11.0.25.
Have you

openjdk11-openj9: update to 11.0.25

---

java/openjdk8-openj9/Portfile

Update to IBM Semeru 8u432.
Have you

openjdk8-openj9: update to 8u432

---

databases/postgresql17/files/patch-fix-ppc-asm.diff

Build fails since a patch has not been rebased. Fix that.
macOS 10.6
Xcode 3.2
Have you

postgresql17: rebase patch so that it applies successfully

---

sysutils/mise/Portfile

mise: Update to 2024.11.17
Have you

mise: Update to 2024.11.17

---

devel/google-cloud-sdk/Portfile

Update to Google Cloud SDK 502.0.0.
Have you

google-cloud-sdk: update to 502.0.0

---

textproc/ocrmypdf/Portfile

ocrmypdf: update to 16.6.2
Have you

ocrmypdf: update to 16.6.2

---

devel/kokkos/Portfile

Update -devel subport
macOS 10.6
Xcode 3.2
Have you

kokkos-devel: update to 2024.11.11

---

devel/qt5-qtcreator/Portfile
devel/qt5-qtcreator/files/patch-clang16_Wenum_constexpr_conversion.diff

Add a patch to fix a build error [-Wenum-constexpr-conversion] with clang v16 and later. This patch is already applied in qtcreator v10.0.2.
I tried to update qtcreator version to 11.0.3 (version 10 and below are archived), but it seems that it requires creating a new port with a new Portfile.
Here is a [track ticket 71319](https://trac.macports.org/ticket/71319) with this issue.
Have you

qt5-qtcreator: fix build with clang16+

---

devel/asio/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

asio: update to 1.32.0

---

java/google-java-format/Portfile

Update google-java-format to 1.24.
Fix build (previous solution did not work reliably when multiple JDK's are installed on the system).
macOS 15.1
Xcode 16.1
Have you

google-java-format: update to 1.24.0

---

sysutils/mise/Portfile

mise: Update to 2024.11.18
Have you

mise: Update to 2024.11.18

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.5.3
Have you

uv: Update to 0.5.3

---

www/hugo/Portfile

hugo: update to 0.139.0
Have you

hugo: update to 0.139.0

---

archivers/minizip-ng/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

minizip-ng: update to 4.0.7

---

perl/p5-imager/Portfile

New version fails to build without at least C99
macOS 10.6
Xcode 3.2
Have you

p5-imager: fix build with Xcode gcc after update

---

python/py-pyperclip/Portfile

Xcode 14.0 14A309
Have you
- [n/a] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [n/a] tested basic functionality of all binary files?
- [n/a] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?

py-pyperclip: update to 1.9.0

---

sysutils/mise/Portfile

mise: Update to 2024.11.19
Have you

mise: Update to 2024.11.19

---

devel/cpp-peglib/Portfile

update
macOS 10.6
Xcode 3.2
Have you

cpp-peglib: update to 1.9.1

---

devel/pika/Portfile

update
macOS 10.6
Xcode 3.2
Have you

pika: update to 0.30.1

---

java/spring-boot-cli/Portfile

Update to Spring Boot CLI 3.4.0.
Have you

spring-boot-cli: update to 3.4.0

---

databases/openldap/Portfile
databases/openldap/files/patch-soelim-name.diff

* Replace heavy port `groff` with lightweight `mandoc`.
* Needed only to build man pages using "soelim".
* Recursive dependencies for openldap reduced from 103 to 33.
* Part of the conversation in https://trac.macports.org/ticket/69601.
Have you

openldap: Reduce dependencies

---

databases/openldap/Portfile

* Bug fix for PR #26700.  Broke all builders for OS < 22.
* Command name change for "soelim" to "msoelim" must be inside OS >= 22 conditional.
CI only.  OS 13, 14 only.
Have you

openldap: New bug fix for all OS < 22

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.5.4
Have you

uv: Update to 0.5.4

---

audio/beets/Portfile
python/py-jellyfish/Portfile
python/py-py7zr/Portfile
python/py-pyppmd/Portfile
python/py-pyzstd/Portfile
python/py-pyzstd/files/patch-no-flto.diff

See commits.
Likely this is not gonna pass CI, since it requires a lot of ports, and uses python310.
macOS 10.6
Xcode 3.2
Have you

Beets: allow installing minimal version on legacy systems, fix dependencies

---

science/nco/Portfile

See: https://trac.macports.org/ticket/71310
This is to remove the linking with `xercesc3` now that it has been marked as deprecated.
In fact, `nco` was wrongly linked to `xercesc3` in the first place, since there was no code requiring it.
Its presence in the `Portfile` was a leftover of support for `esmf`, which was taken out of the port as deprecated over 2 years ago (#14756).
Have you

nco: Stop using xercesc3

---

java/micronaut/Portfile

Update to Micronaut 4.7.1.
Have you

micronaut: update to 4.7.1

---

sysutils/mise/Portfile

mise: Update to 2024.11.24
Have you

mise: Update to 2024.11.24

---

net/offpunk/Portfile
python/py-readability-lxml/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

offpunk: update to 2.4

---

python/py-numpy/Portfile

* move cython to depends_build
* drop obsolete depends fftw-3
Have you

py-numpy: modify depends cython and fftw-3

---

graphics/ImageMagick7/Portfile

imagemagick7: Normal update from 7.1.1-38 to 7.1.1-41
* Update
Have you

imagemagick7: Update to 7.1.1-41

---

devel/ruff/Portfile

Update `ruff` to its latest released version, 0.8.0
Have you

ruff: Update to 0.8.0

---

devel/gitlab-runner/Portfile

macOS 13.7.1 22H221 x86_64
Have you

gitlab-runner: Update to 17.5.1

---

games/rogue/Portfile
games/rogue/files/ncurses-compat-fix.patch

* increse the revision number missing from the previous commit
* correct wrong patch code
macOS x.y
Have you

rogue: increase revision number and correct wrong patch

---

science/ecCodes/Portfile

Simple update to upstream version 2.39.0
Have you

ecCodes: update to 2.39.0

---

devel/bun/Portfile

Bun: Update to 1.1.36

---

R/R-arrow/Portfile

Required revbump was not done, and the port is broken now.
macOS x.y
Have you

R-arrow: revbump to unbreak after apache-arrow update

---

math/eigen3/Portfile

Unfortunately, last update left `eigen3-devel` broken again, since turned out, the fix has not been backported into 3.4 branch. I have opened an issue for that: https://gitlab.com/libeigen/eigen/-/issues/2875
But in any case, -devel should rather track master, and master branch works correctly.
macOS 10.6
Xcode 3.2
Have you

eigen3-devel: update to 20241122

---

devel/pnpm/Portfile

MACH-O files for all architechtures are included in all distributions. It cannot be marked as Universal because it depends on node10, which doesn't have a Universal variant.
Have you

PNPM: Update to 9.14.2

---

sysutils/edid-decode/Portfile

* update to version 20241119
Have you

edid-decode: update to version 20241119

---

gis/qgis3/Portfile

Update:
-  `qgis3` to 3.40.1
-  `qgis3-ltr`  to 3.34.13
Have you

qgis3: update to 3.40.1

---

net/http_ping/Portfile
net/http_ping/files/makefile-support-macports-openssl3.diff

Update `http_ping` to its "latest released" version, released back in March 9, 2016. Much of this PR modernizes the Portfile (by using appropiate indentation, modline, and PortGroups)
One quirk I didn't fix was the `livecheck` method; it reports `09Mar2016` as being older than `29jun2005`.
Have you

http_ping: Update to 20160309

---

devel/libnick/Portfile
devel/maddy-parser/Portfile
gnome/blueprint-compiler/Portfile
net/parabolic/Portfile
net/parabolic/files/parabolic

A port for this library: https://github.com/NickvisionApps/libnick
It will allow to build some useful apps which depend on it.
macOS 14.7
Xcode 15.4
macOS 10.6
Xcode 3.2
Have you

libnick, parabolic: new ports and their deps

---

emulators/kegworks/Portfile

My own project that replaces my wineskin tail fork.

kegworks: new port

---

audio/ncmpcpp/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

ncmpcpp: update to 0.10.1

---

devel/hlint/Portfile

Fixes:
* https://trac.macports.org/ticket/71350
* https://github.com/ndmitchell/hlint/issues/1621
macOS x.y
Have you

hlint: Bugfix, remove --allow-newer dependencies

---

python/py-acor/Portfile

Add subport for new pythons.
macOS 10.6
Xcode 3.2
Have you

py-acor: add py312, py313 subports

---

multimedia/ffmpeg-devel/Portfile
multimedia/ffmpeg-devel/files/patch-add-pixeldensity.diff
multimedia/ffmpeg/Portfile
multimedia/ffmpeg/files/patch-add-pixeldensity.diff

sorry for the additional pull request, but i had to cleave out the nodejs patches and things were messy.
the comments to the patch files have been added.
the change does not affect people who do not have retina displays. you must invoke -movflags write_pixeldensity for the feature to have any effect.
as shown in the portfile comments, daniel kaiser has done all of the legwork but the ffmpeg team does not seem interested in adding the functionality. i did make a properly-formatted git patch for them and they seemed to not care.
Have you

add ffmpeg pixeldensity feature for retina displays

---

textproc/sgrep/Portfile

Update `sgrep` to its last released version, 1.94a. This PR serves to modernize the Portfile by using appropiate indentation and fixing building on Apple Sillicon.
Have you

sgrep: Update to 1.94a

---

sysutils/mise/Portfile

mise: Update to 2024.11.30
Have you

mise: Update to 2024.11.30

---

sysutils/lf/Portfile

Update `lf` to its latest released version, r33. The port note was changed for clarity.
Have you

lf: Update to 33

---

textproc/xmlto/Portfile

xsltproc, docbook-xml and docbook-xsl-nons are not just required at runtime (`depends_run`), but also at build time (i.e., they must be in `depends_build`).
Since xmlto does not care what architecture the xsltproc binary is and does not link against libxslt.dylib, add it to `depends_skip_archcheck`.
Have you

xmlto: Fix build in trace mode

---

games/packwiz/Portfile

packwiz: Update to 20241014

---

devel/bun/Portfile

bun: Update to 1.1.37

---

python/py-biopython/Portfile

Fix
macOS 10.6
Xcode 3.2
Have you

py-biopython: fix build on old systems

---

python/py-bigfloat/Portfile

FIx
macOS 10.6
Xcode 3.2
Have you

py-bigfloat: fix build with new pythons on old systems

---

sysutils/podman/Portfile

podman: Update to 5.3.1 & Fix checksums for pre-Monterey version

---

python/py-google-cloud-core/Portfile
python/py-google-cloud-storage/Portfile
python/py-google-crc32c/Portfile
python/py-google-resumable-media/Portfile
python/py-gsecrets/Portfile

New ports
macOS 14.7
Xcode 15.4
Have you

py-gsecrets and a few py-google* ports

---

audio/libopus/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

libopus: update to 1.5.2

---

databases/postgresql96/Portfile
databases/postgresql96/files/patch-xml_c.diff

Fixes:
* https://www.postgresql.org/message-id/attachment/152769/v1-0001-Make-PostgreSQL-work-with-newer-version-of-libxml.patch
* https://lists.macports.org/pipermail/macports-dev/2024-November/045952.html
macOS x.y
Have you

postgres96: Bugfix, Make PostgreSQL work with newer libxml2

---

databases/timescaledb/Portfile

* update to 2.17.2
* add postgresql17 support
* make it a stub port like py-foo
Have you

timescaledb: update to 2.17.2

---

python/py-pysimdjson/Portfile

New port
macOS 10.6
Xcode 3.2
Have you

py-pysimdjson: new port

---

science/hdf5/Portfile

Closes: https://trac.macports.org/ticket/67893
@eborisch A fix and revbump for non-MPI `libstdc++`-based systems, needed for hdf5, otherwise C++-using dependents fail to link.
`compiler.cxx_standard 2011` has no effect for any other systems, so revbump is specific. Also, MPI variant added the needed flag from its side, so no need to revbump it even for `libstdc++`.
macOS 10.6
Xcode 3.2
Have you

hdf5: fix non-MPI build on libstdc++ systems

---

multimedia/ffmpeg-devel/Portfile
multimedia/ffmpeg-devel/files/patch-libavdevice-avfoundation.diff

PR #25416 is stuck in moderation, however after testing #26520 this patch should be added to ffmpeg-devel.
I'll rebase it if #26775 is merged first.
Have you

ffmpeg-devel: fix compilation for OS X 10.7 through 10.12

---

textproc/pdfgrep/Portfile
textproc/pdfgrep/files/scandir.patch

Update `pdfgrep` to its latest released verison, 2.2.0. This update removes `pdfgrep-legacy`, since the obsolete date has passed.
Have you

pdfgrep: Update to 2.2.0

---

devel/cpp-argparse-dev/Portfile

* Add: Argument::deprecated support
* Add: ArgumentParser::deprecated support
Have you

cpp-argparse-dev: update to v1.9.5

---

audio/sox/Portfile

Revbump to fix 
macOS 10.6
Xcode 3.2
Have you

sox: revbump for libmad update

---

net/bind9/Portfile

bind9: Suppress strchr implicit func decl warning

---

audio/easytag/Portfile

Revbump
macOS 10.6
Xcode 3.2
Have you

easytag: revbump for libid3tag update

---

net/toxic/Portfile

Update
macOS 10.6
Xcode 3.2
Have you

toxic: update to 0.16.0

---

multimedia/ffmpeg7/Portfile
multimedia/ffmpeg7/files/patch-libavdevice-avfoundation.diff

Add patch that adds a type alias for OS X <= 10.12 from `AVMediaType` to `NSString*` (introduced in the 10.13 SDK, but with an extra specifier). I have submitted the same patch to ffmpeg. Before 10.13 these constants were declared directly as `NSString*`.
Have you

ffmpeg7: fix compilation for OS X 10.7 through 10.12

---

devel/uv/Portfile

Update `uv` to its latest released version, 0.5.5.
Have you

uv: Update to 0.5.5

---

audio/xmms2/Portfile

Revbump to fix the port
macOS x.y
Have you

xmms2: revbump for libmad update

---

audio/daapd/Portfile
audio/mt-daapd/Portfile
audio/shell-fm/Portfile

These ports are broken on modern systems, so skipping CI:
https://ports.macports.org/port/daapd/details
https://ports.macports.org/port/mt-daapd/details
https://ports.macports.org/port/shell-fm/details
However, they do build for me on 10.6, so it still makes sense to revbump them for the sake of old systems.
macOS 10.6
Xcode 3.2
Have you

shell-fm, mt-daapd, daapd: revbump for libmad

---

devel/symfony-cli/Portfile

symfony-cli: update to 5.10.5

---

sysutils/llama.cpp/Portfile

Fix the build
macOS 10.6
Xcode 3.2
Have you

llama.cpp: fix build on < 10.12

---

devel/micropython/Portfile

https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/296234/steps/install-port/logs/stdio
Have you

micropython: blacklist clang < 700
