net/abaddon/Portfile
Closes: https://trac.macports.org/ticket/71283
Fix deps
macOS 10.6
Xcode 3.2
Have you
=> abaddon: depend on mdebtls3, revbump

sysutils/caps-log/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> caps-log: update to 1.1.0

math/pspp-devel/Portfile, office/spread-sheet-widget/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> pspp-devel: update to 2.0.1-g395ff8

python/py-rich/Portfile, python/py-rich_rst/Portfile, python/py-textual/Portfile, sysutils/rich-cli/Portfile
New port: https://github.com/Textualize/rich-cli
Updates
macOS 14.7
Xcode 15.4
macOS 10.6
Xcode 3.2
Have you
=> rich-cli: new port; update its python deps

editors/step-writer/Portfile, editors/step-writer/files/patch-CMakeLists.diff
New port: another app using `FTXUI` library.
macOS 10.6
Xcode 3.2
macOS 14.7
Xcode 15.4
Have you
=> step-writer: new port in editors

www/catgirl-downloader/Portfile
Update
macOS 14.7
Xcode 15.4
Have you
=> catgirl-downloader: update to 0.2.7

sysutils/caps-log/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> caps-log: update to 1.2.0

net/gajim/Portfile, python/py-nbxmpp/Portfile, python/py-precis-i18n/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> gajim: update to 1.9.5

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.5.2

devel/qbs/Portfile
=> qbs: Update to 2.4.2

multimedia/openh264/Portfile, multimedia/openh264/files/0001-meson.build-add-powerpc-arch.patch, multimedia/openh264/files/0002-meson.build-do-not-hardcode-libc-on-darwin.patch
New port
macOS 10.6
Xcode 3.2
Have you
=> openh264: new port in multimedia

_resources/port1.0/group/common_lisp-1.0.tcl, lisp/cl-com.inuoe.jzon/Portfile, lisp/cl-idna/Portfile, lisp/cl-ironclad/Portfile, lisp/cl-osicat/Portfile, lisp/cl-slynk/Portfile
See commits
macOS 10.6
Xcode 3.2
Have you
P. S. On old systems `cl-osicat` besides patches also needs this: https://github.com/macports/macports-ports/pull/26571
However, merging these PRs are independent.
=> lisp: fix several packages for legacy systems, close tickets; minor fix to common_lisp PG

net/cgmnlm/Portfile, net/cgmnlm/files/patch-config.sh.diff, net/cgmnlm/files/patch-legacy.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> cgmnlm: update to 1.8

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.15

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.6.4

graphics/asymptote/Portfile, graphics/asymptote/files/2696886e8fbd49af2ca113fdb29b46169366f58b.patch, graphics/asymptote/files/cbbcfd2335a02654acd333f5ff89302586960720.patch
Update
macOS 10.6
Xcode 3.2
Have you
=> asymptote: update to 2.94

math/superlu_dist/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> superlu_dist: update to 9.1.0

lang/camlp5/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> camlp5: update to 8.03.01

science/imager/Portfile
=> imager: v4.0-02 (apr24) update site_base link value sdrive cnrs

graphics/geeqie/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> geeqie: update to 2.5

python/py-awscli2/Portfile
=> py-awscli2: update to 2.22.1

gnome/gstreamer1-gst-libav/Portfile, gnome/gstreamer1-gst-plugins-bad/Portfile, gnome/gstreamer1-gst-plugins-base/Portfile, gnome/gstreamer1-gst-plugins-good/Portfile, gnome/gstreamer1-gst-plugins-ugly/Portfile, gnome/gstreamer1/Portfile, gnome/gstreamer1/files/0001-Revert-macos-Fix-gst_macos_main-terminating-whole-pr.patch
Updates
macOS 10.6
Xcode 3.2
Have you
=> gstreamer1*: update to 1.24.9

python/py-pytest/Portfile
Hello, this is my first attempt at a PR for MacPorts.  Think I have followed the right procedure, apologies in advance if I have missed something or am stepping on toes.
Xcode 14.0 14A309
Have you
- [n/a] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message? 
- [n/a] checked that the Portfile's most important [variants](https://trac.macports.org/wiki/Variants) haven't been broken?
=> py-pytest: update to 8.3.3

net/snac/Portfile
=> snac: update to 2.64

math/fxt/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> fxt: update to 2024.11.16

erlang/elp/Portfile
=> elp: upgrade to 2024-11-07

ocaml/ocaml-angstrom/Portfile
=> ocaml-angstrom: upgrade to 0.16.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.8.0

games/rogue/Portfile, games/rogue/files/ncurses-compat-fix.patch
* add patch for build errors and warnings
* add sha256, rmd160 checksum to Portfile
* remove sha1, md5 checksum
Closes: https://trac.macports.org/ticket/70909
Have you
=> rogue: solve build error on Sequoia

devel/cpr/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> cpr: update to 1.11.1

fortran/forgex-cli/Portfile, fortran/forgex/Portfile
New port in Fortran
macOS 10.6
Xcode 3.2
Have you
=> forgex: new port in fortran

audio/xmms2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> xmms2: update to 0.9.5

python/py-cog/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-cog: update to 3.4.1

net/ngtcp2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ngtcp2: update to 1.9.1

graphics/imlib2/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> imlib2: update to 1.12.3

python/py-marshmallow/Portfile, python/py-webargs/Portfile
New ports
macOS 10.6
Xcode 3.2
Have you
=> py-marshmallow, py-webargs: new port

python/py-clikit/Portfile, python/py-pastel/Portfile, python/py-pylev/Portfile
Support new pythons
macOS 10.6
Xcode 3.2
Have you
=> py-clikit, py-pastel, py-pylev: support modern pythons

python/py-coloredlogs/Portfile, python/py-humanfriendly/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> py-coloredlogs: update to 15.0.1; py-humanfriendly: update to 10.0

audio/rsgain/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> rsgain: update to 3.5.3

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.10.1

security/blake3/Portfile
Update Blake 3 to version 1.5.5
Have you
=> blake3: update to 1.5.5

editors/em/Portfile
=> submission em: new port in editors

net/snac/Portfile
=> snac: update to 2.65

emulators/uxn/Portfile
=> uxn: update to 20241127

shells/tcsh/Portfile
=> tcsh: update to 6.24.14

multimedia/avidemux/Portfile
Revbump to fix the port
macOS x.y
Have you
=> avidemux: revbump for libmad update

devel/got/Portfile
=> got: update to 0.106

gnome/secrets/Portfile, gnome/secrets/files/patch-find-right-python.diff, python/py-kcs11/Portfile, python/py-kcs11/files/patch-fix-swig.diff, python/py-pykeepass/Portfile, python/py-validators/Portfile, python/py-yubico/Portfile, python/py-zxcvbn/Portfile
Gnome password manager
macOS 14.7
Xcode 15.4
macOS 10.8.5
Xcode 5.1
UPD. On Sonoma and 10.8 the app works.
On 10.6 everything builds, but I got a crash on launch. I will address that if solution is found, but not a stopper anyway.
Have you
=> secrets: new app in gnome

sysutils/tree/Portfile
=> tree: update to 2.2.0

net/libstrophe/Portfile, net/profanity/Portfile, net/profanity/files/patch-configure.ac.diff
Update
macOS 10.6
Xcode 3.2
Have you
=> libstrophe: update to 0.13.1; profanity: update to 0.14.0

devel/git-lfs/Portfile
=> git-lfs: 3.6.0, switch to ruby 3.3

sysutils/llama.cpp/Portfile
=> llama.cpp: submission

science/elmerfem/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> elmerfem: update to 2024.11.29

audio/qmmp/Portfile
Update/revbump
macOS x.y
Have you
=> qmmp: update to 1.6.9 for qt5; revbump for qt4 for libmad

sysutils/initool/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> initool: update to 1.0.0

lang/ruby32/Portfile, lang/ruby32/files/patch-sources.diff, lang/ruby33/Portfile, lang/ruby33/files/patch-sources.diff
```
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H15, x86_64, Xcode 12.4 12D4e
macOS 11.7.10 20G1427, …
```
=> ruby3[23]: update to 3.x.6

devel/bun/Portfile
=> bun: update to 1.1.38

textproc/hindent/Portfile
=> hindent: Submission

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.16

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.11.4

python/py-momepy/Portfile, python/py-pointpats/Portfile, python/py-segregation/Portfile, python/py-spreg/Portfile, python/py-tobler/Portfile
Updates:
- py-tobler: update to 0.12.0
- py-pointpats: update to 2.5.1
- py-segregation: update to 2.5.1
- py-spreg: update to 1.8.1
- py-tobler: update to 0.12.0
macOS x.y
Have you
=> PYSAL python ports updates

lang/algol68g/Portfile
Update, drop maintainership
macOS 10.6
Xcode 3.2
Have you
=> algol68g: update to 3.5.10, drop maintainership

math/ensmallen/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ensmallen: update to 2.22.0, remove myself from maintainers

net/yggdrasil-go/Portfile
=> yggdrasil-go: update to 0.5.10

python/py-awscli2/Portfile
=> py-awscli2: update to 2.22.12

science/imager/Portfile
=> imager: update to v4.4-01 (dec24)

math/libqalculate/Portfile, math/qalculate-gtk/Portfile, math/qalculate-qt/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libqalculate and friends: update to 5.4.0

devel/epoll-shim/Portfile, devel/epoll-shim/files/0001-Use-EV_TRIGGER-as-a-fallback-for-NOTE_TRIGGER.patch, devel/epoll-shim/files/0002-Define-MSG_NOSIGNAL-when-undefined.patch, devel/epoll-shim/files/0003-timerfd-root-test-skip-on-macOS-10.12.patch, devel/wayland/Portfile, devel/wayland/files/0001-Darwin-fixes-from-owl-compositor.patch, devel/wayland/files/0002-wayland-os.c-LOCAL_PEERPID-may-not-be-defined.patch, devel/wayland/files/0003-os-wrappers-test-F_DUPFD_CLOEXEC-may-not-be-defined.patch
New port
macOS 10.6
Xcode 3.2
Have you
=> epoll-shim, wayland: new ports in devel

devel/pnpm/Portfile
=> pnpm: update to 9.14.4

gis/tippecanoe/Portfile, gis/tippecanoe/files/0001-mbtiles.cpp-isinf-to-std-isinf.patch
Update, fix
macOS 10.6
Xcode 3.2
Have you
=> tippecanoe: update to 2.71.0, set needed C++17, fix 32-bit

security/sequoia-sq/Portfile
=> sequoia-sq: Update to 0.40.0

python/py-pdfminer/Portfile
=> py-pdfminer: 20240706

gis/pgrouting/Portfile, gis/saga/Portfile
- pgrouting: update to 3.7.0
- saga: update to 9.6.2
Have you
=> saga, pgrouting: updates

python/py-annoy/Portfile, python/py-pacmap/Portfile
=> py-pacmap, py-annoy: Submission

ocaml/ocaml-js_of_ocaml/Portfile, ocaml/ocaml-sedlex/Portfile
And drop maintainership
macOS 10.6
Xcode 3.2
Have you
=> ocaml-js_of_ocaml*: update to 5.9.1; ocaml-sedlex: update to 3.3

net/nfdump/Portfile
Closes: https://trac.macports.org/ticket/71465
Update and fix
macOS 10.6
Xcode 3.2
Have you
=> nfdump: update to 1.7.5, fix build

devel/libsdl2-powerpc/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: update to 2.30.10

python/py-XlsxWriter/Portfile, python/py-pptx/Portfile
=> py-xlsxwriter/py-pptx: Add 3.13 versions

sysutils/coreutils-uutils/Portfile
=> coreutils-uutils: update to 0.0.28

devel/rapidjson-devel/Portfile
Upd
macOS 10.6
Xcode 3.2
Have you
=> rapidjson-devel: update to 20241202, drop maintainership

science/madness/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> madness: update to 2024.12.06

databases/postgresql16-server/Portfile, databases/postgresql16/Portfile
=> postgresql16: update to 16.6

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.12.0

lang/py-htmldocs/Portfile
=> py-htmldocs: latest for 3.10,11,12,13

ocaml/ocaml-utop/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ocaml-utop: update to 2.15.0

gis/pdal/Portfile, python/py-pdal-plugins/Portfile
- pdal: update to 2.8.2
- py-pdal-plugins: update to 1.6.2
Have you
=> pdal, py-pdal-plugins: updates

devel/flickcurl/Portfile, devel/flickcurl/files/001-use-stdlib-h.patch
=> flickcurl: fix stdlib usage

math/ensmallen/Portfile, math/mlpack/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> ensmallen: update to 2.22.1; mlpack: update to 4.5.1

lang/castxml/Portfile
castxml: update to 0.6.10
macOS x.y
Have you
=> castxml: update to 0.6.10

net/zmap/Portfile
=> zmap: update to 4.3.1

net/snac/Portfile
=> snac: update to 2.66

databases/postgresql15-doc/Portfile, databases/postgresql15-server/Portfile, databases/postgresql15/Portfile
=> postgresql15: update to 15.10

databases/postgresql14-doc/Portfile, databases/postgresql14-server/Portfile, databases/postgresql14/Portfile
=> postgresql14: update to 14.15

databases/postgresql12-doc/Portfile, databases/postgresql12-server/Portfile, databases/postgresql12/Portfile
=> postgresql12: update to 12.22

mail/mu/Portfile
Update, fix broken build
macOS 10.6
Xcode 3.2
Have you
=> mu: update to 1.12.7, fix build

math/dbcsr/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> dbcsr: update to 2.8.0

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.22.16

ocaml/ocaml-ocamlformat/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ocaml-ocamlformat: update to 0.27.0, drop maintainership

ocaml/ocaml-ptime/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ocaml-ptime: update to 1.2.0, drop maintainership

net/yggdrasil-go/Portfile
=> yggdrasil-go: update to 0.5.11

python/py-ruamel-yaml-clib/Portfile
=> py-ruamel-yaml-clib: update to 0.2.12

databases/pgbadger/Portfile
=> pgbadger: update to 13.0

devel/flamegraph/Portfile
=> flamegraph: update to 2024.10.20

math/ginkgo/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> ginkgo: update to 1.9.0

devel/hyprlang/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> hyprlang: update to 0.6.0, drop maintainership

sysutils/chrony/Portfile
=> chrony: update to 4.6.1

multimedia/scrcpy/Portfile
* Update to version 3.1
Command Line Tools 8.2.0.0.1.1480973914
Have you
=> scrcpy: Update to version 3.1

net/utdns/Portfile, net/utdns/files/patch-configure.ac.diff
New port
macOS 10.6
Xcode 3.2
Have you
=> utdns: new port in net

gis/kealib/Portfile, gis/rsgislib/Portfile
Update `kealib` to 1.6.0.
macOS x.y
Have you
=> kealib: update to 1.6.0

devel/eask-cli/Portfile
=> eask-cli: update to 0.10.2

security/sequoia-sq/Portfile
=> sequoia-sq: Update to 1.0.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.15.1

lang/logtalk/Portfile
=> logtalk: update to 3.86.0

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.17

lang/swi-prolog/Portfile
=> swi-prolog: Updated to version 9.2.9

R/R-GeneralizedWendland/Portfile, R/R-GeneralizedWendland/files/patch-fix-prefix.diff, R/R-PoissonMultinomial/Portfile, R/R-PoissonMultinomial/files/patch-fix-prefix.diff, R/R-bnpmr/Portfile, R/R-bnpmr/files/patch-fix-prefix.diff
Ensure correct linking.
Related: https://trac.macports.org/ticket/71583
@kencu Example of the issue. As you can see, nothing about compilers or _my_ compilers. Just authors of these packages decided that everyone on Earth must have `gsl` and friends in Homebrew prefix.
macOS 10.6
Xcode 3.2
Have you
=> R: fix linking in three packages

perl/p5-opengl/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
=> p5-opengl: fix build with gcc

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.16.1

lang/rexx/Portfile, lang/rexx/files/patch-configure.diff
Update to rexx version 3.9.6 ([based on a patch provided on the macports-users mailing list](https://lists.macports.org/pipermail/macports-users/2024-December/053244.html))
Have you
=> rexx: update to 3.9.6

audio/lms/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> lms: update to 3.62.1

math/gretl/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> gretl: update to 2024d

devel/skalibs/Portfile, lang/execline/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> skalibs: update to 2.14.3.0; execline: update to 2.9.6.1

net/nghttp3/Portfile, net/ngtcp2/Portfile
Updates
macOS 10.6
Xcode 3.2
Have you
=> ngtcp2: update to 1.10.0; nghttp3: update to 1.7.0

_resources/port1.0/group/java-1.0.tcl, lang/jruby/Portfile
Update, fix powerpc
macOS 10.6
Xcode 3.2
Have you
=> jruby: update to 9.4.9.0, enable on powerpc

www/chatgpt-client/Portfile
New port
macOS 10.6
Xcode 3.2
Have you
=> chatgpt-client: new port

net/yggdrasil-go/Portfile
=> yggdrasil-go: update to 0.5.12

devel/oxker/Portfile
=> oxker: update to 0.9.0

graphics/jpegoptim/Portfile
=> jpegoptim: update to 1.5.5

devel/pnpm/Portfile
Update to [current release](https://github.com/pnpm/pnpm/releases/tag/v9.15.1).
Have you
=> pnpm: update to 9.15.1

net/snac/Portfile, net/snac/files/Makefile.patch
=> snac: update to 2.67

devel/icu-devel/Portfile, devel/icu/Portfile
Closes: https://trac.macports.org/ticket/71620
Have you
=> icu, icu-devel: use cctools on macOS <10.7

multimedia/shairport-sync/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> shairport-sync: update to 4.3.5

lang/elixir/Portfile, lang/erlang/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> erlang: update to 27.2; elixir: update to 1.18.0

sysutils/bash-completion/Portfile
=> bash-completion: update to 2.16.0

emulators/uxn/Portfile
=> uxn: update to 20241225

mail/isync/Portfile, mail/isync/files/patch-paths.diff
Closes: https://trac.macports.org/ticket/71493
=> isync: update to 1.5.0

editors/nano/Portfile
https://lists.gnu.org/archive/html/info-gnu/2024-12/msg00005.html
Have you
=> nano: update to 8.3

graphics/jpegoptim/Portfile
=> jpegoptim: set openmaintainer

devel/bun/Portfile
=> bun: update to 1.1.42

python/py-awscli2/Portfile
=> py-awscli2: update to 2.22.26

databases/msodbcsql17/Portfile, databases/mssql-tools/Portfile, devel/game-porting-toolkit/files/0001-game_porting_toolkit_1.0_beta1.diff, java/openjdk11-microsoft/Portfile, java/openjdk17-microsoft/Portfile, java/openjdk21-microsoft/Portfile, kde/kde-extra-cmake-modules/files/patch-enable-named-operators.diff
- docs.microsoft.com -> learn.microsoft.com
- "/en-us" -> ""
Related: https://github.com/macports/macports-ports/pull/27233
=> Update docs.ms.com links

games/fheroes2/Portfile
=> fheroes2: update to 1.1.5

devel/global/Portfile
https://lists.gnu.org/archive/html/info-global/2024-12/msg00000.html
Have you
=> global: update to 6.6.14

net/uTox/Portfile, net/uTox/files/0001-Allow-X11-build-on-macOS.patch, net/uTox/files/0002-Use-openal-soft.patch
macOS 10.15.7 (x11)
macOS 14.7.1 (Cocoa)
macOS 10.6* (x11)
* On 10.5 and 10a190 this may not work. On 10.6.8 ppc it works, from the looks of things.
Have you
=> uTox: new port in net

news/tin/Portfile
=> tin: update to 2.6.4

gnome/gstreamer1-gst-plugins-bad/Portfile, multimedia/VLC2/Portfile, multimedia/ffmpeg-devel/Portfile, multimedia/ffmpeg/Portfile, multimedia/ffmpeg4/Portfile, multimedia/ffmpeg6/Portfile, multimedia/ffmpeg7/Portfile, multimedia/mythtv.28/Portfile, multimedia/x265/Portfile
=> x265: update to 4.1

lang/libomp/Portfile
=> libomp:19.1.6

devel/jreleaser/Portfile
=> jreleaser: update to version v1.16.0

devel/pnpm/Portfile
Mach-O files for all architectures are contained in all distributions.
Have you
=> pnpm: Update to 9.15.2

security/uacme/Portfile
=> uacme: update to 1.7.6

devel/wolfssl/Portfile
macOS 14.6 23G80 x86_64
Have you
=> wolfssl: update to version 5.7.6

net/shadowsocks-rust/Portfile
=> shadowsocks-rust: update to v1.22.0

devel/universal-ctags/Portfile
=> universal-ctags: update to 6.1.20241229.0

sysutils/fswatch/Portfile
=> fswatch: update to 1.18.0

devel/docker/Portfile
=> docker: update to 27.4.1

devel/operator-sdk/Portfile
=> operator-sdk: update to 1.38.0

devel/rke/Portfile
=> rke: update to 1.7.1

lang/antlr4-cpp-runtime/Portfile
=> antlr4-cpp-runtime: update to 4.13.2

java/flyway/Portfile
=> flyway: update to 11.1.0

devel/docker-buildx-plugin/Portfile
=> docker-buildx-plugin: update to 0.19.3

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.18.0

security/bitwarden-cli/Portfile
=> bitwarden-cli: Update to version 2024.12.0

archivers/draco/Portfile, graphics/tinygltf/Portfile, graphics/tinygltf/files/01_patch-cmake.diff, graphics/tinygltf/files/03_patch-enable-ctest.diff
tinygltf: update to 2.9.4
macOS x.y
Have you
=> tinygltf: update to 2.9.4

net/matrix-commander/Portfile, net/matrix-nio/Portfile, python/py-aiofiles/Portfile, python/py-notify2/Portfile, python/py-unpaddedbase64/Portfile
I do not want to carry generic ports in a fork, rather merge them.
macOS 14.7.1
Xcode 15.4
Have you
=> matrix-commander: CLI client for Matrix

devel/semver-utils/Portfile
=> semver-utils: new port submission

devel/cpp-argparse-dev/Portfile
=> cpp-argparse-dev: update to v1.9.6

devel/got/Portfile
=> got: update to 0.107

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.18

math/fricas/Portfile
=> fricas: revbump for new sbcl version 2.5.0

net/rpki-client/Portfile
=> rpki-client: update to 9.4

net/snac/Portfile, net/snac/files/Makefile.patch
=> snac: update to 2.68

lang/logtalk/Portfile
=> logtalk: update to 3.87.0

gis/kealib/Portfile
Update `kealib` to 1.6.1
macOS x.y
Have you
=> kealib: update to 1.6.1

lang/stack/Portfile
=> stack: update to 3.3.1

lang/ghc/Portfile
=> ghc: update to 9.12.1

editors/moe/Portfile
=> moe: update to 1.15

editors/ed/Portfile
=> ed: update to 1.21

python/py-awscli2/Portfile
=> py-awscli2: update to 2.22.33

devel/bun/Portfile
=> bun: update to 1.1.43

net/wireshark4/Portfile
=> wireshark4: update to 4.4.3

devel/pnpm/Portfile
MACH-O files for all architectures are included in all distributions.
Have you
=> pnpm: update to 9.15.3

www/lighttpd/Portfile, www/lighttpd/files/patch-conf-darwin.diff, www/lighttpd/files/patch-conf.diff
=> lighttpd: Update to 1.4.77

devel/eask-cli/Portfile
=> eask-cli: update to 0.10.3

devel/docker/Portfile
=> docker: update to 27.5.0

gis/gdal/Portfile
Update `gdal` to 3.10.1 and add subport `gdal-hdf4` replacing 'hdf4' variant.
Have you
=> gdal: update to 3.10.1, add subport 'gdal-hdf4' replacing 'hdf4' variant

net/ncdc/Portfile
Add "u" key to file browser to sort non-local files first 
Fix possible crash on aarch64 when connected to an ADC hub 
Slightly improve ADC protocol compliance
Slightly improve C compiler compatibility
Add GeoIP support
macOS 14.7.2
Have you
=> ncdc: update to 1.24.1, add GeoIP support

lang/antlr4-cpp-runtime/Portfile
=> antlr4-cpp-runtime: enhancement add support for all architectures

python/poetry/Portfile, python/py-poetry-core/Portfile, python/py-poetry-plugin-export/Portfile
=> poetry: update to 2.0.1

_resources/port1.0/group/haskell_cabal-1.0.tcl, lang/cabal/Portfile
Fixes:
* https://trac.macports.org/ticket/71821
* https://github.com/macports/macports-ports/pull/27341
* See: https://github.com/haskell/cabal/issues/10755
Note: the `--enable-relocatable` issue in https://github.com/haskell/cabal/issues/10755 affects all `cabal` project builds starting with version 3.12.1.0.
macOS x.y
Have you
=> cabal: Update to version 3.14.1.1; Fix build issue in PG haskell_cabal

devel/reuse/Portfile
macOS 13.7.2 22H313 x86_64
Have you
=> reuse: update to 5.0.2

devel/docker/Portfile
=> docker: update to 27.5.1

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.19

sysutils/terraform/Portfile
=> terraform: update to 1.10.5

lang/kotlin/Portfile
- Simple update to latest release, 2.1.0
=> kotlin: update to 2.1.0

devel/arduino-cli/Portfile
=> arduino-cli: update to 1.1.1

devel/operator-sdk/Portfile
=> terraform: update to 1.39.1

lang/libomp/Portfile
=> libomp: 19.1.7

emulators/uxn/Portfile
=> uxn: update to 20250124

databases/redis/Portfile
=> redis: Update to version 7.4.2

mail/rspamd/Portfile
=> rspamd: Update to version 3.11.0

python/py-XlsxWriter/Portfile
=> py-XlsxWriter: 3.2.1

python/py-ctypeslib2/Portfile
=> py-ctypeslib2: py313 version

sysutils/mc/Portfile, sysutils/mc/files/patch-src_subshell_common.c.diff
https://midnight-commander.org/wiki/NEWS-4.8.33
Have you
=> mc: update to 4.8.33

devel/cpp-argparse-dev/Portfile
=> cpp-argparse-dev: update to v1.9.7

net/snac/Portfile
=> snac: update to 2.69

gis/qgis3/Portfile
`qgis3`: update to 3.40.3
`qgis3-ltr`: update to 3.34.15
Have you
=> qgis3: update to 3.40.3

databases/postgis3/Portfile, gis/pgrouting/Portfile, gis/pgrouting/files/patch-CMakeLists.txt.diff, gis/saga/Portfile, python/py-gdal/Portfile
- `postgis3`: update to 3.5.2
- `py-gdal`: update to 3.10.1
- `pgrouting`: update to 3.7.2
- `saga`: update to 9.7.2
Have you
=> saga, postgis3, pgrouting, py-gdal: updates

sysutils/fswatch/Portfile
=> fswatch: update to version 1.18.1

textproc/pandoc/Portfile
=> pandoc: Update to version 3.6.2

databases/postgis3/Portfile, gis/gdal-grass/Portfile, gis/gdal/Portfile, gis/pdal/Portfile, gis/pgrouting/Portfile, gis/qgis3/Portfile, gis/rsgislib/Portfile, gis/saga/Portfile
Promote @nilason as first maintainer for following ports:
- gdal
- gdal-grass
- pdal
- pgrouting
- postgis3
- qgis3
- rsgislib
- saga
macOS x.y
Have you
=> some gis/* ports: promote nilason as first maintainer

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.19.0

www/phpmyadmin/Portfile
Last update: https://github.com/macports/macports-ports/pull/13724
Have you
The ticket https://trac.macports.org/ticket/43993 should be closed.
=> phpMyAdmin: update to 5.2.2

sysutils/fswatch/Portfile
=> fswatch: update to 1.18.2

java/openjdk11-bootstrap/Portfile, java/openjdk11/Portfile, java/openjdk13-bootstrap/Portfile, java/openjdk13/Portfile, java/openjdk15-bootstrap/Portfile, java/openjdk15/Portfile, java/openjdk17-bootstrap/Portfile, java/openjdk17/Portfile, java/openjdk18-bootstrap/Portfile, java/openjdk18/Portfile, java/openjdk19-bootstrap/Portfile, java/openjdk19/Portfile, java/openjdk20-bootstrap/Portfile, java/openjdk20/Portfile, java/openjdk7-bootstrap/Portfile, java/openjdk8-bootstrap/Portfile, java/openjdk8/Portfile
Closes: https://trac.macports.org/ticket/71932
=> Remove usersxx as maintainer due to inactivity

lang/logtalk/Portfile
=> logtalk: update to 3.88.0

science/pnetcdf/Portfile
macOS 13.7.2
Xcode 15.2 / Command Line Tools 15.2.0
Have you
=> pnetcdf: update to v1.14.0

lang/clojure/Portfile
=> clojure: update to  1.12.0.1501

lang/wabt/Portfile, lang/wabt/files/disable-python3-requirement.patch
Proposed fixes for <https://trac.macports.org/ticket/71968>
=> lang/wabt:  tighten requirements in response to #71968

lang/cabal/Portfile
Draft test CI build following #27470
macOS x.y
Have you
=> cabal: Bugfix build following #27470

sysutils/pv/Portfile
=> pv: 1.9.31

net/snac/Portfile
=> snac: update to 2.70

science/pooler/Portfile
=> pooler: Update to 1.89

sysutils/fswatch/Portfile
=> fswatch: update to 1.18.3

net/snac/Portfile
=> snac: update to 2.71

gis/qgis3/Portfile
Fix broken Python related patch to use correct GDAL tools.
macOS x.y
Have you
=> qgis3: fix python patch

gis/gdal/Portfile
Always look for mpi variant, to be able to find mpi.h if needed.
This is now necessary since hdf5 and kealib are build dependents.
Closes: https://trac.macports.org/ticket/72003
Have you
=> gdal: always look for mpi variant

emulators/uxn/Portfile
=> uxn: update to 20250131

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.20

security/bitwarden-cli/Portfile
update to version 2025.1.3
Have you
=> bitwarden-cli: update to version 2025.1.3

audio/proxy-audio-device/Portfile
=> proxy-audio-device: fix 1.0.7 Portfile

finance/bitcoin/Portfile
=> bitcoin: update to 28.1

gis/rsgislib/Portfile, gis/saga/Portfile, python/py-pdal-plugins/Portfile, python/py-pdal/Portfile
- py-rsgislib: add py313 subport
- py-pdal-plugins: add py313 subport
- py-pdal: add py313 subport
- py-pysaga: add py313 subport
In addition:
- saga: set cxx_standard 2017 
macOS x.y
Have you
=> py-rsgislib, py-pdal-plugins, py-pdal, py-pysaga: add py313 subports

sysutils/yazi/Portfile
=> yazi: Update to version 25.2.7

devel/wasmtime/Portfile
update wasmtime to 29.0.1
Have you
=> wasmtime: update to 29.0.1

devel/luv/Portfile
update luv to 1.50.0-1
Have you
=> luv: update to 1.50.0-1

python/py-geojson/Portfile, python/py-owslib/Portfile
- `py-geojson`: update to 3.2.0; add py313 subport
- `py-owslib`: update to 0.32.1
macOS x.y
Have you
=> py-geojson, py-owslib: updates

gis/gdal/Portfile
=> gdal: fix typos

lang/luajit/Portfile
update luajit to 2.1.1736781742
Have you
=> luajit: update to 2.1.1736781742

net/snac/Portfile
=> snac: update to 2.72

devel/jujutsu/Portfile
Update jujutsu to 0.26.0
Have you
=> jujutsu: update to 0.26.0

python/py-fiona/Portfile, python/py-geopandas/Portfile, python/py-pulp/Portfile, python/py-pyogrio/Portfile, python/py-pyogrio/files/patch_pyproject.diff, python/py-rasterstats/Portfile, python/py-scikit-learn/Portfile, python/py-seaborn/Portfile, python/py-simplejson/Portfile
- py-scikit-learn: update to 1.6.1, add py313 subport
- py-fiona: update to 1.10.1; add py313 subport
- py-pyogrio: new port
- py-geopandas: update to 1.0.1, add py313 subport
- py-pulp: add py313 subport
- py-rasterstats: add py313 subport
- py-seaborn: add py313 subport
- py-simplejson: add py313 subport
Have you
=> Add some py313 subports; update py-scikit-learn, py-fiona, py-geopandas; new port py-pyogrio

audio/liboggz/Portfile
Update liboggz to version 1.1.2
macOS 13.7.2 22H313 arm64
Have you
=> liboggz: update to 1.1.2

python/py-access/Portfile, python/py-branca/Portfile, python/py-codecov/Portfile, python/py-esda/Portfile, python/py-folium/Portfile, python/py-giddy/Portfile, python/py-inequality/Portfile, python/py-libpysal/Portfile, python/py-mapclassify/Portfile, python/py-mgwr/Portfile, python/py-momepy/Portfile, python/py-pointpats/Portfile, python/py-pysal/Portfile, python/py-segregation/Portfile, python/py-spaghetti/Portfile, python/py-spglm/Portfile, python/py-spint/Portfile, python/py-spopt/Portfile, python/py-spreg/Portfile, python/py-spvcm/Portfile, python/py-tobler/Portfile
- `py-access`: add py313 subport
- `py-esda`: update to 2.7.0; add py313 subport
- `py-giddy`: update to 2.3.6; pin 2.3.5 to py39 (not ready for py313)
- `py-inequality`: update to 1.1.1; add py313 subport
- `py-libpysal`: add py313 subport
- `py-mapclassify`: add py313 subport
- `py-mgwr`: add py313 subport
- `py-momepy`: add py313 subport
- `py-pointpats`: add py313 subport
- `py-pysal`: update to 2.5.2 (not ready for py313)
- `py-segregation`: update to 2.5.2 (not ready for py313)
- `py-spaghetti`: add py313 subport
- `py-spglm`: add py313 subport
- `py-spint`: add py313 subport
- `py-spopt`: add py313 subport
- `py-spreg`: add py313 subport
- `py-spvcm`: add py313 subport
- `py-tobler`: update to 0.12.1; add py313 subport
Have you
=> PySAL family ports: add py313 subports, updates

shells/tcsh/Portfile
=> tcsh: update to 6.24.15

archivers/unrar/Portfile
=> unrar: update to 7.1.3

net/vnstat/Portfile
=> vnstat: update to 2.13

lang/logtalk/Portfile
=> logtalk: update to 3.89.0

sysutils/yabai/Portfile, sysutils/yabai/files/patch-makefile-macos11.diff, sysutils/yabai/files/patch-makefile.diff, sysutils/yabai/files/patch-workspace.m-macos11.diff
Update to latest `yabai` version.
Have you
=> yabai: update to 7.1.10

lang/sdcc/Portfile
=> sdcc: update to 4.5.0

science/stimfit/Portfile
* bump revision to 0.16.6_1
* support Python 3.13 now that wxPython supports it
Have you
=> stimfit: update to version 0.16.6_1

science/libframe/Portfile
=> Update libframe to 8.48.4

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff
=> py-awscli2: update to 2.24.5

lang/logtalk/Portfile
=> logtalk: update to 3.89.1

net/openssh/Portfile
=> openssh: update to 9.9p2

emulators/qemu/Portfile
=> qemu: update to 9.2.1, use python 3.13

graphics/lcms2/Portfile
=> lcms2: update to 2.17

shells/yash/Portfile
Update yash to version 2.58.1
Have you
=> yash: update to version 2.58.1

multimedia/ffmpeg-devel/Portfile, multimedia/ffmpeg-devel/files/patch-svt-av1-v3.diff, multimedia/ffmpeg/Portfile, multimedia/ffmpeg/files/patch-svt-av1-v3.diff, multimedia/ffmpeg4/Portfile, multimedia/ffmpeg4/files/patch-svt-av1-v3.diff, multimedia/ffmpeg6/Portfile, multimedia/ffmpeg6/files/patch-svt-av1-v3.diff, multimedia/ffmpeg7/Portfile, multimedia/ffmpeg7/files/patch-svt-av1-v3.diff, multimedia/svt-av1/Portfile
=> svt-av1: update to 3.0.0

archivers/unrar/Portfile
=> unrar: update to 7.1.4

textproc/typst/Portfile
Command Line Tools 10.1.0.0.1.1539992718
Have you
=> typst: Update to version 0.13.0

devel/orc/Portfile
=> orc: update to 0.4.41

graphics/presenterm/Portfile
presenterm: update to 0.10.1
https://github.com/mfontanini/presenterm/releases
Have you
=> presenterm: update to 0.10.1

net/offpunk/Portfile
=> offpunk: update to 2.5

emulators/tnylpo/Portfile
=> tnylpo: update to 1.1.7

sysutils/vivid/Portfile
[vivid](https://github.com/sharkdp/vivid) is a generator for the LS_COLORS environment variable that controls the colorized output of [ls](https://www.gnu.org/software/coreutils/manual/html_node/ls-invocation.html#ls-invocation), [tree](http://mama.indstate.edu/users/ice/tree/), [fd](https://github.com/sharkdp/fd), [bfs](https://github.com/tavianator/bfs), [dust](https://github.com/bootandy/dust) and many other tools.
[![Packaging status](https://repology.org/badge/tiny-repos/vivid.svg)](https://repology.org/project/vivid/versions)
Have you
=> vivid: new port

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.0.0

devel/jreleaser/Portfile
=> jreleaser: update to version v1.17.0

science/seqan2/Portfile
* fetch source using github portgroup
* add openmaintainer to maintainers
* replace local base_name with github.project variable
Have you
=> seqan2: update to version 2.5.0

sysutils/resticprofile/Portfile
update resticprofile to 0.29.1
macOS 15.1 24B2083 arm64
Have you
=> resticprofile: update to 0.29.1

emulators/wine-devel/Portfile, emulators/wine-devel/files/0002-macos_hacks.diff, emulators/wine-devel/files/0003-bug56854.diff, emulators/wine-devel/files/1002-staging-macos_hacks.diff, emulators/wine-devel/files/MR7448.diff
=> wine-devel,wine-staging: Update to 10.2

devel/cpp-argparse-dev/Portfile
=> cpp-argparse-dev: update to v1.9.8

net/s3cmd/Portfile
- update to 2.4.0
- depend on Python 3.13
- maintainer info changed
macOS 13.7.3 22H417 x86_64
Have you
=> s3cmd: update to version 2.4.0

security/blake3/Portfile
Update blake3 to 1.6.1
Have you
=> blake3: update to 1.6.1

net/offpunk/Portfile
=> offpunk: update to 2.6

net/snac/Portfile
=> snac: update to 2.73

devel/d3dmetal/Portfile
=> d3dmetal: Update to v2.1

audio/faad2/Portfile
=> faad2: update to 2.11.2

audio/faac/Portfile
=> faac: update to 1.31.1

archivers/unrar/Portfile
=> unrar: update to 7.1.5

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.1.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.2.1

java/detekt-cli/Portfile
=> detekt-cli: Update to version 1.23.8

gnome/gtk3/Portfile, gnome/gtk3/files/patch-gtk-menu-crash.diff
=> Update to gtk3@3.24.49

devel/re-flex/Portfile
=> re-flex: update to 5.3.0

devel/astyle/Portfile
=> astyle: update to 3.6.7

devel/docker/Portfile
=> docker: update to 28.0.1

lang/gleam/Portfile
=> gleam: update to 1.9.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.3.0

textproc/typst/Portfile
Command Line Tools 10.1.0.0.1.1539992718
Have you
=> typst: Update to version 0.13.1

multimedia/ffmpeg6/Portfile, multimedia/ffmpeg7/Portfile
=> ffmpeg[6,7]: add vmaf variant

multimedia/ab-av1/Portfile
=> ab-av1: submission

sysutils/skhd/Portfile, sysutils/skhd/files/completion.zsh
=> skhd: add zsh completion file

devel/oxker/Portfile
=> oxker: update to 0.10.0

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.21

databases/postgresql16/Portfile, databases/postgresql17/Portfile
=> Add tls certificate dependency to postgresql 16 / 17

security/opensc/Portfile
https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/295771/steps/install-port/logs/stdio
Have you
=> opensc: bump legacysupport to 14 for MAP_ANONYMOUS

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.4.2

net/s3cmd/Portfile
Install man page for s3cmd
macOS 13.7.3 22H417 x86_64
Have you
=> s3cmd: add man page

textproc/glow/Portfile
=> glow: install man page and completions

devel/got/Portfile, devel/got/files/patch-vis-compat.diff
Closes: https://trac.macports.org/ticket/71820
Have you
=> got: fix build on macOS <13

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.4.3

databases/timescaledb/Portfile
=> timescaledb: update to 2.18.2

science/hpl/Portfile
man pages/headers/lib
macOS x.y
Have you
=> hpl: general improvements, install more files

net/shadowsocks-rust/Portfile
=> shadowsocks-rust: update to v1.23.0

multimedia/AtomicParsley-devel/Portfile, multimedia/AtomicParsley-devel/files/patch-dont-force-universal2.diff
=> AtomicParsley-devel: update to 20241205

editors/zile/Portfile
* add revision line
Closes: https://trac.macports.org/ticket/71629
Have you
=> zile: update to 2.6.4

net/scamper/Portfile
=> scamper: update to 20250227

net/snac/Portfile
=> snac: update to 2.74

devel/girara/Portfile, graphics/mupdf/Portfile, office/zathura-plugin-cb/Portfile, office/zathura-plugin-djvu/Portfile, office/zathura-plugin-pdf-mupdf/Portfile, office/zathura-plugin-pdf-poppler/Portfile, office/zathura-plugin-ps/Portfile, office/zathura/Portfile
Remove maintainer harciga who hasn't been heard from since 2017.
See: https://trac.macports.org/ticket/53713#comment:4
See: https://trac.macports.org/ticket/69273#comment:1
Hector, if you still wish to maintain your ports let us know. Otherwise we will merge this PR and remove you as maintainer.
=> Remove maintainer harciga

graphics/babl/Portfile, graphics/gegl/Portfile
=> babl/gegl: updates

python/py-clang/Portfile
=> py-clang: Update to 20.1.1

lang/libomp/Portfile
=> libomp: 20.1.1; Drop long-obsoleted -devel

python/py-h5py/Portfile
=> py-h5py: 3.13.0

python/py-XlsxWriter/Portfile
=> py-XlsxWriter:3.2.2

python/py-qimage2ndarray/Portfile
=> py-qimage2ndarray: Add 312/313

devel/got/Portfile
=> got: update to 0.110

python/py-pygments-mathematica/Portfile
=> py-pygments-mathematica: fetch from PyPI instead of GitHub

databases/postgresql13-doc/Portfile, databases/postgresql13-server/Portfile, databases/postgresql13/Portfile, databases/postgresql14-doc/Portfile, databases/postgresql14-server/Portfile, databases/postgresql14/Portfile, databases/postgresql15-doc/Portfile, databases/postgresql15-server/Portfile, databases/postgresql15/Portfile, databases/postgresql16-server/Portfile, databases/postgresql16/Portfile, databases/postgresql17-server/Portfile, databases/postgresql17/Portfile
```
On branch postgresql
update to @13.20
modified:   databases/postgresql13-doc/Portfile
modified:   databases/postgresql13-server/Portfile
modified:   databases/postgresql13/Portfile
update to @14.17
modified:   databases/postgresql14-doc/Portfile
modified:   databases/postgresql14-server/Portfile
modified:   databases/postgresql14/Portfile
update to @15.12
modified:   databases/postgresql15-doc/Portfile
modified:   databases/postgresql15-server/Portfile
modified:   databases/postgresql15/Portfile
update to @16.8
modified:   databases/postgresql16-server/Portfile
modified:   databases/postgresql16/Portfile
update to @17.4
modified:   databases/postgresql17-server/Portfile
modified:   databases/postgresql17/Portfile
```
[https://endoflife.date/postgresql](url) …
=> postgresql : update v{13..17}

science/ismrmrd/Portfile
=> ismrmrd: 1.14.2

sysutils/OpenIPMI/Portfile
=> OpenIPMI: 2.0.36

security/pam-google-authenticator/Portfile
=> pam-google-authenticator: 1.11

net/tintinxx/Portfile
tintinxx: update to 2.02.42
https://github.com/scandum/tintin/releases
- This port seems to have not been updated for too long, so I will take over as openmaintainer.
- Related comment: https://trac.macports.org/ticket/41845#comment:1
- Change the location for receiving archives from SourceForge to GitHub.
Have you
=> tintinxx: update to 2.02.42

devel/qt6-qtcreator/Portfile
=> qt6-qtcreator: update to v16.0.0

games/fheroes2/Portfile
=> fheroes2: update to 1.1.7

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.5.1

devel/got/Portfile, devel/got/files/patch-vis-compat.diff
=> got: re-fix build on macOS <13

graphics/gegl-devel/Portfile
Required by gimp 3.0.2
macOS x.y
Have you
=> gegl-devel: update to 0.4.58

emulators/wine-devel/Portfile, emulators/wine-devel/files/0002-macos_hacks.diff, emulators/wine-devel/files/0003-wined3d-cwhack-18311.diff, emulators/wine-devel/files/3001-Revert-ntdll-Force-committed-access-on-anonymous-map.diff, emulators/wine-devel/files/3002-Revert-ntdll-Always-map-files-as-writable-and-adjust.diff
=> wine-devel,wine-staging: Update to 10.4

devel/nsis/Portfile
=> nsis: update to 3.11

R/R-igraph/Portfile
=> R-igraph: update to 2.1.4

lang/logtalk/Portfile
=> logtalk: update to 3.90.0

security/putty/Portfile, sysutils/pssh-lilydjwg/Portfile
=> putty: update to 0.83

archivers/unrar/Portfile
=> unrar: update to 7.1.6

editors/ed/Portfile
https://lists.gnu.org/archive/html/info-gnu/2025-03/msg00013.html
Have you
=> ed: update to 1.21.1

devel/qbs/Portfile
=>  qbs: Update to 2.6.0

lang/logtalk/Portfile
=> logtalk: update to 3.90.1

devel/astyle/Portfile
=> astyle: update to 3.6.8

security/blake3/Portfile
=> blake3: update to 1.7.0

gis/proj/Portfile
Update `proj9` to 9.6.0.
Have you
=> proj9: update to 9.6.0

gis/qgis3/Portfile
- update `qgis3` to 3.42.1
- update `qgis3-ltr` to 3.40.5
- add new default postgresql17 variant
Have you
=> qgis3: update to 3.42.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.7.1

sysutils/coreutils-uutils/Portfile
=> coreutils-uutils: update to 0.0.30

multimedia/scrcpy/Portfile
Command Line Tools 8.2.0.0.1.1480973914
Have you
=> scrcpy: update to version 3.2

java/android-platform-tools/Portfile
=> android-platform-tools: update to version 36.0.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.11.0

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.22

net/scamper/Portfile
=> scamper: update to 20250401

games/PrismLauncher/Portfile
=> PrismLauncher: update 9.2

graphics/libpng/Portfile
=> libpng: update to 1.6.47

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.0

net/dnscap/Portfile
=> dnscap: update to 2.2.1

security/bitwarden-cli/Portfile
=> bitwarden-cli: Update to version 2025.3.0

devel/gpatch/Portfile
Closes: https://trac.macports.org/ticket/72265
Have you
=> gpatch: bypass year 2038 check for i386/PowerPC

devel/cmark-gfm/Portfile
Closes: https://trac.macports.org/ticket/72292
macOS 15.4
Xcode 16.3 / Command Line Tools 16.3
Have you
=> cmark-gfm: fetch from archive

devel/taplo/Portfile
Closes: https://trac.macports.org/ticket/72291
macOS 15.4
Xcode 16.3 / Command Line Tools 16.3
Have you
=> taplo: new port

net/fping/Portfile
Updates fping to 5.3.
Have you
=> fping: update to 5.3

games/PrismLauncher/Portfile
* updated to version 9.3
* no other changes to report
macOS 15.3.1
Have you
=> PrismLauncher: update 9.3

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.1

lang/logtalk/Portfile
=> logtalk: update to 3.91.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.13.0

science/socnetv/Portfile
=> socnetv: update to 3.2

lang/eiffelstudio/Portfile
* new version 25.02
* updated maintainer's list
macOS x.y
Have you
Closes: https://github.com/macports/macports-ports/pull/28092
=> eiffelstudio: new version 25.02

games/PrismLauncher/Portfile
* updated to version 9.4
* no other changes to report
Have you
=> PrismLauncher: update 9.4

lang/stack/Portfile
=> stack: update to 3.5.1

net/openiked/Portfile
=> openiked: update to 7.4

textproc/datamash/Portfile
=> datamash: update to 1.9

sysutils/tenv/Portfile, sysutils/terraform/Portfile, sysutils/terragrunt/Portfile
=> tenv: new port

net/rpki-client/Portfile
=> rpki-client: update to 9.5

devel/qt6-qtcreator/Portfile
=> qt6-qtcreator: update to 16.0.1

lang/logtalk/Portfile
=> logtalk: update to 3.91.1

security/pkcs11-provider/Portfile, security/pkcs11-provider/files/patch-meson-build.diff
=> pkcs11-provider: fix build on macOS <10.12

math/SuiteSparse/Portfile
=> SuiteSparse: update to 7.10.2

graphics/graphite2/Portfile
=> graphite2: Update python version to 3.13

net/snac/Portfile
=> snac: update to 2.75

devel/swig/Portfile, devel/swig/files/patch-configure.diff
=> swig: update to 4.3.1

devel/ghidra/Portfile
=> ghidra: update to 11.3.2

lang/py-htmldocs/Portfile
=> py-htmldocs: Latest for 3.10-13

devel/gperf/Portfile
=> gperf: update to 3.2

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.23

devel/micropython/Portfile
Without it, the Clang blacklist doesn't work.
Have you
=> micropython: add forgotten compiler_blacklist_versions portgroup

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.15.0

net/wcurl/Portfile
=> wcurl: update to 2025.02.24

devel/talloc/Portfile
=> talloc: fix build on macOS < 10.10

net/shadowsocks-rust/Portfile
=> shadowsocks-rust: update to v1.23.1

textproc/aichat/Portfile
=> aichat: update to version 0.29.0

devel/tevent/Portfile
=> tevent: fix build on macOS < 10.10

net/dnsviz/Portfile, python/py-pygraphviz/Portfile
=> dnsviz: update to 0.11.1

emulators/wine-devel/Portfile, emulators/wine-devel/files/0002-macos_hacks.diff, emulators/wine-devel/files/0004-winemac.drv-export-essential-apis.diff
=> wine-devel,wine-staging: Update to 10.6

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.18.0

python/py-pyside6/Portfile
See: https://trac.macports.org/ticket/65411
macOS x.y
Have you
=> py-pyside6: manually install pc and cmake files

math/kalc/Portfile
=> kalc: update to 1.5.0, add man page

devel/astyle/Portfile
=> astyle: update to 3.6.9

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.24

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.2

lang/MoarVM/Portfile, lang/MoarVM/files/patch-libuv-legacy.diff, lang/nqp/Portfile, lang/rakudo/Portfile
=> rakudo and its depends: update to 2025.04

net/shadowsocks-rust/Portfile
=> shadowsocks-rust: update to v1.23.2

gis/qgis3/Portfile
Update `qgis3` to 3.42.2, and `qgis3-ltr`  to 3.40.6.
macOS x.y
Have you
=> qgis3: update to 3.42.2

security/blake3/Portfile
Update Blake3 to v.1.8.2
Have you
=> blake3: update to 1.8.2

sysutils/netdata/Portfile, sysutils/netdata/files/patch-pr-20145.diff
=> netdata: update to 2.4.0

python/py-XlsxWriter/Portfile
=> py-XlsxWriter:3.2.3

python/py-clang/Portfile
=> py-clang: 20.1.3

devel/jreleaser/Portfile
=> jreleaser: update to version v1.18.0

lang/binaryen/Portfile
Simple update to latest release.
=> binaryen: update to 123; use py313

net/offpunk/Portfile
=> offpunk: update to 2.7.1

_resources/port1.0/group/crossbinutils-1.0.tcl
Closes https://trac.macports.org/ticket/72415
macOS x.y
=> crossbinutils: Use MacPorts zlib

security/libressl/Portfile, security/libressl/files/patch-openssldir-cert.pem.diff
=> libressl: update to 4.1.0

textproc/krep/Portfile
=> krep: fix build on macOS <10.12

lang/algol68g/Portfile
=> algol68g: update to 3.5.14

graphics/jpegoptim/Portfile
=> jpegoptim: fix build on macOS <10.7

graphics/imlib2/Portfile
=> imlib2: update to 1.12.5

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.20.0

audio/liboggz/Portfile
=> liboggz: update to 1.1.3

graphics/MoltenVK/Portfile
=> MoltenVK: update to 1.3.0

math/LBFGSpp/Portfile
=> LBFGSpp: update to 0.4.0

x11/sunclock/Portfile
Also see https://trac.macports.org/ticket/57785#comment:3
Have you
=> sunclock: add link to github repo

science/mfem/Portfile
=> mfem: update to 4.8

textproc/docbook-xsl/Portfile, textproc/docbook-xsl/files/patch-libxsl.diff
Closes: https://trac.macports.org/ticket/72362
Have you
=> docbook-xsl: fix infinite recursion for e.g. samba

python/podman-compose/Portfile, python/py-python-dotenv/Portfile
=> podman-compose: update to version 1.3.0

python/py-giddy/Portfile, python/py-numba/Portfile, python/py-plotly/Portfile, python/py-pysal/Portfile, python/py-quantecon/Portfile, python/py-segregation/Portfile, python/py-splot/Portfile
=> multiple python ports: add python 3.13

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.3

net/samba4/Portfile
This pull request mainly addresses the extreme amount of dependencies introduced by the last overhaul:
- removes `tracker`, a file/media tracker for GNOME, which notably involves `libgstreamer` and its various codecs
- removes `avahi` (which serves no purpose on macOS) and `glib2` (another unneeded GNOME dependency)
- adds `cmocka` as a build dependencies to match other package managers (Homebrew, FreshPorts, etc.)
- enables FHS configuration directory structure to match Linux, as was the state before the last patch
Have you
=> samba4: various dependency improvements

gis/qgis3/Portfile
=> qgis3: add and default to python 3.13

net/libtorrent-rasterbar/Portfile
=> libtorrent-rasterbar: add and default to python313

sysutils/OpenIPMI/Portfile
=> OpenIPMI: 2.0.37

games/fheroes2/Portfile
=> fheroes2: update to 1.1.8

shells/fish/Portfile, shells/fish3/Portfile, shells/fish3/files/patch-share_config_fish.diff
=> fish3: submission

net/get_iplayer/Portfile
=> get_iplayer: update to 3.36

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.4

net/snac/Portfile, net/snac/files/Makefile.patch
=> snac: update to 2.76

devel/oxker/Portfile
=> oxker: update to 0.10.3

shells/oksh/Portfile
=> oksh: update to 7.7

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 25.23.0

net/snac/Portfile
=> snac: update to 2.77

net/shadowsocks-rust/Portfile
=> shadowsocks-rust: update to v1.23.4

science/imager/Portfile, science/imager/files/greg.in, science/imager/files/imager.in, science/imager/files/sic.in, science/imager/files/viewer.in
=> imager: update to V4.5-01 (may25)

mail/opensmtpd/Portfile
=> opensmtpd: update to 7.7.0p0

net/zmap/Portfile
=> zmap: update to 4.3.4

devel/qt6-qtcreator/Portfile
=> qt6-qtcreator: update to v16.0.2

net/zenmap/Portfile
=> zenmap: update to 7.97

net/wireshark4/Portfile
=> wireshark4: update to 4.4.6

sysutils/genext2fs/Portfile
* Releases >1.4.1 were only published as tags on github and are absent
on sourceforge.
* Metadata updated to fulfill port lint
Have you
=> genext2fs: update to 1.5.0

graphics/presenterm/Portfile
presenterm: update to 0.10.1
https://github.com/mfontanini/presenterm/releases
Have you
=> presenterm: update to 0.13.0

python/py-xmltodict/Portfile, sysutils/jc/Portfile
* py-xmltodict: update to 0.14.2, and add py313
* jc: use py313
=> py-xmltodict: update to 0.14.2, add py313; jc: use py313

fuse/sshfs/Portfile
=> sshfs: request comaintainer

audio/audiowmark/Portfile
=> audiowmark: update to 0.6.5

graphics/timg/Portfile
=> timg: update to 1.6.2

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.5

sysutils/asdf/Portfile
Fix asdf building. Asdf has been rewritten in Go since 0.16.0. The way to build and activate the tool has been changed.
https://trac.macports.org/ticket/72149
macOS 12.7 21G816 arm64
Have you
=> asdf: rebuild with golang, upgrade to 0.17.0

gnome/garagejam/Portfile
GarageJam 5.0.0 (Development Release) from https://www.garagejam.org/src/garagejam-5.0.0.tar.xz on macports 2.10.5
macOS 15.4 24E5222f arm64
Have you
=> garagejam: Update to 5.0.0

python/py-cramjam/Portfile
=> py-cramjam: submission

python/py-iterable-io/Portfile, python/py-zipstream-ng/Portfile
=> py-zipstream-ng & py-iterable-io: submission

python/buku/Portfile
buku: update to 5.0
* update python default version to 3.13
* update maintainer email
Have you
=> buku: update to 5.0

devel/cmake-devel/Portfile
=> cmake-devel-doc: add and default to python 3.13

graphics/xaos/Portfile
=> xaos: update to 4.3.4

sysutils/netdata/Portfile
=> netdata: update to 2.5.2

python/py-autobahn/Portfile, python/py-automat/Portfile, python/py-constantly/Portfile, python/py-hkdf/Portfile, python/py-passlib/Portfile, python/py-pyhamcrest/Portfile, python/py-python-snappy/Portfile, python/py-pytrie/Portfile, python/py-qrcode/Portfile, python/py-spake2/Portfile, python/py-twisted/Portfile, python/py-txaio/Portfile, python/py-txtorcon/Portfile, python/py-u-msgpack-python/Portfile
=> multiple python ports: add python 3.12 and 3.13

java/async-profiler/Portfile, java/async-profiler/files/patch-Makefile.diff
new port for - https://github.com/async-profiler/async-profiler
macOS 14.7.5 23H527 arm64
Have you
=> async-profiler: new port

science/dcm2niix/Portfile
=> dcm2niix: 1.0.20241211

devel/docker-compose-plugin/Portfile
=> docker-compose-plugin: update to 2.36.2

net/magic-wormhole/Portfile
=> magic-wormhole: update to 0.18.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.0.0

lang/cppreference/Portfile
=> cppreference: 20250209; move to GH distribution

net/regclient/Portfile
=> regclient: new port

graphics/virglrenderer/Portfile
=> virglrenderer: update to 0.10.4d

net/nmap/Portfile
=> nmap: update to 7.97

devel/64tass/Portfile
Xcode 16.3 / Command Line Tools 16.3.0.0.1.1742442376
Have you
=> 64tass: update to 1.60.3243

emulators/libkrun/Portfile, emulators/libkrun/files/patch-makefile.diff
=> libkrun: update to 1.12.2

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.2.0

emulators/krunkit/Portfile, emulators/krunkit/files/patch-makefile.diff
=> krunkit: update to 0.2.1

net/tn5250/Portfile
=> tn5250: update to version 0.18.0

python/py-pynetdicom/Portfile
=> pynetdicom: 3.0.1; set tarball_from

lang/gleam/Portfile
=> gleam: update to 1.11.0

textproc/pandoc/Portfile
=> pandoc: Update to version 3.7.0.2

emulators/libkrun/Portfile
=> libkrun: update to 1.13.0

lang/gleam/Portfile
=> gleam: update to 1.11.1

gis/qgis3/Portfile, gis/qgis3/files/patch-62113.diff
Closes: https://trac.macports.org/ticket/72531
macOS x.y
Have you
=> qgis3: update to 3_42_3

net/snac/Portfile, net/snac/files/Makefile.patch
=> snac: update to 2.78

sysutils/tenv/Portfile
=> tenv: update to 4.7.0

devel/re-flex/Portfile
=> re-flex: update to 5.5.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.4.0

sysutils/netdata/Portfile
=> netdata: update to 2.5.3

math/igraph/Portfile
=> igraph: update to 0.10.16

lang/py-htmldocs/Portfile
=> py-htmldocs: 3.10.18, 3.11.12, 3.12.11, 3.13.4

gis/proj/Portfile
Update `proj9` to 9.6.2.
Have you
=> proj9: update to 9.6.2

games/fheroes2/Portfile
=> fheroes2: update to 1.1.9

sysutils/is/Portfile
=> is: update to 0.8.2

python/py-pynetdicom/Portfile
=> pynetdicom: 3.0.2

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.6

net/wireshark4/Portfile
=> wireshark4: update to 4.4.7

lang/racket/Portfile, lang/racket/files/paths-to-openssl.diff
=> racket: Update to version 8.17; Fix livecheck

devel/qt6-qtcreator/Portfile, devel/qt6-qtcreator/files/patch-fix_operator_return_type_deduction.diff
macOS 13.7.4 22H420 x86_64
Have you
=> qt6-qtcreator: update to v17.0.0

gis/pcraster/Portfile, gis/pcraster/files/patch_pybind11.diff
`pcraster`: update to 4.4.2, default to py313 variant
Have you
=> pcraster: update to 4.4.2, default to py313 variant

devel/cpp-argparse-dev/Portfile
=> cpp-argparse-dev: update to v1.9.10

devel/qbs/Portfile
=> qbs: Update to 3.0.1

devel/ghidra/Portfile
=> ghidra: Update to 11.4

gis/grass/Portfile, gis/orfeotoolbox/Portfile, math/libsvm/Portfile, php/php-svm/Portfile
=> libsvm: update to 3.36, add py313 subport

net/rclone/Portfile
=> rclone: 1.70.1

lang/vala/Portfile
Fix home page only.  No code changes.
CI only.
Have you
=> vala: Update home page

devel/git-lfs/Portfile
=> git-lfs: update to 3.7.0

devel/cmake-devel/Portfile
=> cmake-devel: update to 4.0.3

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.7

devel/dagger/Portfile
=> dagger: update to 0.18.12

lang/cabal/Portfile
=> cabal: update to 3.14.2.0

lang/stack/Portfile
=> stack: update to 3.7.1

math/fricas/Portfile
macOS 14.7.6 23H626 x86_64
Have you
=> fricas: update to 1.3.12

sysutils/carapace/Portfile
The homepage was incorrect. Thanks to @i0ntempest for reporting.
N/A
Have you
=> carapace: fix homepage

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.14.3

net/snac/Portfile
=> snac: update to 2.80

archivers/7zip/Portfile
=> 7zip: update to 25.0.0

gis/gdal/Portfile, python/py-gdal/Portfile
Update `gdal` and `py-gdal` to 3.11.2.
macOS x.y
Have you
=> gdal, py-gdal: update to 3.11.2

mail/rspamd/Portfile
=> rspamd: Update to version 3.12.1

sysutils/coreutils-uutils/Portfile
=> coreutils-uutils: update to 0.1.0

gis/gdal/Portfile, python/py-gdal/Portfile
Update `gdal` and `py-gdal` to 3.11.3.
macOS x.y
Have you
=> gdal, py-gdal: update to 3.11.3

gis/saga/Portfile, gis/saga/files/patch-exiv2.diff
Update `saga` and `py-pysaga` to 9.9.0.
Have you
=> saga, py-pysaga: update to 9.9.0

graphics/glslang/Portfile, graphics/shaderc/Portfile, graphics/shaderc/files/use-installed-spirv-tools.patch, graphics/spirv-headers/Portfile, graphics/spirv-tools/Portfile, graphics/vulkan-headers/Portfile, graphics/vulkan-loader/Portfile, graphics/vulkan-tools/Portfile, graphics/vulkan-utility-libraries/Portfile, graphics/vulkan-validationlayers/Portfile, graphics/vulkan-volk/Portfile
=> vulkan-*, spirv-*, glslang, shaderc: updates

print/a2ps/Portfile
=> a2ps: update to 4.15.7

python/py-geopandas/Portfile, python/py-owslib/Portfile, python/py-pulp/Portfile, python/py-pyogrio/Portfile, python/py-quantecon/Portfile
- py-quantecon: update to 0.8.2
- py-pyogrio: update to 0.11.0
- py-pulp: update to 3.2.1
- py-owslib: update to 0.34.1
- py-geopandas: update to 1.1.1
macOS x.y
Have you
=> py-quantecon, py-pyogrio, py-pulp, py-owslib, py-geopandas: updates

devel/ggc/Portfile
=> ggc: install completions

devel/mbedtls/Portfile, devel/mbedtls3/Portfile, mail/hello/Portfile
=> hello: update to 2.12.2

gis/osm2pgrouting/Portfile, gis/osm2pgsql/Portfile
`osm2pgrouting`: add PostgreSQL 16 and 17 variants, default to 17
`osm2pgsql`: update to 2.1.1 
- Drop 'lua' variant and 'osm2pgsql-lua' subport, lua is now a requirement of 'osm2pgsql'.
- Add postgresql17 variant (now default)
macOS x.y
Have you
=> osm2pgsql: update to 2.1.1 ; osm2pgrouting: add postgresql16-17 variants

devel/direnv/Portfile
macOS 15.5 24F74 arm64  
Have you
=> direnv: Update to 2.37.1

java/jenv/Portfile
Add www.jenv.be back as website now it is available again
Have you
=> jenv: update website

lang/ghc/Portfile
Fixes:
* https://trac.macports.org/ticket/72340
macOS x.y
Have you
=> ghc: Fix `arm64` build

dotnet/aspnetcore-runtime-8/Portfile, dotnet/aspnetcore-runtime-9/Portfile, dotnet/aspnetcore-runtime-devel/Portfile, dotnet/dotnet-cli/Portfile, dotnet/dotnet-runtime-8/Portfile, dotnet/dotnet-runtime-9/Portfile, dotnet/dotnet-runtime-devel/Portfile, dotnet/dotnet-sdk-8/Portfile, dotnet/dotnet-sdk-9/Portfile, dotnet/dotnet-sdk-devel/Portfile
```
dotnet-sdk-devel:         update to 10.0.100 @ 5.25277.114
dotnet-runtime-devel:     update to 10.0.0 @ 5.25277.114
aspnetcore-runtime-devel: update to 10.0.0 @ 5.25277.114
dotnet-sdk-9:             new port @ 9.0.302
dotnet-runtime-9:         update to 9.0.7
aspnetcore-runtime-9:     new port @ 9.0.7
dotnet-sdk-8:             update to 8.0.412
dotnet-runtime-8:         update to 8.0.18
aspnetcore-runtime-8:     update to 8.0.18
dotnet-cli:               update to 9.0.7
```
=> .NET {8,9,devel} : update to newest versions

devel/MMTabBarView/Portfile
=> MMTabBarView: Submission

python/pipenv/Portfile
=> pipenv: update to 2025.0.4

cross/binwalk/Portfile, cross/binwalk2/Portfile
=> binwalk: major update to version 3

archivers/7zip/Portfile, archivers/7zip/files/patch-powerpc.patch
=> 7zip: make a complete p7zip replacement

net/httping/Portfile, net/httping/files/define-no-tfo.diff, net/httping/files/patch-tcp.c.diff
Update `httping` to its latest released version, 4.4.0. Support for < macOS 10.11 was added through [this pull request](https://github.com/folkertvanheusden/HTTPing/pull/22)
Have you
=> httping: Update to 4.4.0

devel/fossil/Portfile
macOS 10.15
Command Line Tools 12.4
Have you
=> fossil: update to 2.26

sysutils/podman/Portfile
=> podman: update version to 5.5.2

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.27

editors/neovim/Portfile
- update neovim to 0.11.3
- update neovim-devel to 20250714
Have you
=> neovim, -devel: update to 0.11.3 and 20250714

science/dcm2niix/Portfile
=> dcm2niix: 20250506

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.28

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.19.0

devel/jujutsu/Portfile
Update jujutsu to 0.32.0
macOS 14.7.5 23H527 arm64
Have you
=> jujutsu: update to 0.32.0

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.28.6

lang/py-htmldocs/Portfile
=> py313-htmldocs: 3.13.6

devel/docker/Portfile
macOS 15.6 24G84 x86_64
Have you
=> docker: update to 28.3.3

devel/kompose/Portfile
=> kompose: update to 1.37.0

graphics/QtPBFImagePlugin/Portfile
=> QtPBFImagePlugin: update to 4.5

editors/emacs/Portfile
=> emacs{,-app} 30.2, emacs{,-app}-devel 20250814

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.19.1

devel/got/Portfile
=> got: update to 0.117

devel/jira-cli/Portfile
Update jira-cli to 1.6.0
Have you
=> jira-cli: update to 1.6.0

net/softether5/Portfile
use release tarball
fix homepage
avoid direct folder creation in post-activate
set myself as comaintainer
macOS x.y
Have you
=> softether5: update to 5.2.5188

textproc/aichat/Portfile
=> aichat: update to version 0.30.0

sysutils/tenv/Portfile
=> tenv: update to 4.7.7

java/apache-solr8/Portfile, java/apache-solr9/Portfile, java/apache-solr9/files/solr.in, java/apache-solr9/files/solr.xml
=> apache-solr9: Submission

_resources/port1.0/group/deprecated-1.0.tcl
Add a comment for `deprecated.eol_version` option.
=> Document option deprecated.eol_version

_resources/port1.0/group/compilers-1.0.tcl, lang/gcc13/Portfile, lang/gcc14/Portfile, lang/gcc15/Portfile, lang/libgcc/Portfile
Makes libgcc15 the primary runtime provider and adds gcc15 to the known compilers
=> GCC compilers: make gcc15 default runtime provider

devel/astyle/Portfile
=> astyle: update to 3.6.12

mail/dovecot/Portfile, mail/mail-server/Portfile, mail/mail-server/files/prefix/var/solr/dovecot/conf/schema.xml, mail/mail-server/files/prefix/var/solr/dovecot/conf/solrconfig.xml
Depends upon #29165
macOS x.y
Have you
=> mail-server: Upgrade to use apache-solr9

net/snac/Portfile
=> snac: update to 2.82

python/py-pyside6/Portfile
Moves the extra modules and configuration files to default variants. PySide version not changed, revision bumped.
Have you
=> py-pyside6: updated variants and default variants, revbump

graphics/MoltenVK/Portfile
=> MoltenVK: update to 1.4.0

lang/libomp/Portfile
=> libomp: 21.1.0

java/jarviz/Portfile
=> jarviz: install shell completions

lang/swi-prolog-devel/Portfile
=> swi-prolog-devel: Updated to version 9.3.30

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.22.0

science/proxmark3-iceman/Portfile
Updates package to upstream version 4.20728. It also:
- Changes required Python version to 3.12 (verified with upstream maintainer)
- Adds Python dependencies that the upstream requires for some of its tool binaries
- Adds more hardware variants
Have you
=> proxmark3-iceman: update to v4.20728

sysutils/coreutils-uutils/Portfile
=> coreutils-uutils: update to 0.2.2

devel/eask-cli/Portfile
=> eask-cli: update to 0.11.8

fuse/macfuse/Portfile
=> macfuse: update to 5.0.6

devel/clang-uml/Portfile
=> clang-uml: new Portfile

java/openjdk24-zulu/Portfile
Mark Azul Zulu 24 as having reached End of Life.
=> openjdk24-zulu: mark as end of life

devel/golines/Portfile
=> golines: update to 0.13.0

java/openjdk11-corretto/Portfile, java/openjdk17-corretto/Portfile, java/openjdk21-corretto/Portfile, java/openjdk22-corretto/Portfile, java/openjdk23-corretto/Portfile, java/openjdk24-corretto/Portfile, java/openjdk25-corretto/Portfile, java/openjdk8-corretto/Portfile
Update Amazon Corretto support dates.
=> openjdk*-corretto: update support dates

java/openjdk11-microsoft/Portfile, java/openjdk17-microsoft/Portfile, java/openjdk21-microsoft/Portfile
=> openjdk*-microsoft: add end of support dates

java/openjdk21-graalvm/Portfile, java/openjdk22-graalvm/Portfile, java/openjdk24-graalvm/Portfile, java/openjdk25-graalvm/Portfile
Add support dates voor GraalVM Community Edition ports.
=> openjdk*-graalvm: add support dates

devel/tevent/Portfile
=> tevent: update to 0.17.1

databases/tdb/Portfile
=> tdb: update to 1.4.14

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.23.6

devel/gradle/Portfile
=> gradle: add gradle8 subport

dotnet/aspnetcore-runtime-8/Portfile, dotnet/aspnetcore-runtime-9/Portfile, dotnet/aspnetcore-runtime-devel/Portfile, dotnet/dotnet-cli/Portfile, dotnet/dotnet-runtime-8/Portfile, dotnet/dotnet-runtime-9/Portfile, dotnet/dotnet-runtime-devel/Portfile, dotnet/dotnet-sdk-8/Portfile, dotnet/dotnet-sdk-9/Portfile, dotnet/dotnet-sdk-devel/Portfile
```
dotnet-sdk-devel        : update to rc.1.25451.107
dotnet-sdk-9            : update to 9.0.305
dotnet-sdk-8            : update to 8.0.414
dotnet-runtime-devel    : update to rc.1.25451.107
dotnet-runtime-9        : update to 9.0.9
dotnet-runtime-8        : update to 8.0.20
dotnet-cli              : update to 9.0.9
aspnetcore-runtime-devel: update to rc.1.25451.107
aspnetcore-runtime-9    : update to 9.0.9
aspnetcore-runtime-8    : update to 8.0.20
```
=> dotnet-{8,9,cli,devel}: update to latest versions

games/fheroes2/Portfile
=> fheroes2: update to 1.1.11

math/nauty/Portfile
=> nauty: update to 2.9.1

net/6tunnel/Portfile
Command Line Tools 12.5.1.0.1.162319612
Have you
=> 6tunnel: update to 0.14

math/m4ri/Portfile
Have you
- [] tested basic functionality of all binary files?
=> m4ri: update to 20250128

net/rpki-client/Portfile
=> rpki-client: update to 9.6

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.25.0

mail/rspamd/Portfile
=> rspamd: Update to version 3.13.0

sysutils/detox/Portfile
=> detox: update to 3.0.1

java/openjdk24-openj9/Portfile
=> openjdk24-openj9: update EOL date

sysutils/RHash/Portfile
=> RHash: new port

sysutils/podman/Portfile
=> podman: update to 5.6.1

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 26.26.1

devel/got/Portfile
=> got: update to 0.119

science/nco/Portfile
macOS 15.7
Xcode 26.0 / Command Line Tools 26.0.0
Have you
=> nco: update to 5.3.5

security/libressl/Portfile
=> libressl: update to 4.1.1

java/openjdk25-microsoft/Portfile
Add earliest end-of-support date.
=> openjdk25-microsoft: add earliest end-of-support date

devel/qt6-qtcreator/Portfile
macOS 15.6.1 24G90 x86_64
Have you
=> qt6-qtcreator: update to v17.0.2

sysutils/funky/Portfile
=> funky: update to  3.5.5

devel/got/Portfile
=> got: update to 0.120

games/lbreakout2/Portfile
=> lbreakout2: update to 2.6.5

games/bs/Portfile
=> bs: update to v2.13

net/openssh/Portfile
* closes https://trac.macports.org/ticket/73084
Have you
=> openssh: update to 10.1p1

devel/uncrustify/Portfile
=> uncrustify: update to v0.81.0

security/libressl-devel/Portfile
=> librssl-devel: update to 4.1.1
