devel/ruff/Portfile
Update `ruff` to its latest released version, 0.8.1
Have you
=> ruff: Update to 0.8.1

science/zfp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> zfp: update to 2024.11.26

databases/pspg/Portfile
Update, fix
macOS 10.6
Xcode 3.2
Have you
=> pspg: update to 5.8.7, fix for old systems

devel/libsdl2-powerpc/Portfile, devel/libsdl2-powerpc/files/0002-fix-x11.diff
Do not enable OpenGL by default, it causes troubles at least if using Mesa (and we cannot assume XQuartz is installed).
Tested with `ffplay6` (which uses SDL2 output).
In addition, a few trivial fixes to configure (to be on a safe side and use MacPorts libs and headers) and one macro (to enable cocoa for 10.7+ and not all non-powerpc, since cocoa of modern SDL2 does not build on 10.6.8 Intel, which is why there is a fallback port).
macOS 10.6
Xcode 3.2
Have you
=> libsdl2-powerpc: minor fix, revbump

sysutils/caps-log/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> caps-log: update to 1.2.1

audio/jack/Portfile
Nothing changes for clang-using systems (so no revbump). This only restores support for libstdc++ systems by adding `jack1` for them.
macOS 10.6
Xcode 3.2
Have you
=> jack: fallback to jack1 with libstdc++

audio/mp3cue/Portfile
Revbump
macOS 10.6
Xcode 3.2
Have you
=> mp3cue: revbump for libid3tag update

audio/cmus/Portfile
Revbump.
Fix dependency on ffmpeg7.
macOS x.y
Have you
=> cmus: revbump for libmad update

python/py-cdflib/Portfile, python/py-cftime/Portfile, python/py-cftime/files/patch-numpy-pyproject.toml.diff, python/py-geomagpy/Portfile, python/py-magpy/Portfile, python/py-netcdf4/Portfile, python/py-netcdf4/files/patch-numpy-pyproject.toml.diff, python/py-paho-mqtt/Portfile, python/py-pypubsub/Portfile
- remove `py-magpy` (PY27 only, no dependents) ; replaced by `py-geomagpy` (new port, py312 subport)
- new ports as dependents of `py-geomagpy`: `py-pypubsub` and `py-cdflib`
- `py-paho-mqtt`: update to 2.1.0, update Python subports
- `py-netcdf4`: update 1.72, drop py27 subport
- `py-cftime`: drop py27 subport
Have you
=> py-geomagpy: new port (remove py-magpy)

audio/mp3cat/Portfile, audio/mp3cat/files/implicit.patch, audio/mp3cat/files/patch-Makefile.diff
Update `mp3cat` to version 0.5, modernizing the Portfile with appropiate PortGroups, indentation, etc.
Have you
=> mp3cat: Update to 0.5

databases/xeus-sqlite/Portfile
Fix deps, allow building on powerpc as a consequence.
macOS 10.6
Xcode 3.2
Have you
=> xeus-sqlite: fix dependencies in the portfile

textproc/sgrep2/Portfile
Fix `sgrep2` building on Apple Silicon. Though [#26764](https://github.com/macports/macports-ports/pull/26764) was ultimately reverted, the fixes were simply applied to the wrong port.
Have you
=> sgrep2: Fix build on Apple Silicon

audio/libmp3splt/Portfile
Revbump
macOS 10.6
Xcode 3.2
Have you
=> libmp3splt: revbump for libmad update

audio/audacious-core/Portfile, audio/audacious-core/files/patch-big-endian.diff, audio/audacious-plugins/Portfile, audio/audacious-plugins/files/patch-big-endian.diff, audio/audacious/Portfile
Update, big-endian fix (we just restore what we had in 4.4 and 4.3.1).
P. S. Last attempt to fix BE builds with upstream did not go well, and we got a broken sound output in 4.4.1.
For now, revert those changes and use our patch which works correctly.
This has been tested and confirmed to work.
macOS 10.6
Xcode 3.2
Have you
=> audacious*: update to 4.4.2, fix big-endian back

lang/tcl/Portfile, x11/tk/Portfile, x11/tk/files/fix-aqua-i386-clang-crash.patch
Also change tk's default variant to +quartz, which better matches user expectations (see e.g. https://trac.macports.org/ticket/71359), matches the system Tk, and requires many fewer dependencies.
If you're wondering about the md5 and sha1 hashes, unfortunately that's all that upstream publishes.
Have you
=> Tcl/Tk: Update to 8.6.15

games/rebels-in-the-sky/Portfile
rebels-in-the-sky: Update to 1.0.25
Have you
=> rebels-in-the-sky: Update to 1.0.25

multimedia/libheif/Portfile
=> libheif: use fallback for 10.6

java/openjdk8-powerpc/Portfile, java/openjdk8/Portfile
Also make `openjdk8` a stub on powerpc, otherwise users try installing it and it expectedly fails.
P. S. @breun Please take a look. Hope this is fine, the change in the main port only concerns powerpc. Otherwise I got complaints when someone tried to install it and got a bunch of errors: it is not really evident that one should install `-powerpc` port and not the generic one.
macOS 10.6
Xcode 3.2
Have you
=> openjdk8-powerpc: update to 8u432

databases/libsql/Portfile, databases/libsql/files/0001-sqliteInt.h-fix-pointer-size-for-ppc64.patch
Update
P. S. @herbygillot While I am not gonna do that myself (approval will take forever), perhaps consider switching everything which depends on `sqlite3` to path-style dependency? Otherwise this port cannot be usable in MacPorts.
macOS 10.6
Xcode 3.2
Have you
=> libsql: update to 0.5.0

science/openmpi/Portfile, science/openmpi/files/portselect/openmpi-clang18, science/openmpi/files/portselect/openmpi-clang18-fortran, science/openmpi/files/portselect/openmpi-clang19, science/openmpi/files/portselect/openmpi-clang19-fortran, science/openmpi/files/portselect/openmpi-gcc14-fortran
Add `clang18`, `clang19`, and `gcc14` sub-ports to `openmpi`.
These sub-ports help addressing tickets like [this](https://trac.macports.org/ticket/70458).
Have you
=> openmpi: add clang18, clang19, and gcc14 sub-ports

net/gallery-dl/Portfile
gallery-dl: update to 1.28.0
Have you
=> gallery-dl: update to 1.28

audio/FAudio/Portfile
Update, orphan the port.
macOS 10.6
Xcode 3.2
Have you
=> FAudio: update to 24.12, drop maintainership

devel/openssl3/Portfile
clang-11-bootstrap does not build on older versions of Mac OS, so guard against it and let it use the normal 10.4 workarounds later in the script.
@neverpanic I'm thinking it would be relevant for you to take a look at this PR since you added the code that it's modifying.
See https://trac.macports.org/ticket/71442
(I didn't expect I would be submitting a PR when I created it)
macOS 10.4.11 8S2167 i386
Xcode 2.5
Have you
=> openssl3: Fix building on 10.4 Intel

devel/ddev/Portfile
Update ddev to version 1.24.0
- PHP 8.4.1 included
- New drupal11 project type
- Smaller ddev-webserver image
- Various bug fixes and improvements
=> ddev: update to 1.24.0

sysutils/lima/Portfile
=> lima: update to 1.0.2

x11/tk/Portfile
See: https://trac.macports.org/ticket/71444
Unbreak the port after recent update
macOS 10.6
Xcode 3.2
Have you
=> tk: do not switch to quartz on 32-bit where it fails

graphics/vtk/Portfile, graphics/vtk/files/patch-MACH_TASK_BASIC_INFO.diff, graphics/vtk/files/patch-fix-DataObjectBackendInterface.diff, graphics/vtk/files/patch-libxml2-getentropy.diff
@Dave-Allured FYI
macOS 10.6
Xcode 3.2
Have you
=> vtk: fix build of 9.4.0 for legacy OS

python/py-owslib/Portfile, python/py-pytest-env/Portfile, python/py-rasterstats/Portfile
Updates:
- py-owslib: update to 0.32.0 (and pins 0.31.0 to Python 3.9)
- py-pytest-env: update to 1.1.5
- py-rasterstats: update to 0.20.0
macOS x.y
Have you
=> py-rasterstats, py-owslib, py-pytest-env: updates

lang/gcc7-bootstrap/Portfile, lang/gcc7-bootstrap/files/patch-gcc7-tiger-intel.diff
small patch isolated to Intel Tiger to fix the build of the gcc7-boostrap
@kencu is the original author of this fix, I'm simply copying it from `gcc7` to `gcc7-bootstrap`.
See 084e2e8809afc62472eafc9c098b4bc9249b48b0
Previously this port would fail to build which prevented a whole host of other packages from being build as they depend on it for being build them selfs. I don't expect a version bump is needed for this as no one would have been able to install it before hand.
macOS 10.4.11
Xcode 2.5 / Command Line Tools x.y.z
Have you
=> gcc7-bootstrap: fix build on Intel Tiger

kde/tellico/Portfile
[skip ci]
KDE4 ports won’t build due to broken dependencies, and also this change is inconsequential for all systems for which buildbots exist, since 10.6 Intel uses clang-11 in MacPorts by default, not gcc-4.2.
Fix build on old systems.
macOS 10.6
Xcode 3.2
Have you
=> tellico: avoid old Xcode gcc, it fails to build this

devel/ddev/Portfile
Fix Trac ticket #71373
Add default case for go_arch variable to allow parsing on all architectures
=> ddev: fix parsing on unsupported architectures

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.6
Have you
=> uv: Update to 0.5.6

science/gildas/Portfile, science/gildas/files/patch-admin-Makefile.build.diff, science/gildas/files/patch-admin-Makefile.python.diff, science/gildas/files/patch-admin-python-config-ldflags.py.diff
=> Gildas: update to 202412a

audio/rsgain/Portfile
=> rsgain: use legacysupport.use_mp_libcxx on Mojave and older

gis/JOSM/Portfile
=> josm: update to 19265

devel/koio/Portfile, devel/koio/files/patch-meson.build.diff
New port
macOS 10.6
Xcode 3.2
Have you
=> koio: new port in devel

archivers/draco/Portfile, archivers/draco/files/patch-gltf_utils.h.diff
Fix
macOS 10.6
Xcode 3.2
Have you
=> draco: fix build with gcc

sysutils/mise/Portfile
mise: Update to 2024.12.0
Have you
=> mise: Update to 2024.12.0

security/pkcs11-provider/Portfile
=> pkcs11-provider: Update to 0.6

devel/Bear/Portfile
Drop platforms line, which re-specifies the default.
Have you
=> Bear: Update to 3.1.5

tex/latexmk/Portfile
=> latexmk: Update to 4.85

lang/gcc14/Portfile, lang/gcc14/files/darwin-ppc-fpu.patch
This patch is from upstream gcc commit at:
https://github.com/gcc-mirror/gcc/commit/1cfe4a4d0d4447b364815d5e5c889deb2e533669
Per @barracuda156, this is needed for gfortran on ppc. See https://github.com/macports/macports-ports/pull/26655#issuecomment-2481208553
Untested
macOS x.y
Have you
=> gcc14: Add ppc FPU patch

devel/epoll-shim/Portfile
https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/282593/steps/install-port/logs/stdio
Have you
=> epoll-shim: bump legacysupport to 15 for clock_gettime

python/py-progressbar/Portfile
Add Python 3.13 support.
Have you
=> py-progressbar: add support for Python 3.13

security/libressl/Portfile
Marking as draft, as my environment forces to use OpenSSL.
Any help would be appreciated.
Have you
=> libressl: re-fix build on macOS < 10.14

math/plfit/Portfile, math/plfit/files/patch-fix-linking-gcc.diff
1. Tests are broken, since the build does not find dylibs.
2. Build fails to link with gcc due to invalid linker argument.
macOS 10.6
Xcode 3.2
Have you
=> plfit: fix running tests, fix build with gcc

devel/libcddb/Portfile, devel/libcddb/files/patch-fix-log-headers.diff
Also clean-up portfile.
P. S. All other headers use `#define SOME_HEADER_H 1`, hence here too.
macOS 14.7
Xcode 15.4
Have you
=> libcddb: fix typo in two headers

databases/postgresql95/Portfile, databases/postgresql95/files/patch-xml_c.diff
Fixes:
* https://www.postgresql.org/message-id/attachment/152769/v1-0001-Make-PostgreSQL-work-with-newer-version-of-libxml.patch
* https://lists.macports.org/pipermail/macports-dev/2024-November/045952.html
macOS x.y
Have you
=> postgres95: Bugfix, Make PostgreSQL work with newer libxml2

aqua/qt5/Portfile, aqua/qt511/Portfile, aqua/qt513/Portfile, aqua/qt53/Portfile, aqua/qt55/Portfile, aqua/qt56/Portfile, aqua/qt57/Portfile, aqua/qt58/Portfile, aqua/qt59/Portfile
I was able to build the qt5-psql-plugin against postgresql16 successfully and confirmed the plugin binary was correctly linked against postgresql16. However, I didn't test any functionality. I also tried to build qt57 to test the plugin but couldn't get the qt base package to build at all. Maybe a consequence of the new xcode?
Have you
=> qt5: update postgresql variants

python/py-bitmath/Portfile
Add support for Python 3.13.
Have you
=> py-bitmath: add support for Python 3.13

graphics/QCSXCAD/Portfile, python/py-mayavi/Portfile, science/AppCSXCAD/Portfile, science/gdcm/Portfile, science/nektarpp/Portfile, science/openEMS/Portfile, textproc/CSXCAD/Portfile
* Rev bump for 7 library dependents of port VTK.
* Follows the VTK update 9.3.1 --> 9.4.0 in #26773.
* See previous conversation in draft PR #26823.
* Some dependents are broken for other reasons, and will continue to fail builds.
CI only.  Some builds failed.
Have you
=> Rev bumps for VTK update to 9.4.0

python/py-mac-alias/Portfile
Add Python 3.13 support.
Have you
=> py-mac-alias: add Python 3.13 support

python/py-makelive/Portfile
Add Python 3.13 support.
Have you
=> py-makelive: add Python 3.13 support

python/py-bitstring/Portfile
Update to 4.2.3, add subport for Python 3.13.
Have you
=> py-bitstring: update to 4.2.3, add subport for Python 3.13

python/py-applescript/Portfile
Add subport for Python 3.13.
Have you
=> py-applescript: add subport for Python 3.13

python/py-osxmetadata/Portfile
Update to 1.4.0, added subport for Python 3.13.
Have you
=> py-osxmetadata: update to 1.4.0

devel/epoll-shim/Portfile
=> epoll-shim: blacklist clang < 800

lang/python310/Portfile, lang/python311/Portfile, lang/python312/Portfile, lang/python313/Portfile, lang/python314-devel/Portfile, lang/python39/Portfile
On Tiger, the modern `ttyname_r` signature is not available without this define.
Fixes Python v3.9+ build on Tiger with gcc14.
Older Python versions are not affected because `ttyname_r` is only used since Python v3.9+.
Verified with gcc14 from #26655.
This was not an error on earlier gcc versions (it  was only a warning).
Tested with:
* 3.9 - ✅ https://glebm.github.io/macports-tiger-ppc-binary-archives/dist/python39
* 3.10 - ✅ https://glebm.github.io/macports-tiger-ppc-binary-archives/dist/python310
* 3.11 - ✅ https://glebm.github.io/macports-tiger-ppc-binary-archives/dist/python311
* 3.12 - ✅ https://glebm.github.io/macports-tiger-ppc-binary-archives/dist/python312
* 3.13 - ❌ fails due to https://trac.macports.org/ticket/71206
* 3.14-devel - ❌ same as 3.13 
I've also filed …
=> python39+: fix `ttyname_r` build error on Tiger gcc14

python/py-bpylist2/Portfile
Add subport for Python 3.13.
Have you
=> py-bpylist2: add Python 3.13 subport

python/py-cgmetadata/Portfile
Update to 0.2.0, add Python 3.13 subport.
Have you
=> py-cgmetadata: update to 0.2.0, add Python 3.13 subport

python/py-blessed/Portfile
=> py-blessed: add Python 3.13 subport

python/py-uc-micro-py/Portfile
=> py-uc-micro-py: add Python 3.13 subport

python/py-arpeggio/Portfile
=> py-arpeggio: add Python 3.13 subport

python/py-mdit-py-plugins/Portfile
Update to 0.4.2, add Python 3.13 subport.
Have you
=> py-mdit-py-plugins: update to 0.4.2, add Python 3.13 subport

python/py-mdurl/Portfile
=> py-mdurl: add Python 3.13 subport

python/py-pathvalidate/Portfile
Update to 3.2.1, add Python 3.13 subport.
Have you
=> py-pathvalidate: update to 3.2.1, add Python 3.13 subport

python/py-feedparser/Portfile
closes: https://trac.macports.org/ticket/70091
closes: https://trac.macports.org/ticket/70520
macOS x.y
Have you
=> py-feedparser: correct python 27; use pypi instead of github

python/py-wurlitzer/Portfile
=> py-wurlitzer: add Python 3.13 subport

python/py-ptpython/Portfile, python/py-ptpython/files/py313-ptpython
Update to 3.0.29, add Python 3.13 subport.
Have you
=> py-ptpython: update to 3.0.29, add Python 3.13 subport

audio/rsgain/Portfile, audio/rsgain/files/0001-rsgain.cpp-use-C-cmath.patch
The last update has broken build with gcc (upstream bug). Fix that.
macOS 10.6
Xcode 3.2
Have you
=> rsgain: fix the build after legacysupport added

python/py-xdg-base-dirs/Portfile
Update to 6.0.2, add Python 3.13 subport.
Have you
=> py-xdg-base-dirs: update to 6.0.2, add Python 3.13 subport

python/py-pytimeparse2/Portfile
=> py-pytimeparse2: add Python 3.13 subport

python/py-shortuuid/Portfile
=> py-shortuuid: add Python 3.13 subport

science/hmmer/Portfile
gcc-4.2 errs out on Altivec code here.
macOS 10.6
Xcode 3.2
Have you
=> hmmer: fix build on powerpc

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.7
Have you
=> uv: Update to 0.5.7

python/py-photoscript/Portfile
Update to 0.4.0, add Python 3.13 subport.
Have you
=> py-photoscript: update to 0.4.0, add Python 3.13 subport

python/py-textx/Portfile
Update to 4.1.0, add Python 3.13 subport.
Have you
=> py-textx: update to 4.1.0, add Python 3.13 subport

science/aptdec/Portfile
Fix
macOS 10.6
Xcode 3.2
Have you
=> aptdec: fix build with Xcode gcc

textproc/less/Portfile
=> less: update to 668

python/py-linkify-it-py/Portfile
=> py-linkify-it-py: add Python 3.13 subport

python/py-markdown-it-py/Portfile
=> py-markdown-it-py: add Python 3.13 subport

python/py-pkginfo/Portfile
=> py-pkginfo: update to 1.12.0

python/py-strpdatetime/Portfile
Update to 0.4.0, add Python 3.13 subport.
Have you
=> py-strpdatetime: update to 0.4.0, add Python 3.13 subport

python/py-utitools/Portfile
New port for utitools, which is a dependency for the latest osxphotos versions.
Have you
=> py-utitools: new submission

python/py-wxpython-4.0/Portfile
Fix ScreenCaptureKit Error
* Added check for macos 15 deployment target and set target to 14
macOS 15.1.1 24B91
Have you
=> py-wxpython-4.0: Fix ScreenCaptureKit Error

sysutils/mise/Portfile
mise: Update to 2024.12.3
Have you
=> mise: Update to 2024.12.3

multimedia/QMPlay2/Portfile
Update
macOS 14.7.1
Xcode 15.4
Have you
=> QMPlay2: update to 24.12.06 for new systems

devel/qbs/Portfile
=> qbs: Update to 2.5.0

_resources/port1.0/compilers/gcc_compilers.tcl, _resources/port1.0/compilers/gcc_dependencies.tcl, _resources/port1.0/group/R-1.0.tcl, _resources/port1.0/group/compilers-1.0.tcl, lang/gcc-devel/Portfile, lang/gcc10/Portfile, lang/gcc14/Portfile, lang/gcc14/files/darwin8-define-PTHREAD_RWLOCK_INITIALIZER.patch, lang/gcc14/files/darwin8-ttyname_r.patch, lang/gcc7/Portfile, lang/gcc9/Portfile, lang/libgcc/Portfile, math/R/Portfile
gcc7 is obsolete at this point and fails to build a lot of software. Enables gcc14 for all platforms and sets it as default.
gcc14 is built using gcc10-bootstrap on 10.4 and 10.5.
Before I go ahead with trying to build this (in qemu it takes a very long time), I'd like to ask someone more knowledgeable like @kencu and @barracuda156 to have a look (this is my very first PR to macports!), so I'm creating this PR as a draft.
This PR is based on what I've seen in #16843 by @barracuda156 and https://github.com/macports/macports-ports/commit/9aa2182afcd93d2baeffc480c0b19067c1717bc6 by @kencu and is completely untested.
macOS 10.4.11 8S165 Power Macintosh
Have you
=> Make gcc14 the primary version on Tiger+

devel/tevent/Portfile
=> tevent: fix compiler choice

lang/gcc10/Portfile
@kencu No need revbump, given that no one could have built it yet in 10 min, right?
macOS x.y
Have you
=> gcc10: use correct triples on powerpc*

mail/libvmime/Portfile, mail/libvmime/files/patch-AI_NUMERICSERV.diff
Closes: https://trac.macports.org/ticket/71487
Minor fix for old systems
macOS 10.6
Xcode 3.2
Have you
=> libvmime: fix for old systems

textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.7.0
Have you
=> ocrmypdf: update to 16.7.0

python/py-lesscpy/Portfile
Update `lesscpy` to its latest released version, 0.15.1, adding subports for Python 3.11 and 3.12
Have you
=> py-lesscpy: Update to 0.15.1

lang/lua/Portfile
Lua uses `localtime_r` and `gmtime_r`, which require legacy-support on Tiger.
Fixes Lua on Tiger (tested with lua54).
macOS 10.4.11 8S165 Power Macintosh
Have you
/cc @AJenbo
=> lua: add legacy-support for Tiger

sysutils/mise/Portfile
mise: Update to 2024.12.4
Have you
=> mise: Update to 2024.12.4

python/py-rich/Portfile
=> py-rich: add Python 3.13 subport

python/py-rich-theme-manager/Portfile
Add Python 3.13 subport, removed Python 3.8 (EOL) subport.
Have you
=> py-rich-theme-manager: add Python 3.13 subport, remove Python 3.8 (EOL) subport

devel/google-benchmark/Portfile
Adds a package for https://github.com/google/benchmark
Component versions: DevToolsCore-798.0; DevToolsSupport-794.0
Have you
/cc @AJenbo
=> google-benchmark: new package

net/samba4/Portfile, net/samba4/files/patch-vfs_default.c.diff
Fix build with gcc14 and on older systems
macOS 10.6
Xcode 3.2
Have you
=> samba4: fix build with gcc14 and on older OS

comms/lrzsz/Portfile
closes: https://trac.macports.org/ticket/70755
Resovles clang 16 breaking change that affects C functions with no declared return type.
The clang 16 change broke the lrzsz configure script. This change detects the clang version
and adds -Wno-implicit-int for clang version >= 16.
Note that addition of the -Wno-implicit-int clang flag is the same resolution as that was
used by homebrew to resolve this lrzsz problem.
Have you
=> lrzsz: update to support clang 16

science/dcm2niix/Portfile
Fixes https://trac.macports.org/ticket/71509
=> dcm2niix: Fix openjpeg usage; add batch tool.

graphics/inkscape/Portfile
Since a5bed96ea30dd136434b63fc7e5a885d3a393086, installing the libsoup port no longer automatically pulls in libsoup-2.4, but inkscape requires the latter. Adjust the dependency spec to match.
Have you
=> inkscape: Fix dependency on libsoup 2.4

python/py-emmet-core/Portfile, python/py-maggma/Portfile, python/py-mongomock/Portfile, python/py-mp-api/Portfile, python/py-pycifrw/Portfile, python/py-pydash/Portfile, python/py-pyqtgraph/Portfile, python/py-sentinels/Portfile, python/py-smart-open/Portfile, python/py-sqlalchemy-utils/Portfile, python/py-sshtunnel/Portfile, python/py-xraylarch/Portfile
This PR supersedes #25157. @joefowler this includes the update to the latest upstream version and adds (recursively) the required dependencies. 
I have no interest in maintaining these ports, but would be happy to add you as maintainer if you wish to do so and keep things up-to-date; please let me know.
I added a `gui` variant as on the latest macOS version the `py-wxpython-4.0` port does not build and would thus prohibit the port to be installed. There is/are Trac ticket(s) for that; I did take a quick look but couldn't fix it in the time I'm willing to spend on it...
Have you
=> py-xrachlarch: update to 0.9.81; add missing dependencies

security/libressl-devel/Portfile
Backport of the fix added in #26827. Once again, it fails to test correctly due to a conflict with OpenSSL.
Have you
=> libressl-devel: re-fix build on macOS < 10.14

python/py-jaraco.classes/Portfile, python/py-jaraco.functools/Portfile
=> Update py-jaraco packages

devel/sealcurses/Portfile, net/lagrange/Portfile
https://github.com/skyjake/lagrange/releases/tag/v1.18.4
Xcode 14.2
Have you
=> lagrange: update to 1.18.4

python/py-openbabel2/Portfile, science/openbabel2/Portfile, science/openbabel2/files/patch-fix-wxWidgets-search.diff
Closes: https://trac.macports.org/ticket/71480
Fix this finally.
(Revbump due to opportunistic usage of wxWidgets, not due to C++ standard.)
macOS 10.6
Xcode 3.2
Have you
=> openbabel2: fix C++ standard, fix opportunistic usage of wxWidgets

python/py-tenacity/Portfile
Update to 9.0.0, add Python 3.13 subport.
Have you
=> py-tenacity: update to 9.0.0, add Python 3.13 subport

databases/postgresql17-server/Portfile, databases/postgresql17/Portfile
=> postgresql17: update to 17.2

science/opencascade/Portfile, science/opencascade/files/patch-StdPrs_BRepFont.cxx.diff
* Closes: https://trac.macports.org/ticket/71233
* Fixes "error: cannot initialize a variable of type 'const char *' with an rvalue of type 'unsigned char *'"
* See:  https://github.com/Open-Cascade-SAS/OCCT/discussions/48
* Apply upstream patch.
* https://git.dev.opencascade.org/gitweb/?p=occt.git;a=commitdiff;h=7236e83dcc1e7284e66dc61e612154617ef715d6;hp=099e0d25243925da349d43e6e1ee0528763cdabe#patch1
CI only.
Have you
=> opencascade: Fix build, initialization error

emulators/dosbox-x/Portfile
Update to dosbox-x 2024.12.04
Have you
=> dosbox-x: update to 2024.12.04

devel/liboqs/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> liboqs: update to 0.12.0

devel/fizz/Portfile
Revbump
macOS 10.6
Xcode 3.2
Have you
=> fizz: revbump for liboqs update

net/scamper/Portfile
Update `scamper` to its latest released version, 20241112. This PR serves to modernize the Portfile, properly specifying maintainers, using PortGroups, etc.
As a note for one of the maintainers being removed, see [this Trac ticket](https://trac.macports.org/ticket/70553). Only one maintainer has vowed to be maintainer, so only one should be kept.
Have you
=> scamper: Update to 20241112

audio/xmms2/Portfile
Fix dependencies further.
Samba in a variant, since samba3 conflicts with samba4, we do not want that by default.
Disabling only `mdns` but leaving `daap` enabled in meaningless, since both use `avahi`. Join them together in one variant.
Add other dependencies which the port links to via plugins.
macOS 10.6
Xcode 3.2
Have you
=> xmms2: another go with fixing opportunistic linking

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 503.0.0.
Have you
=> google-cloud-sdk: update to 503.0.0

sysutils/mise/Portfile
mise: Update to 2024.12.6
Have you
=> mise: Update to 2024.12.6

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.8
Have you
=> uv: Update to 0.5.8

science/Gyoto/Portfile
@ryandesign This fixes it
macOS 10.6
Xcode 3.2
Have you
=> Gyoto: fix the build with libstdc++

graphics/OpenSceneGraph/Portfile, graphics/h3dutil/Portfile, graphics/openimageio/Portfile
Bump ports which link against DCMTK.
=> dcmtk: Bump linking dependents for 3.6.9

sysutils/mise/Portfile
mise: Update to 2024.12.7
macOS 15.1.1 24B2091 arm64
Have you
=> mise: Update to 2024.12.7

net/wget/Portfile
In order to reduce the dependencies of wget, make metalink support optional via a variant. Currently, wget is the only port that depends on libmetalink and metalink support is disable on most Linux distributions in wget and curl.
Re: https://trac.macports.org/ticket/69601
Closes: https://trac.macports.org/ticket/71523
Have you
=> wget: make metalink support a variant

ruby/ruby-build/Portfile
ruby-build: Update to 20241213
macOS 15.1.1 24B2091 arm64
Have you
=> ruby-build: Update to 20241213

sysutils/mise/Portfile
mise: Update to 2024.12.8
Have you
=> mise: Update to 2024.12.8

multimedia/VLC2/Portfile, multimedia/VLC2/files/patch-AudioComponent.diff, multimedia/VLC2/files/patch-SystemConfiguration.diff
Fix some issues which prevented it building on 10.5.8.
No need in revbump, since all changes are only used on < 10.6, where it did not build before.
macOS 10.5.8
Xcode 3.1.4
Have you
=> VLC2: add a fix for < 10.6

sysutils/nut/Portfile, sysutils/nut/files/patch-legacy-macos.diff
Closes: https://trac.macports.org/ticket/71514
Fix build
macOS 10.6
Xcode 3.2
Have you
=> nut: fix build on legacy macOS

science/hackrf/Portfile
hackrf: Update to 2024.02.1
hackrf-devel: Update to 20241205-db884152
Have you
=> hackrf: Update to 2024.02.1; hackrf-devel: Update to 20241205-db884152

gnome/tracker3/Portfile
Unbreak the build after https://github.com/macports/macports-ports/commit/49a25be1045bc2abc8857b953582c878756fcf04
The port does not need C++11, however it uses C11 features and fails to build with a C99 compiler.
P. S. @mohd-akram @kencu If you consider that the failure is not due to C11 being required, alternative fix would be to blacklist Xcode gcc, since MacPorts considers it to be C99-capable, and it fails to build this port. So what we have now is wrong in any case.
macOS 10.6
Xcode 3.2
Have you
=> tracker3: fix compiler choice

sysutils/mise/Portfile
mise: Update to 2024.12.10
Have you
=> mise: Update to 2024.12.10

java/mvnd2/Portfile
Until 2.0.0 is out, use a version that sorts before 2.0.0.
=> mvnd2: use rc version

java/micronaut/Portfile
Update to Micronaut Starter 4.7.2.
Have you
=> micronaut: update to 4.7.2

graphics/jpeg2png/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
=> jpeg2png: fix build with gcc

textproc/rarian/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
=> rarian: use C++11 to unbreak the build

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.9
Have you
=> uv: Update to 0.5.9

audio/qmmp/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> qmmp: update to 0.12.20 for qt4

graphics/vtk/Portfile
Port vtk is currently configured to use many bundled (built-in) third party libraries. Therefore, external dependencies are redundant and should be removed to simplify builds.
* I DID check that all generated distfiles are functionally identical, by binary comparison.
* I did NOT analyze or change dependencies within declared variants.
* I did NOT check for run dependencies.
* No rev bump because only changes are unused dependencies, or related to them.
Command Line Tools 15.3.0
Have you
=> vtk: Remove unused dependencies

java/maven4/Portfile, java/maven4/files/maven4
New port for Apache Maven 4.
Have you
=> maven4: new submission

graphics/libgeotiff/Portfile
- libgeotiff: update to 1.7.3
- libgeotiff: use latest version of PROJ (drop proj variants)
Have you
=> libgeotiff: update to 1.7.3 and use latest PROJ

graphics/libsixel/Portfile, x11/mlterm/Portfile, x11/mlterm/files/patch-clipboard.diff
Sort out dependencies, fix config args for fribidi variant, add support for images rendering via `libsixel`.
macOS 10.6
Xcode 3.2
Have you
=> mlterm: misc improvements, revbump

graphics/osm-gps-map/Portfile
=> osm-gps-map: fix libsoup dependency

sysutils/mise/Portfile
mise: Update to 2024.12.11
Have you
=> mise: Update to 2024.12.11

graphics/jpeg-quantsmooth/Portfile, graphics/jpeg-quantsmooth/files/patch-Makefile.patch
Fix the build
macOS 10.6
Xcode 3.2
Have you
=> jpeg-quantsmooth: fix build with gcc and for ppc

lang/python314-devel/Portfile, lang/python314-devel/files/patch-hacl-compatibility.diff
=> python314-devel: add compatibility patches for macOS < 10.15

sysutils/colima/Portfile
colima: Update to 0.8.1
Have you
=> colima: Update to 0.8.1

security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.559
Have you
=> ipsw: Update to 3.1.559

devel/tre/Portfile
Update `tre` to its latest released version, 0.9.0. This change dictatest an upstream change, [per this blog post by the author](https://laurikari.net/tre/tre-on-github/).
Before this update, this port didn't ship a statically-linked library along with a dynamically linked one. Unsure if that should be the case now (since its possible)
Have you
=> tre: Update to 0.9.0

perl/p5-getopt-argvfile/Portfile
new port of Perl5 Getopt::ArgvFile module
Have you
=> p5-getopt-argvfile: new port (version 1.11)

science/ccfits/Portfile
Fix build
macOS 10.6
Xcode 3.2
Have you
=> ccfits: fix C++ standard

editors/scite/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> scite: update to 4.4.6

net/liboping/Portfile, net/liboping/files/devel-patch-oping.c.diff, net/liboping/files/patch-oping.c.diff
Fix build
macOS 10.6
Xcode 3.2
Have you
=> liboping*: fix building, update -devel subport

java/maven4/Portfile
Update to Maven 4.0.0-rc-2.
Have you
=> maven4: update to 4.0.0-rc-2

aqua/qt5/Portfile
macOS 15.1.1 24B2091 arm64
Have you
=> qt5*: fix build with ICU 76

_resources/port1.0/group/python-1.0.tcl, python/py-acor/Portfile, python/py-bigfloat/Portfile
_This does not change anything for Pythons themselves;_ this simply extends requirement for C11 from Python 3.13 to py313 packages, otherwise those fail to build, since Python 3.13 checks for C11 atomics and does not find it for old Xcode gcc.
@reneeotten I do not know how wide is c99 requirement for python312, it may be that many ports pass `-std=c99` anyway from upstream code, or it is a recent change, or I did not build affected ports earlier. Do you think this rather should also be done via PG?
Since pythons 311+ themselves cannot be built with pre-C11 compilers anyway, it may also be okay just to require it for py312+ ports, though it is not a requirement with py312- ones, strictly speaking.
macOS 10.6
Xcode 3.2
Have you
=> python PortGroup: require C11 with py313 packages due to atomics requirement, adjust a few subports

shells/bash/Portfile
This doesn't have a fix for https://trac.macports.org/ticket/68638 . I made an initial attempt to cherry-pick that patch but it seemed hairy enough it's probably not worth maintaining.
But, to throw the affected a bone, I have added the bash-devel port that pulls in the latest devel branch. The fix is not in the 5.3-alpha release.
I didn't put this in as a Closes: because it doesn't really close the issue but can be persuaded if anyone feels strongly.
Have you
=> bash: update to 5.2 patch 37, bash-devel: new port

sysutils/mise/Portfile
mise: Update to 2024.12.13
Have you
=> mise: Update to 2024.12.13

devel/google-cloud-sdk/Portfile
Update to Google Cloud 504.0.0.
Have you
=> google-cloud-sdk: update to 504.0.0

editors/kakoune/Portfile, editors/kakoune/files/patch-fix-prefix.diff
Closes: https://trac.macports.org/ticket/71584
Fix installation
macOS 10.6
Xcode 3.2
Have you
=> kakoune: fix install prefix, revbump

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.10
Have you
=> uv: Update to 0.5.10

shells/oksh/Portfile
Update oksh to version 7.6
Have you
=> oksh: update to version 7.6

graphics/libgeotiff/Portfile
Fix build after update
macOS 10.6
Xcode 3.2
Have you
=> libgeotiff: fix build with Xcode gcc

graphics/osxphotos/Portfile
Update to osxphotos 0.69.2.
Have you
=> osxphotos: update to 0.69.2

sysutils/mise/Portfile
mise: Update to 2024.12.14
Have you
=> mise: Update to 2024.12.14

java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.4.1.
Have you
=> spring-boot-cli: update to 3.4.1

multimedia/ffmpeg-devel/Portfile
This restores the previous behavior of ffmpeg-devel.
Have you
=> ffmpeg-devel: don't install in separate prefix

gnome/yelp-tools/Portfile
Revbump, because it was not a build error.
macOS 10.6
Xcode 3.2
Have you
=> yelp-tools: fix broken installation, revbump

devel/ruff/Portfile
Update `ruff` to its latest released version, 0.8.4
Have you
=> ruff: Update to 0.8.4

cross/mingw-w64-wine-mono/Portfile
=> mingw-w64-wine-mono: new subport 9.4.0

net/tcpflow/Portfile, net/tcpflow/files/patch-configure.ac-devel.diff, net/tcpflow/files/patch-fix-includes.diff, net/tcpflow/files/patch-fix-macOS-build.diff
Fix build with gcc14, update -devel subport.
macOS 10.6
Xcode 3.2
Have you
=> tcpflow: fix gcc build; tcpflow-devel: update to 20240919

_resources/port1.0/group/fortran-1.0.tcl, fortran/fitpack/Portfile
Also allow git-devel.
_This PG uses gcc-13 presently, so it will fail on macOS 14, like in a case of R._
macOS 10.6
Xcode 3.2
Have you
=> fitpack: update to 0.2.0

python/py-blis/Portfile, python/py-cymem/Portfile, python/py-murmurhash/Portfile, python/py-preshed/Portfile, python/py-srsly/Portfile, python/py-thinc/Portfile
Also for `py-srsly` blacklist Xcode gcc.
macOS 10.6
Xcode 3.2
Have you
=> py-thinc and friends: drop unneeded hardcoding of archs

python/pipenv/Portfile
I'm updating the dependencies because those are the four packages that are specified as build-time dependencies in the wheel (see https://github.com/pypa/pipenv/blob/main/pyproject.toml#L32 ).
Have you
=> pipenv: update to 2024.4.0

net/nxcomp/Portfile
This restores old behavior where VERSION file was move at "pre-build" time, rather than "post-patch". VERSION is used to fill in version number. It's currently broken and version ends up being "0.0.0.0".
Have you
=> nxcomp: Restore old 'VERSION' move behavior

net/nxcomp/Portfile, net/nxcomp/files/bind.patch, net/nxcomp/files/patch-nxproxy_src_Makefile.am-use-system-libXcomp.diff
This allows files in the top-level dir, like version.sh, to be patched, should the need arise.
Have you
=> nxcomp: Reorganize so patch.dir is top-level dir

devel/meson/Portfile, python/py-meson/Portfile
* Update Meson to 1.6.1, as the latest release includes an important ld-related fix
* Fixes: [70386 - glib2 @2.78.4_0+x11: ld: unknown option: -export_dynamic](https://trac.macports.org/ticket/70386)
=> meson: update to 1.6.1; includes important fix for ld

devel/cmake/Portfile
* Bumps the version to 3.31.2 and updates the hashes.
Have you
=> cmake: update 3.31.2

sysutils/uptimed/Portfile, sysutils/uptimed/files/patch-libuptimed-urec.h.diff
Update `uptimed` to its latest released version, 0.4.6
Have you
=> uptimed: Update to 0.4.6

devel/onedpl/Portfile
Fix the build
macOS 10.6
Xcode 3.2
Have you
=> onedpl: set correct C++ standard

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 504.0.1.
Have you
=> google-cloud-sdk: update to 504.0.1

devel/libnick/Portfile, net/parabolic/Portfile
Update, add runtime deps
macOS 10.6
Xcode 3.2
Have you
=> libnick, parabolic: update to 2024.12.0

audio/mpg123/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> mpg123: update to 1.32.10

net/gallery-dl/Portfile
gallery-dl: update to 1.28.2
Have you
=> gallery-dl: update to 1.28.2

python/py-blis/Portfile, python/py-thinc/Portfile
Forgot to add this in the original PR. No reason to prohibit modern GCC here.
macOS 10.6
Xcode 3.2
Have you
=> py-blis, py-thinc: unblacklist modern gcc

sysutils/mdate/Portfile
Update `mdate` to 1.7.0.3. This change demands a new upstream change, evident by the use of the `github` PG
Have you
=> mdate: Update to 1.7.0.3

sysutils/mise/Portfile
mise: Update to 2024.12.17
Have you
=> mise: Update to 2024.12.17

python/py-pydantic/Portfile
Provide rust-free version for legacy systems
macOS 10.6
Xcode 3.2
Have you
=> py-pydantic: provide rust-free version for old systems

python/poetry/Portfile, python/py-cachecontrol/Portfile, python/py-cleo/Portfile, python/py-keyring/Portfile, python/py-poetry-core/Portfile, python/py-poetry-plugin-export/Portfile
=> poetry: update to 1.8.5

devel/ddev/Portfile
Update ddev to version 1.24.1
- Fix for PHP < 8.1 in environments with additional SSL certificates
- Restore SQLite 3.45.1 only for Drupal 11
- Add more default locales
- Other minor improvements
=> ddev: update to 1.24.1

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.11. Additonally, fix any opportunistic linking with `xz` and MacPort's `libiconv`
Have you
=> uv: Update to 0.5.11

security/rage/Portfile
Updates rage to [0.11.1](https://github.com/str4d/rage/releases/tag/v0.11.1). 
macOS 15.1.1 24B2091 arm64
Have you
=> rage: update to 0.11.1

sysutils/termscp/Portfile
https://github.com/veeso/termscp/releases
Xcode 14.2
Have you
=> termscp: update to 0.16.1

net/miniflux/Portfile
=> miniflux: update to 2.2.4

gis/GPXSee/Portfile
=> GPXSee: update to 13.33

sysutils/simplotask/Portfile
=> simplotask: update to 1.16.3

net/wcurl/Portfile
Update `wcurl` to its latest released version, 2024.12.08
Have you
=> wcurl: Update to 2024.12.08

ocaml/opam/Portfile, ocaml/opam/files/patch-link-legacysupport.diff
=> opam: update to 2.3.0

devel/jenkins-cli/Portfile
https://github.com/jenkins-zh/jenkins-cli/compare/v0.0.42...v0.0.44
Xcode 14.2
Have you
=> jenkins-cli: update to 0.0.44

sysutils/mise/Portfile
mise: Update to 2024.12.19
Have you
=> mise: Update to 2024.12.19

security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.560
Have you
=> ipsw: Update to 3.1.560

lang/llvm-17/Portfile, lang/llvm-17/files/0130-10.14-and-less-availability.patch, lang/llvm-18/Portfile, lang/llvm-18/files/0130-10.14-and-less-availability.patch, lang/llvm-19/Portfile, lang/llvm-19/files/0130-10.14-and-less-availability.patch
After the [recent switch](https://github.com/macports/macports-ports/commit/c8cceb0dec2dfb15e3a54e38260a676cb59fc9af) of older OS versions to allow mp-clang-17 as the fallback compiler, [qt64-qtbase has stopped building on 10.14](https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/217224/steps/install-port/logs/stdio) with
```
Undefined symbols for architecture x86_64:
"__availability_version_check", referenced from:
___isPlatformVersionAtLeast in libclang_rt.osx.a(os_version_check.c.o)
__initializeAvailabilityCheck in libclang_rt.osx.a(os_version_check.c.o)
```
There is also https://trac.macports.org/ticket/68522 dealing with the same issue.
The reason is [this upstream clang change](https://reviews.llvm.org/D150397). It looks like a performance-only fix, and it does …
=> clang-{17,18,19}: unbreak `@available` on MacOS 10.14

devel/patchelf/Portfile
Update `patchelf` to its latest released version, 0.18.0
Have you
=> patchelf: Update to 0.18.0

math/z3/Portfile
Update
macOS 10.6
Xcode 3.2
Have you
=> z3: update to 4.13.4

java/micronaut/Portfile
Update to Micronaut Starter 4.7.3.
Have you
=> micronaut: update to 4.7.3

graphics/pdfpc/Portfile
Update, fix
macOS 10.6
Xcode 3.2
Have you
=> pdfpc: update to 4.7.0, fix build on powerpc

audio/ocp/Portfile, audio/ocp/files/patch-types.h.diff, audio/ocp/files/patch-xmload.c.diff
Revbump for `libmad`, also fix for old systems and gcc.
macOS 10.6
Xcode 3.2
Have you
=> ocp: revbump for libmad, use legacysupport

ruby/ruby-build/Portfile
ruby-build: Update to 20241225.2
Have you
=> ruby-build: Update to 20241225.2

sysutils/mise/Portfile
mise: Update to 2024.12.20
Have you
=> mise: Update to 2024.12.20

net/gping/Portfile
Update `gping` to its latest released version, 1.19.0
Have you
=> gping: Update to 1.19.0

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.12
Have you
=> uv: Update to 0.5.12

sysutils/lima/Portfile
lima: Update to 1.0.3
Have you
=> lima: Update to 1.0.3

net/sfeed/Portfile
https://git.codemadness.org/sfeed/log.html
Xcode 14.2
Have you
=> sfeed: update to 2.1

games/rebels-in-the-sky/Portfile
rebels-in-the-sky: Update to 1.0.27
Have you
=> rebels-in-the-sky: Update to 1.0.27

devel/qt6-qtcreator/Portfile
Portfile has been updated for the new Qt Creator version:
- build with cmake
- use clang-17 from macports instead of host clang
- remove unused patch clang16_Wenum_constexpr_conversion
- adapt patch no_qtwebengine for cmake
- use c++ standard 20 (defined in CMakeLists.txt)
- update Qt Creator.app build directory for destroot
- remove move libexec/QtProject to Resources (must be already there)
Have you
=> qt6-qtcreator: new port

sysutils/mise/Portfile
mise: Update to 2024.12.21
Have you
=> mise: Update to 2024.12.21

devel/uv/Portfile
Update `uv` to its latest released version, 0.5.13
Have you
=> uv: Update to 0.5.13

graphics/vtk/Portfile
vtk: Update 9.4.0 --> 9.4.1
CI only.  OS 13, 14 only.
Have you
=> vtk: Update to 9.4.1

irc/weechat/Portfile, irc/weechat/files/fix-linking.patch
Fix broken linking. Revbump, because all systems were affected.
Also switch to `legacysupport` 1.1.
macOS 10.6
Xcode 3.2
Have you
=> weechat: fix linking to correct libs

aqua/barrier/Portfile, aqua/barrier/files/0001-Add-missing-cstdint-header.patch, aqua/barrier/files/0002-libplatform-use-ObjC-flags-on-Apple.patch, aqua/barrier/files/0003-OSXScreen.mm-do-not-use-reserved-id-for-variables.patch, aqua/barrier/files/0004-basic_types.h-pull-in-cstdint-only-with-C.patch
Fix the build on systems using gcc
macOS 10.6
Xcode 3.2
Have you
=> barrier: fix build with gcc

devel/jenkins-cli/Portfile
https://github.com/jenkins-zh/jenkins-cli/releases/tag/v0.0.45
https://github.com/jenkins-zh/jenkins-cli/releases/tag/v0.0.46
Xcode 14.2
Have you
=> jenkins-cli: update to 0.0.46

java/openjdk24-zulu/Portfile
New port for Azul Zulu OpenJDK 24.
Have you
=> openjdk24-zulu: new submission

sysutils/mise/Portfile
mise: Update to 2024.12.22
Have you
=> mise: Update to 2024.12.22

sysutils/mise/Portfile
mise: Update to 2024.12.24
Have you
=> mise: Update to 2024.12.24

devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases/tag/v1.0.0
Xcode 14.2
Have you
=> jsoncons: update to 1.0.0

sysutils/mise/Portfile
mise: Update to 2025.1.0
Have you
=> mise: Update to 2025.1.0

graphics/xfig/Portfile, print/fig2dev/Portfile
Simple update to upstream version 3.2.9a for both `xfig` and `fig2dev`
I combined the two, since they are intrinsically linked.
I also replaced `nomaintainer` with myself and `openmaintainer`.
Have you
=> xfig and fig2dev: update to 3.2.9a

science/nco/Portfile
Simple update to upstream version 5.3.0
Have you
=> nco: update to 5.3.0

devel/symfony-cli/Portfile
=> symfony-cli: update to 5.10.6

dotnet/aspnetcore-runtime-2.1/Portfile, dotnet/aspnetcore-runtime-3.1/Portfile, dotnet/aspnetcore-runtime-6/Portfile, dotnet/aspnetcore-runtime-7/Portfile, dotnet/aspnetcore-runtime-8/Portfile, dotnet/aspnetcore-runtime-devel/Portfile, dotnet/dotnet-cli/Portfile, dotnet/dotnet-runtime-2.1/Portfile, dotnet/dotnet-runtime-3.1/Portfile, dotnet/dotnet-runtime-6/Portfile, dotnet/dotnet-runtime-7/Portfile, dotnet/dotnet-runtime-8/Portfile, dotnet/dotnet-runtime-devel/Portfile, dotnet/dotnet-sdk-2.1/Portfile, dotnet/dotnet-sdk-3.1/Portfile, dotnet/dotnet-sdk-6/Portfile, dotnet/dotnet-sdk-7/Portfile, dotnet/dotnet-sdk-8/Portfile, dotnet/dotnet-sdk-devel/Portfile
Many Microsoft links (A) offer localized content if the locale is removed, and (B) still work even if there is only English content.
=> Update dotnet links to be global

lang/clojure/Portfile
=> clojure: update to  1.12.0.1495

python/pipx/Portfile
pipx: change default variant to python313
This PR replaces #26990: resubmitting after January 1, 2025 per @reneeotten.
Have you
=> pipx: change default variant to python313

devel/rancher-cli/Portfile
=> rancher-cli: update to 2.10.1

graphics/librsvg-devel/Portfile, graphics/librsvg/Portfile
See: https://trac.macports.org/ticket/70693
Have you
=> librsvg, librsvg-devel: use fallback version on Snow Leopard

devel/appstream-glib/Portfile
Even though upsteam doesn't declare uuid as a dependency in appstream-glib, it won't start without ossp-uuid being installed.
Even though upstream doesn't declare uuid as a dependency in `appstream-glib`, it won't start without `ossp-uuid` being installed.
Have you
=> appstream-glib: fix missing ossp-uuid dependency

devel/spatialindex/Portfile, gis/qgis3/Portfile
Update:
- `qgis3`to 3.40.2
-  `qgis3-ltr`  to 3.34.14
-  `spatialindex` to 2.1.0
Have you
=> qgis3: update to 3.40.2; qgis3-ltr: update to 3.34.14

databases/postgis3/Portfile, gis/pdal/Portfile, gis/pgrouting/Portfile, gis/saga/Portfile
postgis3: update to 3.5.1
pgrouting: update to 3.7.1
saga: update to 9.7.0
pdal: update to 2.8.3
Have you
=> postgis3, pgrouting, saga, pdal: updates

python/py-lazy_loader/Portfile
Note: Python 3.13 is not in the list of supported Python versions on PyPI, but [this PR](https://github.com/scientific-python/lazy-loader/pull/139), which adds 3.13 support, only updates the documentation and makes no changes to the source code. Development versions of 3.13 have been included in their tests for months, and I verified that the package is compatible with 3.13 by testing that it works.
Have you
Tested by importing the module and caling `lazy_loader.load()` for both modules that exist and modules that do not exist.
=> py-lazy_loader: update to 0.4, add py313 subport

audio/easytag/Portfile, audio/gmpc/Portfile, comms/telepathy-gabble/Portfile, comms/telepathy-salut/Portfile, devel/cutter/Portfile, devel/geany-plugins/Portfile, devel/geoclue/Portfile, devel/geoclue2/Portfile, devel/gvfs/Portfile, gnome/frogr/Portfile, gnome/geocode-glib/Portfile, gnome/gfbgraph/Portfile, gnome/grilo/Portfile, gnome/gstreamer010-gst-plugins-good/Portfile, gnome/gthumb/Portfile, gnome/libchamplain/Portfile, gnome/libepc/Portfile, gnome/libgdata/Portfile, gnome/libsocialweb/Portfile, gnome/polari/Portfile, gnome/rest/Portfile, gnome/tracker3/Portfile, gnome/uhttpmock/Portfile, graphics/osm-gps-map-gtk2/Portfile, net/libgrss/Portfile, net/libgweather/Portfile, www/libhttpseverywhere/Portfile, www/midori/Portfile, www/webkit-gtk/Portfile
=> multiple ports: fix libsoup dependency

devel/gcovr/Portfile
=> gcovr: new port

graphics/tkimg/Portfile, math/R/Portfile, math/netgen/Portfile, science/gvemod-labeler/Portfile, science/magic/Portfile, science/xcrysden/Portfile, science/xcrysden/files/patch-C-Makefile.diff, x11/Togl/Portfile, x11/blt/Portfile, x11/tix/Portfile, x11/tk/Portfile, x11/tkdnd/Portfile, x11/tktable/Portfile, x11/xcircuit/Portfile
This allows ports that require an X11 version of tk to depend on tk-x11, and this is implemented in the second commit.
=> tk: split into quartz and x11 subports

graphics/opencv4/Portfile
Have you
No binary files. Tested by importing `cv2` into Python 3.13 and reading an image.
Linting returns:
```
Error: conflicts references unknown port: py313-opencv3
Error: conflicts references unknown port: py313-opencv3-devel
Error: conflicts references unknown port: py313-opencv4-devel
```
There are no Python 3.12 bindings for OpenCV 3 either, but bindings exist for the devel version of OpenCV 4. I did not add py313-opencv4-devel because I have not had the chance to test it. I am not sure what the difference actually is, since both are at version 4.9.0.
=> opencv4: add py313 bindings

math/igraph/Portfile
=> igraph: use external plfit

python/poetry/Portfile, python/py-poetry-core/Portfile, python/py-poetry-plugin-shell/Portfile
=> poetry: update to 2.0.0

science/cdo/Portfile
Simple update to upstream version 2.5.0
Have you
=> cdo: update to 2.5.0

graphics/libfive/Portfile
=> libfive: use Python 3.13

security/age/Portfile
Add installation of manpages to the age port.
Have you
=> age: install manpages

textproc/ocrmypdf/Portfile
=> ocrmypdf: rework python variants, default to 3.13; enable english by default

net/gallery-dl/Portfile
- updated to 1.28.3
- changed default python to 3.13
Have you
=> gallery-dl: update to 1.28.3 and bump python

science/gildas/Portfile, science/gildas/files/patch-admin-python-config-ldflags.py.diff
=> Gildas: update to 202501a

python/py-imageio/Portfile
Update to 2.36.1 and add subport for Python 3.13, which is officially supported. This package still supports Python 3.9, so no need to pin that version to a specific package version.
Have you
Tested by importing the module and reading an image.
=> py-imageio: update to 2.36.1, add py313 subport

sysutils/mise/Portfile
mise: Update to 2025.1.1
Have you
=> mise: Update to 2025.1.1

lang/ruby32/Portfile, lang/ruby32/files/patch-sources.diff, lang/ruby33/Portfile, lang/ruby33/files/patch-sources.diff
This fixes a couple of issues that were warnings until gcc14 made them errors.  At least one such issue probably would have caused a crash if the relevant code were executed.
This changes the installed content on 10.4, and hence gets a revbump.
TESTED:
Built successfully on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.  Included all variants compatible with available dependencies on the respective platforms (except ppc builds, which were limited to default variants to save time).
```
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 …
```
=> ruby3[23]: Fix build on 10.4 with gcc14.

mail/isync/Portfile, mail/isync/files/0001-accept-zero-sized-messages-from-IMAP.patch
Backport a patch already applied upstream that fixes this. Notably, attempting to sync a [Gmail]/Chats folder from GMail triggers this.
Have you
=> isync: Fix crash on 0-size messages on IMAP

devel/openssl3/Portfile, devel/openssl3/files/5549fcd4783cb6c2a7f07e74505a2eea4939e5b1.patch
This fixes using an algorithm from the legacy provider while the pkcs11-provider is active.
Closes: https://trac.macports.org/ticket/71760
Have you
=> openssl3: Fix no_cache issue w/3rd party providers

gis/GPXSee/Portfile
=> GPXSee: update to 13.34

net/paho.mqtt.c/Portfile, net/paho.mqtt.cpp/Portfile
* https://github.com/eclipse-paho/paho.mqtt.c/releases/tag/v1.3.14
* https://github.com/eclipse-paho/paho.mqtt.cpp/releases/tag/v1.5.0
cc @barracuda156 
Xcode 14.2
Have you
=> paho.mqtt.c: update to 1.3.14, paho.mqtt.cpp: update to 1.5.0

emulators/dosbox-x/Portfile
Update dosbox-x to version 2025.01.01
macOS 13.7.2 22H313 arm64
Have you
=> dosbox-x: update to 2025.01.01

sysutils/mise/Portfile
mise: Update to 2025.1.2
Have you
=> mise: Update to 2025.1.2

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 505.0.0.
Have you
=> google-cloud-sdk: update to 505.0.0

devel/astyle/Portfile, devel/astyle/files/dont-force-stdlib.diff
- update to 3.6.6
- fix build on Mojave, where Xcode 10 does not have the <filesystem> header
- make sure docs are installed on all platforms
Have you
=> astyle: update to 3.6.6

net/wireshark4/Portfile
Add and default to python313, drop python38
macOS x.y
Have you
=> wireshark4: update to 4.4.2

devel/icu-devel/Portfile, devel/icu/Portfile
macOS Mojave with a copy of `MacOSX10.13.sdk` and forced 10.13 deployment target can compile for i386 & x86_64
This change was required when trying to build `wine-devel` & `wine-staging`
macOS 10.14.6
Xcode 11.3.1
=> icu,icu-devel: Tweak usage of muniversal

graphics/wxWidgets-3.0/Portfile
The builds of the wx30 ports are failing on 10.7, at least.
This appears to be because 10.7 is building them with clang-16, and clang-16 defaults to a too-new c++ standard, which causes all the builds to error out.
We have two versions of most of the wx30 ports, one a "standard" build, which up to now was defaulting to something pre-c++-11 in almost all cases, and one a "*-cxx11" build, where a c++11 compiler was used.
If we set the c++ standards as such in each of the subports, this fixes the builds of the wx30 ports on 10.7, at least.
I have not tested wxPython as yet, nor any other systems beyond 10.7 as yet.
=> wxWidgets-3.0: set c++ standards

devel/glib2/Portfile, devel/glib2/files/no-distutils.patch
This was broken by aa0ed802cb96987a14af16d7974f68dbc218cdf5 and breaks the build of gtk3.
Backport the upstream patches to remove the dependency completely.
The same patch or an update to an upstream version with the fix is probably required for glib2-devel, but I don't have time to do that right now.
gtk3 @3.24.43_1+quartz
Have you
=> glib2: Fix code generator with Python 3.13

sysutils/mise/Portfile
mise: Update to 2025.1.3
Have you
=> mise: Update to 2025.1.3

net/Legcord/Portfile
Legcord (originally Armcord) is a version of the Discord web client packaged for desktop. Unlike the Discord application or web client, it blocks Discord's trackers and consumes far fewer resources. It also supports all of the major Discord client plugin/theming frameworks.
Have you
=> legcord: new port

graphics/tkimg/Portfile, math/netgen/Portfile, x11/Togl/Portfile, x11/tix/Portfile, x11/tkdnd/Portfile, x11/tktable/Portfile
These ports offer quartz and x11 variants and use the corresponding tk subports. The tk port now defaults to +quartz when it will work, and otherwise doesn't offer a quartz variant and defaults to +x11, so this makes these ports do the same.
=> tk dependents: default to +quartz when tk does

sysutils/mise/Portfile
mise: Update to 2025.1.4
Have you
=> mise: Update to 2025.1.4

java/micronaut/Portfile
Update to Micronaut Starter 4.7.4.
Have you
=> micronaut: update to 4.7.4

textproc/tesseract/Portfile
tesseract-training uses `std::filesystem` from C++17. Xcode 11, which only runs on 10.14 and up, adds support for that. The newest version that needs to link MacPorts libc++ is therefore Darwin 17.
Have you
`port lint` reports one warning, but it is not new and not related to my changes.
Binary files: tested running `/opt/local/bin/text2image --help` and verified using `otool -L` that it is linked against `/opt/local/lib/libcxx/libc++.1.0.dylib`.
=> tesseract-training: use_mp_libcxx on 10.13 and older

python/py-scikit-image/Portfile, python/py-scikit-image/files/patch-pyproject.toml-0.24.0.diff, python/py-scikit-image/files/patch-pyproject.toml.diff
* Update to 0.25.0 for Python >= 3.10
* Pin to 0.24.0 for Python 3.9
* Add py313 subport
Have you
No binary files. Tested by importing the module and testing a function (`skimage.morphology.remove_small_objects`).
=> py-scikit-image: update to 0.25.0, add py313 subport

python/py-urwid/Portfile
Have you
No binary files to test. Python 3.13 support is explicitly stated in the project README.md.
=> py-urwid: add subport py313

sysutils/starship/Portfile
Update to Starship 1.22.1.
Have you
=> starship: update to 1.22.1

multimedia/mat2/Portfile, python/py-mutagen/Portfile
mat2: update to 0.13.5, update default python
py-mutagen: add python 3.13 support (port is currently unmaintained). 
Have you
=> mat2: update to 0.13.5, update default python

sysutils/mise/Portfile
mise: Update to 2025.1.6
Have you
=> mise: Update to 2025.1.6

python/py-urwid-readline/Portfile
Package needed by more recent versions of py-pudb.
`pyproject.toml` does not specify any dependencies, but `setup.py` does. Development dependencies (pytest, black) not added.
There is no information about supported Python versions, so I have specified the same subports as `py-urwid` has (py39, ..., py313).
Have you
No binaries to test, but I imported the package (in Python 3.13) and ran the example code.
=> py-urwid-readline: new port

devel/vttest/Portfile
=> vttest: update to 20241208

science/nco/Portfile
Simple update to upstream version 5.3.1
Have you
=> nco: update to 5.3.1

net/gallery-dl/Portfile
gallery-dl: update to 1.28.4
Have you
=> gallery-dl: update to 1.28.4

python/py-black/Portfile, python/py-black/files/black313
This version explicitly states support for Python 3.9 through 3.13 on PyPI.
Note: PR #27172 also updates Black, but is tagged as work in progress and has had draft status for several weeks. Black is only one of several ports that it updates. Being a widely use package without strong ties to the other packages in that PR, I think that Black can be updated separately to avoid delays. I propose the same changes here to Black’s Portfile as the other PR, except that I do not re-add the py38 subport (it is my understanding that we are removing those now and, besides, Black no longer officially supports 3.8 according to its pyproject.toml file)
Have you
Testing: I have been running this locally for a couple of weeks now without problems.
=> py-black: update to 24.10.0, add py313 subport

aqua/alacritty/Portfile
alacritty: update to 0.15
Have you
=> alacritty: update to 0.15

science/libframe/Portfile
This PR updates the `libframe` port to the latest release.
Have you
=> libframe: update to 8.48.3

x11/mesa/Portfile
Mesa uses python-packaging to check whether mako is installed, and fails to find mako if packaging isn't available (e.g., in trace mode).
No revbump, since it either builds correctly, or not at all.
Have you
=> mesa: Add missing build dep

python/py-jedi/Portfile
=> py-jedi: update to 0.19.2

security/keybase/Portfile
macOS 13.7.2 22H313 x86_64
Have you
=> keybase: update to version 6.4.0

sysutils/oh-my-posh/Portfile
=> oh-my-posh: update to version 24.18.1

sysutils/mise/Portfile
mise: Update to 2025.1.7
Have you
=> mise: Update to 2025.1.7

ruby/ruby-build/Portfile
ruby-build: Update to 20250114
Have you
=> ruby-build: Update to 20250114

science/libframe/Portfile
This PR fixes problems with the cmake configuration for `libframe` introduced by #27384.
Have you
=> libframe: fix bugs in cmake configuration

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 506.0.0.
Have you
=> google-cloud-sdk: update to 506.0.0

gis/tippecanoe/Portfile
=> tippecanoe: update to 2.74.0

devel/kustomize/Portfile
Update to Kustomize 5.6.0.
Have you
=> kustomize: update to 5.6.0

mail/aerc/Portfile
[Changelog](https://git.sr.ht/~rjarry/aerc/refs/0.19.0)
macOS 12.6.5 x86_64
Xcode 14.2
Have you
=> aerc: update to 0.19.0

devel/mani/Portfile
The manpage and completions are present after update.
macOS 14.7.2 23H311 arm64 Xcode 16.2 16C5032a
Have you
same change?
=> mani: Install manpage and completions

ruby/ruby-build/Portfile
ruby-build: Update to 20250115
Have you
=> ruby-build: Update to 20250115

devel/d3dmetal/Portfile
=> d3dmetal: Update to v2.0

sysutils/mise/Portfile
mise: Update to 2025.1.9
Have you
=> mise: Update to 2025.1.9

net/newsraft/Portfile
https://codeberg.org/newsraft/newsraft/releases/tag/newsraft-0.28
Xcode 14.2
Have you
=> newsraft: update to 0.28

gis/JOSM/Portfile
=> josm: update to 19277

devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases/tag/v1.1.0
Xcode 14.2
Have you
=> jsoncons: update to 1.1.0

graphics/libpng/Portfile
Simple update to upstream version 1.6.45
Have you
=> libpng: update to 1.6.45

python/py-meson/Portfile, python/py-meson/files/cross/arm64-darwin, python/py-meson/files/cross/i386-darwin, python/py-meson/files/cross/ppc-darwin, python/py-meson/files/cross/ppc64-darwin, python/py-meson/files/cross/x86_64-darwin
when building a non-native cross arch,
meson requires most binaries used during
the build to be specified in the cross
files.
these don't have to be full path-specified,
however, and simply setting this:
llvm-config = 'llvm-config'
will satisfy meson that it's OK to use the
llvm-config binary found in the PATH.
closes: https://trac.macports.org/ticket/71852
Have you
=> meson: add llvm-config to cross files

textproc/utfcpp/Portfile
New port `utfcpp` (“UTF-8 with C++ in a Portable Way”): https://github.com/nemtrif/utfcpp
This library is now a dependency of `lttoolbox` and `apertium`, which I plan to update.
The library is header-only. It has a CMakeLists.txt file that provides an `install` target, so the easiest solution was to use the `cmake 1.1` port group. According to the developer, the CMakeLists.txt file was only intended for testing and might go away in a future release, but it has been there for over nine years, so I took the chance and used it. We can always update the Portfile if the file eventually gets deleted.
```
$ port cont utfcpp
Port utfcpp @4.0.6_0 contains:
/opt/local/include/utf8cpp/utf8.h
/opt/local/include/utf8cpp/utf8/checked.h
/opt/local/include/utf8cpp/utf8/core.h …
```
=> utfcpp: new port

devel/minipro/Portfile
This updates minipro to 0.7.2. Also removes the platform line to satisfy `port lint`.
Have you
=> minipro: Update to 0.7.2.

llm/llama.cpp/Portfile, llm/llama.cpp/files/patch-llama-mmap-errno.diff
- Explicitly disable OpenMP
Fixes: https://trac.macports.org/ticket/71870
- Upstream patch for errno-related build failure on 10.15:
Fixes: https://trac.macports.org/ticket/71880
=> llama.cpp: update to b4508; fix builds for 10.15 and earlier

games/rebels-in-the-sky/Portfile
rebels-in-the-sky: Update to 1.0.28
Have you
=> rebels-in-the-sky: Update to 1.0.28

java/openjdk24-zulu/Portfile
Update to Azul Zulu OpenJDK 24.0.67.
Have you
=> openjdk24-zulu: update to 24.0.67

sysutils/glances/Portfile
glances: Update to version 4.3.0.8, Fix py-orjson related bug
* Update version to 4.3.0.8
* Ensure py-orjson is only used on High Sierra and later
Note: orjson@3.10.14 requires rustc 1.82 which is only available on High Sierra and later.
(See https://trac.macports.org/ticket/71807)
P.S.  Also tested on Mountain Lion (10.8.5)
Have you
=> glances: Update to version 4.3.0.8, Fix py-orjson related bug

devel/openssl3/Portfile, devel/openssl3/files/77c608f4c8857e63e98e66444e2e761c9627916f.patch
Fixes a small timing sidechannel in ECDSA that can in the worst case lead to a private key compromise.
See https://openssl-library.org/news/secadv/20250120.txt for the upstream advisory.
CVE: CVE-2024-13176
Have you
=> openssl3: Fix CVE-2024-13176

_resources/port1.0/group/crossbinutils-1.0.tcl
Needed to build binutils versions greater than 2.41
From feedback from @kencu in https://github.com/macports/macports-ports/pull/27345#issuecomment-2601373548
macOS x.y
=> crossbinutils: Add compiler blacklist

net/Legcord/Portfile
legcord: update to 1.0.7
Have you
=> legcord: update to 1.0.7

science/qdmr/Portfile
* Update qDMR to version 1.12.1
* Reworked CTCSS/DCS settings.
* Reworked repeater database sources.
* Updated OpenGD77 support to R20240908.
* Bugfixes and updates
This release add support for the latest stable OpenGD77 firmware allowing macOS users the 
ability to program their OpenGD77 radios without requiring a windows box.
Have you
=> qdmr: Update to 1.12.1

multimedia/ffmpeg-devel/Portfile, multimedia/ffmpeg7/Portfile, multimedia/ffmpeg7/files/patch-add-pixeldensity.diff
Backport the patch to ffmpeg7, since the ffmpeg-devel port uses v7 branch.
Have you
=> ffmpeg7: add pixeldensity feature for retina displays

net/Legcord/Portfile
legcord: update to 1.0.8
Have you
=> legcord: update to 1.0.8

java/jdk23/Portfile
Update to Oracle JDK 23.0.2.
Have you
=> jdk23: update to 23.0.2

java/jdk21/Portfile
Update to Oracle JDK 21.0.6.
Have you
=> jdk21: update to 21.0.6

java/jdk21-graalvm/Portfile
Update to Oracle GraalVM for JDK 21.0.6.
Have you
=> jdk21-graalvm: update to 21.0.6

java/openjdk23-corretto/Portfile
Update to Amazon Corretto 23.0.2.
Have you
=> openjdk23-corretto: update to 23.0.2

java/openjdk17-corretto/Portfile
Update to Amazon Corretto 17.0.14.7.1.
Have you
=> openjdk17-corretto: update to 17.0.14.7.1

java/openjdk21-corretto/Portfile
Update to Amazon Corretto 21.0.6.7.1.
Have you
=> openjdk21-corretto: update to 21.0.6.7.1

java/openjdk11-corretto/Portfile
Update to Amazon Corretto 11.0.26.4.1.
Have you
=> openjdk11-corretto: update to 11.0.26.4.1

java/openjdk8-corretto/Portfile
Update to Amazon Corretto 8.442.06.1.
Have you
=> openjdk8-corretto: update to 8.442.06.1

java/openjdk21-zulu/Portfile
Update to Azul Zulu 21.40.17 based on OpenJDK 21.0.6.
Have you
=> openjdk21-zulu: update 21.40.17

java/openjdk23-zulu/Portfile
Update to Azul Zulu 23.32.11 based on OpenJDK 23.0.2.
Have you
=> openjdk23-zulu: update to 23.32.11

java/openjdk17-zulu/Portfile
Update to Azul Zulu 17.56.15 based on OpenJDK 17.0.14.
Have you
=> openjdk17-zulu: update to 17.56.15

java/openjdk11-zulu/Portfile
Update to Azul Zulu 11.78.15 based on OpenJDK 11.0.26.
Have you
=> openjdk11-zulu: update to 11.78.15

java/openjdk8-zulu/Portfile
Update to Azul Zulu 8.84.0.15 based on OpenJDK 8u442.
Have you
=> openjdk8-zulu: update to 8.84.0.15

java/openjdk23/Portfile
Update to OpenJDK 23.0.2.
Have you
=> openjdk23: update to 23.0.2

ruby/ruby-build/Portfile
ruby-build: Update to 20250121
Have you
=> ruby-build: Update to 20250121

java/openjdk23-sap/Portfile
Update to SapMachine 23.0.2.
Have you
=> openjdk23-sap: update to 23.0.2

java/openjdk21-sap/Portfile
Update to SapMachine 21.0.6.
Have you
=> openjdk21-sap: update to 21.0.6

java/openjdk21/Portfile
Update to OpenJDK 21.0.6.
Have you
=> openjdk21: update to 21.0.6

java/openjdk17/Portfile
Update to OpenJDK 17.0.14.
Have you
=> openjdk17: update to 17.0.14

java/openjdk11/Portfile
Update to OpenJDK 11.0.26.
Have you
=> openjdk11: update to 11.0.26

java/openjdk21-temurin/Portfile
Update to Eclipse Temurin 21.0.6.
Have you
=> openjdk21-temurin: update to 21.0.6

java/openjdk17-temurin/Portfile
Update to Eclipse Temurin 17.0.14.
Have you
=> openjdk17-temurin: update to 17.0.14

java/openjdk11-temurin/Portfile
Update to Eclipse Temurin 11.0.26.
Have you
=> openjdk11-temurin: update to 11.0.26

java/openjdk8-temurin/Portfile
Update to Eclipse Temurin 8u442.
Have you
=> openjdk8-temurin: update to 8u442

java/openjdk21-microsoft/Portfile
Update to Microsoft OpenJDK 21.0.6.
Have you
=> openjdk21-microsoft: update to 21.0.6

java/openjdk17-microsoft/Portfile
Update to Microsoft OpenJDK 17.0.14.
Have you
=> openjdk17-microsoft: update to 17.0.14

java/openjdk11-microsoft/Portfile
Update to Microsoft OpenJDK 11.0.26.
Have you
=> openjdk11-microsoft: update to 11.0.26

java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.4.2.
Have you
=> spring-boot-cli: update to 3.4.2

devel/skaffold/Portfile
Update to Scaffold 2.14.0.
Have you
=> skaffold: update to 2.14.0

sysutils/stern/Portfile
Update to Stern 1.32.0.
Have you
=> stern: update to 1.32.0

lang/ruby33/Portfile, lang/ruby33/files/patch-sources.diff
See:
https://www.ruby-lang.org/en/news/2025/01/15/ruby-3-3-7-released/
Ruby 3.3 no longer builds with Xcode 10.1 clang 425 on 10.7, so this blacklists clangs < 500 (in addition to the preexisting blacklisting of clang 900).
Also cleans up a couple of long-standing Portfile issues.
TESTED:
Built successfully on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-15.x arm64.  Included all variants compatible with available dependencies on the respective platforms.
```
Mac OS X 10.6.8 10K549, …
```
=> ruby33: update to 3.3.7

sysutils/mise/Portfile
mise: Update to 2025.1.13
Have you
=> mise: Update to 2025.1.13

devel/reflex/Portfile
Update "reflex" to current version, for compiler-warning fixes.
also macOS 15.2 24C101 x86_64
(same Xcode)
Have you
- [] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message?
=> reflex: update to 2.5.4-20241231

devel/toast/Portfile
toast: Update to 0.47.7
Have you
=> toast: Update to 0.47.7

net/haproxy/Portfile
haproxy: enable the Prometheus Exporter service
Have you
=> haproxy: enable the Prometheus Exporter service

java/openjdk23-temurin/Portfile
Update to Eclipse Temurin 23.0.2.
Have you
=> openjdk23-temurin: update to 23.0.2

java/openjdk24-zulu/Portfile
Update to Azul Zulu 24.0.73.
Have you
=> openjdk24-zulu: update to 24.0.73

sysutils/mise/Portfile
mise: Update to 2025.1.14
Have you
=> mise: Update to 2025.1.14

devel/got/Portfile
=> got: update to 0.108

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 507.0.0.
Have you
=> google-cloud-sdk: update to 507.0.0

net/ncdc/Portfile
Add "u" key to file browser to sort non-local files first  
Fix possible crash on aarch64 when connected to an ADC hub  
Slightly improve ADC protocol compliance
Slightly improve C compiler compatibility
macOS x.y
Have you
=> Update to 1.24.1

sysutils/lima/Portfile
As of [Lima 1.0.0](https://github.com/lima-vm/lima/releases/tag/v1.0.0), it no longer defaults to using QEMU. Since QEMU is a rather large dependency, we should not depend on needless, so I've dropped it from 14 onwards.
macOS x.y
Have you
=> lima: drop dependency on QEMU from macOS 14 onwards

sysutils/fastfetch/Portfile
switch python to build dep and make sure the build process uses the specified version
macOS x.y
Have you
=> fastfetch: update to 2.35.0, use python 3.13

emulators/wine-devel/Portfile, emulators/wine-stable/Portfile
With this enabled most of the MacPorts buildbots are failing so disable pcap, this didn't happen when building locally on macOS Mojave +universal nor has it happened on macOS Sonoma
@kencu weirdly the buildbots are failing due to libpcap, no clue why when this works just fine locally, I have no idea why it's the case with the buildbots when we both managed to build wine locally without issue on multiple macOS versions.
=> wine-*: Don't use libpcap

textproc/pandoc/Portfile
Fixes:
* https://trac.macports.org/ticket/71949
macOS x.y
Have you
=> pandoc: Bugfix legacy checksums

sysutils/mise/Portfile
mise: Update to 2025.1.15
Have you
=> mise: Update to 2025.1.15

lang/groovy/Portfile
Update to Groovy 4.0.25.
Have you
=> groovy: update to 4.0.25

java/openjdk11-sap/Portfile
End of support reached in December 2024.
Have you
=> openjdk11-sap: end of support

emulators/wine-devel/Portfile, emulators/wine-stable/Portfile
Fix platform and add missing -append for MoltenVK-latest
macOS x.y
Have you
=> wine-*: Fixup portfiles

science/ncview/Portfile
macOS 13.7.2
Xcode 15.2 / Command Line Tools 15.1.0
Have you
=> ncview: update to v2.1.11

sysutils/chezmoi/Portfile
chezmoi: Update to 2.59.0
Have you
=> chezmoi: Update to 2.59.0

lang/kotlin/Portfile
Update to Kotlin 2.1.10.
Have you
=> kotlin: update to 2.1.10

textproc/yq/Portfile
Closes: https://trac.macports.org/ticket/71959
Have you
=> yq: Fix checksum mismatch of manpage distfile

_resources/port1.0/group/haskell_cabal-1.0.tcl, lang/ghc/Portfile
=> ghc: Bugfix build

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 508.0.0.
Have you
=> google-cloud-sdk: update to 508.0.0

ruby/ruby-build/Portfile
ruby-build: Update to 20250127
Have you
=> ruby-build: Update to 20250127

net/gallery-dl/Portfile
gallery-dl: update to 1.28.5
Have you
=> gallery-dl: update to 1.28.5

sysutils/mise/Portfile
mise: Update to 2025.1.16
Have you
=> mise: Update to 2025.1.16

security/age-plugin-se/Portfile
=> age-plugin-se: An Age plugin for Apple's Secure Enclave

python/ansible_select/Portfile, python/ansible_select/files/base, python/py-ansible-compat/Portfile, python/py-ansible-core/Portfile, python/py-ansible-core/files/py310-ansible, python/py-ansible-core/files/py311-ansible, python/py-ansible-core/files/py312-ansible, python/py-ansible-core/files/py313-ansible, python/py-ansible-core/files/py39-ansible, python/py-ansible/Portfile, python/py-bcrypt/Portfile, python/py-httplib2/Portfile, python/py-paramiko/Portfile, python/py-pynacl/Portfile, python/py-resolvelib/Portfile, python/py-subprocess-tee/Portfile
Update   ansible to 11.1.0, add python313
ansible-core to 2.18.1, remove defunct ansible-connect, add python 313
ansible-compat to 24.10.0, update download name, add python313
ansible-select: remove defunct ansible-connect
py-bcrypt, py-httplib2, py-paramiko, py-resolvelib,py-subprocess-tee
Update to python 3.13 and update where appropriate
- py-bcrypt: update to 4.2.1, update related cargo modules
add python 3.13, add patch to remove uppoer version boundary of py-setuptools (75.8.0)
- py-httplib2: add python 3.13
- py-paramiko: update to 3.5.0 add python 3.13
- py-pynacl: add python 3.13
- py-resolvelib: update to 1.1.0 add python 3.13
- py-subprocess-tee: update to 0.4.2 add python 3.13
Have you
=> Update ansible, ansible-core and ansible-compat to latest versions

ruby/ruby-build/Portfile
ruby-build: Update to 20250130
Have you
=> ruby-build: Update to 20250130

security/gitleaks/Portfile
gitleaks: Update to 8.23.3
Have you
=> gitleaks: Update to 8.23.3

python/py-flit/Portfile
Adding py313 flavor. Port has no maintainer.
=> py-flit: add py313 (nomaintainer)

lang/libomp/Portfile
=> libomp: use newer python for new systems

aqua/oscar/Portfile
* Update to 1.6.0
* Change to new gitlab repo
* Add me(@markemer) as additional maintainer
* Change livecheck to proper url
macOS x.y
Have you
=> oscar: update to 1.6.0

gis/tippecanoe/Portfile
=> tippecanoe: update to 2.75.0

science/ngspice/Portfile
- Updated ngspice to version 44.2
- Modified the Portfile to handle the "." of the version.
macOS 13.7.2 22H313 x86_64
Have you
=> ngspice: update to version 44.2

emulators/wine-devel/Portfile, emulators/wine-stable/Portfile
Currently the buildbots assume this can build on El Capitan when that's not the case so use >= instead.
SDK check causes build to fail on macOS High Sierra as it looks for the SDK inside Xcode instead of "/Library/Developer/CommandLineTools/SDKs"
macOS x.y
=> wine-*: Fix platforms & building on macOS High Sierra

sysutils/mise/Portfile
mise: Update to 2025.1.17
Have you
=> mise: Update to 2025.1.17

devel/lazarus/Portfile
* update to version 3.8
* update homepage
* add dependence of qt4 variant on qt4pas
* fix missing library paths for gtk2 Note: issue 70817 refers to a much older version (2.10.1)
Closes: https://trac.macports.org/ticket/71939
Closes: https://trac.macports.org/ticket/71679
Possibly closes: https://trac.macports.org/ticket/70817
Lazarus: update to 3.8 and fixes for qt4 and gtk2 variants.
- [] security fix
Have you
=> Lazarus: update to 3.8 and fixes for qt4 and gtk2 variants.

devel/girara/Portfile
* update to version 0.4.5
* don't use the gitlab PortGroup since this project is not hosted on GitLab anymore
* update homepage (project moved)
* update master_sites (project moved)
* update livecheck (project moved)
* distfiles are now compressed using xz
Have you
=> girara: update to version 0.4.5

python/py-awscli2/Portfile, python/py-awscli2/files/patch-requirements.diff, python/py-awscrt/Portfile
=> py-awscli2: update to 2.23.10

editors/vile/Portfile
Update to current version, minor bug-fixes and compiler-warnings.
Have you
=> vile: Update to 9.8za

textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.8.0
Have you
=> ocrmypdf: update to 16.8.0

devel/yamllint/Portfile, python/py-bracex/Portfile, python/py-enrich/Portfile, python/py-wcmatch/Portfile, sysutils/ansible-lint/Portfile, sysutils/ansible-lint/files/patch-disable_path_warning.diff
Update ansible-lint and yamlint to use python 3.13
Additionally:
ansible-lint: update to 24.12.2 use python 3.13
yamlint: add python 3.13
py-bracecx: update to 2.5 and add python 3.13
py-enrich: add python 3.13
py-wcmatch: update to 10.0 and add python 3.13
Update yamlint and ansible-lint to the latest python (3.13)
Have you
=> ansible-lint, yamllint: Update revision and interpreter to python3.13

python/py-nbconvert/Portfile
Add missing dependency of `py-nbconvert` to `py-jupyterlab_pygments` (file `/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nbconvert/preprocessors/csshtmlheader.py` from `py-nbconvert` contains `from jupyterlab_pygments import JupyterStyle`).
Have you
=> py-nbconvert: add missing dependency to py-jupyterlab_pygments

sysutils/mise/Portfile
mise: Update to 2025.2.0
Have you
=> mise: Update to 2025.2.0

net/bettercap/Portfile
remove python build dep
macOS x.y
Have you
=> bettercap: patch default caplets path

archivers/bzip3/Portfile
Update `bzip3` to 1.5.1
macOS 14.7.3 23H417 arm64
Have you
=> bzip3: update to 1.5.1

security/1password-cli/Portfile
1password: Update to provide completions on install
macOS 14.7.2 23H311
arm64 Xcode 16.2 16C5032a
Have you
=> 1password: Update to provide completions on install

gis/JOSM/Portfile
=> josm: update to 19307

python/py-pyobjc/Portfile, python/py-pyobjc/files/patch-setup-no-werror.diff
Update to PyObjC 10.3.2. This removes the build dependency on Xcode (see https://github.com/ronaldoussoren/pyobjc/commit/3ce18202867ab76c94be509f7c166102cd46b063).
Have you
=> py-pyobjc: update to 10.3.2

lang/elixir/Portfile
Updates Elixir to 1.18.2
macOS 15.2
Command Line Tools 2409
Have you
=> elixir: update to 1.18.2

sysutils/man/Portfile, sysutils/man/files/patch-int-main.diff
=> man: Fixes C99 implicit int errors in configure script

ruby/ruby-build/Portfile
ruby-build: Update to 20250205
Have you
=> ruby-build: Update to 20250205

textproc/apertium/Portfile, textproc/lttoolbox/Portfile
These ports have not been updated in several years. I am not sure if old and new versions work well together, so I thought it would be best to update them both in the same PR. They are separate ports even though both are part of the Apertium project, so there are two commits. Please let me know if I should squash them.
Both have migrated from SourceForge to GitHub. They now require C++17 (apertium needs LegacySupport for `std::filesystem` on Darwin < 19) and build with autoreconf. I have also updated the dependencies.
For `lttoolbox` I had to add dependencies `autoconf`, `automake` and `libtool` even though I put `use_autoreconf` in the Portfile. That was not necessary for `apertium`, and doing it would even have `port lint` complain about duplicate dependencies. I have no idea why.
macOS …
=> lttoolbox: upgrade to 3.7.6, apertium: upgrade to 3.9.4

graphics/ImageMagick7/Portfile
ImageMagick7: Update 7.1.1-41 --> 7.1.1-43
CI only.
Have you
=> ImageMagick7: Update to 7.1.1-43

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 509.0.0.
Have you
=> google-cloud-sdk: update to 509.0.0

java/openjdk24-zulu/Portfile
Update to Azul Zulu 24.0.77.
Have you
=> openjdk24-zulu: update to 24.0.77

devel/ghidra/Portfile
update ghidra to 11.3, requires python3 now to build/run
Have you
=> ghidra: update to 11.3

devel/pnpm/Portfile
=> pnpm: update to 10.2.1, add nodejs ver fallback

devel/gcovr/Portfile, devel/gcovr/files/relax-hatchling-version.patch
macOS 14.7.3 23H417 arm64
Have you
=> gcovr: update to 8.3

gis/gdal-grass/Portfile
Update `gdal-grass` to version 1.0.3, now build with CMake.
Have you
=> gdal-grass: update to 1.0.3, build with CMake

graphics/openjpeg/Portfile
* switch github.tarball_from to archive
* use HTTPS for homepage
Have you
=> openjpeg: update to 2.5.3

devel/qbs/Portfile
Now that qt64 is allowed on 10.14, we can build qbs. It [requires using the same compiler toolchain Qt was built with](https://qbs.io//docs/building-qbs/#system-requirements) and also requires std::filesystem.
Have you
=> qbs: Fix building on 10.14

databases/sqlite3/Portfile, databases/sqlite3/files/no-rpath.patch
Don't use -rpath since it's never needed and causes an error with older compilers.
Closes: https://trac.macports.org/ticket/72018
Change the install name from /opt/local/lib/libsqlite3.dylib back to /opt/local/lib/libsqlite3.0.dylib as it was in 3.48.0 and earlier.
Change the install name in post-build not post-destroot and use shellescape when doing so.
See: https://trac.macports.org/ticket/72021
Have you
=> sqlite3: Avoid rpath; tweak install name

emulators/dosbox-x/Portfile
Update dosbox-x to version 2025.02.01
macOS 13.7.2 22H313 arm64
Have you
=> dosbox-x: update to 2025.02.01

genealogy/geneweb/Portfile, ocaml/ocaml-uri/Portfile
geneweb build was broken as ocaml-uri had to be rebuilt.
Have you
=> ocaml-uri and geneweb: bump revision as ocaml-angstrom was updated

devel/xcode-build-server/Portfile
Update with the latest release, v1.2.0. The project has a new helper OSAScript file, "xcode/build.js", so that is added to the install steps.
Have you
=> xcode-build-server: update to v1.2.0

sysutils/podman/Portfile
=> podman: update to 5.3.2

textproc/libutf8proc/Portfile
update libutf8proc to 2.10.0
Have you
=> libutf8proc: update to 2.10.0

net/gvisor-tap-vsock/Portfile
- Major motivation is a fix to keyring spam which is fixed in 0.7.5: https://github.com/podman-desktop/podman-desktop/issues/8452
- Adds a bunch of features (see their changelog).
=> gvisor-tap-vsock: update to 0.8.3

sysutils/vfkit/Portfile
=> vfkit: update to 0.6.0

net/sshuttle/Portfile
https://github.com/sshuttle/sshuttle/releases/tag/v1.2.0
Xcode 14.2
Have you
=> sshuttle: update to 1.2.0

devel/legacy-support/Portfile
Notable changes since v1.3.0:
- Works around Apple's broken versioning in the macOS 15 SDK
- Implements scandir() compatibility feature
- Fixes dprintf() bug and implements vdprintf() See: https://trac.macports.org/ticket/67598 See: https://trac.macports.org/ticket/70118
- Mismatched SDK compatibility is extended to include 15.x SDK.
- Broken 10.4 CLOCK_MONOTONIC is fixed.
- Fixes stat inconsistency in some 32-bit 10.4 builds.
- Adds stat64 header support for 10.4 SDK.
- Adds INODE64 support for *stat*() on 10.4.
- Reworks fstatat*() support, similar to previous item, fixing buffer overrun in some cases.
- Backports 10.5 'which' to 10.4.
- Adds support for code that can't tolerate the normal scandir() compatibility feature.
- Replaces broken 10.4/10.5 copyfile wrapper with full 10.6 …
=> legacy-support: update to v1.4.0.

sysutils/mise/Portfile
mise: Update to 2025.2.3
Have you
=> mise: Update to 2025.2.3

emulators/wine-devel/Portfile
=> wine-devel,wine-staging: Update to 10.1

lang/clojure/Portfile
=> clojure: update to  1.12.0.1517

devel/symfony-cli/Portfile
=> symfony-cli: update to 5.10.7

java/micronaut/Portfile
Update to Micronaut Starter 4.7.5.
Have you
=> micronaut: update to 4.7.5

devel/skaffold/Portfile
Update to Scaffold 2.14.1.
Have you
=> skaffold: update to 2.14.1

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 510.0.0.
Have you
=> google-cloud-sdk: update to 510.0.0

science/stimfit/Portfile
* update to version 0.16.6
* update file I/O
* update to latest numpy API
Have you
=> stimfit: update to version 0.16.6

ruby/ruby-build/Portfile
ruby-build: Update to 20250212
Have you
=> ruby-build: Update to 20250212

python/py-awscli2/Portfile
Add python 3.13 support to py-awscli2
Have you
`port lint` does complain that this conflicts with nonexistent port py313-awscli. I didn't think it made sense to add that version in this PR or to try to avoid the conflict now (which would become necessary if the py313-awscli version were added. It also looks like py312-awscli was added long before py313-awscli2 so I think this is "tradition".
=> py-awscli2: add python 3.13

sysutils/lima/Portfile
lima: Update to 1.0.6
Have you
=> lima: Update to 1.0.6

science/hamlib/Portfile
Update hamlib to the latest stable version, v4.6.2.
NOTE: this fixes the compile issue created in v4.6.0 by reverting the change so we can safely move on.
Have you
=> hamlib: Update to v4.6.2

net/Legcord/Portfile
Legcord: update to 1.1.0
Have you
=> Legcord: update to 1.1.0

devel/uv/Portfile
Update uv to its latest released version, 0.6.0
Have you
=> uv: Update to 0.6.0

sysutils/ipatool/Portfile
Update `ipatool` to its latest released version, 2.1.6, which fixes a critical feature involving purchasing apps on the App Store
Have you
=> ipatool: Update to 2.1.6

ruby/ruby-build/Portfile
ruby-build: Update to 20250215
Have you
=> ruby-build: Update to 20250215

sysutils/bfs/Portfile
=> bfs: update to 4.0.5

sysutils/mise/Portfile
mise: Update to 2025.2.4
Have you
=> mise: Update to 2025.2.4

gis/tippecanoe/Portfile
=> tippecanoe: update to 2.75.1

devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases/tag/v1.2.0
Xcode 14.2
Have you
=> jsoncons: update to 1.2.0

java/openjdk21-openj9/Portfile
Update to IBM Semeru 21.0.6.
Have you
=> openjdk21-openj9: update to 21.0.6

java/openjdk23-openj9/Portfile
Update to IBM Semeru 23.0.2.
Have you
=> openjdk23-openj9: update to 23.0.2

java/openjdk8-openj9/Portfile
Update to IBM Semeru 8u442.
Have you
=> openjdk8-openj9: update to 8u442

java/openjdk11-openj9/Portfile
Update to IBM Semeru 11.0.26.
Have you
=> openjdk11-openj9: update to 11.0.26

gis/GPXSee/Portfile
=> GPXSee: update to 13.35

security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.570. A release schedule has been introduced for this port given the frequent updates from upstream.
Have you
=> ipsw: Update to 3.1.570

sysutils/g-ls/Portfile
Update `g-ls` to its latest released update, 0.29.0
Have you
=> g-ls: Update to 0.29.1

net/tlrc/Portfile
Update `tlrc` to its latest released version, 1.10.0
Have you
=> tlrc: Update to 1.10.0

sysutils/mise/Portfile
mise: Update to 2025.2.5
Have you
=> mise: Update to 2025.2.5

sysutils/mise/Portfile
mise: Update to 2025.2.6
Have you
=> mise: Update to 2025.2.6

devel/gum/Portfile
gum: Update to 0.15.2
Have you
=> gum: Update to 0.15.2

devel/symfony-cli/Portfile
=> symfony-cli: update to 5.11.0

python/py-h5py/Portfile, science/hdf5/Portfile
Most hdf5-dependent ports no longer need rev-bumps for HDF5, by py-h5py has its own version warning baked in.
add py313 flavor of hdf5 and drop cython-compat (builds with Cython 3.x since 3.11; missed earlier).
=> hdf5: 1.14.6 py-h5py: Add 313

games/2048.c/Portfile
Update `2048.c` to its latest released version, 1.0.3
Have you
=> 2048.c: Update to 1.0.3

_resources/port1.0/group/dart-1.0.tcl, _resources/port1.0/group/pub-1.0.tcl, devel/fvm/Portfile, sysutils/pub2port/Portfile
This enables building Dart/pub projects in the same vein as Rust/cargo projects.
This PR is for feedback and CI testing.
Have you
=> Add dart, pub portgroups, relevant ports

gis/rsgislib/Portfile
- `rsgislib`: update to 5.1.8
- `py-rsgislib`: no livecheck for python subports
macOS x.y
Have you
=> rsgislib: update to 5.1.8

devel/gitu/Portfile
Update `gitu` to its latest released version, 0.28.1
Have you
=> gitu: Update to 0.28.1

devel/ruff/Portfile
Update `ruff` to its latest released version, 0.9.6
Have you
=> ruff: Update to 0.9.6

aqua/alacritty/Portfile
alacritty: update to 0.15.1
Have you
=> alacritty: update to 0.15.1

security/gitleaks/Portfile
gitleaks: Update to 8.24.0
Have you
=> gitleaks: Update to 8.24.0

aqua/qt6/Portfile, aqua/qt67/Portfile
The initial Qt6 port (and updates to newer versions I committed) had the supported versions incorrectly listed. That issue was corrected a while ago, but there are users who had the `qt6` port installed on a system that is no longer supported. So instead they should install the `qt67` or `qt64` (sub)ports. 
To provide an "upgrade" path for these situations I added some logic to the Portfiles that will set `replaced_by` on systems that no longer support the versions provided by the `qt6` or `qt67` ports.  
macOS x.y
Have you
=> qt6,qt76: provide "upgrade" path on systems where the port is no longer supported

java/apache-solr8/Portfile
=> apache-solr8: Update to version 8.11.4

java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.4.3.
Have you
=> spring-boot-cli: update to 3.4.3

gnome/gtk-doc/Portfile
remove python 3.8
macOS x.y
Have you
=> gtk-doc: add and default to python 3.13 variant

devel/legacy-support/Portfile
Notable changes:
- Fix some possible warnings in the headers.
TESTED:
Tested both normal and -devel versions -/+universal on 10.4-10.5 ppc, 10.5-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-15.x arm64.
Builds and passes all tests on all tested platforms.
```
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518 …
```
=> legacy-support-devel: Update to latest master - v20250220.

sysutils/g-ls/Portfile
Update `g-ls` to its latest released version, 0.29.2
Have you
=> g-ls: Update to 0.29.2

devel/gitu/Portfile
Update `gitu` to its latest released version, 0.28.2. This PR fixes any opportunistic linking with `libiconv` by declaring it as a needed library
Have you
=> gitu: Update to 0.28.2

python/py-graph-tool/Portfile
=> py-graph-tool: Update to version 2.91

multimedia/svt-av1/Portfile
https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/201809/steps/install-port/logs/stdio
Have you
=> sv1-av1: use port:git on macOS <10.9

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 511.0.0.
Have you
=> google-cloud-sdk: update to 511.0.0

devel/pcre/Portfile
=> pcre2: update to 10.45

python/py-acme/Portfile, python/py-josepy/Portfile, security/certbot/Portfile
certbot 3.2.0 is looking for the certificates in the wrong place:
Saving debug log to /var/log/letsencrypt/letsencrypt.log
certificate path : /etc/letsencrypt/
The problem w/ the paths was introduced in
https://github.com/macports/macports-ports/commit/408ad4d
Lines 56-61 were removed ; but only line 56 ought to have been removed. lines 58-62 ought only to have had their paths corrected
On branch certbot
modified:   security/certbot/Portfile
- [ x] bugfix
macOS 14.7.3 23H417 x86_64
Have you
=> certbot 3.2.0 wrong paths

devel/openssl3/Portfile, devel/openssl3/files/0001-revert-rcu.diff, devel/openssl3/files/0002-use-atomic-relaxed.diff, devel/openssl3/files/0003-dont-use-atomic-acq-rel.diff
Closes: https://trac.macports.org/ticket/72055
Have you
=> openssl3: fix build on macOS =<10.6 i386/PowerPC

devel/zlog/Portfile
**[zlog](https://github.com/HardySimpson/zlog)** is a reliable, high-performance, thread safe, flexible, clear-model, pure C logging library.
[![Packaging status](https://repology.org/badge/tiny-repos/zlog.svg)](https://repology.org/project/zlog/versions)
Xcode 14.2
Have you
=> zlog: new port

sysutils/simplotask/Portfile
=> simplotask: update to 1.16.4

net/paho.mqtt.cpp/Portfile
https://github.com/eclipse-paho/paho.mqtt.cpp/releases/tag/v1.5.1
Xcode 14.2
Have you
=> paho.mqtt.cpp: update to 1.5.1

devel/ruff/Portfile
Update `ruff` to its latest released version, 0.9.7, fixing any opportunistic linking with `libiconv`. This seems to be a common issue with Rust ports, so make sure to test your binaries.
Have you
=> ruff: Update to 0.9.7

sysutils/chezmoi/Portfile
chezmoi: Update to 2.60.0
Added myself as a maintainer for chezmoi (I am a collaborator on chezmoi itself).
Have you
=> chezmoi: Update to 2.60.0

python/py-h5py/Portfile
- h5py is now compatible with cython 3.x
- h5py does not depend on pythran (did it ever? not in history on GitHub)
- pkgconfig is not a runtime dependency
- h5py does not depend on six any more
- build for Python 3.13
macOS x.y
Have you
=> py-h5py: update build dependencies

textproc/jaq/Portfile
=> jaq: Update to 2.1.1

devel/zlog/Portfile, devel/zlog/files/patch-stdint.diff
=> zlog: fix build on macOS <10.9

devel/tree-sitter/Portfile
update tree-sitter to 0.25.2
Have you
=> tree-sitter: update to 0.25.2

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 512.0.0.
Have you
=> google-cloud-sdk: update to 512.0.0

net/sshuttle/Portfile
https://github.com/sshuttle/sshuttle/releases/tag/v1.3.0
Xcode 14.2
Have you
=> sshuttle: update to 1.3.0

security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.576
Have you
=> ipsw: Update to 3.1.576

net/youtube-dl/Portfile
yt-dlp: update to 2025-02-19
Have you
=> yt-dlp: update to 2025-02-19

multimedia/ffmpeg7/Portfile, multimedia/ffmpeg7/files/patch-texinfo7x-pretest-support.diff
=> ffmpeg7: Add support for texinfo 7.1/7.2 pretest

multimedia/ffmpeg/Portfile, multimedia/ffmpeg/files/patch-texinfo7x-pretest-support.diff
=> ffmpeg: Add support for texinfo 7.1/7.2 pretest

multimedia/ffmpeg6/Portfile, multimedia/ffmpeg6/files/patch-texinfo7x-pretest-support.diff
=> ffmpeg6: Add support for texinfo 7.1/7.2 pretest

multimedia/ffmpeg-devel/Portfile, multimedia/ffmpeg-devel/files/patch-texinfo7x-pretest-support.diff
=> ffmpeg-devel: Add support for texinfo 7.1/7.2 pre

sysutils/mise/Portfile
mise: Update to 2025.2.9
Have you
=> mise: Update to 2025.2.9

multimedia/ffmpeg4/Portfile, multimedia/ffmpeg4/files/patch-texinfo7x-pretest-support.diff
=> ffmpeg4: Add support for texinfo 7.1/7.2 pretest

textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.10
Have you
=> ocrmypdf: update to 16.10

science/iverilog/Portfile, science/iverilog/files/patch-vvp-Makefile.in.diff
- Update iverilog from version 12.0 to tag s20250103 to support libvvp integration with ngspice.
- Split documentation into a new `iverilog-docs` port due to increased compile dependencies and source tree changes.
- Many text files, such as `cadpli.txt`, are no longer included upstream.
- Add patch for `libvvp.so` to ensure proper functionality.
macOS 13.7.2 22H313 x86_64
Have you
=> iverilog: update to s20250103, split documentation, add libvvp patch

devel/ruff/Portfile
Update `ruff` to its latest released version, 0.9.9
Have you
=> ruff: Update to 0.9.9

devel/docker-machine-parallels/Portfile, devel/docker-machine-parallels/files/patch-makefile.diff
Port currently fails to build for some macOS releases. Try to fix for all.
Fixes: https://trac.macports.org/ticket/65384
=> docker-machine-parallels: fix build

net/mqttui/Portfile
https://github.com/EdJoPaTo/mqttui/releases/tag/v0.22.0
Xcode 14.2
Have you
=> mqttui: update to 0.22.0

net/miniflux/Portfile
=> miniflux: update to 2.2.6

lang/groovy/Portfile
Update to Groovy 4.0.26.
Have you
=> groovy: update to 4.0.26

java/openjdk25-zulu/Portfile
New port for Azul Zulu OpenJDK 25.0.11 (Early Access).
Have you
=> openjdk25-zulu: new submission

python/py-codestyle/Portfile, python/py-codestyle/files/pycodestyle-py313
pycodestyle-py313 installs bin/pycodestyle-3.13, not bin/pycodestyle-3.12
`port select --set pycodestyle pycodestyle-py313` currently fails:
> Selecting 'pycodestyle-py313' for 'pycodestyle' failed: could not create new link "/opt/local/bin/pycodestyle": target "/opt/local/bin/pycodestyle-3.12" doesn't exist
The reason is that the file `files/pycodestyle-py313` contains a pointer to `bin/pycodestyle-3.12`, while instead it should contain `bin/pycodestyle-3.13`.
Have you
=> py-codestyle: Fix select for py313

net/rustscan/Portfile
Without nmap it cannot run any scripts and will exit with an error after scanning
macOS x.y
Have you
=> rustscan: add nmap as runtime dep

_resources/port1.0/group/crossbinutils-1.0.tcl, cross/i686-w64-mingw32-binutils/Portfile, cross/x86_64-w64-mingw32-binutils/Portfile
=> *-w64-mingw32-binutils: Update to 2.44

net/gallery-dl/Portfile
gallery-dl: update to 1.29.0
Have you
=> gallery-dl: update to 1.29.0

sysutils/mise/Portfile
mise: Update to 2025.3.0
Have you
=> mise: Update to 2025.3.0

shells/fish/Portfile
fish: update to 4.0.0
Have you
=> fish: update to 4.0.0

textproc/rhyme/Portfile, textproc/rhyme/files/patch-fatalError.diff
This pull request updates the `fatalError` function signature in the rhyme port. Previously, `setup.h` declared
`void fatalError(char s[]);`
while setup.c defined it as
`void fatalError(const char *s) { … }`
This inconsistency caused a build error on macOS 15.3 when `fatalError` was passed to `gdbm_open` (which expects a function pointer taking a `const char *`). Changing the declaration in `setup.h` to use `const char *` brings both files into alignment and resolves the conflict. The port revision has been bumped to 7 accordingly.
Have you
=> rhyme: update fatalError signature

emulators/qemu/Portfile
* qemu: Update 9.2.1 --> 9.2.2
* Also resolves previous checksum error due to stealth update.
CI only.  OS 13, 14, 15.
Have you
=> qemu: Update to 9.2.2

emulators/wine-stable/Portfile, emulators/wine-stable/files/MR7328.diff
This patch from upstream is only needed when building from source since https://github.com/macports/macports-ports/commit/7968ba7470e3c56ed67375a8c561d169273498f7 already prebuilt packages won't be affected.
=> wine-stable: Add patch for bug 57819

lang/nim/Portfile
Update to the latest version, per request: https://trac.macports.org/ticket/69115
Have you
=> nim: update to 2.2.2

x11/xorg-cf-files/Portfile
Closes: https://trac.macports.org/ticket/62895
=> xorg-cf-files: update to 1.0.8

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 513.0.0.
Have you
=> google-cloud-sdk: update to 513.0.0

security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.581
Have you
=> ipsw: Update to 3.1.581

gis/qgis3/Portfile
`hdf5` is opportunistically linked if found, so better add it as a dependency. Also make sure to find path to 'mpi.h'  if needed.
Closes: https://trac.macports.org/ticket/72100
macOS x.y
Have you
=> qgis3: add hdf5 as dependency

devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases/tag/v1.3.0
Xcode 14.2
Have you
=> jsoncons: update to 1.3.0

textproc/ov/Portfile
Add completions for `ov` on install.
Have you
=> ov: Add completions on install

lang/clojure/Portfile
=> clojure: update to  1.12.0.1530

www/wp2hugo/Portfile
wp2hugo: update to 1.11.0
Have you
=> wp2hugo: update to 1.11.0

sysutils/mise/Portfile
mise: Update to 2025.3.1
Have you
=> mise: Update to 2025.3.1

science/gildas/Portfile
Have you
- [x ] followed our [Commit Message Guidelines](https://trac.macports.org/wiki/CommitMessages)?
=> Gildas: update to 202503a

sysutils/mise/Portfile
mise: Update to 2025.3.2
Have you
=> mise: Update to 2025.3.2

devel/ruff/Portfile
Update `ruff` to its latest released version, 0.9.10
Have you
=> ruff: Update to 0.9.10

python/hyfetch/Portfile
Upgrade `hyfetch` to Python 3.13, following the `python` PG default Python version
Have you
=> hyfetch: Use Python 3.13

python/py-gobject3/Portfile
Update py-gobject3.
I've attempted to switch to meson build, but there's very little documentation out there to
suggest if this is the right way to do it.
It has worked for me, however.
Have you
=> Update to py-gobject3@3.50.0

devel/fossil/Portfile
- update live check URL to point to the page recommended
by the fossil maintainers.
- remove the `--with-exec-rel-paths` flag
Related Trac tickets:
- [69920](https://trac.macports.org/ticket/69920): original submission
- [65516](https://trac.macports.org/ticket/65516): abandoned port
Discussion related to the `--with-exec-rel-paths` flag:
- https://fossil-scm.org/forum/forumpost/06fd5536c1
- [65085](https://trac.macports.org/ticket/65085)
Closes: https://trac.macports.org/ticket/69920
Have you
=> fossil: update to 2.25, fix livecheck and config

gis/JOSM/Portfile
=> josm: update to 19342

net/lagrange/Portfile
https://github.com/skyjake/lagrange/releases/tag/v1.18.5
Xcode 14.2
Have you
=> lagrange: update to 1.18.5

python/py-awscli2/Portfile
=> py-awscli2: update to 2.24.20

math/SuiteSparse/Portfile
* update to version 7.10.1
* add ParU subport
Have you
=> SuiteSparse: update to version 7.10.1

net/gallery-dl/Portfile
gallery-dl: update to 1.29.1
Have you
=> gallery-dl: update to 1.29.1

textproc/asciidoc/Portfile
Closes: https://trac.macports.org/ticket/72169
Have you
=> asciidoc: Use python 3.13

security/opensc/Portfile
Remove the openssl3 variant and make it the default. Remove support for OpenSSL 1.1, which is no longer receiving security updates since September 2023.
Have you
=> opensc: Use OpenSSL 3

java/maven4/Portfile
Update to Maven 4.0.0-rc-3.
Have you
=> maven4: update to 4.0.0-rc-3

science/nco/Portfile
Simple update to upstream version 5.3.2.
It also replaces `github.tarball_from tarball` to `github.tarball_from archive`, as requested by comment in the `Portfile` for `nco-5.3.1-1`.
Have you
=> nco: update to 5.3.2

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 514.0.0.
Have you
=> google-cloud-sdk: update to 514.0.0

python/py-libxml2/Portfile, textproc/libxml2/Portfile
=> libxml2: update to 2.13.6

sysutils/mac-brightnessctl/Portfile
New port for [mac-brightnessctl](https://github.com/rakalex/mac-brightnessctl).
Have you
=> mac-brightnessctl: new submission

devel/gitu/Portfile
Update `gitu` to its latest released version, 0.29.0
Have you
=> gitu: Update to 0.29.0

gis/imposm/Portfile
https://github.com/omniscale/imposm3/releases/tag/v0.14.1
Xcode 14.2
Have you
=> imposm: update to 0.14.1

net/paho.mqtt.cpp/Portfile
https://github.com/eclipse-paho/paho.mqtt.cpp/releases/tag/v1.5.2
Xcode 14.2
Have you
=> paho.mqtt.cpp: update to 1.5.2

security/zizmor/Portfile
zizmor: Update to 1.5.1
Have you
=> zizmor: Update to 1.5.1

textproc/csvtk/Portfile
csvtk is a toolkit for manipulating CSV files.
macOS 15.3.2 24D81 arm64 Xcode 16.2 16C5032a
Have you
=> csvtk: New Port

shells/fish/Portfile
fish: update to 4.0.1
Have you
=> fish: update to 4.0.1

science/ecCodes/Portfile
Simple update to upstream version 2.40.0
Have you
=> ecCodes: update to 2.40.0

R/R-RNetCDF/Portfile
This PR just changes a comment on a required patch to g95. The original was found to be confusing. See #27710.
There is no change to the source code, version number, nor the package. So no revbump.
Have you
=> R-Rnetcdf: change confusing comment in Portfile

gis/gdal/Portfile
Add the HFA/ERDAS [driver](https://gdal.org/en/stable/drivers/raster/hfa.html#raster-hfa), which is usually built by default to GDAL.
Have you
=> gdal: add HFA (ERDAS Imagine) driver

math/OpenBLAS/Portfile
=> OpenBLAS: update to 0.3.29

sysutils/g-ls/Portfile
Update `g-ls` to its latest released version, 0.30.0
Have you
=> g-ls: Update to 0.30.0

java/mvnd2/Portfile
Update to mvnd 2.0.0-rc-3.
Have you
=> mvnd2: update to 2.0.0-rc-3

net/sfeed/Portfile
https://git.codemadness.org/sfeed/log.html
Xcode 14.2
Have you
=> sfeed: update to 2.2

science/netcdf/Portfile
Fixes: https://trac.macports.org/ticket/70185
When not adding cxx to the list, it won't find mpicxx.
=> netcdf: Configure cxx compiler, too.

devel/ruff/Portfile
Update `ruff` to its latest released version, 0.11.0
Have you
=> ruff: Update 0.11.0

x11/turbovnc-viewer/Portfile
Update turbovnc-viewer to latest version 3.1.4. Present version 2.2.6 doesn't build on Mac OS 15.3.1 with the default java and libjpeg-turbo.
Have you
=> turbovnc-viewer: update to 3.1.4

gis/GPXSee/Portfile
=> GPXSee: update to 13.37

sysutils/mise/Portfile
mise: Update to 2025.3.3
Have you
=> mise: Update to 2025.3.3

python/py-igraph/Portfile
- depend on external plfit with the -external_igraph variant
- remove no-longer-necessary settings from portfile
Have you
=> py-igraph: depend on external plfit

devel/git/Portfile, perl/p5-mac-systemdirectory/Portfile
```
added :
PortGroup           conflicts_build 1.0
conflicts_build     libuuid
On branch libuuidconflicts
modified:   devel/git/Portfile
modified:   perl/p5-mac-systemdirectory/Portfile
```
closes: https://trac.macports.org/ticket/72200
closes: https://trac.macports.org/ticket/63365
Have you
=> git, p5-mac-systemdirectory : fails to build when the libuuid port is active

science/eso-flames-fposs/Portfile, science/eso-flames-fposs/files/Makefile_Darwin.diff, science/eso-flames-fposs/files/fposs.sh.tpl.diff, science/eso-flames-fposs/files/pafchk.makefile.novlt.diff
New Portfile eso-flames-fposs
FPOSS is the Observation preparation Software for the FLAMES instrument on the European Southern Observatory's Very large telescope.
Have you
=> eso-flames-fposs: new port

python/py-pygments-mathematica/Portfile
=> new port: py-pygments-mathematica

java/openjdk24-zulu/Portfile
=> openjdk24-zulu: include short description in long_description

java/openjdk24-corretto/Portfile
New port for Amazon Corretto 24.
Have you
=> openjdk24-corretto: new submission

java/openjdk25-zulu/Portfile
Update to Azul Zulu 25.0.29.
Have you
=> openjdk25-zulu: update to 25.0.29

java/jdk24/Portfile
New port for Oracle Java SE Development Kit 24.
Have you
=> jdk24: new submission

java/jdk24-graalvm/Portfile
New port for Oracle GraalVM for JDK 24.
Have you
=> jdk24-graalvm: new submission

net/tlrc/Portfile
Update `tlrc` to its latest released, 1.11.0
Have you
=> tlrc: Update to 1.11.0

ruby/ruby-build/Portfile
ruby-build: Update to 20250318
Have you
=> ruby-build: Update to 20250318

sysutils/mise/Portfile
mise: Update to 2025.3.6
Have you
=> mise: Update to 2025.3.6

security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.585
Have you
=> ipsw: Update to 3.1.585

science/mpich/Portfile
macOS 15.3.2 24D2082 arm64
Have you
=> mpich: build with python 3.13

java/openjdk24/Portfile, java/openjdk24/files/JDK-8340341-clang-16-workaround.patch
New port for OpenJDK 24.
Have you
=> openjdk24: new submission

java/openjdk24-sap/Portfile
New port for SapMachine 24.
Have you
=> openjdk24-sap: new submission

java/openjdk24-sap/Portfile
=> openjdk24-sap: update description

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 515.0.0.
Have you
=> google-cloud-sdk: update to 515.0.0

science/ecCodes/Portfile
* Use legacy support PG to fix builds for macos <= 10.12.
* Fixes undefined symbols for "std::bad_optional_access::~bad_optional_access()".
Have you
=> eccodes: Fix builds for macos <= 10.12

print/ghostscript/Portfile
Relatively simple update to upstream version 10.05.0
Also:
* Replaced tabs in the Portfile by spaces.
* Removed comment to also "update ghostscript-fonts-hiragino Portfile to keep version in sync". In fact, that Portfile is broken as the referenced fonts from ghostscript no longer exist. This was likely broken since ghostscript version 10, as that Portfile still refers to version 9.54.0.
* `mappingresources_commit` did not need to be updated; it is the latest version.
The library version did not change, so no dependencies need to be bumped.
Have you
=> ghostscript: update to 10.05.0

java/openjdk24-temurin/Portfile
New port for Eclipse Temurin 24.
Have you
=> openjdk24-temurin: new submission

lang/kotlin/Portfile
Update to Kotlin 2.1.20.
Have you
=> kotlin: update to 2.1.20

devel/skaffold/Portfile
Update to Skaffold 2.14.2.
Have you
=> skaffold: update to 2.14.2

perl/p5-dbd-mysql/Portfile
Fix issue where multiple variant conflicts were being set as a single
conflict. Fixing this also allowed for the removal of the
active_vartiants workaround.
- fix variant conflicts
- remove active variants workaround\
- fix typos
Closes: https://trac.macports.org/ticket/60517
Closes: https://trac.macports.org/ticket/71360
Closes: https://trac.macports.org/ticket/71381
Note - I have these broken into 2 commits to allow them to be tracked easier.
Correct improper variant conflicts issue where all conflicts were handled as a single port.  Additionally, attempt to address typos (at least the ones I can find) and add back the legacy mariadb10_2 variant.
Have you
=> p5-dbd-mysql: Fix variant conflicts issues

java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.4.4.
Have you
=> spring-boot-cli: update to 3.4.4

python/py-pydicom/Portfile, python/py-pynetdicom/Portfile
=> py-py[net]dicom: Add py313 flavors

sysutils/mise/Portfile
mise: Update to 2025.3.7
Have you
=> mise: Update to 2025.3.7

devel/zmq/Portfile
zeromq 4.3.5 changed the default for the ENABLE_CURVE option to false instead of true while removing the tweetnacl implementation because of an inability to license (see https://github.com/zeromq/libzmq/pull/4554).  The macports 4.3.5 version bump, however, didn't specify the option and so currently doesn't support secure zmq connections at all, while 4.3.4 and earlier *always* supported CURVE regardless of the variant (either via libsodium or the build-in tweetnacl, depending on whether the sodium variant was used).
This reenables it behind a new, default-enabled `curve` variant (which depends on the already-default `libsodium` as that is now the only supported zeromq curve implementation) so that the default variant zmq package supports curve encryption, as it did for versions before …
=> zmq: Re-enable CURVE encryption

emulators/wine/Portfile
=> wine: Update to account for macOS 10.12

lang/ucblogo/Portfile
Update ucblogo to version 6.2.5 and add a variant for building the GUI version.
Have you
=> ucblogo: update to 6.2.5

sysutils/lima/Portfile
lima: Update to 1.0.7
Have you
=> lima: Update to 1.0.7

security/zizmor/Portfile
zizmor: Update to 1.5.2
Have you
=> zizmor: Update to 1.5.2

python/py-awscli2/Portfile, python/py-awscli2/files/0001-py-awscli2-Support-empty-PAGER.patch
=> py-awscli2: update to 2.25.1

devel/qt6-qtcreator/Portfile
=> qt6-qtcreator: use llvm 20 for macOS 15+

devel/ruff/Portfile
Update `ruff` to its latest released version, 0.11.2
Have you
=> ruff: Update to 0.11.2

gis/osmium-tool/Portfile
Changelog: https://github.com/osmcode/osmium-tool/releases
macOS 12.6.2
Xcode 14.2
Have you
=> osmium-tool: update to 1.18.0

science/iverilog/Portfile
Changed the maintainers to reflect those whom showed an interest.
Removed the former maintainer as they are no longer active with Macports.  Added myself and markemer as we have an interest in the package.
macOS 13.7.4 22H420 x86_64
Have you
=> iverilog: transfer maintainers

databases/postgresql16/Portfile
```
modified:   databases/postgresql16/Portfile
```
Since the port used depends_build without -append, our powerpc chunk has no effect on dependencies requirements, and perl5 is ignored, so the clean build still fails. Either powerpc chunk should be moved below, after initial depends_build, or in both cases -append should be used.
=> postgresql16 : fix powerppc depends_build-append for perl

net/gallery-dl/Portfile
gallery-dl: update to 1.29.2
Have you
=> gallery-dl: update to 1.29.2

devel/mani/Portfile
mani: Update to 0.30.1
Have you
=> mani: Update to 0.30.1

devel/unicorn/Portfile
unicorn: update to 2.1.3
Have you
=> unicorn: update to 2.1.3

sysutils/nnn/Portfile
https://github.com/jarun/nnn/releases/tag/v5.1
Xcode 14.2
Have you
=> nnn: update to 5.1

devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 516.0.0.
Have you
=> google-cloud-sdk: update to 516.0.0

net/sshuttle/Portfile
https://github.com/sshuttle/sshuttle/releases/tag/v1.3.1
Xcode 14.2
Have you
=> sshuttle: update to 1.3.1

security/logwatch/Portfile
Do not use the perl stub
Closes: https://trac.macports.org/ticket/72188
macOS x.y
Have you
=> logwatch: correct perl dependencies

security/pinact/Portfile
pinact is a CLI to edit GitHub Workflow and Composite action files and
pin versions of Actions and Reusable Workflows. pinact can also update
their versions and verify version annotations.
Have you
=> pinact: New Port

sysutils/mise/Portfile
mise: Update to 2025.3.10
Have you
=> mise: Update to 2025.3.10
