macports/macports-ports

- ruby/ruby-build/Portfile
ruby-build: Update to 20250326
Have you
> ruby-build: Update to 20250326

- devel/cocogitto/Portfile
The Conventional Commits toolbox, providing verified commits, automatic version bump and changelog, release profiles, conventional git log, GitHub integration, and monorepo support.
Have you
> cocogitto: New port at 6.3.0

- science/netcdf/Portfile
Fixes: https://trac.macports.org/ticket/72243
Removed from the Portfile the reference to an already deleted obsolete patch.
This only applied to the `+hdf4` option.
Since the build for this failed, no need to revbump.
Have you
> netcdf: removed reference to obsolete patch

- sysutils/fswatch/Portfile
Closes: https://trac.macports.org/ticket/71758
Closes: https://trac.macports.org/ticket/71935 (fixed upstream)
Have you
> fswatch: use legacysupport.use_mp_libcxx on macOS Mojave and older

- devel/uv/Portfile
Update `uv` to its latest released version, 0.6.10. [Commit change of astral-sh/uv@`0.6.1...0.6.10`](https://github.com/astral-sh/uv/compare/0.6.1...0.6.10)
Have you
> uv: Update to 0.6.10

- www/lighttpd/Portfile
lighttpd: Update to 1.4.78
macOS 11.7
Have you
> lighttpd: Update to 1.4.78

- devel/lazarus/Portfile
lazarus: Fix 3.8 on macOS 10.13 (High Sierra) and lower
There is no separate framework Usernotifications on macOS 10.13 and lower
Note this test only tests that the package is not broken on the most recent version of macOS. The pipelines will show, whether the fix actually works. Unfortunately, I have no older systems available.
Have you
- [] referenced existing tickets on [Trac](https://trac.macports.org/wiki/Tickets) with full URL in commit message?
> lazarus: Fix 3.8 on macOS 10.13 (High Sierra) and lower

- devel/dagger/Portfile
Update to [latest release](https://github.com/dagger/dagger/releases/tag/v0.17.1).
Have you
> dagger: update to 0.17.1

- devel/buf/Portfile
Added a new port for Buf, a tool for working with Protocol Buffers.
Have you
> buf: new Portfile

- sysutils/mise/Portfile
mise: Update to 2025.3.11
Have you
> mise: Update to 2025.3.11

- security/pinact/Portfile
pinact: Update to 2.2.1
Have you
> pinact: Update to 2.2.1

- editors/neovim/Portfile
- update neovim to 0.11.0
- update neovim-devel to 20250328
Also, restrict to MacOS >= 10.11 due to past build failures. See https://github.com/macports/macports-ports/commit/670a0f4eb6
Have you
> neovim, -devel: update to 0.11.0 and 20250328

- mail/muchsync/Portfile
- mail/notmuch/Portfile
Drop out of maintainership for the `muchsync` and `notmuch` ports. No other changes are included in this pull request.
> Drop maintainership for muchsync & notmuch

- lang/fpc/Portfile
- lang/fpc/files/rautils.patch
fix taking from this commit:
https://gitlab.com/freepascal.org/fpc/source/-/commit/e749c81040070d3e8cb0c070e6e63f2f9b54fef4
Expected to be part of version 3.2.4
Have you
> fpc: fix building for macOS 15 and x86_64

- science/netcdf-fortran/Portfile
- science/netcdf-fortran/files/patch-nf-config.diff
Update to upstream version 4.6.2
* Changes `tarball` to `archive` as requested in Portfile
* Ensures that `zstd` is supported when it is so in `netcdf`
* Removes part of patch as original file has been removed
Have you
> netcdf-fortran: update to 4.6.2

- devel/libmaxminddb/Portfile
Closes: https://trac.macports.org/ticket/72187
Have you
> libmaxminddb: remove p5-ipc-run3 stub dependency

- net/netatalk4/Portfile
New major version of netatalk is from a new upstream maintainer. https://netatalk.io/
Have you
> netatalk4: Add port

- devel/CLI11/Portfile
https://github.com/CLIUtils/CLI11/releases/tag/v2.5.0
Xcode 14.2
Have you
> CLI11: update to 2.5.0

- security/pinact/Portfile
Add .pinact.yaml migration instructions on install.
Have you
> pinact: Upgrade to 3.0.1

- net/lldpd/Portfile
[lldpd](https://lldpd.github.io) is a daemon that implements LLDP and LLDP-MED.
LLDP (Link Layer Discovery Protocol) is a link-local protocol—that is, it's limited to the physical Ethernet connection between one device and another—that devices use to exchange information about how they are connected, and what their capabilities are, from a Layer-1 and Layer-2 perspective.
For example, say your Mac has a physical Ethernet connection that is plugged into a switch.  If both sides support LLDP, the switch might tell you:
* Its make, model, and OS.
* The name of the switch, and its management IP address.
* What type of Ethernet connections are supported (you may be on a port that can support 10-Gigabit Ethernet).
* What VLAN you are on, and for tagged (802.11q) VLANs, what VLANs are being …
> lldpd: new port

- lang/fpc/files/rautils.patch
fpc: fix building on macOS 15 - x86_64, 2nd try.
Now it has the correct the path to file rautils.pas in the patch file.
Note: As before, this does not actually test the fix, as I have no access to macOS 15 on x86_64. So, the pipeline will show.
Have you
> fpc: fix building on macOS 15 - x86_64, 2nd try

- graphics/ImageMagick7/Portfile
ImageMagick7: Update 7.1.1-43 --> 7.1.1-47
CI only.
Have you
> ImageMagick7: Update to 7.1.1-47

- databases/mariadb-10.11/Portfile
- databases/mariadb-10.5/Portfile
- databases/mariadb-10.6/Portfile
```
On branch mariadb10
updated :
modified:   databases/mariadb-10.5/Portfile @10.5.28
modified:   databases/mariadb-10.6/Portfile @10.6.21
modified:   databases/mariadb-10.11/Portfile @10.11.11
```
[https://mariadb.org/mariadb/all-releases/](https://mariadb.org/mariadb/all-releases/)
[https://endoflife.date/mariadb](https://endoflife.date/mariadb)
Model Identifier: Macmini6,1
Model Identifier: MacPro5,1
macOS 14.7.4 23H420 x86_64
Have you
> mariadb-10.{5,6,11}: update to 10.5.25, 10.6.21, 10.11.11

- science/dftd3/Portfile
dftd3: Dispersion correction for quantum chemical methods
Have you
> dftd3: new package

- finance/pta/Portfile
- finance/pta/files/patch-Makefile.diff
[pta](https://mandoc.bsd.lv/pta/) reads bookkeeping journals and writes account lists, balances, and cost center assessments to standard output. All input files are ASCII text files.
It is written in [Perl 5](https://www.perl.org/) and comes with an [ISC](https://www.isc.org/licenses/) license.
Have you
> pta: new port, version 0.1

- net/gallery-dl/Portfile
gallery-dl: update to 1.29.3
Have you
> gallery-dl: update to 1.29.3

- lang/pascal-p5/Portfile
pascal-p5: update to newer upstream version
Also enable on arm64
Have you
> pascal-p5: update

- sysutils/ddrescue/Portfile
* add myself as co-maintainer
https://lists.gnu.org/archive/html/info-gnu/2025-03/msg00011.html
Have you
> ddrescue: update to 1.29.1

- net/youtube-dl/Portfile
macOS 10.15.1 19B88 x86_64
Command Line Tools 11.2.0.0.1.1571444319
Have you
> yt-dlp: Update to 2025.03.27

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 517.0.0.
Have you
> google-cloud-sdk: update to 517.0.0

- sysutils/mise/Portfile
mise: Update to 2025.4.0
Have you
> mise: Update to 2025.4.0

- science/gildas/Portfile
> Gildas: update to 202504a

- science/nco/Portfile
Simple update to upstream version 5.3.3
Have you
> nco: update to 5.3.3

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.590. [blacktop/ipsw@``v3.1.585...v3.1.590``](https://github.com/blacktop/ipsw/compare/v3.1.585...v3.1.590)
Have you
> ipsw: Update to 3.1.590

- net/newsraft/Portfile
https://codeberg.org/newsraft/newsraft/releases/tag/newsraft-0.29
Xcode 14.2
Have you
> newsraft: update to 0.29

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.77.0

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.11.4
Have you
> ruff: Update to 0.11.4

- devel/cmark-gfm/Portfile
[cmark-gfm](https://github.com/github/cmark-gfm) is an extended version of the C reference implementation of CommonMark, a rationalized version of Markdown syntax with a spec. This repository adds GitHub Flavored Markdown extensions to the upstream implementation, as defined in the spec.
The rest of the README is preserved as-is from the upstream source. Note that the library and binaries produced by this fork are suffixed with -gfm in order to distinguish them from the upstream.
macOS 15.2
Xcode 16.2
Have you
> cmark-gfm: new port

- fuse/gocryptfs/Portfile
I am no longer using gocryptfs and have no possibility to test new releases.
> gocryptfs: Remove @MarcelBochtler as maintainer

- security/pinact/Portfile
Upgrade pinact to v3.0.3.
Have you
> pinact: Update to 3.0.3

- sysutils/chezmoi/Portfile
chezmoi: Update to 2.62.0
Have you
> chezmoi: Update to 2.62.0

- editors/neovim/Portfile
Previously, during build-time Neovim's build system would fetch missing Tree-sitter syntaxes online. This introduces a change to leverage MacPorts ability to fetch more than one distfile and moves these new files to their expected place.
Also:
- bumped neovim-devel version
Have you
> neovim{,-devel}: prevent build-time fetching

- security/grype/Portfile
> grype: Update to 0.91.0

- java/openjdk25-zulu/Portfile
Update to Azul Zulu 25.0.31.
Have you
> openjdk25-zulu: update to 25.0.31

- java/micronaut/Portfile
Update to Micronaut Starter 4.8.0.
Have you
> micronaut: update to 4.8.0

- devel/skaffold/Portfile
Update to Skaffold 2.15.0.
Have you
> skaffold: update to 2.15.0

- www/nginx/Portfile
The version of PCRE installed by the pcre port is EOL. The lua module for nginx has supported pcre2 since version 0.10.26.
See: https://github.com/openresty/lua-nginx-module/commit/cb83e33e26579788be0fe0282fa5976de6dfa6e3
> nginx: use pcre2

- sysutils/mise/Portfile
mise: Update to 2025.4.1
Have you
> mise: Update to 2025.4.1

- net/cidr/Portfile
The homepage and the distfile from the master_sites are no longer available. Update them to a reliable mirror on github.
> net/cidr: Update master_sites, homepage

- gis/JOSM/Portfile
> josm: update to 19369

- emulators/kegworks/Portfile
> kegworks: update to 2.0.4

- science/ecCodes/Portfile
Simple update to upstream version 2.41.0
Have you
> ecCodes: update to 2.41.0

- ruby/ruby-build/Portfile
ruby-build: Update to 20250409
Have you
> ruby-build: Update to 20250409

- www/lighttpd/Portfile
lighttpd: Update to 1.4.79
macOS 11.7
Have you
> lighttpd: Update to 1.4.79

- sysutils/mise/Portfile
mise: Update to 2025.4.2
Have you
> mise: Update to 2025.4.2

- net/syncthing/Portfile
syncthing: update to 1.29.5
Have you
> syncthing: update to 1.29.5

- sysutils/resticprofile/Portfile
macOS 15.1 24B2083 arm64
Have you
> resticprofile: update to 0.30.0

- devel/libffi/Portfile
- devel/libffi/files/patch-sources.diff
This cherry-picks an upstream fix for a build problem with a recent clang.  Although the fix is included in v3.4.7, the latter has significantly more test failures than v3.4.6.  Until that is investigated further, we stay on v3.4.6 with the cherry-picked fix, to avoid a possible functional regression.
Due to the (admittedly unlikely) possibility that this changes the installed content, it includes a revbump, which is not very expensive for this particular port.  No revbumping of dependents is needed.
Closes: https://trac.macports.org/ticket/72271
The unified patchfile is also renamed with a more generic name.
TESTED:
Successfuly built -/+universal on 10.4-10.5 ppc, 10.5-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-15.x arm64. Tests not included due to many known …
> libffi: Fix build on Sequoia.

- devel/kubecolor/Portfile
It adds `kubecolor` as a new `MacPorts` port.
https://github.com/kubecolor/kubecolor/issues/224
Have you
> kubecolor: new port

- python/py-pyside6/Portfile
Ticket reference: https://trac.macports.org/ticket/70343
Have you
> New port py-pyside6, version 6.9.0

- net/gallery-dl/Portfile
gallery-dl: update to 1.29.4
Have you
> gallery-dl: update to 1.29.4

- sysutils/kubie/Portfile
kubie: Update to 0.25.2
Have you
> kubie: Update to 0.25.2

- sysutils/mise/Portfile
mise: Update to 2025.4.3
Have you
> mise: Update to 2025.4.3

- java/jdk24/Portfile
Update to JDK 24.0.1.
Have you
> jdk24: update to 24.0.1

- java/jdk24-graalvm/Portfile
Update to GraalVM for JDK 24.0.1.
Have you
> jdk24-graalvm: update to 24.0.1

- ruby/ruby-build/Portfile
ruby-build: Update to 20250415
Have you
> ruby-build: Update to 20250415

- java/jdk21-graalvm/Portfile
Update to GraalVM for JDK 21.0.7.
Have you
> jdk21-graalvm: update to 21.0.7

- lang/ruby33/Portfile
- lang/ruby33/files/patch-sources.diff
See:
https://www.ruby-lang.org/en/news/2025/04/09/ruby-3-3-8-released/
TESTED:
Built successfully on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-15.x arm64.  Included all variants compatible with available dependencies on the respective platforms.
``` …
```
> ruby33: update to 3.3.8

- python/py-sphinx-copybutton/Portfile
Add support for Python 3.13 to the py-sphinx-copybutton package.
Since this version was not supported before, and nothing changes for the already existing subports, no version bump is needed.
Have you
> py-sphinx-copybutton: add support for py313

- java/jdk21/Portfile
Update to JDK 21.0.7.
Have you
> jdk21: update to 21.0.7

- java/openjdk24-sap/Portfile
Update to SapMachine 24.0.1.
Have you
> openjdk24-sap: update to 24.0.1

- java/openjdk24-corretto/Portfile
Update to Amazon Coretto 24.0.1.9.1.
Have you
> openjdk24-coretto: update to 24.0.1.9.1

- java/openjdk21-corretto/Portfile
Update to Amazon Coretto 21.0.7.6.1.
Have you
> openjdk21-coretto: update to 21.0.7.6.1

- java/openjdk11-corretto/Portfile
Update to Amazon Coretto 11.0.27.6.1.
Have you
> openjdk11-coretto: update to 11.0.27.6.1

- java/openjdk8-corretto/Portfile
Update to Amazon Coretto 8.452.09.1.
Have you
> openjdk8-coretto: update to 8.452.09.1

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 518.0.0.
Have you
> google-cloud-sdk: update to 518.0.0

- devel/qbs/Portfile
> qbs: Update to 2.6.1

- java/openjdk21-zulu/Portfile
Update to Azul Zulu 21.42.19.
Have you
> openjdk21-zulu: update to 21.42.19

- java/openjdk24-zulu/Portfile
Update to Azul Zulu 24.30.11.
Have you
> openjdk24-zulu: update to 24.30.11

- java/openjdk17-zulu/Portfile
Update to Azul Zulu 17.58.21.
Have you
> openjdk17-zulu: update to 17.58.21

- java/openjdk11-zulu/Portfile
Update to Azul Zulu 11.80.21.
Have you
> openjdk11-zulu: update to 11.80.21

- java/openjdk8-zulu/Portfile
Update to Azul Zulu 8.86.0.25.
Have you
> openjdk8-zulu: update to 8.86.0.25

- java/openjdk17/Portfile
Update to OpenJDK 17.0.15.
Have you
> openjdk17: update to 17.0.15

- java/openjdk21-sap/Portfile
Update to SapMachine 21.0.7.
Have you
> openjdk21-sap: update to 21.0.7

- java/openjdk17-sap/Portfile
Update to SapMachine 17.0.15.
Have you
> openjdk17-sap: update to 17.0.15

- www/dart-sass/Portfile
Updates dart-sass to 1.86.3
Requires new port: https://github.com/macports/macports-ports/pull/28024
Have you
> dart-sass: update to 1.86.3

- python/py-agate-dbf/Portfile
- python/py-agate-excel/Portfile
- python/py-agate-sql/Portfile
- python/py-agate/Portfile
- python/py-csvkit/Portfile
- python/py-csvkit/files/py313-csvkit
- python/py-dbfread/Portfile
- python/py-isodate/Portfile
- python/py-leather/Portfile
- python/py-pytimeparse/Portfile
- python/py-slugify/Portfile
- python/py-xlrd/Portfile
Add support for Python 3.13 to py-csvkit as well as to its dependencies:
* py-agate
* py-agate-dbf
* py-agate-excel
* py-agate-sql
* py-dbfread
* py-isodate
* py-leather
* py-pytimeparse
* py-slugify
* py-xlrd
No revision bump is needed since the py313-* variant was not available for any of these before, and nothing changes for the existing py*-* variants.
Have you
> py-csvkit: add support for py313 (also dependencies)

- security/cosign/Portfile
> cosign: update to 2.5.0

- devel/direnv/Portfile
direnv: Update to 2.36.0
Have you
> direnv: Update to 2.36.0

- java/openjdk21-temurin/Portfile
Update to Eclipse Temurin 21.0.7.
Have you
> openjdk21-temurin: update to 21.0.7

- python/py-fido2/Portfile
- python/py-fido2/files/e2eb7d4a52a762795c1a8aa9804f184b11b5e64d.patch
- security/yubikey-manager/Portfile
- security/yubikey-manager/files/b951fcd0c6e916a5ccf751307b8dcdf71149b38a.patch
- security/yubikey-manager4/Portfile
- security/yubikey-manager4/files/0001-Avoid-using-PCSCContext-if-it-is-unavailable.patch
This fixes Yubico Authenticator.
See
https://github.com/Yubico/python-fido2/commit/e2eb7d4a52a762795c1a8aa9804f184b11b5e64d
and
https://github.com/Yubico/yubikey-manager/commit/b951fcd0c6e916a5ccf751307b8dcdf71149b38a
Have you
> py-fido2, yubikey-manager(4): Backport upstream fixes for py-scard API change

- audio/whisper/Portfile
- audio/whisper/files/add-metal-path.diff
- audio/whisper/files/ggml-hard-coded.diff
- audio/whisper/files/whisper-add-depends.diff
- audio/whisper/files/whisper-add-models.diff
* updates to new version
* package now uses CMake to build
* now installs needed *.dylib files to lib/
Closes: https://trac.macports.org/ticket/72073
Have you
> whisper: update to 1.7.5

- science/ortep3/Portfile
-O2 optimization creates wrong overlap of lines calculations.
Have you
> ortep3: fix errorneous lines in graphics output

- lang/ruby34/Portfile
- lang/ruby34/files/patch-generated.diff
- lang/ruby34/files/patch-sources.diff
See:
https://www.ruby-lang.org/en/news/2025/04/14/ruby-3-4-3-released/
TESTED:
Built successfully on OSX 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-15.x arm64.  Included all variants compatible with available dependencies on the respective platforms.
``` …
```
> ruby34: update to 3.4.3

- science/gildas/Portfile
> Gildas: update to 202504b

- java/openjdk17-temurin/Portfile
Update to Eclipse Temurin 17.0.15.
Have you
> openjdk17-temurin: update to 17.0.15

- devel/libffi/Portfile
- devel/libffi/files/patch-sources.diff
As usual, the patchfile is derived from git differences, which no longer include the now-upstream fix for the build problem on Sequoia.
As usual, there are many test failures, but 3.4.8 is roughly comparable to 3.4.6 in this regard.
TESTED:
Tested -/+universal on 10.4-10.5 ppc, 10.5-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-15.x arm64.
```
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, …
```
> libffi: update to 3.4.8

- sysutils/mise/Portfile
mise: Update to 2025.4.5
Have you
> mise: Update to 2025.4.5

- devel/ddev/Portfile
Update ddev port to version 1.24.4. Release notes: https://github.com/ddev/ddev/releases/tag/v1.24.4
> ddev: update to 1.24.4

- python/py-gnupg/Portfile
* Update py-gnupg to the latest release
* Enable support for Python 3.13
* Disable test that relies on external keyservers
Have you
> py-gnupg: Update to 0.5.4, enable support for Python 3.13, fix tests

- python/py-nclib/Portfile
Enable Python 3.13 support for py-nclib.
Have you
> py-nclib: Enable support for Python 3.13

- ruby/ruby-build/Portfile
ruby-build: Update to 20250418
Have you
> ruby-build: Update to 20250418

- sysutils/chezmoi/Portfile
chezmoi: Update to 2.62.2
Have you
> chezmoi: Update to 2.62.2

- security/pinact/Portfile
pinact: Update to 3.0.5
Have you
> pinact: Update to 3.0.5

- x11/auto-multiple-choice/Portfile
auto-multiple-choice: update to version 1.7.0
auto-multiple-choice-devel: update to version 1.7.0
Xcode 16.3 16E140 
MacPorts 2.10.5
Have you
> auto-multiple-choice: update to version 1.7.0

- java/openjdk24-temurin/Portfile
Update to Eclipse Temurin 24.0.1.
Have you
> openjdk24-temurin: update to 24.0.1

- java/openjdk8-temurin/Portfile
Update to Eclipse Temurin 8u452.
Have you
> openjdk8-temurin: update to 8u452

- java/micronaut/Portfile
Update to Micronaut Starter 4.8.2.
Have you
> micronaut: update to 4.8.2

- audio/whisper/Portfile
> whisper: fix wrong # args: should be "sha256 action ?file?"

- gis/GPXSee/Portfile
> GPXSee: update to 13.39

- devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases
Xcode 14.2
Have you
> jsoncons: update to 1.3.2

- mail/lbdb/Portfile
* Also adds a description for the LDAP variant.
I am willing to add myself to maintainers for this port since I use it regularly.
Have you
> lbdb: update to 0.56

- textproc/tinyxml2/Portfile
update to 11.0.0 which has a fix https://github.com/advisories/GHSA-884x-p7qm-gq3f which was a problem parsing character encodings.
Have you
> tinyxml2: update to 11.0.0

- security/zizmor/Portfile
zizmor: Update to 1.6.0
Have you
> zizmor: Update to 1.6.0

- databases/postgresql14/Portfile
- databases/postgresql14/files/patch-strchrnul.diff
- databases/postgresql15/Portfile
- databases/postgresql15/files/patch-strchrnul.diff
- databases/postgresql16/Portfile
- databases/postgresql16/files/patch-strchrnul.diff
- databases/postgresql17/Portfile
- databases/postgresql17/files/patch-strchrnul.diff
> postgresql: fix strchrnul on 15.4

- security/cosign/Portfile
`sget` has been removed from cosign as of  sigstore/cosign#2885. It is no longer possible to install this port with the `sget` command, as its source code is no longer present in upstream.
Have you
> cosign: remove sget variant

- java/openjdk24/Portfile
Update to OpenJDK 24.0.1.
Have you
> openjdk24: update to 24.0.1

- sysutils/k9s/Portfile
Update to k9s 0.50.4.
Have you
> k9s: update to 0.50.4

- shells/fish/Portfile
fish: update to 4.0.2
Have you
> fish: update to 4.0.2

- databases/postgresql16/Portfile
- databases/postgresql17/Portfile
Switch to the same path dependency used by other ports.
Closes: https://trac.macports.org/ticket/72215
This problem is breaking ports that depend on both cmake and postgresql16 or 17, because of unexpected conflict between curl-ca-bundle and certsync.
A current example is gdal following its recent update.
See https://trac.macports.org/ticket/72215 for details.
CI only.  Macos 13, 14, 15.
Early CI failure on Macos 15, due to recent SDK update to 15.4, is now solved by PR #28208.
Have you
> postgresql16/17: Remove conflict, fix dependant builds

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.11.6
Have you
> ruff: Update to 0.11.6

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.595
Have you
> ipsw: Update to 3.1.595

- java/openjdk11-temurin/Portfile
Update to Eclipse Temurin 11.0.27.
Have you
> openjdk11-temurin: update to 11.0.27

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 519.0.0.
Have you
> google-cloud-sdk: update to 519.0.0

- devel/gperf/Portfile
https://lists.gnu.org/archive/html/info-gnu/2025-04/msg00013.html
Closes: https://trac.macports.org/ticket/71950
Have you
> gperf: update to 3.3

- sysutils/mise/Portfile
mise: Update to 2025.4.6
Have you
> mise: Update to 2025.4.6

- devel/pkgconf/Portfile
Update `pkgconf` to its latest released version, 2.4.3. The `legacysupport` PortGroup is now needed to fix building `libpkgconf` on older systems (e.g OSX 10.7)
Have you
> pkgconf: Update to 2.4.3

- java/openjdk11-microsoft/Portfile
Update to Microsoft Build of OpenJDK 11.0.27.
Have you
> openjdk11-microsoft: update to 11.0.27

- sysutils/podman/Portfile
> podman: update to version 5.4.2

- python/py-future/Portfile
py-future: add support for python 3.13
* add support for python 3.13
Have you
> py-future: add support for python 3.13

- sysutils/mise/Portfile
mise: Update to 2025.4.8
Have you
> mise: Update to 2025.4.8

- java/spring-boot-cli/Portfile
Update to Spring Boot 3.4.5.
Have you
> spring-boot-cli: update to 3.4.5

- devel/cutter-rizin/Portfile
- devel/cutter-rizin/files/patch-3395_PySide_6.8.diff
> cutter-rizin: use qt6, enable python support

- devel/libnewt/Portfile
- Add support for python 3.13 with new subport `py313-libnewt`
- Drop support for EOL python 3.8 in subport `py38-libnewt`
- macOS 14.7.5 23H527 arm64
- macOS 10.15.7 19H2026 x86_64
Have you
=> Not applicable
> devel/libnewt: Add support for python 3.13

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.11.7
Have you
> ruff: Update to 0.11.7

- textproc/ocrmypdf/Portfile
ocrmypdf: update to 16.10.1
Have you
> ocrmypdf: update to 16.10.1

- sysutils/mise/Portfile
mise: Update to 2025.4.9
Have you
> mise: Update to 2025.4.9

- ruby/ruby-build/Portfile
ruby-build: Update to 20250424
Have you
> ruby-build: Update to 20250424

- sysutils/starship/Portfile
Update to Starship 1.23.0.
Have you
> starship: update to 1.23.0

- devel/rizin/Portfile
Use MP xxhash, drop usage of MP tree-sitter
macOS x.y
Have you
> rizin: update to 0.8.0

- net/gallery-dl/Portfile
gallery-dl: update to 1.29.5
Have you
> gallery-dl: update to 1.29.5

- sysutils/lf/Portfile
Update `lf` to its latest released version, 35
Have you
> lf: Update to 35

- devel/dagger/Portfile
Update to the latest version
Have you
> dagger: update to 0.18.5

- security/gitleaks/Portfile
gitleaks: Update to 8.25.0
Have you
> gitleaks: Update to 8.25.0

- archivers/unshield/Portfile
Update unshield to v.1.6.2
Have you
> unshield: update to 1.6.2

- _resources/port1.0/group/crossgcc-1.0.tcl
- cross/i686-w64-mingw32-gcc/Portfile
- cross/x86_64-w64-mingw32-gcc/Portfile
> *-w64-mingw32-gcc: Update to 15.1.0

- lang/pascal-p5/Portfile
pascal-p5: reenable ppc build
(According to barracuda156 it builds on ppc)
Have you
> pascal-p5: reenable ppc build

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 520.0.0.
Have you
> google-cloud-sdk: update to 520.0.0

- sysutils/netdata/Portfile
https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/291603/steps/install-port/logs/stdio
https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/301725/steps/install-port/logs/stdio
Have you
> netdata: fix build on macOS 10.12

- devel/uv/Portfile
Update `uv` to its latest released verison, 0.7.1. This port would originally update to 0.7.0, but this new version provides a necessary bugfix, per [uv's release notes](https://github.com/astral-sh/uv/releases/tag/0.7.1).
Have you
> uv: Update to 0.7.1

- ruby/ruby-build/Portfile
ruby-build: Update to 20250430
Have you
> ruby-build: Update to 20250430

- textproc/krep/Portfile
https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/306498/steps/install-port/logs/stdio
Have you
> krep: blacklist clang < 700 for stdatomic.h

- security/libressl-devel/Portfile
- security/libressl-devel/files/openssldir-cert.pem.patch
- security/libressl/Portfile
I can't actually test this due to heavy linking to OpenSSL on my system - just pick the changes made in https://github.com/macports/macports-ports/commit/ef12ddfb7ff8935585d9f95b4a923d694ac6498b.
Also solves the trouble with this buildbot: https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/291662/steps/install-port/logs/stdio
Have you
> libressl-devel: update to 4.1.0

- devel/tig/Portfile
- Also fixed missing dependency: pkgconfig
macOS 15.4.1
Command Line Tools 16.3.0
Have you
> tig: Update to 2.5.12

- net/youtube-dl/Portfile
yt-dlp: updated to 2025-04-30
Have you
> yt-dlp: updated to 2025-04-30

- devel/codemod/Portfile
> codemod: switch to use python3.13

- science/esmf/Portfile
* Add compiler.cxx_standard and thread_local_storage to fix builds for 10.8-10.10.  Tentative fix, not tested yet.
* Remove known_fail for older OS versions <= 10.7, re-test and enable new work.
* Build fixes only.  No rev bump needed.
Needs testing for 10.8-10.0, and older.  Waiting for buildbots on this, after merge.
Have you
> esmf: Fix builds for 10.8-10.10

- _resources/port1.0/group/crossgcc-1.0.tcl
A required build dep for gcc, yet somehow it managed to build until recently?
The missing dep is the reason for https://github.com/macports/macports-ports/commit/6db39daae92b9e442aba7649b9ef8811cfda6e43 failing to on most versions of macOS
Once merged I'd like to request the buildbots try to build `i686-w64-mingw32-gcc `& `x86_64-w64-mingw32-gcc` again for affected macOS versions.
> crossgcc: add build dep texinfo

- math/scalapack/Portfile
scalapack: fix duplicate rpaths warning/error
Fixes trac issue [#72299](https://trac.macports.org/ticket/72299)
Have you
> scalapack: fix duplicate rpaths warning/error

- x11/mesa/Portfile
- x11/mesa/files/patch-missing-mach-init-include.patch
The build failed on Tiger due to a missing include, see upstream MR for details:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/34718
Fixes https://trac.macports.org/ticket/72409
macOS x.y
Have you
> mesa: fix build on Tiger

- sysutils/mise/Portfile
mise: Update to 2025.5.0
Have you
> mise: Update to 2025.5.0

- devel/gitlab-runner/Portfile
- Simple bump to latest release 17.11.0
- macOS 14.7.5 23H527 arm64
- macOS 13.7.5 22H527 x86_64
Have you
> gitlab-runner: update version to 17.11.0

- net/gallery-dl/Portfile
gallery-dl: update to 1.29.6
Have you
> gallery-dl: update to 1.29.6

- devel/boost181/Portfile
- devel/boost187/Portfile
> boost18{1,7}: add and default to python313

- python/py-awscli2/Portfile
- python/py-awscli2/files/patch-requirements.diff
- python/py-awscrt/Portfile
- python/py-prompt_toolkit/Portfile
- python/py-prompt_toolkit/files/patch-importlib-metadata.diff
Patching prompt_toolkit in this way gets awscli2 working for now.
Have you
> py-awscli2: update to 2.27.7

- _resources/port1.0/group/crossgcc-1.0.tcl
Looks like the macOS shipped version of `texinfo` is just too old below macOS 13 so always install MacPorts version.
> crossgcc: always install texinfo

- emulators/wine-devel/Portfile
> wine-devel,wine-staging: Update to 10.7

- devel/ccache/Portfile
> ccache: update to 4.11.3

- sysutils/mise/Portfile
mise: Update to 2025.5.1
Have you
> mise: Update to 2025.5.1

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 521.0.0.
Have you
> google-cloud-sdk: update to 521.0.0

- security/pinact/Portfile
pinact: Update to 3.1.0-0
Have you
> pinact: Update to 3.1.0-0

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.31.0
Have you
> gitu: Update to 0.31.0

- java/openjdk25-zulu/Portfile
Update to Azul Zulu 25.0.33.
Have you
> openjdk25-zulu: update to 25.0.33

- devel/skaffold/Portfile
Update to Skaffold 2.16.0.
Have you
> skaffold: update to 2.16.0

- graphics/libpng/Portfile
* remove the abandoned mirror from master_sites (no updates since 2019)
Have you
> libpng: update to 1.6.48

- science/iverilog/Portfile
- science/iverilog/files/patch-fix-headers.diff
* fix build on macOS <10.7
Have you
> iverilog: fix implicit declaration error

- print/ghostscript/Portfile
Simple upgrade to upstream version 10.05.1
Have you
> ghostscript: update to 10.05.1

- science/esmf/Portfile
- science/esmf/files/patch.FieldEmpty_cppF90.diff
* Fixes "error: missing terminating ' character".
* This is actually a preprocessor bug that breaks only in Clang 11 and other early Clang versions.
* Clang CPP does not correctly handle fortran comment lines containing unbalanced quote characters such as ('), ("), etc.
* Upstream fix after ESMF version 8.8.1 is pending.
* Upstream details: https://github.com/orgs/esmf-org/discussions/400
* Build fixes only, no rev bump is needed.
CI only.  MacOS 13, 14, 15 only.
* Waiting on merge to retest 10.6 builds.
* Only comment lines in fortran code were changed, so testing is minimal.
Have you
CC:  @barracuda156
> esmf: Fix builds for 10.6

- net/tlrc/Portfile
Update `tlrc` to its latest released version, 1.11.1
Have you
> tlrc: Update to 1.11.1

- java/openjdk17-openj9/Portfile
Update to IBM Semeru 17.0.15.
Have you
> openjdk17-openj9: update to 17.0.15

- java/openjdk11-openj9/Portfile
Update to IBM Semeru 11.0.27.
Have you
> openjdk11-openj9: update to 11.0.27

- java/openjdk8-openj9/Portfile
Update to IBM Semeru 8u452.
Have you
> openjdk8-openj9: update to 8u452

- ruby/ruby-build/Portfile
ruby-build: Update to 20250507
Have you
> ruby-build: Update to 20250507

- sysutils/mise/Portfile
mise: Update to 2025.5.2
Have you
> mise: Update to 2025.5.2

- security/zizmor/Portfile
zizmor: Update to 1.7.0
Have you
> zizmor: Update to 1.7.0

- gis/JOSM/Portfile
> josm: update to 19396

- sysutils/yabai/Portfile
> yabai: update to 7.1.14

- sysutils/mise/Portfile
mise: Update to 2025.5.3
Have you
> mise: Update to 2025.5.3

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.78.0

- emulators/qemu/Portfile
- Bump version to 10.0.0
- Closes: https://trac.macports.org/ticket/72413
- Simplify definition of default `py_branch`  and `py_version`
- macOS 14.7.5 23H527 arm64
Have you
> qemu: update to 10.0.0

- textproc/pdfjam/Portfile
Update to pdfjam 4.2.
Have you
> pdfjam: update to 4.2

- devel/nlohmann-json/Portfile
* Update 3.11.3 --> 3.12.0.
* Obtain bug fixes.
macOS 14.6.1
Xcode 16.2
Command Line Tools 16.2.0
SDK 15.2
Have you
> nlohmann-json: Update to 3.12.0

- graphics/osxphotos/Portfile
Update to osxphotos 0.70.0.
Have you
> osxphotos: update to 0.70.0

- net/miniflux/Portfile
> miniflux: update to 2.2.8

- net/newsraft/Portfile
https://codeberg.org/newsraft/newsraft/releases/tag/newsraft-0.30
Xcode 14.2
Have you
> newsraft: update to 0.30

- gis/GPXSee/Portfile
> GPXSee: update to 13.42

- sysutils/tenv/Portfile
> tenv: update to 4.6.2

- net/telescope/Portfile
[Changelog](https://github.com/omar-polo/telescope/releases)
Xcode 14.2
Have you
> telescope: update to 0.11

- sysutils/chezmoi/Portfile
chezmoi: Update to 2.62.4
Have you
> chezmoi: Update to 2.62.4

- net/et/Portfile
> et: update to 6.2.9

- python/py-autopage/Portfile
- python/py-cinderclient/Portfile
- python/py-cliff/Portfile
- python/py-cmd2/Portfile
- python/py-debtcollector/Portfile
- python/py-dogpile-cache/Portfile
- python/py-iso8601/Portfile
- python/py-jsonpatch/Portfile
- python/py-keystoneauth1/Portfile
- python/py-keystoneclient/Portfile
- python/py-novaclient/Portfile
- python/py-openstackclient/Portfile
- python/py-openstacksdk/Portfile
- python/py-os-service-types/Portfile
- python/py-osc-lib/Portfile
- python/py-oslo-config/Portfile
- python/py-oslo-i18n/Portfile
- python/py-oslo-serialization/Portfile
- python/py-oslo-utils/Portfile
- python/py-requestsexceptions/Portfile
- python/py-stevedore/Portfile
Update py-openstackclient to 8.0.0 and its dependencies to up-to-date versions (incl. non-OpenStack packages py-cmd2, py-dogpile-cache, py-iso8601) and enable them to build under Python <= 3.13.
Xcode 9.1 9B55
Have you
> py-openstackclient: update to 8.0.0; bump dependencies

- devel/Bear/Portfile
> Bear: update to 3.1.6, update dependencies

- gis/imposm/Portfile
https://github.com/omniscale/imposm3/releases/tag/v0.14.2
Xcode 14.2
Have you
> imposm: update to 0.14.2

- java/openjdk21-jetbrains/Portfile
Update to JetBrains Runtime 21.0.7-b982.16.
Have you
> openjdk21-jetbrains: update to 21.0.7-b982.16

- devel/dagger/Portfile
Update to the current version.
Have you
> dagger: update to 0.18.6

- graphics/virglrenderer/Portfile
libvirglrenderer.1.dylib fails when it is installed from a binary archive compiled on the buildserver against libepoxy +x11, but the user has libepoxy +quartz installed:
```
Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: _epoxy_glXChooseFBConfig
Referenced from: <44D61F46-2561-3257-886E-71513200EEFC> /opt/local/lib/libvirglrenderer.1.dylib
Expected in:     <789F52DB-263C-319B-B70E-560271F22A8F> /opt/local/lib/libepoxy.0.dylib
```
Rebuilding virglrenderer locally fixes this, but we should prevent the use of the binary archive in this situation to avoid breakage on a user's system.
Introduce empty `+x11` and `+quartz` variants and automatically switch the default variant based on the one chosen for libepoxy. …
> virglrenderer: Avoid binary when libepoxy is +quartz

- net/openssh/Portfile
* closes: https://trac.macports.org/ticket/72317
Have you
> openssh: update to 10.0p2

- security/pinact/Portfile
pinact: Update to 3.1.1
Have you
> pinact: Update to 3.1.1

- security/gitleaks/Portfile
gitleaks: Update to 8.26.0
Have you
> gitleaks: Update to 8.26.0

- devel/protozero/Portfile
> protozero: update to 1.8.0

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 522.0.0.
Have you
> google-cloud-sdk: update to 522.0.0

- net/mosh/Portfile
Adds compilation flags to:
- Avoid overlinking against abseil
- Use C++17 (`gnu++17`)
- Install bash completions without the need for a `post-destroot` block
The only critical change is the second one mentioned above. This is necessary for the port to build successfully after `protobuf3-cpp` gets updated (#28321).
Have you
> mosh: minor enhancements

- mail/astroid/Portfile
> astroid: update to 0.17

- sysutils/jc/Portfile
https://github.com/kellyjonbrazil/jc/releases/tag/v1.25.5
Xcode 14.2
Have you
> jc: update to 1.25.5

- cross/i686-w64-mingw32-gcc/Portfile
- cross/x86_64-w64-mingw32-gcc/Portfile
> *-w64-mingw32-gcc: rev bump

- fuse/archivemount/Portfile
add fs_link variant
macOS x.y
Have you
> archivemount: fix building against new fuse3

- emulators/qemu/Portfile
- Since [macfuse was bumped from 4.8.3 to 4.9.1](https://github.com/macports/macports-ports/commit/fc4bb96dd6ef5bb8b056391a9997db3f7e84ea87) building `qemu` with fuse support (enabled by auto-detection of fuse headers) fails compilation (some header mismatch). The fuse support only enables relative less used functionality to 'export block device using fuse loopback driver'.
- Add new variant `fuse`, disabled by default
- Workaround only, compilation bug still exists.
macOS 14.7.5 23H527 arm64
Have you
> qemu: Fix compilation when macfuse is installed

- sysutils/mise/Portfile
mise: Update to 2025.5.4
Have you
> mise: Update to 2025.5.4

- gis/libosmium/Portfile
> libosmium: update to 2.22.0

- python/py-klein/Portfile
> py-klein: update to 24.8.0

- net/paho.mqtt.cpp/Portfile
https://github.com/eclipse-paho/paho.mqtt.cpp/releases/tag/v1.5.3
Xcode 14.2
Have you
> paho.mqtt.cpp: update to 1.5.3

- databases/dbeaver-community/Portfile
The all_arches variant requests distfiles for both aarch64 and x86_64, regardless of the actual build arch. This allows commands like `port bump` to function correctly.
Have you
> dbeaver-community: Update to 2024.2.3 and add `all_arches` variant.

- dotnet/aspnetcore-runtime-2.1/Portfile
- dotnet/aspnetcore-runtime-3.1/Portfile
- dotnet/aspnetcore-runtime-6/Portfile
- dotnet/aspnetcore-runtime-7/Portfile
- dotnet/aspnetcore-runtime-8/Portfile
- dotnet/aspnetcore-runtime-devel/Portfile
- dotnet/dotnet-cli/Portfile
- dotnet/dotnet-runtime-2.1/Portfile
- dotnet/dotnet-runtime-3.1/Portfile
- dotnet/dotnet-runtime-6/Portfile
- dotnet/dotnet-runtime-7/Portfile
- dotnet/dotnet-runtime-8/Portfile
- dotnet/dotnet-runtime-devel/Portfile
- dotnet/dotnet-sdk-2.1/Portfile
- dotnet/dotnet-sdk-3.1/Portfile
- dotnet/dotnet-sdk-6/Portfile
- dotnet/dotnet-sdk-7/Portfile
- dotnet/dotnet-sdk-8/Portfile
- dotnet/dotnet-sdk-devel/Portfile
`dotnetcli.azureedge.net` may fail soon.
Related: https://github.com/dotnet/core/issues/9671
> Critical: Update dotnetcli domain

- net/calendar-contacts-server/Portfile
- net/calendar-contacts-server/files/calendarserver.plist
- net/calendar-contacts-server/files/patch-build_python_venv.diff
> calendar-contacts-server: Fix build; Migrate to postgresql17; Deprecate APNS

- python/py-findpython/Portfile
New dependency for poetry
Have you
> py-findpython: new port

- sysutils/atuin/Portfile
atuin: update to 18.6.1
https://github.com/atuinsh/atuin/releases
Have you
> atuin: update to 18.6.1

- ruby/ruby-build/Portfile
ruby-build: Update to 20250516
Have you
> ruby-build: Update to 20250516

- emulators/dosbox-x/Portfile
Update dosxbox to version 2025.05.03
macOS 13.7.5 22H527 arm64
Have you
> dosbox-x: update to 2025.05.03

- irc/weechat/Portfile
weechat: update to 4.6.3
Have you
> weechat: update to 4.6.3

- sysutils/simplotask/Portfile
> simplotask: update to 1.17.0

- sysutils/mise/Portfile
mise: Update to 2025.5.6
Have you
> mise: Update to 2025.5.6

- _resources/port1.0/group/fortran-1.0.tcl
- devel/fpm/Portfile
- devel/fpm/files/patch-install.diff
The update fixes https://trac.macports.org/ticket/71644
Have you
> fpm: update to 0.11.0 and fix 71644

- devel/got/Portfile
* add FreeBSD mirror to master_sites
Closes: https://trac.macports.org/ticket/72492
Have you
> got: update to 0.112

- fuse/macfuse/Portfile
> macfuse: add fs_link variant

- mail/mpack/Portfile
- mail/mpack/files/cmulocal-bsd_sockets.m4.patch
- mail/mpack/files/configure.in.patch
`configure` was failing as its tests appear to be pre C99 requiring implicit int.
`Makefile.am` failed to build due to a local variable being null.
Have you
> mpack: fix configure and build failures

- www/catgirl-downloader/Portfile
> catgirl-downloader: update to 0.2.8

- gis/mod_tile/Portfile
- gis/mod_tile/files/README_MacPorts.md
- gis/mod_tile/files/osm_setup_db.sh
- gis/mod_tile/files/osmosis-db_replag.diff
- Update `proj7` dependency to `proj9`
- Updated README on where to obtain Noto fonts and updating `mapnik.xml`
- Updated notes in `osm_setup_db.sh` script to refer to PostgreSQL 16
- Added executing `functions.sql` to `osm_setup_db.sh` script
- Fix formatting time difference message in log output `osmosis-db_replag.diff`
Have you
> mod_tile: update to 0.8.1

- devel/mercurial/Portfile
- devel/mercurial/files/allow_rust.diff
- devel/mercurial/files/hg.diff
- devel/mercurial/files/makefile.diff
- devel/mercurial/files/rust_darwin.diff
- devel/mercurial/files/setup_py.diff
This reinstates the experimental Rust extensions as a separate subport, configures Mercurial to optionally load them, and reintroduces the manual pages, which still require GNU Make to build.
Fixes: https://trac.macports.org/ticket/72455
macOS x.y
Have you
> mercurial: fix issues in port

- sysutils/mise/Portfile
mise: Update to 2025.5.8
Have you
> mise: Update to 2025.5.8

- security/pinact/Portfile
pinact: Update to 3.1.2
Have you
> pinact: Update to 3.1.2

- gis/openstreetmap-carto/Portfile
Add and default to postgresql17
Have you
> openstreetmap-carto: update to 5.9.0

- python/py-incremental/Portfile
- python/py-twisted/Portfile
Github action currently failing due to py38-twisted missing py38-bcrypt, which has been removed. This is not related to any changed I made. Currently only py38-txgithub still uses py38-twisted.
Have you
> py-incremental: update to 24.7.2

- databases/postgresql13-doc/Portfile
- databases/postgresql13-server/Portfile
- databases/postgresql13/Portfile
- databases/postgresql14-doc/Portfile
- databases/postgresql14-server/Portfile
- databases/postgresql14/Portfile
- databases/postgresql15-doc/Portfile
- databases/postgresql15-server/Portfile
- databases/postgresql15/Portfile
- databases/postgresql16-server/Portfile
- databases/postgresql16/Portfile
- databases/postgresql17-server/Portfile
- databases/postgresql17/Portfile
```
Model Identifier: MacPro5,1                 Model Identifier: Macmini6,1
macOS 14.7.5 23H527 x86_64                  macOS 10.15.7 19H2026 x86_64
Xcode 16.2 16C5032a                         Xcode 12.4 12D4e
Command Line Tools 16.2.0.0.1.1733547573    Command Line Tools 12.4.0.0.1.1610135815
```
```
port -cuN -f uninstall postgresql*
for pgsql in {13..17}; do port clean --all postgresql${pgsql}; done
for pgsql in {13..17}; do port -cuN -d install postgresql${pgsql}; done
for pgsql in {13..17}; do port -cuN -d install postgresql${pgsql}-server; done
for pgsql in {13..17}; do port -cuN -d upgrade --enforce-variants postgresql${pgsql} +python3; done
port install -cuN llvm-20
for pgsql in {13..17}; do port -cuN -d upgrade --enforce-variants postgresql${pgsql} +llvm -python3; done
for pgsql …
```
> Postgresql{13..17}: update to newest versions

- lang/cppman/Portfile
Maintainer update. Migrate to tracking default python flavor.
> cppman: 0.5.9

- security/zizmor/Portfile
Upgrade to Zizmor 1.8.0; also change the repo origin.
macOS 15.5 24F74 arm64 Xcode 16.3 16E140
Have you
same change?
> zizmor: Upgrade to 1.8.0

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 523.0.0.
Have you
> google-cloud-sdk: update to 523.0.0

- science/cdo/Portfile
Simple update to upstream version 2.5.2
Have you
> cdo: update to 2.5.2

- devel/n/Portfile
> n: update to 10.2

- sysutils/cdargs/Portfile
* Add missing rev bump after PR #28479.
Have you
> cdargs: Add missing rev bump

- sysutils/mise/Portfile
mise: Update to 2025.5.9
Have you
> mise: Update to 2025.5.9

- net/wireguard-tools/Portfile
wireguard-tools: update to 1.0.20250521
* update maintainer email
Have you
> wireguard-tools: update to 1.0.20250521

- www/chromedriver/Portfile
* Update to version 136.0.7103.113
* Add `+chrome_app` variant default that included `Google Chrome for Testing.app` designed to be a fixed-version Chrome browser to be used with `chromedriver`
macOS x.y
Have you
> chromedriver: Update to version 136.0.7103.113

- sysutils/lima/Portfile
Upgrade to lima 1.1.0. This introduces `+additional_guestagents`, as recommended in the ["Hint for package maintainers"][1] link, where native guest agents are built and installed by default, but additional architecture guest agents are not.
For macOS < 14, this variant is enabled by default; with macOS >= 14 it is disabled by default. **This may be considered a breaking change.**
This is similar to the change where we disabled the installation of `qemu` by default with Lima 1.0, but I am happy to change the configuration so that the guest agents are built by default, but I would also remove `depends_run-append port:qemu` from the variant (and add it back to the macOS < 14 option).
If it's possible to have the build bots build both the default and `+additional_guestagents` variants, this …
> lima: Update to 1.1.0

- devel/openssl3/Portfile
- devel/openssl3/files/0001-apps-x509.c-Fix-the-addreject-option-adding-trust-in.patch
No revbump of dependents, since this is a very minor CVE fix only and the OpenSSL version stays the same.
Advisory is at https://openssl-library.org/news/secadv/20241016.txt.
Have you
> openssl3: Fix CVE-2025-4575

- devel/quickjs/Portfile
Updates quickjs to 2025-04-26 and quickjs-devel to 2025-05-20
Have you
> Update quickjs to 2025-04-26

- sysutils/chezmoi/Portfile
chezmoi: Update to 2.62.5
Have you
> chezmoi: Update to 2.62.5

- sysutils/mise/Portfile
mise: Update to 2025.5.10
Have you
> mise: Update to 2025.5.10

- sysutils/lima/Portfile
- sysutils/lima/files/patch-Makefile.diff
Upgrade lima to 1.1.1
macOS 15.5 24F74 arm64 Xcode 16.3 16E140
Have you
same change?
[variants](https://trac.macports.org/wiki/Variants) haven't been broken?
> lima: Update to 1.1.1

- devel/dagger/Portfile
Update to latest version
Have you
> dagger: update to 0.18.8

- gnome/gstreamer1-gst-plugins-base/Portfile
graphene doesn't support arm64 & x86_64 universal builds
This change would make it possible to install for arm64 & x86_64 +universal, that’s a requirement for installing the `wine-*` ports for reference https://trac.macports.org/ticket/72005
macOS x.y
> gstreamer1-gst-plugins-base: Disable graphene for arm64 & x86_64

- devel/libayatana-indicator/Portfile
- devel/libayatana-indicator/files/0001-Remove-unnecessary-gio-gdesktopappinfo.h-include.patch
The `gdesktopappinfo.h` header does not exist in glib2 +quartz, but is also not needed by libayatana-indicator. See also https://github.com/AyatanaIndicators/libayatana-indicator/pull/77
Have you
> libayatana-indicator: Fix build with glib2 +quartz

- comms/minicom/Portfile
This was suggested in https://trac.macports.org/ticket/72226 , since kermit is currently broken (see https://trac.macports.org/ticket/71517 for that issue)
Have you
> minicom: Move kermit dep to an optional variant

- sysutils/lima/Portfile
My update process failed me and the variants are new enough that I had missed the variant reversion. (This appears to be caused by the fact that I had not run `port sync` before using `seaport clip`; this is now part of my update steps.)
Have you
same change?
> lima: Restore build variants

- net/youtube-dl/Portfile
yt-dlp: update to 20250522
Have you
> yt-dlp: update to 20250522

- net/gallery-dl/Portfile
gallery-dl: update to 1.29.7
Have you
> gallery-dl: update to 1.29.7

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.605
Have you
> ipsw: Update to 3.1.605

- security/i2pd/Portfile
> i2pd: use boost 1.81

- net/trojan/Portfile
https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/308119/steps/install-port/logs/stdio
Have you
> trojan: set compiler.cxx_standard 2011, blacklist clang < 700

- java/spring-boot-cli/Portfile
Update to Spring Boot 3.5.0.
Have you
> spring-boot-cli: update to 3.5.0

- net/Legcord/Portfile
- net/Legcord/files/package-version-bump.diff
- Updates legcord to v1.1.5
- Upstream didn't bump the package.json version number, patch will fix that. Otherwise, legcord will issue a warning at startup that there's a new version, despite being on the latest version.
[as previously noted](https://github.com/macports/macports-ports/pull/28335), github CI will fail, but it will build just fine on MacPorts buildbots, cf. https://build.macports.org/builders/ports-14_arm64-watcher/builds/21076
Have you
> legcord: updated to 1.1.5

- java/openjdk25-zulu/Portfile
Update to Azul Zulu 25.0.37.
Have you
> openjdk25-zulu: update to 25.0.37

- lang/kotlin/Portfile
Update to Kotlin 2.1.21.
Have you
> kotlin: update to 2.1.21

- sysutils/mise/Portfile
mise: Update to 2025.5.15
Have you
> mise: Update to 2025.5.15

- _resources/port1.0/group/legacysupport-1.1.tcl
* Housekeeping.  Remove temporary options block, as requested.
* The related base bug was resolved with earlier commit:
* https://github.com/macports/macports-base/commit/a86f95c5ab86ee52c8fec2271e005591179731de
Have you
> legacysupport-1.1.tcl: Remove temporary bug fix

- graphics/optipng/Portfile
> optipng: update to 7.9.1

- R/R-gert/Portfile
- R/R-git2r/Portfile
- devel/cargo-c/Portfile
- devel/cargo/Portfile
- devel/cocogitto/Portfile
- devel/committed/Portfile
- devel/dura/Portfile
- devel/git-branchless/Portfile
- devel/gitui/Portfile
- devel/gitweb/Portfile
- devel/libgit2/Portfile
- devel/onefetch/Portfile
- devel/stgit/Portfile
- editors/lapce/Portfile
- fortran/fortran-git/Portfile
- gnome/gitg/Portfile
- gnome/libgit2-glib/Portfile
- lang/rust/Portfile
- python/py-pygit2/Portfile
- science/gnuastro/Portfile
- sysutils/broot/Portfile
- sysutils/caps-log/Portfile
- sysutils/eza/Portfile
- sysutils/starship/Portfile
- textproc/bat/Portfile
- textproc/git-delta/Portfile
- www/stagit/Portfile
* libgit2: update to 1.9.0
* py-pygit2: update to 1.18.0
* gitg: add py312, py313; drop py38
* libgit2 dependents: rev-bump
CC: https://github.com/macports/macports-ports/pull/28554
> libgit2: update to 1.9.0

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 524.0.0.
Have you
> google-cloud-sdk: update to 524.0.0

- devel/git-absorb/Portfile
> git-absorb: Update to version 0.8.0

- security/nsc/Portfile
New port submission for nsc v2.11.0 - NATS Security CLI for managing NATS account and user security configurations.
nsc is the official command-line tool for creating and managing NATS Operators, Accounts, and Users. It handles permissions, generates activation tokens, and manages the complete NATS security ecosystem.
Key features:
- Create/edit Operators, Accounts, and Users
- Manage permissions and access controls  
- Generate activation tokens
- NATS security configuration management
Xcode 16.4
Have you
> nsc: new port at 2.11.0

- sysutils/mise/Portfile
mise: Update to 2025.5.17
Have you
> mise: Update to 2025.5.17

- science/pnetcdf/Portfile
* Blacklist early compiler versions.
* Fixes error: invalid instruction mnemonic 'cvtsi2ssl' on 10.7.
* Also fix livecheck.
* CI only.  OS 13, 14, 15 only.
* Waiting for merge to check 10.7 and other early OS versions.
Have you
> pnetcdf: Fix 10.7 build; fix livecheck

- devel/buf/Portfile
buf update from v1.50.1 to v1.54.0. Includes binary size optimization using Go ldflags to reduce binary size by 31% (from 61MB to 42MB).
Notable changes in v1.54.0:
- Local bufplugins support for improved development workflow
- RISC-V binaries now available
- Improved `buf lint` and `buf config migrate` functionality  
- Build optimization with `-ldflags="-s -w"` for smaller binaries
Xcode 16.4
Have you
> buf: Update to 1.54.0

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.32.0
Have you
> gitu: Update to 0.32.0

- devel/natscli/Portfile
natscli update from v0.0.35 to v0.2.3. Includes migration away from deprecated GitHub tarball_from tarball to use golang PortGroup default 'archive' method.
Notable changes:
- Significant version jump with new features and fixes
- Simplified port configuration by removing explicit tarball_from setting
- Maintained golang PortGroup offline_build no for dependency resolution
Xcode 16.4
Have you
> natscli: update to 0.2.3

- lang/clojure/Portfile
> clojure: update to 1.12.1.1543

- devel/libusbmuxd/Portfile
Update `libusbmuxd` to its latest released version, 2.1.1
Have you
> libusbmuxd: Update to 2.1.1

- devel/uv/Portfile
Update `uv` to its latest released version, 0.7.11. 0.7.10 was skipped due to a small fix pushed regarding a crucial feature, per [astral-sh/uv#13835](https://github.com/astral-sh/uv/pull/13835). Additionally, ``--no-default-features`` was removed per [homebrew/homebrew-core#222211](https://github.com/Homebrew/homebrew-core/pull/222211)
Have you
> uv: Update to 0.7.11

- java/maven3/Portfile
Update to Apache Maven 3.9.10.
Have you
> maven3: update to 3.9.10

- fuse/archivemount/Portfile
Update `archivemount` to its latest released version, 1b
Have you
> archivemount: Update to 1b

- lang/clojure/Portfile
> clojure: update to 1.12.1.1550

- devel/got/Portfile
> got: update to 0.113

- devel/google-cloud-sdk/Portfile
Make sure that the installation doesn't attempt to install its own Python (even though `--install-python false` is passed to it). This is a workaround for https://trac.macports.org/ticket/72553.
Have you
> google-cloud-sdk: workaround for unwanted Python installation attempt

- python/py-h5py/Portfile
- python/py-h5py/files/patch-oldest-supported-numpy.diff
Disabled new npystrings module until NumPy 2 in ports.
> py-h5py: 3.14.0

- sysutils/chezmoi/Portfile
chezmoi: Update to 2.62.6
Have you
> chezmoi: Update to 2.62.6

- python/py-whenever/Portfile
New port for whenever.
Have you
> py-whenever: new submission

- gis/JOSM/Portfile
> josm: update to 19412

- security/gitleaks/Portfile
gitleaks: Update to 8.27.1
Have you
> gitleaks: Update to 8.27.1

- devel/legacy-support/Portfile
- Fixes performance issue in sleep-affected clock functions.
- Disables broken sleep-time accounting on ppc64.
Earlier notable -devel changes since v1.4.0:
- Complete rewrite of clock functions, including:
- CLOCK_MONOTONIC is no longer non-monotonic
- Mach-based clocks are no longer horribly inaccurate on PPC
- High-precision thread time is now reported on 10.10+
- "Approximate" clocks work as intended on 10.10+
- Fallbacks for missing mach_time clocks are provided
- A corner case in CLOCK_THREAD_CPUTIME_ID is fixed
- Bad clock IDs no longer fail to set errno
- Most functions are now faster.
- Two packet timestamp bugs are fixed:
- 10.5 x86_64 no longer supplies an unexpected timestamp format
- Timestamps now have correct endianness under Rosetta
- The …
> legacy-support-devel: Update to latest master - v20250608.

- sysutils/minikube/Portfile
Update of minikube from 1.35 to 1.36
Update
Have you
Remark on variants: To my understanding variant "hyperkit" cannot be tested on arm64
> minikube: update to 1.36

- devel/dagger/Portfile
> dagger: update to 0.18.9

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.611. A common feature received a hotfix in this release, [per the release notes](https://github.com/blacktop/ipsw/releases/tag/v3.1.611)
Have you
> ipsw: Update to 3.1.611

- devel/jsonnet-language-server/Portfile
Update jsonnet-language-server from version 0.10.0 to 0.16.0.
This update removes the vendored dependencies approach and switches to online dependency resolution to handle the changed dependency tree in the newer version.
Have you
> jsonnet-language-server: update to 0.16.0

- sysutils/tenv/Portfile
Created with [seaport](https://seaport.rtfd.io/), the modern MacPorts portfile updater.
macOS 15.5 24F74
Have you
> tenv: update to 4.7.6

- lang/swi-prolog/Portfile
Bumped Python dependency to 3.13
macOS 13.7.6 22H625 x86_64
Have you
> swi-prolog: Bumped Python to 3.13

- print/paps/Portfile
Submitting `paps`, a command line program for converting Unicode text encoded in UTF-8 to postscript and pdf by using pango.
Xcode 12.2 12B45b
Have you
> paps: submission

- databases/postgis3/Portfile
- gis/pgrouting/Portfile
`postgis3`: update to 3.5.3, add PostgreSQL 17 subport
`pgrouting`: update to 3.8.0, add PostgreSQL 17 subport
macOS x.y
Have you
> postgis3: update to 3.5.3; pgrouting: update to 3.8.0; add pg17 subports

- sysutils/podman/Portfile
Update podman to version 5.5.1
Have you
> podman: update to 5.5.1

- sysutils/lima/Portfile
- sysutils/lima/files/patch-usrlocalsharelimago.diff
Lima contains a message for installing `lima-additional-guestagents` package when agents can't be found. This does not work for MacPorts because we have a variant (`+additional_guestagents`). Added a patch to update the message to refer to this variant instead of a package that does not exist.
Closes: https://trac.macports.org/ticket/72567
macOS 15.5 24F74 arm64  
Have you
> lima: Improve additional guest agents message

- print/paps/Portfile
This fixes the platform and license in the portfile of the recently submitted `paps` port.
Have you
> paps: fixing platform and license

- sysutils/mise/Portfile
mise: Update to 2025.6.2
Have you
> mise: Update to 2025.6.2

- java/micronaut/Portfile
Update to Micronaut Starter 4.8.3.
Have you
> micronaut: update to 4.8.3

- graphics/osxphotos/Portfile
Update to osxphotos 0.72.0.
Have you
> osxphotos: update to 0.72.0

- security/pinact/Portfile
pinact: Update to 3.3.0
Have you
> pinact: Update to 3.3.0

- math/gunits/Portfile
I inadvertently broke builds on OS X 10.7 through 10.11 in #28645.
Here is an apologetic patch.  I specifically tested on 10.8.
macOS 10.8.5 12F45 x86_64
and
Have you
(tracing still busted?  OK without `-t`)
> gunits: fix builds on legacy platforms

- devel/dagger/Portfile
> dagger: update to 0.18.10

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.33.0
Have you
> gitu: Update to 0.33.0

- www/ls-qpack/Portfile
Dug out my ancient machine just to test this on an older platform to ensure it actually works ;)
Will do a follow-up for `py3*-pylsqpack` once it is updated upstream (since it is vendored there) - upstream has an open issue on whether to support shared package in `setup.py` for packagers. 
macOS 10.8.3 12D78 x86_64
Have you
> ls-qpack: update to 2.6.2

- science/nco/Portfile
Simple update to upstream version 5.3.4
Have you
> nco: update to 5.3.4

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 527.0.0.
Have you
> google-cloud-sdk: update to 527.0.0

- graphics/osxphotos/Portfile
Update to osxphotos 0.72.1.
Have you
> osxphotos: update to 0.72.1

- science/hamlib/Portfile
Update hamlib to v4.6.3
Closes: https://trac.macports.org/ticket/72614
This is a new attempt to get the pr working since something weird happened with 
https://github.com/macports/macports-ports/pull/28704
Have you
> hamlib: Update to v4.6.3

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.5.3.
Have you
> spring-boot-cli: update to 3.5.3

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.616
Have you
> ipsw: Update to 3.1.616

- science/xnec2c/Portfile
The app requires a C11+ compiler. 
Closes: https://trac.macports.org/ticket/72617
Have you
> xnec2c: set compiler.c_standard 2011

- devel/allegro5/Portfile
Update devel/allegro5 port to the current latest version and take maintainership, since it is unmaintained.
Current 5.2.7 version contains plethora of bugs, like e.g. this one https://github.com/liballeg/allegro5/issues/1643.
macOS 13.7.6 22H625 x86_64
Have you
> allegro5: update to 5.2.10.1; adopt

- sysutils/chrony/Portfile
> chrony: update to 4.7

- gis/h3/Portfile
> h3: update to 4.3.0

- devel/pkgconf/Portfile
Update `pkgconf` to its latest released version, 2.5.0
Have you
> pkgconf: Update to 2.5.0

- java/openjdk25-zulu/Portfile
Update to Azul Zulu 25.0.39.
Have you
> openjdk25-zulu: update to 25.0.39

- devel/skaffold/Portfile
Update to Skaffold 2.16.1.
Have you
> skaffold: update to 2.16.1

- databases/postgresql16/Portfile
* Restore previous certificate fix which was accidentally reverted here:
* https://github.com/macports/macports-ports/commit/edac8ddd08f6e8f18e0e5f738442eaa8604b6111
* Also see https://trac.macports.org/ticket/72215
* Rev bump needed to clear out file conflicts.
Have you
> postgresql16: Restore previous fix for curl-ca-bundle

- devel/legacy-support/Portfile
- Fixes boottime sysctls for 64-bit <10.6
- Consequently undisables sleep offset on ppc64
A compiler selection tweak was needed for 10.4, to work around a bug recently introduced elsewhere.
TESTED:
Tested both normal and -devel versions -/+universal on 10.4-10.5 ppc, 10.4-10.5 ppc64, 10.4-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-15.x arm64.
Builds and passes all tests on all tested platforms, except that seven tests fail on 10.4 ppc64 (almost certainly long-standing bugs).
```
Mac OS X 10.4.11 8S165, ppc, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S165, ppc64, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, ppc (i386 Rosetta), Xcode 2.5 8M2558 …
```
> legacy-support-devel: Update to latest master - v20250622.

- lang/MoarVM/Portfile
- lang/MoarVM/files/patch-libuv-legacy.diff
> MoarVM: fix build on macOS 10.7-10.9 and 10.12

- math/OpenBLAS/Portfile
> OpenBLAS: update to 0.3.30

- devel/libgee/Portfile
* Update libgee 0.20.6 --> 0.20.8.
* Fixes recent broken builds due to newly occurring pointer type errors.
* Switch to new nearest approximation of a home page.  Old home page was retired.
* Remove obsolete Vala recompile trick for fixing previous errors.
macOS 15.5
Xcode 16.2
Command Line Tools 16.2.0
Have you
> libgee: Update to 0.20.8

- devel/jsonnet/Portfile
- devel/jsonnet/files/patch-Makefile.diff
Update jsonnet from 0.17.0 to 0.21.0
- Update version from 0.17.0 to 0.21.0
- Update checksums for new version
- Fix Python subport categories (categories devel python) 
- Update Python versions from {3.7 3.8 3.9} to {3.9 3.10 3.11 3.12 3.13}
- Update patch file for new Makefile structure (C++17, rapidyaml support)
macOS 15.5 24.5.0 arm64
Xcode 16.4 16.4.0.0.1.1747106510
Have you
> jsonnet: update to 0.21.0

- python/py-whenever/Portfile
Update to whenever 0.8.6.
Have you
> py-whenever: update to 0.8.6

- graphics/vtk/Portfile
* Update vtk 9.4.1 --> 9.5.0.
* Use gitlab instance.
* Switch distfile format from gz to bz2.
* Update C++ standard from 2011 to 2017, as indicated by upstream.
* Add python 3.13 to supported versions.
macOS 15.5
Xcode 16.2
Command Line Tools 16.2.0
Have you
> vtk: Update to 9.5.0

- math/OpenBLAS/Portfile
- math/OpenBLAS/files/patch-CMakeLists.txt.diff
* Copied from upstream commit after release 0.3.30.
* Closes https://trac.macports.org/ticket/72638
* Build fixes for macOS 10.6 through 10.15 (Catalina).
* No rev bump needed.  Fixes only builds that are currently broken.
Committers, please squash commits on merge.
Have you
> OpenBLAS: Build fix for "argument list too long"

- graphics/vtk/Portfile
* Legacy support:  Use Macports libcxx.
* Fixes undefined symbols for std::bad_variant_access.
* No rev bump.  Only fixes newly broken legacy builds.
* CI only.  OS 13, 14, 15 only.
* Needs testing on one of the target legacy OS versions.
* Test now, or merge and wait for builder results.
Have you
> vtk: Fix builds for 10.7-10.12

- devel/pkgconf/Portfile
Update `pkgconf` to its latest released version, 2.5.1
Have you
> pkgconf: Update to 2.5.1

- devel/volta-node/Portfile
Update `volta-node` to v2.0.2. I got some warnigns from `port lint` about `missing recommended checksum type: rmd160`, but since this was also the case in the previous Portfile, I assume it's alright.
Have you
> volta-node: update to version 2.0.2

- devel/kustomize/Portfile
Update to Kustomize 5.7.0.
Have you
> kustomize: update to 5.7.0

- graphics/libpng/Portfile
> libpng: update to 1.6.49

- archivers/unrar/Portfile
> unrar: update to 7.1.8

- sysutils/mise/Portfile
mise: Update to 2025.7.0
Have you
> mise: Update to 2025.7.0

- sysutils/netdata/Portfile
> netdata: update to 2.5.4

- devel/got/Portfile
* closes: https://trac.macports.org/ticket/72650
Have you
> got: update to 0.115

- net/youtube-dl/Portfile
yt-dlp: update to 2025.06.30
Have you
> yt-dlp: update to 2025.06.30

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 529.0.0.
Have you
> google-cloud-sdk: update to 529.0.0

- sysutils/bfs/Portfile
> bfs: update to 4.0.8

- devel/mockery/Portfile
Update mockery to version 3.5.0
Have you
> mockery: update to 3.5.0

- devel/direnv/Portfile
direnv: Update to 2.37.0
Have you
> direnv: Update to 2.37.0

- x11/auto-multiple-choice/Portfile
Update auto-multiple-choice-devel to version 1.7.0-git 20250704122834
Xcode 16.4 16F6 
MacPorts 2.10.7
Have you
> auto-multiple-choice-devel: update to version 1.7.0-git 20250704122834

- science/openEMS/Portfile
* Second rev bump, fix VTK linkage.
* The first bump was done too quickly and linked to the previous version of VTK.  My mistake in timing.
Have you
> openEMS: Rev bump for VTK-9.5.0 update

- sysutils/mise/Portfile
mise: Update to 2025.7.1
Have you
> mise: Update to 2025.7.1

- textproc/ocrmypdf/Portfile
OCRmyPDF: update to 16.10.4
Have you
> OCRmyPDF: update to 16.10.4

- sysutils/chrony/Portfile
> chrony: add legacysupport portgroup for macOS 10.6 (strnlen)

- python/py-service_identity/Portfile
> py-service_identity: pin to last working version for py27

- gis/grass/Portfile
- gis/grass7/Portfile
- gis/qgis3/Portfile
Increase revision for `pdal` dependents after PDAL update to 2.9.0 (9ecd36e).
macOS x.y
Have you
> pdal dependents: increase revision after PDAL update to 2.9.0

- graphics/libpng/Portfile
Since buildbots are offline there is no need to merge this PR immediately.
Have you
> libpng: update to 1.6.50

- java/micronaut/Portfile
Update to Micronaut Starter 4.9.1.
Have you
> micronaut: update to 4.9.1

- sysutils/mise/Portfile
mise: Update to 2025.7.3
Have you
> mise: Update to 2025.7.3

- devel/uv/Portfile
Update `uv` to its latest released version, 0.7.20
Have you
> uv: Update to 0.7.20

- security/ipsw/Portfile
Update `ipsw` to its latest released version, 3.1.621
Have you
> ipsw: Update to 3.1.621

- sysutils/g-ls/Portfile
Update `g-ls` to its latest released update, 0.31.0
Have you
> g-ls: Update to 0.31.0

- lang/nim/Portfile
Update to current version
Have you
> nim: update to 2.2.4

- multimedia/x264/Portfile
This is causing build failures:
Failed to parse file multimedia/x264/Portfile: invalid command name "livecheck.branch"
This reverts commit a9e6773b171a4ec6aafe738d9bfc35c1e2c8afb2.
**/cc** @mohd-akram 
Have you
> Revert "x264: improve livecheck"

- devel/fzy/Portfile
update fzy to version 1.1
Have you
> fzy: update to 1.1

- devel/legacy-support/Portfile
- Fixes fcntl() F_GETPATH for 10.4 ppc64
- Fixes stat() et al tv_nsec for 10.4 ppc64
- Adds missing address validation for 10.4 stat64() calls.
- Makes all tests parallelizable.
- Fixes (Apple) [f]setattrlist() bug in 10.5-10.7.
Now runs tests in parallel (-devel only until next release).
TESTED:
Tested both normal and -devel versions -/+universal on 10.4-10.5 ppc, 10.4-10.5 ppc64, 10.4-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-15.x arm64.
Builds and passes all tests on all tested platforms, except for the expected non-devel test failures on 10.4 ppc64, and a -devel test failure on 10.4 ppc64 which seems to be an indirect artifact of muniversal.
```
Mac OS X 10.4.11 8S165, ppc, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S165, ppc64, …
```
> legacy-support-devel: Update to latest master - v20250711.

- python/py-llfuse/Portfile
update to 1.5.1 adds a python 3.13 variant. This will be necessary for #28848 since there was no 3.13 variant and thus `port install borgbackup +fuse` would fail.
Have you
> py-llfuse: update to 1.5.1, add python 3.13 variant

- java/openjdk11-zulu/Portfile
Update to Azul Zulu 11.82.19.
Have you
> openjdk11-zulu: update to 11.82.19

- java/openjdk24-zulu/Portfile
Update to Azul Zulu 24.32.13.
Have you
> openjdk24-zulu: update to 24.32.13

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 530.0.0.
Have you
> google-cloud-sdk: update to 530.0.0

- java/maven3/Portfile
Update to Apache Maven 3.9.11.
Have you
> maven3: update to 3.9.11

- net/gallery-dl/Portfile
gallery-dl: update to 1.30.0
Have you
> gallery-dl: update to 1.30.0

- java/openjdk21-corretto/Portfile
Update to Amazon Corretto 21.0.8.9.1.
Have you
> openjdk21-corretto: update to 21.0.8.9.1

- java/openjdk17-corretto/Portfile
Update to Amazon Corretto 17.0.16.8.1.
Have you
> openjdk17-corretto: update to 17.0.16.8.1

- graphics/argyll/Portfile
just changed version+ checksums/size
Have you
> Update argyll to 3 .4.0

- java/openjdk11-corretto/Portfile
Update to Amazon Corretto 11.0.28.6.1.
Have you
> openjdk11-corretto: update to 11.0.28.6.1

- java/openjdk24-graalvm/Portfile
Update to GraalVM Community Edition 24.0.2.
Have you
> openjdk24-graalvm: update to 24.0.2

- java/openjdk24/Portfile
Update to OpenJDK 24.0.2.
Have you
> openjdk24: update to 24.0.2

- java/openjdk21/Portfile
Update to OpenJDK 21.0.8.
Have you
> openjdk21: update to 21.0.8

- java/jdk21-graalvm/Portfile
Update to Oracle GraalVM for JDK 21.0.8.
Have you
> jdk21-graalvm: update to 21.0.8

- devel/git-annex/Portfile
Update git-annex to 10.20250630.
Have you
> git-annex: update to 10.20250630

- python/py-msgpack/Portfile
- sysutils/borgbackup/Portfile
- sysutils/borgbackup/files/patch-accept-newer-msgpack.diff
- sysutils/borgbackup/files/patch-docs-use-sphinx_rtd_theme.diff
Update borgbackup to 1.4.1, which now supports Python 3.13, which is currently our preferred version.
Enable running borgbackup tests, since I'm adding a patch to remove the msgpack version check that keeps breaking otherwise working installations and causing churn. See the patch header of the added patchfile for an in-depth look at the situation to determine whether this check is a net benefit for MacPorts.
Change the reinplaces to fix the docs builds to use a patchfile, which is cleaner and allows us to document the rationale in the patch file header. Remove the reinplace that switches the sphinx-build executable by overriding the Makefile variable on the command line instead to fix an interrupted build, see https://trac.macports.org/ticket/72139.
Closes: …
> borgbackup: Update to 1.4.1, use Python 3.13, ignore msgpack version

- gis/JOSM/Portfile
> josm: update to 19423

- java/openjdk21-temurin/Portfile
Update to Eclipse Temurin 21.0.8.
Have you
> openjdk21-temurin: update to 21.0.8

- java/jdk21/Portfile
Update to Oracle Java SE 21.0.8.
Have you
> jdk21: update to 21.0.8

- devel/uv/Portfile
Update `ruff` to its latest released version, 0.8.0. Since 0.7.11, MacPorts' `xz` no longer shows as a dependency in the output of `otool -L`. However, their provided binaries as well as those from Homebrew don't show this in "preference"(?) for `bzip2`
On the other hand, MacPorts' `bzip2` also doesn't show when specified as a `depends_lib` (but `uv` binaries and those of Homebrew correctly link with the system's `bzip2`
Have you
> uv: Update to 0.8.0

- java/tomcat-native/Portfile
Update Tomcat Native to version 1.3.1
Have you
> tomcat-native: update to 1.3.1

- security/gitleaks/Portfile
gitleaks: Update to 8.28.0
Have you
> gitleaks: Update to 8.28.0

- comms/kermit-devel/Portfile
Update kermit-devel from @10.0-beta09_0 to @10.0-beta12_0.
Version @10.0-beta12_0 supports non standard UART speeds such as 1500000 used in Radxa Rock 3a board.
Have you
> kermit-devel: update to 10.0-beta12

- java/openjdk21-jetbrains/Portfile
Update to JetBrains Runtime 21.0.7b1038.58.
Have you
> openjdk21-jetbrains: update to 21.0.7b1038.58

- devel/legacy-support/Portfile
- Fixes 64-bit packet timestamps with unusual 10.4 SDK.
- Implements multiarch test runner.
Earlier notable -devel changes since v1.5.0:
- Fixes boottime sysctls for 64-bit <10.6
- Consequently undisables sleep offset on ppc64
- Fixes fcntl() F_GETPATH for 10.4 ppc64
- Fixes stat() et al tv_nsec for 10.4 ppc64
- Adds missing address validation for 10.4 stat64() calls.
- Makes all tests parallelizable.
- Fixes (Apple) [f]setattrlist() bug in 10.5-10.7.
Switches to built-in universal support for the -devel subport, while continuing to use muniversal for the main port.
TESTED:
Tested both normal and -devel versions -/+universal on 10.4-10.5 ppc, 10.4-10.5 ppc64, 10.4-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-15.x arm64.
Builds and …
> legacy-support-devel: Update to latest master - v20250720.

- java/openjdk17-microsoft/Portfile
Update to Microsoft OpenJDK 17.0.16.
Have you
> openjdk17-microsoft: update to 17.0.16

- java/openjdk17-temurin/Portfile
Update to Eclipse Temurin 17.0.16.
Have you
> openjdk17-temurin: update to 17.0.16

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 531.0.0.
Have you
> google-cloud-sdk: update to 531.0.0

- net/ncdc/Portfile
Add support for IP to country lookups through libloc Add location_db config option
Indicate GeoIP support in --version
macOS x.y
Have you
> ncdc: update to 1.25

- devel/liboqs/Portfile
> liboqs: update to 0.14.0

- gis/cgal6/Portfile
* Update CGAL 6.0 --> 6.0.1 (bugfix release).
* Update to cmake portgroup 1.1.
Have you
> cgal6: Update to 6.0.1

- devel/dagger/Portfile
Another day, another dagger version
Have you
> dagger: update to 0.18.14

- graphics/glfw/Portfile
macOS 13.7.6
Xcode 15.2 / Command Line Tools x.y.z
Have you
> glfw: Update to 3.4

- net/newsraft/Portfile
https://codeberg.org/newsraft/newsraft/releases/tag/newsraft-0.32
Xcode 14.2
Have you
> newsraft: update to 0.32

- gis/tippecanoe/Portfile
> tippecanoe: update to 2.79.0

- databases/redka/Portfile
https://github.com/nalgeon/redka/releases
Xcode 14.2
Have you
> redka: update to 0.6.0

- graphics/vtk/Portfile
* Livecheck: Avoid release candidates.
* Tested livecheck change only.  No other portfile changes.
Have you
> vtk: Livecheck avoid release candidates

- sysutils/ddrescueview/Portfile
- sysutils/ddrescueview/files/patch-deployment_target.patch
set deployment target
macOS x.y
Have you
> ddrescueview: use ld-classic on macOS 14 and later

- java/openjdk24-temurin/Portfile
Update to Eclipse Temurin 24.0.2.
Have you
> openjdk24-temurin: update to 24.0.2

- lang/groovy/Portfile
Update to Apache Groovy 4.0.28.
Have you
> groovy: update to 4.0.28

- java/openjdk21-openj9/Portfile
Update to IBM Semeru 21.0.8.
Have you
> openjdk21-openj9: update to 21.0.8

- java/openjdk17-openj9/Portfile
Update to IBM Semeru 17.0.16.
Have you
> openjdk17-openj9: update to 17.0.16

- java/openjdk8-openj9/Portfile
Update to IBM Semeru 8u462.
Have you
> openjdk8-openj9: update to 8u462

- java/openjdk11-openj9/Portfile
Update to IBM Semeru 11.0.28.
Have you
> openjdk11-openj9: update to 11.0.28

- devel/ruff/Portfile
Update `ruff` to its latest released version, 0.12.5
Have you
> ruff: Update to 0.12.5

- java/openjdk21-jetbrains/Portfile
Update to JetBrains Runtime 21.0.8b1038.68.
Have you
> openjdk21-jetbrains: update to 21.0.8b1038.68

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.5.4.
Have you
> spring-boot-cli: update to 3.5.4

- python/py-whenever/Portfile
Update to Whenever 0.8.8.
Have you
> py-whenever: update to 0.8.8

- net/youtube-dl/Portfile
yt-dlp: update to 2025.07.21
Have you
> yt-dlp: update to 2025.07.21

- net/gemget/Portfile
https://github.com/makew0rld/gemget/releases/tag/v1.9.0
Xcode 14.2
Have you
> gemget: update to 1.9.0

- science/gmsh/Portfile
- science/kicad/Portfile
- science/nektarpp/Portfile
Bump 3 dependents.
Skip deal.ii, currently does not build and needs update.
Have you
> Rev bump dependents for opencascade update

- editors/auctex/Portfile
* change maintainer to `nomaintainer`
* add **Obsolete port** to description
* change note to recommend auctex installation via ELPA/MELPA
Closes:  https://trac.macports.org/ticket/54841
Closes:  https://trac.macports.org/ticket/34846
Upstream developers of Auctex have changed the build process to presume exclusive installation via Gnu ELPA. While it is likely possible to replicate the steps via a Portfile, I personally lack the motivation and time to make that happen and maintain the Portfile with future releases.
Have you
> auctex:  mark as obsolete

- devel/cppcheck/Portfile
> cppcheck: update to 2.18.0

- x11/hamclock/Portfile
HamClock is a kiosk-style application that provides real time space weather, radio propagation models, operating events and other information particularly useful to the radio amateur.
https://clearskyinstitute.com/ham/HamClock/
Closes: https://trac.macports.org/ticket/72625
Thanks to @barracuda156 for setting up the initial Portfile.
macOS 13.7.6
Xcode 15.2
CL tools 15.1.0
Also tested on PowerPC.
Have you
> hamclock: New port

- devel/legacy-support/Portfile
- Fixes thread time bug on 10.10-10.11.
Earlier notable -devel changes since v1.5.0:
- Fixes boottime sysctls for 64-bit <10.6
- Consequently undisables sleep offset on ppc64
- Fixes fcntl() F_GETPATH for 10.4 ppc64
- Fixes stat() et al tv_nsec for 10.4 ppc64
- Adds missing address validation for 10.4 stat64() calls.
- Makes all tests parallelizable.
- Fixes (Apple) [f]setattrlist() bug in 10.5-10.7.
- Fixes 64-bit packet timestamps with unusual 10.4 SDK.
- Implements multiarch test runner.
TESTED:
Tested both normal and -devel versions -/+universal on 10.4-10.5 ppc, 10.4-10.5 ppc64, 10.4-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-15.x arm64.
Builds and passes all tests on all tested platforms, except expected 10.4 ppc64 test …
> legacy-support-devel: Update to latest master - v20250728.

- sysutils/netdata/Portfile
> netdata: update to 2.6.1

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 532.0.0.
Have you
> google-cloud-sdk: update to 532.0.0

- java/openjdk25-zulu/Portfile
Update to Azul Zulu 25.0.45.
Have you
> openjdk25-zulu: update to 25.0.45

- java/openjdk8-temurin/Portfile
Update to Eclipse Temurin 8u462.
Have you
> openjdk8-temurin: update to 8u462

- net/dante/Portfile
Update `dante` to its latest released version, 1.4.4
Have you
> dante: Update to 1.4.4

- devel/ldid-procursus/Portfile
Remove `compiler_blacklist_versions` PortGroup, as it's no longer necessary. [Compiler version comparisons Just Work now](https://lists.macports.org/pipermail/macports-dev/2025-July/046375.html)
Have you
> ldid-procursus: Remove `compiler_blacklist_versions`

- sysutils/colima/Portfile
colima: Update to 0.8.2
Have you
> colima: Update to 0.8.2

- audio/audacious-core/Portfile
- audio/audacious-core/files/patch-big-endian.diff
- audio/audacious-plugins/Portfile
- audio/audacious-plugins/files/patch-big-endian.diff
- audio/audacious/Portfile
> audacious: update to 4.5

- java/micronaut/Portfile
Update to Micronaut Starter 4.9.2.
Have you
> micronaut: update to 4.9.2

- sysutils/mise/Portfile
Update mise from 2025.7.32 to 2025.8.4
Have you
> mise: update to 2025.8.4

- python/py-virtualenv/Portfile
Command Line Tools 16.4.0.0.1.1747106510e
Have you
> py-virtualenv: update to 20.33.0

- python/py-tox/Portfile
The latest available version
Have you
> py-tox: update to 4.28.4

- devel/dprint/Portfile
- devel/dprint/files/rust_darwin.diff
Update `dprint` to its latest released version, 0.50.1
Have you
> dprint: Update to 0.50.1

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 533.0.0.
Have you
> google-cloud-sdk: update to 533.0.0

- sysutils/colima/Portfile
Update to colima 0.8.3.
Have you
> colima: update to 0.8.3

- net/lagrange/Portfile
https://github.com/skyjake/lagrange/releases/tag/v1.18.6
Xcode 14.2
Have you
> lagrange: update to 1.18.6

- graphics/ImageMagick7/Portfile
Update 7.1.1-47 --> 7.1.2-0
macOS 15.5
Xcode 16.2
Command Line Tools 16.2.0.
Have you
> ImageMagick7: Update to 7.1.2-0

- net/steampipe/Portfile
Update to the latest version of steampipe.
Have you
> steampipe: update to 2.1.0

- sysutils/colima/Portfile
Update to colima 0.8.4.
Have you
> colima: update to 0.8.4

- devel/gitui/Portfile
https://github.com/gitui-org/gitui/releases/tag/v0.27.0
Xcode 14.2
Have you
> gitui: update to 0.27.0

- security/sequoia-sq/Portfile
> sequoia-sq: Update to 1.3.1

- sysutils/fx/Portfile
https://github.com/antonmedv/fx/releases/tag/39.0.1
macOS 12.6.5 x86_64
Xcode 14.2
Have you
> fx: update to 39.0.1

- net/sshuttle/Portfile
https://github.com/sshuttle/sshuttle/releases/tag/v1.3.2
Xcode 14.2
Have you
> sshuttle: update to 1.3.2

- devel/libgphoto2/Portfile
* Comment update only.  No rev bump or testing.
* Anticipate upstream fix:  https://github.com/gphoto/libgphoto2/pull/1151
* Comment update only.  No testing needed.
Have you
> libgphoto2: Add portfile developer note

- lang/llvm-3.4/Portfile
- lang/llvm-3.4/files/regex_impl.h.patch
This is intended to fix the build on macOS 15 by applying an upstream patch that renames an include guard to avoid a conflict with the macOS SDK.
I haven't tested it locally besides verifying the patch applies. CI results are unlikely to be useful since the issue only affects macOS 15 and later and the port doesn't build on arm64 but CI only has arm64 runners for macOS 15.
Have you
> llvm-3.4: Fix build on macOS 15

- lang/tcl/Portfile
Avoid linking to MacPorts zlib opportunistically
Closes: https://trac.macports.org/ticket/71893
macOS 10.15
Have you
> tcl: use zlib from MacPorts

- net/youtube-dl/Portfile
yt-dlp: update to 2025.08.11
Have you
> yt-dlp: update to 2025.08.11

- sysutils/mise/Portfile
mise: Update to 2025.8.8
Have you
> mise: Update to 2025.8.8

- sysutils/resticprofile/Portfile
macOS 15.1 24B2083 arm64
Have you
> resticprofile: update to 0.31.0

- security/zizmor/Portfile
zizmor: Update to 1.12.1
Have you
> zizmor: Update to 1.12.1

- net/miniflux/Portfile
> miniflux: update to 2.2.11

- net/gallery-dl/Portfile
gallery-dl: update to 1.30.3
Have you
> gallery-dl: update to 1.30.3

- net/lagrange/Portfile
https://github.com/skyjake/lagrange/releases/tag/v1.18.7
Xcode 14.2
Have you
> lagrange: update to 1.18.7

- sysutils/simplotask/Portfile
> simplotask: update to 1.18.0

- sysutils/k9s/Portfile
Stealth update for 0.50.9: https://trac.macports.org/ticket/72837
Have you
> k9s: stealth update for 0.50.9

- www/lighttpd/Portfile
lighttpd: Update to 1.4.80
macOS 11.7
Have you
> lighttpd: Update to 1.4.80

- net/paho.mqtt.c/Portfile
- net/paho.mqtt.c/files/0001-Thread-fix-dispatch-usage-on-macOS.patch
- net/paho.mqtt.c/files/0002-Thread.c-fix-Availability-macros.patch
https://github.com/eclipse-paho/paho.mqtt.c/releases/tag/v1.3.15
cc @barracuda156 
Xcode 14.2
Have you
> paho.mqtt.c: update to 1.3.15

- graphics/clutter/Portfile
* Fix recent builds.
* Fixes: error: cogl/cogl-egl.h: No such file or directory
* Closes https://trac.macports.org/ticket/71653.
* Follows recommendation in that ticket.
Have you
> clutter: Disable EGL backend

- science/gmsh/Portfile
* Add legacy support for Darwin <= 15.
* Fixes builds for 10.9-10.11.
* Provide clock_gettime with CLOCK_MONOTONIC.
* No rev bump.  Build fixes only.
* CI only.  OS 13, 14, 15 only.
* Waiting for merge to check legacy build results.
Have you
> gmsh: Legacy support for 10.9-10.11

- _resources/port1.0/fetch/archive_sites.tcl
- _resources/port1.0/fetch/mirror_sites.tcl
The Johannesburg, South Africa mirror will stop working on September 10, 2025.
Have you
> Remove jnb.za.*.macports.org mirror

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 535.0.0.
Have you
> google-cloud-sdk: update to 535.0.0

- lang/kotlin/Portfile
Update to Kotlin 2.2.10.
Have you
> kotlin: update to 2.2.10

- x11/hamclock/Portfile
> hamclock: Fix livecheck

- science/giza/Portfile
Update giza 1.4.1 --> 1.5.0
Have you
> giza: Update to 1.5.0

- sysutils/netdata/Portfile
> netdata: update to 2.6.2

- python/py-elastic-transport/Portfile
- python/py-elasticsearch/Portfile
The ports py-elasticsearch and it's accompanying dependency py-elastic-transport are very outdated. This updates both to the latest version.
Have you
> py-elasticsearch and py-elastic-transport: update to 9.1.0

- sysutils/bfs/Portfile
> bfs: update to 4.1

- net/youtube-dl/Portfile
> yt-dlp: Update to 2025.08.20

- textproc/jaq/Portfile
> jaq: Update to 2.3.0

- sysutils/mise/Portfile
mise: Update to 2025.8.20
Have you
> mise: Update to 2025.8.20

- security/pinact/Portfile
pinact: Update to 3.4.2
Have you
> pinact: Update to 3.4.2

- net/gallery-dl/Portfile
gallery-dl: update to 1.30.5
Have you
> gallery-dl: update to 1.30.5

- python/py-markdown2/Portfile
Update to 2.5.4, add subport for Python 3.13.
Have you
> py-markdown2: update to 2.5.4, add Python 3.13 subport

- devel/lychee/Portfile
lychee: Update to 0.20.0
Have you
> lychee: Update to 0.20.0

- editors/emacs/Portfile
- editors/emacs/files/site-start-app.el
Set lexical binding cookie in `site-start.el` to prevent a warning (in emacs{,app}-devel) about missing cookie. Also relevant for Emacs 30.x; but here the user does not get the warning about the missing cookie.
Have you
> emacs{,-app}-devel: set lexical binding, update to 20250816

- devel/radlib/Portfile
- devel/radlib/files/implicit.patch
Closes: https://trac.macports.org/ticket/70407
Have you
> radlib: Fix build failures

- net/munge/Portfile
- net/munge/files/libmissing.patch
Closes: https://trac.macports.org/ticket/72860
Have you
> munge: Update to 0.5.16

- java/jarviz/Portfile
New port for [jarviz](https://github.com/kordamp/jarviz).
Have you
> jarviz: new submission

- emulators/blink/Portfile
- emulators/blink/files/patch-f-dupfd-cloexec.diff
> blink: re-fix build on macOS <10.12 and >13

- sysutils/simplotask/Portfile
https://github.com/umputun/spot/releases/tag/v1.19.0
Xcode 14.2
Have you
> simplotask: update to 1.19.0

- mail/aerc/Portfile
[Changelog](https://git.sr.ht/~rjarry/aerc/refs/0.21.0)
macOS 12.6.5 x86_64
Xcode 14.2
Have you
> aerc: update to 0.21.0

- science/cdo/Portfile
- science/cdo/files/patch-cdo-missing-strings-h.diff
Fixes https://trac.macports.org/ticket/72890
Fixes https://trac.macports.org/ticket/72909
This attempts to fix:
* https://trac.macports.org/ticket/72890 by reducing the scope of the clang blacklisting, eventually removing it in its entirety.
* https://trac.macports.org/ticket/72909 by fixing a bug in the latest cdo source code
In addition an upstream stealth update to v2.5.3 is now used.
macOS 15.6.1 24G90 x86_64
Have you
> cdo: remove blacklisting and fix bug

- net/regclient/Portfile
Created with [seaport](https://seaport.rtfd.io/), the modern MacPorts portfile updater.
macOS 15.6.1 24G90
Have you
> regclient: update to 0.9.2

- ruby/ruby-build/Portfile
ruby-build: Update to 20250829
Have you
> ruby-build: Update to 20250829

- textproc/tabiew/Portfile
https://github.com/shshemi/tabiew/releases/tag/v0.11.1
Xcode 14.2
Have you
> tabiew: update to 0.11.1

- sysutils/mise/Portfile
mise: Update to 2025.8.21
Have you
> mise: Update to 2025.8.21

- editors/neovim/Portfile
- update neovim to 0.11.4
- update neovim-devel to 20250901
Have you
> neovim, -devel: update to 0.11.4 and 20250901

- science/asco/Portfile
asco: fix build on Sequoia
Have you
> asco: fix build on Sequoia

- graphics/osxphotos/Portfile
Update to osxphotos 0.72.3.
Have you
> osxphotos: update to 0.72.3

- python/poetry/Portfile
- python/py-poetry-core/Portfile
I had removed python 3.9 earlier in the year when certain bugs in the Python portgroup were preventing the new dependencies from building on 3.9. However, now that we are months away from 3.9 being EOL forever I lean towards just removing 3.9 support.
Have you
> poetry: update to 2.1.4

- python/py-findpython/Portfile
> py-findpython: update to 0.7.0

- science/gildas/Portfile
> Gildas: update to 202509a

- graphics/ImageMagick7/Portfile
Update 7.1.2-1 --> 7.1.2-3
Have you
> ImageMagick7: Update to 7.1.2-3

- security/libfido2/Portfile
This PR updates libfido2 from version 1.15.0 to 1.16.0.
libfido2 provides library functionality and command-line tools to communicate with a FIDO device over USB, and to verify attestation and assertion signatures.
* Update to version 1.16.0
* Update maintainer email address
**Tested on**
macOS 15.6.1 Xcode 16.4 / Command Line Tools 16.4.0.0.1.1747106510 (arm64)
macOS 15.6.1 Command Line Tools 16.4.0.0.1.1747106510 (x86_64)
- **Category**: security
- **Version**: 1.16.0 (updated from 1.15.0)
- **Homepage**: https://github.com/Yubico/libfido2
- **License**: BSD
- **Dependencies**: mandoc, pkgconfig, libcbor, openssl
@trodemaster (openmaintainer)
> libfido2: update to 1.16.0

- sysutils/tenv/Portfile
Created with [seaport](https://seaport.rtfd.io/), the modern MacPorts portfile updater.
macOS 15.6.1 24G90
Have you
> tenv: update to 4.7.21

- devel/oxker/Portfile
https://github.com/mrjackwills/oxker/releases/tag/v0.11.0
Xcode 14.2
Have you
> oxker: update to 0.11.1

- graphics/pngcheck/Portfile
Update pngcheck to 4.0.0 and switch to new upstream. [pngcheck's homepage contains a "Change of Address" note](https://www.libpng.org/pub/png/apps/pngcheck.html) that points to the new upstream.
Have you
> pngcheck: Update to 4.0.0

- graphics/opencv4/Portfile
- graphics/opencv4/files/patch-ffmpeg8.diff
ffmpeg-devel has moved to ffmpeg 8.0, which breaks the current opencv4 build. This patch is copied from an upcoming opencv change (post 4.12) to fix macports opencv (currently still on 4.9)
Have you
> opencv4: fix ffmpeg8 builds

- gis/geographiclib/Portfile
https://github.com/geographiclib/geographiclib/blob/main/NEWS
Xcode 14.2
Have you
> geographiclib: update to 2.5.2

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 537.0.0.
Have you
> google-cloud-sdk: update to 537.0.0

- devel/cmake-devel/Portfile
> cmake-devel: update to 4.1.1

- textproc/lowdown/Portfile
lowdown: update to 2.0.2
* Use `bmake` to build instead of `make` (starting upstream v1.4.0)
* Clean up Portfile
Have you
> lowdown: update to 2.0.2

- science/freehdl/Portfile
- science/freehdl/files/patch-freehdl_kernel-db_hh.diff
freehdl: fix build on Sequoia
Have you
> freehdl: fix build on Sequoia

- net/htpdate/Portfile
Update htpdate to 2.0.0 and switch to new upstream.
Have you
> htpdate: Update to 2.0.0

- lang/racket/Portfile
- lang/racket/files/paths-to-openssl.diff
This PR builds the full racket system per https://github.com/racket/racket/issues/5055#issuecomment-2321445579, and fixes the issue of unsigned `arm64` binaries.
There is the remaining issue that calling the GUI fails with the cause apparently being uninitialized variables: "`invalid memory reference`").
If anyone knows how to set defaults at compile time or in a config file, please post.
Here's the issue:
> ```sh
> $ drracket -display=0:0
> invalid memory reference.  Some debugging context lost
>   context...:
>    body of "/opt/local/share/racket/pkgs/gui-lib/mred/private/wx/gtk/style.rkt"
>   body of "/opt/local/share/racket/pkgs/gui-lib/mred/private/wx/platform.rkt"
> ```
Using trace with `(require racket/gui)` shows that the variables `has-x-selection?`, `cursor-driver%`, and so …
> racket: Update to version 8.18; Use full Racket source with native apps

- textproc/bstring/Portfile
This PR adds a new port for bstring version 1.0.1 to the textproc category.
The Better String Library for C - a fork of Paul Hsieh's Better String Library providing comprehensive string functions for C programming with improved memory safety and performance.
* Comprehensive string manipulation functions
* Safer memory handling than standard C strings
* Improved performance over traditional string operations
* Enhanced API for modern C development
**Tested on**
macOS 15.6.1 Xcode 16.4 / Command Line Tools 16.4.0.0.1.1747106510 (arm64)
macOS 15.6.1 Command Line Tools 16.4.0.0.1.1747106510 (x86_64)
- **Category**: textproc
- **Version**: 1.0.1
- **Homepage**: https://github.com/msteinert/bstring
- **License**: BSD
- **Dependencies**: pkgconfig, autoconf, automake, libtool, check
@trodemaster …
> bstring: new port, version 1.0.1

- python/py-pyside6/Portfile
> py-pyside6: update to version 6.9.2

- audio/portmidi/Portfile
> portmidi: update to 2.0.6

- net/syncthing-macos/Portfile
- net/syncthing-macos/files/patch-disable-autoupdatechecks.diff
- net/syncthing-macos/files/patch-no-bundled-syncthing.diff
syncthing-macos: update to v2.0.3+1
* fixes incompatibility with syncthing version 2
* updated patchfiles
Have you
> syncthing-macos: update to v2.0.3+1

- net/gallery-dl/Portfile
gallery-dl: update to 1.30.6
Have you
> gallery-dl: update to 1.30.6

- java/async-profiler/Portfile
macOS 14.7.8 23H730 arm64
Have you
> async-profiler: update to 4.1

- sysutils/mise/Portfile
mise: Update to 2025.9.5
Have you
> mise: Update to 2025.9.5

- textproc/bstring/Portfile
This PR updates the bstring port to version 1.0.2 and fixes a documentation installation issue.
bstring is a fork of Paul Hsieh's Better String Library. It provides a comprehensive string library for C with features like autotools build system, updated test suite based on Check, Valgrind integration, and continuous integration via GitHub Actions.
* update to version 1.0.2
* fix documentation installation in post-destroot
* update checksums for new version
**Tested on**
macOS 15.6.1 Xcode 16.4 / Command Line Tools 16.4.0.0.1.1747106510 (arm64)
- **Category**: textproc, devel
- **Version**: 1.0.2
- **Homepage**: https://github.com/msteinert/bstring
- **License**: BSD
- **Dependencies**: pkgconfig
@trodemaster (openmaintainer)
> bstring: update to 1.0.2

- devel/cproto/Portfile
> cproto: update to 4.7y

- ruby/ruby-build/Portfile
ruby-build: Update to 20250908
Have you
> ruby-build: Update to 20250908

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 538.0.0.
Have you
> google-cloud-sdk: update to 538.0.0

- lang/kotlin/Portfile
Update to Kotlin 2.2.20.
Have you
> kotlin: update to 2.2.20

- sysutils/kubie/Portfile
kubie: Update to 0.26.0
Have you
> kubie: Update to 0.26.0

- devel/gitu/Portfile
Update `gitu` to its latest released version, 0.35.0
Have you
> gitu: Update to 0.35.0

- shells/fish/Portfile
fish: update to 4.0.6
Have you
> fish: update to 4.0.6

- net/gallery-dl/Portfile
gallery-dl: update to 1.30.7
Have you
> gallery-dl: update to 1.30.7

- security/oath-toolkit/Portfile
update oath-toolkit to 2.6.13
Have you
- n/a: tried a full install with `sudo port -vst install`?
> update to oath-toolkit: 2.6.13

- java/openjdk25-zulu/Portfile
Update to Azul Zulu 25.28.85.
Have you
> openjdk25-zulu: update to 25.28.85

- java/openjdk25-graalvm/Portfile
New port for GraalVM Community Edition 25.
Have you
> openjdk25-graalvm: new submission

- java/openjdk24-graalvm/Portfile
GraalVM Community Edition 24 has reached end of life.
> openjdk24-graalvm: mark as EOL

- devel/openssl/Portfile
- devel/openssl3/Portfile
- net/openssh/Portfile
- sysutils/freeradius/Portfile
> openssl3: Update to 3.5.3

- lang/zig/Portfile
Update minimum OS version to macOS 13 Ventura. https://ziglang.org/download/0.15.1/release-notes.html#OS-Version-Requirements mentions this as the minimum version, which is confirmed by builds indeed failing on macOS 12 and older in the [Port Health](https://ports.macports.org/port/zig/details/) overview.
> zig: update minimum OS version

- irc/weechat/Portfile
- irc/weechat/files/no-extra-gcc-warnings.patch
weechat: update to 4.7.1
* no-extra-gcc-warnings.patch: update patch to work with a newer file from upstream
Have you
> weechat: update to 4.7.1

- ruby/ruby-build/Portfile
ruby-build: Update to 20250916.1
Have you
> ruby-build: Update to 20250916.1

- sysutils/neofetch/Portfile
* package is no longer maintained upstream
* removing myself as port maintainer
macOS 13.7.8
Xcode 15.2 / Command Line Tools 15.1.0.0.1.1700200546
Have you
> neofetch: marking deprecated

- archivers/lzma/Portfile
> lzma: update to 25.01

- java/openjdk25-corretto/Portfile
Update to Amazon Corretto 25.0.0.36.2.
Have you
> openjdk25-corretto: update to 25.0.0.36.2

- graphics/wxWidgets-3.0/Portfile
- graphics/wxWidgets-3.0/files/patch-libpng.diff
- Backport a libpng patch. https://github.com/pnggroup/libpng/commit/893b8113f04d408cc6177c6de19c9889a48faa24
- Don’t link against the AGL framework, removed from the macOS 26 SDK. https://developer.apple.com/documentation/macos-release-notes/macos-26-release-notes#AGL
Have you
> wxWidgets-3.0: support macOS 26

- graphics/wxWidgets-3.2/Portfile
- graphics/wxWidgets-3.2/files/dd3f2509499e0e6aac4ebf8dab72b5d496c5bfbc.patch
AGL framework was removed from macOS, but it was apparently not needed anyway. Backport an upstream patch that removes it.
Have you
> wxWidgets-3.2: Fix build on macOS 26

- www/hugo/Portfile
hugo: update to 0.150.0
Have you
> hugo: update to 0.150.0

- lang/algol68g/Portfile
- lang/algol68g/files/0006-Fix-endianness-includes-and-macros.patch
* Update algol68g 3.7.7 --> 3.9.5.
* Update 1 patch file with 2 changed patch hunks.
* Fix livecheck.
Have you
> algol68g: Update to 3.9.5

- java/plantuml/Portfile
> plantuml: update to 1.2025.7

- cross/bossa/files/patch-Makefile
bossa makes use of variable-length arrays in C++ code, which now trigger -Wvla-cxx-extension warnings at -Wall under Xcode 26 clang (https://github.com/llvm/llvm-project/commit/7339c0f782d5c70e0928f8991b0c05338a90c84c). Remove -Werror to prevent these variable-length arrays from breaking the bossa build with this newer compiler.
Have you
> bossa: support macOS 26

- _resources/port1.0/group/gobject_introspection-1.0.tcl
Fixes universal builds of meson-based projects that depend on gobject-introspection
Note: The fix sets env variables instead of appending to the command line for meson, since ninja doesn't support `VAR+=append` syntax.  This overwrites the environment variable if it already existed, but hopefully overriding cflags/ldflags for builds isn't too common.
Have you
> gobject_introspection: Fix meson universal builds

- aqua/qt5/Portfile
- aqua/qt5/files/patch-qtbase-icu-cxx11.diff
- aqua/qt5/files/patch-qtbase-tahoe-no-agl-framework.diff
AGL.framework no longer exists, but is apparently also not needed — just remove it on Tahoe and above.
Additionally, the configure test for ICU fails because ICU now required C++17, but the config test did not pass the required flag. Some attempts seem to have been made to fix this, but they weren't sufficient in my testing unless the qmake project file also declared 'CONFIG += c++11'. Add a patch that does that.
Closes: https://trac.macports.org/ticket/72729
Have you
> qt5-qtbase: Fix build on macOS 26

- net/knot-resolver/Portfile
- net/knot/Portfile
- net/knot/files/patch-for-macos-10.11-and-older.diff
> knot, libknot, knot-resolver: fix build on macOS >=10.7 and =<10.13

- science/splash/Portfile
* Blacklist 10.7 Xcode clang, fix "invalid instruction mnemonic cvtsi2sdl".
* No rev bump. Build fix only.
Have you
> splash: Fix build for 10.7

- java/spring-boot-cli/Portfile
Update to Spring Boot CLI 3.5.6.
Have you
> spring-boot-cli: update to 3.5.6

- sysutils/k9s/Portfile
Update to k9s 0.50.12.
Have you
> k9s: update to 0.50.12

- net/lft/Portfile
- net/lft/files/lft_types.h.patch
lft: Fix build failure on macOS 26
Closes: https://trac.macports.org/ticket/72989
Have you
> lft: Fix build failure on macOS 26

- python/py-zipfile-deflate64/Portfile
- python/py-zipfile-deflate64/files/patch-zlib.diff
This adapts https://github.com/madler/zlib/commit/4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9 (2024-01-14), which appeared in zlib 1.3.1 (2024-01-22), to the snapshot of zlib in zipfile-deflate64 0.2.0 (2022-01-05). This zlib snapshot is based on zlib 1.2.11 (2017-01-15).
This patch is necessary for compatibility with the Clang compiler in Xcode ≥ 16.3: TARGET_OS_MAC as it was used in zutil.h intends to refer to the Classic Mac OS. This macro has long been defined by the macOS SDK to mean modern macOS, but was only defined by <TargetConditionals.h>, which was not ordinarily https://github.com/llvm/llvm-project/commit/6e1f19168bca7e3bd4eefda50ba03eac8441dbbf (2023-12-07, in upstream Clang 18.1, 2024-01-29, and in Xcode 16.3, 2025-03-31) now has the compiler itself defining this macro …
> py-zipfile-deflate64: Xcode ≥ 16.3 compatibility

- shells/fish/Portfile
fish: update to 4.0.8
Have you
> fish: update to 4.0.8

- java/mvnd1/Portfile
Update to Maven Daemon 1.0.3.
Have you
> mvnd1: update to 1.0.3

- lang/zig/Portfile
- lang/zig/files/patch-duplicate-LC_RPATH.diff
Fix 'duplicate LC_RPATH' error using patch from https://github.com/ziglang/zig/pull/25152.
Have you
> zig: fix duplicate LC_RPATH

- audio/aacgain/Portfile
clang tries to compile this with C++11, resulting in compilation errors, e.g.
```
:info:build atom_standard.cpp:25:28: error: constant expression evaluates to 169 which cannot be narrowed to type 'char' [-Wc++11-narrowing]
:info:build    25 | static const char name[5]={0251,'n', 'a', 'm', '\0'};
:info:build       |                            ^~~~
```
Switching to older C++ standard resolves the issue
Have you
> aacgain: fix compile on Tahoe (MacOS 26)

- devel/xeus-zmq/Portfile
> xeus-zmq: fix build on macOS >=10.7 and =<10.12

- graphics/xvega/Portfile
> xvega: fix build on macOS <10.13

- devel/the_Foundation/Portfile
- net/lagrange/Portfile
https://github.com/skyjake/lagrange/releases/tag/v1.19.2
https://git.skyjake.fi/skyjake/the_Foundation/releases/tag/v1.10.1
Xcode 14.2
Have you
> lagrange: update to 1.19.2

- sysutils/simplotask/Portfile
https://github.com/umputun/spot/releases/tag/v1.19.1
Xcode 14.2
Have you
> simplotask: update to 1.19.1

- net/miniflux/Portfile
> miniflux: update to 2.2.13

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.14.2

- llm/ramalama/Portfile
ramalama didn't declare a dependency on it, and fails to run without it.
Fixes: fee5ad975bfe1238e37ecae4abc08d3885798e68
Fixes: #29461
Have you
> ramalama: Add missing py-yaml dependency

- _resources/port1.0/group/crossbinutils-1.0.tcl
Add latest version 2.45 to crossbinutils
Have you
> Add version 2.45 to crossbinutils

- java/openjdk25-temurin/Portfile
New port for Eclipse Temurin based on OpenJDK 25.
Have you
> openjdk25-temurin: new port

- java/openjdk25-microsoft/Portfile
New port for Microsoft Build of OpenJDK 25.
Have you
> openjdk25-microsoft: new port

- python/py-matplotlib/Portfile
https://github.com/macports/macports-ports/commit/91dc01dadd6b14d05a84ac7d0aad1b3 removed the 'qt4' and 'pyside' variants, but there are still some references to them that should be removed as well.
Have you
> py-matplotlib: removed references to missing variants

- cross/x86_64-binutils/Portfile
x86_64-binutils: Update to 2.45 and add targets haiku and solaris
Have you
> x86_64-binutils: Update to 2.45 and add targets haiku and solaris

- sysutils/k9s/Portfile
Update to k9s 0.50.13.
Have you
> k9s: update to 0.50.13

- math/igraph/Portfile
- python/py-igraph/Portfile
> igraph: update to 1.0.0

- math/BRiAl/Portfile
Have you
Thanks @barracuda156 here is the non-draft PR.
> BRiAl: update to 1.2.14

- devel/oxker/Portfile
https://github.com/mrjackwills/oxker/releases/tag/v0.12.0
Xcode 14.2
Have you
> oxker: update to 0.12.0

- shells/fish/Portfile
fish: update to 4.1.0
Have you
> fish: update to 4.1.0

- java/openjdk25/Portfile
New port for OpenJDK 25.
Xcode 26.1 17B5025f
Have you
> openjdk25: new port

- science/hamlib/Portfile
Update to 4.6.5
Added support for Python 3.13
Closes: https://trac.macports.org/ticket/72282
Have you
> hamlib: update to 4.6.5

- sysutils/freeipmi/Portfile
new port: FreeIPMI 1.6.15
Have you
- n/a: tried a full install with sudo port -vst install? (broken on Sequoia [#66358](https://trac.macports.org/ticket/66358))
> submission: FreeIPMI: version 1.6.15

- net/picotls/Portfile
- net/picotls/files/patch-aligned_alloc.diff
> picotls: update, disable mbedtls, fix test

- lang/antlr/Portfile
* antlr:  Remove noarch.  Was inserted by mistake in previous PR.
* This is critical, to prevent wrong arch files being provided on OS versions supporting dual arch types.
Have you
> antlr: Fix mistake, remove noarch

- devel/openssl/Portfile
- devel/openssl3/Portfile
- net/openssh/Portfile
- sysutils/freeradius/Portfile
Upstream advisory at:
https://openssl-library.org/news/secadv/20250930.txt
CVE: CVE-2025-9230
CVE: CVE-2025-9231
CVE: CVE-2025-9232
Have you
> openssl3: Update to 3.5.4

- shells/fish/Portfile
fish: update to 4.1.1
macOS 15.7.1 24G231 arm64
Have you
> fish: update to 4.1.1

- net/arpwatch/Portfile
- net/arpwatch/files/_getshort.patch
Closes: https://trac.macports.org/ticket/73043
but notably not tested on a version affected by the problem (e.g. macOS 26).
Have you
> arpwatch: Attempt to fix build with macOS 26 SDK

- devel/lychee/Portfile
lychee: Update to 0.20.1
Have you
> lychee: Update to 0.20.1

- java/openjdk21-jetbrains/Portfile
Update to JetBrains Runtime 21.0.8-b1140.54.
Xcode 26.1 17B5025f
Have you
> openjdk21-jetbrains: update to 21.0.8-b1140.54

- java/openjdk25/Portfile
- java/openjdk25/files/non-reproducible.diff
Build without `-reproducible` linker flag on macOS 12 and older, because it doesn't seem to be supported on those OS versions.
> openjdk25: build without -reproducible flag on macOS 12 and older

- devel/legacy-support/Portfile
Notable functional changes since v1.5.1:
- Updates headers for macOS 26 SDK.
Also switches `github.tarball_from` to `archive` for the release version.
Closes: https://trac.macports.org/ticket/72738
TESTED:
Tested both normal and -devel versions -/+universal on 10.4-10.5 ppc, 10.4-10.5 ppc64, 10.4-10.6 ppc (i386 Rosetta), 10.4-10.6 i386, 10.4-12.x x86_64, and 11.x-26.x arm64.
Builds and passes all tests on all tested platforms.
```
Mac OS X 10.4.11 8S165, ppc, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S165, ppc64, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, ppc (i386 Rosetta), Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, ppc, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, ppc64, Xcode 3.1.4 9M2809
Mac OS X …
```
> legacy-support: Update to v1.5.2.

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.15.0

- games/ctris/Portfile
- games/ctris/files/patch-version.diff
Have you
When ran the version is shown 0.42 but is 0.43 (https://github.com/0xminik/ctris/pull/4)
> ctris: update to v0.43

- net/lagrange/Portfile
https://github.com/skyjake/lagrange/releases/tag/v1.19.3
Xcode 14.2
Have you
> lagrange: update to 1.19.3

- gis/osm2pgsql/Portfile
https://github.com/osm2pgsql-dev/osm2pgsql/releases/tag/2.2.0
Xcode 14.2
Have you
> osm2pgsql: update to 2.2.0

- audio/libsidplayfp/Portfile
- audio/libsidplayfp/files/patch-fix-pre-cxx20.diff
> libsidplayfp: fix build with C11 compilers

- devel/fossil/Portfile
Fix spelling in notes
https://fossil-scm.org/forum/info/1c824e3299
macOS 10.15
Command Line Tools 12.4
Have you
> fossil: update to 2.27

- sysutils/macos-trash/Portfile
> macos-trash: Update to 2.0.0

- devel/jsoncons/Portfile
https://github.com/danielaparker/jsoncons/releases/tag/v1.4.2
Xcode 14.2
Have you
> jsoncons: update to 1.4.2

- mail/cclient/Portfile
- mail/cclient/files/scandir.patch
modified:   mail/cclient/Portfile
new file:   mail/cclient/files/scandir.patch
fixes: https://trac.macports.org/ticket/71181
```
Model Identifier: Macmini6,1                Model Identifier: MacPro5,1                 
macOS 10.15.7 19H2026 x86_64                macOS 14.7.7 23H723 x86_64                  
Xcode 12.4 12D4e                            Xcode 16.2 16C5032a                         
Command Line Tools 12.4.0.0.1.1610135815    Command Line Tools 16.2.0.0.1.1733547573    
```
Have you
> cclient: fix for changed definiton of scandir

- devel/symfony-cli/Portfile
> symfony-cli: update to 5.15.1

- net/gallery-dl/Portfile
gallery-dl: update to 1.30.9
macOS 15.7.1 24G231 arm64
Have you
> gallery-dl: update to 1.30.9

- science/ecCodes/Portfile
Simple update to upstream version 2.44.0
macOS 15.7.1 24G231 x86_64
Have you
> ecCodes: update to 2.44.0

- databases/mysql56/Portfile
Fixes: https://trac.macports.org/ticket/71801
macOS 10.15
Command Line Tools 12.4
Have you
Only tested through build phase.
> mysql56: force pre-2017 C++ standard

- llm/gemini-cli/Portfile
New port for [gemini-cli](https://google-gemini.github.io/gemini-cli/).
Have you
> gemini-cli: new port

- devel/google-cloud-sdk/Portfile
Update to Google Cloud SDK 542.0.0.
Have you
> google-cloud-sdk: update to 542.0.0

- sysutils/k9s/Portfile
Update to k9s 0.50.15.
Have you
> k9s: update to 0.50.15
